microsoft/MixedRealityToolkit-Unity

Assets/HoloToolkit/Input/GestureManager.cs

Adds a property to GestureManager to address Issue #9

Added FocusedObject property

---

Assets/HoloToolkit/Input/Scripts/CursorManager.cs
Assets/HoloToolkit/Input/Scripts/GazeManager.cs
Assets/HoloToolkit/Input/Scripts/GestureManager.cs
Assets/HoloToolkit/Input/Scripts/HandsManager.cs
Assets/HoloToolkit/Input/Scripts/KeywordManager.cs
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMappingManager.cs
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs
Assets/HoloToolkit/SpatialSound/UAudioManager.cs
Assets/HoloToolkit/SpatialSound/UAudioManagerBase.cs
Assets/HoloToolkit/SpatialSound/UAudioMiniManager.cs

added partial to all top level manager classes, resolves Microsoft/HoloToolkit-Unity#7

added partial to all top level manager classes

---

Assets/HoloToolkit/Input/Scripts/GazeManager.cs

By adding the SetFocusPointForFrame to the GazeManager, we will help
stabilize the hologram the user is currently gazing at.
https://github.com/Microsoft/HoloToolkit-Unity/issues/18

Add SetFocusPointForFrame stability plane to GazeManager

---

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs
Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs.meta
Assets/HoloToolkit/SpatialMapping/Tests/TapToPlace.unity
Assets/HoloToolkit/SpatialMapping/Tests/TapToPlace.unity.meta
README.md

Adding TapToPlace script which helps place an object on a real surface.
Closes #17

Adding TapToPlace

---

Assets/HoloToolkit/SpatialMapping/Scripts/PlaneFinding.cs
Assets/HoloToolkit/SpatialMapping/Scripts/SurfacePlane.cs

Added method BoundedPlane to build from Transform.
In SurfacePlane Awake, set plane to BoundedPlane from self transform.
In SurfacePlane Start, update the surface plane.
Note that UpdateToSurface is delayed until start so that SurfaceMeshesToPlanes.Instance can be initialized by the it's Awake call. Setting the plane must happen in Awake so that modifications when instantiated dynamically aren't overwritten.

Fixed SurfacePlane functionality in Editor

---

Assets/HoloToolkit/Input/Scripts/GazeStabilizer.cs

A queue's ElementAt method iterates internally until it reaches element i. Calling this multiple times within a for loop is very slow.  This commit changes the Queue to a List so that it can iterate more quickly.

GazeStabilizer Optimization

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/SpatialMappingRenderer.cs

It seems like some materials got moved and this script wasn't updated to the new location

BUG FIX: SpatialMappingRenderer.cs referenced materials in the wrong location

---

Assets/HoloToolkit/SpatialMapping/Editor/SpatialMappingRendererInspector.cs
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/SpatialMappingRenderer.cs
README.md

Spatial Mapping renders Hot Pink because it uses Resources.Load to load
materials that do not exist under a resources folder. This change will
still require that the user set the occlusion and render materials
directly (or else they'll see hot pink), but now exposes the 'Occlusion
Material' as a property that can be set in the Inspector.

Exposing occlusion material to address issue #58

---

Assets/HoloToolkit/Utilities/Scripts/ManualCameraControl.cs

exposing them to the editor for non- standard unity input configuration. 
The right thumb stick will need to have axes created in Project Settings -> Input in unity to work correctly.
Due to Hololens unique nature, none of my projects have had the standard input setup so far. Putting in this class would, at least temporarily break things. These changes mostly fix that issue.

Changed Input Axes strings  to variables

---

Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs

Will likely be wired up to a configuration option when HTTPS support is implemented, so makes more sense as a property.

Resolve LocalIPsOnly warning (fixes #101)

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs

This change allows applications do defer starting the spatial mapping observer rather than have it immediately start.
Also moved the stored mesh loading logic from Start() to StartObserver() and added an #if !UNITY_EDITOR block around the code in StopObserver() for balance.

add autoStartObserver to SpatialMappingManager

---

Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs

Having spaces in your solution's directory resulted in MSBuild Error (Code = 1) when building your appx. Enclosed the path in escaped quotes to resolve the issue.

Fix for MSBuild .sln path argument to allow for directories with spaces.

---

Assets/HoloToolkit/Build/Editor/BuildDeployPortal.cs

Switched to using the app name (rather than package name) when looking for the app in the app list (if the package name didn't contain the app name, this would fail - this is a more correct way to do it)

Build window - fix for potential install/launch issue

---

Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs
Assets/HoloToolkit/Build/Editor/BuildSLNUtilities.cs

When building an app from unity it's possible to have multiple scenes in
the build window, but only have one scene enabled. Unity only includes the
enabled scenes, see https://docs.unity3d.com/Manual/BuildSettings.html.
Have HoloToolkit build window match this behavior.

Build only enabled scenes when using "Build Visual Studio SLN" button in Build Window

---

Assets/HoloToolkit/Sharing/Editor/SharingMenu.cs

Scenario: Developer copies the cloned HoloTookit files into their own
project and External folder gets left behind. Even if they use a unity
package, the Externals folder is not part of that package.
Fix: Log an error when the files are not found in the expected path.
Fixes HoloToolkit-Unity GitHub issue #135

Log error when Sharing binaries are not found in the External folder 

---

Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs
Assets/HoloToolkit/Build/Editor/XdeGuestLocator.cs

- Added XDE detection and GUI element to support picking localhost/emulator options, without sacrificing the undocumented/unsupported non-local-ip mode. Just in case some folks are using it.
- Adjusted copyright as it was incorrect (and included obsolete 'all rights reserved' silliness). This code was originally provided by @jevertt with my modifications added. No transfer of copyright occurred and we maintain our rights in alignment with CLA. (@jevertt, let me know if you want your full name in there instead. It would certainly look nicer.)
OnGui cleanup is needed; will submit a future PR for that.

Added xde detection/deployment (fixes #149)

---

Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs

- Build window GUI could become permanently disabled if xde locator was not searching and did not have previous scan data (e.g. very first run through).
- Renamed some locals for clarity

BuildWindow GUI state bugfix

---

Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs

Camera background color to RGBA 0,0,0,0. But "Apply HoloLens Scene Settings" is black(0,0,0,1)
It was changed from black to clear.
https://developer.microsoft.com/en-us/windows/holographic/unity_development_overview#configuring_a_unity_project_for_hololens

Change camera backgorund color

---

Assets/HoloToolkit/Build/Editor/BuildDeployPrefs.cs
Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs
Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs

- Add checkbox "Increment version" in build window
- If checked, build a new appx, incrementing the last number in
Major.Minor.Build.Revision. Example: 1.0.0.3 => 1.0.0.4
This can be useful for easily checkpointing your work, especially when
you're actively working on something and somebody asks for a demo it's
easy to just install an older version.

Build Window - Add option to auto-increment appx version

---

Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs

If we press "Build SLN, Build APPX, then Install" and we are incrementing
the appx version on every build, we end up installing the _second to last_
build instead of the _most recent build_ because we are not updating the
list of builds in BuildDeployWindow.CalcMostRecentBuild. Fix this.

bug fix - Update builds before computing most recent build

---

Assets/HoloToolkit/Utilities/Prefabs/FPSDisplay.prefab

Prefab did not work well due to camera being used in screen space for the UI Text. 
Changed the UI Text camera to render in world space.
Also scale did not work great so fixed that too.
Added SimpleTagAlong and BillBoard to have the FPS counter follow along as we gaze around in the world.

Fixing FPSDisplay prefab to work better with tagalong and world space camera for UI Text

---

Assets/HoloToolkit/Input/README.md
Assets/HoloToolkit/Input/Scripts/GestureManager.cs
Assets/HoloToolkit/Input/Scripts/GestureManipulator.cs
Assets/HoloToolkit/Input/Scripts/GestureManipulator.cs.meta
Assets/HoloToolkit/Input/Tests/GestureManipulator.unity
Assets/HoloToolkit/Input/Tests/GestureManipulator.unity.meta

Holograms 211 contains a relatively simple implementation of hand based
object manipulation.  That implementation uses the world space deltas
to move holograms exactly as the hand moves.  This works fine in some
cases, but becomes limiting in more sophisticated manipulation
scenarios.
The implementation in this change is taken directly from 3D Viewer
and ActionGrams and supports more sophisticated movement scenarios
which combine both gesture and gaze.  For example, with this new
implementation if you manipulate a hologram and then turn your head
the hologram will move with your head, while still allowing you to make
adjustments with your hands.  If you manipulate a hologram and then
walk somewhere else the hologram will move with you as long as you
maintain the gesture.  This allows for …

Adding support for hand based object manipulation

---

Assets/HoloToolkit/Sharing/Tests/RemoteHeadManager.cs

fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/214 by excluding the addition of the local users head from the remoteHeads dictionary.

Fixes remote head manager

---

Assets/HoloToolkit/Utilities/Scripts/TextToSpeechManager.cs
Assets/HoloToolkit/Utilities/Tests/TextToSpeechManager.unity
Assets/HoloToolkit/Utilities/Tests/TextToSpeechManagerTest.cs

This pull request fixes #220. It adds a dropdown in the inspector for TextToSpeechManager that includes 4 options:
1. Default
2. David
3. Mark
4. Zira
This list unfortunately cannot be dynamic because we can't execute UWP APIs in the Unity Editor. Even if we could, the voices available on the desktop will likely not match those on the HoloLens. Therefore, this list is hard coded. If we find the list changing frequently in the future (unlikely) we can add an option for typing in the voice name.
At runtime, if the dropdown was set to Default no extra code will be run and the behavior will be as before. If the dropdown is set to anything other than Default, the installed voices are searched for one that matches the selected name. If the voice is found, it's used. If the voice is not found, …

Added voice selection to TextToSpeechManager.

---

Assets/HoloToolkit/Input/Scripts/GestureManager.cs

When looking at adding events for gesture recognition start and end so that my UI elements could display a visual down and up state, I noticed that when focused changed, the new focused object was being set before the gestures were canceled. Canceling gestures sends the recognition end event, but to the new focused object.
While I was updating the logic, adding the "SendMessageOptions.DontRequireReceiver" to the OnSelect message seemed to match the intent that any object may or may not be listening for the OnSelect message.

Focus object fix

---

Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs

This pull request addresses #202. It adds a new menu item underneath the HoloToolkit to enable the recommended default capabilities. There are two options:
1. Recommended
2. Recommended with Internet
Both options enable Microphone, SpatialPerception and WebCam. The second option also enables InternetClient.

Added menu item to enable recommended capabilities

---

Assets/HoloToolkit/Input/Scripts/BasicCursor.cs

Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/246 Null Ref on Awake when looking for `GazeManager.Instance`.
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/197 Layer raycast mask to use bitwise op for calculation.

Basic cursor null ref and bitwise fixes

---

GettingStarted.md

Added note regarding the architecture type needed to properly build/run the project from the examples. I've added this because in our case, when we try to build and run the project in ARM (because that's the default arch type when we open it in Visual Studio) we're having errors when it comes to getting the required DLLs

Adding note related to building project

---

Assets/HoloToolkit/Sharing/Scripts/SharingStage.cs
Assets/HoloToolkit/Sharing/Tests/ImportExportAnchorManager.cs

This references issue https://github.com/Microsoft/HoloToolkit-Unity/issues/292
The major fixes here are subscribing to `NetworkConnection` events so that we know when we're connected to the server instead of using `Invoke` with a certain time (which failed when init took more than one second) and using `Singleton<T>` for `SharingStage`, as the previous implementation was broken and an unnecessary duplication of efforts.
My previous testing showed the Sharing sample scene to work now, which wasn't the case before; I would appreciate if some other people tested and verified this to be true.

Sharing fixes

---

Assets/HoloToolkit/Sharing/Tests/ImportExportAnchorManager.cs

Enables ImportExportAnchorManager to place user into a room if testing in editor.
Also helps fix https://github.com/Microsoft/HoloToolkit-Unity/issues/292 while in editor.

Sharing Test script update.

---

Assets/HoloToolkit/Utilities/Scripts/FixedAngularSize.cs
Assets/HoloToolkit/Utilities/Tests/FixedAngularSize.unity
Assets/HoloToolkit/Utilities/Tests/FixedAngularSize.unity.meta
ProjectSettings/GraphicsSettings.asset

In some cases text scales too small using FixedAngularSize. Though the overall size stays visually the same based on the FOV, the content can scale too much when getting closer to UI elements.
I added an override value that will reduce or increase the scale ratio as needed. By default it will act exactly the same as it does now, but if there is a UI element with content scaling too small, the override size ratio can be used to reduce the amount of scale as the user get closer to the element. This new value takes the original scale ratio and treats it like a lever using the starting position as the fulcrum. The override scale ratio moves this lever up or down to adjust the scale ratio (or angular ratio) so that the UI content is always legible.

Fixed angular size expanded

---

Assets/HoloToolkit/Utilities/Scripts/HeadsUpDirectionIndicator.cs

#355 
Change the bad namespace to the standard one

Fix namespace error on HeadsUpDirectionIndicator

---

Assets/HoloToolkit/Utilities/Editor/EnforceEditorSettings.cs
Assets/HoloToolkit/Utilities/Editor/EnforceEditorSettings.cs.meta

@jwittner I don't know why this isn't the default settings in Unity.

Force Text Asset Serialization and visible meta files

---

Assets/HoloToolkit/Input/Tests/Textures/button_test_cubemap.tga.meta

It was 12MB, making up ~1/3 of our Assets folder size. Now it's under 1MB. This probably isn't a huge deal either way, but I figured it'd be nice, especially since this Texture is for a test scene.

Resizing a large test scene texture.

---

Assets/HoloToolkit/Input/Scripts/Voice/KeywordManager.cs

This way, the actions are only performed if they'd be in context for the recognizer too.

Add a check to only process key bindings if the recognizer is listening

---

Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs

When using "Oriented towards user" mode, there was a bug that the object is rotated not towards the user, but exactly from the user.
Reversing the subtraction solves this problem.

Fix object orientation being rotated 180 degrees

---

Assets/HoloToolkit/Utilities/Prefabs/FPSDisplay.prefab
Assets/HoloToolkit/Utilities/Scripts/FpsDisplay.cs

Removed redundant text mesh.
Updated prefab's pivot to be pre-selected to Y axis. (was unset previously)

FpsDisplay fixes

---

Assets/HoloToolkit/Input/Scripts/Voice/KeywordManager.cs

This PR fixes the issue with `KeywordManager` keyword recognition not stopping when the script is deactivated. It also checks for the script being re-enabled and if `RecognizerStart` is set to `RecognizerStartBehavior.AutoStart`, resumes keyword recognition.

Fix KeywordManager not stopping when deactivated

---

Assets/HoloToolkit/SpatialMapping/README.md
Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs

#404
This makes the TapToPlace.cs script more generic. Start(), Update(), and OnInputClicked() are now virtual so when it's a base class these methods may be overridden.
Additionally you can now specify a parent to be moved with the currently tapped game object. If no parent is specified then the immediate parent is selected automatically.

Refactor TapToPlace.cs to be more generic

---

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs

#405 had an issue with parent movement and rotation.
I simplified the logic and tossed out the "Relational Distance" and in its place just applied the movement vector the the parent object instead of the currently selected object which fix the issue of the Relational Distance becoming increasingly erroneous.

TapToPlace.cs : Fix parent movement logic

---

Assets/HoloToolkit/Input/Tests/Scripts/FocusedObjectColorChanger.cs
Assets/HoloToolkit/Input/Tests/Scripts/SelectedObjectMessageReceiver.cs
Assets/HoloToolkit/Input/Tests/Scripts/SphereGlobalKeywords.cs
Assets/HoloToolkit/Input/Tests/Scripts/SphereKeywords.cs
Assets/HoloToolkit/Input/Tests/Scripts/TestButton.cs
Assets/HoloToolkit/Sharing/Scripts/Utilities/Utils.cs
Assets/HoloToolkit/Utilities/Scripts/DirectionIndicator.cs

https://github.com/Microsoft/HoloToolkit-Unity/issues/236
https://github.com/Microsoft/HoloToolkit-Unity/pull/354
http://answers.unity3d.com/questions/548420/material-memory-leak.html
> void OnDestroy() { DestroyImmediate(renderer.material); }
https://docs.unity3d.com/ScriptReference/Renderer-material.html
>Renderer.material
>
> public Material material;
> Description
> 
> Returns the first instantiated Material assigned to the renderer.
> 
> Modifying material will change the material for this object only.
> 
> If the material is used by any other renderers, this will clone the shared material and start using it from now on.
> 
> Note:
> This function automatically instantiates the materials and makes them unique to this renderer. 
> **It is your responsibility to destroy the materials …

Fixes material memory leaks in various files

---

Assets/HoloToolkit/Input/Scripts/Cursor/ObjectCursor.cs

It makes no sense to hide the cursor when there is no cursor listed for a given state. It's better just retain the last one. Otherwise you are obliged to add a cursor for EVERY possible state.

It makes no sense to hide the cursor when there is no cursor listed

---

Assets/HoloToolkit/Input/Shaders/Cursor.shader
Assets/HoloToolkit/Input/Shaders/CursorShader.shader
Assets/HoloToolkit/Input/Shaders/EditorHands.shader
Assets/HoloToolkit/SpatialMapping/Shaders/Occlusion.shader
Assets/HoloToolkit/SpatialMapping/Shaders/Wireframe.shader
Assets/HoloToolkit/SpatialUnderstanding/Materials/SpatialMappingSurface.shader
Assets/HoloToolkit/SpatialUnderstanding/Materials/SpatialUnderstandingSurface.shader
Assets/HoloToolkit/Utilities/Shaders/UnlitConfigurable.cginc
Assets/HoloToolkit/Utilities/Shaders/UnlitNoDepthTest.shader
Assets/HoloToolkit/Utilities/Shaders/VertexLitConfigurable.cginc
Assets/HoloToolkit/Utilities/Shaders/WindowOcclusion.shader

Many of the holotoolkit shaders weren't working correctly with the
single-pass stereo instancing option enabled in unity 5.5. This change
adds the instanceId and sets up the rendertarget index as required.
See issue #390

fix(stereo) allowing shaders to work with singlepass

---

Assets/HoloToolkit/Utilities/Shaders/BlinnPhongConfigurable.shader
Assets/HoloToolkit/Utilities/Shaders/BlinnPhongConfigurableTransparent.shader
Assets/HoloToolkit/Utilities/Shaders/LambertianConfigurable.shader
Assets/HoloToolkit/Utilities/Shaders/LambertianConfigurableTransparent.shader
Assets/HoloToolkit/Utilities/Shaders/UnlitConfigurable.shader
Assets/HoloToolkit/Utilities/Shaders/UnlitConfigurableTransparent.shader
Assets/HoloToolkit/Utilities/Shaders/VertexLitConfigurable.shader
Assets/HoloToolkit/Utilities/Shaders/VertexLitConfigurableTransparent.shader

As mentioned in issue #391 I'm not very familiar with how Unity shaders work under the covers, so I am not 100% sure if this is the correct fix or not. That being said, it produces the correct results.

fix(nearplanefade) multi_compile _NearPlaneFadeOn

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/InputSources/EditorHandsInput.cs
Assets/HoloToolkit/Input/Scripts/InputSources/RawInteractionSourcesInput.cs
Assets/HoloToolkit/Input/Scripts/Utilities/AxisController.cs
Assets/HoloToolkit/Input/Scripts/Utilities/ManualHandControl.cs
Assets/HoloToolkit/Utilities/Scripts/Interpolator.cs
Assets/HoloToolkit/Utilities/Scripts/SphereBasedTagalong.cs
Assets/HoloToolkit/Utilities/Scripts/StabilizationPlaneModifier.cs

This change enables editor input, tagalongs, and the cursor to work
while the time scale is set to 0. Setting the time scale to 0 is a
common practice to implement game "pause" behavior as is done in the
Unity sample project. With this change, tagalong menus will still
function even when the game is paused.

Support lerping with unscaled time to enable pause menus

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs

If the app runs of a Windows 10 device that is NOT a HoloLens, it will will crash. This happens for instance when the Windows App Certification Kit runs. Result: the WACK lists a boatload of errors that will never happen when the app is actually deployed to a HoloLens, causing confusing for developers. Also, it prevents the app from running on a normal PC.

The check for a VR device does not happen at run time.

---

Assets/HoloToolkit/Utilities/Shaders/HoloToolkitCommon.cginc

@RyanMonday pointed out some code that was left out of HoloToolkitCommon, which broke the new shader.

HoloToolkitCommon fix

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs

Resolves #445 by adding additional checks to determine cursor state.
The first one essentially says that `IsInputSourceDown` should be `true` and visible hands should be greater than one to say that cursor is in a select state.  The second if statement is to mend the case where `IsInputSourceDown` happens to be true while no hands are visible, in which case we set `IsInputSourceDown` to false.

prevent cursor from disappearing on manipulation cancel

---

Assets/HoloToolkit/Utilities/Shaders/FastConfigurable.shader.meta
ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt
README.md

Resolves https://github.com/Microsoft/HoloToolkit-Unity/issues/475
https://unity3d.com/unity/whats-new/unity-5.5.1
**Caution!**
> - Warning about missing object references in the inspector after upgraded to 5.5. We have only received one bug report and we have not been able to reproduce the issue. If you find some/all of your object references missing in the inspector do not save your scene. Quit the editor and re-open your project and the references should come back correctly.
HoloLens Specific Improvements:
> - AR: Fixed a crash when exiting play mode during a Holographic Simulation session. (858208)
> - HoloLens: Fixed a crash in Editor when terminating Remoting App during an active Holographic Remoting session.
> - HoloLens: Fixed resume-from-suspend bugs that would occasionally crash …

Update to Unity 5.5.1f1

---

Assets/HoloToolkit-UnitTests.meta
Assets/HoloToolkit-UnitTests/Editor.meta
Assets/HoloToolkit-UnitTests/Editor/Utilities.meta
Assets/HoloToolkit-UnitTests/Editor/Utilities/Extensions.meta
Assets/HoloToolkit-UnitTests/Editor/Utilities/Extensions/VectorExtensionsTests.cs
Assets/HoloToolkit-UnitTests/Editor/Utilities/Extensions/VectorExtensionsTests.cs.meta
Assets/HoloToolkit-UnitTests/README.md
Assets/HoloToolkit-UnitTests/README.md.meta

It's hard for the reviewers to test all functionalities so I think it's a good idea to start enforcing a unit tests requirement.
Here is an example for the VectorExtensions. While working on it, I noticed that the latest functionalities added are actually not extensions. One good reason for them to exist...
I placed the unit tests in a HoloToolkit-UnitTests folder under Assets to keep the HoloToolkit deployment simple.
Unit tests execution is integrated into the Unity editor (since 5.3). It doesn't require the Unity Test Tools from the asset store.
To run all the tests: 
1. Click on the menu item Window | Editor Tests Runner. 
2. Click on the button Run All.

Added unit tests for VectorExtensions

---

Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs

Since the up vector was ignored, the dragging function always messed up with the rotation of a object if it was rotated before.
Quaternion.LookRotation() takes the global up vector (Y) by default,  but if the object was rotated for example around the Z axis, the global up vector isn't the same as the local one -> object rotation is messed up, because the local forward vector and the global up vector are used instead of local forward and local up.

Fix rotation if hologram was rotated before

---

Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingCustomMesh.cs

There appears to be a bug with SpatialUnderstandingCustomMesh: when finalizing the mesh data (with Commit()), the rendering mesh picks up the changes but the collision mesh does not. Presumably this is a quirk of how Unity handles collision meshes.
The result of this is that using meshes produced by the Spatial Understanding system (as opposed to the underlying meshes provided by SpatialMappingManager) doesn't work in scenarios where rigid bodies are expected to collide with the world.
This patch appears to be the minimum required change to fix the problem however it's a bit ugly: I have to set a reference to the MeshCollider in MeshData, which otherwise consists exclusively of readonly members. A proper fix would require modifying CreateSurfaceObject() but that is a bit more of an …

Need to update collision mesh when committing mesh data

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingObserver.cs
Assets/HoloToolkit/SpatialMapping/Tests/Scripts/SpatialProcessingTest.cs

Related to https://github.com/Microsoft/HoloToolkit-Unity/issues/79 - when physics in Unity are paused using timeScale = 0.0f (which is quite a common use case), the spatial mapping stops too, which is undesirable in almost all circumstances.
The common use case is actually the opposite: the game is usually paused, while the HoloLens is allowed to gather spatial mapping data.
The change to unscaledTime allows Spatial Mapping to continue while the physics are
paused.

Make Spatial Mapping use unscaledTime

---

ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt
README.md

Resolves https://github.com/Microsoft/HoloToolkit-Unity/issues/489
[See all the changes here](https://unity3d.com/unity/whats-new/unity-5.5.2)
HoloLens Specific fixes and changes:
> - (860775) - HoloLens: Fixed a crash that occurs on device when downloading files with WWW.
> - (847798) - Mono: Correct an invalid C# compiler error with generic types in compiler generated code (like lambdas and enumerators). The error from the C# compiler often includes this text: "There is no boxing or type parameter conversion from..."
> - (none) - Android/Metro: Fixed the issues preventing the Application.Unload API from functioning correctly.
> - (none ) - Scripting: Added the following non-allocating accessors to Mesh. These accessors write into a user-specified List. The accessors are GetBindposes, …

Editor update to 5.5.2f1

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialProcessing/RemoveSurfaceVertices.cs

Changing from List to HashSet greatly improves the speed of .contains(), which allows RemoveSurfaceVertices to complete in at most 1 or 2 seconds as opposed to 10+ previously.

Greatly speed up RemoveSurfaceVertices

---

Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs

When u drag a object via HandDraggable and move your head the rotation of the object changes.
At least in my case I don't want that, it somehow feels unnatural, so I implemented a public flag to prevent this behaivour (lock the rotation of the object).
Also I added a Header and Space for grouping the different rotation modes in the inspector (probably change the text there a bit?)
And I grouped the handling of the rotation modes (upright, towards user, lock orientation)  into an if-else if-else if construct. If nothing applies (when IsRotationLocked == true) the rotation of the object isn't changed at all (my desired behaivour).
Any opinions?

Added possibility to lock the objects rotation while dragging it

---

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingObserver.cs

Hello,
As outlined by the issue [#557](https://github.com/Microsoft/HoloToolkit-Unity/issues/557) I adapted the code of the SpatialMappingObserver to allow for changing the observed volume to an axis or an axis aligned box.
Please let me know, if I missed out on something.
Thanks.

Adapting SpatialMappingObserver as lined out in Issue #557

---

Assets/HoloToolkit/CrossPlatform/Scripts/Reflection/ReflectionExtensions.cs

ReflectionExtensions declared in global namespace possible to effect to other libraries. First I tried to move ReflectionExtensions to HoloToolkit.Unity namespace but HoloToolkit.Sharing.SyncModel is using extension method in ReflectionExtensions.
example)
Import HoloToolkit-Unity and MessagePack.1.0.3.unitypackage, then build error has been occured.
https://github.com/neuecc/MessagePack-CSharp/releases/tag/v1.0.3

Move ReflectionExtensions namespace to HoloToolkit

---

Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs

Now the closest hit is picked instead of the first one.
This was an issue when multiple UI canvases was on top of each other. The Raycast result was not ordered, and the FindFirstRaycastInLayermasks returned the first hit in the list, not the closest hit. 
Now the code checks the distance of the hist to return the closest one.

Fixed issue with GazeManager not hitting the closest UI element when raycasting.

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs

TargetedCursorModifier is dependent on TargetedObject and therefore should be cleared out whenever TargetedObject is cleared out
Resolves #584

bugfix for Cursor: TargetedCursorModifier should've been nulled

---

Assets/HoloToolkit/Build/Editor/HoloToolkitCommands.cs
Assets/HoloToolkit/CrossPlatform/Scripts/Reflection/ReflectionExtensions.cs
Assets/HoloToolkit/CrossPlatform/Scripts/Reflection/TypeUtils.cs
Assets/HoloToolkit/Input/Scripts/Editor/EditorHandsMaterialInspector.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/EnforceEditorSettings.cs

Adds scripts to `HoloToolkit.Unity`, if no namespace declaired.
Simple typo fixes in existing namespaces.

Namespace fixes

---

Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs

[This issue ](https://forums.hololens.com/discussion/7036/moving-object-very-slow-juddering) has come up as a question once or twice in the forums, and I had a fix for this in my own project that I figured I could contribute back to the main repository.
I didn't add specific code to disable this, but setting the speed values to 1.0 will effectively give you the same behavior as before. The default values are just what felt good to me, but I'm open to tweaking the defaults if people prefer things more responsive, or smoother.

Add smoothing to translation and rotation for HandDraggable script

---

Assets/HoloToolkit-Tests/Input/Shaders/button_unlit_shader.shader
Assets/HoloToolkit/Input/Shaders/Cursor.shader
Assets/HoloToolkit/Input/Shaders/CursorShader.shader
Assets/HoloToolkit/Input/Shaders/EditorHands.shader
Assets/HoloToolkit/Input/Shaders/SpecularHighlight.shader
Assets/HoloToolkit/SpatialMapping/Shaders/Occlusion.shader
Assets/HoloToolkit/SpatialMapping/Shaders/SpatialMappingTap.shader
Assets/HoloToolkit/SpatialMapping/Shaders/Wireframe.shader
Assets/HoloToolkit/SpatialUnderstanding/Materials/SpatialMappingSurface.shader
Assets/HoloToolkit/SpatialUnderstanding/Materials/SpatialUnderstandingSurface.shader
Assets/HoloToolkit/UI/Shaders/3DTextShader.shader
Assets/HoloToolkit/Utilities/Shaders/HoloToolkitCommon.cginc
Assets/HoloToolkit/Utilities/Shaders/UnlitConfigurable.cginc
Assets/HoloToolkit/Utilities/Shaders/UnlitNoDepthTest.shader
Assets/HoloToolkit/Utilities/Shaders/VertexLitConfigurable.cginc
Assets/HoloToolkit/Utilities/Shaders/WindowOcclusion.shader

`UnityObjectToClipPos` is supposed to be faster than multiplying by `UNITY_MATRIX_MVP` when using SinglePassStereo and/or when using concatenated matrices. The same applies to `UnityObjectToViewPos` and `UNITY_MATRIX_MV`.  
The Unity team has mentioned this in a couple talks recently, and Unity 5.6 has starts providing a performance warning when importing shaders that use UNITY_MATRIX_MVP, etc, so I figured its probably worth addressing.

Using UnityObjectToClipPos according to performance recommendations

---

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs

Tap to place currently sets a world anchor on game object during start
method, which keeps it from moving around if starting out with
IsBeingPlaced true.  I put a check to see if we are starting out
placing, and if so, then we don't add the world anchor.
#535 is resolved by this PR

Fixes issue with tap to place not working

---

Assets/HoloToolkit/Utilities/Scripts/Editor/EnforceEditorSettings.cs

The existing version does not feature a prompt, and modifies the
project configuration without warning. Users with complex or unique
project setups may encounter issues.
Users will now be prompted to change their project settings when
importing the HoloToolkit, or opening a project with the toolkit
already included, to better support external VCS and project
maintainability.
___
Whether or not this pull request is worth including is up for debate. It adds a new pop-up every time the editor is launched until project settings are modified, and is a good deal more involved than the previous implementation.
\- Requires user attention when first importing a project
\- Requires a field in the EditorPrefs store to save pop-up state.
\+ Allows users to delay the changes to their project settings …

Added confirmation dialogues to EnforceEditorSettings

---

Assets/HoloToolkit/SpatialUnderstanding/Prefabs/SpatialUnderstanding.prefab

It appears that commit 22d1d94b54d64e19fcfbf3e157990eefb04b8f99 renamed the meshMaterial field. SpatialUnderstanding.prefab uses this field and needs to be updated to match.

Fixes #681 by updating serialized meshMaterial field.

---

Assets/HoloToolkit-Examples/InteractiveElements/Prefabs/Button.prefab

For the Button GameObject in the InteractiveButtonComponents scene, the ButtonOutline's Label GameObject had a typo under its Button Theme Widget Label (Script)'s Color Theme Tag variable. Originally, the value of the Color Theme Tag variable was buttonLableColor, but it should have been buttonLabelColor.

Typo in the InteractiveButtonComponents scene in the HoloToolkit-Examples.

---

Assets/HoloToolkit-Tests/Sharing/Scripts/ImportExportAnchorManager.cs

Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/652
- sometimes InitRoomApi was called twice. this is beeing avoided now
- GetRoomCount is giving 0 sometimes when there are rooms, causing a extra room is created. added a slight delay that seems to fix the issue

improvements for ImportExportAnchorManager 

---

Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/NetworkDiscoveryWithAnchors.cs

Was seeing issues with clients not connecting to the server in Master configuration with "Compile with .NET Native tool chain" checked. Unchecking the native tool chain resolved that issue. This code is a work-around that also resolves the problem and keeps the native tool chain enabled.

Fixes issues with the server broadcasting when building as master.

---

Assets/HoloToolkit/Build/Editor/BuildSLNUtilities.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs
Assets/HoloToolkit/Utilities/Shaders/FastConfigurable/Editor/CustomMaterialEditor.cs
Assets/HoloToolkit/Utilities/Shaders/FastConfigurable/Editor/FastConfigurableGUI.cs
ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt
README.md

Resolves https://github.com/Microsoft/HoloToolkit-Unity/issues/767
- Removed references to `EditorUserBuildSettings.wsaSDK`.  It is obsolete and has no effect and will be removed in a subsequent Unity release.
- Fixed `BeginAnimatedCheck` overload.
- Fixed `TextureScaleOffsetVector4Property` overload.
- Updated `ProjectSettings`.
- Updated Project version.

Update Unity Editor to 2017.1.0f3

---

Assets/HoloToolkit/Sharing/Scripts/Spawning/PrefabSpawnManager.cs
Assets/HoloToolkit/Sharing/Scripts/Spawning/SpawnManager.cs

- Added more control over spawning synced objects when connection is made.
- Will now respawn `GameObject`s when reconnected.
- Added a dictionary of `GameObject` references for each `SyncSpawnObject`.

SpawnManager Update

---

Assets/HoloToolkit/UI/Scripts/Keyboard.cs

The new HoloToolkit supports selecting ranges of text (a standard feature of an InputField) and will autoselect all text when opening a keyboard with text already set, but currently will not delete selected text with the backspace key. Fix will delete the selected text and set the cursor to that position.

support for backspace deleting selected text

---

Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs

- Fixed https://github.com/Microsoft/HoloToolkit-Unity/issues/804 where uGUI raycasting was compensating for Unity Bug.  Unity now correctly calculates raycast value from the near clip plane.
- Fixed https://github.com/Microsoft/HoloToolkit-Unity/issues/778 by checking the `GazeTransform` in update and moving the initialization from `Start` to `Awake`.

Updated GazeManager uGUI raycast calculations & GazeTransform initialization 

---

Assets/HoloToolkit-Tests/Input/Scenes/InteractiveMeshCursor.unity
Assets/HoloToolkit/Input/Prefabs/Cursor/InteractiveMeshCursor.prefab
Assets/HoloToolkit/Input/Scripts/Cursor/InteractiveMeshCursor.cs

Using the cursor SetVisibility, the ring, dot and light is set properly. Issue #785

The light now goes away when the cursor's visibility is set to false.

---

Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
Assets/HoloToolkit/Utilities/Scripts/CameraCache.cs

Reverted the gaze manager code to what it was before. Also removed the other occurrence in the CameraCache class for good measure, although that one seemed to work.

Fix null coalescing causing errors

---

Assets/HoloToolkit/Input/Scripts/Editor/SpeechInputSourceEditor.cs
Assets/HoloToolkit/Input/Scripts/Voice/SpeechInputSource.cs

Added confidence level for the keyword recognizer in SpeechInputSource and assosiated editor script.

Added confidence level for the keyword recognizer 

---

Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs
Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/Schema/Node.cs

Removed a workaround for Grip/Position rotation returning incorrect values. Removing a manual calculation (which wasn't working properly with the provided glTF models) in favor of Unity's built in rotation matrix.

Fix glTF loader rotation calculation.

---

Assets/HoloToolkit/Sharing/Scripts/VoiceChat/MicrophoneReceiver.cs
Assets/HoloToolkit/Sharing/Scripts/VoiceChat/MicrophoneTransmitter.cs

Fixes #786 
- Added HTRF bits to be read from the stream to prevent mismatch on receiving end.

Fix for mismatched Mic network stream

---

Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs

Fixed null reference when setting icon in icon generator with bad dimensions.

Fixed null reference when setting icon in icon generator with bad dimensions.

---

Assets/HoloToolkit/SpatialMapping/Prefabs/RemoteMapping.prefab
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/MeshSaver.cs
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMeshTarget.cs
Assets/HoloToolkit/SpatialMapping/Tests/Scenes/RemoteMapping.unity

See #265 
This also fixes a bug where spatial mapping file saving didn't properly get data from the remote mapping source.

Fixing remote mapping for IL2CPP support

---

Assets/HoloToolkit-Tests/SpatialMapping/Scenes/RemoteMapping.unity
Assets/HoloToolkit/SpatialMapping/Prefabs/RemoteMapping.prefab
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/MeshSaver.cs
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMeshTarget.cs

Fixes #265
This also fixes a bug where spatial mapping file saving didn't properly get data from the remote mapping source.

Updating remote mapping for IL2CPP builds in master

---

Assets/HoloToolkit/Input/Materials/ControllerMaterial.mat
Assets/HoloToolkit/Input/Materials/ControllerMaterial.mat.meta
Assets/HoloToolkit/Input/Prefabs/Controllers.prefab
Assets/HoloToolkit/Input/Prefabs/MixedRealityCamera.prefab
Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParent.prefab
Assets/HoloToolkit/Input/Scripts/ControllerInfo.cs
Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs
Assets/HoloToolkit/Input/Tests/Scenes/MotionControllerTest.unity
Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFLoader.cs
Assets/HoloToolkit/Utilities/Scripts/GLTFComponentStreamingAssets.cs

Making glTF loading take in a material instead of a shader, since Unity doesn't build unused shader configurations.
Also, refactored controller animation to be dependent on developer preference instead of override/non-override, to allow for specialized overrides to be animated.

Fixing glTF controller emission & normal mappings and override animations

---

Assets/HoloToolkit/Input/Scripts/Voice/SpeechInputSource.cs

Addition to #927 
Since we expose the confidence level in the editor now we also need the using.
Those compiler directives are really annoying to spot in a diff.

Fix for speech cross platform support

---

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs
ProjectSettings/QualitySettings.asset

Fixes #950
Reverted removal of QualitySettings Hack.
[Currently no APIs available](http://answers.unity3d.com/questions/886160/how-do-i-change-qualitysetting-for-my-platform-fro.html) to change default platform quality setting via code.
See #949

Quality Settings regression fix.

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs

update to BuildAndDeploy

---

Assets/HoloToolkit/Utilities/Scripts/Extensions/HapticsExtensions.cs

Turns out there's an easier way to convert seconds into a TimeSpan :)

Fix haptics bug for durations shorter than 1 second

---

Assets/HoloToolkit/Input/Scripts/Interactions/TapToPlace.cs
Assets/HoloToolkit/Utilities/Scripts/Extensions/TransformExtensions.cs

Adds an offset to the placement position for situations where the centre of a mesh is not the same as the centre of the GameObject.
(Should I have opened an Issue first btw? Wasn't sure if it mattered since it's such a small feature)

Added a Cursor Offset to the TapToPlace script

---

Assets/HoloToolkit-UnitTests/Editor/Utilities/Extensions/TransformExtensionsTests.cs
Assets/HoloToolkit/Utilities/Scripts/Extensions/TransformExtensions.cs

Add tests for `TransformExtensions.GetColliderBounds`
Also, some minor changes to the method itself to use early return and I don't think we need the warning as the description mentions that it will return empty bounds when there is no collider.

Collider bounds tests

---

Assets/HoloToolkit-UnitTests/Editor/Input/InputManagerTests.cs
Assets/HoloToolkit-UnitTests/Input/TestEventHandler.cs
Assets/HoloToolkit/Input/Scripts/InputManager.cs

Fixes #1022
The InputManager changes mean that it now takes into account whether the eventdata was actually used versus an event firing.

Updating input tests with FocusManager and new InputManager checks

---

Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs

Reverts Microsoft/MixedRealityToolkit-Unity#1033
This change completely blows up in the editor.
Need to find a better way to filter out what's actually in the scene vs. on disk.

Revert "Instance isn't found if class is on a disabled GameObject."

---

Assets/HoloToolkit-Examples/SpatialMappingComponent/DropCube.cs
Assets/HoloToolkit/SharingWithUNET/UI/Scripts/StartSessionButton.cs
Assets/HoloToolkit/SpatialMapping/Scripts/ObjectSurfaceObserver.cs
Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingObserver.cs
Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingCustomMesh.cs
Assets/HoloToolkit/Utilities/Scripts/DisplayDependentObjectActivator.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/ExternalProcess.cs
Assets/HoloToolkit/Utilities/Scripts/FadeScript.cs
Assets/HoloToolkit/Utilities/Scripts/StabilizationPlaneModifier.cs

Now builds for win standalone. (after Input Update gets merged)

More WSA wrapping

---

Assets/HoloToolkit-Examples/GamePad/Scenes/XboxControllerExample.unity
Assets/HoloToolkit/Input/Scripts/GamePad/XboxControllerMapping.cs
Assets/HoloToolkit/Input/Scripts/InputSources/XboxControllerInputSource.cs

Regression from #994 
- Event System Overrides were mapped incorrectly.
- `XboxControllerMappingTypes.None` was not handled when getting and setting the mapping types.

Fixed XboxController update regressions

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPrefs.cs
Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs
Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Assets/HoloToolkit/Sharing/Scripts/Editor/SharingMenu.cs
Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/Editor/RoomMeshExporter.cs
Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioProfiler.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/AutoConfigureMenu.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/SceneSettingsWindow.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs

Redone PR of #1048 (Messed up my rebase)
Gets some of the forwards compatibility issues out of the way.
Most changes are to the Build and Deploy windows and Mixed Reality Toolkit Menus
Fixes #851
Fixes #895
Fixes #1018
Fixes #1019

Mrtk forward compatibility

---

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs

Incorrectly changed it to `stereo` instead of `WindowsMR`
Updated `HoloLens` to `WindowsMR`
No changes needed to master branch, because the SDK names did not change, and there's no way to enable occluded devices.

Fixed VR enabling on build target group in Project wizard.

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs
Assets/HoloToolkit/Utilities/Scripts/FadeScript.cs

Fixes #1112 Added a null-check of TeleportMarker before instantitiating the object.
Fixes #1113 Add an option to use sharedMaterial when fading.

Add a null-check of TeleportMarker before instantiating the object.

---

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Extensions/InteractionSourceExtensions.cs
Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs

Fixed GLTF build errors

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs

I may be totally missing something here, but I'm just going off what the build window generates for me (that is, it builds to the build folder directory, it doesn't build to incremental subfolders or anything like that)
Currently, it will search the build folder for folders, then search those folders for an `AppPackages` folder and use that to identify it's a build. But this isn't how builds are generated by the build tools. The `AppPackages` folder is in the root of the build folder, so what should actually be iterated through is the contents of the `AppPackages` folder in the root of the build folder. _Those_ are the individual builds.

Fixes build discovery

---

Assets/HoloToolkit/Utilities/Scripts/Editor/CapabilitySettingsWindow.cs

Only just found this one, you need Private Network Client Server enabled in order to use the Unity Remote Profiler with Hololens.
Wording may need tweaking, or perhaps it would be best moved into a separate menu option for "Enable Remote Profiler" that pops up a window saying "This will enable the 'Private Network Client Server' capability, are you sure?" instead.

Added a note to capabilities RE: Remote Profiler

---

Assets/HoloToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs

This resolves an issue when calling `GetInternalSwitchAddressInfo()` where when failing to locate the adapter, it would throw a silent exception and never stop searching - giving the impression that it's still trying to find something when it never gets to line 58 to check if it's null.

Handle a null switch and gracefully stop searching

---

Assets/HoloToolkit/Input/Scripts/Utilities/SetGlobalListener.cs
Assets/HoloToolkit/Utilities/Scripts/Singleton.cs

Updated singleton to search the scene if an instance isn't found.
Also reverted the `AddGlobalListener` and have it handle itself better when cleaning up.
Fixes #1157

Singleton changes.

---

Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/HandDraggable.cs

Fixes #1176
To test, build and run the `InputManagerTest` scene on the HoloLens and drag around the objects.

Properly supports Hand position and Fixed HandDraggable

---

Assets/HoloToolkit/Input/Scripts/InputEventData/SpeechKeywordRecognizedEventData.cs
Assets/HoloToolkit/Input/Scripts/InputEventData/SpeechKeywordRecognizedEventData.cs.meta

Added `SpeechKeyworkRecognizedEventData` back into project to help devs update instead of ripping it out.
Now properly uses `obsolete` attribute.

Reverted removal of SpeechKeyworkRecognizedEventData

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/InputManager.cs

Maybe a nit, but if there are no input handlers on the stack, the InputManager throws an exception. Added a check for empty stack to prevent exception being thrown.

Prevent Stack exception on InputManager.PopModalInputHandler

---

Assets/HoloToolkit-Examples/Input/Scenes/InputNavigationRotateTest.unity
Assets/HoloToolkit-Examples/Input/Scripts/NavigationRotateResponder.cs

This scene was an old version of the UNET Sharing test scene, which must have happened during the test scene moves or the unet sharing folder move (or a combination of merging both). I've reverted it to a version of the test scene I had locally, and also updated the script to fix a bug I noticed when focus left the spinning cube before navigation ended, which happened often with the motion controllers.

Input navigation test scene fixes

---

Assets/HoloToolkit-Examples/Input/Scenes/MotionControllerTest.unity
Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scripts/BaseGrabber.cs
Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs

Fix for issue #1174 to allow for default models if the OS's models weren't loaded in addition to allowing for overriding the models.

Allowing default versus overriden controller models

---

Assets/HoloToolkit-Examples/Input/Scenes/MotionControllerTest.unity
Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParent.prefab
Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs

The Dev_Unity_2017.2.0 branch will be retired after this PR to prevent future work from being done in it.

Final merge of dev branch into master, including alternate model loading

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/Cursor/CursorModifier.cs
Assets/HoloToolkit/Input/Scripts/Focus/FocusDetails.cs
Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs
Assets/HoloToolkit/Input/Scripts/Focus/IPointingSource.cs
Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs
Assets/HoloToolkit/Input/Scripts/Focus/PointerResult.cs
Assets/HoloToolkit/Input/Scripts/Focus/PointerResult.cs.meta
Assets/HoloToolkit/Input/Scripts/Focus/RayStep.cs
Assets/HoloToolkit/Input/Scripts/Focus/RayStep.cs.meta
Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/CustomHeaderDrawer.cs
Assets/HoloToolkit/Utilities/Scripts/Inspectors/MRTKEditor.cs

_(Resubmission of #1318 with clean commit history)_
This is a first pass at adding multi-step pointer support to the FocusManager.
Also Fixes: #1300 with the Header attribute getting overwritten by `MRTKEditor`.
The main change is in IPointingSource, where we go from this:
```
public interface IPointingSource
{
...
Ray Ray { get; }
...
}
````
To this:
```
public interface IPointingSource
{
...
RayStep[] Rays { get; }
...
}
````
Where RayStep is a struct with an origin and terminus.
This enables IPointingSources with curving trajectories, similar to what we see in WMR (parabolic navigation pointers, bendy transform pointers, etc).
Because this is a breaking change I'm creating a separate pull request to discuss it. So far I can't see a way to do this without breaking previous …

MRDL->MRTK: Multi-step pointer sources

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityCameraManager.cs

Overview
---
Updates the code to match the prefabs to prevent confusion.
Previously, the prefabs were updated to use a near clipping plane of 0.1. The code still had 0.3 as its default.
Changes
---
- Fixes: #1337

Updating Opaque clipping plane in code to match prefabs

---

Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TapToPlace.cs

Fixes #1328. If TapToPlace does not call eventData.Use() then fallback handlers will respond to the tap/click event. This can lead to undersirable behavior while placing an object.

TapToPlace needs to let event system know when a click is handled

---

Assets/HoloToolkit/UX/Scripts/Distorters/Distorter.cs
Assets/HoloToolkit/UX/Scripts/Distorters/DistorterBulge.cs
Assets/HoloToolkit/UX/Scripts/Distorters/DistorterGravity.cs
Assets/HoloToolkit/UX/Scripts/Distorters/DistorterSimplex.cs
Assets/HoloToolkit/UX/Scripts/Distorters/DistorterSphere.cs
Assets/HoloToolkit/UX/Scripts/Distorters/DistorterWiggly.cs
Assets/HoloToolkit/UX/Scripts/Lines/Bezier.cs
Assets/HoloToolkit/UX/Scripts/Lines/Ellipse.cs
Assets/HoloToolkit/UX/Scripts/Lines/Line.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineBase.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineBaseEditor.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineMeshes.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineObjectCollection.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineObjectFollower.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineObjectSwarm.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineParticles.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineRendererBase.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineStripMesh.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineUnity.cs
Assets/HoloToolkit/UX/Scripts/Lines/LineUtility.cs
Assets/HoloToolkit/UX/Scripts/Lines/Parabola.cs
Assets/HoloToolkit/UX/Scripts/Lines/Rectangle.cs
Assets/HoloToolkit/UX/Scripts/Lines/Spline.cs
Assets/HoloToolkit/UX/Scripts/Lines/SplinePoint.cs

Overview
---
Changed namespaces to `HoloToolkit.Unity.UX`. These changes could be breaking, if someone uses the scripts. All tests ran through, although I could only test them with Unity 2017.1.2f1.
Please run the tests in 2017.2.
I noticed there are a lot of unused dependencies in these scripts, but I didn't remove them to keep the PR clean. Maybe you should refactor that at some point in time. 
Changes
---
- Fixes: #1366

Changed the namespaces to HoloToolkit.Unity.UX

---

Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs
Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs
Assets/HoloToolkit/Input/Scripts/Focus/SimpleSinglePointerSelector.cs
Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/CustomInputSelector.cs

Changes
---
- Fixes: #1346
- Fixes: #1344 Fixed Pointer registration.  We still register pointers on the fly but now we only unregister them when we get a source lost event raised by the `InputManager`.
- Removed `OnValidate` checking the `UIRaycastCamera` so there's not a warning every time we recompile. (For some reason during deserailization when the script is loading, the `uiRaycastCamera` is null, even though the serialized value is valid.)
- Fixes: #1356 
- FIxes: #1363

Added check for valid uiRaycastResults and fixed pointer registration

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/HandDraggable.cs
Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs

Overview
---
Updated HandDraggable to support knowing the difference between Hand and Controller input. 
Because the clicker is considered a controller, but does not raise the `Select` press type, we need to update its press type.  We know it's the clicker because pointer position is not supported.
Also, updated the cursor to support not having a pointer.
Changes
---
- Fixes: #1271
- Fixes: #1203
- Fixes: #741

Hand draggable and clicker fixes

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs
Assets/HoloToolkit/Input/Scripts/Focus/IPointingSource.cs
Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs
Assets/HoloToolkit/Input/Scripts/Focus/RayStep.cs
Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
Assets/HoloToolkit/UX/Scripts/Receivers/InteractionReceiver.cs

This PR adds a FocusLocked field to IPointingSource.
While a pointer's FocusLocked is true, focus enter / exit events are suspended and that pointer will continue to send manipulation to the last focused object.
This is needed for tools like bounding boxes, which require gaze focus for initial selection but not for subsequent manipulation.
PR passes all input tests.

MRDL->MRTK: Pointer focus locking

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Assets/HoloToolkit/Utilities/Scripts/WindowsApiChecker.cs

Updated API and SDK compatibility

---

Assets/HoloToolkit/Input/Scripts/Utilities/MicrophoneHelper.cs
Assets/HoloToolkit/Input/Scripts/Utilities/MicrophoneHelper.cs.meta
Assets/HoloToolkit/Input/Scripts/Utilities/MicrophoneHelperSample.cs
Assets/HoloToolkit/Input/Scripts/Utilities/MicrophoneHelperSample.cs.meta

Microphone helper sample to query microphone presence and availability at runtime. Partners have asked for such sample to make decisions in game whether to show speech use helpers.

Add microphone helper sample

---

Assets/HoloToolkit/SpatialMapping/Shaders/SpatialMappingTap.shader

Overview
---
apply this document's content into spatial mapping tap shader
https://docs.unity3d.com/Manual/SinglePassStereoRenderingHoloLens.html
Changes
---
- Fixes: #1411

spatial mapping tap is working with single-pass stereo rendering

---

Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs

Overview
UnityEngine.XR.WSA   InteractionSourceState.sourcePose.TryGetPosition and InteractionSourceState.sourcePose.TryGetRotation can return 'NaN' and or 'Infinity/NegativeInfinty' as a coordinate value. When setting a transform.postion or transform.rotation with non numeric coord values will through an error.
Changes
Added two validation methods to test for 'IsNaN' and 'IsInfinity'. Applied these changes to the condition statement befor setting prosition and rotation of controller model.
- Fixes: #1290.

Validation for Position and Rotation Coords Issue#1290

---

Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParent.prefab

Overview
---
In certain scenarios, the fade plane casts a large shadow, which isn't ideal.
Changes
---
- Related to: #1257, Q6.

Removing casting and recieving shadows from the FadePlane

---

Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/SimpleMeshSerializer.cs

Overview
---
Simple addition that allows the serialised mesh to be converted to the local space of a supplied transform.
This requires that you also provide the necessary transform to convert the current local co-ordinates of the mesh into world space first.
Changes
---
Feature addition, does not affect current functionality.
- Fixes: N/A

Allow serialised mesh to be converted to supplied local space.

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityCameraManager.cs

Overview
---
Initialization of transparent display settings when holographic remoting in editor using `HolographicEmulationWindow  emulationMode` to detect if remoting to HoloLens in Editor.
Changes
---
- Fixes: #1287

Holographic remoting support for mixed reality camera manager

---

Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs

Overview
---
Currently, the `#if` tags hide the overridable methods. This will cause errors on anything that overrides them in non-UWP builds.

Fixing AttachToController for non-UWP builds

---

Assets/HoloToolkit-Examples/Input/Scenes/GamepadTest.unity
Assets/HoloToolkit-Examples/Input/Scripts/XboxControllerHandlerTest.cs
Assets/HoloToolkit/Input/Scripts/GamePad/GamePadHandlerBase.cs
Assets/HoloToolkit/Input/Scripts/GamePad/XboxController/XboxControllerHandlerBase.cs

Overview
---
Simplified the state machine in `XboxControllerHandlerBase` to reduce confusion and cases where states may conflict with each other.
Also resolved a bug where `GamePadHandlerBase` was registering as a global listener twice, thus receiving all events from the `InputManager` twice.
Changes
---
- Fixes: #1517

XboxControllerHandlerBase fixes

---

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs

Overview
---
If a HoloLens is detected, now the `BoundaryManager` script is disabled.
Changes
---
- Fixes: #1505.

Removing BoundaryManager from HoloLens

---

README.md

The plural of API is APIs, not API's. Reference: https://english.stackexchange.com/questions/323688/what-is-the-plural-of-api
Overview
---
Changes
---
- Fixes: # .

Fix typo "API's" -> APIs

---

Assets/HoloToolkit-Examples/Sharing/SharingService/Scripts/UserNotifications.cs

Overview
---
Simple fix to have the code behave as it was intended - only notify when a remote user joined instead of all users (including the local user).

Fixed bug in UserNotifications example that didn't correctly check for local user.

---

Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs

In my app Walk the World I have seen crashes happening on this line, debugging learned that for some reasons sometimes uiRaycastResult.module is indeed null, causing the next clause (uiRaycastResult.module.eventCamera == UIRaycastCamera) to throw a null pointer exception.

Catch possible uiRaycastResult.module null value

---

Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/README.md

Overview
---
Hey guys, quick PR here to add control docs to the GrabMechanics readme.
Based on previous experience in WMR, and even another demo in this project, I had expected to use the motion control pointer to interact with the blocks. I searched the forum and saw some similar looking problems. I read this readme, but it didn't clarify anything for me, so I came to the conclusion that there must be a bug.
I was about to file an issue, but checked on closed issues and saw someone else had opened #1261 with the same problem, and that it was user error! The demo turned out really cool, and I'm really excited to start playing around with the scripts. I'm also hoping this update to the README will help the next guy along, as I don't think that closed issues are sufficiently discoverable. …

Add demo controls to GrabMechanics readme

---

Assets/HoloToolkit-Examples/Input/Scenes/InteractiveMeshCursor.unity
Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityTeleportEditor.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs

- Added an option "Stay on the floor" to actually stay in the same horizontal plane, regardless whether or not the user puts the teleport marker on something higher. 
- Added a cube to step on to the InteractiveMeshCursor to be able to test the above
- Fixed MixedRealityTeleportEditor because it did never serialize only three of the twelve properties it edits.

MixedRealityTeleport option to stay in same horizontal plane, fixed Editor

---

Assets/HoloToolkit/UX/Prefabs/BoundingBoxes/BoundingBoxBasic.prefab
Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBox.cs

Bounding box layer mask fix

---

Assets/HoloToolkit-Examples/UX/Scripts/InteractiveToggle.cs

Overview
---
Wanted to make a customized InteractiveToggle script which inherits from InteractiveToggle.cs and needed to change the ToggleLogic() mehtod (use a dynamic Unity bool Event). For this I need ToggleLogic() to be virtual and I think this could help others, as well, because in the current form it is not possible to implement a custom toggle logic.
Changes
---
Made ToggleLogic() virtual in InteractiveToggle

Make ToggleLogic virtual

---

Assets/HoloToolkit/Utilities/Scripts/Editor/CanvasEditorExtension.cs

Fix for setting worldCamera of a Canvas to null even when the user chose the UIRaycastCamera. This way way the user could only change the Canvas Camera to UIRaycastCamera when he deliberatly chose a wrong camera, so that the script kicked in and changed it for him.

Fix for setting worldCamera to null even when user chose UIRaycastCamera

---

Assets/HoloToolkit-Examples/Utilities/Scenes/SolverExamples.unity
Assets/HoloToolkit/Input/Scripts/Editor/AttachToControllerEditor.cs
Assets/HoloToolkit/Input/Scripts/Editor/AttachToControllerEditor.cs.meta
Assets/HoloToolkit/Input/Scripts/Editor/ControllerFinderEditor.cs
Assets/HoloToolkit/Input/Scripts/Editor/ControllerFinderEditor.cs.meta
Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs
Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/SolverHandlerEditor.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/SolverHandlerEditor.cs.meta
Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverHandler.cs

Overview
---
Fix for hidden members in AttachToController.  Second attempt.
This time I simply made ControllerFinder Abstract so no one could use it directly on a GameObject.  I couldn't think of any reason to really have it unless you needed to inherit anyway. (Mostly a helper).
Added a industry standard editor for SolverHandler to make sure we don't show the fields we didn't need to change.
Also added editors for the Controller Finder and Attach To Controller classes for aesthetics.
Changes
---
Fixes #1661

Fix for hidden members in AttachToController

---

Assets/HoloToolkit/UX/Scripts/Collections/ObjectCollection.cs

Column calculation was buggy because of some `int` math.  
As an Example, when calculating columns with a `NodeList.Count` of `4` and `Rows` of `5` (both are `int` values) the result is 0. That resulted in all CollectionNodes being positioned in one place.

Fixed int bug in column calculation of ObjectCollection

---

Assets/HoloToolkit-Examples/SpatialUnderstanding/Scripts/SpaceVisualizer.cs
Assets/HoloToolkit-Examples/SpatialUnderstanding/Scripts/UI.cs
Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDllTopology.cs

Add QueryTopology_FindLargestPositionsSittable() to Unity and update the Spatial Understanding demo with this query. This is the companion to: Microsoft/HoloToolkit#86
Note: this should replace Platforms #651.

Platforms2

---

Assets/HoloToolkit-Examples/Input/Scripts/DictationRecordButton.cs
Assets/HoloToolkit/Input/Scripts/InputSources/DictationInputManager.cs
Assets/HoloToolkit/UX/Scripts/Keyboard.cs

Overview
---
Added modal focus for the currently listening game object during dictation.
Changes
---
- Fixes: #1689

Dictation Focus

---

Assets/HoloToolkit/UX/Scripts/Buttons/CompoundButtonSpeech.cs

Overview
---
Using UnityEngine.Windows.Speech namespace prevents build for other platforms than UWP (e.g. iOS).
Platform dependent compilation is used in other places in code, e.g. HoloToolkit.UI.Keyboard.Keyboard
But it is missed in HoloToolkit.Unity.Buttons.CompoundButtonSpeech that prevents build for ios.

Fix build for non windows platforms

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs
Assets/HoloToolkit/Utilities/Scripts/Tagalong.cs

Resolved two issues that will become a problem in 2018, as they are fixable now it seems sensible to resolve them.
Overview
---
2018 highlighted some obsolete code / functions that were now removed.  The new versions of these functions exist now, so we should fix them ahead of them being a problem
Changes
---
- BuildsNSLTools updated to force conversion of it's build output to a string (as Unity will change it from a string to a Type)
- Changed the Destroy method used in Tagalong script (as destroyobject is scheduled for removal)
Remaining Issues
---
- EnumMaskField is being replaced with EnumFlagsField (but not in 2.17.2 build so cannot be fixed now)
- WSA Images are getting tidied up (removing old types and Phone), we should probably remove these now, but need to validate the effect on …

Resolve future issues... now

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs

Removed depreciated reflection methods that checked UWP version.  We verify installation in other places based on the presence of the Windows SDKs and vswhere in the build window itself.

Removed Build warning about SDK in 2017.3+

---

Assets/HoloToolkit/Utilities/Scripts/GLTF/Plugins/GLTFSerialization/GLTFSerialization.dll.meta
Assets/HoloToolkit/Utilities/Scripts/GLTF/Plugins/JsonNet/Newtonsoft.Json.dll.meta
Assets/HoloToolkit/Utilities/Scripts/GLTF/Shaders/GLTFStandard.shader

Overview
---
Issue mentioned at https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1708#issuecomment-364632400
This updates the glTF DLLs to be included for any build type not explicitly excluded, which allows for arbitrary build types to be selected without getting the "namespace GLTF cannot be found" error.
I only have the Android build type installed to test with, but the shader change fixes building there (no guarantee on it working, just building).

Fixing building glTF libraries for other build types

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs

Left some convenience buttons in the window.

Disabled the MRTK build window when the build target != UWP

---

Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/HandDraggable.cs

If you attach both RigidBody and HandDraggable to an object, then it will be affected by both gravity and the user's motion controller while dragging. The result is that it flops on the ground like a struggling flounder. This change turns off the influence that the physics engine has over the object while the user is in control of it.

Turn off the influence of the physics engine while dragging.

---

Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDll.cs
Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDllObjectPlacement.cs
Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDllShapes.cs
Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDllTopology.cs

Overview
---
Explicitly added calling convention to SpatialUnderstanding imports to prevent application from crashing when built using IL2CPP.
Changes
---
- Fixes: #1784 .

Changed SpatialUnderstanding DllImports to cdecl.

---

Assets/MixedRealityToolkit/UX/Materials/DialogBackPlate.mat
Assets/MixedRealityToolkit/UX/Materials/DialogBackPlate.mat.meta
Assets/MixedRealityToolkit/UX/Prefabs/Dialog.prefab

Overview
---
Replaced [Dialog UI control'](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_DialogsExample.md)s texture-based button with new shader-based HolographicButtons.
Dialog prefab file updated.

Updated Dialog UI with new HolographicButton component

---

Assets/MixedRealityToolkit-Examples/UX/Prefabs/ButtonHolographic.prefab
Assets/MixedRealityToolkit-Examples/UX/Prefabs/ToolBar.prefab
Assets/MixedRealityToolkit-Examples/UX/Scenes/InteractableObjectExample.unity
Assets/MixedRealityToolkit-Examples/UX/Scenes/ObjectCollectionExample.unity

Overview
---
Button objects in the InteractableObjectExample and ObjectCollectionExample scenes were missing profile. Assigned correct profile (HolographicButtonMeshProfile).

Fixed buttons with unassigned profiles in the example scenes

---

Assets/MixedRealityToolkit/Utilities/Scripts/Billboard.cs

Overview
---
Added support for all combinations of axes. I rearranged the enum to preserve existing behavior (the previous Free was actually only the X and Y axes).
Changes
---
- Fixes #1672, fixes #383, fixes #208.

Adding two-axis pivots, fixing free, and adding other missing axes to Billboard

---

Assets/HoloToolkit/Utilities/Scripts/Billboard.cs

Port of #1817.
Overview
---
Added support for all combinations of axes. I rearranged the enum to preserve existing behavior (the previous Free was actually only the X and Y axes).
Changes
---
- Fixes: #1672, fixes #383, fixes #208.

[Dev→master] Billboard updates

---

Assets/MixedRealityToolkit-Examples/Sharing/Scenes/SharingTest.unity
Assets/MixedRealityToolkit-Examples/SpatialMapping/Scenes/TapToPlace.unity
Assets/MixedRealityToolkit/SpatialMapping/Scripts/TapToPlace.cs
Assets/MixedRealityToolkit/SpatialMapping/Scripts/TapToPlaceColliderPlacement.cs
Assets/MixedRealityToolkit/SpatialMapping/Scripts/TapToPlaceColliderPlacement.cs.meta

Introduces the ability to use other parts of the collider like top or bottom, useful for common scenarios where user wants to place the object on the floor or ceiling.
Used the TapToPlace scene to test combinations (DontUse, UseCenter, UseBottom and UseTop) to validate the desired behavior.

TapToPlace: extends the usage of collider to place objects

---

Assets/HoloToolkit/Utilities/Scripts/FixedAngularSize.cs

Overview
FixedAngularSize was previously using Update to adjust the element's visible size. This caused a flicker when applied to a cursor and this update came before the update performed by the GazeManager (as reported in #1831).
Changes
---
* Replaced Update with LateUpdate to ensure the scaling occurs after other modifications.
* Encapsulated the SizeRatio field per the pending code style guide and applied a range check in the setter.
* Add a range to SizeRatio (was defined as 0 - 1 in SetSizeRatio())
* Add summary tag comments throughout.
- Fixes: #1831 .

[master] fixes #1831 - replace update with lateupdate in FixedAngularSize

---

Assets/MixedRealityToolkit/Common/Scripts/Editor/StandardShaderGUI.cs
Assets/MixedRealityToolkit/Common/Shaders/Standard.shader

Overview
---
Integrating the latest work to improve the MRTK/Standard shader.  Improvements include softer (anti aliased) borders, a lighting model closer to the Unity/Standard shader (see below), and other minor fixes.
This pull request brings the MRTK/Standard shader up to parity with this [pull request.](https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1847#issuecomment-375453871)
The Unity/Standard shader is on the left and MRTK/Standard shader is on the right. (Note the specular highlight improvements and accurate shading on the bottom right of the grid as the gif toggles from old to new.)

Lighting Improvements to the MRTK/Standard Shader

---

Assets/HoloToolkit/UX/Scripts/Collections/ObjectCollection.cs

Fixes issue with GameObject staying in NodeList even though it is not a child anymore.
Overview
---
Remove GameObject from NodeList, when it is not a child of this.transform anymore
!NodeList[i].transform.IsChildOf(this.transform))
Changes
---
- Fixes: #1868

[master] Update ObjectCollection.cs

---

Assets/HoloToolkit/UX/Scripts/Collections/ObjectCollection.cs

The previous test using "IsChildOf" did process deep children also, that are not supposed to be considered for layout purposes in this case.
An additional test for "transform.parent == null" is necessary to a) allow transform.parent.gameObject to evaluate and b) to account for nodes that are now in the root of the scene hierarchy.
Overview
---
`!NodeList[i].transform.IsChildOf(this.transform)`
did also consider DeepChildren to be proper children, for layout purposes we only want direct children.
`NodeList[i].transform.parent==null`
checks if a GameObject is in the root of the scene. If so, then it should not participate in the layout of ObjectCollection, also a subsequent test to compare the parent would fail.
`!(NodeList[i].transform.parent.gameObject==this.gameObject)`
is an exact test …

Replace "IsChildOf" test with exact parent test

---

Assets/MixedRealityToolkit-Examples/SpatialUnderstanding/Scripts/AppState.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/CustomInputSource.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/InteractionInputSource.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/SupportedInputInfo.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/TouchscreenInputSource.cs
Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/Interactions/DebugInteractionSourcePose.cs
Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/Interactions/HandDraggable.cs

Overview
---
WSA input sources do not currently report their capabilities correctly in regards to Pointer position/rotation and grip position/rotation. This PR attempts to fix the situation by adding GripPosition/GripRotation input info types, and clearly differentiating between the Pointer and Grip types. InteractionInputSource and a number of related classes are updated to accommodate use of the new types.
Changes
---
* added PointerPosition (Position-equivalent), PointerRotation (Rotation-equivalent), GripPosition and GripRotation  to SupportedInputInfo enumeration
* deprecated existing Position and Rotation enum ids
- Fixes: #1824 .

Adding GripPosition and GripRotation to SupportedInputInfo and adding support to WSA input source and related classes

---

Assets/HoloToolkit-Examples/UX/Prefabs/CheckBox.prefab
Assets/HoloToolkit-Examples/UX/Prefabs/CheckBoxSet.prefab
Assets/HoloToolkit-Examples/UX/Prefabs/Radial.prefab
Assets/HoloToolkit-Examples/UX/Prefabs/RadialSet.prefab

Overview
When a radial button's selected state is off, the radialDot gameObject is set to inactive. When this happens the widget on the gameObject removes itself from the list of widgets in the Interactive and causes the warning. This is expected behavior, when a gameObject with a widget should not receive updates from Interactive.
Changes
Moved the widget from the RadialDot to another gameObject (Outline) that does not become inactive.
- Fixes: #1857.

Removed a warning when the radial dot is set to inactive

---

Assets/MixedRealityToolkit/InputModule/Scripts/Focus/FocusManager.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputManager.cs
Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/CustomInputSource.cs

Overview
---
Updated Focus Manager `TryGetFocusedObject` to make sure we set the pointer data's selected object with the focus details.
Also added a null check in the Input Manager's `RaiseInputUp` and `RaiseInputDown` methods before we execute the pointer handlers for the `UnityEngine.Graphic` objects.
Changes
---
- Fixes: #1872

Fixed null ref when pointer data does not have a selected object.

---

CONTRIBUTING.md
DocumentationGuide.md

Write documentation guidelines file based on the v.Next Documentation proposal (#1814). Add steps (and links to the Coding/Documentation guidelines) in the Implementation section of CONTRIBUTING,md to improve process clarity and visibility.
- Fixes: #1893.

Write documentation guidelines document

---

Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBarButton.cs

Overview
---
App Bar's Done/Hide menu button stays highlighted once you enter/exit the adjust mode.
In Show() and Hide(), added code for disabling/enabling the render of the highlighting mesh.
Changes
---
- Fixes: #1877

App Bar highlighted state bug fix #1877

---

Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs

- changed if (enabled) -> if (enabled && !m_disabled) in OnInputDown, OnInputUp and OnInputClicked.
- added encapsulation of serialized fields per vNext coding style guidelines
Fixes: #1827.

[Patch4] fix #1827 (disabled state handling)

---

Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/SpeechInputHandler.cs

Fix so recognized text "example_keyword" and keyword added with SpeechInputSource "example_keyword " (notice the extra space) are treated equally
Appending an extra space when adding keywords is an easy to make mistake and also easy to miss while debugging, causes events not being raised even though keyword is correctly recognized

Trim end of keywords

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPortal.cs
Assets/HoloToolkit/Common/Scripts/Extensions/InteractionSourceExtensions.cs
Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs
Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxGizmoHandle.cs
Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxRig.cs
Assets/HoloToolkit/Utilities/Scripts/AtlasReferenceUpdater/AtlasPrefabReference.cs
Assets/HoloToolkit/Utilities/Scripts/AtlasReferenceUpdater/Editor/AtlasReferenceUpdater.cs
Assets/HoloToolkit/Utilities/Scripts/AtlasReferenceUpdater/Editor/Extensions/SpriteAtlasExtensions.cs

There have been a number of instances of APIs used in recent master and Patch4_Dev branch checkins that are not supported on Unity 5.6 and 2017.1.  Add #if version checks around them, and where appropriate use a preprocessor warning directive to alert users to the functionality limitations.
- Fixes: #1958 
- Fixes: #1960 
- Fixes: #1962
- Fixes: #1964

[2017.2.1.4] Fix building on Unity 5.6 and 2017.1

---

Assets/HoloToolkit-Examples/UX/Scenes/BoundingBoxGizmoExample.unity
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs

Disables the logic in OnTwoHandManipulationStarted, OnTwoHandManipulationEnded and OnTwoHandManipulationUpdated for Unity 2017.1 and older.
Also adds a message in the test scene noting the above.
Fixes: #1967 .

[Patch4] Disable two hand manipulation for Unity versions prior to 2017.2

---

Assets/HoloToolkit-Examples/Sharing/SharingService/Scripts/UserNotifications.cs
Assets/HoloToolkit-Examples/UX/Scripts/ExampleData/NoteDataProvider.cs
Assets/HoloToolkit-Examples/UX/Scripts/InteractiveGroup.cs
Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Assets/HoloToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs
Assets/HoloToolkit/Common/Scripts/Extensions/EnumerableExtensions.cs
Assets/HoloToolkit/SpatialMapping/Shaders/SpatialMappingTap.shader

Overview
---
Reverts misattributed license headers. Also, removes some copyright headers that were added incorrectly.
Changes
---
- Fixes: #1931 for the next patch release.

[Patch4] Revert misattributed license headers

---

Assets/MixedRealityToolkit-Examples/Sharing/Scripts/UserNotifications.cs
Assets/MixedRealityToolkit-Examples/UX/Scripts/ExampleData/NoteDataProvider.cs
Assets/MixedRealityToolkit-Examples/UX/Scripts/InteractiveGroup.cs
Assets/MixedRealityToolkit-UnitTests/Editor/Utilities/Extensions/EnumerableExtensionsTests.cs
Assets/MixedRealityToolkit-UnitTests/Editor/Utilities/WorldAnchorManagerTests.cs
Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Assets/MixedRealityToolkit/BuildAndDeploy/Editor/XdeGuestLocator.cs
Assets/MixedRealityToolkit/Common/Scripts/Extensions/EnumerableExtensions.cs
Assets/MixedRealityToolkit/SpatialMapping/Shaders/SpatialMappingTap.shader

Overview
---
Reverts misattributed license headers. Also, removes some copyright headers that were added incorrectly.
Changes
---
- Fixes: #1931 in dev.

[Dev] Revert misattributed license headers

---

ProjectSettings/ProjectSettings.asset

Overview
---
In the current Master build, the Version set in the ProjectSettngs file for new projects breaks WACK, as MS demands the final value on the app version to be 0.
Changes
---
Changes version numbers of 2017.2.1 in the Project Settings asset
to 2017.2.0.0

Wack version fix

---

Assets/HoloToolkit/Utilities/Scripts/FpsDisplay.cs

FpsDisplay was repeatedly fetching components if the user did not use both a TextMesh and a uGui Text component. Fixed by adding Start() and calling InitBuffer there instead of in Update.
Also added a range (1-300) to the number of frames used to calculate FPS and some documentation comments.
Fixes: #1913 .

fix fpsdisplay perf, add comments and frame range

---

Assets/HoloToolkit/Utilities/Scripts/FpsDisplay.cs

Remove the unneeded RequiredComponent attribute that force adds a TextMesh.
Fixes: #2006

[may18] remove required component from fpsdisplay.cs (#2006)

---

Assets/HoloToolkit-Examples/UX/Prefabs/Button.prefab
Assets/HoloToolkit-Examples/UX/Prefabs/ToggleButton.prefab

There are two unused colliders on Button.prefab and ToggleButton.prefab from the Examples\UX\Prefabs folder. Similar buttons in the main HoloToolkit\UX folder do not have these sub-object colliders.
Removing them to reduce confusion.
Fixes: #1969 .

Remove unused box colliders from example scene button prefabs

---

Assets/HoloToolkit-Examples/SpatialUnderstanding/Scenes/SpatialUnderstandingExample.unity
Assets/HoloToolkit/SpatialUnderstanding/Materials/SpatialUnderstandingSurface.mat

Overview
---
Spatial Understanding example scene UX refinement (SpatialUnderstandingExample.unity)
- Updated material colors to make it similar to Fragments' visual mesh
- Added MRTK logo + scene title
- Refined app state text with smooth tag-along 
- Updated fonts to Selawik
Changes
---
Scene and material updates. No code changes.
Before & after screenshots (MRC picture is somewhat different from actual visual)

[May18] Spatial Understanding example scene UX refinement

---

Assets/MixedRealityToolkit-Examples/MixedRealityToolkit-Examples.asmdef
Assets/MixedRealityToolkit-Examples/MixedRealityToolkit-Examples.asmdef.meta
Assets/MixedRealityToolkit-SDK/MixedRealityToolkit-SDK.asmdef
Assets/MixedRealityToolkit-SDK/MixedRealityToolkit-SDK.asmdef.meta
Assets/MixedRealityToolkit-SDK/Profiles/Mixed Reality Configuration Default Profile.asset
Assets/MixedRealityToolkit-SDK/Profiles/Mixed Reality Configuration Default Profile.asset.meta
Assets/MixedRealityToolkit-Tests.meta
Assets/MixedRealityToolkit-Tests/MixedRealityManagerTests.asmdef
Assets/MixedRealityToolkit-Tests/MixedRealityManagerTests.asmdef.meta
Assets/MixedRealityToolkit-Tests/MixedRealityManagerTests.cs
Assets/MixedRealityToolkit-Tests/MixedRealityManagerTests.cs.meta
Assets/MixedRealityToolkit/Boundary/MixedRealityBoundarySystem.cs
Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/MixedRealityToolkit.asmdef
Assets/MixedRealityToolkit/MixedRealityToolkit.asmdef.meta
Assets/MixedRealityToolkit/_Core/Definitions/BaseManager.cs
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Interfaces/IMixedRealityManager.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs.meta
External/Documentation/MixedRealityManagerConstruction.md

Overview
---
Updated the Mixed Reality manager to now also support runtime Managers.  Main difference is that design time managers are unique (e.g. InputSystemManager) whereas there maybe many runtime managers.
Also added support for the Disable and Enable MonoBehaviour functions.
See "/External/Documentation/MixedRealityManagerConstruction.md" for more details
Also added some simple Unit Tests (WIP) for the MR Manager, to test DI implementation and use.
Changes
---
- Fixes: Resolved some null reference issues when initialising
- Fixes: Singleton pattern updated in manager to be Unit Test Friendly
- Additions: Assembly refs added for Unit Testing only atm.  For further review.
TODO
---

Updated the Mixed Reality manager to now also support runtime Managers.

---

Assets/HoloToolkit/Input/Prefabs/Cursor/Cursor.prefab
Assets/HoloToolkit/Input/Prefabs/Cursor/CursorWithFeedback.prefab
Assets/HoloToolkit/SpatialSound/Scripts/AudioEmitter.cs
Assets/HoloToolkit/Utilities/Scripts/Billboard.cs

Overview
---
Some minor updates that were found while updating the Academy courses to the most recent Toolkit release.
Partner PR to #2036.
Changes
---
- Fixes: #1983.

[May18] Cursor light fix (and other minor fixes)

---

Assets/MixedRealityToolkit/UX/Prefabs/Text/3DTextSelawikBold.prefab
Assets/MixedRealityToolkit/UX/Prefabs/Text/3DTextSelawikLight.prefab
Assets/MixedRealityToolkit/UX/Prefabs/Text/3DTextSelawikSemibold.prefab
Assets/MixedRealityToolkit/UX/Prefabs/Text/3DTextSelawikSemilight.prefab

Four of the 3DTextPrefabs had no material for their MeshRenderer.
- Selawik Bold
- Selawik Light
- Selawik Semibold
- Selawik Semilight

Updated 3DTextPrefab materials

---

Assets/HoloToolkit-Examples/SpatialUnderstanding/Scripts/AppState.cs
Assets/HoloToolkit/Input/Scripts/InputSources/CustomInputSource.cs
Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs
Assets/HoloToolkit/Input/Scripts/InputSources/SupportedInputInfo.cs
Assets/HoloToolkit/Input/Scripts/InputSources/TouchscreenInputSource.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/DebugInteractionSourcePose.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/HandDraggable.cs

Overview
---
Adding GripPosition and GripRotation to SupportedInputInfo and adding support to WSA input source and related classes, originally submitted in Dev_Working_Branch as PR #1870. Now 'cherry picked' and submitted for the May18 release in the original HoloToolkit hierarchy.
Changes
---
* added new input info types to SupportedInputInfo;
PointerPosition and PointerRotation have equivalence to, and deprecate, Position and Rotation;
GripPosition and GripRotation extend the bitfield
* InteractionInputSource now reports support for grip position & rotation; replaced deprecated type id's with replacements
* replacing use of deprecated SupportedInputInfo types in simple use cases
* adding support for GripPosition/Rotation, and updating uses of now-deprecated Position/Rotation type enums, …

'Cherry pick' of work previously committed to Dev_Working with PR #1870:

---

Assets/HoloToolkit-Examples/Input/Scenes/TwoHandManipulationTest.unity
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/ManipulationMode.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/ManipulationMode.cs.meta
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatableMode.cs

Overview
---
Update private SetManipulationMode to public in TwoHandManipulatable.cs. This allows the user change manipulation mode option in real-time. (possibly through menu buttons or voice command) Currently, it is only supported in the editor's inspector panel.
Separated enum TwoHandManipulatableMode into a new file.
FYI, supported manipulation mode:
- Scale
- Rotate
- Move, Scale
- Rotate, Scale
- Move, Rotate, Scale
Changes
---
- Fixes: #1994

[may18] Update SetManipulationMode to public in TwoHandManipulatable

---

Assets/HoloToolkit/Utilities/Prefabs/HeadsetAdjustmentDisplay.prefab
Assets/HoloToolkit/Utilities/Prefabs/HeadsetAdjustmentDisplay.prefab.meta
Assets/HoloToolkit/Utilities/Scenes/HeadsetAdjustment.unity

At some point in late 2017, the camera object in the HeadsetAdjustment.unity scene lost the canvas that displayed the message and bounding box.
This change creates HeadsetAdjustmentScene.prefab and adds it as a child of the camera in the scene.
Fixes: #1935

Fix headadjustment scene not displaying content

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPortal.cs
Assets/HoloToolkit/Input/Scripts/InputSources/CustomInputSource.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/HandDraggable.cs
Assets/HoloToolkit/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs
Assets/HoloToolkit/SpectatorView/Scripts/Networking/SpectatorViewNetworkDiscovery.cs
Assets/HoloToolkit/SpectatorView/Scripts/Networking/SpectatorViewNetworkManager.cs
Assets/HoloToolkit/SpectatorView/Scripts/SpatialSync/CameraCaptureHololens.cs
Assets/HoloToolkit/SpectatorView/Scripts/SpatialSync/MarkerDetectionHololens.cs
Assets/HoloToolkit/UX/Prefabs/Text.meta

Add UNITY_2017_1_OR_NEWER blocks (and modify some existing 2017_2 blocks) to eliminate the API conversion popup when loading the MRTK in Unity 2017.1
There isn't an issue for this, it is an extension of #1921.

Eliminate API conversion popup when loading in Unity 2017.1

---

Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs

Changed <= to > when comparing _handCount against zero in OnSourceLost. This fixed our inability to return to ObservationTargeted and Observation button states
Changes
---
- Fixes: #1887.

fix #1887, src lost had a backwards compare

---

Assets/HoloToolkit/Common/Scripts/Singleton.cs
Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs

Overview
---
Eliminates NullReferenceException when using the Solver System if the MotionControllers prefab is not in the scene (typically attached to the camera)
Changes
---
- Adds ConfirmInitialized() to Singleton<T> (back-port from Dev_Working_Branch)
- Checks that the MotionControllerVisualizer has been initialized in ControllerFinder.OnEnable()
- Fixes: #2053.

handle case of no MotionControllerVisualizer singleton

---

Assets/MixedRealityToolkit/Utilities/Scripts/Solvers/SolverBodyLock.cs

Overview
---
If the tracked object isn't present, [line 65](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverBodyLock.cs#L65) null refs when trying to access transformTarget.
#2078 for the dev branch.
Changes
---
- Fixes: #2073

[Dev] Fixes SolverBodyLock potential null ref

---

Assets/MixedRealityToolkit/UX/Scripts/Keyboard/KeyboardInputField.cs

Bring fix (from may18_dev) for not being able to clear the input field when backspacing over the last character.
- Fixes: #917, #1169, #1927, #1979 .

[dev] fix #917 and duplicate kbd backspace issues

---

Assets/HoloToolkit/UX/Scripts/KeyboardInputField.cs

Directly set the text value to what is provided in the newText argument of Keyboard_OnTextUpdated.
The previous (broken) implementation failed to set the text value if newText was null or the empty string
- Fixes: #917, #1169, #1927, #1979

fix backspace not clearing the last character in the field

---

Assets/MixedRealityToolkit-Examples/SpatialMapping/Scripts/PlaneFindingTest.cs
Assets/MixedRealityToolkit/SpatialMapping/Scripts/SpatialProcessing/Editor/SurfaceMeshesToPlanesEditor.cs
Assets/MixedRealityToolkit/Utilities/Scripts/Editor/EditorGUIExtensions.cs

Overview
---
Pair PR of #2060, addressing https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2060#issuecomment-387520905.
Adding support for changed 2017.3 APIs and removing warnings from deprecated APIs.

[Dev] Updating scripts to support 2017.3

---

Assets/HoloToolkit/UX/Textures/KeyboardAtlas.spriteatlas

Overview
---
Without this, symbols dependent on the spriteatlas don't load:
After:
The atlas was un-defaulted in https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/0033c67f59ca6b5703c892258354c977f2c7ee98.
Pair PR to #2121.
Changes
---
- Fixes: #1852

[May18] Set KeyboardAtlas as default

---

Assets/MixedRealityToolkit/UX/README_TextPrefab.md.meta
Assets/MixedRealityToolkit/UX/Textures/KeyboardAtlas.spriteatlas

Overview
---
Without this, symbols dependent on the spriteatlas don't load:
After:
The atlas was un-defaulted in https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/0033c67f59ca6b5703c892258354c977f2c7ee98.
Pair PR to #2120.
Changes
---
- Related to: #1852
This PR also addresses https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2029#discussion_r189128675

[Dev] Set KeyboardAtlas as default 

---

Assets/HoloToolkit/Input/Prefabs/LeftHandInputControl.prefab
Assets/HoloToolkit/Input/Prefabs/RightHandInputControl.prefab
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/CustomInputControl.cs

Overview
---
Fixes an issue introduced #1870 (& #2050 ) whereby the in-Editor hands no longer report their position, if data is requested through `TryGetGripPosition`
Changes
---
- Fixes: #2131  .

Fix to allow in-Editor hands to properly support and report a 'grip' position

---

Assets/HoloToolkit/SpectatorView/Scripts/SpatialSync/MarkerDetector.cs
Assets/HoloToolkit/SpectatorView/Scripts/Utilities/OpenCVUtils.cs

Overview
---
The SpectatorView feature references, but does not ship a companion dll (it must be built from https://github.com/microsoft/mixedrealitytoolkit and added to the project by the app developer). As a result, the .net native compiler (used for master builds) cannot resolve the pinvokes and reports warnings.
Changes
---
Tell the .net native compiler that it can trust the pinvoke calls by setting ExactSpelling=true in the DllImport attribute.
- Fixes: #2126

eliminate .net native pinvoke warnings

---

Assets/MixedRealityToolkit-Examples/StandardShader/Animations/RoundedCorner.anim
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/CubeBorderRoundedOpaque.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/CubeEnvironmentColor.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorder.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderBlue.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderCyan.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderGreen.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderOrange.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderPink.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderPurple.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderRed.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/PanelBorderRoundedBlue.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/ShaderBallGlass.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/ShaderBallNearPlaneFade.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/ShaderBallNormalMap.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Materials/ShaderBallNormalMapTransparent.mat
Assets/MixedRealityToolkit-Examples/StandardShader/Prefabs/Placard.prefab
Assets/MixedRealityToolkit/Common/Scripts/HoverLight.cs
Assets/MixedRealityToolkit/Common/Shaders/Standard.shader

Overview
---
Integrating the latest work to improve the MRTK/Standard shader. Improvements include:
- Support for non-D3D11 APIs (tested on iOS and Android devices using OpenGL ES and Metal)
- Support for three hover lights (useful with IHMDs with multi-pointers)
- Improved rounded corner algorithm
- Closer match to the Unity/Standard shader
- Improved shader based anti-aliasing support
- Minor optimizations
(Shader based anti-aliasing example.)

MRTK/Standard Shader Improvements

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs

Overview
---
Previously, the fade manager was potentially (script execution order, etc) being checked in cases where it isn't supported anyway.
Changes
---
- Fixes: #1790

[May18] Slightly adjusts the order Teleport unsupported checks happen

---

Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/Interactions/TwoHandManipulatable.cs

Updated TwoHandManipulatable to use `HostTransform` for `BoundingBoxRig`.

HostTransform for TwoHandManipulatable

---

Assets/MixedRealityToolkit/SpatialMapping/Scripts/RemoteMapping/FileSurfaceObserver.cs
Assets/MixedRealityToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMappingManager.cs
Assets/MixedRealityToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMeshTarget.cs

Extend the RemoteMeshTarget so it can not only be used in the Unity Editor to receive a mesh from a Hololens but also within UWP Immersive Windows Mixed Reality applications. Also allow the saving and loading of a mesh file from an UWP app.

Allow remote mapping to UWP / Immersive Windows MR apps

---

Assets/HoloToolkit/UX/Scripts/Keyboard.cs

Overview
---
This sets the slider input field in the MRTK keyboard to have a keyboardType that isn't defined, which prevents a keyboard from popping up.
This PR does not address the situation where both the MRTK and the system keyboard pop up on other input fields. This only addresses the situation where the MRTK keyboard triggers the system keyboard itself.
Changes
---
- Fixes: #1940

[May18] Disable keyboard for the MRTK keyboard's inputfield

---

Assets/HoloToolkit/Input/Prefabs/LinearControllerPointer.prefab
Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs
Assets/HoloToolkit/Input/Scripts/Focus/SimpleSinglePointerSelector.cs
Assets/HoloToolkit/Input/Scripts/Utilities/BaseControllerPointer.cs
Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs
Assets/HoloToolkit/Input/Scripts/Utilities/PointerLine.cs

Overview
---
This PR updates the pointing ray visualization to extend out the full length of the pointer's pointing extent (or the FocusManager's default, if no override is specified), instead of the previous cursor default.
This is implemented in a way to preserve the default behavior of the Gaze cursor being placed at 2m, which is closer than the default pointing extent.
Changes
---
- Fixes: #2166.

[May18] Updating pointing rays to extend out to the pointing extent off holograms

---

Assets/HoloToolkit/Utilities/Scripts/Solvers/Solver.cs

Overview
---
Just switches a != null to a == null so it yields whenever the element transform doesn't exist, rather than yielding when it does.

Fixed a bug where solvers would try to attach to the right hand before it was ready

---

Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverRadialView.cs

Overview
---
Removed the flip check which caused a temporary gimble lock when the solver was used in small numbers < .01.
Works as expected now.
Changes
---
- Fixes: 1
SolverRadialView.cs

Eliminated unnecessary check that resulted in bad behavior at short distances

---

Assets/HoloToolkit-Preview/SpectatorView/Scripts/Utilities/ARMarkerController.cs

Overview
---
The UnityEngine.Handheld class doesn't exist when building for Standalone (it probably doesn't exist in some number of other non-handheld platforms as well).
Since SV only supports iOS at the moment, I wrapped the call in `#if UNITY_IOS`.
Changes
---
- Fixes: #2225.

Fixing building for Standalone

---

Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs
Assets/HoloToolkit/Utilities/Scripts/BoundingBoxHelper.cs.meta

Overview
---
BoundingBoxHelper is [only used with the `new` keyword](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/june18_dev/Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs#L249), which throws a Unity warning when called on MonoBehaviours.
Also, the meta file wasn't included.

Added the missing meta file and removing MonoBehaviour from BoundingBoxHelper

---

Assets/HoloToolkit/UX/Scripts/UICollection.cs

Overview
There was a bug with the keyboard (#1744) which causes the first button in each row to not appear or at least be positioned correctly.
Please note, the bug fixed by this Pull Request was deemed to be a Unity bug that has now been reported as fixed so perhaps this pull request can be ignored.
However, I am still leaving this code in my local respository for the slight performance improvement since the layouts never need to be updated at runtime.   Each keyboard layout is saved as a child gameObject so if you switch between layouts this code never needs to be called.  The only reason I can think of is if you try to customize the keyboard at runtime, but in that case you should just call update layout manually.  
Perhaps I am missing something? @keveleigh
Changes
Each of the layouts …

Keyboard Fix for Missing Keys Bug

---

ProjectSettings/ProjectSettings.asset
ProjectSettings/ProjectVersion.txt

Bumped version to 2018.1.3f1 and changed the scripting runtime to 4.x so we get player projects generated.

vNEXT Editor Update

---

Assets/HoloToolkit/Input/Scripts/InputSources/DictationInputManager.cs

Overview
---
FinishStopRecording() uses variables that are only declared in Unity Windows platforms without checking if it's in a Unity Windows platform itself. This fix simply adds this check, so that Unity will not throw errors on non-Windows computers for variables not existing in the scope.
Changes
---
- Adds checks for Unity Windows platform in FinishStopRecording() and simply returns null if not in a Unity Windows Platform.

Fixed FinishStopRecording() error on non-Windows platform

---

Assets/MixedRealityToolkit-Tests/InteractionDefinitionTests.cs
Assets/MixedRealityToolkit/_Core/Definitions/Devices/InteractionMapping.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenXR/OpenXRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/Simulator/SimulatedDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/WindowsGamingDevice.cs
Assets/MixedRealityToolkit/_Core/Extensions/CollectionsExtensions.cs

Overview
---
The generic Get|SetValue methods , as asserted in the test cases, were slower (and produced garbage) than their specific counterparts.
Changes
---
This change:
* removes the generic GetValue<T> and SetValue<T> methods
* renames the Get<type> methods (ex: GetRaw -> GetRawValue)
* updates calling code
* removes test cases that utilized the generic methods
* renumbered the test cases to eliminate the gaps that were introduced

Remove InteractionMaping Get|SetValue<T> and update relevant tests

---

Assets/MixedRealityToolkit/_Core/Attributes/ExtendsAttribute.cs
Assets/MixedRealityToolkit/_Core/Attributes/ImplementsAttribute.cs
Assets/MixedRealityToolkit/_Core/Definitions/Devices/ControllerState.cs
Assets/MixedRealityToolkit/_Core/Definitions/Devices/Headset.cs

Overview
---
Found some references to the Microsoft.MixedReality.Toolkit.Internal.Extensions that should be in closed in #if WINDOWS_UWP && !ENABLE_IL2CPP.
Added IsOpaque to the headset definition to allow differentiation between opaque (vr) and see through (ex: HoloLens).
Also tweaked controller state comments and added OrientationOnly state.

add #if around extensions namespace as appropriate, add IsOpaque

---

CodingGuidelines.md

There were some errors in CodingGuidelines.md including:
* Incorrect namespace
* Shifting 0
* Spaces in enum values
* Spelling errors

fix assorted errors in the CodingGuidelines doc

---

Assets/MixedRealityToolkit-Tests/InteractionDefinitionTests.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenXR/OpenXRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/Simulator/SimulatedDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/WindowsGamingDevice.cs
Assets/MixedRealityToolkit/_Core/Extensions/CollectionsExtensions.cs

Overview
---
Added tests for how the InteractionMappings are used in the device space.  Highlighting the issues now created by removing the generics functions.  These tests all fail with the following error (simply because SETVALUE cannot distinguish a type like Get can)
SetValue(object) is only valid for AxisType.Raw InteractionMappings
Also added another extension for the InteractionMapping Dictionary as I missed that changed was updated between gets.
Known Issues
---
Tests now fail as Dictionary updates ONLY update the raw data type without the generic SET method.
Changes
---
- Added Dictionary Tests for InteractionMappings
- Added new InteractionMapping Dictionary extension to allow changed to be updated for a mapping
- Updated used of "Changed" in the devices to use the new …

Added tests for InteractionMappings dictionary

---

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
Assets/HoloToolkit/Input/Scripts/Cursor/InteractiveMeshCursor.cs

InteractiveMeshCursor was unknowingly hiding Cursor's Awake. This wasn't an issue previously, since the only thing in Awake actually didn't really do anything due to a different bug (also fixed here). 
Update Cursor to make its Awake (and others) overridable.
This commit also exposes `isVisible` in the Editor, as the comment in
Awake() indicates that it should be settable before startup.
Also, removes an extra SetVisibility call that already happens in the
public setter.
Fixes #2294.

Properly expose MonoBehaviour methods in Cursor.cs

---

Assets/HoloToolkit-Examples/SharingWithUNET/Materials/ButtonBackground.mat
Assets/HoloToolkit-Examples/SharingWithUNET/Prefabs/UIContainer.prefab
Assets/HoloToolkit-Examples/SharingWithUNET/Scenes/SharingWithUnetExample.unity
Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/GenericNetworkTransmitter.cs
Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/UNetAnchorManager.cs
Assets/HoloToolkit/Utilities/Scripts/ApplicationViewManager.cs

Overview
---
Updates some `#if`s from #2127 to run on all build configurations except the intended IL2CPP && .NET Standard 2.0. This was blocking Sharing with UNET from working.
This also contains some minor changes to the scene to bring it up-to-date with the latest components.
Changes
---
- Fixes #2276, fixes #2303

Re-enable Sharing with UNET

---

Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs
Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityCameraProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityManagerInspector.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs

- We were having issues with active profiles being registered to the Mixed Reality Manager whenever we crated a new scene and selected a config profile.
- I also added a Quickstart menu under Mixed Reality Toolkit menu to generate the Mixed Reality Manager in the scene if none exists.
- Updated how we create profiles.
- Updated Camera Profile Inspector to match the rest of the profiles.
- Fixed Profile Activation crashing if it's null or unset.

Fixed some Profile Serialization Issues and added Quickstart Menu

---

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityGestureController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/GenericOpenVRController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/HTCViveController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OculusTouchController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/ValveKnucklesController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenXR/GenericOpenXRController.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenXR/OpenXRDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/Simulator/SimulatedController.cs
Assets/MixedRealityToolkit/_Core/Devices/Simulator/SimulatedDevice.cs
Assets/MixedRealityToolkit/_Core/Devices/Simulator/SimulatedHandController.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/ArcadeStickController.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/GamepadController.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/JoystickController.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/RacingWheelController.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/WindowsGamingDevice.cs
Assets/MixedRealityToolkit/_Core/Utilities/DebugUtilities.cs

The controller classes (deriving from IMixedRealityController) were marked as public. Since apps should not have access to them and should be getting their data via the interface, therefore I have marked them as internal.
The device classes (deriving from IMixedRealityDevice) had inconsistent visibility. Some were private and others public. Similar to the controllers, there is no need for these classes to be available to applications. Since WindowsMixedRealityDevice had the most restrictive visibility and is what we have successfully used, I have made them all private.
While not strictly related, the intent of adjusting the visibility of classes is to enable use of asserts during development and free the release/master builds from needing to check for situations that should not be …

update class visibility and add runtime assert/logging

---

Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxGizmoHandle.cs
Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxRig.cs

Overview
---
This PR is a rebase and retarget of the commit from @paulmriordan's PR #2160. That PR had been inactive for a month.
To quote @paulmriordan in #2160:
>Current method of rotation is not consistent; the object is rotated different directions
>depending on orientation of object.
>This commit adds an option (rotateAroundPivot) which allows the user to rotate an object in a more >natural way.
>To avoid breaking existing usage, this new rotation is enabled via a bool in BoundingBoxRig.
> Existing behaviour:
> ![boundingboxgizmoold](https://user-images.githubusercontent.com/4314853/40498945-6573e890-5f78-11e8-9268-0dd08701ffd2.gif)
> 
> New behaviour:
> ![boundingboxgizmonew](https://user-images.githubusercontent.com/4314853/40498949-68375396-5f78-11e8-82d1-36e322d07808.gif)

[June retarget] Fix for dragging of rotation handles of BoundBoxRig

---

Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scripts/BaseGrabber.cs

Sort method was comparing distance of first object to itself, rather than second object
Overview
---
This PR is a rebase and retarget of the commit from @paulmriordan's PR #2159. That PR had been inactive for a month.

[June retarget] Fix for choosing closest grabbable object to grab

---

Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs
Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs.meta

Overview
---
Fixed #2295. Marked eventData objects as used inside Button to ensure events do not propagate to downstream handlers.
Changes
---
- Fixes: # 2295.

Button.cs eventData fixes

---

Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs

Overview
---
Previously, the data was removed before the event was fired. This caused any queries back about the data while handling the event to fail.
This was found during Button.cs investigation, and subsequent PRs will be opened following this change.

Fixes an InteractionInputSource bug where data was removed too soon

---

Assets/HoloToolkit-Preview/SpectatorView/Scripts/Recording/ReplayKitRecorder.cs

Overview
---
`Controls` was calling itself instead of the backing field, thus becoming recursive.
I also updated some of the documentation and `Debug.Log`s.
Changes
---
- Fixes: #2165

Spectator View recursive fix

---

Assets/HoloToolkit-Examples/Input/Scenes/InputManagerTest.unity
Assets/HoloToolkit-Examples/Input/Scripts/PopupMenu.cs
Assets/HoloToolkit-Examples/Input/Scripts/TestButton.cs

Overview
---
The PopupMenu was consuming `OnInputDown` and `OnInputUp` events, while it seemed like it should consume (and other similar components were using) `OnInputClicked`. I reworded the example scene to be clearer, and also decreased the number of places states were being handled. The PopupMenu routes its "close" input handling through a button, but was also receiving its own input. Now, everything goes through the button.
Changes
---
- Fixes: #2040, fixes #1535

PopupMenu options fix

---

Assets/HoloToolkit-Examples/SpectatorView/Scripts/SpectatorViewNetworkManager.cs
Assets/HoloToolkit-Preview/SpectatorView/UnityARKitPlugin/Plugins/iOS/UnityARKit/Helpers/UnityARUtility.cs
Assets/HoloToolkit/UX/Scripts/AppBar/AppBar.cs

Overview
---
The `planePrefab` is only used in this script and is only used `#if UNITY_IOS || UNITY_EDITOR`. Without this check when building for Standalone:
SpectatorViewNetworkManager also shows:
and AppBar shows:
Changes
---
- Fixes: #2068, specifically https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2068#issuecomment-393639957

Fix some build warnings

---

Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs

Overview
---
Part 2 of #2359. This is a rework of the way the Button.cs events are fired. Previously, duplicate events were fired in both `OnInputDown` and `OnInputClicked` (and `OnHoldStarted`). This cleans those up and makes the state logic a little clearer.
Changes
---
- Fixes: #1879

Button.cs event firing fixes

---

Assets/MixedRealityToolkit/_Core/Devices/BaseController.cs

Overview
---
Currently the "No Mappings Found" error is reported all the time, simply because there is no IF statement around the error to test if there are no interactions mapped
Changes
---
Surrounds the error with a ```if (Interactions == null || Interactions.Length < 1)``` to validate there are interactions.

Fixed Issue where the "No controller mappings found" error is logged even if there ARE mappings

---

Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityCameraProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs

- Fixes #2371's issues with cleaning up profiles after user changes them in the inspector.
- fixed null ref when selecting camera profile when no mixed reality manager is in the scene.

Config Profile Inspector doesn't update values after change.

---

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs

Overview
---
This change fixes two scenarios that may arise in Windows Mixed Reality controllers.
1. A non-trackable source may be encountered (ex: Voice or a Controller that cannot point)
2. It is possible to have a source that loses positional tracking without losing rotational tracking.
Changes
---
This PR fixes the issues as follows:
1. Determines if a controller can be tracked, and only determines the state if true. Otherwise, returns TrackingState.NotApplicable
2. Checks if we have position data OR rotational data to determine the tracking state between NotTracked and Tracked
- Fixes: #2378.

vNext: fix corner cases in determining windows mixed reality controller tracking

---

Assets/HoloToolkit/Utilities/Scripts/Billboard.cs

Overview
---
LookRotation wants the two vectors to be orthogonal. Giving it the
object's current up vector caused some drift in the z angle in some
cases (since the resulting up vector sometimes cannot be what we pass in). Now, we
don't pass any up vector in and let Unity handle it in cases where we
don't want z touched.

Billboard.cs up vector bug fix

---

Assets/MixedRealityToolkit/InputSystem/Focus/FocusProvider.cs
Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs

- Disabled focus provider and added a check in the `UIRaycastCamera` creation to return if it's disabled.
- Added a flag to `GetOrAddController` to skip updating the controller when we remove it.

Fixed errors when stopping editor playmode.

---

Assets/HoloToolkit-Examples/UX/Prefabs/Slider.prefab
Assets/HoloToolkit-Examples/UX/Scenes/SliderSamples.unity
Assets/HoloToolkit-Examples/UX/Scripts/Controls/SliderGestureControl.cs

Overview
---
Currently, a non-centered SliderGestureControl assumes it will always have a min value of 0. If the min value is not zero, it will slide the range down until it starts at 0, decreasing the max value by the same amount.
This change also re-exposes a starting SliderValue in the editor, which was (inadvertently?) removed in #816, when the public float was turned into a property without serializing its backing field.
Changes
---
- Fixes: #1712

Add support for non-0 min values in SliderGestureControl

---

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs

Overview
---
Multiple menu items had the same priority, so the ordering became inconsistent on launch. This pushes the lower items down in priority, but retains a smaller difference between priorities than the 10 that generates a section separator.
Changes
---
- Fixes: #2071

MRTK menu ordering fix

---

Assets/HoloToolkit-Examples/Boundary/Scenes/BoundaryTest.unity
Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryTest.cs
Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryVisualizer.cs
Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryVisualizer.cs.meta
Assets/HoloToolkit-UnitTests/Editor/Utilities/InscribedRectangleTest.cs
Assets/HoloToolkit-UnitTests/Editor/Utilities/InscribedRectangleTest.cs.meta
Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs
Assets/HoloToolkit/Boundary/Scripts/Edge.cs
Assets/HoloToolkit/Boundary/Scripts/Edge.cs.meta
Assets/HoloToolkit/Boundary/Scripts/EdgeHelpers.cs
Assets/HoloToolkit/Boundary/Scripts/EdgeHelpers.cs.meta
Assets/HoloToolkit/Boundary/Scripts/InscribedRectangle.cs
Assets/HoloToolkit/Boundary/Scripts/InscribedRectangle.cs.meta
Assets/HoloToolkit/UX/Materials/MRTK_Standard_Charcoal.mat

Overview
---
This is a port of @KevinKennedy's inscribed rectangle code from his PR #1759.
I also removed the old Bounds creation for checking if an object was inside the boundary, since that wasn't doing what we expected (Bounds are rectangular, not the shape of the boundary's polygon). Instead, I refactored out some code that was included here to properly check against the edges of the boundary.
Purple is inside the boundary. Cyan is inside the inscribed rectangle, also pictured as a quad.
Changes
---
- Fixes: #1709, fixes #2138.

Add inscribed rectangle to BoundaryManager

---

Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryVisualizer.cs
Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs
Assets/HoloToolkit/Boundary/Scripts/EdgeHelpers.cs
Assets/HoloToolkit/Boundary/Scripts/InscribedRectangle.cs

Overview
---
There was an optimization mentioned in #2403 that I'm addressing here.
I also refactored out a method to convert Vector3s into Edges, which needed to happen in (at least) two places. This simplifies the InscribedRectangle constructors slightly as well.
Changes
---
- Addresses https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2403#discussion_r200541457

Addressing previous inscribed rectangle PR comments

---

Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs

Overview
---
This should prevent unnecessary height changes in RoomScale.
In Stationary, we'll still need the downward raycast for height estimation most of the time.
If your floor is not at y=0 in either case, you can select the existing Stay on the floor setting, which will prevent height changes.
Changes
---
- Fixes: #1181, fixes #2362.

Slight update to the teleport height logic

---

Assets/HoloToolkit-Examples/StandardShader/Animations/RoundedCorner.anim
Assets/HoloToolkit-Examples/StandardShader/Materials/CubeBorderRoundedOpaque.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/CubeEnvironmentColor.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorder.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderBlue.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderCyan.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderGreen.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderOrange.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderPink.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderPurple.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderRed.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/PanelBorderRoundedBlue.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/ShaderBallGlass.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/ShaderBallNearPlaneFade.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/ShaderBallNormalMap.mat
Assets/HoloToolkit-Examples/StandardShader/Materials/ShaderBallNormalMapTransparent.mat
Assets/HoloToolkit-Examples/StandardShader/Prefabs/Placard.prefab
Assets/HoloToolkit/Common/Scripts/Editor/StandardShaderGUI.cs
Assets/HoloToolkit/Common/Scripts/HoverLight.cs
Assets/HoloToolkit/Common/Shaders/Standard.shader

Overview
---
From original PR:
>Integrating the latest work to improve the MRTK/Standard shader. Improvements include:
>
>- Support for non-D3D11 APIs (tested on iOS and Android devices using OpenGL ES and Metal)
>- Support for three hover lights (useful with IHMDs with multi-pointers)
>- Improved rounded corner algorithm
>- Closer match to the Unity/Standard shader
>- Improved shader based anti-aliasing support
>- Minor optimizations
>
>
>![aa](https://user-images.githubusercontent.com/13305729/40255071-b4227e3a-5a9a-11e8-9d01-5ff0b0a807c6.png)
>(Shader based anti-aliasing example.)
Changes
---
- Migrates over #2129.
- Part of #2423.

Shader updates from Dev

---

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs

Overview
---
`UpdateSettings` is used as a callback when the build target is updated asynchronously. Previously, none of the settings were saved before the window was closed, so, when the callback tried to query them, it received the defaults. This change saves the settings before trying to update the build target.
Changes
---
- Fixes #2214

Update ProjectSettingsWindow to not lose settings on BuildTarget update

---

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
Assets/MixedRealityToolkit/_Core/Utilities/MotionController/MotionControllerVisualizer.cs
Packages/manifest.json
ProjectSettings/EditorBuildSettings.asset
ProjectSettings/ProjectVersion.txt
ProjectSettings/UnityConnectSettings.asset

Overview
---
Upgraded project to 2018.2 and removed some unwanted warning messaged.
Also resolved an issue where the editor ONLY runs in standalone mode, so added another function for selecting SDK based on build type
Changes
---
- Updated project to 2018_2
- Fixed some warning errors
- Resolved a Post OpenVR editor runtime issue (Editor only runs as standalone :D)

Mrtk version next 2018 2 upgradeplusfixes

---

Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryTest.cs
Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryVisualizer.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs

Overview
---
A few `#endif`s were in the wrong place, and there was a reference to `XRDevice`.

Fixes for pre-2017.2 in June

---

Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/ManipulationMode.cs
Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs

Overview
---
Updated TwoHandManipulatable to use `HostTransform` for `BoundingBoxRig`.
Many of the other changes were already present. Also, minor clean-up.
Changes
---
- Migrates over #1820 and #2144 
- Related to #2423

TwoHandManipulatable updates from Dev

---

Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/_Core/EventDatum/Input/MixedRealityPointerEventData.cs

- Pose was executing the wrong event data handler.
- Pointer event data needed to call Initialize overload instead of base initialize.
_It's the little things that matter._

Fixed a couple of input system bugs

---

Assets/HoloToolkit-Examples/UX/Models/TheModule.fbx.meta

Overview
---
The meshes in the model do not have tangents build in, so there was a warning printout on fresh load. This turns off the attempted load.
Changes
---
- Fixes: #2070

Turn off tangent import for TheModule

---

Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/TwoHandManipulatable.cs

Overview
---
Previously, a lost hand would revert to one-handed move even if one-handed move wasn't enabled. Now, it falls back to `None` in that case.
Changes
---
- Fixes #2021

Fix bug with enableOneHandMovement in TwoHandManipulatable

---

Assets/HoloToolkit/Utilities/Scripts/Billboard.cs

Overview
---
Two small changes to help Billboard cope with the lack of, or late setup of, a cached camera instance. 
Changes
---
1. null check in OnEnable
2. per-frame attempt to obtain the main camera transfer within the existing null-transform test

Billboard camera tolerance

---

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs

Overview
---
After a teleport, the boundary APIs still return positions around the origin, as though the camera has not moved.
I previously updated the RectangleParams method, but did not transform the RectanglePoints method. This fixes that.
Changes
---
- Related to #2469

Fix in TryGetBoundaryRectanglePoints after teleport

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerConfigurationProfile.asset

Overview
---
Looks like the axes weren't updated/saved properly, resulting in:

Saving the default ConfigurationProfile axes

---

Assets/HoloToolkit/UX/Scripts/Keyboard.cs
Assets/HoloToolkit/UX/Scripts/KeyboardInputField.cs

Overview
---
Instead of trying to case a negative int and failing on XAML, now we cast a large, still invalid, number.
Also, disables the Toolkit keyboard on platforms that support a system keyboard.
Changes
---
- Fixes: #2384

Minor keyboard fixes

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityBoundaryVisualizationProfile.asset
Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs

Overview
---
Based on verbal feedback and additional testing, it was apparent that the default floor size in the boundary profile was too small, as were the default values in the class.
Changes
---
Changed default floor plane to be 10x10m

fix the default floor plane being too small

---

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseFocusHandler.cs

Overview
---
The script was checking the new/old focused gameobject against itself instead of against its gameobject. Therefore, this comparison was always false.

Fixed bug in BaseFocusHandler where wrong comparison was made

---

Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Pointers/DefaultControllerPointer.prefab
Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Pointers/ParabolicPointer.prefab
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/MRTK_DefaultPointerLine.mat
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/MRTK_DefaultPointerLine.mat.meta
Assets/MixedRealityToolkit/_Core/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs

Overview
---
Unity doesn't include shaders that aren't used in materials either referenced in a scene or in a Resources folder. This PR creates a material for the pointer lines with the same settings as the code was doing, instead of trying to create one at runtime and failing when not in the Editor.

Fix pointer line material not being included in the build

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerConfigurationProfile.asset
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/GenericOpenVRController.cs

Left and right triggers were defined as the same axis.

Fix mismapped OpenVR trigger axis

---

Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SystemType.cs

Overview
---
- Allowed setting `Type` to null as it should be a valid operation.
- Added string is null or empty check to `AssemblyQualifiedName`.

Updated SystemType

---

Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/Devices/MixedRealityControllerMappingProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputActionsProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealitySpeechCommandsProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityCameraProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/Utilities/ProfileMenuItemIndices.cs
Assets/MixedRealityToolkit/_Core/Definitions/Utilities/ProfileMenuItemIndices.cs.meta

Overview
---
It is hard to know what value you should use when adding a new menu item and reordering a menu requires modifying multiple files.
To add a new menu item:
- Add an entry in the ProfileMenuItemIndices enum
- Cast the enum value to an in in the CreateAssetMenu attribute (order property)
To reorder the menu:
- Change the value(s) in the ProfileMenuItemIndices enum
Changes
---

Improve how menu item order is specified

---

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs

Overview
---
- Speech input source would throw a null ref if created out of order and no input system nor input action profile existed. Added error dialog and safe returns.
- Fixed an issue making a new profile via add button in main config.

Fixed some null refs when no input action profile exists

---

Assets/HoloToolkit-Preview/SpectatorView/Scripts/Networking/NewDeviceDiscovery.cs
Assets/HoloToolkit-Preview/SpectatorView/Scripts/Networking/SpectatorView.cs
Assets/HoloToolkit-Preview/SpectatorView/Scripts/SpatialSync/CameraCaptureHololens.cs

Overview
---
As a fix to #2438 we have now forced SpectatorView's `isHost` field to initialize on the `Awake`. That will allow `SpectatorViewNetworkManager` to make use of that field without risking getting into script execution order issues. 
@davidkline-ms I have created this PR against `Master` because I wasn't sure which branch should I create it of. Could you please redirect the PR or let me know what you would like me to do? 
Changes
---
- Fixes: #2438
- Some exception handling has been added on `OnPhotoModeStarted`. There were some instances when if the iPhone stopped broadcasting while the HoloLens was still taking pictures, it would throw an exception.
- We're now manually disposing of the pictures taken to avoid the GC kicking in more often
- `NewDeviceDiscovery` initialization …

Fix for #2438 . Force components to initialize in the right order

---

Assets/MixedRealityToolkit/_Core/Resources/Shaders/InvisibleShader.shader

Overview
---
Currently, the Standard shader and the Invisible shader appear in different folders in the shader query tree.
This fixes this so that both MRTK shaders now appear in the same folder, matching what the Standard shader was using
Changes
---
- Fixes: Folder names for shaders

Fixed the folder name for the Invisible Shader

---

Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs

Overview
---
No longer hiding boundary visualization configuration settings when disabling the default showing of a component (ex: walls).
Added profile tooltips to help with user education.
Changes
---
- Fixes: #2616 .

fix boundary visualization inspector #2616

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/InteractiveMeshCursor.cs

Overview
---
The source detected and lost logic assumed that pointers and cursors will only care about events from the same input source that they're registered on. That might be the case for most of the controller pointers, but that's not the case for the gaze pointer. The hand is a separate input source from the gaze input source.
This assumption is made in other places in the MRTK as well and will likely need updating as we investigate HoloLens support. In most cases, it's probably more correct to check "am I registered in this input source's list of pointers" instead of checking "is my input source the same input source that the event is coming from".
Additionally, `IsHandDetected` was not intended to specifically filter out hands only in the HTK. Its name was from the time before …

Update BaseCursor to properly respond to source events

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs

Overview
---
Previously, the source lost handling checked to see if the lost source was the gaze input source, and special-cased some logic to clear the pointing data.
We also need to special case if the gaze pointer was being used by a lost non-gaze input source (in the discovered case, this would be a hand source on HoloLens). In this case, we should not remove the gaze pointer, since the gaze input source still exists and other sources might be using it.
Changes
---
- Related to: #2626 
Fixes:
>Head tracking stops working when a hand is raised and lost. Cursor does not follow head movement anymore. It follows head movement only when a hand is raised.

Fix gaze pointer being lost on hand lost

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs
Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerConfigurationProfile.asset

Overview
---
Adds a new mapping for unhanded WMR controllers, as HoloLens hands come through with an unknown handedness.
Also adds `IMixedRealityInputHandler` to the `GazeProvider` in order to properly route input events into pointer events. This enables both HoloLens hands and immersive apps that choose not to use controller-based pointers.
Changes
---
- Related to #2626 
Fixes:
>Does not trigger input events.
for PointerDown/Click/Up.

Add support for controllers/sources without pointers to use the GazePointer

---

.gitignore

Overview
---
Otherwise, when switching between the projects, the TextMesh Pro folders show up in the changelist.
This also brings over support for the VSCode generated folder.

Updating HTK gitignore to match MRTK

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/---feature-request.md
.github/ISSUE_TEMPLATE/---mrtk-task.md
.github/ISSUE_TEMPLATE/---vnext-task.md

Overview
---
Adds multiple issue templates for bug reports, feature requests, and MRTK tasks, with specialized templates for each.
See https://github.com/keveleigh/HoloToolkit-Unity/issues/new/choose to see how this looks when filing an issue.
The default, existing issue template is now the fallback and has been left untouched.

Add multiple GitHub issue templates, to better facilitate MRTK task filing

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs

Overview
---
Cursor was spawned in root node and not in body
Changes
---
Changed parenting on instantiate as @StephenHodgson showed me.

Fixed parenting of cursor

---

Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs

Overview
---
Pointers were getting their start position from the grip position instead of the pointer position. This was causing the debug ray to not match the pointer visualization, which was correctly aligning itself with the pointer position.
Changes
---
- Fixes: #2523.

Fix HTK pointer debug rays

---

Assets/HoloToolkit/Input/Scripts/Utilities/ControllerFinder.cs

Overview
---
When one controller is using the glTF controller model and the other isn't, the pointing ray doesn't properly disable itself when it doesn't find anything to attach to. This is because we update the handedness, then in the refresh code check to make sure the handedness is the same as the currently tracked controller before sending the controller lost event.
This change forces the previous controller to be lost, regardless of the current handedness.
Changes
---
- Fixes: #2669

Fix pointer line visibility when switching the active controller

---

Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityInputSystem.cs

Overview
---
The compiler definitions for speech are no longer needed.

Removed unneeded platform specific compiler definitions.

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs

Overview
---
Broadened visibility for Start() to allow derived providers to add e.g. a GazeFuse to the DefaultCursor after init.

GazeProvider Start() visibility to protected for derived providers

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset

Overview
---
#2639 checked in the default controller mapping profile with stale axes for the HoloLens gestures mappings. The Grip interaction was updated to be a single axis trigger, but those values weren't updated in the profile. When running on HoloLens, the controller was getting a mapping error, which then [shuts down the entire controller](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs#L136), causing input on HoloLens to be broken.

Fixes controller mapping profile serialization for HoloLens gestures

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs
Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/SpeechInputHandler.cs
Assets/MixedRealityToolkit-SDK/Features/Input/InputSystemGlobalListener.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs

Overview
---
There was a race condition we needed to check against in the BaseInputHandler.  If the Input System isn't valid by the time we get OnEnable called we could drop registration of listeners. 
BaseControllerPointer also had the same issue for the Teleport System, and was updated to accommodate that as well.
These changes make the handlers more robust and is lazy initialized, waiting until the systems are valid before doing any action.

Fixed a race condition with BaseInputHandler

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityRegisteredComponentsProfile.asset
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityComponentConfiguration.cs
Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SupportedPlatforms.cs
Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SupportedPlatforms.cs.meta
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityRegisteredComponentsProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
Assets/MixedRealityToolkit/_Core/Utilities/PlatformUtility.cs
Assets/MixedRealityToolkit/_Core/Utilities/PlatformUtility.cs.meta

Overview
---
New registered component profile wasn't saving the platforms correctly bc unity's build targets and runtime platform enums were not bit flags.  
I added an enum with our supported platforms and added a little utility to check if the runtime time platform or build target matches our own supported mask.
I also fixed an issue where we were not saving our new values before resetting the profile.

Added better platform checking

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityRegisteredComponentsProfile.asset

Overview
---
Unity does not include OpenVR as a valid VR SDK on UWP.

Removed UWP from OpenVR supported platforms

---

Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs

Overview
---
After #2718, only one GetManager call was updated to actually check all interfaces. The others simply kept checking against the registered type, which is now IMixedRealityComponent for all components (causing them to return empty).
Basically, this is an expansion of the code added in e710233caeadf9238fb180a061e589fa61dfeadb to all component/manager getters.

Fix GetManager(s) calls in MixedRealityManager

---

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseInputHandler.cs

Overview
---
`InputSystemGlobalListener` registers as a global listener in `Start`, `OnEnable`, and `OnDisable`. `BaseInputHandler` properly hides the registration in `OnEnable` and `OnDisable`, but did not in `Start`.
Changes
---
- Fixes: #2786

Hide the base InputSystemGlobalListener Start call if isFocusRequired is checked

---

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs

Overview
---
Currently, the manager assumes that any source without a handedness is a hand. However, it can also be voice, which comes across the `InteractionManager` events as a select press and release when "Select" is spoken.

Update WMR source naming to include Voice

---

Assets/MixedRealityToolkit-SDK/Features/Utilities/Solvers/SolverHandler.cs

Overview
---
Removed `[DisallowMultipleComponent]` as it shouldn't have been added in the first place and the InBetween solver depends on multiple handlers.
Refactored out `RefreshTrackedObject()` as a public method to facilitate runtime refreshes.
Fixed a bug where a solver's parent's scale wasn't being accounted for in the desired solver offset, so offsets could be larger or smaller in world space than expected.

[Solver PR 3.5] SolverHandler bug fixes

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityCursor.cs

Overview
---
- Also waited until the input system is valid before setting the cursor.
- We should only be setting the cursor once in Start, not on each Enable.
- Added documentation to cursor interface and moved the property into the cursor implementation region of the class.
Changes
---
- Fixes: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2752

Fixed pointer registration.

---

Assets/MixedRealityToolkit-SDK/Features/Boundary/MixedRealityBoundaryManager.cs
Assets/MixedRealityToolkit-SDK/Features/Teleportation/MixedRealityTeleportManager.cs
Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityConfigurationProfile.asset
Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityConfigurationProfileInspector.cs

Overview
---
We want to make sure that all feature specific settings are encapsulated in the feature's profile. Boundary height should have been part of the boundary viz profile.
- moved boundary height into boundary visualization profile.
- made sure boundary profile wasn't hidden when experience setting wasn't set to room.
- removed teleport duration from main config profile, as it's currently unimplemented anyway.

Updated config profiles

---

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseInputHandler.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Receivers.meta
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs.meta

Porting the original InteractionReceiver from HTK. This script registers itself with the `InputSystem` and listens for all events available for GameObjects in the Interactables list. To extend, simply override the virtual methods. This is a core component used by many others (namely App bar). Unfortunately, since InteractionReceiver is not necessarily a "UX" component, I can't make a demo scene - this is more foundational and unblocks other components.
-- **InteractionReceiver** now implements `IMixedRealityGestureHandler<T>`
I put the InteractionReceiver in the `SDK.UX.Receivers` namespace, but it might make more sense in `SDK.Input.Receivers`
https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/master/Assets/HoloToolkit-Examples/UX/Readme/README_InteractableObjectExample.md …

vNext: InteractionReceiver base class

---

Assets/MixedRealityToolkit-SDK/Inspectors/UX/Collections/BaseCollectionInspector.cs

Overview
---
`BaseCollectionInspector`'s namespace wasn't in the normal inspector namespace for SDK inspectors.

Updated the namespace of BaseCollectionInspector

---

Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityCameraProfile.cs
Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs

Overview
---
Resolution for Task #2826
Changes
---
- Changes IsOpaque property to be non-static
- MRManager check updated to match.
IsOpaque option now accessible through the profile with
```
MixedRealityManager.ActiveProfile.CameraProfile.IsOpaque
```

Updated isOpaque check to be part of the camera profile #2826

---

Assets/MixedRealityToolkit/_Core/Resources/Shaders/MixedRealityStandard.shader

Overview
---
The namespace of the shader's inspector was changed in #2783, but the reference in the shader itself wasn't updated, causing:

Update MRTKStandard shader's reference to its custom inspector

---

Assets/MixedRealityToolkit/_Core/Utilities/Editor/Setup/EnforceEditorSettings.cs

Made sure to get the folder name only and make sure it exactly equals the folder name we're searching for.

MRTK relative folder matching fix.

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs

Overview
---
Added await to start to make sure the input system is initialized before setting cursor.

Ensured Input System is valid before setting cursor on Gaze Provider.

---

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityConfigurationProfileInspector.cs

While using the configuration inspector, I found it hard to locate the registered components profile since it did not have a header, so I added one.
While in the code, I noticed that there were some boundary system variables located with the teleport system, so I relocated to be with "friends".
Also made some minor layout (spacing) changes and moved the boundary requiring room scale notification to a more prominent location for easier notice.

add additional components header, code organization cleanup

---

MRTK-WorkRoadmap.md

Overview
---
I'll follow up with a PR removing this from the other doc. (https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2845)
I am not opposed to deleting this list, if it's not longer relevant. I just wanted to get it out of the architecture guidance.

Moved some of the non-guidance info out of the architecture docs

---

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseFocusHandler.cs

Overview
---
BaseFocusHandler was assuming that being the `OldFocusedObject` meant that overall focus was lost. Since we're keeping track of the focusers (and there might be multiple), I've updated the locally tracked bool to instead check if any focusers are currently focusing the object.

Update BaseFocusHandler, as being the old focused object does not always mean overall focus was lost

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs

Migrated https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2456 from master (with #2450 being the Issue).
It also doesn't look like the assert was doing what it thought it did, since it's checking against the focused point, not the start point.

Removed obsolete assert in FocusProvider

---

CodingGuidelines.md

The coding guidelines don't currently specify interface design recommendations. This adds the recommendation that interface types should avoid concrete types where possible.

Add interface guidelines

---

Assets/MixedRealityToolkit-SDK/Features/Diagnostics/MixedRealityDiagnosticsManager.cs
Assets/MixedRealityToolkit/_Core/EventDatum/Diagnostics/DiagnosticsEventData.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs
Assets/MixedRealityToolkit/_Core/Interfaces/Diagnostics/IMixedRealityDiagnosticsHandler.cs

Overview
---
There were remaining boundary comments, namespaces, and text in the diagnostic code. Scrub that out
Changes
---
- Fixes: #2863

Fix copy+paste errors in diagnostic code

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/MousePointer.cs
Assets/MixedRealityToolkit/_Core/Devices/UnityInput/MouseController.cs
Assets/MixedRealityToolkit/_Core/Devices/UnityInput/MouseDeviceManager.cs

Overview
---
- Added notification when mouse device manager is started about how to regain mouse control.
- Cached the ray in `BasePointer`
Changes
---
- Fixes: #2832 
- FIxes: #2756

Mouse Pointer Updates

---

Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/_Core/EventDatum/Input/MixedRealityPointerEventData.cs

Overview
---
`RaisePointerDown` and `RaisePointerUp` were using `InputEventData`'s `Initialize` instead of `MixedRealityPointerEventData`'s, so the pointer stored inside the event data wasn't being updated. This caused the pointer to always be the pointer that last fired a click event (or `null`, initially), as that was the only method properly updating the pointer.

Properly initialize pointerEventData in the input manager

---

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseFocusHandler.cs
Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/Handlers/IMixedRealityFocusHandler.cs

Overview
---
This is the only handler interface that contains more than the event handlers. `IMixedRealityFocusHandler` contains three additional properties which added unnecessary overhead for implementing the focus events and are implementation-specific.
If a developer needs access to this information, they can inherit from `BaseFocusHandler`. Either way, we don't pass `I[*]Handler` references around, so there's no need to define them there, and not all interface implementations will need them.

Remove non-events from IMixedRealityFocusHandler

---

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs

Overview
---
Issue seems related to the way Unity is exposing the InteractionManager and access to the data within which seems UI / polling bound (only works correctly when attached to a GameObject/MonoBehaviour).
The resolution was to change from using the InteractionManager events for update / pressed / released, to polling during the Unity Update event.  This ensures the data is synchronised accurately.
Changes
---
- Fixes: #2889
Results
---
From (Top - Raw, Bottom - MRTK)
To (Top - Raw, Middle - MRTK, Bottom - InteractionDef)

Fixed UWP Lag issue, changed from Event Based updates to polling.

---

Assets/HoloToolkit-Examples/Utilities/Prefabs/SolverExample/WristWrapper.prefab
Assets/HoloToolkit-Examples/Utilities/Scenes/SolverExamples.unity
Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverHandler.cs

Overview
---
After the glTF coordinate system update (#2638), the controller model's forward, up, etc vectors are reversed.
In order to account for this in solvers that assume the forward direction is out from the controller, we now expose a transform rotated 180 degrees around the Y axis, so "forward" is "forward" again.
This PR also updates the sample scene a little bit to account for this addition.

Add rotated transform to Solvers after glTF coordinate system update

---

Assets/MixedRealityToolkit-SDK/Features/Diagnostics/CpuUseTracker.cs
Assets/MixedRealityToolkit-SDK/Features/Diagnostics/MemoryUseTracker.cs

Overview
---
Add pragma restrictions on use of System.Diagnostics.Process for cases where UWP and dotnet backend are used, since they don't use netstandard 2.0
Changes
---
- Fixes: #2874

Fix dotnet runtime for UWP

---

Documentation/Architecture/Package_Manager/Package_Manager.md
Documentation/Architecture/Readme.md

Overview
---
Start documentation for Package Management. This should be used as a basis for conversation in determining policy more than implementation details. I want to make sure the community has the right discussion before I start adding any interfaces, classes, or in depth implementation on how to hook in with Unity.

Add initial documentation around package manager

---

CONTRIBUTING.md

The current documentation mention to join HoloLens dedicated forum, or Slack. If you are not member of HoloDevelopers on Slack, you need someone to send you an invitation.
An automatic invitation sender has been hosted on Azure for a while now, and can provide a quick and easy access to anybody without manual intervention.
Since the Contribution guide was providing the Slack address, I suggest we also provide a link to the automatic invitation sender.

 Add link to Azure hosted Slack invitation sender

---

Assets/HoloToolkit/Common/Scripts/WorldAnchorManager.cs

Overview
---
if WorldAnchor component dont have parent, null exception occur.
change to check to be anchor.gameobject.transform.parent null
---
- Fixes: #1781

fix bug : Null Exception occur in WorldAnchorManager 

---

Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/SolverSwappingVolume.prefab

Overview
---
Some stray settings and a `ChaseSource` object were added to the prefab during #2885 that caused a red circle to appear in each swapping volume when the actual solver became active. This removes those from the prefab.

Remove stray ChaseSource from SwappingVolume prefab

---

Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SystemType.cs

Overview
---
When using different platforms it's guaranteed that certain platform specific types will be missing (As they're not included in the build). So this warning doesn't really need to be raised. Classes utilizing this should be checking if the returned type is null before use.

Updated SystemType deserialization method

---

Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs

The manager should not throw exceptions. They are expensive and handled automatically, so they aren't much more useful than a simple (and quicker) debug message
Changes
---
* The manager no longer throws
* Error debug log messages are displayed
* Safe (null, empty collections, etc) values are returned where an exception would have been thrown

replace manager exceptions with debug.logerror and return

---

Assets/MixedRealityToolkit-SDK/Features/Utilities/Solvers/SolverHandler.cs

Overview
---
Moved the initial transform finding logic into `Start`, to prevent the handler from trying to find a transform immediately in case a dev wants to change the `TrackedObjectToReference` on instantiation.
Refactored out a `DetachFromCurrentTrackedObject` method, since the same logic was used in multiple places.

Minor SolverHandler refactor

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs
Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/DragAndDropHandler.cs
Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs
Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs

Overview
---
Removed eventData methods for getting focus data. Users should instead iterate over the event data's pointers and call on the focus provider's pointer specific methods for getting focus data. This ensures there are not extra allocations while getting focus data and keeps performance in mind.
Changes
---
- Fixes: #2918

Fixed issue getting focused GameObject(s) when handling input event

---

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs

Inspector changes weren't ever being saved from the diagnostic profile UI, which would cause it to never be enabled.

Add update to serializedObject in diagnostic inspector 

---

Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityToolkitInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

Overview
---
> Take 2 :D 
The MixedRealityPlayspace should be instantiated at Design time, to ensure the developer / adopter understands the default layout of an MRTK scene.
They can change this afterwards, but should be there to begin with to ensure the scene is not tampered with at runtime and introduce unexpected results.
This was how it was in the HTK and how the framework was designed initially to run (Body -> head, until Body was renamed)
Changes
---
- Fixes: #2899

Updated Inspectors to apply the playspace at design time

---

Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipLines.mat
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipLines.mat.meta
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipWithBorder.mat
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipWithBorder.mat.meta
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipWithoutBorder.mat
Assets/MixedRealityToolkit-SDK/StandardAssets/Materials/TooltipWithoutBorder.mat.meta

Overview
---Added default materials & tooltip backgrounds.
---These assets cannot live inside of the Examples folder due to being needed by the three Default Tooltips prefabs (similar to how default cursor & pointer prefabs live inside of the SDK folder)
Changes
---Added 2 background materials and 1 solid color line renderer material
- Fixes: # .

Add Tooltip Materials

---

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityToolkitConfigurationProfile.asset
Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityToolkitConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs

---
@davidkline-ms noted an exception that was being raised in a UWP build on both Windows10 and HoloLens in #2979.  
On investigation, this was actually caused by poorly serialised data in the DefaultMixedRealityConfigurationProfile asset.  When the Core Services get reordered for Initialization, these serialised versions were also being detected and as they were being serialized by their concrete types and not their interface, the system failed to identify them as core systems.
This had two effects:
* The core system were duplicated in the service registry, one as a concrete type and another as a system interface
* The concrete type, being not seen as a core system, was attempted to be registered as a Registered service, causing a type cast failure.
It was also noted by others that …

Mrtk development serialization fix

---

Assets/MixedRealityToolkit-SDK/Features/Boundary/MixedRealityBoundaryManager.cs
Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs

Overview
---
Changes the return type from Vector3 -> Vector2. We were only using `x` and `y` in the manager anyway.
Changes
---
- Fixes: #2706

Make FloorScale's type match floorScale's type

---

CodingGuidelines.md

Overview
---
Add platform-dependent compilation section to CodingGuidelines, migrating over #2461 from master.
Changes
---
- Fixes: #2142

Add platform-dependent compilation section to CodingGuidelines

---

Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/ChaseSource.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/ChaseSourceWithOffset.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/ChaseSourceWithOffsetThenFaceHead.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/InBetweenSources.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/Orbital.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/OrbitalWithStepping.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/Snake.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/SurfaceMagnetism.prefab
Assets/MixedRealityToolkit-Examples/Demos/Solvers/Prefabs/SurfaceMagnetismAndRadialView.prefab

Overview
---
The solver prefabs had some stale handedness data which was causing them to inappropriately attach to the wrong sources in some cases. This was then overriding the SolverHandlers attachment behavior, causing invalid scenarios as seen in the two below reports.
Changes
---
- Fixes #2996 and fixes #2997

Remove stale handedness data from Solver prefabs

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs

Overview
---
When a pointer is set to [no longer be enabled for interaction](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs#L509), the focused object is reset without the previous object being cleared. Since this line is hit every time the pointer is updated, multiple `FocusLost` events are sent to the previous object, since it never changes.
With this change, on the first call to this method, the previous object will be properly set to the old current focused object. Since the `CurrentPointerTarget` is then set to null, every subsequent call to this method will set the previous target to null and not send another `FocusLost` event.

Fix bug in ResetFocusedObjects where the previous target stayed the same

---

Assets/MixedRealityToolkit/_Core/Utilities/CameraCache.cs

Overview
---
- added camera lookup if no main camera tag is found.
Changes
---
- Fixes: #3021

Fixed CameraCache fail if no camera tagged as main camera.

---

Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs

Overview
---
Carry on processing other images after an unsupported image type is encountered.
Changes
---
- Fixes: #3028 .

Fix for tile generator quitting if used on a non 2018 build of Unity

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/MousePointer.cs

Overview
---
The Base Cursor could be null during these checks. Using the `isDisabled` allows us to better check the internal state of the active pointer.
Also moved the timer reset out of the threshold check to prevent resetting when doing fine movements but still working with the mouse.

Fixed some null refs with mouse pointer

---

Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/ParabolaConstrainedLineDataProvider.cs

Overview
---Fixed the unclear behavior of the ParabolaConstrainedLineDataProvider's SetPointInternal
If a function called it with a 0 value (for the origin point of the parabola), it would report with a vague error.
Added a comment explaining why nothing was done.
Needed for Tooltip refactor.
Changes
---
- Fixes: # .

Fixed ParabolaConstrainedLineDataProvider's SetPointInternal

---

Assets/HoloToolkit/Utilities/Scripts/StabilizationPlaneModifier.cs

When camera collides with an object, the stabilization plane comes to camera. 
This makes Holograms unstable.
The distance of stabilization plane should be greater than that of near clip.
Maybe this behaviour should be optional so that user can disable it.

Set minimum distance of stabilization plane to nearclip distance of camera

---

Assets/HoloToolkit-Preview/QRTracker/Scripts/AttachToQRCode.cs
Assets/HoloToolkit-Preview/QRTracker/Scripts/QRCode.cs
Assets/HoloToolkit-Preview/QRTracker/Scripts/QRCodesManager.cs
Assets/HoloToolkit-Preview/QRTracker/Scripts/QRCodesVisualizer.cs
Assets/HoloToolkit-Preview/QRTracker/Scripts/SpatialGraphCoordinateSystem.cs

Overview
---
The QR code plugin is only provided for UWP and the editor, so all references to it (and other Unity WSA specific APIs) needed to be wrapped with `#if UNITY_EDITOR || UNITY_WSA`. This also led to some minor clean-up to better wrap the contents.
Changes
---
- Fixes: https://github.com/Microsoft/MixedRealityToolkit/issues/183

Added #if blocks to QR code preview feature

---

Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxRig.cs

Currently BoundingBoxRig missing several public properties for private SerializedField fields.
This cause user could not modify component when dynamically add component from Script. This commit open these parameters modifiable.

Add missing public properties to BoundingBoxRig

---

Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityToolkitConfigurationProfile.cs
Assets/MixedRealityToolkit/_Core/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs

Overview
---
- Fixed a null ref when disabling diagnostics system at edit time.
- Only enable diagnostics system if a valid profile is assigned.

Fixed diagnostics null ref when disabling at edit time

---

Assets/MixedRealityToolkit/_Core/Devices/BaseDeviceManager.cs

Overview
---
Line 49 was overwriting a method parameter inside a `for` loop.
The result of this was that subsequent pointers in the pointer profile were using the overwritten value instead of their own bool checks.
For example:
Putting a specifically typed pointer above a `None` typed pointer in the pointer profile.
The specifically typed pointer will overwrite `useSpecificType` to true, which will cause all following pointers to keep using `useSpecificType` as true, since line 49 will be skipped.

Fix overwriting bool in RequestPointers

---

Assets/HoloToolkit/Input/Scripts/InputSources/TouchscreenInputSource.cs

Overview
---
Make TouchScreenInputSource .cs functions virtual so its possible to override them when inderiting from TouchScreenInputSource 
Changes
---
- Fixes: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3197

TouchScreenInputSource virtual  functions 

---

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealitySpatialAwarenessProfileInspector.cs

Overview
---
This inspector was missing the base call, so some expected values weren't being set properly. In particular, this broke copy + paste.

Add base.OnEnable to Spatial Awareness inspector

---

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs.meta
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs
Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs.meta

- Updated two profile inspector icons
- The `MixedRealityInputActionRulesInspector` had an error where you could see the "Back to Configuration Profile" message even if there was no MixedRealityToolkit in your scene.

Some fixes

---

Assets/MixedRealityToolkit/_Core/Resources/Shaders/MixedRealityStandard.shader

Materials using channel maps or alpha tested (cutout) materials could report incorrect alpha values. This is not something apparent in usual usage, but could present problems during Mixed Reality or BEV capture.

Fixing incorrect alpha channel values for channel maps and alpha tested (cutout) materials.

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs

Overview
This change addresses the bug described in #3216. The method used for updating `PointerData` with canvas raycast information was missing a line to assign the current pointer target. I fixed this with a slight refactor that should make errors like this harder to make by reducing duplicate code and properties on the object. 
Changes
- Fixes: #3216

Set CurrentPointerTarget properly when updating PointerData

---

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs

Overview
---
Remove configuration of near/far clip planes on the UI raycast camera after testing and finding that their values don't seem to affect raycasting at all. This is mainly just to avoid confusing any future readers who may assume it is important.

Remove a couple unnecessary lines from UI camera config

---

Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SystemType.cs

Changes
---
Add preprocessor directives and alternate implementation for the .net backend.
- Fixes: #3273  .
Built successfully with 2018.2.19 using .net and il2cpp

fix cs0019 when building against the .net backend

---

Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableActivateTheme.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableAudioTheme.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableMaterialTheme.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableStringTheme.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableTextureTheme.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Scripts/Themes/InteractableThemeBase.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Themes/ToggleIcon.asset
Assets/MixedRealityToolkit-SDK/Features/UX/Interactable/Themes/ToggleIconSelected.asset
Assets/MixedRealityToolkit-SDK/Inspectors/UX/Interactable/ThemeInspector.cs

Overview
A bug on the radials and checkbox controls was pointed out last week. The dots and checks should only appear during the selected states. Updated the new theme to turn the dots and checks off.
Looked at why the animation does not happen on the first click of a toggle button, but each future click themes animated correctly. 
Fixed an issue with the InteractableActivatorTheme. It should not have easing controls sense it does not animate from activated to non activated. Finished a feature I started implimenting a while ago to remove the easing controls when a theme property does not require animation, like strings and audio clips. We could add themes later to fade audio or animate strings.
- Fixes:
Radial and check box toggles did not visually update correctly for each selected state …

Updated radial and checkBox themes

---

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs

Overview
---
After #3113, the new `GazeCursor` property (and its underlying field) were never being set, thus causing all references to them to be null.
Now, the `GazeCursor` property will return the `GazePointer`'s cursor.
Changes
---
- Related to #2960

Fix bug where GazeCursor was never being set

---

Assets/MixedRealityToolkit/_Core/EventDatum/Input/InputEventData.cs

Overview
---
Since we reuse a single event data object for each type of event data, it sometimes contained stale handedness data when the non-handed `Initialize` was used.
Changes
---
- Related to #2960

Fix issue where some event data wasn't having its handedness properly reset

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

Overview
---
Fix bug introduced by #2944, where a backing field was created but it was never populated.
Now, the pointer sets its backing field anywhere its gameObject name is updated (here, it's set in the `base.Controller` setter).

Properly set pointerName at pointer creation

---

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProvider.cs

Overview
---
Line 176 in LinePointer was adding 0 (the distance between a point and itself) for the raystep that hit the object. This now properly adds the distance between the start of the raystep and the hit point.
Additionally, `GetNormalizedLengthFromWorldLength` was consistently overshooting and providing a slightly larger value than the true normalized length. This code now subtracts the amount that was overshot.
Changes
---
- Related to #2960

Pointer line length bugs

---

Assets/MixedRealityToolkit/_Core/Definitions/Devices/MixedRealityInteractionMapping.cs
Assets/MixedRealityToolkit/_Core/Devices/BaseController.cs

I wasn't able to reopen #3291, so here's a new PR.
Overview
---
Since the controller mapping profile only contains one array for HoloLens hands (since there's no differentiation between handedness), both hands are reusing the same array. This causes their values to overwrite each other, and causes events to fire endlessly when one hand is selecting and the other isn't. This would also be seen in any other source that reuses one array in the profile, like touch.
This bug fix instead creates a copy of the profile's array, so we aren't reusing the same structure. This will also fix cases where a source might be lost while selecting, which would cause the state to change when a second, unselecting source is detected.
Changes
---
- Fixes: #3195 
- Fixes: …

Fix issue where HoloLens hands were using the same MixedRealityInteractionMapping array

---

Assets/MixedRealityToolkit-Examples/Demos/Input.meta
Assets/MixedRealityToolkit-Examples/Demos/Input/Scenes.meta
Assets/MixedRealityToolkit-Examples/Demos/Input/Scenes/DragAndDropExample.unity
Assets/MixedRealityToolkit-Examples/Demos/Input/Scenes/DragAndDropExample.unity.meta
Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs
Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs
Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/DragAndDropHandler.cs
Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MixedRealityToolkit/_Core/Definitions/Physics/RayStep.cs
Assets/MixedRealityToolkit/_Core/EventDatum/Input/MixedRealityPointerEventData.cs
Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityInputSystem.cs

Overview
---
The original issue with DragAndDropHandler was that the gaze pointer was sending its own input source across the Pointer events, instead of the input source that originally sent the event.
This updates the pointer event methods to allow for an input source that's different from the pointer's input source. This allows matching position events to pointer events, and vice versa.
This change also adds support for moving objects with the tip of a controller's pointer ray, instead of with the source's position. Over the gaze pointer, the position is used.
Changes
---
- Fixes: #2960
Blocked By
---

Fix DragAndDropHandler to properly support hands over the gaze pointer

---

Assets/MixedRealityToolkit-SDK/Features/SpatialAwareness/System/MixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit/_Core/Devices/BaseSpatialObserver.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealitySpatialObserver.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealitySpatialObserver.cs.meta
Assets/MixedRealityToolkit/_Core/EventDatum/SpatialAwareness/MixedRealitySpatialAwarenessEventData.cs
Assets/MixedRealityToolkit/_Core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessObserver.cs
Assets/MixedRealityToolkit/_Core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs

Overview
---
This change moves the implementation of IMixedRealityEventSource from the spatial awareness system and adds it to the spatial awareness observer. This enables client code to determine / access the source of the events.
This is a breaking change for any concrete implementations of IMixedRealitySpatialAwarenessSystem and/or IMixedRealitySpatialAwarenessObserver.
Changes
---
- Fixes: #3190

Move eventsource functionality from SpatialAwarenessSystem to observer(s)

---

Assets/MixedRealityToolkit-Tests/Core/TestFixture_01_MixedRealityToolkitTests.cs
Assets/MixedRealityToolkit-Tests/Services/TestExtensionService1.cs
Assets/MixedRealityToolkit-Tests/Services/TestExtensionService2.cs
Assets/MixedRealityToolkit/_Core/Devices/BaseDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/BaseSpatialObserver.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealitySpatialObserver.cs
Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/UnityInput/MouseDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/UnityInput/UnityJoystickManager.cs
Assets/MixedRealityToolkit/_Core/Devices/UnityInput/UnityTouchDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/VoiceInput/WindowsDictationInputDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/VoiceInput/WindowsSpeechInputDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Devices/WindowsGaming/WindowsGamingDeviceManager.cs
Assets/MixedRealityToolkit/_Core/Services/BaseExtensionService.cs
Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs

Overview
---
Add ScriptableObject member as configurationProfil in the BaseExtensionService class to store the profil.
Add the configuration.ConfigurationProfil as additionnal parameter when registering the IMixedRealityExtensionService.
Change all IMixedRealityExtensionService implementation constructor to add ScriptableObject has third parameter to accept the configuration profil.
Changes
---
- Fixes: # .

Add ConfigurationProfil connection for Extension Service

---

Assets/MixedRealityToolkit/_Core/Utilities/ClippingPrimitive.cs

Overview
Changing ClippingPrimitive.ClippingSide to an explicit property. For some reason the lambda prevents other classes from accessing it.
Changes
---
Added an explicit get/set.

changing accessability on ClippingPrimitive.ClippingSide

---

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs

Overview
---
In the 2018.3 update, I think the wrong API was used for these lines. As written, the profiles didn't accept any prefabs.

Change GetPrefabInstanceStatus -> GetPrefabAssetType

---

Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs

Overview
---
Makes the gaze cursor optional. Otherwise, if no gaze cursor is set in the profile (a valid state), the system setup will fail out when trying to `Instantiate` null.

Add check to prevent trying to instantiate null gaze cursor

---

Assets/MixedRealityToolkit/Definitions/Utilities/SupportedPlatforms.cs
Assets/MixedRealityToolkit/Utilities/PlatformUtility.cs

Overview
---
This will help enable systems / services that are only meant for editor simulation or otherwise not intended to run on an actual device.

Add WindowsEditor as a supported platform

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs
Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs
Assets/MixedRealityToolkit.Tests/Services/TestExtensionService1.cs
Assets/MixedRealityToolkit.Tests/Services/TestExtensionService2.cs
Assets/MixedRealityToolkit/Definitions/MixedRealityServiceConfiguration.cs
Assets/MixedRealityToolkit/Devices/BaseDeviceManager.cs
Assets/MixedRealityToolkit/Devices/BaseSpatialObserver.cs
Assets/MixedRealityToolkit/Devices/OpenVR/OpenVRDeviceManager.cs
Assets/MixedRealityToolkit/Devices/UnityInput/MouseDeviceManager.cs
Assets/MixedRealityToolkit/Devices/UnityInput/UnityJoystickManager.cs
Assets/MixedRealityToolkit/Devices/UnityInput/UnityTouchDeviceManager.cs
Assets/MixedRealityToolkit/Devices/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs
Assets/MixedRealityToolkit/Devices/WindowsMixedReality/WindowsMixedRealitySpatialObserver.cs
Assets/MixedRealityToolkit/Services/BaseExtensionService.cs

Overview
---
#3318 was a fantastic change that had one minor flaw. Rather than pass a ScriptableObject as the profile, BaseMixedRealityProfile should have been used.
This change also updates the summary tags for the relevant constructors
Client code / profiles should not encounter any breaking changes with this PR.

replace ScriptableObject with BaseMixedRealityProfile

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DragAndDropHandler.cs
Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs.meta
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/GazeHandHelper.cs
Assets/MixedRealityToolkit/Interfaces/Devices/IMixedRealityControllerPoseSynchronizer.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityInputHandler.cs

Overview
---
Not every class that implements `IMixedRealityInputHandler < T >` needs the methods from `IMixedRealityInputHandler`. This change removes the dependency and allows code that so desires to implement one or both without need for empty method implementations.
Changes
---
Fixes: #3295

remove IMixedRealityInputHandler from IMixedRealityInputHandler<T>

---

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/MatrixMRTKStandard.mat
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/MatrixMRTKStandardNoReflections.mat
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/StandardMaterialComparison.unity
Assets/MixedRealityToolkit/Inspectors/ChannelPackerWindow.cs
Assets/MixedRealityToolkit/Inspectors/ChannelPackerWindow.cs.meta
Assets/MixedRealityToolkit/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MixedRealityToolkit/Resources/Shaders/ChannelPacker.shader
Assets/MixedRealityToolkit/Resources/Shaders/ChannelPacker.shader.meta
Assets/MixedRealityToolkit/Resources/Shaders/MixedRealityStandard.shader

Overview
---
Adding a few improvements to the MRTK/Standard shading system:
- A GPU accelerated channel packer editor for easy channel map generation
- Spherical harmonics support for better lighting
- Vertex color support (can now be used with the Unity LineRenderer)
- Improved lightmapping support with a meta pass
- HDR emission support
- Minor bug fixes
Screenshot of the channel packer:

Channel Packer Editor + Other Shader Features

---

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs

Overview
---
As currently written, the FocusProvider assumes that the camera will only ever have more than 0 children if the UIRaycastCamera is already present. This isn't a robust assumption, as devs can place additional children under the Camera, which leads to null refs.

Update FocusProvider's UIRaycastCamera logic

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs

Call observedObjectParent instead of ObservedObjectParent, so we don't create GameObjects on cleanup.

Update Spatial Awareness system cleanup

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnToggleReceiver.cs

Overview
Removed a check comparing the Interactable's DimensionIndex to a cached index value that was meant to keep the receiver and interactable in sync. The check is not needed and actually caused errors if the interactable's toggled state is set through code using SetDimensioniIndex(1).
Changes
---
- Fixes: # .

removed check for dimension index change which should not be needed.

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset
Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs

That's what the mouse manager expects, otherwise input action mappings are not applied to mouse events.
Overview
---
Changes
---
- Fixes: # .

Declare mouse controller as 'any' handedness

---

README.md

Overview
---
The main hyperlink calling out the a MRTK-vnext development branch is broken. This review redirects developers to our branch guide wiki page, which should remain regardless of branching name changes
Changes
---
- Fixes: #3335 .

Remove broken hyper link - current development branch

---

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Orbital.cs

Overview
---
Increase the stability of the Orbital solver in case the transform target is destroyed or otherwise null.
Also, the `targetYRotation` should be 0 instead of 1 when the transform target is null.

Add additional null checking in the Orbital solver

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs

Overview
---
The method didn't need anything out of `InteractionSourceState`, so this removes the need to call `.Source` multiple times.

Change WMR.RemoveController to take in an InteractionSource

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MixedRealityToolkit/Services/BaseService.cs

Overview
---
This change updates the dispose pattern implementation in BaseService.cs to better match the documented sample ( https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose ).
As part of this change, the WindowsMixedRealitySpatialMeshObserver's cleanup code was modified to use Dispose internally and some UNITY_WSA #ifs were consolidated for readability.

update dispose pattern implementation, spatial mesh observer now uses dispose

---

README.md

Overview
---
The landing page currently contains some nuget package generation steps that could benefit from more details and may lead to users feeling like they haven't correctly setup the MRTK. With the packaging story for the MRTK still under development, I think we should be more cautious on asking that all MRTK users go through these nuget generation step. For example I have hit some issues with my local setup where nuget doesn't resolve in my powershell environment, but i am still able to use the MRTK. 
To keep this packaging goodness, I've created a new wiki page in our documentation:
https://github.com/Microsoft/MixedRealityToolkit-Unity/wiki/Generating-Nuget-Packages 
It seems like there can be greater velocity in editing/fixing wiki pages compared to readmes. So it may be a …

Update landing page read me

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Layout/ButtonBorder.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableAnimatorTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableAudioTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableColorTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableMaterialTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableOffsetTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableRotationTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableScaleTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableShaderTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableStringTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableTextureTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableThemeBase.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableThemePropertyValue.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/ScaleOffsetColorTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTip.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTipConnector.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTipUtility.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/Easing.cs
Assets/MixedRealityToolkit/Utilities/Physics/VectorRollingStatistics.cs

Overview
---
Small performance tweaks - we stuck to changes that didn't require much refactoring. Primary test case was a scene with 50 HoloButtons and 50 Unity UI Canvas buttons. Tested using HoloLens and VR devices.
Changes
---
- Removed allocations from Interactable components (~5k per frame in test case)
- Shaved a few milliseconds off hot Interactable profile code
- Cached Interactable host components using Init wherever possible
- Small improvement in VectorRollingStatistics (but they add up)
- ToolTips only update content borders when content is changed

Small Performance Tweaks Round 2

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs

Overview
---
This PR adds the ability to have the registered service providers profile to auto-set its values based on the already set values in the MixedRealityExtensionServiceAttribute.
To start, it tries to load the default profile from an asset path, and it sets the supported platforms automatically.
(video didn't pick up the service type dropdown)

Read the default profile and default platforms from the ExtensionServiceAttribute

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs

Workaround for a blocker bug in our development workflow

Fix air-tap in Holographic Remoting (workaround for Unity issue #1033526)

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/SpectatorViewPluginArUcoMarkerDetector.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpatialCoordinates/MarkerSpatialCoordinateService.cs

Overview
---
We could get into a weird state where the assigned marker to a spectator was rapidly increased based on the delay in sending the assigned marker over the network. 
Changes
---
We now check our local cache of the spectator marker value on the main user device. If its assigned, we don't reassign a new number in instances where the spectator has not yet registered that its had a marker assigned.

Fix marker assignment by checking local cache of spectator information

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployWindow.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs

Overview
With Unity 2019.1 the option to generate project references for UWP was removed. The related API calls were therefore removed as well and caused the compilation errors. Since .NET scripting runtime was removed for UWP too, code was futher excluded when combinations of the two appeared. 
Changes
---
- Fixes: #3104

Fixed script errors related to upgrade to Unity 2019.1

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpatialAwarenessMeshObserverProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs

Overview
---
Adds sub-profile inspector rendering. Whenever a profile field is drawn in a default MRTK configuration profile a dropdown is created which lets the user display the contents of the field's profile. This allows users to quickly access and modify all active profiles in a project when they select the MixedRealityToolkit object in the scene.
Configuration profiles are made aware of when they are being drawn as sub-profiles and omit logos and 'Back' buttons in this state.
Dropdown states are stored in editor prefs and will persist across sessions.
Problems
----
- If every nested sub-profile from the main configuration profile is open at once the inspector can become a bit sluggish.
- There's no check for recursive profile inspectors being drawn. I can't imagine what scenario …

Mrtk Inspector Upgrade (Part 2)

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityDiagnosticsProfile.asset
Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs
Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
Assets/MixedRealityToolkit/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Interfaces/Diagnostics/IMixedRealityDiagnosticsSystem.cs

Enable diagnostic visualization by default.
Add ability to configure frameRateDuration (time span to collect frames for calculation)
Update visual profiler to allow setting sample duration via code
Add diagnostics recommendation in toolkit config inspector
Fixes #3536

Diagnostics settings updates

---

Assets/MixedRealityToolkit/Attributes/MixedRealityControllerAttribute.cs
Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs

Overview
---
- Wrap editor specific code in the controller mapping profile in #if / #endif.
- Add "using Microsoft.MixedReality.Toolkit.Core.Extensions" when building UWP on .net backend
This does not 100% resolve .net backend build breaks. There are some changes needed in interactables to work around AppDomain usage

Controller mapping profile and controller attribute fixes

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs

Overview
---
From this:
to this:
(extra space is between Profile and contents)

Remove extra space from BaseMixedRealityProfileInspector

---

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Changed the order of checks since the platform can filter classes that might be null
Overview
While implementing the Oculus Go I received 5 errors every time I started the app. Since Service Providers specific to certain platforms are stripped by their containing ASMDEFs, checking for null first and the supported platform second does not seem very idea.
Changes
Changed the check order

Changed the order of checks

---

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/ControllerFinder.cs

Overview
---
When implementing a custom controller without a visualizer (Keyboard controller) a NRE occurred in check when accessing GameObjectProxy
Changes
---
- Fixes: # .

Fix NRE when custom controller has no visualizer

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityFocusHandler.cs

Overview
There were still traces of the two obsolete methods in IMixedRealityFocusHandler. I removed them along with the methods.

IMixedRealityFocusHandler cleanup

---

Assets/MixedRealityToolkit/Attributes/MixedRealityServiceProfileAttribute.cs
Assets/MixedRealityToolkit/Attributes/MixedRealityServiceProfileAttribute.cs.meta
Assets/MixedRealityToolkit/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs
Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerVisualizationProfile.cs
Assets/MixedRealityToolkit/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs
Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs
Assets/MixedRealityToolkit/Definitions/MixedRealityRegisteredServiceProvidersProfile.cs
Assets/MixedRealityToolkit/Definitions/SpatialAwareness/MixedRealitySpatialAwarenessMeshObserverProfile.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs

Overview
---
This PR adds the MixedRealityServiceProfileAttribute class and adds inspector warnings for incorrectly configured registered services.
The attribute should be used on any profile class that is consumed by an IMixedRealityService.
```
[AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = true)]
public class MixedRealityServiceProfileAttribute : Attribute
{
public MixedRealityServiceProfileAttribute(Type serviceType) { ServiceType = serviceType; }
public Type ServiceType { get; private set; }
}
```
```
[MixedRealityServiceProfile(typeof(IMixedRealitySpatialAwarenessMeshObserver))]
public class MixedRealitySpatialAwarenessMeshObserverProfile : BaseMixedRealityProfile 
{
...
}
```
This is intended mostly for registered service providers. But core services …

Mrtk Inspector Upgrade (Part 3)

---

CodingGuidelines.md

Coding guidelines document was requiring the old namespace pattern. With #3546, this pattern has been simplified. The guidelines have been updated to reflect the pending change.

update namespace rules to match #3546

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Overview
---
This change fixes a few null reference bugs in the editor when MRTK is unavailable, and a prefab is opened. The simplest repro is:
1. Create a new scene
2. Open any prefab
3. Observe null reference being thrown.

Editor Null Reference Fixes

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProvider.cs

Overview
The BaseMixedRealityLineDataProvider was updating its matrices in Update, which did not match the timing of the LinePointer needing the matrix in its PreRaycast phase. Since it's the only class activating this component in OnPostRaycast and is raycasting all the time, I replaced its internal Update with a MatrixUpdate in the LinePointer's PreRaycast phase.
Changes
---
- Fixes: part of #3614.

Mrtk data provider matrix update

---

Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs

Overview
In case meshObject.GameObject was null or was destroyed, meshObject.Filter and meshObject.Collider were still accessed without null checks. all 3 references were actually referencing the same gameobject with its components

fixed NullReference

---

Assets/MixedRealityToolkit.Services/BoundarySystem/MixedRealityBoundarySystem.cs
Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs
Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs

Overview
Sometimes the Editor throws a lot of errors about destroying transforms and other components that are not allowed to be Destroyed, even though there's no code doing this.
That's because altering a gameobjects hierarchy (detaching children) before calling DestroyImmediate on it is not supported.
Only detach children if the call is Destroy
Unity Case 1136869

Fix: detaching children before DestroyImmediate causes Errors in the Editor

---

Assets/MixedRealityToolkit/Definitions/Physics/RayStep.cs

Overview
The code in GetPointByDistance compared and subtracted the remainingDistance with the raystep's array length, not with the individual length of the current raystep.
I fixed that and also reduced the code, making GetPointByDistance use GetStepByDistance introducing a returning tuple.
Changes
---
- Fixes: #3571 .

MRTK Raystep fix and cleanup

---

Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs
README.md

The previous change added some new information into the middle table, which broke the table formatting (table content must be contiguous otherwise it ends up just rendering the | and ---- values as-is)

Fix up the README.md layout issues

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs

Overview
The Unity Editor still detects a motion controller during the first frame when it was active during the last run regardless of it being now turned off or not. You'd need a second run to start with no controllers detected at all. Actual detection always happens a couple of frames later.
It's save to ignore the detection during the first frame altogether
Unity case 1137312

Mrtk avoid unity editor bug

---

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs

Overview
The Ray that actually hits an object was not adjusted in length. Therefore the check if hit UI elements should override the physics result always turned out to be true if distances were below the Rays Length, which in case of the gaze is 10 units by default.
Changes
---
- Fixes: #3645

MRTK Fix Raycast sorting

---

Assets/MixedRealityToolkit.SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs

Overview
---
The SpeechInputHandlerInspector doesn't properly delete the last keyword, since it tries to continue through displaying the keyword and ends up throwing exceptions:

Fix exceptions deleting SpeechInputHandler's last keyword

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs

Use the `OnBeforeFocusChange` handler to keep track of all the pointers entering and leaving the interactable instead of using `OnFocusEnter/Exit` as those are only triggered for the first pointer entering/last exiting.
- Fixes: #3577 .

Modified Interactable to keep track of pointers using focus changed events

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildInfo.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/IBuildInfo.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs

Add command line switch to change the scripting backend in command line builds. This is needed in order to build using .NET backend on CI.

Add switch for scripting backend

---

.gitignore

Overview
---
Spectator View will likely begin to start consuming NuGet packages. This change is intended to avoid checking in any nuget related helpers or nuget package obtained dlls.
Changes
---
- Fixes: # .

Add items to .gitignore file to avoid checking in nuget packages

---

Assets/MixedRealityToolkit/Utilities/Lines/Renderers/BaseMixedRealityLineRenderer.cs
Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MeshLineRenderer.cs
Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs
Assets/MixedRealityToolkit/Utilities/Lines/Renderers/ParticleSystemLineRenderer.cs
Assets/MixedRealityToolkit/Utilities/Lines/Renderers/StripMeshLineRenderer.cs

Overview
---
Uses a different method to render instanced meshes in MeshLineRenderer. Less finicky both at runtime and in editor.
- Removed command buffers
- Removed hidden mesh / OnWillRenderObject call
- Adds point distribution mode to base line renderer class

MeshLineRenderer improvement

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/BaseFocusHandler.cs

Overview
---
In #3113, `IMixedRealityFocusHandler` was changed to no longer be a `IMixedRealityFocusChangedHandler`, but BaseFocusHandler, which consumes events from both interfaces, didn't have `IMixedRealityFocusChangedHandler` added. Since then, this script has silently not been receiving events it depends on.

Fix BaseFocusHandler's events / interfaces

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs
Assets/MixedRealityToolkit.SDK/Features/Audio/Influencers/AudioInfluencerController.cs
Assets/MixedRealityToolkit/EventDatum/GenericBaseEventData.cs
Assets/MixedRealityToolkit/EventDatum/Input/BaseInputEventData.cs
Assets/MixedRealityToolkit/EventDatum/Input/SpeechEventData.cs
Assets/MixedRealityToolkit/Utilities/FastSimplexNoise.cs
CodingGuidelines.md

Overview
---
In previous performance investigations we've found that using DateTime.Now adds significant overhead especially when used in the Update() loop. [Others have hit the same issue](https://stackoverflow.com/questions/1561791/optimizing-alternatives-to-datetime-now).
Prefer using DateTime.UtcNow unless you actually need the localized times (a reason may be wanting to show the current time in the user's time zone). If you are dealing with relative times (i.e. the delta between some last update and now), it's best to use DateTime.UtcNow to avoid the overhead of doing timezone conversions.

Prefer DateTime.UtcNow over DateTime.Now

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs

Overview
---
On source lost, we were unregistering from the FocusProvider before sending the event. This led to focused objects not properly receiving source lost events.

Fix focus bug in MixedRealityInputSystem.cs

---

Assets/MixedRealityToolkit/Utilities/CameraCache.cs

The Camera object is a unity object, which actually must be checked using the == null or != null operator explicitly (because Unity) overloads that operator. It's possible for a camera to be destroyed but not yet null (i.e. the unity concept of the the camera is dead but the object is still non-null). The ?? operator skips Unity's overloading, and will sometimes return "it's not null" which is technically true but still not safe to use from a Unity perspective.

Remove usage of the non-overloaded null operator on the camera cache.

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs

Overview
---
From @julenka:
This PR fixes a bug in the input system where pointers are dispatching pointer events to all other pointers attached to an input source, which causes a large number of null pointer exceptions and also duplicate events to be sent to the system.
Currently MixedRealityInputSystem dispatches any event `E` to all pointers attached to `E`.InputSource. Therefore, when a Pointer wants to send a PointerDown event to the object it is focusing, instead the following happens when trying to dispatch pointer event `E` from pointer `P`:
1. Initialize `E` with information about pointer `P` so that `eventData.Pointer` returns `P`
1. Get the InputSource `S` attached to pointer `P`
2. For all pointers `P2` on `S`...
a. If `P2` is focused on some object `O`
b. Dispatch pointer …

Pointer focus dispatch rework

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/FingerCursor.cs

Overview
---
The finger cursor was aligning with the surface normal rather than the inverse surface normal. Normally not an issue because the cursor looks the same front & back but when the cursor moves from finger alignment to surface alignment it does some extra rotation.

The finger cursor should align the inverse surface normal

---

Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs

Ray-cast distance calculations should take into account that ray-casts from the UI camera originate from the near clipping plane of the camera since Unity 2017.4.3 and newer versions.
Overview
---
MRTK/HTK does not currently calculate the distance to a UI canvas correctly (#3359) or correctly work out the depth of UI objects when trying to determine if a UI or physics object should get focus (#3322). This is only an issue in Unity 2017.4.3 and later versions due to the introduction of the Unity fix [934908](https://issuetracker.unity3d.com/issues/using-canvas-on-world-space-or-camera-buttons-are-not-clickable-if-pos-z-is-set-less-than-zero)
Changes
---
Currently the original MRTK claims to support Unity 2017.2+ so I have assumed we need to variant the code based on the version of Unity to …

UI Ray-cast distances should take into account the near clip plane

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs
Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs
Assets/MixedRealityToolkit/Interfaces/Devices/IMixedRealityDictationSystem.cs

Overview
---
The speech and dictation providers had their constructors wrapped inside `#if` statements, which seemed to be preventing their docs from being properly generated. I moved the statements around to reduce the scope they were wrapping.

Update #if wrappings around speech providers

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs

This was a side effect of separating IMixedRealityDataProvider from IMixedRealityExtensionService.

Fix test failure (core 04_09) related to requesting the wrong interface type

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs

changed flag for gltf model load fail - default case is now that we load the model by calling the base class TryRenderControllerModel. 
fixes model loading for devices that use the articulated hands controller

fixed hand mesh loading on hl2

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs

There was a missing "break;" statement that was causing the input provider to fall through and execute code at the wrong time, resulting in an ArgumentException related to "control 4'2 position".
As part of the validation, the input profile was updated to add back the dictation provider.

Fix error when auto-configuring input data provider

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs

The new hand pose information is only present on universal contract version 8 and up.
This was found by looking at ildasm against the previous SDK (i.e. version 7) and the latest drops of the new one (version 8). Note that other things in this file still exist in previous versions (i.e. version 2 actually has the SpatialInteractionManager defined).
This is primarily to ensure that we don't try to exercise an unsupported API if we end up getting this far (we also shouldn't because this object should only get instantiated in cases where hands are detected).
It probably makes sense to restructure this in the future, however, to make it so that we never try to call UpdateControllerData in the case that the underlying APIs this file requires aren't supported (so maybe each controller can …

Gate the articulated hand update loop behind a platform check.

---

Documentation/toc.yml

Previous PR https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3731/files didn't update the toc.yml, but the build didn't catch the issue because it was broken due to SDK versioning issues (and then scene rename issues).
Basically there were a chain of things that were broken and we only now got to the point where we can see it working.

Fix the doc build

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_Visualizer/Scripts/UserInput_Playback.cs
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/OpenKeyboard.cs

Some of the new code that was introduced added dependencies on UWP APIs
even when calling from a non-UWP context. (i.e. UserInput_Playback.cs)
Also added a UNITY_WSA check around OpenKeyboard because the touch keyboard
APIs are only documented to work on UWP/IOS/Android/etc locations.

Fix the broken OpenVR build.

---

Documentation/GettingStartedWithTheMRTK.md

Due to the new HL2 payload, in order to build against new MRTK you need
to have the latest windows SDK (as of right now it's still in the
insider state).
While we have an issue open to see if we can disentangle this (https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3801) in the interim we should at least document the actual requirements

Update the Getting Started page to mention the required windows SDK.

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/ToggleBoundingBox.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs

In previous PRs we've gotten feedback that BoundingBox feels like a more
UI concept than a "utilities" concept, so moving this to that namespace.

Change the namespace of BoundingBox to the UI one (from Utilities)

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs

The parent->child enumeration currently throws an exception for input
sources that don't have a parent set. Add a null check around those
references so that we don't throw an exception in those cases.
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3802

Add a null input parent check in DefaultPointerMediator

---

.gitignore

Added to .gitignore the 'doc' folder generated when running DocFX

Ignore DocFX generated doc/ folder

---

Assets/MixedRealityToolkit/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs

Added a range of 0 (show FPS every frame) to 5 seconds

profiler sample rate was unbounded in the inspector

---

Documentation/GettingStartedWithTheMRTK.md

Due to prefab changes in Unity 2018.3, that's our minimum supported Unity version.

Update minimum supported Unity version in docs

---

Assets/MixedRealityToolkit/Providers/BaseController.cs

- removed the error for no controller model available as there's platforms that don't have a controller visualization like xbox controller and touch input
fixes: 
#3685 
#3710

replaced error with comment for platforms that don't have a controller visualization

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs

Overview
For instance, the mouse input source is available before activating the input module

When activating MixedRealityInputModule, handle input sources already present

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildInfo.cs

No longer build appx with WSAPlayer by default. Also removed build platform defaulting to x86 for uwp builds.

No longer build appx with WSAPlayer by default

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit/EventDatum/Input/HandTrackingInputEventData.cs
Assets/MixedRealityToolkit/EventDatum/Input/InputEventData.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityInputSystem.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/UnityTouchController.cs

Implemented the changes described in proposal #3791 . As a side effect, this PR changes the handedness of some input events raised by mouse and unity touch controllers from `Handedness.None` to the actual handedness of each controller as defined by `IMixedRealityController.ControllerHandedness`.

Removed variants of methods to raise input events that receive no handedness.

---

ProjectSettings/EditorBuildSettings.asset

Overview
---
Remove example scenes list in the Build Settings for the users without Examples package.

Remove example scenes list in the Build Settings

---

README.md

It turns out that we've been checking in conflicting changes to README.md in multiple locations.
This takes most of the changes from mrtk_release (it's been the most active area of change)

Merges the README.md changes from mrtk_release into mrtk_development

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/PanZoom_RectTransf.cs

This actually shows up in the unity editor console.
Why this one shows up in the unity editor console and not other ones is a mystery to me but let's clean this up.

Remove the unused variable warning.

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs

Overview
---
- MixedRealityInputSystem was not extensible, as methods were not virtual.
- Simply converted all public void methods to be virtual, to make it easier to extend the class without duplicating it.
Changes
---
- Fixes: # .

Allow extension of MixedRealityInputSystem

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/HolographicButtonSeeItSayItLabel.asset

Overview
---
Fix See-it, Say-it label delay timing regression: Easing was unchecked. 
Interactable theme updated to have easing timing for 1 sec.
Changes
---
See-it, Say-it label profile updated. No code change.

Fix See-it, Say-it label delay timing regression: Easing was unchecked. Interactable theme updated.

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs

This PR reverts a previous change, which we want to have a little more discussion on.
There are some things we need to chat around performance and ensuring that specific base class functionality is always invoked.
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3821

Revert previous change to MixedRealityInputSystem

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBarButton.cs
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchable.cs

Overview
---
Updates AppBar to make touch events work in all cases. Buttons no longer fade out when disabled but the visual loss is minimal.
Changes
---
AppBarButton gameobjects are now set active / inactive based on visibility. Also fixed an edge case in NearInteractionTouchable where a disabled collider on an inactive gameobject could still be considered 'enabled.'
Fixes #3809 but doesn't address the underlying issue of touchables not receiving touch events when intersecting with touchables with disabled colliders.
- Fixes: #3809

Update AppBar to make touch events work in all cases

---

Documentation/GettingStartedWithTheMRTK.md

Some of the prefabs and assets require text mesh pro, which isn't apparent as you start using things. We aren't able to automatically import TMP assets, so we should provide guidance that these are required.

Add a note that prefabs/assets require TMP.

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/ShellHandRayPointer.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointerVisual.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPan.cs
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit/Definitions/Physics/FocusDetails.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityPointerHandler.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityPointer.cs
Assets/MixedRealityToolkit/Providers/GenericPointer.cs
Assets/MixedRealityToolkit/Utilities/Physics/MixedRealityRaycaster.cs

Add `TargetPositionLockedOnFocusLock ` for pointers to to allow the cursor to not be position-locked on HandInteractionPan surfaces
Overview
---
In order for the pannable texture to be fixed to the pointer target position, the pointer target position needs to be movable when focus is locked. This change ensures that the focused object is maintained, even if the pointer ray cast may not be hitting the focused object anymore. This only happens when `IMixedRealityPointer.IsTargetPositionLockedOnFocusLock` is set to false (usually in an event handler). The default setting is to keep the position locked on focus lock.
Since focus lock is handled per pointer, target position lock needs to be handled on the same level.
The initial idea was to only allow a `FocusSessionConfiguration` object to be …

Add TargetPositionLockedOnFocusLock for pointers

---

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityInputSystemProfile.asset.meta
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityToolkitConfigurationProfile.asset

Data providers in custom input system profiles were lost when the profile was refactored.

Regenerated input system profile for speech sample so we have the default data providers

---

README.md

Since I split the pipelines in two, the status badge has only been reporting CI status and not docs status.

Add docs ci badge to readme

---

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SelectRepairedTypeWindow.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SelectRepairedTypeWindow.cs.meta
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs

Overview
---
When a type reference is lost in a SystemType field - common when refactoring namespaces - a 'Try Repair' button is displayed. Clicking it searches filtered types by name. If a matching name is found, that type reference is used.
If no types are found you're altered with a dialog. If multiple types are found, a utility window is launched so you can select which type to use.
- Fixes: #3672 #3693

Adds 'Try Repair' to SystemType property drawer with missing class reference

---

Assets/MixedRealityToolkit/Inspectors/ChannelPackerWindow.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs

Overview
---
Moves _Channel Packer_ and _Build Window_ to a _Utilities_ sub-menu.
A nitpicky change but I feel it's important that _Add to Scene and Configure..._ remain as obvious as possible.
Current:
New:

Adds 'Utilities' to Mixed Reality Toolkit menu

---

Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHandPose.cs

Overview
---
Alternative Pinch gesture that keeps the wrist stead and moves the index finger and thumb instead. This was requested by users, but rather than having one or the other i would rather provide both options. The fixed index tip variant is still the default, since it is considered better for testing interactions. The alternative with moving index finger is more anatomically correct though.
Changes
---
- Fixes: # .

Alternative Pinch gesture with a steady wrist.

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs

Overview
---
MixedRealityInputModule was only correctly releasing pointer data for input sources currently in the input system. Changed it to release all pointer data instead.
Changes
---
- Fixes: #3944 .

Remove all pointer data on input module deactivation

---

Assets/MixedRealityToolkit.Extensions/PhotoCapture/HoloLensCamera.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/SpectatorViewPluginArUcoMarkerDetector.cs

Overview
---
Its better to not expect users to release a frame. They should have to opt in to incrementing the reference count for said frame.
Changes
---
- Fixes: # .

Release frame after its been used for aruco marker detection

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs

While looking into other build related issues (i.e. IL2CPP vs .NET) I noticed that there were some issues with the build window (with respect to SDK versioning and chosing the right SDK).
There were a couple of issues:
1) There was a concept of a "min" SDK, but the code was actually doing an equality comparison to look for it. That is, if you had GREATER than the min SDK it would fall over.
2) It looks like even if you set a different target SDK than you current (i.e. if you had a higher target SDK than the current min one specified by the MRTK), it would lower your target.
This does change things a bit in that this will now prefer the latest SDK (over always the min SDK). It's a marginal improvement over the old in that now future progress (where new SDK version drops occur) don't cause …

Build and deploy window fixes

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityPreferences.cs

Interestingly enough this appears to be the only compile-time incompatibility
with Unity 2019.1. 2019.1 support in the MRTK is still highly experiemental
but with this change the UWP should build (and be deployable to HL2)
Also note that this change doesn't affect 2018.3 behavior, see:
https://github.com/Unity-Technologies/UnityCsReference/blob/2018.3/Editor/Mono/Settings/SettingsProvider.cs
vs
https://github.com/Unity-Technologies/UnityCsReference/blob/2019.1/Editor/Mono/Settings/SettingsProvider.cs
The constructor for this object used to default to SettingsScope.Project
2019.1 removed the default (for the second parameter only).
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/3951

Update the MixedRealityPreferences to explicitly provide a SettingScope

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs

One of the points of customer feedback we've seen internally is that as a new person configuring a scene for the first time, they see a list of ~5 profiles of which they don't know what to pick. We should at least point to a reasonable default (i.e. the default profile), even if we don't want to filter down this list further to avoid breaking advanced user scenarios.

Update the MRTK root profile picker to select a reasonable default.

---

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs

Currently there place where we clone profiles is somewhat inconsistent - if you clone default root MRTK profile it will go into the CustomProfiles by default. If you use the clone button for the other profiles, they will get dumped in the root Assets folder, which isn't optimal. This makes it so that we at least default to a reasonable thing (the CustomProfiles) while providing a way to override that if so desired.

Update the default location that profiles are cloned to.

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs

A couple of things here:
BuildDeployWindow.cs - The user already gets .NET backend deprecation warnings in the regular Unity build window. The language of this warning is a bit strong telling people to switch to IL2CPP that may have good reason to stick to .NET (i.e. they actually want a debuggable experience and a faster inner loop). This changes the message to be closer to what Unity says - i.e. it's deprecated, try to use the new thing, but you don't have to. Originally I was going to remove this but then opted to keep it around in case people are only using this build window (in which case they still have some notification that this isn't going to be supported going forward.)
MixedRealityEditorSettings.cs - This was actually a fairly problematic suggestion, because really going to …

Update some of the MRTK-specific .NET scripting backend callouts.

---

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Overview
---
Generating a new instance during app shutdown in the editor allows instances to persist into edit mode, which cause unwanted behavior.
This fix returns a null Instance of the MRTK if none are found in the scene and the app is quitting while running in the editor.
Previously, the editor could attempt to ping the MRTK instance while the app was shutting down, which caused it to generate an instance during shutdown, which it held onto during the transition back to edit mode.
Changes
---
- Fixes: # .

Prevent MRTK instance from being created OnAppQuitting

---

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Utilities/MixedRealityToolkitSceneChecker.cs
Assets/MixedRealityToolkit/Utilities/MixedRealityToolkitSceneChecker.cs.meta

Overview
This check should not be performed when loading profiles, since it only happens when a profile is actually visible in the inspector, which can happen at arbitrary times in the workflow or not at all. Profiles as separate assets should not be responsible for modifying scene state.
---
Changes
The new utility class will be created on project load (`[InitializeOnLoad]` attribute) and check for a MRTK instance when a new scene is created (with default objects) or when a scene is loaded.
This also solves the problem that the popup would come up when running tests, since these first start from an empty scene before a test scene is loaded. The check will now be ignored in that case, using the `NewSceneSetup.EmptyScene` parameter.
---
- Fixes: #3884 .

Move MRTK scene check out of the profile inspector and into a utility class.

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityPreferences.cs

This change replaces "MRTK" with "Mixed Reality Toolkit", "Microsoft Mixed Reality Toolkit" or "Mixed Reality Toolkit - Unity" as appropriate.
- Fixes: #3979  .

update preferences ui to use full name of MRTK

---

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs

Prior to this change, when given a new name for the profile that will be cloned, the cloning code just throws away the name (see how it is taken but not used).
Now we honor the name, horray.

Update the profile clone window to honor the name given to it.

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoPointerProfile.asset
Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputPointerProfile.asset
Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs

This was introduced as part of our large payload but was actually never hooked up to anything - it shows up as an option in the inspector but is misleading (i.e. you think it should show a cursor with eye gaze, but it doesn't)

Remove references to dead field showCursorWithEyeGaze.

---

Assets/MixedRealityToolkit/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs

Fixes two things, which kinda are fixed together because one of them blocks the other. The main thing this addresses is the cloning of profile's failure to clone subprofiles correctly (i.e. if you do:
Click 'Copy & Customize' in Mixed Reality Toolkit component
Click 'Clone' by Input System Profile
Select 'Clone Existing' in Pointer Profile and click 'Clone'
Navigate to newly created pointer profile and observe how the Pointer Options array is empty)
1) Removed line in ScriptableObjectExtensions was causing exceptions in the case where you cloned a profile. This actually was causing the sub-profile cloning code to hit an exception and then never actually copy things over. This also manifests itself when you just hit "copy and customize" for the root profile. AFAICT I can see that this has …

Fix a couple of inspector related bugs and exceptions

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs

Overview
---
Previously the only way to modify settings like rotation constraints was by modifying the serialized property fields. This made it difficult to configure handlers when adding them via another script, as in a factory pattern.
Changes
---
- Fixes: # .

Exposed manipulation handler parameters to be publicly set

---

Assets/MixedRealityToolkit/Definitions/Devices/ControllerMappingLibrary.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs.meta

This work is needed when MRTK is split into separate NuGet packages and may contain assets split across those package folders.

Updated with a new way of loading resources from project folders

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBar.cs

Overview
---
AppBar no longer sets custom buttons to invisible on startup or during update. Custom button visibility can be managed by a separate script.
- Fixes: #3966

Stops AppBar from changing custom button visibility

---

.github/pull_request_template.md

One idea point of feedback around pull requests is that it's often not clear the level of verification expected from reviewers - should reviewers be patching all changes to be validating them, only specific ones. For new features, it's also sometimes unclear how a reviewer can functionally test things (i.e. exactly what should be tested, how to engage the scenarios, etc). One idea is to provide an optional section on the PR template where people can call out specifics they want reviewed (i.e. please patch my change and test ABC out, or please pay attention to this specific thing)

Update the Pull Request template to include a "Verification" section

---

Assets/MixedRealityToolkit/Utilities/MixedRealityToolkitSceneChecker.cs

Overview
---
This stops the scene checker window from opening during / immediately after a build as described in #4043
Requests for validation
---
Verify that this fixes the repro case described in #4043

Disable MRTK scene checker window while build is active

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs

This is necessary so other providers can still be enabled after the speech input provider fails.
Overview
---
Changes
---
- Fixes: #4026 .

Catch Unity exception in speech input provider.

---

Documentation/DownloadingTheMRTK.md
Documentation/GettingStartedWithTheMRTK.md

We currently do not support several of the other mechanisms listed in the DownloadingTheMRTK page, and there's nothing more frustrating when coming upon docs than seeing text that says "coming soon" that isn't helpful.
Our docs should reflect the current state of how to use the product, and when additional support is added for other delivery mechanisms, we should then update the docs to describe those mechanisms.

Clean up delivery mechanism documentation.

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/Slate.prefab

Overview
---
The fingertip visual should align with the slate normal, but it didn't.
Updated
---
Now fingertip ring visualization aligns with the surface within the threshold distance.
Changes
---
Updated Slate prefab's Local Forward Z to -1. (We already updated other buttons in the scene before)

Fingertip ring surface alignment bug fix

---

Documentation/MixedRealityConfigurationGuide.md

Without a newline after the > line, it was rendering the line as a header, which was super super super super super weird.

Fix the formatting of the configuration guide's "Back to Configuration Profile" messages.

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableThemeShaderUtils.cs

Overview
---
Changing the Interactable system to use the shared material to avoid creating new material instances and breaking batching. Because MaterialPropertyBlocks are used for setting material properties the shared material is used to set the initial state of the MaterialPropertyBlock(s) before mutating state.

Interactable Optimization

---

Assets/MixedRealityToolkit/Attributes/EnumFlagsAttribute.cs
Assets/MixedRealityToolkit/Definitions/BoundarySystem/Edge.cs

I'm going through the process of looking through our codebase to learn more about everything, and as I'm seeing random issues like this I'm fixing them.
In the case of EnumFlagsAttribute.cs we shouldn't have to go to a link to understand the context.
In the case of Edge.cs it was referencing what appeared to be an older naming of the type.

Fix up a few of the doccomments for the EnumFlags and Edge types

---

Documentation/toc.yml

This particular entry in the TOC wasn't hooked up even though the underlying page was already created.

Fix the reference to the 'Configuring the Spatial Awareness Mesh Observer' page.

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

These produce compiler warnings, which for projects that treat warnings as errors, become errors.
@wiwei @davidkline-ms @andreiborodin

Initialize geometry fields to null

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/InputSystemGlobalListener.cs

There are multiple ways we wait for InputSystem validity, some of which
check for the current state of the object and some of which use the await directly.
AFAICT it looks like we should have moved to a common helper (i.e. in this PR: https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3462/files), so this common-izes this action into the base class

Standardize on the way we wait for InputSystem validity.

---

Assets/MixedRealityToolkit/Inspectors/InputTemplates.meta

Overview
---
This folder was moved outside the Assets folder in #3748, but the meta was left behind.

Removing a stale meta

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs

We've seen a couple of instances now where the MixedRealityInputModule and various providers (i.e. GazeProvider) are getting initialized in non-deterministic fashion. If the GazeProvider starts first, it will raise its source detected, and then when MixedRealityInputModule::ActivateModule is invoked, it re-invokes OnSourceDetected, which tries to add the same pointer to the pointer dictionary.
This throws an exception (bad). We want to update the OnSourceDetected function to only try to add it to the dictionary if it doesn't exist to work around this and unblock a few consumers.
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/4084

Workaround for mis-ordered initialization of some input providers.

---

pipelines/ci.yaml
pipelines/pr.yaml

We should switch to YAML build definitions to leverage the benefits of having "configuration-as-code" (as previously discussed in an internal email thread and offline). 
This change adds YAML configuration files that correspond to the existing MRTK_CI and MRTK_PR jobs.
Switching from visual designer to YAML will require setting up new builds (it should be straightforward although we will lose build history and we need to pay close attention to setting up triggers, etc.) and I can take care of it afterwards.
The CI config references a new variable "NuGetFeedId" (which is a GUID of the feed that we use to publish the packages internally).
I verified the set up by creating personal test builds on my fork of the repo:
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buil …

Add definitions of AzurePipelines builds

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs
Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs

Overview
---
Reported on Slack: opening the MRTK caused issues on non-Windows platforms (in this case, Mac).
This PR fixes most of them, but I'll need to get my hands on a Mac to repro the glTF-specific ones.
The fix: I moved the methods required by the interfaces outside of the Windows-platform `#if`s, where possible, or created a second version for non-Windows platforms where not possible.
Report: https://holodevelopers.slack.com/archives/C2H4HT858/p1556141818234600

Fix using MRTK in Unity editors on non-Windows platforms (part 1)

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/InteractableHighlight.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/RadialView.cs
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityInteractionMapping.cs
Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputActionsProfile.cs
Assets/MixedRealityToolkit/EventDatum/Input/HandPanEventData.cs
Assets/MixedRealityToolkit/EventDatum/Input/SourcePoseEventData.cs
Assets/MixedRealityToolkit/EventDatum/Input/SourceStateEventData.cs
Assets/MixedRealityToolkit/Extensions/ProcessExtensions.cs
Assets/MixedRealityToolkit/Interfaces/EventSystem/IMixedRealityEventSystem.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityFocusChangedHandler.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityFocusProvider.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityInputSystem.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityPointer.cs
Assets/MixedRealityToolkit/Interfaces/Registrars/IMixedRealityServiceRegistrar.cs
Assets/MixedRealityToolkit/Interfaces/TeleportSystem/IMixedRealityTeleportHotSpot.cs
Assets/MixedRealityToolkit/Providers/BaseGenericInputSource.cs
Assets/MixedRealityToolkit/Utilities/Editor/EditorAssemblyReloadManager.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
Assets/MixedRealityToolkit/Utilities/Physics/Interpolator.cs
Assets/MixedRealityToolkit/Utilities/WindowsApiChecker.cs
Assets/MixedRealityToolkit/Utilities/WindowsDevicePortal/DevicePortal.cs

Overview
---
Some of our summary tags were misformatted. This moves all tags into their own scope, to improve the layouting of our docs (remarks tags get their own section):

Move remarks tags outside of summary tags

---

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Tooltips/Bezier ToolTip.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Tooltips/Simple Line ToolTip.prefab

Overview
---
Two of our four Tooltip prefabs used the default TMP font shader so labels only rendered in one eye when using single pass instanced rendering. This fixes the issue.

Fix Tooltip font materials for single pass instanced rendering.

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs

Correctly handle pointers with no controller attached (i.e. gaze pointer) in manipulation handler

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs

Stops FacadeHandler from accessing MRTK instance in DestroyAllChildren

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs
Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputPointerProfile.asset
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs

- Fixes: #4170
The root cause of this bug is that the grab pointer was getting disabled whenever the poke pointer was near a surface, this was a bug in the input mediator.
In addition, I made a few other changes:
- Only render debug pointer rays if the rays are active (makes them easier to view)
- Update default pointer profile to include several colors of pointer rays so we can tell apart poke pointer from grab pointer. The new colors are as follows:

Fix grab pointer is disabled when poke pointer near touchable.

---

ProjectSettings/ProjectSettings.asset

Updating UWP compat to .NET Standard 2.0, as this affects the DLLs produced that are then packaged into NuGet. But has no impact on .unitypackage nor when this repo is consumed as a Submodule.

Update UWP .NET compat to .NET Standard 2.0

---

ProjectSettings/ProjectSettings.asset
pipelines/ci.yaml

The issue is that NuGet is being pacakged with UWP DLLs incorrectly targetting System.Numerics instead of System.Numerics.Vectors.
I previously chased a red herring, and the fault actually lies with us not building a .NET flavor of UWP for packaging purposes.

Another iteration on having the proper NuGet package generation

---

Documentation/EyeTracking/EyeTracking_BasicSetup.md
Documentation/EyeTracking/EyeTracking_ExamplesOverview.md
Documentation/EyeTracking/EyeTracking_Positioning.md
Documentation/EyeTracking/EyeTracking_TargetSelection.md
Documentation/EyeTracking/EyeTracking_Visualization.md
Documentation/toc.yml

This PR removes TODO links that were added in #4074, per https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/4074#discussion_r279567577.
This also removes the link under Service Provider, as it led to a more generic guide. This link will be re-added when the Service Provider guide is published.
This also corrects some paths in the ET documentation that were leading to broken links on the GitHub.io page.
- Fixes: #4163, fixes #4186

Update documentation (ToC and ET images / links)

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs

This reflects the actual requirements set out on:
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html

Update the build window's min Windows SDK version.

---

Assets/MixedRealityToolkit.Examples/Demos/SpatialAwareness/Scripts/DemoSpatialMeshHandler.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs

- Update the base spatial observer to honor the spatial awareness system instance passed in the constructor.
- Remove the duplicate SpatialAwarenessSystem property from the WindowsMixedRealitySpatialMeshObserver.
- Update the spatial awareness demo to retrieve the service instance from the registry,
This change builds upon #4099 and is related to #3545.

update spatial observers and demo to use registry

---

Documentation/EyeTracking/EyeTracking_BasicSetup.md

This issue comes up repeatedly, but unfortunately isn't something that we have too much control over - there needs to be Unity support added to check this from within Unity, and until that happens, we should try to do all we can to call out in our docs that this is a VS specific step.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4193

Bold the fact that the 'Gaze Input' capability is only settable in Visual Studio.

---

Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchable.cs

NearInteractionTouchable.DistanceToSurface was getting the distance to a rectangle in 3D space. This was causing issues where nearby touchable surfaces were interfering with eachother. This fix disregards points that don't project into the rectangle bounds.
I'm sure there's a better way to do this too, but this was a quick fix to existing code that fixed our repro case.

Fix NearInteractionTouchable interference.

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/States/InteractableStateModel.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/CursorModifier.cs
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionGrabbable.cs
Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs

Was going through the code to learn more, found some other small things for cleanup, so cleaning them up here.
General changes:
m_* -> not m_* (this is a C++ like coding convention which doesn't follow our C# guidelines)
InteractableStateModel.cs -> comments removed because they looked like there were notes-to-self and didn't help a reader understand what was going on (I'm more confused reading it).
BaseCursor -> It powers non-gaze cursors as well.
Everything else - general comment cleanup

Code cleanup, 2 of N

---

Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs
Assets/MixedRealityToolkit/Attributes/HelpAttribute.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/HelpDrawer.cs

It's somewhat of a common thing that folks are hitting that enabling the 'Gaze Input' capability isn't clear (i.e. it's something you have to do as a separate step in VS, and while it's documented in our docs, you don't know it's necessary without reading that or debugging through a number of things). Adding this help text will hopefully get some additional eyes while we wait for Unity to expose this property in its own UI.
I considered doing this automatically in our build process, but not everyone uses the UWP build window, and doing automagic stuff can also be really frustrating (because the user never learns that this is required and one day when the magic stops you have to deal with the pain anyway). We already have significant auto-running code complexity in the editor and I don't …

Add explicit help text around the "Eye Tracking Enabled" property.

---

Assets/MixedRealityToolkit/Providers/Hands/HandJointUtils.cs

These functions only work if you pass in the specific Handedness.Left or Handedness.Right. They should be documented as such.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4175

Update the TryGetJointPose docs to accurately describe the set of inputs

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/ColorChanger.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButton.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonPlated.prefab

Our default button prefabs currently invoke Interactable.OnClick events when the button gets unpressed ("On Click Completion"), instead of when a button gets pressed.
This is currently causing many buttons to appear difficult to press by partner teams, for a few reason:
1. People do not realize that they need to 'unpress' the button to activate (evidence: user research in OOBE).
2. We have some bugs in pressable button. For example, if the finger exits the collider on the same frame as an unpress happens, Interactable.OnClick does not get invoked.
Activating buttons on release is only necessary in some cases, such as for buttons on scrollable panels, or for buttons that support press and hold. To unblock customers and allow for most reliable click experience, allow for the easiest …

Activate PressableButton on press by default, not on release

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/CalculatedCameraExtrinsics.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/CalculatedCameraIntrinsics.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/CalibrationDataHelper.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/HeadsetCalibration.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/HeadsetCalibrationData.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/CalibrationData.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/CalibrationData.cs.meta
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/ICalibrationData.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Sharing/MarkerSpatialCoordinateService.cs

This review contains the following logic:
1) calculated camera intrinsics/extrinsics serialization is moved within their class
2) An argument name that was a bit unclear has been renamed in ICalibrationData
3) A new class implementing ICalibrationData is added for applying camera intrinsics/extrinsics obtained through the new spectator view calibration process.

Add class for reading new calibration data

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/TeleportHotSpot.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs

Updates the teleport hotspot (input) and pointer (teleport) sdk components to obtain the teleport system instance from the static registry class.
Builds upon #4099 and is related to #3545.

update teleport sdk components to use the service registry

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoConfigurationProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/CustomProfiles/HandInteractionAllExampleMixedRealityToolkitConfigurationProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Dictation/Dictation.MixedRealityToolkitConfigurationProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityToolkitConfigurationProfile.asset

The following profiles didn't have their CameraSystemType set:
- EyeTrackingDemoConfigurationProfile
- HandInteractionAllExampleMixedRealityToolkitConfigurationProfile
- Dictation.MixedRealityToolkitConfigurationProfile.asset
- Speech.MixedRealityToolkitConfigurationProfile.asset

Sets CameraSystemType on non-default config profiles

---

Assets/MixedRealityToolkit.Services/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityPreferences.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityEyeTrackingProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityHandTrackingProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityMouseInputProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpatialAwarenessMeshObserverProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpatialAwarenessSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs

Makes the look of headers in profiles more consistent and adds some functions to encourage more consistency in the future.
- Adds a `RenderTitleDescriptionAndLogo` function to MixedRealityInspectorUtility. This handles the business of drawing a title and helpbox with consistent spacing etc.
- When an instance of the MRTK isn't found, profile inspectors now provide a button that will add one to your scene.
- Most profiles will now render their contents even if a MixedRealityToolkit instance isn't found. The only exceptions are profiles that require calls to MixedRealityToolkit.Instance to function. In a future PR it would be nice if these could be made to at least render partial contents. Will open an issue for this later.
- Fixes: #3876

Config Profile Homogenization

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointerVisual.cs

In a scenario where we had an object with a BoundingBox that triggers its own destruction once its scale gets sufficiently large, the SpherePointerVisual doesn't properly identify that the object it is grabbing has been destroyed and spams this error every frame in Release (and shows as a warning about referencing a destroyed object in the Editor):
NullReferenceException: Object reference not set to an instance of an object.
at UnityEngine.GameObject.GetComponentFastPath (System.Type type, System.IntPtr oneFurtherThanResultValue) [0x00000] in <00000000000000000000000000000000>:0 
at UnityEngine.GameObject.GetComponent[T] () [0x00000] in <00000000000000000000000000000000>:0 
at Microsoft.MixedReality.Toolkit.Input.SpherePointerVisual.Update () [0x00000] in …

Fixing a bug where NullReferenceException occurs every frame if grabbed object is destroyed

---

Assets/MixedRealityToolkit/Definitions/Utilities/MixedRealityPose.cs

According to https://answers.unity.com/questions/288338/how-do-i-compare-quaternions.html
== compares two Quaternions via Dot product, suffering from floating point precision, while
Equals compares binary wise (floats)
- Fixes: #4304

From Dot comparison to binary float comparison

---

Assets/MixedRealityToolkit/Definitions/Physics/RayStep.cs

The default keyword isn't available in the .NET language version that the .NET backend supports.

Fix broken .NET build

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/BaseObjectCollection.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs

Fixing object collection to record changes to transform of children. Also making default orient type None since Face Origin is generally awkward for Plane grid default
- Fixes: #4272 Update collection on a Grid object in a prefab does not save changes.
- Fixes: #4231 GridObjectCollection should support undo
Tested GridObjectCollection with capsules children, update collection, then cntrl+z
Tested modifying update collection inside prefab, and seeing results updated when exiting prefab
Unity 2018.3.14f1

Adding undo support to ObjectCollection.UpdateCollection

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

We're making use of bounding boxes to manipulate dynamic content. Part of this involves dynamically querying the size characteristics of the content and deciding at runtime what the minimum and maximum scale factors should be. Another part of this scenario is detecting when the minimum/maximum are reached to display information to the user.
Exposing these values and the means to update them at runtime (and recalculate the cached parameters based on them) allows completion of this scenario. This also exposes the ability to have more precise control of scaling by setting it in either absolute or relative (default) terms.
partially Fixes:#3950

Expose ability to get and set scaling limits on bounding box at runtime

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs.meta

Fixes: #4183 by loading the default interactable states if Interactable.States is null on Awake(). This can happen when Interactable is instantiated at runtime.
Verified by running repro steps at #4183 and seeing that Interactable is correctly instantiated.

Fix NullRef when Interactable created at runtime

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/SpeechInputHandler.cs

It seems that event data is supposed to be marked as "used" by handlers, so it doesn't bubble up further. The SpeechInputHandler is not doing this and so gets invoked twice for the same speech event, when it is both a global and focused listener.
- Fixes: #4368

Mark the speech event data as "used" to prevent double invocation of the handler.

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs
Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Removes the [ExecuteAlways] attribute from MixedRealityToolkit instance to prevent it from being destroyed on entering play mode in editor. This was causing some services like camera and input simulation to not function.
Fixes #4392
Follow-up fix for #4381

Removes ExecuteAlways from MixedRealityToolkit

---

Assets/MixedRealityToolkit.Generated/CustomProfiles.meta

It looks like with this change, https://github.com/microsoft/MixedRealityToolkit-Unity/commit/3f99837d23465857ecd533bc46903a443f3b4dce#diff-0839b16787c3c63d682e567be8e56a92 this file was added unintentionally (probably some leftover file during profile testing)

Clean up a dead meta file.

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySpeechCommandsProfile.asset

This was causing 'Select' speech comands being ignored when filtering using the 'Select' input action.
Fixes: #4419  .

Updated outdated description and axis constraint for 'Select' input action in default speech commands profile

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/CompositionManager.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/HolographicCameraNetworkManager.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CompositorWindow.cs

This change adds one more line of status information to the Compositor window so that you can easily tell whether or not calibration data was received and loaded from the connected camera rig.

Add calibration status message to the Compositor window

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs
Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4261
Starting and stopping play mode can be excruciatingly slow because of the time spent waiting for the dictation and speech providers to shut down. These are ultimately due to slowdowns in the Unity wrapped APIs themselves (and ultimately the UWP APIs)
Note that the "dispose" function on these services isn't a standard monobehavior function - it's specially invoked by the finalizer of the BaseService - this happens off of the main Unity thread.
Please fetch this change locally by running:
> git fetch origin pull/4439/head:verifyslowdownpr
> git checkout verifyslowdownpr

Move the disposal of the dictation and speech providers off the main Unity thread.

---

Assets/MixedRealityToolkit.Extensions/Sharing/SpatialAlignment/Common/SpatialCoordinateServiceBase.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scenes/StateSynchronization.unity
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/MarkerDetectorCoordinateService.cs

1) The state synchronization demo scene was missing some serialized fields.
2) After completing detection, you can could get into a state where the marker spatial coordinate service states its no longer tracking. This throws an exception if a spatial coordinate is reported at the same time.

Fix spatial coordinate scene and remove some exceptions

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs

There's an underlying Unity bug where calling InteractionManager:GetCurrentReading when there are no sources trips this asssertion. This change addresses a couple of things:
1) Works around this underlying bug by checking to see if numSourceStates == 0 (if so, don't bother calling that API)
2) As a related but not totally related change, making it so that we now support cases where the number of states is > the value of 20. Note that I didn't change the naming of it because the value is public (and thus, it would be a value-less breaking change).  When we detect that our array size is not large enough, we will re-allocate (and in a way that should reduce the number of repeat allocations if the numbers are fluctuating a lot).
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/428 …

Exception raised in call to InteractionManager.GetCurrentReading()

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs
Assets/MixedRealityToolkit/Interfaces/Devices/IMixedRealityHandVisualizer.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4268
It turns out that the hand pan interaction script was directly calling into the hand visualization code in order to get joint locations, instead of just calling the hand APIs themselves (which have the exact same data). As I understand, historically the only way of getting this information was through the visualization class. It's been a while that this hasn't been the case, so now it's good to just go straight to the joint data.

Turning off "Enable Hand Joint Visualization" turns off hand input in Editor

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/CompositionManager.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Compositor/HolographicCameraNetworkManager.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CalibrationTestWindow.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CalibrationTestWindow.cs.meta
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CompositorWindow.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CompositorWindowBase.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CompositorWindowBase.cs.meta
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/Microsoft.MixedReality.Toolkit.Extensions.Experimental.SpectatorView.Editor.asmdef
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/HolographicCamera/HolographicCameraOriginAnchor.cs

This PR adds a new window called Calibration Test for testing out a calibration file.  There are two steps to testing:
1. Recording a test video.  This process connects to the holographic camera rig and captures video frames with the pose that the HMD was at for that frame. The video should include the ArUco marker used to establish an origin for the camera tracking.  The camera rig does not need to be calibrated yet during this process, as only the video input and HMD pose are recorded
2. Playing back a test video.  This process loads a calibration file and the recording from step 1 and renders a cube placed on top of the ArUco marker.  This can be used to judge the quality of the calibration file. If the quality is great, the cube should appear to sit on top of the ArUco marker.

Add a Calibration Test window for recording and testing Spectator View calibration files

---

Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHandDataProvider.cs

Simulated hands would not show when toggling persistent hands as the first action (T/Y keys) before first moving them (shift/space). They are now initialized in both cases where tracking starts, either when simulating hands or when just toggling them on.
- Fixes: #4365 .

Make sure sim hands are initialized when starting in persistent mode.

---

Assets/MixedRealityToolkit/Definitions/Utilities/ArticulatedHandPose.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs

Articulated hand pose data loading from json files depends on finding paths in the InputSimulation folder. This was using a hardcoded relative path that can easily be broken by installing MRTK into a non-conventional directory.
The fix involves using the MixedRealityToolkitFiles utility class that registers the MRTK directory and provides convenient path construction. However, the utility was only registering the core MixedRealityToolkit path, so it has to be extended to track all the major modules in MRTK.
- Fixes: #4448

Extend the Files utility to support non-core modules and loading.

---

Assets/MixedRealityToolkit/Services/BaseDataProvider.cs
Assets/MixedRealityToolkit/Services/BaseExtensionService.cs

A `ConfigurationProfile` is [already defined in `BaseService`](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/Assets/MixedRealityToolkit/Services/BaseService.cs#L24), leading to the above warning.

Remove extra configuration profile references

---

Assets/MixedRealityToolkit.SDK/Features/UX/Materials/BoundingBox.mat
Assets/MixedRealityToolkit.SDK/Features/UX/Materials/BoundingBoxGrabbed.mat

Visual fit & finish: material updates for the wire color, glow, and thickness.
Part of #4200 [MRTK Shell Parity] UX Controls Parity with HoloLens 2 Shell
- Fixes: #4416

[MRTK Shell Parity] [Bounding Box] Visual fit & finish

---

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/GazePointerVisibilityStateMachine.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/GazePointerStateMachineTests.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4431
In a previous change (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4270) a gaze provider state machine was added to bring the head gaze pointer behavior in-line with how the shell works. This had the side effect of also impacting eye-gaze state. This change brings the old eye-gaze behavior back by updating the state machine to be aware of the type of gaze being provided.
Also added a bunch of tests for this new thing, along with tests that show that transitions between the two (for example, when the eye tracking system gains tracking or loses tracking) works well.

Eye targeting is not working with near hand pointers

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/CompositorWindow.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/EditorWindowBase.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/FullScreenCompositorWindow.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Editor/FullScreenCompositorWindow.cs.meta

This change adds a "Fullscreen" button to the Compositor window that shows a second window with just the composition preview (and none of the other UI).  This is useful for live demonstrations, where you want to show a large preview of the composition on a second monitor without hooking up the capture card output to that monitor. The button lives in the Composite second of the UI, next to the display texture choice, and honors the choice of display texture you choose.

Add a compositor preview window that can be maximized to take up most of a monitor

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs

Modification to allow spatial mapping to work with teleport and camera control via the MixedRealityPlayspace.
Rather than having a WorldAnchor directly control the spatial mesh's transform, read the WorldAnchor's transform and concatenate with the playspace transform to get the mesh's transform.
- Fixes: #4276  .
>
>

Fix spatial mapping to work with teleport and camera control.

---

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Assets/MixedRealityToolkit.Services/InputSystem/GazePointerVisibilityStateMachine.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/GazePointerStateMachineTests.cs

Fixes: #4510 while maintaining ability to show cursor when articulated hands are used in GGV mode.
Also add unit tests to cover HoloLens 1 and articulated hands in GGV.

Fix cursor not displaying on HoloLens 1

---

pipelines/ci-release.yml
pipelines/ci.yaml
pipelines/pr.yaml
pipelines/templates/common.yml
pipelines/templates/tasks/unitybuild.yml

#3656
The folder destination of the appx package and its naming are also different when building C# projects, so instead of being in the build/AppPackages/MixedRealityToolkit folder, it's actually in the build/MixedRealityToolkit/AppPackages. And instead of the name MixedRealityToolkit_2.0.0.0_Win32_Master_Test, it's MixedRealityToolkit_2.0.0.0_x86_Master_Test. This will need to be a followup YAML pipeline switch on scripting backend.
Note that this change makes it run in CI and PR, which will increase times. Depending on duration we might look to split this step out into its own check (so that we can parallelize across machines). Note that simply replacing one of the other ones I'm not certain will work, because we depend on those existing pipelines to generate assemblies which get …

Enable .NET scripting backend support in CI, part 2/2

---

Assets/MixedRealityToolkit.Extensions/Sharing/SpatialAlignment/Common/ISpatialCoordinate.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/MarkerVisualizerSpatialLocalizer.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpatialCoordinateSystemManager.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpatialCoordinateSystemMember.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpatialLocalizer.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpatialLocalizerBase.cs

1) We start handing around the command associated with a binary reader so that different commands can be interpretted.
2) We add richer documentation on how ISpatialCoordinate transforms should be used.

Prepare networking logic to support multiple headers.

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/SpectatorViewPluginArUcoMarkerDetector.cs

This change reduces the threshold for accepting/rejecting markers, which allows detection to succeed in more cases without significantly affecting the quality of the successfully-detected markers.

Relax the thresholds on the ArUco marker detection

---

Assets/MixedRealityToolkit.Services/BoundarySystem/MixedRealityBoundarySystem.cs
Assets/MixedRealityToolkit/Definitions/BoundarySystem/InscribedRectangle.cs

In some cases, `UnityBoundary.TryGetGeometry` returns true but returns an empty list of boundary points.
In this case, we shouldn't try to create an inscribed rectangle.
- Fixes: #4541

Fix potential infinite loop caused by InscribedRectangle

---

Documentation/Input/InputEvents.md

Feedback from Berlin 
This is a common issue with new devs, so may be a good idea to say it more prominently

Added to doc: Input event handlers need to be registered to receive events. 

---

pipelines/templates/common.yml

This step is only creating .unitypackages now. This is no longer necessary for all of our builds. We may need this again for our internal packaging/signing pipeline, but until then we are removing this step.
This will fix an error we are currently seeing on CI.

Removing build.ps1 step from our pipelines

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoScrollPanZoom/Scripts/BaseClasses/PanZoomBase.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DictationHandler.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/MousePointer.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/ControllerFinder.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs
Assets/MixedRealityToolkit.Services/InputSimulation/Editor/InputSimulationService.cs
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/TestFixture_03_InputSystemTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs
Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityEyeGazeDataProvider.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityMouseDeviceManager.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityMouseDeviceManager.cs.meta
Assets/MixedRealityToolkit/Interfaces/Services/IMixedRealityDataProviderAccess.cs
Assets/MixedRealityToolkit/Interfaces/Services/IMixedRealityDataProviderAccess.cs.meta
Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs

This is an RC 2 targetted version of #4466. The previous PR got updated to newer dev branch code prematurely, hence it being recreated.
Below is the original PR description:
This change introduces IMixedRealityDataProviderAccess, which allows system implementations a standard contract through which they can allow components access to data provider instances.
As an example, the solver handler now accesses the hand joint service using the following pattern
handJointService = (InputSystem as IMixedRealityDataProviderAccess)?.GetDataProvider<IMixedRealityHandJointService>()
This change also adds IMixedRealityMouseDeviceManager to allow for easy recognition of mouse data providers.
To ensure consistency across services with data providers, the spatial awareness system's GetObserver* methods …

Add IMixedRealityDataProviderAccess and update how data providers are retrieved

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs

- we're storing an offset to the parent now instead of the world space position, so we can apply that offset to an up-to-date world space position of the button
- also added proper reset of the moveable button part on disabling of the button
- Fixes: #4600  .

fixed moveable button visuals position update while button is moving

---

Assets/MixedRealityToolkit.Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxTest.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MixedRealityToolkit/Extensions/BoundsExtensions.cs

- Fixes: #4151
- Add test to BoundingBox test scene to repro the issue and verify the fix
- Expose method BoundingBox.UpdateRig() developers can use to force the bounding box rig to update.
> commands
>
> git fetch origin pull/4592/head:name_of_local_branch
>

BoundingBox Fix rig when parent of has non uniform scale

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

In the HandInteractionExamples scene, slates had the wrong size for the bounding box scaling handles.
Updated the scene with proper scale values in the inspector. 
- Fixes: #4608

[RC2 Stabilization] Wrong scale handle size - HandInteractionExamples scene

---

Assets/MixedRealityToolkit.Examples/Demos/UX/PressableButton/Scenes/PressableButtonExample.unity
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Interactable inspector accesses the MRTK.Instance.ActiveProfile to find available input actions. Currently, MRTK.Instance will return null until the MRTK gameobject has actually been selected by the user.
Therefore, you will get an error when trying to edit an inspector until you click MRTK gameObject.
Fix this by changing the .Instance accessor to actually search for an instance if one is not found.
Fixes: #4610 
- Verified that I don't get errors when inspecting interactable
- PlayMode Tests
- EditMode Tests

Fix "MRTK not found" errors even when MRTK is present in scene

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/Slate.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4167
Slates use the bounding box's rotate colliders in order to handle rotation - note that even though the slate provides its own box-like prefab, the bounding box still creates a sphere collider (which has wayyyyy more vertices than the simple box), even though a basic box would suffice. This change addresses the issue by adding an option to either use a box or sphere collider when a custom prefab is provided for bounding box rotate handles.
This is done in this way to avoid being a breaking behavior change - other folks can choose to use a more performant collider, and the slate is the only thing updated to use this behavior for now.
For the prefab, all I did was update the dropdown select button to choose "box" - everything …

Slate prefab box collider performance issue

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/Slate.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

We're currently trying to merge some changes that went into the stabilization branch back into the mrtk_development branch.
Unfortunately, there's a conflict that was caused by the meeting of two changes:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4514
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4461
I'm reverting my change that I made, and will be re-applying it after the stabilization->development branch merge. My change was just caused by re-serialization of the prefab after I changed a single property on the prefab (i.e. changing the handle setting to 'box'). This is easy enough to do in Unity through the UI, and really hard to do manually merging on Github.

Revert "Slate prefab box collider performance issue"

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4485
If you're building the UWP AppX from the build window for the very first time (without having built the Unity project before) this error shows up because the current platform isn't being properly propagated to the second step (i.e. the actual building of the AppX). If it's already been built (which is the case once you've started using your project for a while) you won't hit this codepath.
It's a pretty annoying thing to see as a first time user (i.e. I would expect it to work) so making sure that the right data (platform) is getting piped through is the right thing to do!

Can't build UWP APPX from MRTK Build Window in Unity

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

Warning message 'FollowMeToggle.visualizationObject' is never assigned to, and will always have its default value null
Explicitly assigned null
- Fixes: #4613

Bug fix: warning message on FollowMeToggle.cs

---

pipelines/ci-release.yml
pipelines/ci.yaml
pipelines/templates/package.yml
pipelines/templates/publishpackages.yml

mrtk_CI pipeline is failing due to missing signing task - it appears that it is not enough to disable a task that doesn't exist (in the context of AIPMR project) as perhaps some validation happens before the template is fully evaluated. This change attempts to remove the signing task from the ci.yml template (only left in ci-release.yml).

Move package signing into separate template

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity.meta
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/HandInteractionTouchRotate.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MixedRealityToolkit.Services/InputSystem/BaseNearInteractionTouchable.cs
Assets/MixedRealityToolkit.Services/InputSystem/BaseNearInteractionTouchable.cs.meta
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchable.cs
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableUnboundedPlane.cs
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableUnboundedPlane.cs.meta
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableVolume.cs
Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableVolume.cs.meta

Changes NearInteractionTouchable.TouchableSurface to allow for quads or boxes. Quads use the old logic for DistanceToSurface. Boxes use shortest distance to a cuboid in space for DistanceToSurface.
This change may be breaking, as the TouchableSurface enum has changed, meaning that the value that was previously UnityUI is now Box. The UI will still function, but the distance to surface may be strange at the edges. There is a helper in the inspector that will amend this.

Touch NearInteractionTouchable volumes from the side

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics/Utilities.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics/Utilities/InterpolationUtilitiesTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics/Utilities/InterpolationUtilitiesTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics/Utilities/InterpolatorTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Physics/Utilities/InterpolatorTests.cs.meta
Assets/MixedRealityToolkit/Utilities/Physics/InterpolationUtilities.cs
Assets/MixedRealityToolkit/Utilities/Physics/InterpolationUtilities.cs.meta
Assets/MixedRealityToolkit/Utilities/Physics/Interpolator.cs
Assets/MixedRealityToolkit/Utilities/Physics/Interpolator.cs.meta

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4191
The previous linked change got rid of some code that wasn't referenced anywhere in the MRTK and had no documentation - along with the private->public payload that came back in March, there was a significant portion of dead code that was introduced and this got cleaned up with it. Based on some feedback from customers, they were in fact using these utilities, so we're adding them back with tests to show how things should expect to work.
I'd love to have more coverage on Interpolator.cs, but this would require some minor refactoring (non breaking changes) in order to actually unit test those things (in particular, we'd need to abstract away the usage of time in order to properly test the script)

Reintroduce the Interpolator utilities back to the MRTK

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableColorTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/ScaleOffsetColorTheme.cs
Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/ThemeInspector.cs

The InteractableColorTheme will color meshRenderers, as well as Text objects. Previously it only set the color fields of UI Text and TextMesh objects.
- Fixes: #4551 .
- Different Text objects will be effected by color changes from the InteractableColorTheme and ScaleOffsetColorTheme.
- Renderers are the fall back option.
- Theme does not show shader property drop down when the target is a text base object.
- Only does the check for each text object once, then will use a delegate to apply colors is a text object exists.

Added TextMeshPro support to the InteractableColorTheme

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/ServiceFacadeInspector.cs
Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Assets/MixedRealityToolkit/Utilities/Editor/MixedRealityEditorUtility.cs

Profile inspectors now check whether an active service has a DocLink attribute. If one is found, a documentation link is drawn on the profile.
Fixes #4670

Adds Documentation link to profile inspectors

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/Solvers/HandConstraint.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
Assets/MixedRealityToolkit/Attributes/ExperimentalAttribute.cs
Assets/MixedRealityToolkit/Attributes/ExperimentalAttribute.cs.meta
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/ExperimentalDrawer.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/ExperimentalDrawer.cs.meta

Looks like I committed, but failed to push my last change to: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4532 The final change was the addition of an "Experimental" attribute to tag experimental features with.

Re-targeting Experimental Property for Stabilization

---

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/Rotator.cs
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/PointerResult/SpawnOnPointerEvent.cs
Assets/MixedRealityToolkit.Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxTest.cs

The addition of this test caused an issue building NuGet packages, because this test was added without a namespace. The asset retargetting step (which is a precursor to building nuget packages) assumes that every single class belongs to the non-global namespace (actually, the MRTK main namespace).
Other followups associated with this issue:
1) Probably some linter that checks that all .cs files actually have a namespace declared.
2) Probably treating warnings from the nuget step/asset retargetting step as error (so that it fails the CI build)

Add missing namespaces to resolve the lack of NuGet packages building.

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit/Definitions/Utilities/SupportedPlatforms.cs
Assets/MixedRealityToolkit/Utilities/PlatformUtility.cs

Add iOS, Web and Lumin to the SupportedPlatform enums. This will allow future platform extensions to be created for these without needing to recompile the core assemblies.
This is related to the work by @Alexees (#4358) that has been moved to being under consideration for the next major MRTK release.
Also added Mac and Linux editor platforms to address #4601.

add additional supportedplatform enum values for future / expansion use

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs

distFront is now per BaseNearInteractionTouchable. As such, we need to check distFront for each BaseNearInteractionTouchable.
- Fixes: #4699.

Add check to assure that closestProximityTouchable is at least distFront away

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/States/States.cs

States.cs was using `new` to create an instance of a `ScriptableObject` instead of `CreateInstance`.
I'm not fully sure how I got into this state, since the `GetDefaultInteractableStates` method appears to only be called if you don't have a state specified in the Inspector, but the Inspector seems to try to make sure the default asset is always loaded in. Deleting the default asset is a good way to repro this issue.
Note: this is currently targeting mrtk_development. Feel free to retarget to stabilization if we want to take this there (my branch is based on stabilization, so it won't be bringing over anything extra from dev), but I don't see this as blocking RC2.
- Fixes: #4705 
1. Ensure that this call still creates `States` and uses it correctly

Update States.cs to use CreateInstance instead of new

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs

The current implementation of the DisplayOption setter in WindowsMixedRealitySpatialMeshObserver checks to see if the value being set is _not_ the same as the current value. Only then will it perform any operations (including updating the material on existing meshes).
Because of this, code that changes a material (ec: VisibleMaterial) must set DisplayOption twice.
```
observer.VisibleMaterial = newMaterial;
observer.DisplayOption = SpatialAwarenessMeshDisplayOptions.None;
observer.DisplayOption = SpatialAwarenessMeshDisplayOptions.Visible;
```
This change removes the previous value check and _always_ performs processing when DisplayOption is set. This allows for a more natural calling pattern without the need for knowing the quirks of this observer.
```
observer.VisibleMaterial = …
```

Remove need for repeated calls to DisplayOption in WindowsMixedRealitySpatialMeshObserver

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/TestCanvas.prefab

and resized caption to fit the scrollable box
Fixes unity ui example in HandInteractionExample scene that would render the tmp section only in one eye on WMR , Hl1, Hl2
(also fixes overlapping text with dropdown)

replaced unity ui textmeshpro example materials with mrtk segoeui SDF material

---

Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs

When #4593 was merged, the spatial awareness system was updated to implement the IMixedRealityDataProviderAccess interface. With one notable exception....
It was never tagged as implementing the interface. 
All code paths that were added were validated by being used by the now deprecated GetIObserver and GetObservers methods. The only thing missing was the interface in the class definition.
This change adds IMixedRealityDataProviderAccess to MixedRealitySpatialAwarenssSystem.

add missing interface declaration to spatial awareness

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-04-TargetPositioning.unity

The text says "here" but the actual keyword is "over here" - this is super confusing for folks using it, and it's not clear without some unnecessarily deep debugging.
Basically if you say "here" nothing happens - you have to say "over here" so we may as well document that you have to say "over here"

Update the eye tracking scene sample to have the correct verbal keyword.

---

Documentation/InputSimulation/InputSimulationService.md

Another point of feedback from partners who hit this (i.e. if you set the holographic emulation setting to "Simulate in Editor", the MRTK's input simulation won't work because Unity will take over the camera and input)
We're following up with Unity to see if we can get an API to know what the current emulation setting is (such that if unity's Simulate in Editor is set, we could show a dialog showing a warning saying that MRTK's simulation will be turned off)

Update the input simulation docs to mention issues with Unity's built in editor simulation

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/CustomProfiles/HandInteractionRecordArticulatedHandPoseMixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Dictation/Dictation.MixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Profiles/Interactable_MixedRealityInputSystemProfile.asset
Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2InputSystemProfile.asset
Assets/MixedRealityToolkit.Services/InputSimulation/Editor/InputSimulationService.cs

Following up on #4691, a few input system profiles needed to be updated. Additionally, I marked the service itself as cross-editor-platform via the system attribute.
- Additional support for #4601

Update other inputsystemprofiles and mark simulation service as cross-editor-platform

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

- Fixes: #4702
hand held MR Controllers and GGV now scrolls slate control

Fix: Slate scroll with hand not working with GGV on Hololens 1 and Motion Controllers in VR #4702

---

Assets/MixedRealityToolkit.Examples/Demos/Diagnostics/Scenes/DiagnosticsDemo.unity

#4708 removed a script from the project and removed the need for the diagnostics demo to contain a SpeechInputHandler.
However, I forgot to remove the references to these scripts from the demo scene. This change fixes the issue.

Remove unused scripts from the diagnostics demo scene

---

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityFocusProvider.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Focus provider is considered a core system by the MixedRealityToolkit object. As such, it should implement IMixedRealitySystem, derive from BaseCoreSystem and be registered in the MixedRealityServiceRegistry.
This change correctly classifies and registers IMixedRealityFocusProvider instances.
Tested via the solvers scene on OpenVR and Windows Mixed Reality Immersive devices. Teleportation and object selection were the primary focus of interaction testing.

Consistency: make FocusProvider a core service and not a data provider

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs

While working on an experimental standalone teleport service, it was discovered that there were hard coded references to the MixedRealityToolkit object that was blocking the standalone service.
This change updates how the teleport pointer behaves and has been tested in the following configurations:
* MRTK input and teleport enabled
* MRTK input enabled and teleport disabled
* MRTK input enebled, teleport enabled with standalone teleport service prototype
Each of the above configurations behaved as expected (teleport supported, not supported and supported, respectively).
This change is needed to ensure support for a standalone teleportation service is possible without requiring a new version of the mrtk core assembly.

Fix teleport pointer to support mrtk object or standalone service

---

Documentation/MixedRealityConfigurationGuide.md

Removed leading slash from scene system overview link.
- Fixes: #4802
@keveleigh Can you verify that this fixes the issue?

Fix Scene System Overview link in Mixed Reality Configuration Guide

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs

- added handling for cached ghost controllers that unity's interactionManager sends our way on consecutive editor sessions with different controller setup
- removed existing workaround that breaks controller representations for connected controllers until start button is pressed
- Fixes: #4748 , #3638 
- start editor session with controllers connected
- observe visible controller representations
- stop editor simulation
- disconnect WMR controllers by pressing the start button for a long time
- start editor simulation again
- observe no controller representation
- stop simulation
- turn on controllers
- start simulation
- observe visible representation
- try to switch on/off controllers several times during simulation

added handling of lost interaction sources that didn't raise an interactionSourceLost event

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputModule.cs

Add support for drag interactions in Unity UI for HoloLens 1 GGV interactions. This is done by using the pointer position instead of the pointer ray origin in cases when the pointer ray is decoupled from the actual pointer, like with hands (pointer ray is the head, but pointer position is hands).
- Fixes: #4750 
All tests done in editor, not on device.
- Tested articulated hands
- Tested gesture hands

[RC2] Add ability to scroll, drag UnityUI canvas on HoloLens 1

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityTextMeshProShaderGUI.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityTextMeshProShaderGUI.cs.meta
Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkit.Core.Inspectors.asmdef
Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitShaderGUIUtilities.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitShaderGUIUtilities.cs.meta
Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityTextMeshPro.shader

When enabling depth buffer sharing the stabilization of renderables greatly diminishes when a user looks at a renderable that has a material which does not write to the depth buffer. This has been a common pain point for HoloLens 2 users which don't understand why their holograms look distorted or unstable.
This pull request introduces a warning and "Fix Now" button on materials which are in a project that has depth buffer sharing enabled and do not write depth.
On the MRTK/Standard shader:
On the MRTK/Text Mesh Pro shader:
If the "Fix Now" button will spawn a dialog confirming the user wants to change the material to write to the depth buffer.
Other changes include:
-  Moving the "Albedo Assigned At Runtime" option up the inspector for better visibility.
-  Bug fix, allowing the alpha …

Depth Buffer Sharing Material Warning

---

Assets/MixedRealityToolkit/Providers/Hands/BaseHandVisualizer.cs

Don't create a mesh object in the hand visualizer for the "None" joint. The position of that joint is quite arbitrary and creates a distracting floating cube.
- Fixes: #4534 .

Don't create a rendered object for the None hand joint.

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/StateSynchronization/ComponentBroadcasterDefinition.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/StateSynchronization/ComponentBroadcasterService.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/StateSynchronization/GameObjectHierarchyBroadcaster.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/StateSynchronization/StateSynchronizationSceneManager.cs

These types need to be public for Guides (or any 3rd party) to provide custom component broadcasters.  ComponentBroadcasterDefinition and StateSynchronizationSceneManager are necessary to register the custom broadcaster service.  GameObjectHierarchyBroadcaster is necessary to attach this MonoBehaviour to the hierarchies that Guides wants to sync.

Make types needed for Guides to add custom component broadcasters outside the SpectatorView assembly

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityCameraProfile.asset
Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2CameraProfile.asset
Assets/MixedRealityToolkit.Services/CameraSystem/MixedRealityCameraSystem.cs
Assets/MixedRealityToolkit/Definitions/MixedRealityCameraProfile.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs

This changes adds the far clip plane property for both the opaque and transparent system in the camera profile. This is important for MRTK developers to set different far clip plane values for opaque vs transparent. Default in Unity is 1000m which for Hololens is well outside the typical rendering/user volume. However, this large value (1000m) for the far clip plane reduces depth fidelity, especially for 16-bit. 
This change also updates the default camera profiles to set Transparent far to 50m and Opaque far to 1000m. 
- Fixes: #4783 
Far clip plane not settable in MRTK profiles 
Tested profiles actually setting correct values on Camera in Unity editor
Tested camera profiles without serialized far field in text file. MRTK takes default set in the script. 
Tested far clip plane …

Initial addition of far plane property

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs

Fixes: #4696 by making pointer mediators accessible from code. Also allows `DefaultPointerMediator` to be extended by making methods virtual and fields protected.
This enables users to crate solutions like turn off the far hand beams at runtime as described in [this stackoverflow post](https://stackoverflow.com/questions/56248329/how-to-turn-off-motion-controller-pointer-mediator)

Pointer Mediators accessible from code and extensible

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs

ManipulationHandler used to default one hand interactions to move without taking into account the "TwoHandOnly" mode. 
Added an early out for no hand and (one hand in TwoHandsOnly mode) in the ManipulationHandlers state switch
- Fixes: #4629 
- tried all three types of manipulating (OneHandOnly, TwoHandOnly, OneAndTwoHand)
- TwoHandOnly won't perform any manipulation on one hand interaction anymore
other two modes stayed as they used to be:
- OneHand will move objects
- TwoAndOneHand will move objects if one hand is used and perform rotate / scale when both hands are used

changed ManipulationHandler state switch to ignore one hand interactions in twoHandOnly mode

---

Documentation/EyeTracking/EyeTracking_TargetSelection.md

Caused by this change:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4697
This fix only resolves the docs build issue, but doesn't actually fix the docs themselves which are technically out of date with that change.

Fix the docs build caused by previous eye tracking change

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/EyeTrackingTarget.cs

These warnings were introduced in a previous eye tracking PR, tidying them up.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4697

Fix warnings in EyeTrackingTarget

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/EyeTrackingTarget.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4849
I had missed this in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4845

Make EyeTrackingTarget's Start() function match the definition of its base class

---

toc.yml

The Architecture side of the MRTK docs has been pretty sparse for a long time, and there's currently an issue where clicking on the 'Architecture' tab will go to a seemingly random page (spatial awareness). After reading through all of these pages, there's SOME interesting content, but probably 95% of it isn't actually useful for the reader (i.e. many things list random names without giving any relationship between them)
While I work on getting new architecture docs up, we're removing this tab to prevent us from leading people down the wrong path. I'm not deleting the existing MD files themselves, just making them WAY harder to access. I will do the actual cleanup as part of my next docs pass.
- Fixes: #4789

Temporarily remove the "Architecture" tab from the github.io docs

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs

fixes planes going crazy during runtime when there's a transform on the button and a local transform on the moveable button part
when storing the initaloffset the world transform wasn't applied (so basically the local offset was missing the world scale that made the planes shift whenever the moving visuals had an offset applied)
- Fixes: #4870 
used Julias example scene to verify , tested existing buttons in examples

fixed initial offset for pushable button part

---

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs

and adjusted undo messages
PressableButtonHololens2 wasn't exposing any properties in the editor because inspector was only defined for PressableButton class.  Enabled the fallback flag so it's available for all derived types and adjusted the undo msgs that would refer to PressableButton base type.
- Fixes: #4869 
PressableButtonHololens2  is used in PressableButton Example Scene. Now the buttons will show the properties in the editor and also have the planes to adjust distances

enabled pressable button inspector for derived types 

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_02_MixedRealityToolkitFilesTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_02_MixedRealityToolkitFilesTests.cs.meta
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs

The files utility was using a simple "endsWith" string comparison to find resource folders for MRTK. This does not work for the path format used by nuget packages, e.g.:
"MixedRealityToolkit.Services" (Unity package)
vs.
"Microsoft.MixedReality.Toolkit.Services.2.0.0-20190611.2/MRTK" (nuget package)
The fix changes the MixedRealityToolkitFiles utility class to search for both patterns and find the matching module name.
- Fixes: #4827 
* Create a new Unity project
* Install latest NuGet for Unity from here: [https://github.com/GlitchEnzo/NuGetForUnity/releases](https://github.com/GlitchEnzo/NuGetForUnity/releases)
* Add the source URL https://pkgs.dev.azure.com/aipmr/_packaging/MixedRealityToolkit/nuget/v2/ through _Edit > Preferences > NuGet_ for Unity. Uncheck "Read-Only Packaging Files" …

Fix MixedRealityToolkitFiles utility to handle the nuget resource path format

---

Assets/MixedRealityToolkit.Extensions/ScreenRecording/AndroidRecordingService.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/Mobile Recording Service Visual.prefab
Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/Mobile Recording Service Visual.prefab.meta
Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.Android.prefab
Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.HoloLens.prefab
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scenes/SpectatorView.ASA.Android.unity
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/MarkerDetection/ArUco/HoloLens/ArUcoMarkerAnchor.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/SpectatorView.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/UI/MobileOverlayVisual.cs
Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/UI/RecordingServiceVisual.cs

This review adds mobile recording to the android asa spectator view scene.
1) We now can specify to have mobile recording/mobile recording ui via SpectatorView.cs
2) If mobile recording is enabled, SpectatorView will dynamically create a recording ui prefab and a IRecordingService.

Mobile recording for spectator view

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTip.cs

Font size of ToolTip changes ToolTip now without editing the text first. FontSize is available in scripts now. 
- Fixes: #4886

Change font size of ToolTip

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/EyeTrackingTarget.cs

Reverts microsoft/MixedRealityToolkit-Unity#4850

Revert "Make EyeTrackingTarget's Start() function match the definition of its base class"

---

Assets/MixedRealityToolkit/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs

The camera system interface defines it as a data provider (incorrect) while the concrete class derives from BaseCoreSystem (correct).
This inconsistency was preventing the camera system to be correctly registered with the service registry and blocks the future ability to run it as a stand alone service.
This change resolves the consistency issue.

fix definition of camera system interface

---

Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityCameraProfile.asset

DefaultMixedRealityCameraProfile's near clipping distance is 0.85m
This clipping plane creates some confusion for the HoloLens (1st gen) developers since objects are abruptly disappearing from 0.85m distance. There are many apps that require content observation closer than 0.85m (e.g. viewing architectural model). 
Instead of forcing hard/abrupt clipping by the camera, we recommend using MRTK Standard Shader's Near Fade property to gradually fade out the objects in the near distance range. (~0.45m) 
- Fixes: #4905

Updated DefaultMixedRealityCameraProfile from 0.85m to 0.1m

---

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Pointers/GrabPointer.prefab

Addresses good defaults for the `GrabPointer`.
As issue mentions - default radius was set to 15cm. Feedback has been that its much too large. The propose default is 5cm.
- Fixes: #4371 
>
>
> …

Default GrabPointer grab radius

---

Assets/MixedRealityToolkit.SDK/Features/UX/Materials/PinchSliderTickMarkMaterial.mat
Assets/MixedRealityToolkit.SDK/Features/UX/Materials/PinchSliderTickMarkMaterial.mat.meta
Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Sliders/PinchSlider.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

This fixes two minor things in MRTK example components. 
1) BoundingBox does not auto allocate it's UnityEvents. This makes it annoying when using BoundingBox component dynamically and subscribing via code/AddListener() because the developer needs to check if the property is null and if so, do the allocation him/herself. 
2) Pinch slider has multiple tick mark sphere balls that each have their own draw call for rendering. This change creates a material for them and turns on GPU instancing to reduce 13 draw calls to 1. 
- Fixes: #4929 
1) Tested out that is no longer null
2) View change in Frame debugger

MRTK Example quick fixes

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/Billboard.cs

The current implementation does not allow for spawning a billboard in, because the target cannot be set. Most of the solver allow for doing that. This fixes it.

Allow setting the Billboard TargetTransform from code

---

Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader

When rendering the back faces of triangles, the normals are flipped the opposite way which can lead to artifacts in lighting calculations and other techniques which utilize normals. This change flips the normals based on which side of the triangle face is being rendered.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4946
To verify the fix look at lit surfaces with back face culling disabled in the Material Gallery.
>
>
>

Fixing Normal Direction on Back Face Triangles

---

Assets/MixedRealityToolkit/Utilities/Physics/InterpolationUtilities.cs.meta
Assets/MixedRealityToolkit/Utilities/Physics/Interpolator.cs.meta

The two interpolation meta files added in #4677 had some trailing tabs for some reason.
This was causing Unity 2019.3 to regenerate these metas from scratch, including changing their GUIDs.
This PR puts the meta serialization in-line with other metas.

Fix interpolation meta file serialization

---

Documentation/Profiles/Profiles.md

This provides a little history for why the SA system was disabled by default on the HL2 profiles.
#4945

Update the HL2 profile description's SA section

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs

Fixing issue where the whole editor is locked by periodically checking for new appx directories.
#3264
- Removed periodic build checking
- Added a refresh button to check for builds
- Added checking when switching to the deploy tab.

Build window performance fix

---

pipelines/ci-packaging.yml
pipelines/ci-release.yml
pipelines/templates/ci-common.yml
pipelines/templates/package.yml
pipelines/templates/tasks/signing.yml

Implement changes from the NuGet versioning / release planning thread.
- Split mrtk_CI into two templates - CI in AIPMR project will no longer produce NuGet packages. We will set up an internal build that will push CI packages to internal feed in microsoft ADO org. (We can continue publishing packages as before until we communicate the switch internally).
- Release CI in microsoft org (manually triggered) will produce both prerelease and release packages. Pre-release packages will be uploaded to the artifact feed while the release packages will flow through the Release Pipeline after we test the pre-release package and it's ready to be published.
- Signing configuration moved to an internal "build" repo.
PR validation is not necessary as only CI build will be affected. It will need to be …

Pipeline changes for NuGet release process

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

MRTK services are not harden to be reliable enough to be destroyed & recreated at runtime atm. There is work to make this better. This change though does two things
1) Ensure changing tabs in the MRTK inspector is not considered as a profile "change" which will call MRTK to reset configuration. 
2) If in play mode, all profile inspector GUI's are disabled from editing
Number 2 was added because
a) Some MRTK profile changes will cause a reset which will spew errors & problems as in #4944 and #3945
b) Some MRTK profiles changes will not be consumed when changed at runtime. For example, modifying the MRTK near clip plane value in the camera profile will not modify the actual camera near clip plane at runtime. 
Drawback: if a developer wants to make a profile change even though they are aware …

Stop MRTK resets with inspector tab selection & disable MRTK profile inspectors in play mode

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs

There were two changes that went in, that each built successfully on their own, but combined led to a break. Basically, there were these new tests which assumed there were no default listeners of the new RegisterHandler input system event system. However, a checkin also went in that started consuming that by default (this is the primary pointer work). Both changes individually were correct, but together there was a new combination that hadn't existed.

Fix the broken build.

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs

With build window visible and project running, developers notice massive performance drop. Even without play mode, this window is repainting itself more than necessary due to update() method.
This change just removes the excessive repaint
- Fixes: #5003 
Opened window with game mode and noticed perf drop in half. Now fixed
Close & open window fine
Select buttons to switch tabs 
Build worked

Remove update repaint method in build window

---

Documentation/README_Interactable.md
Documentation/README_MRTKStandardShader.md

Adding information on best practices to extend InteractableTheme for setting shader properties. Focusing on
1) MaterialPropertyBlock
2) Using shader integer keys over string keys
Also fixed some inlining errors and added bullet points
- Fixes: #4228 
Related: #4819 
Looked at preview content

Updating Interactable.md for shader theme content

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableColorChildrenTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableShaderTheme.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Themes/InteractableThemeProperty.cs

InteractableTheme classes are able to update shader properties such as color or glow, etc in response to scene interactions such as focus or click. These theme handler classes updates shaders in Unity via string properties. Whenever a property is updated via a string key such as GetFloat(), Unity will automatically call Shader.PropertyToId() to get it's int key and then perform the get or the set. 
This change caches the integer property keys for all property strings in a given theme class so as to help with performance when calling the get/set functions at runtime
- Fixes: #4228 
Optimize Shader property and Material access on Interactable*Theme class
Confirmed HandInteraction scene worked with Interactable classes on changes such as focus or clicks, etc.

Update Interactable property code to utilize shader int keys instead of strings

---

Documentation/HTKToMRTKPortingGuide.md

Billboard class is still needed as RadialView does not satisfy necessary functionality. 
- Fixes: #4843 
>
>
>
>
> git checkout …

Updating porting guide to point to billboard class

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs

Fixed access of parent transform - if there's no parent the initial offset is vector3.zero
- Fixes: #5023

fixed initial offset for buttons that are created in root of prefab

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs

The bug listed in #4857 was caused by a missed check `BaseControllerPointer`:
- Pointer Up/down events were fired without checking `IsInteractionEnabled`
- This caused Pointer Up event to be fired by the GrabPointer, even when it was disabled. The repro in #4857 had a modal dialog that would show when a button B was clicked. The modal would then disappear whenever it saw a click form any pointer. The bug was that after user pressed select on controller, Bwould receive click from line pointer, which would show modal M. Then the grab pointer (from that same select gesture) would fire a second click, which would hide the modal M.
- Fixes: #4857 
- Also remove extra 0.05 m buffer when doing test for is sphere collider near grabbable. This was causing confusing UX feedback where the line …

Don't fire pointer events if IsInteractionEnabled == false

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Utils/EyeCalibrationChecker.cs
Assets/MixedRealityToolkit.Examples/Demos/Utilities/Scripts/MixedRealityCapabilityDemo.cs
Assets/MixedRealityToolkit/Definitions/SceneSystem/MixedRealitySceneSystemProfile.cs

The current state of mrtk_development had a few build warnings.
EyeCalibrationChecker: Changed from `#if UNITY_EDITOR` to `if (Application.isEditor)`, since the code itself is outside the `UnityEditor` namespace and will build for device.
MixedRealityCapabilityDemo: The `Start` method was incorrectly marked as asynchronous.
MixedRealitySceneSystemProfile: Some public properties were marked as `#if UNITY_EDITOR`. I removed these, so the corresponding serialized fields were referenced elsewhere. I wasn't sure the original intent in keeping these `#if`ed out, @railboy?

Fix build warnings

---

Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/Observers/IMixedRealitySpatialAwarenessObserver.cs

#5035 had some todo comments where the documentation comments should have been. this change adds the proper text.

fix doc comments in new ClearObservations methods

---

Documentation/UpdatingToGA.md

Adds an api changes section and describes the new changes for clearing spatial observations.
Also fixes some spelling / typing errors in the assembly name section

Add api change section to UpdateRC2toGA doc

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs
Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/ServiceFacadeInspector.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
Assets/MixedRealityToolkit/Utilities/PlatformUtility.cs

MixedRealityToolkitFacadeHandler and ServiceFacadeInspector:
Platform Utility:
MixedRealityEditorSettings:
Note: This doesn't remove all issues with 2019.3, as that version adds a requirement for the `Unity.ugui` package to be added to all our asmdefs (#4545). Unfortunately, that fix is backwards compatible with previous versions of Unity 2019 but causes errors in Unity 2018.
Fixes: #4831

Remove warnings in Unity 2019

---

Assets/MixedRealityToolkit.Services/InputSystem/InputSystemGlobalHandlerListener.cs

Update InputSystemGlobalHandlerListener to try register as a global listener in OnEnable. Previously it was trying to register in Start, causing it to miss some events.
- Fixes: #5029
The `lateInitialize` variable was introduced in the following commit:
```
1c17f7847e1d3a3a8e125b876a9c57ad1fb42a6f
Author: Stephen Hodgson <hodgson.designs@gmail.com>
Date:   Sun Sep 9 14:13:25 2018 -0700
Fixed input handler race condition if input system and teleport system not found before gameobjects wake up
```
So it sounds like there were cases when a component was enabled before input system was valid. However, we do want to register some components in OnEnable to ensure they get all input events. Therefore, modify the code s.t. we try to register both in OnEnable and in Start.
Verified that simulated …

Fix simulated hand ray not correct until hand moves

---

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs

Fix for Issue #4011 
When initializing the Interactable the inspector does a check to see if the States property is not null. If it's null, then we try to fill it with the DefaultInteractableStates asset.
The issue came up when the States property was filled in the layout phase, but never rendered. During the repaint phase, now that the property is not null, we attempt to render the field in the inspector.
We are now rendering the field in both phases, in the layout phase after the property is filled.
I was able to consistently repro this by adding the Interactable component to a GameObject using the Add Component button in the inspector.
1 Create a new Scene
2 Add MRTK by selecting MRTK/Add to Scene and Configure... in the menu
3 Drag a pressable button into the scene
4 press play
5 …

updated InteractableInspector to fix mismatch repaint issue

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerEventsTests.cs

`PlayModeTestUtilities.ShowHand` now steps an extra frame after showing hands, which changes the events the pointer handler receives so we need to adjust the expected values accordingly. Also, simplified interpolation math in `PlayModeTestUtilities.MoveHandFromTo`

Fixed pointer events tests to adapt to changes to PlayModeTestUtilities.ShowHand.

---

Assets/MixedRealityToolkit.Services/InputSystem/Inspectors.meta
Assets/MixedRealityToolkit/Definitions/Utilities/Editor.meta

Importing the current state of the mrtk_development branch, two meta files get deleted because their corresponding folders do not exist anymore.
removes the 2 meta filesw

Removed deleted meta files

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/EventCatcherTestUtilities.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/InputEventSystemTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/NearInteractionTouchableTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerEventsTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/TestHand.cs
Documentation/Contributing/UnitTests.md

This is an oldie but goldie. There's an issue that arises only when building on the .NET backend with C# projects enabled (this is a deprecated scenario but still one that is really useful for fast iteration).
The problem is that even if an assembly is marked as a "test assembly" (as the play mode tests are), they will still be included in player builds for .NET-C# project builds. This is what the old comment was alluding to (but wasn't very specific about)
We also explored doing things like marking the play mode tests as editor only (i.e. matching what the edit mode test asmdef looks like) but this had the side effect of removing all tests from the test runner (bad, tests are gone). Also tried making things editor + Win32 (standalone) + Win64 (standalone) only as well, though this still …

Fix the broken .NET-C# projects build.

---

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerHandlerExample.cs

It's been a few days of us not building NuGet packages - here's what happened.
We hit a CI outage earlier in the week caused by an upstream Azure DevOps issue (a bad nuget push package was pushed out). Our build was broken for a couple of days, during which we still had changes going in (mostly we were judging by green-ness of mrtk_pr, which is identical to CI except it doesn't produce and publish NuGet packages).
The problem is, without coverage on the NuGet building, we didn't know that we broke the nuget packages until the upstream nuget push package got fixed.
The asset retargeter assumes that every single class/object in the MRTK is prefixed by the MRTK namespace. This is a fairly reasonable assumption to make, and it throws when it finds something that violates it (so that we can …

Fix the broken NuGet build.

---

Packages/manifest.json
ProjectSettings/ProjectVersion.txt

Updates the WMR Unity package to 1.0.12 to include HL2 remoting.
Also updates the editor version to 2018.4.2 to support the HL2 remoting window update.
NOTE: Currently, hand joints, hand mesh, and eye tracking are not supported by MRTK over remoting.

Update WMR Unity package to support HL2 remoting

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySceneSystemProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

This change adds MRTK editor preferences to save the view state of certain foldouts. This way when user enters play mode or inspector refreshes, it doesn't repaint to default state. 
Also fixed missing issue for input system that causes MRTK to reset when showing/hiding input foldouts which become considered as "changes"
- Fixes: #4997 
Enter/exit playmode
Drill down into input profile

Add MRTK inspector preferences 

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/SystemKeyboardExample.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5018 broke the standalone build, but we didn't know until roughly today.
Here's what happened.
TouchScreenKeyboard is only documented to be useable on the WSA/iOS/Android build options. It turns out that the "visible" property just doesn't exist on the object when build against Standalone targets. The code will build fine in editor but when you actually try to build the player, it doesn't work.
So to that end, I've wrapped the rest of the code in platform specific wrappers (to target only the places where TouchScreenKeyboard is documented to work)
I only caught this because I was making asset retargeting actually fail the build if it failed:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5103
I'm going to make a …

Fix the broken Standalone build.

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/WorldAnchorManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/WorldAnchorManager.cs.meta

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4509
The WorldAnchorManager provided a convenience wrapper on top of Unity's WorldAnchor/AnchorStore abstractions. This change ports the file mostly as-is into the Experimental namespace, because we haven't yet figured out how best to have end to end tests for this, and because we don't have any documentation yet.
Note that there have been several changes here from the HTK version:
1) Some functions that were protected/virtual have been made private, for the sake of going out with the minimal API surface needed to use the World Anchor Manager. This doesn't mean that we they will be private forever, just that we don't want to create a massive surface and want to extend it as-needed.
2) Removed usage of the Singleton<> template - …

Port the WorldAnchorManager from the HTK to MRTKv2.

---

pipelines/templates/common.yml

The build tasks take largest percentage of time (i.e. 80%) but are also the least likely to be the ones that fail repeatedly (generally people are able to make sure that things build before submitting things for PR). However, tests themselves can be trickier because they have slightly different behaviors in batch mode vs in editor. Right now people have to wait ~30 minutes for the builds to complete (successfully each time) before being able to see tests run again. Instead, what should happen is tests should run first (because this will let people iterate more quickly) and then do the long-running build work after.
Note that we're also going to be updating the docs to show how to run the tests in batch mode (so people can iterate on their own machines instead of spinning up CI tasks), but …

Update the CI pipeline to run tests first, and then do all of the build tasks.

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/LaunchUri.cs
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/LaunchUri.cs.meta

Add a button that launches the Edge browser. This demonstrates that the browser slate can be launched while your application continues running. ~~The web page that is launched contains controls modeled after the Unity GUI controls in the examples, showing a button, checkbox, slider, dropdown, and edit box. This demonstrates the option of integrating with existing web tools or of creating simple form UI using HTML and shows what this kind of interaction would feel like.~~
~~Note that I originally implemented this by calling the UWP LaunchUriAsync API, but later found out that is unnecessary because Unity's Application.OpenURL seems to work just as well.~~
- Fixes: #2934.
~~Note that this references a web page in order to demonstrate using web controls from within a browser. Because I …

launch browser example

---

Documentation/ExperimentalFeatures.md
Documentation/SceneSystem/SceneSystemContentLoading.md
Documentation/SceneSystem/SceneSystemGettingStarted.md
Documentation/SceneSystem/SceneSystemLightingScenes.md
Documentation/SceneSystem/SceneSystemLoadProgress.md
Documentation/SceneSystem/SceneSystemSceneTypes.md

Since the documentation portal pages are generated from mrtk_development branch, it has the pages about the features only available in the development branch. 
Adding a disclaimer block to the feature pages that are not available in the release branch yet.
- Fixes: #4792

[Docs] Adding disclaimer message on development branch features

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Sliders/PinchSlider.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PinchSliderTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PinchSliderTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/TestHand.cs

Adds playmode tests for sliders and a few extra test utilities / cleanups.
- Fixes: #4759 
- Fix bugs causing slider to not be configurable from code
- Add Push/Pop InputSimulationProfile and SetInputSimulationMode to test utilities to allow easier switching between articulated and GGV hands for tests
- Add TestHand.Move()
Note: This change also has a couple of changes to test setup and teardown from Railboy's PR #4723. Hopefully that will go in before this one.
Verified all playmode tests pass.

Tests for Sliders

---

pipelines/templates/common.yml

It turns out that if there's a build error, running play mode tests will hang indefinitely in batch mode (this is because it shows a dialog saying "hey, make sure your stuff builds"). Previously this wasn't an issue because the test step happened after everything else, but now that we moved the test step up to be the first thing, this is now problematic.
Building standalone is the fastest of all of the flavors (because it doesn't have to build an AppX), so we're moving this to the top.

Update the build pipeline to first build standalone, in order to avoid infinitely hanging play mode tests.

---

Documentation/Contributing/BreakingChanges.md
Documentation/toc.yml

As a team we've had a policy around breaking changes, though we haven't really written this down until now. This is a summarization of the current state of our stance on breaking changes (tl;dr it's impossible to avoid in all cases, in many cases it's possible to avoid, in the cases where it's not possible to avoid we have to see if the value the change bring is greater than the pain of adoption)

Add documentation on the current breaking changes policy.

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Removes OnValidate from MixedRealityToolkit and replaces with ExecuteAlways.
ExecuteAlways was always preferred over OnValidate, but wasn't viable at the time because ExecuteAlways causes the instance to be torn down prior to entering playmode. Now that our teardown issues are resolved we can use it again.
- Fixes: #5131
>
>

Fixes build error when a scene with MRTK instance is open in editor

---

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/ControllerFinder.cs

- Fixes: #5144
ControllerFinder is capable of searching controllers on it's own but should also be capable of receiving controller detection events in the case a handedness is requested where there is no controller for yet.
Registering the corresponding events completes the amount of necessary calls.
In other words, the interface implementation was already there, it was just not listening at all

ControllerFinder now registers its interface with the InputSystem

---

pipelines/ci-packaging-internal.yml

We need a duplicate of the pipeline definition for now because it is not possible to re-assign the Agent Pool using the UI. This is temporary until we can shut down the feed in AIPMR.

Create a copy of CI definition using internal agent pool

---

Documentation/Contributing/DevDocGuide.md

It turns out that the syntax for xrefs is super hard and not actually easy to find. However, running docfx locally will generate a convenient map, which takes away the memorization process (you can just Ctrl+F for thing you want to link to)
Adding this nugget of guidance to our dev docs.

Add guidance on how to find valid xrefs to reference.

---

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs

#5167 introduced a regression in accessing the registered speech commands.
This change fixes it by referencing the correct profile in the property.
Fixes #5192
Confirmed issue and verified fix using keyboard shortcuts in editor and stepping through the speech provider startup code in the debugger.

Fix regression caused by #5167

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs

This change adds support for:
- Automatic mesh material updates when OcclusionMaterial || VisibleMaterial properties are modified at runtime. NOTE: The updates _only_ occur when the appropriate DisplayOption is set.
- Updating mesh physics layer at runtime.
Each of the above applies the meshes that have previously been observed. All new meshes will continue to be created using the latest settings (previous behavior)
Fixes #5196

Add customer feedback described in #5196

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs

Physics-based touchables now have a broadphase that limits the number of
touchables that need to be examined for finding the closest one.
Unity UI touchables don't have such a broadphase test, so distances needs
to be checked against the touch distance as well, otherwise any UnityUI
touchable will activate if no other touchable is closer.
- Fixes: #5217

Fix Unity UI touchable "greedy" activation.

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputPlayback.cs
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputRecorder.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos/EyeTracking.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos/EyeTracking/DemoVisualizer.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos/EyeTracking/DemoVisualizer/Scripts.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputRecorderTest.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputRecorderTest.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Microsoft.MixedReality.Toolkit.Tests.EditModeTests.asmdef

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5184
On certain locales, the CSV delimiter isn't the comma, but the semicolon instead.
Previously, we assumed that the delimiter would always be the comma, but this would cause problems in cases like de-DE where numbers are written with commas (instead of decimals) to represent the decimal digits.
So for example, en_US:
123.123, ABCABC, XYZXYZ
Without this change, it would look like this on de_DE
123,123, ABCABC, XYZXYZ
This is obviously totally wrong - now we have four cells, it doesn't make sense!
The solution is to use the real delimiter for the current locale:
123,123; ABCABC; XYZXYZ

Logging of EyeGaze data to csv file is culture-specific

---

Assets/MixedRealityToolkit/Attributes/ReadOnlyAttribute.cs
Documentation/UpdatingToGA.md

A handful of attributes were left outside the MRTK namespace, leading to conflicts with external packages.
- Fixes: #5214

Add namespace to ReadOnlyAttribute

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/SpeechTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/SpeechTests.cs.meta

This change adds a test to toggle the diagnostics system's profiler off using the speech provider. In MRTK v2, the profiler toggle command is associated with the "9" key on the keyboard. This key stroke is used to simulate a user speaking "Toggle Profiler"
Resolves #5216

add playmode test that toggles the profiler using speech kbd shortcuts

---

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

The _Copy & Customize_ button in a default profile now opens a clone window, letting you specify the name / path for the newly cloned profile.
To address #4961, a _Put in original folder_ button has been added next to the _Target Folder_ field. Clicking this sets the path to the original profile's path. This option is also available for cloned sub-profiles.
To keep this process fast / simple by default an _Advanced_ foldout has been added to hide the sometimes visually overwhelming sub-profile options.
- Fixes: #4961, #4959
>
>

Updates Copy & Customize to use Clone Profile Window

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityShaderGUI.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityShaderGUI.cs.meta
Assets/MixedRealityToolkit/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityWireframeShaderGUI.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityWireframeShaderGUI.cs.meta
Assets/MixedRealityToolkit/StandardAssets/Shaders/MRTK_Wireframe.shader

This change updates the MRTK wireframe shader to support multiple rendering modes identical to the functionality in the MRTK standard shader. This is primarily to support transparency & other similar settings. 
The change creates a new base shaderGUI inspector class to be shared by both wireframe & standard shader. The related functionality is removed from StandardShaderGUI and WireframeShaderGUI is given the necessary code to render it's base properties plus the shared rendering mode-type properties. 
The shader is also updated to take the output alpha from both the base & wire color values instead of just wire intensity which will always be transparent on the faces. This gives developers more flexibility and control
- Fixes: #4992

Update Wireframe Shader & Inspector for transparency support

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/Slate.prefab
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

Fixing an issue where flattened bounding boxes would be completely flattened on an axis results in a very thin bounding box border. Bounding boxes now have a display scale (tweakable) for the flattened axis.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4976
Please see the slates contained in the HandInteractionExamples scene.
>
>

[Shell Parity] [Slate] Slate Flattened Border Fix

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/BaseInputHandler.cs

Allow `BaseInputHandler.IsFocusRequested` to be changed during play mode (and propagate a change to handler registration).

Support focus requested property change in runtime

---

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/VisualProfilerControl.cs

The VisualProfilerControl script's ToggleProfiler method was toggling all diagnostics, rather than just the profiler. While today there is only a single diagnostic that is controlled by ToggleDiagnostics, in the future, it is anticipated that additional displays (ex: debug panel, individual control of the profiler's settings, etc) will be added.

Fix VisualProfilerControl.ToggleProfiler implementation

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Controllers/WindowsMixedRealityControllerVisualizer.cs

When using the platform motion controller models, they showed up in the wrong place on-device after teleportation.
This was because we transformed the poses for the explicit pointer and grip poses, but not for the source pose.

Fix motion controller not moving with teleportation on-device

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/Camera/Prefabs/CameraSystem.prefab

The camera service manager prefab lost the reference to the concrete service type. this change repairs the issue.

camera service manager: fix missing service type reference

---

Assets/link.xml

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4265
See this comment in that issue for some more details on what happened here:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4265#issuecomment-510246866
Also, in case you were wondering how this was generated, these are the assemblies that are referenced in the default MRTK profiles (i.e. look for things of type "SystemType" and look at their corresponding references). In the long run this has to be more automated, as this was obviously a highly manual process. See this issue (https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5273) for more details on that.

Add a link.xml to Assets to prevent critical MRTK components from getting optimized away in IL2CPP builds

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Documentation/README_ManipulationHandler.md

manipulation handler one hand manipulation set to maintain rotation to user will now not take roll into account anymore.
- Fixes: #4295 
tested with WMR headset

removed roll from "maintain rotation to user" one hand manipulation mode

---

Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec
Assets/MixedRealityToolkit.Providers/MixedReality.Toolkit.Providers.nuspec
Assets/MixedRealityToolkit.Services/MixedReality.Toolkit.Services.nuspec
Assets/MixedRealityToolkit/MixedReality.Toolkit.nuspec

Our NuGet packages have been broken due to this PR:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4858
Which updated assembly names, but didn't also update the corresponding nuspec files to ensure that they would continue to get copied over.
Thankfully, there was also this pretty sweet migration guide which makes it super clear where things moved: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/UpdatingToGA.html

Fix the broken NuGet packages.

---

Assets/MixedRealityToolkit.Services/CameraSystem/MixedRealityCameraSystem.cs
Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs

The camera system was previously not initiating the parenting of the camera to the playspace. This was being performed by most other services when they added a child object to the playspace transform.
Since MRTK expects the camera to be parented to support features such as teleportation, the camera system should ensure proper hierarchy at runtime.
Since the XR SDKs underlying our mixed reality support assume control over the camera's local position and not all platforms enforce the initial camera position be the origin (ex: Windows Mixed Reality uses the origin while OpenVR looks to be honoring the value set in the inspector).
This change adds a log warning that informs developers when the camera is not set to the origin at initialization of the camera system.

Make camera system initiate playspace parenting

---

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/ConstantViewSize.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/InBetween.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Momentum.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Orbital.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Overlap.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/RadialView.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Solver.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SurfaceMagnetism.cs

Changing the solverUpdate methodology to always apply the update from working to goal, regardless of solver. This allows for those creating new solvers to ignore the update process in favor of simply updating the goal position/rotation/scale. Also, by guaranteeing that these are called, maintainScale becomes a functional variable again
Also some minor documentation updates.

Update solver logic to update more consistently and respect scale

---

Assets/MixedRealityToolkit.Examples/Demos/SpatialAwareness/Scripts/DemoSpatialMeshHandler.cs

The previous version of the spatial awareness demo event handler only modified registration in Start and OnDestroy, This change adds OnEnable and OnDestroy registration changes.

Improve event [un]registration in spatial awareness demo

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/Boundary/Scripts/BoundarySystemManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Camera/Scripts/CameraSystemManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Diagnostics/Scripts/DiagnosticsSystemManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Input/Scripts/InputSystemManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/SpatialAwareness/Scripts/SpatialAwarenessSystemManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Support/Scripts/BaseServiceManager.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Teleport/Scripts/TeleportSystemManager.cs

This change updates the namespaces for the stand alone service implementations to help clarify that they are currently experimental and may experience significant change before they are finalized.

Move stand alone service managers to experimental namespace

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonContentCageProximity.mat
Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Cursors/FingerCursor.prefab
Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader
Assets/MixedRealityToolkit/Utilities/ProximityLight.cs

Tweaking proximity light behavior and parameters to closer match the shell.
Below this change is the proximity light in the Shell (left) and the MRTK (right).
After this change is the proximity light in the Shell (left) and the MRTK (right).
Note, the colors were tuned as close as possible but the shell using a texture whereas the MRTK uses a 3 way color blend to allow for easy customization. The button border width was also adjusted to match the shell.  
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5218
Try pressing buttons in the Hand Interaction Examples scene.
>
>
> As a reviewer, it is possible to check out this change …

[Shell Parity] Proximity Light Shell Parity

---

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs

Recently, enhanced log messages were added to the service locator object to help developers better understand which service(s) were failing to register. This change adds the interface type name to the message regarding attempting to register a null instance.
This was hit by one of our customers who reached out to me with the issue,

Add interface type to the "null concrete type" message in the service locator

---

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs

Manipulationhandler movement for both one and two hand far interaction would only take pointer position into account instead of the point where the pointer ray hits the object for grabbing.
- Fixes: #4399 
- added test for far interaction movement: moves cube 360 degree around player and makes sure the pointer ray stays on the same position on the cube
- tested in editor hand simulation, far and near interaction
- tested with WMR controllers far and near interaction
- tested on Hololens 2 far and near interaction

Fixed far interaction movement in ManipulationHandler

---

Assets/MixedReality.Toolkit.Foundation.nuspec

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4265
See the linked issue for more details about what we're doing here - this is being included as a convenience to NuGet consumers so that things just "work out of the box" and they don't have to define their own link.xml in order to avoid IL2CPP bytecode stripping

Add the link.xml in the Foundation NuGet package.
