microsoft/MixedRealityToolkit-Unity

Assets/HoloToolkit/Input/GazeManager.cs
=> Send OnGazeEnter and OnGazeLeave messages when the user gazes on a hologram

CONTRIBUTING.md, README.md
1. Added a table of contents.
2. Reorganized the readme so its easier to navigate.
3. Update the readme with appropriate links.
=> Updating README to match new folder structure

Assets/HoloToolkit/SpatialMapping/Scripts/RemoveSurfaceVertices.cs
Error in RemoveSurfaceVerticies was causing it to fail
=> Fix simple error

Assets/HoloToolkit/SpatialMapping/Shaders/Occlusion.shader, Assets/HoloToolkit/SpatialMapping/Shaders/Wireframe.shader
I missed these in my previous pull request.
=> Updating whitespace in the spatial mapping shaders

Assets/HoloToolkit/Input/Scripts/KeywordManager.cs
This allows quick and easy debugging in the Unity Editor
Fixes Issue #36.
=> Updated KeywordManager to support key bindings as well

Assets/HoloToolkit/Sharing/Tests/CustomMessages.cs
Introduced null checks for SharingStage and ServerConnection.
Fixes #40
=> Fixed potential null reference exception in CustomMessages.cs

Assets/HoloToolkit/Utilities/Prefabs/FPSDisplay.prefab, Assets/HoloToolkit/Utilities/Prefabs/FPSDisplay.prefab.meta
uses the Fps display script to render frame rate and render times directly in your scene.
Fixes #42
=> Added FPSDisplay prefab

Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs, Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs.meta
Auto Configure -> Scene, applies settings to main camera
Auto Configure -> Project, applies build, quality, and project settings.
See here for applied setting:
https://developer.microsoft.com/en-us/windows/holographic/unity_development_overview#Configuring_a_Unity_project_for_HoloLens
Resolves #50
=> Added new HoloToolkit menu for easy Configuration

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs
Minor but bubbles up through IntelliSense and can cause confusion
=> StopObserver summary typo

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingComponent/Support/SMBaseAbstract.cs
=> Change null coalescing operator to ternary for proper Mono 3.5 support

.gitignore, Assets/HoloToolkit/Utilities/Editor/BuildCommands.cs, Assets/HoloToolkit/Utilities/Editor/BuildCommands.cs.meta, Assets/HoloToolkit/Utilities/Editor/BuildMenu.cs, Assets/HoloToolkit/Utilities/Editor/BuildMenu.cs.meta
Menu allows for building the project with preferred settings.
Menu allows for opening the solution from the build.
Both commands ask about executing the other at appropriate times.
=> Added Build commands and menu.

Assets/HoloToolkit/Input/Scripts/BasicCursor.cs, Assets/HoloToolkit/Input/Scripts/CursorFeedback.cs, Assets/HoloToolkit/Input/Scripts/GazeManager.cs, Assets/HoloToolkit/Input/Scripts/HandGuidance.cs, Assets/HoloToolkit/Input/Scripts/HandsManager.cs, Assets/HoloToolkit/Sharing/Scripts/Utilities/ExternalProcess.cs, Assets/HoloToolkit/Utilities/Scripts/Billboard.cs, Assets/HoloToolkit/Utilities/Scripts/DirectionIndicator.cs, Assets/HoloToolkit/Utilities/Scripts/FixedAngularSize.cs, Assets/HoloToolkit/Utilities/Scripts/FpsDisplay.cs, Assets/HoloToolkit/Utilities/Scripts/SimpleTagalong.cs
Addressing some internal feedback.  Things like rewording comments/errors, renaming variables for clarity, instantiating at more appropriate times.  The biggest change might be in GazeManager, where Normal = -gazeDirection was changed so that the cursor front faces back to the user in a no-raycast-hit scenario. (Hard to notice because our default cursor is directionless)
=> Addressing internal feedback for input/utilities

External/MagicWindow/Occlusion.shader
Hosting some files for the magic window feature work.
=> Feature magicwindow

Assets/HoloToolkit/Utilities/Scripts/ManualCameraControl.cs
=> Default mouse look control to Shift key

Assets/HoloToolkit/SpatialMapping/Tests/SpatialMappingComponent/Example.unity
This change sets the Occlusion and Wireframe materials on the Spatial Mapping Renderer component that is attached to the main camera in the Example scene.
=> Editing example test scene for issue #58

GettingStarted.md, README.md
As a newbie to C# and Unity (and obviously HoloLens) I took some wrong turns that led me down the path of importing HoloToolkit as a Git submodule rather than as a Unity package. As a result I raised a couple of invalid issues here (#89 and #90). 
This Getting Started guide is intended to prevent others making the same mistakes (and for me to have your team review my approach to ensure I got it right this time).
Fixes #89 and #90
=> Document how to get started

Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs
fix for nuget restore (previously didn't function on some people's machines)
=> Build automation window - fix for nuget restore

Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs
=> Fix bad project list via absolute path

Assets/HoloToolkit/Input/Scripts/GazeManager.cs, Assets/HoloToolkit/Utilities/Scripts/StabilizationPlaneModifier.cs, Assets/HoloToolkit/Utilities/Scripts/StabilizationPlaneModifier.cs.meta, Assets/HoloToolkit/Utilities/Tests/Animations.meta, Assets/HoloToolkit/Utilities/Tests/Animations/PopupText.controller, Assets/HoloToolkit/Utilities/Tests/Animations/PopupText.controller.meta, Assets/HoloToolkit/Utilities/Tests/Animations/horizontal.anim, Assets/HoloToolkit/Utilities/Tests/Animations/horizontal.anim.meta, Assets/HoloToolkit/Utilities/Tests/Animations/horizontal.controller, Assets/HoloToolkit/Utilities/Tests/Animations/horizontal.controller.meta, Assets/HoloToolkit/Utilities/Tests/Animations/spiral.anim, Assets/HoloToolkit/Utilities/Tests/Animations/spiral.anim.meta, Assets/HoloToolkit/Utilities/Tests/Animations/spiral.controller, Assets/HoloToolkit/Utilities/Tests/Animations/spiral.controller.meta, Assets/HoloToolkit/Utilities/Tests/Animations/textfade.anim, Assets/HoloToolkit/Utilities/Tests/Animations/textfade.anim.meta, Assets/HoloToolkit/Utilities/Tests/Animations/vertical.anim, Assets/HoloToolkit/Utilities/Tests/Animations/vertical.anim.meta, Assets/HoloToolkit/Utilities/Tests/Prefabs.meta, Assets/HoloToolkit/Utilities/Tests/Prefabs/dot.prefab, Assets/HoloToolkit/Utilities/Tests/Prefabs/dot.prefab.meta, Assets/HoloToolkit/Utilities/Tests/Scripts.meta, Assets/HoloToolkit/Utilities/Tests/Scripts/GestureResponder.cs, Assets/HoloToolkit/Utilities/Tests/Scripts/GestureResponder.cs.meta, Assets/HoloToolkit/Utilities/Tests/Scripts/PlaneTargetGroup.cs, Assets/HoloToolkit/Utilities/Tests/Scripts/PlaneTargetGroup.cs.meta, Assets/HoloToolkit/Utilities/Tests/Scripts/PlaneTargetGroupPicker.cs, Assets/HoloToolkit/Utilities/Tests/Scripts/PlaneTargetGroupPicker.cs.meta, Assets/HoloToolkit/Utilities/Tests/StabilizationPlaneSetting.unity, Assets/HoloToolkit/Utilities/Tests/StabilizationPlaneSetting.unity.meta
Refactored stabilization plane code into its own file. Added functionality to tweak the stabilization plane's behavior and to visualize the plane when running in the Unity editor.
=> Update and refactor to GazeManager, creation of StabilizationPlane script

Assets/HoloToolkit/Input/Scripts/OnGazeEnterEvent.cs, Assets/HoloToolkit/Input/Scripts/OnGazeEnterEvent.cs.meta, Assets/HoloToolkit/Input/Scripts/OnGazeLeaveEvent.cs, Assets/HoloToolkit/Input/Scripts/OnGazeLeaveEvent.cs.meta, Assets/HoloToolkit/Input/Scripts/OnSelectEvent.cs, Assets/HoloToolkit/Input/Scripts/OnSelectEvent.cs.meta, Assets/HoloToolkit/Input/Tests/GazeEvents.unity, Assets/HoloToolkit/Input/Tests/GazeEvents.unity.meta, Assets/HoloToolkit/Utilities/Scripts/ManualCameraControl.cs
PR for https://github.com/Microsoft/HoloToolkit-Unity/issues/107
Added OnSelect and OnGazeEnter/Leave unity events hook incl a test scene
=> Add UnityEvent support

Assets/HoloToolkit/Utilities/Shaders/WindowOcclusion.shader, Assets/HoloToolkit/Utilities/Shaders/WindowOcclusion.shader.meta, Assets/HoloToolkit/Utilities/Tests/Materials.meta, Assets/HoloToolkit/Utilities/Tests/Materials/WindowContents.mat, Assets/HoloToolkit/Utilities/Tests/Materials/WindowContents.mat.meta, Assets/HoloToolkit/Utilities/Tests/Materials/WindowOcclusion.mat, Assets/HoloToolkit/Utilities/Tests/Materials/WindowOcclusion.mat.meta, Assets/HoloToolkit/Utilities/Tests/WindowOcclusion.unity, Assets/HoloToolkit/Utilities/Tests/WindowOcclusion.unity.meta, README.md
Added a WindowOcclusion shader for the already-published case study, plus a simple scene to demonstrate it working.
=> WindowOcclusion shader and test scene

Assets/HoloToolkit/Utilities/Scripts/ManualCameraControl.cs
- no need to check for GetKeyDir up/down AND GetAxis horizontal/vertical
- moved new walk code where it's supposed to be
- exposed fast control key (instead of always using left shit)
- also removed an annoying debug statement
=> Various fixes to ManualCameraControl :

GettingStarted.md
=> Update GettingStarted.md to clarify export requirements.

Assets/HoloToolkit-Examples/README.md
This folder will host samples/examples that use the HoloToolkit to help solve interesting scenarios.
=> Adding HoloToolkit-Examples folder

Assets/HoloToolkit/SpatialMapping/Shaders/Wireframe.shader
Side note: Recommend adopting EOF change as it's automatically made by GitHub's online code editor. Rejecting changes due to unwanted EOF will alienate potential contributors for zero actual project gain.
=> Update paper reference in comment (fixes #132)

Assets/HoloToolkit/Utilities/Scripts/Billboard.cs
=> Fixed Billboards alignment across all axes.

Assets/HoloToolkit-Examples/GazeRuler/Scripts/Test/LineTest.cs
I have deleted the unused variable and fix the issue
=> delete unused variable

Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/ActiveEvent.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManager.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManagerBase.cs
=> Added Support for Events on Audio Play Completion

GettingStarted.md
I added a few clarifications to the Getting Started documentation since I actually ran into these issues and figured others might too. Experienced Unity users will not need this, but Unity beginners will appreciate the clarifications.
=> Updated getting Started documentation

Assets/HoloToolkit/Utilities/README.md, Assets/HoloToolkit/Utilities/Scripts/SphereBasedTagalong.cs, Assets/HoloToolkit/Utilities/Scripts/SphereBasedTagalong.cs.meta, Assets/HoloToolkit/Utilities/Tests/SphereBasedTagalong.unity, Assets/HoloToolkit/Utilities/Tests/SphereBasedTagalong.unity.meta
See issue https://github.com/Microsoft/HoloToolkit-Unity/issues/111
=> Added SphereBasedTagalong + test scene

Assets/HoloToolkit/Sharing/Scripts/SharingStage.cs, Assets/HoloToolkit/Sharing/Tests/CustomMessages.cs, Assets/HoloToolkit/Sharing/Tests/ImportExportAnchorManager.cs
Added a flag in SharingStage to enable server auto discovery. 
Uses the first server that responds to connect to.
Fixes #172
=> AutoDiscover in Sharing Stage

Assets/HoloToolkit/Utilities/Prefabs/FPSDisplay.prefab, Assets/HoloToolkit/Utilities/Scripts/FpsDisplay.cs
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/216
Utilizes TextMesh and removes the two boxing allocations created every update.
=> Updated FpsDisplay Optimizations

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs, Assets/HoloToolkit/SpatialMapping/Tests/TapToPlace.unity, Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs, Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs.meta
Updated TapToPlace to use this script.
Updated TapToPlace test scene to include the WorldAnchorManager on the Managers GameObject.
=> Create WorldAnchorManager to abstract saving and loading of persisted anchors

Assets/HoloToolkit/Input/Scripts/HandsManager.cs
Added delegate event to HandsManager.cs for better hand tracking capabilities.
=> Added delegate event to HandsManager.cs for better hand tracking capabilities.

Assets/HoloToolkit/Input/Scripts/GestureManager.cs
UI elements should have a pressed and release state to provide the correct about of visual feedback to users, typical to most current UI systems. The GestureRecognizer.RecognitionStartedEvent fires first when a finger and thumb come together and GestureRecognister.RecognitionEndedEvent fires last, after all other manipulation events. This allows the UI to provide a solid down visual state so that the user knows how their input is being interpreted.
This is building off the current pattern of SendMessage for OnSelect, OnGazeEnter and OnGazeExit.
=> Added Pressed and Released events to the Gesture Manager

Assets/HoloToolkit/Sharing/Scripts/SDK/ObjectElementAdapter.cs, Assets/HoloToolkit/Sharing/Tests/Sharing.unity
Added missing Element changed events to ObjectElementAdapter.cs
Also fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/259
=> Sharing SDK update to ObjectElementAdapter.cs

Assets/HoloToolkit/Utilities/README.md
=> documenting FPSDisplay within Utilities' README

Assets/HoloToolkit/Input/Scripts/GazeStabilizer.cs, Assets/HoloToolkit/SpatialMapping/Scripts/SpatialProcessing/RemoveSurfaceVertices.cs
Issue #280 - using the MeshRenderer bounds rather than the collider bounds. Also being sure to transform the verts from the meshes into world space
Issue #282 - fixed the reported logic bug and cleaned up the UpdateInstability function a little bit
=> Fix issues #280 and #282

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingSource.cs
=> Increment SpatialMappingSource UpdateID based on mesh updates

Assets/HoloToolkit/Input/Scripts/GazeStabilizer.cs, Assets/HoloToolkit/Utilities/Scripts/RollingStatistics.cs, Assets/HoloToolkit/Utilities/Scripts/RollingStatistics.cs.meta
I tested this on the ColorPickerExample scene on 4 users (aside from myself).  Everyone agreed that this updated version was better.
=> simplified GazeStabilizer and made it less sticky

Assets/HoloToolkit-Examples/GazeRuler/Scenes/GazeRulerTest.unity, Assets/HoloToolkit-Examples/SpatialMappingComponent/SpatialMappingExample.unity, Assets/HoloToolkit/Input/Prefabs/Cursor.prefab, Assets/HoloToolkit/Input/Tests/BasicCursor.unity, Assets/HoloToolkit/Input/Tests/Cursor.unity, Assets/HoloToolkit/Input/Tests/CursorWithFeedback.unity, Assets/HoloToolkit/Input/Tests/FocusedObjectKeywords.unity, Assets/HoloToolkit/Input/Tests/GazeEvents.unity, Assets/HoloToolkit/Input/Tests/GestureManipulator.unity, Assets/HoloToolkit/Input/Tests/KeywordManager.unity, Assets/HoloToolkit/Input/Tests/MicrophoneStream.unity, Assets/HoloToolkit/Input/Tests/Prefabs/FocusedObjectCube.prefab, Assets/HoloToolkit/Input/Tests/Prefabs/FocusedObjectSphere.prefab, Assets/HoloToolkit/Input/Tests/Prefabs/SelectedObjectCube.prefab, Assets/HoloToolkit/Input/Tests/Prefabs/SelectedObjectSphere.prefab, Assets/HoloToolkit/Sharing/Tests/Sharing.unity, Assets/HoloToolkit/SpatialMapping/Prefabs/SurfacePlane.prefab, Assets/HoloToolkit/SpatialMapping/Tests/TapToPlace.unity, Assets/HoloToolkit/Utilities/Materials.meta, Assets/HoloToolkit/Utilities/Materials/HoloToolkit_Default.mat, Assets/HoloToolkit/Utilities/Materials/HoloToolkit_Default.mat.meta, Assets/HoloToolkit/Utilities/Tests/ManualCameraControl.unity, Assets/HoloToolkit/Utilities/Tests/Prefabs/dot.prefab, Assets/HoloToolkit/Utilities/Tests/SphereBasedTagalong.unity, Assets/HoloToolkit/Utilities/Tests/StabilizationPlaneSetting.unity, Assets/HoloToolkit/Utilities/Tests/TextToSpeechManager.unity, Assets/HoloToolkit/Utilities/Tests/WindowOcclusion.unity
Remove the tiny sphere from the cursor off holograms
=> switch default material to a HoloToolkit_Default Material

Assets/HoloToolkit/Build/Editor/BuildDeployWindow.cs, Assets/HoloToolkit/Sharing/Editor/SharingMenu.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioProfiler.cs, Assets/HoloToolkit/Utilities/Editor/ConfigureMenu.cs
Moved UAudio profiler from Addons to HoloToolkit.
Changed priority of menu items and fixed improper usage.
=> Updated HoloTookit Menu Dropdown

Assets/HoloToolkit-Examples/SharingWithUNET/Scenes/sharingwithunet.unity, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/BulletController.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/GenericNetworkTransmitter.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/NetworkDiscoveryWithAnchors.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/PlayerController.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/SharedAnchorDebugText.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/SharedAnchorDebugText.cs.meta, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/SharedCollection.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/UNetAnchorManager.cs
add copyright information to source files
added debug text on the anchor position.
=> put BulletController and PlayerController into separate name space

Assets/HoloToolkit-Examples/SharingWithUNET/Scenes/sharingwithunet.unity, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/UNetAnchorManager.cs, Assets/HoloToolkit/Utilities/Scripts/ManualCameraControl.cs
fix missing object in prefab
remove excessive debug print
=> ifdef out ManualCameraControl if not in the UNITY_EDITOR

Assets/HoloToolkit/Sharing/Tests/ImportExportAnchorManager.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/FileSurfaceObserver.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/MeshSaver.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMappingManager.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMeshSource.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMeshTarget.cs, Assets/HoloToolkit/SpatialMapping/Scripts/SpatialProcessing/RemoveSurfaceVertices.cs, Assets/HoloToolkit/SpatialMapping/Scripts/SpatialProcessing/SurfaceMeshesToPlanes.cs
Creates ability to use HoloToolkit in companion apps on other platform targets.
=> Cross platform compatibility

Assets/HoloToolkit-Examples/Text.meta, Assets/HoloToolkit-Examples/Text/3DTextSamples.prefab.meta, Assets/HoloToolkit-Examples/Text/TextPrefabSamplesTest.unity.meta, Assets/HoloToolkit-Examples/Text/UITextSamples.prefab.meta, Assets/HoloToolkit/UI/Materials.meta, Assets/HoloToolkit/UI/Materials/3DTextSegoeUI.mat.meta, Assets/HoloToolkit/UI/Prefabs.meta, Assets/HoloToolkit/UI/Prefabs/3DTextPrefab.prefab.meta, Assets/HoloToolkit/UI/Prefabs/UITextPrefab.prefab.meta, Assets/HoloToolkit/UI/README.md.meta, Assets/HoloToolkit/UI/Scripts.meta, Assets/HoloToolkit/UI/Shaders.meta, Assets/HoloToolkit/UI/Shaders/3DTextShader.shader.meta
Adding missing .meta files for https://github.com/Microsoft/HoloToolkit-Unity/pull/339
=> Adding .meta files

Assets/HoloToolkit/Input/Scripts/InputManager.cs
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/366
=> Fixed reversed logic and typo in InputManager.cs

ProjectSettings/ProjectSettings.asset
For some reason this file does not update properly when saving project, but generates after building a project.
=> Updated ProjectSettings.asset for 5.3.0f3

Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/LevelSolver.cs
=> Fix check to see if solver is initialized

Assets/HoloToolkit/Input/Scripts/Interactions/HandDraggable.cs
Matches formatting pattern throughout HTK
=> Minor formatting changes to HandDraggable.cs

Assets/HoloToolkit/Input/Scripts/Voice/KeywordManager.cs
A fix to issue #396 and removed Linq.
=> Fix KeywordManager initialization

Assets/HoloToolkit/Utilities/Editor/EditorGUIExtensions.cs, Assets/HoloToolkit/Utilities/Editor/EditorGUILayoutExtensions.cs
Updated EditorGUILayoutExtensions to also handle ObjectFields with Material, SceneAssets, and Generic UnityEngine.Objects.
Cleaned up EditorGUIExtionsions and added SceneAsset and Material types to ObjectField.
=> Updates to EditorGUI Extensions in Utilities folder.

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs
=> Remove test code from TapToPlace.cs

Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/AppState.cs
Checked out today's master branch and it was giving me a compilation error.
=> Added missing using HoloToolkit.Unity.InputModule;

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs, Assets/HoloToolkit/Utilities/Scripts/Extensions/VectorExtensions.cs
Just pulled and was unable to compile because of missing references
=> Add missing references for VectorExtensions.cs

Assets/HoloToolkit/Utilities/Scripts/Extensions/VectorExtensions.cs
Added the oveloads but I would argue that the Average and the Median of an empty collection is not Zero. It should either throw an exception or return null (using Nullable<Vector3>). This forces the developer to check for empty collections and avoid weird runtime errors. What do you think?
=> Extended Average and Median to support IEnumerable and Vector2

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs
Made private fields protected to make this class easier to extend. https://github.com/Microsoft/HoloToolkit-Unity/issues/421
Also added tooltip for `IsBeingPlaced`
Made unity specific methods private.
=> TapToPlace.cs: updated access modifiers

Assets/HoloToolkit/Utilities/Scripts/Extensions/TransformExtensions.cs
Create one single instance of StringBuilder.
=> TransformExtensions.GetFullPath() optimization

CONTRIBUTING.md
I also started a similar [pull request for HoloToolkit](https://github.com/Microsoft/HoloToolkit/pull/66).
=> Update contribution instructions for Microsoft employees

Assets/HoloToolkit/SpatialMapping/Scripts/TapToPlace.cs
"private virtual void" for several methods is not valid -> "protected virtual void". And the IInputClickHandler.OnInputClicked is implemented as protected, but should be public, or the class does not implement the interface.
=> This does not compile. TapToPlace contains several errors

Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/PlayerController.cs, Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/AppState.cs, Assets/HoloToolkit/Input/Scripts/SetGlobalListener.cs
Some scripts were not unregistering on destroy. Most importantly SetGlobalListener.cs
=> Unregister global listeners on destroy

Assets/HoloToolkit/Utilities/README.md, Assets/HoloToolkit/Utilities/Shaders/FastConfigurable.shader, Assets/HoloToolkit/Utilities/Shaders/FastConfigurable.shader.meta, Assets/HoloToolkit/Utilities/Shaders/macro.cginc, Assets/HoloToolkit/Utilities/Shaders/macro.cginc.meta
 should be able to replace almost all uses of existing shaders.
=> Adding fast configurable shader

Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/AppState.cs
Simply added a curly brace to EOF.
=> Fixing build break caused due to recent input changes merge

Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManager.cs
- Added check for null or empty string before searching `eventDictionary`.
- Added an optional parameter to one of the `PlayEvents` to remove a redundant one.
- Formatting.
=> UAudioManager added null check in PlayEvent

Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
Resolves https://github.com/Microsoft/HoloToolkit-Unity/issues/524
=> Compatibility with Vuforia: GazeTransform initialization.

Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs
It will remove all user anchors from the scene (anchors generated from Spatial Mapping and Surface Observer won't be removed)
=> Adding a Remove All Anchors method in WorldAnchorManager

Assets/HoloToolkit/Input/Scripts/InputSources/EditorHandsInput.cs
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/448
=> Modified Editor Input

Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingManager.cs, Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstanding.cs, Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingCustomMesh.cs
Added Delegate when scan is done and a bool property whether Any mesh sectors been scanned
Why i did this?
I needed an delegate event when scanning is done;
In my application i need to know if something has been scanned to show additional label
=> Added event when scan is done and a bool property whether Any mesh sectors been scanned

Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs
I'm sorry if I'm mistaken.
Thanks.
=> Fixed a hit target variable in Cursor.UpdateCursorTransform

Assets/HoloToolkit/Utilities/Scenes/HeadsetAdjustment.unity, Assets/HoloToolkit/Utilities/Scripts/Editor/HeadsetAdjustmentEditor.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/HeadsetAdjustmentEditor.cs.meta, Assets/HoloToolkit/Utilities/Scripts/HeadsetAdjustment.cs
- Added class to `HoloToolkit.Unity` namespace and organized methods.
- Added license header.
- Enable scene object reference in editor.
=> Moved HeadsetAdjustment into HoloToolkit.Unity namespace 

.gitignore
=> Add WindowsStoreApp to .gitignore

Assets/HoloToolkit/SpatialMapping/README.md
Just found them while reading the documentation, figured it might confuse a new reader and hence proposing the fix.
=> Fixing some typos

Assets/HoloToolkit/Utilities/Prefabs/ReturnToSceneLauncher.prefab, Assets/HoloToolkit/Utilities/Prefabs/ReturnToSceneLauncher.prefab.meta, Assets/HoloToolkit/Utilities/README.md, Assets/HoloToolkit/Utilities/Scenes/SceneLauncher.unity, Assets/HoloToolkit/Utilities/Scenes/SceneLauncher.unity.meta, Assets/HoloToolkit/Utilities/Scripts/SceneLauncher.cs, Assets/HoloToolkit/Utilities/Scripts/SceneLauncher.cs.meta, Assets/HoloToolkit/Utilities/Scripts/SceneList.cs, Assets/HoloToolkit/Utilities/Scripts/SceneList.cs.meta
=> Scene Launcher for easily switching between various HoloToolkit scenes

Assets/HoloToolkit/UI/Scripts.meta, Assets/HoloToolkit/UI/Scripts/UsabilityScaler.cs, Assets/HoloToolkit/UI/Scripts/UsabilityScaler.cs.meta, Assets/HoloToolkit/UI/Scripts/UsabilityUtilities.cs, Assets/HoloToolkit/UI/Scripts/UsabilityUtilities.cs.meta, Assets/HoloToolkit/UI/Tests.meta, Assets/HoloToolkit/UI/Tests/Scenes.meta, Assets/HoloToolkit/UI/Tests/Scenes/UsabilityScalerTest.unity, Assets/HoloToolkit/UI/Tests/Scenes/UsabilityScalerTest.unity.meta
This PR adds UsabilityScaler and UsabilityUtilities classes to help scale objects based on
HMD visual characteristics.  Currently it only uses field of view and resolution to choose
the scale factor, but as new devices are created in the future, additional characteristics
may come into play.
=> Usability scaler

Assets/HoloToolkit/Utilities/Prefabs/ReturnToSceneLauncher.prefab, Assets/HoloToolkit/Utilities/Prefabs/ReturnToSceneLauncher.prefab.meta, Assets/HoloToolkit/Utilities/Prefabs/SceneLauncherButton.prefab, Assets/HoloToolkit/Utilities/Prefabs/SceneLauncherButton.prefab.meta, Assets/HoloToolkit/Utilities/README.md, Assets/HoloToolkit/Utilities/Scenes/SceneLauncher.unity, Assets/HoloToolkit/Utilities/Scenes/SceneLauncher.unity.meta, Assets/HoloToolkit/Utilities/Scripts/SceneLauncher.cs, Assets/HoloToolkit/Utilities/Scripts/SceneLauncher.cs.meta, Assets/HoloToolkit/Utilities/Scripts/SceneLauncherButton.cs, Assets/HoloToolkit/Utilities/Scripts/SceneLauncherButton.cs.meta, Assets/HoloToolkit/Utilities/Scripts/SceneList.cs, Assets/HoloToolkit/Utilities/Scripts/SceneList.cs.meta
Unreverts #713. Fixes #712 and #674.
@StephenHodgson this should address the issue that you raised.
=> Restore SceneLauncher and remove usage of HoloToolkit-Examples

Assets/HoloToolkit/Input/Scripts/Editor/SpeechInputHandlerEditor.cs, Assets/HoloToolkit/Input/Scripts/Voice/SpeechInputHandler.cs
Added Global Listener option to SpeechInputHandler as this scenario is no longer supported due to KeywordManager now being obsolete
=> Added Global Listener option to SpeechInputHandler 

Assets/HoloToolkit/Utilities/Scripts/Billboard.cs
Updated the billboard script to use a custom transform target.
=> Updated billboard to use a target transform.

ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, README.md
Fixes https://github.com/Microsoft/HoloToolkit-Unity/issues/691
=> Update to Unity 5.6.2f1

Assets/HoloToolkit/Input/Scripts/InputManager.cs
- Added check for modal input != null when we handle events.
=> InputManager Update

Assets/HoloToolkit-Tests/Input/Scenes/InputManagerTest.unity
TextMesh objects were marked static, which thew GI warnings about missing normals.
`Mesh doesn't have normals. Please create some for GI.`
=> Updated Input Manager Test scene.

Assets/HoloToolkit/Build/Editor/BuildSLNUtilities.cs
[Fixed typo for cmd line build utilities](https://github.com/Microsoft/HoloToolkit-Unity/pull/714#discussion_r126690156).
=> Build utilities update

Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParentWithControllers.prefab, Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParentWithControllers.prefab.meta, Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs, Assets/HoloToolkit/Input/Scripts/InputSources/GesturesInput.cs, ProjectSettings/ProjectVersion.txt
Adds a new prefab with controller visualization built-in.
Fixes an issue where already paired controllers weren't firing a SourceDetected on app launch (resolving some question TODOs).
Fixes an issue where lost controllers weren't properly destroying their visualization GameObjects.
=> [RS2] Controller visualization updates

Assets/HoloToolkit/Build/Editor/BuildDeployTools.cs
Fixes #775 when determining Visual Studio instance.
=> Build & Deploy tools fix

Assets/HoloToolkit/UI/Scripts/Keyboard.cs
Updated to check for UNITY_WSA before accessing the dictation object since it won't exist in any other build targets.  Also removed all the tabs replaced with spaces for consistent indentation.
=> Fix for issue 794

Assets/HoloToolkit-Examples/InteractiveElements/Scripts/Controls/SliderGestureControl.cs
The UpdateEvent of the  slider  control didn't fire anytime. UpdateEvent now getting fired when
SliderValue is set to a new value.
=> Added update event invoking

README.md
[README update] Updated strings in URLs that contains RS2_WindowsMixedReality to Dev_Unity_2017.2.0
=> Updated broken links to renamed branch

Assets/HoloToolkit/Input/Scripts/HandGuidance.cs, Assets/HoloToolkit/Input/Scripts/InputManager.cs, Assets/HoloToolkit/Input/Scripts/Microphone/DictationInputManager.cs, Assets/HoloToolkit/Input/Scripts/Voice/KeywordManager.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/RemoteMappingManager.cs
https://github.com/Microsoft/HoloToolkit-Unity/pull/827#discussion_r131950983
=> fixed cross platform support from last refactor PR

Assets/HoloToolkit-Tests/SpatialSound/Scenes/UAudioManagerTest.unity, Assets/HoloToolkit-Tests/SpatialSound/Scenes/UAudioManagerTest.unity.meta, Assets/HoloToolkit-Tests/SpatialSound/Scripts.meta, Assets/HoloToolkit-Tests/SpatialSound/Scripts/UAudioManagerTest.cs, Assets/HoloToolkit-Tests/SpatialSound/Scripts/UAudioManagerTest.cs.meta, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/ActiveEvent.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/AudioClip.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/AudioContainer.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/AudioEvent.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioManagerBaseEditor.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioManagerEditor.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioMiniManagerEditor.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioProfiler.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/MiniAudioEvent.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManager.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManagerBase.cs, Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioMiniManager.cs
Fixes #32 
during renaming of the UAudioManager Module (commit: a473ee2) the Names in the Editor Scripts were not changed acordingly. This caused errors in the editor.
I changed the variable names and also added a test scene for the UAudioManager.
=> Fixed UAudioManager Editor Bug and added Test Scene for UAudioManager

Assets/HoloToolkit-Examples/SpatialMappingComponent/DropCube.cs, Assets/HoloToolkit-Examples/SpatialUnderstanding/SpatialUnderstanding-FeatureOverview/Scripts/UI.cs, Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs, Assets/HoloToolkit/Input/Scripts/HandGuidance.cs, Assets/HoloToolkit/Input/Scripts/InputManager.cs, Assets/HoloToolkit/Input/Scripts/InputSources/GesturesInput.cs, ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, README.md
=> Updating to 2017.2.0b8

Assets/HoloToolkit-Examples/InteractiveElements/Materials/Controls/Button.mat, Assets/HoloToolkit-Examples/InteractiveElements/Scenes/InteractiveButtonComponents.unity, Assets/HoloToolkit-Examples/Prototyping/Shaders/UnlitTransparentTriplanar.shader, Assets/HoloToolkit-Examples/Prototyping/Shaders/UnlitTriplanar.shader, Assets/HoloToolkit/UI/Shaders/3DTextShader.shader
I updated the 3DTextShader and a couple vertex shaders to include instancing and now works with both multi pass and single pass stereo rendering build types.  #551
=> 3DTextShader instancing updates

Assets/HoloToolkit/Input/Scripts/Gaze/GazeManager.cs
=> Updated Motion Blending for uGUI elements.

Assets/HoloToolkit/Input/Scripts/InputSources/GesturesInput.cs, Assets/HoloToolkit/Input/Tests/Scenes/MotionControllerTest.unity, Assets/HoloToolkit/Input/Tests/Scripts/HapticsTest.cs, Assets/HoloToolkit/Input/Tests/Scripts/HapticsTest.cs.meta, Assets/HoloToolkit/Utilities/Scripts/Extensions/HapticsExtensions.cs, Assets/HoloToolkit/Utilities/Scripts/Extensions/HapticsExtensions.cs.meta
These features won't be supported as Unity APIs in Unity 2017.2.
=> Adding haptics extensions to InteractionSource

Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/Pyramid3side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/Pyramid4side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/Pyramid5side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/angleThick.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/angleThickThin.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/angleThin.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/arrow.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/arrowPointer.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/cheveron.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/cone.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/crosshair.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/crosshairSmall.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diamond.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diamond3side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diamond4side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diamond5side.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diamondCone.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/disk.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diskLarge.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diskMedium.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/diskSmall.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/sqCrosshair.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/sqCrosshairSmall.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/torus.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/triangle.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/wedge.fbx.meta, Assets/HoloToolkit-Examples/Prototyping/Primitives/Models/wedgeOpen.fbx.meta
Primitives keep importing unused materials into the project.
=> Turned off material importer for primitives

Assets/HoloToolkit-Examples/ColorPicker/GazeableColorPicker.cs, Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Input/Scripts/ControllerInfo.cs, Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityCameraMangerEditor.cs, Assets/HoloToolkit/Input/Scripts/Editor/MixedRealityCameraMangerEditor.cs.meta, Assets/HoloToolkit/Input/Scripts/Utilities/MixedRealityCameraManager.cs, ProjectSettings/ProjectVersion.txt, README.md
Updated Editor to 2017.2.0b11.
Updated obsolete quality settings usages.
fixed misc warnings.
=> Editor update and misc compiler warning fixes.

Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/GenericNetworkTransmitter.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/NetworkDiscoveryWithAnchors.cs
fixed some members not being renamed properly in last pr
=> Examples regression fix

README.md
See [preview here](https://github.com/StephenHodgson/HoloToolkit-Unity/blob/readme-update/README.md#roadmaps)
=> Updated Main readme page table formatting.

Assets/HoloToolkit/Utilities/Scripts/Editor/AutoConfigureMenu.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs, Assets/HoloToolkit/Utilities/Shaders/FastConfigurable/Editor/CustomMaterialEditor.cs
=> Unity 5.6 support

Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs
Moved two bools out of the WSA definition.
=> Fixed some serialization errors when building for standalone.

Assets/HoloToolkit/Input/Scripts/Editor/SpeechInputHandlerEditor.cs
Fixes #996
Reloading keyword in speech input handler when changed in speech input source
=> Reloading keyword in speech input handler

Assets/HoloToolkit/Utilities/Scripts/FadeScript.cs
See https://github.com/Microsoft/MixedRealityToolkit-Unity/commit/290cec0854c67b923e810a8a440c55151bcb8a85
=> Fixed improper OnDestroy implementation

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParent.prefab, Assets/HoloToolkit/Input/Prefabs/TeleportMarker.prefab, Assets/HoloToolkit/Input/Scripts/ControllerVisualizer.cs, Assets/HoloToolkit/Input/Scripts/Cursor/Cursor.cs, Assets/HoloToolkit/Input/Scripts/EditorInputSelector.cs, Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs, Assets/HoloToolkit/Input/Scripts/Focus/InputSourcePointer.cs, Assets/HoloToolkit/Input/Scripts/Gaze/MixedRealityTeleport.cs, Assets/HoloToolkit/Input/Scripts/InputEvents/IControllerInputHandler.cs, Assets/HoloToolkit/Input/Scripts/InputEvents/ISelectHandler.cs, Assets/HoloToolkit/Input/Scripts/InputEvents/ISelectHandler.cs.meta, Assets/HoloToolkit/Input/Scripts/InputManager.cs, Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs, Assets/HoloToolkit/Input/Scripts/InputSources/InteractionSourceInputSource.cs, Assets/HoloToolkit/Input/Scripts/Utilities/ManualGazeControl.cs, ProjectSettings/InputManager.asset
Fixes #843.
Use MotionControllerTest.unity to test.
=> Fix teleport to match current shell and update stage to not move during teleport

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs, Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFComponent.cs, Assets/HoloToolkit/Utilities/Scripts/GLTFComponentStreamingAssets.cs
Assigned default values, if none.
Updated `WebRequest.send()`.
Updated null check because structs can't be null.
=> Removes misc compiler warnings.

Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs
=> Instance isn't found if class is on a disabled GameObject.

Assets/HoloToolkit-Examples/GamePad/Scenes/XboxControllerExample.unity, Assets/HoloToolkit/Input/Scripts/GamePad/XboxControllerMapping.cs, Assets/HoloToolkit/Input/Scripts/InputSources/XboxControllerInputSource.cs
=> Mrtk 2017.2 Xbox Controller Regression Fixes

Assets/HoloToolkit/Sharing/Scripts/Utilities/SharingWorldAnchorManager.cs, Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs
=> Mrtk dev2017.2 sharing fixes port

Assets/HoloToolkit/Sharing/Scripts/Utilities/SharingWorldAnchorManager.cs, Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs
=> Fixes issue with Start method inheritance.

ProjectSettings/ProjectVersion.txt, README.md
=> Update Dev Branch Editor to 2017.2.0f2-MRTP

Assets/HoloToolkit/Input/Prefabs/HoloLensCamera.prefab
=> Updated HoloLensCamera.prefab Joystick Gaze Control Mappings

GettingStarted.md
Syncing up the Dev branch with master changes.
=> Mrtk dev2017.2 master merge sync

Assets/HoloToolkit/Sharing/Scripts/Utilities/ManualIpConfiguration.cs
=> Sharing Service IP input Fix

Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs
Fixes #1074
Missing UnitTests.
=> Fixed the logic fault to assign the anchorName.

ProjectSettings/ProjectSettings.asset
=> Changing API Compatibility Level to .NET 4.6

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployPrefs.cs, Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs, Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs, Assets/HoloToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/AutoConfigureMenu.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/SceneSettingsWindow.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs, Assets/HoloToolkit/Utilities/Scripts/Editor/TextureScale.cs
Fixes #1067
Fixes #1071 
Fixes https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/1059#discussion_r142541238
=> Misc Fixes

Assets/HoloToolkit/Sharing/Scripts/Utilities/ManualIpConfiguration.cs, Assets/HoloToolkit/Utilities/Scripts/WorldAnchorManager.cs, ProjectSettings/ProjectSettings.asset
Fixes IL2CPP not building, among other things.
=> Merging master into Dev branch

ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, README.md
=> Updated Unity Editor to 2017.1.2

Assets/HoloToolkit-Examples/Medical/Scenes/MedicalExample.unity
=> Updated medical example to use SpeechInputSource.cs and SpeechInputHandler.cs

GettingStarted.md
=> Fixing little typo 'envionment'

Assets/HoloToolkit-Examples/UX/Prefabs/CheckBoxSet.prefab, Assets/HoloToolkit-Examples/UX/Prefabs/CheckBoxSet.prefab.meta, Assets/HoloToolkit-Examples/UX/Scenes/InteractiveButtonComponents.unity, Assets/HoloToolkit-Examples/UX/Scripts/InteractiveSet.cs, Assets/HoloToolkit-Examples/UX/Scripts/InteractiveSet.cs.meta
=> Extended InteractiveRadialSet to allow multiple selection

Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs, Assets/HoloToolkit/Utilities/Scripts/SingleInstance.cs.meta
=> Adds SingleInstance from dev branch and fixed #1031

Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs
=> Cleans up event handlers and Tracks previously untracked controllers if seen in InteractionSourceUpdated event.

ProjectSettings/ProjectVersion.txt, README.md
=> Unity Editor Update 2017.2.0f3 MRTP

README.md, UpgradeGuide.md
Fixed #882 Preview [Here](https://github.com/StephenHodgson/MixedRealityToolkit-Unity/blob/MRTK-UpgradeGuide/UpgradeGuide.md)
Also updated the roadmap.
=> Mrtk upgrade guide

Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/Editor/UAudioManagerBaseEditor.cs
Fixed the curve property names to match the new casing.
=> Fixed AudioManager Editor property names for 3D Sound properties.

Assets/HoloToolkit-Examples/Sharing/SharingService/Scenes/SharingSpawnTest.unity
I had a quick look to see if any of the other example scenes have this issue, but couldn't see any
=> Updated SharingSpawnTest to use speech input handler and source

Assets/HoloToolkit-Examples/Sharing/SharingService/Scenes/RoomAndAnchorTest.unity, Assets/HoloToolkit-Examples/Sharing/SharingService/Scenes/SharingSpawnTest.unity
=> Updated sharing scenes to use Sharing World Anchor Manager

Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs
=> Add already tracked controllers in Awake

Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs
Fixes duplicate add attempts when async controller loading causes a delay in the ID actually being in the dictionary
I also refactored the controller update code, since I had identical code in two places.
=> Motion Controller detection update

README.md
Spotted two typos in the HoloLens section of the readme.
=> Fixed Typo's on front page

Assets/HoloToolkit/Utilities/Scripts/Singleton.cs
=> Singleton update

Assets/HoloToolkit-Examples/Input/Scenes/BasicCursor.unity, Assets/HoloToolkit-Examples/Input/Scenes/Cursor.unity, Assets/HoloToolkit-Examples/Input/Scenes/CursorWithFeedback.unity, ProjectSettings/ProjectVersion.txt
Use the cursor matching the scene name rather than DefaultCursor
Sort scene objects identically
=> Fix cursor example scenes

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs
=> Fixed target VR device on 5.6 and 2017.1

ProjectSettings/ProjectVersion.txt, README.md
=> Updated Unity Editor 2017.2.0f3 MRTP3

Assets/HoloToolkit/Input/Scripts/InputSources/InteractionInputSource.cs
Added delayed initialization in `OnEnable` to wait until `Start` in case the `InputManager` instance isn't ready.
=> Fixes Interaction Sources not properly being registered at startup in some cases

Assets/HoloToolkit/Input/Scripts/InputSources/GamepadInput.cs
=> Mrtk small game pad update

Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scenes/GrabMechanics.unity
=> Resetting controller hands in grab scene

.github/issue_template.md, .github/pull_request_template.md
=> Added issue & pr template

Assets/HoloToolkit/SpatialSound/Scripts/UAudioManager/UAudioManagerBase.cs, Assets/HoloToolkit/UX/Scripts/Lines/LineBaseEditor.cs, Assets/HoloToolkit/UX/Scripts/Lines/Spline.cs
Overview
---
Cleaned up compiler warning messages.
Changes
---
- Fixes: #1334 
- Also fixes hidden field in `Spline.cs`
- Fixes: #1333 (@DaveSullivanAtWork please review this)
=> Compiler messages cleanup

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployTools.cs
Overview
---
Added scripting backend check before restoring nuget packages.
Changes
---
- Fixes: #1358.
=> Fix building APPX for IL2CPP target

Assets/HoloToolkit/Input/Scripts/Focus/FocusManager.cs
Just updated an assert.
Zero is a valid index.
=> Updated Assert for invalid pointer index.

Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs, Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs.meta, Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerInfo.cs, Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs
This pulls some of the latest controller-related work from the upcoming 213 academy course into MRTK.
Includes numerous fixes and improvements for **MotionControllerInfo** / **MotionControllerVisualizer**, as well as the new utility **AttachToController**.
Everything has been tested thoroughly and works well in the wild.
=> Motion controller script updates 

Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs
=> Fixed standalone compile issues

Assets/HoloToolkit/UX/Textures/KeyboardAtlas.spriteatlas, GettingStarted.md, ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, README.md
=> Updated MRTK Unity Editor to 2017.2.0p2 MRTP 5

Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs, Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerInfo.cs
Overview
---
Fixes compatibility with 5.6 & 2017.1 unity builds.
=> 5.6 & 2017.1 Build fixes

Assets/HoloToolkit-Examples/UX/Scripts/GestureInteractive.cs
Overview
---
Updated `GestureInteractive.cs` to be backwards compatible for 2017.1 
Changes
---
- Fixes: #1275
=> Updated GestureInteractive example script

.gitignore
Overview
---
Adding UnityPackageManager to .gitignore
Changes
---
- Fixes: #1404.
=> Adding UnityPackageManager to .gitignore

Assets/HoloToolkit-Examples/Boundary/Materials/Highlight.mat, Assets/HoloToolkit-Examples/Boundary/Scenes/BoundaryTest.unity, Assets/HoloToolkit-Examples/Boundary/Scripts/BoundaryTest.cs, Assets/HoloToolkit-Examples/Input/Scenes/InputManagerTest.unity, Assets/HoloToolkit-Examples/Input/Scenes/InputTapTest.unity, Assets/HoloToolkit-Examples/Input/Scenes/MotionControllerTest.unity, Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scenes/GrabMechanics.unity, Assets/HoloToolkit-Examples/UX/Scenes/InteractableObjectExample.unity, Assets/HoloToolkit-Examples/UX/Scripts/OptimizeSceneforDeviceType.cs, Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Boundary/Scripts/SceneContentAdjuster.cs, Assets/HoloToolkit/Input/Prefabs/MixedRealityCameraParent.prefab, Assets/HoloToolkit/UX/Scripts/Receivers/InteractionReceiver.cs
Overview
---
Scene content adjuster both wasn't working on an actual device and was overwriting the X and Z values of the GameObject's position. This fixes both of those bugs.
Changes
---
- Fixes: #1324
- Fixes: #1354 
- Fixes: #1304 
- Fixes: #1384
=> SceneContentAdjuster updates

Assets/HoloToolkit/Input/Scripts/Utilities/AttachToController.cs
Overview
---
Fixes build when target is not WSA
Changes
---
- Fixes: #1475
=> Mrtk build hot fix

CONTRIBUTING.md, README.md, Roadmap.md
Updated text to mention new branch structure.
Master will be locked for direct checkins.
Dev_Working_Branch will be the place to be for daily work.
=> Adding Roadmap.md

Assets/HoloToolkit-Examples/Input/Scenes/GamepadTest.unity, Assets/HoloToolkit-Examples/Input/Scripts/GazeResponder.cs
Overview
---
Changes
---
- Fixes: #1515
=> Fixing GazeResponder to use the new shader property instead of old one.

Assets/HoloToolkit/Boundary/Scripts/SceneContentAdjuster.cs
=> MRTK Editor Compatibility

Assets/HoloToolkit-Examples/UX/Prefabs/ButtonRectTransform.prefab, Assets/HoloToolkit-Examples/UX/Prefabs/ButtonRectTransform.prefab.meta, Assets/HoloToolkit-Examples/UX/Prefabs/ToggleButtonRectTransform.prefab, Assets/HoloToolkit-Examples/UX/Prefabs/ToggleButtonRectTransform.prefab.meta, Assets/HoloToolkit-Examples/UX/Scenes/InteractiveElementInstantiate.unity, Assets/HoloToolkit-Examples/UX/Scripts/ExampleData/NoteDataProvider.cs, Assets/HoloToolkit-Examples/UX/Scripts/InteractiveGroup.cs, Assets/HoloToolkit-Examples/UX/Scripts/InteractiveSet.cs
Bugfix for the issue mentioned in https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/1137
=> Use Unity internal GridLayoutGroup (from UI) to position Buttons

Assets/HoloToolkit-Examples/Input/Scenes/KeyboardTest.unity, Assets/HoloToolkit/UX/Prefabs/Keyboard.prefab, Assets/HoloToolkit/UX/Scripts/Keyboard.cs
Overview
Fixed keyboard dictation button - now actually shows some feedback, and recognized text is properly inserted. Some UI enhancements as well
Changes
- Dictation now works
- Dictation button is red when dictation is active
- Keyboard automatically closes after a set time of inactivity
- Includes method to set scaling from the outside by code
- Includes method to set scaling from the outside by code
- Text inside text field is bigger so it's actually readable
- Remove ray cast hit from input field and prevent activation, as this brings up the SYSTEM keyboard in MR (not in HL)
This code is successfully deployed in Walk the World for both HoloLens and Immersive headsets
Fixes #976
=> Enhanced Keyboard, fixed dictation, feedback on dictation actually doing something

Assets/HoloToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs
Overview
---
- Fixes some issues with generating duplicate textures, when we can just reuse the ones we have, and issues where we were multiplying by zero instead of 1.
- Added Windows Phone icon settings back into the generation
=> Tile Generation Update

Assets/HoloToolkit/Utilities/Scripts/Solvers/Solver.cs
=> removed unused local variable

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs
Removed an unused field in the boundary manager
See #1530
=> Removed unused field in boundary manager

Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerInfo.cs, Assets/HoloToolkit/Utilities/Scripts/Solvers/Solver.cs
Fixes errors when targeting and building for Windows Standalone.
See #1530
=> Standalone Build Fixes

Assets/HoloToolkit-Examples/UX/Scenes/InteractiveElementInstantiate.unity, Assets/HoloToolkit-Examples/UX/Scripts/InteractiveGroup.cs
Overview
---
- Set the Grid in inspector/unity file
- Added code to find the grid by name if it is not set (as described in #1577)
- Removed some unused Scaler for Canvas in inspector/unity file
Changes
---
- Fixes: #1577 .
=> Set Grid in inspector, get Grid using code if it is not defined

Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerInfo.cs, ProjectSettings/ProjectSettings.asset
Overview
---
Addresses the Patch Release for MRTK 2017.2.1.0
Changes
---
- Fixed building for Window Standalone.
- Fixed unused field warning in `BoundaryManager`
- Added unity packages from 2017.2.1.0 release
- Added unity packages for 2017.2.1.1 release
=> MRTK 2017.2.1.1 Patch Release

Assets/HoloToolkit-Examples/Input/Materials/HoloToolkit_Focusable.mat, Assets/HoloToolkit-Examples/Input/Prefabs/RecordButton.prefab, Assets/HoloToolkit-Examples/Input/Scenes/DictationTest.unity
Overview
---
Fixed an issue with a material in the Dictation Input Test Scene
=> Dictation Test Scene Fix

Assets/MixedRealityToolkit-Examples/Input/Scenes/CanvasUiRaycasts.unity, Assets/MixedRealityToolkit-Examples/Input/Scripts/DictationRecordButton.cs, Assets/MixedRealityToolkit-Examples/SpatialUnderstanding/Scripts/SpaceVisualizer.cs, Assets/MixedRealityToolkit-Examples/SpatialUnderstanding/Scripts/UI.cs, Assets/MixedRealityToolkit/BuildAndDeploy/Editor/SceneSettingsWindow.cs, Assets/MixedRealityToolkit/InputModule/Scripts/Editor/CanvasEditorExtension.cs, Assets/MixedRealityToolkit/InputModule/Scripts/Editor/CanvasEditorExtension.cs.meta, Assets/MixedRealityToolkit/InputModule/Scripts/Focus/FocusManager.cs, Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/DictationInputManager.cs, Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/CanvasHelper.cs, Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/CanvasHelper.cs.meta, Assets/MixedRealityToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDllTopology.cs, Assets/MixedRealityToolkit/UX/Scripts/Keyboard/KeyboardManager.cs
Latest changes from Dev branch.
=> Merge Dev branch into Namespace Refactor.

Assets/MixedRealityToolkit-Examples/MotionControllers-GrabMechanics/README.md, Roadmap.md
=> Update Dev branch with docs updates

Assets/MixedRealityToolkit/BuildAndDeploy/Editor/BuildSLNUtilities.cs, Assets/MixedRealityToolkit/Utilities/Scripts/Editor/SetIconsWindow.cs, Assets/MixedRealityToolkit/Utilities/Scripts/Tagalong.cs
Overview
---
Replicating future proof fixes from Stabalisation
Changes
---
* Tagalong - fix destroyobject -> destroy
* BuildsNSLUtilities - fix build return text
* SetIconsWindow - remove redundant image types
=> Replicating future proof fixes from Stabalisation

Assets/MixedRealityToolkit-Examples/SpatialMapping/Scripts/PlaneFindingTest.cs, Assets/MixedRealityToolkit/UX/Scripts/Buttons/Profiles/ButtonIconProfile.cs, Assets/MixedRealityToolkit/UX/Scripts/Buttons/Profiles/ButtonIconProfileTexture.cs, Assets/MixedRealityToolkit/UX/Scripts/Buttons/Utilities/CompoundButtonIcon.cs
Overview
---
This updates button icon profile textures to allow selection of 'empty' button textures. (The original vetting method was slightly confusing.)
Fixes #1724
=> CompountButton Icon Profile Change

Assets/HoloToolkit-Examples/Input/Scripts/DictationRecordButton.cs, Assets/HoloToolkit-Examples/Input/Scripts/PopupMenu.cs, Assets/HoloToolkit-Examples/Input/Scripts/RotateMinMax.cs, Assets/HoloToolkit-Examples/Input/Scripts/XboxControllerHandlerTest.cs, Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scripts/BaseUsable.cs, Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scripts/Grabber.cs, Assets/HoloToolkit-Examples/MotionControllers-GrabMechanics/Scripts/RotatableObject.cs, Assets/HoloToolkit-Examples/Sharing/SharingService/Scripts/SyncObjectSpawner.cs, Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/UNetSharedHologram.cs, Assets/HoloToolkit-Examples/Utilities/Scripts/CheckApiTest.cs, Assets/HoloToolkit/Boundary/Scripts/BoundaryManager.cs, Assets/HoloToolkit/Input/Scripts/InputSources/XboxControllerInputSource.cs, Assets/HoloToolkit/Input/Scripts/Utilities/Interactions/CustomInputSelector.cs, Assets/HoloToolkit/Input/Scripts/Utilities/Managers/MixedRealityTeleport.cs, Assets/HoloToolkit/Input/Scripts/Utilities/MotionControllerVisualizer.cs, Assets/HoloToolkit/Sharing/Scripts/Utilities/ManualIpConfiguration.cs, Assets/HoloToolkit/SharingWithUNET/Scripts/GenericNetworkTransmitter.cs, Assets/HoloToolkit/SpatialMapping/Scripts/SpatialMappingObserver.cs, Assets/HoloToolkit/UX/Scripts/Buttons/ButtonIconProfileTexture.cs, Assets/HoloToolkit/UX/Scripts/Buttons/CompoundButtonIcon.cs, Assets/HoloToolkit/UX/Scripts/CapsLockHighlight.cs, Assets/HoloToolkit/UX/Scripts/Lines/LineObjectFollower.cs, Assets/HoloToolkit/UX/Scripts/SymbolDisableHighlight.cs, Assets/HoloToolkit/Utilities/Scripts/AdaptiveQuality/AdaptiveViewport.cs, Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/GLTFComponent.cs, Assets/HoloToolkit/Utilities/Scripts/SceneLauncher.cs, Assets/HoloToolkit/Utilities/Scripts/SphereBasedTagalong.cs
Overview
---
Resolved all "warnings" in the Stabalisation branch raised during build
Changes
---
Code warnings be gone
=> Stabilization clean up warnings

Assets/MixedRealityToolkit-Examples/Input/Scripts/HapticsTest.cs, Assets/MixedRealityToolkit-Examples/SharingWithUNET/Scripts/PlayerController.cs, Assets/MixedRealityToolkit/Boundary/Scripts/BoundaryManager.cs
Overview
---
Updates the debug log from a SharingWithUNET component to be correct.
Reverts the addition of `requiredComponent: ` from `HapticsTest` which was preventing the editor from working.
Updates the `TryGetGeometry` call in `BoundaryManager` to actually return something in WMR.
Changes
---
- Fixes: #1679
=> A few more small bug fixes

Roadmap.md
=> Updated Roadmap

Assets/HoloToolkit/SharingWithUNET/Scripts/UNetAnchorManager.cs
=> Make Spatial Mapping optional when Finding Anchor Position

Assets/MixedRealityToolkit-UnitTests/Editor/Utilities/Extensions/GameObjectExtensionsTests.cs, Assets/MixedRealityToolkit-UnitTests/Editor/Utilities/Extensions/TransformExtensionsTests.cs, Assets/MixedRealityToolkit/Common/Scripts/Extensions/TransformExtensions.cs, Assets/MixedRealityToolkit/Common/Scripts/Singleton.cs
Overview
---
Fixed broken unit tests:
- Input Unit Tests did not pass bc of Singleton update.
Changes
---
- Fixes: #1788
=> Unit Tests Fixes

Assets/MixedRealityToolkit-Examples/UX/Prefabs/ButtonHolographic.prefab, Assets/MixedRealityToolkit-Examples/UX/Scenes/InteractableObjectExample.unity, Assets/MixedRealityToolkit-Examples/UX/Scenes/ObjectCollectionExample.unity, Assets/MixedRealityToolkit/UX/Profiles/HolographicButtonMeshProfile.asset
Overview
---
Updated button and toolbar control examples in [InteractableObjectExample ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_InteractableObjectExample.md)and [ObjectCollectionExample ](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit-Examples/UX/Readme/README_ObjectCollection.md)scene, using new [MRTK/Standard shader.](https://github.com/Microsoft/MixedRealityToolkit-Unity/blob/Dev_Working_Branch/Assets/MixedRealityToolkit/Common/Shaders/Standard.shader) 
Video:
https://gfycat.com/PlushUglyCattle
=> UX controls example updated with new MRTK/Standard Shader

Assets/MixedRealityToolkit/InputModule/Scripts/Focus/FocusManager.cs
Added unregister pointer method.
Added asserts to verify we're not registering or unregistering the gaze pointer improperly.
=> Updated the pointer registration.

Assets/HoloToolkit-Examples/UX/Prefabs/ButtonTraditional.prefab
The ButtonTraditional prefab was using an old 3DTextPrefab, and wasn't using the new standard text shader
=> Updated ButtonTraditional prefab

Assets/HoloToolkit-Examples/UX/Scripts/Controls/SliderGestureControl.cs, Assets/HoloToolkit/Utilities/Scripts/UnityEventFloat.cs, Assets/HoloToolkit/Utilities/Scripts/UnityEventFloat.cs.meta
Overview
---
Allows for value to be sent when invoking **OnUpdateEvent** method.
Changes
---
Can Specify a method that accepts a float
Previous behavior works correctly (specifying a method and supplying a value)
- Fixes: #1760 .
=> Send Slider Value on Update - Stabilization

Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/Interactions/TwoHandManipulatable.cs
* Bug in TwoHandManipulatable that threw a error when you didn't set a BoundingBox prefab
* Added public ```BoundingBoxPrefab```
* Added ```SetManipulationMode```
=> Updated TwoHandManipulatable

Assets/MixedRealityToolkit/UX/Scripts/AppBar/AppBar.cs
Overview
---
Fixed an issue with building for the standalone player.
Misc formatting.
=> App Bar Build Fixes

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
Overview
---
Added ability to build out of the box without creating a wsa cert.
Changes
---
- Fixes: #1951
=> Patch4 build window fix

ProjectSettings/EditorBuildSettings.asset
Overview
---
Removed scene from editor build settings. Incorrectly added in #1839.
=> [Dev] Removed scene from editor build settings

Assets/MixedRealityToolkit-Examples/UX/Models/Buttons.FBX.meta, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/Black.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/BlackWindow.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/ClearWindow.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/Default.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/Gold.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/GreenGas.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/RedLight.mat, Assets/MixedRealityToolkit-Examples/UX/Models/Materials/WhiteLight.mat, Assets/MixedRealityToolkit-Examples/UX/Models/TheModule.fbx.meta, Assets/MixedRealityToolkit-Examples/UX/Scenes/TooltipExamples.unity, Assets/MixedRealityToolkit/UX/Prefabs/ToolTip.prefab
Overview
---
Mostly, this turns off automatic material import for TheModule.fbx and converts all already imported materials to use the Toolkit's Standard shader.
Also, some settings were not properly saved/updated in the prefab/scene files.
=> [Dev] Cleanup tooltip scene

CodingGuidelines.md
Overview
---
Fixed the typos raised by @keveleigh
Changes
---
- Fixes: typographic errors when viewing the rings of Saturn through an elliptical plane
=> Mrtk version next coding standards typo

Assets/HoloToolkit/Utilities/Scripts/Editor/ProjectSettingsWindow.cs
This change adds a checkbox (selected by default) to the Apply Mixed Reality Project Settings dialog.
When selected, layer 31 is checked to see if it is in use (with a name other than Spatial Mapping) and if not, sets the layer name to "Spatial Mapping". If we are able to set the layer, the Spatial Perception capability is also set (setting the layer implies it will be used).
If we fail to set the layer (the preparation code fails, or layer 31 has a name that implies it is in use, a message is displayed stating that we failed and that the user should check Tags & Layers in the inspector.
- Fixes: #1443.
- Fixes: #1770
=> add option to set default spatial mapping layer

Assets/MixedRealityToolkit/BuildAndDeploy/Editor/ProjectSettingsWindow.cs
Port of the may18_dev branch change #1991 to Dev_Working_Branch.
This fixes #1998
=> [Dev_Working] Set Default Spatial Mapping Layer in the Project Settings Dialog

Assets/MixedRealityToolkit/InputModule/Prefabs/Cursor/Cursor.prefab, Assets/MixedRealityToolkit/InputModule/Prefabs/Cursor/CursorWithFeedback.prefab, Assets/MixedRealityToolkit/Utilities/Scripts/Billboard.cs
Overview
---
Some minor updates that were found while updating the Academy courses to the most recent Toolkit release.
Partner PR to #2035.
Changes
---
- Fixes: #1983.
=> [Dev] Cursor light fix (and other minor fixes)

Assets/MixedRealityToolkit-Examples/UX/Scripts/Controls/SliderGestureControl.cs, Assets/MixedRealityToolkit/InputModule/Scripts/InputSources/InteractionInputSource.cs, Assets/MixedRealityToolkit/Utilities/Scripts/GLTF/Scripts/Extensions/SchemaExtensions.cs
Overview
---
This PR removes tabs and formats files which previously contained tabs.
Changes
---
- Related to: #2045 .
=> [Dev] Removing tabs

Assets/HoloToolkit-Examples/UX/Scripts/Controls/SliderGestureControl.cs, Assets/HoloToolkit/SpatialMapping/Scripts/RemoteMapping/SimpleMeshSerializer.cs, Assets/HoloToolkit/SpatialUnderstanding/Scripts/SpatialUnderstandingDll.cs, Assets/HoloToolkit/UX/Scripts/Buttons/ButtonIconProfileTexture.cs, Assets/HoloToolkit/UX/Scripts/CapsLockHighlight.cs, Assets/HoloToolkit/UX/Scripts/SymbolDisableHighlight.cs, Assets/HoloToolkit/Utilities/Scripts/GLTF/Scripts/Extensions/SchemaExtensions.cs, Assets/HoloToolkit/Utilities/Scripts/GpuTiming/GpuTiming.cs, Assets/HoloToolkit/Utilities/Scripts/GpuTiming/GpuTimingCamera.cs, Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverMomentumizer.cs, Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverSurfaceMagnetism.cs
Overview
---
This PR removes tabs and formats files which previously contained tabs.
Changes
---
- Fixes: #2045 .
=> [May] Removing tabs and formatting

CONTRIBUTING.md, CodingGuidelines.md, README.md, Roadmap.md
Update roadmap to reflect how master is currently being managed as well as to add release cadence and branch management updates re: vNext
Contributing modified to describe how to find the correct dev branch for master.
Adapt coding guidelines from vNext.
Closes #2014, #2015, #2038
=> [may18] Documentation updates: roadmap, contributing, coding guidelines

Assets/HoloToolkit-Examples/UX/Readme/README_BoundingBoxGizmoExample.md, Assets/HoloToolkit-Examples/UX/Scripts/BoundingBoxRigActivityExample.cs, Assets/HoloToolkit-Examples/UX/Scripts/BoundingBoxRigActivityExample.cs.meta, Assets/HoloToolkit/Input/README.md, Assets/HoloToolkit/Input/Scripts/InputEventData/BoundingBoxEventData.cs, Assets/HoloToolkit/Input/Scripts/InputEventData/BoundingBoxEventData.cs.meta, Assets/HoloToolkit/Input/Scripts/InputHandlers/IBoundingBoxStateHandler.cs, Assets/HoloToolkit/Input/Scripts/InputHandlers/IBoundingBoxStateHandler.cs.meta, Assets/HoloToolkit/Input/Scripts/Utilities/Managers/InputManager.cs, Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxRig.cs
Overview
---
Dev_Working_Branch recently took a change to allow applications to handle when bounding boxes activate and deactivate.
Bringing this change into the 2017.4.0.0 (may '18) release
Changes
---
- Fixes: #2037.
=> [May18] Port BoundingBox activated events from the dev branch

Assets/MixedRealityToolkit/UX/Scripts/Buttons/Button.cs
Same change as may18_dev branch (replace <= with >).
- Fixes: #1887.
=> fix #1887, dev branch

Assets/MixedRealityToolkit/InputModule/Scripts/Utilities/ControllerFinder.cs
bring the null reference exception fix from the may18 branch to dev
Fixes: #2053
=> dev branch version of the fix for #2053

Assets/HoloToolkit-Examples/UX/Prefabs/ButtonHolographic.prefab, Assets/HoloToolkit/UX/Prefabs/Buttons/HolographicButton.prefab
Overview
---
Removing unused Animation script & animation in HolographicButton prefab
Changes
---
- Fixes: #2019
=> [may18] Removing unused Animation script & animation in HolographicButton prefab

Assets/MixedRealityToolkit-Examples/UX/Prefabs/ButtonHolographic.prefab, Assets/MixedRealityToolkit/UX/Prefabs/Buttons/HolographicButton.prefab
Overview
---
Removing unused Animation script & animation in HolographicButton prefab
Changes
---
- Fixes: #2019
=> [Dev] Removing unused Animation script & animation in HolographicButton prefab

Assets/HoloToolkit/UX/Scripts/BoundingBoxes/BoundingBoxGizmoHandle.cs
Overview
---
I made a mess of the last PR (#2086) .... please forgive.
Changes
Clean up PR history. Addresses #2009
=> Fix broken PR for BoundingBoxRigHandle exception

Assets/MixedRealityToolkit/UX/Scripts/BoundingBoxes/BoundingBoxGizmoHandle.cs
Port bounding box handle exception prevention fix from may18_dev to the dev branch
=> port #2105 to dev branch

Assets/HoloToolkit-Examples/UX/Scenes/TooltipExamples.unity
Overview
---
Updated the position of the labels in ToolTip example scene.
Changes
---
- Fixes: #2157
=> [May18] Updating tooltip label position.

UpgradeGuide.md
Updates to UpgradeGuide.md.
Fixes: #2062 .
=> new upgrade guide (#2062)

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityConfigurationProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefualtMixedRealityInputActionsProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefualtMixedRealityInputActionsProfile.asset.meta, Assets/MixedRealityToolkit-SDK/Profiles/DefualtMixedRealitySpeechCommandsProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefualtMixedRealitySpeechCommandsProfile.asset.meta, Assets/MixedRealityToolkit/InputSystem/Focus/FocusProvider.cs, Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/InputAction.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputActionsProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealitySpeechCommandsProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealitySpeechCommandsProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/RotationConstraintType.cs.meta, Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions.meta, Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions/EditorClassExtensions.asmdef, Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions/EditorClassExtensions.asmdef.meta, Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs, Assets/MixedRealityToolkit/_Core/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/CanvasEditorExtension.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/Inspectors.asmdef, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityBaseConfigurationProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealitySpeechCommandsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
- Fixed SystemType drawer to also show structs as well as classes.
- Updated inspector to shorten the namespace of the currently selected type.
=> Fixed some issues with profile configs

ProjectSettings/ProjectSettings.asset
- Project version is only temporary until we agree upon a final release candidate.
=> updated a few project settings

Assets/MixedRealityToolkit-Tests/MixedRealityManagerTests.cs, Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityBaseConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityManagerInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealitySpeechCommandsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
Made a few improvements to the way we handle how to query if an active profile is set and how to deal with it.
=> Mixed Reality Manager Update

Assets/MixedRealityToolkit/_Core/Definitions/Handedness.cs
Overview
---
Values were wrong, and added Both enum.
=> Fixed some issues with handedness declarations.

Assets/HoloToolkit/BuildAndDeploy/Editor/BuildDeployWindow.cs
=> Build Window fix for IL2CPP Targets

Assets/MixedRealityToolkit-SDK/Models.meta
=> added missing meta file for models folder

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityInputActionsProfile.asset, Assets/MixedRealityToolkit/_Core/Extensions/MathfExtensions.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealitySpeechCommandsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs.meta
- Added input action drawer so handler's have easy way to implement and set Input Actions.
- Updated Input Action Config profile to include an axis constraint.
=> Input Action Drawer for Handlers

Assets/MixedRealityToolkit/InputSystem/Cursors/AnimatedCursor.cs, Assets/MixedRealityToolkit/_Core/Attributes/SystemTypeAttribute.cs, Assets/MixedRealityToolkit/_Core/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/AnimatedCursorData.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/KeywordAndResponse.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/AnimatorParameter.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SystemType.cs, Assets/MixedRealityToolkit/_Core/Extensions/NetNativeReflectionExtensions.cs, Assets/MixedRealityToolkit/_Core/Extensions/NetNativeReflectionExtensions.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs, ProjectSettings/ProjectSettings.asset
Overview
---
- (Begrudgingly) Ported support for .NET Native building.
- Cleaned up build warnings.
- Fixed an issue where the IL2CPP/.NET switch in the build windows did not properly switch after folder delete prompt.
=> vNEXT .NET Native build support.

Assets/MixedRealityToolkit-SDK/Features/Input/SpeechInputHandler.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/Devices/MixedRealityControllerMappingProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputActionsProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealitySpeechCommandsProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityBaseConfigurationProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityControllerMappingProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityInputActionsProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityManagerInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealitySpeechCommandsProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Interfaces/IMixedRealityManager.cs.meta, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs.meta, Assets/MixedRealityToolkit/_Core/Utilities/EditorSetup/IconEditor.cs
Overview
---
added ability to either skip or target specific partial name's for assets when assigning icons.
=> MRTK Icon Manager filtering

Assets/HoloToolkit-Examples/Prototyping/Scripts/MoveToPosition.cs
Overview
---
MoveToPosition was setting its own transform instead of the TargetObject's transform.
Changes
---
- Fixes: #2300.
=> fix MoveToPosition.TargetObject

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityCameraProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityCameraProfile.asset.meta, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityConfigurationProfile.asset, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityCameraProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityCameraProfile.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityCameraProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityCameraProfileInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
Updated Mixed Reality Camera Manager to be a configurable profile
=> Updated Mixed Reality Camera Manager to be a configurable profile

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityInputActionsProfile.asset, Assets/MixedRealityToolkit-Tests/InteractionDefinitionTests.cs, Assets/MixedRealityToolkit/InputSystem/Cursors/BaseCursor.cs, Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/InputSystem/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit/InputSystem/Sources/DictationInputSource.cs, Assets/MixedRealityToolkit/InputSystem/Sources/InteractionInputSources.cs, Assets/MixedRealityToolkit/InputSystem/Sources/SpeechInputSource.cs, Assets/MixedRealityToolkit/InputSystem/Sources/TouchscreenInputSource.cs, Assets/MixedRealityToolkit/_Core/Definitions/Devices/InteractionMapping.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputActionsProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/AxisType.cs, Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/BaseInputEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/DictationEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/InputEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/InputPressedEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/ManipulationEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/MixedRealityPointerEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/NavigationEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/SixDoFInputEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/SourceStateEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/SpeechEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/ThreeDoFInputEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/TwoDoFInputEventData.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityInputSystem.cs, ProjectSettings/ProjectVersion.txt
- Refactored InputSystem to accept custom InputAction types.
- Now all raised events require an InputAction as a parameter.
- Cleaned up IMixedRealityInputSystem.
- Removed the default pointer from the input action configuration profile.
=> vNEXT Input System Refactoring and Cleanup

Assets/HoloToolkit-Preview/SpectatorView/README.md
github image links are case-sensitive.
=> Fix image links

.gitignore, Assets/MixedRealityToolkit-Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit-Examples/MixedReality.Toolkit.Examples.nuspec.meta, Assets/MixedRealityToolkit-SDK/MixedReality.Toolkit.SDK.nuspec, Assets/MixedRealityToolkit-SDK/MixedReality.Toolkit.SDK.nuspec.meta, Assets/MixedRealityToolkit-Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit-Tests/MixedReality.Toolkit.Tests.nuspec.meta, Assets/MixedRealityToolkit/MixedReality.Toolkit.nuspec, Assets/MixedRealityToolkit/MixedReality.Toolkit.nuspec.meta, README.md, build.ps1
Overview
---
Adds metadata and a build script to package up the repo into NuGet and Unity packages.
=> Automation script for build process.

Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs
we also needed to check if the input system type was null as well
=> Mixed Reality Manager Tests fix

Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IBaseRayStabilizer.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IBaseRayStabilizer.cs.meta, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/ICursorModifier.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/ICursorModifier.cs.meta, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IPointerResult.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IPointerResult.cs.meta, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/ITeleportTarget.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/ITeleportTarget.cs.meta
Input system now properly cleans itself from the scene when Destroyed.
Moved a few interfaces into their own classes.
=> Made sure that the input system cleans itself up properly.

Assets/HoloToolkit/UX/Scripts/Buttons/Button.cs, Assets/HoloToolkit/UX/Scripts/Buttons/ButtonEnums/ButtonStateEnum.cs
Overview
---
Cleans up Button.cs a bit, in preparation for a fix for #1879 incoming after merge.
Changes
---
- First PR towards a fix for #1879 (splitting up into smaller PRs for review ease).
=> Button.cs documentation and formatting updates

Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs
properly cleanup ui raycast camera when we disable input system.
=> properly cleanup ui raycast camera when we disable input system.

Assets/MixedRealityToolkit/InputSystem/Focus/FocusProvider.cs, Assets/MixedRealityToolkit/InputSystem/Gaze/GazeProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/CameraCache.cs
- Added null check assert for main camera tag in `CameraCache.Main`.
- (This should probably be backported into master as well.)
- Added asserts in Gaze and Focus Providers for MR Manager and Input System.
=> Added asserts for things

Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityController.cs
cleaned up comments and field names a bit as well.
=> Added device position updates for WMR controller.

Assets/MixedRealityToolkit/_Core/EventDatum/Input/SourcePoseEventData.cs
Fixes #2372 MixedRealityPosePose  -> MixedRealityPose
=> Fixed typo

Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityStandardShaderGUI.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityStandardShaderGUI.cs.meta, Assets/MixedRealityToolkit/_Core/Resources/Shaders/MixedRealityStandard.shader, Assets/MixedRealityToolkit/_Core/Resources/Shaders/MixedRealityStandard.shader.meta
Overview
---
Ported Standard Shader and GUI from master.
=> Ported Standard Shader and GUI from master.

Assets/MixedRealityToolkit/InputSystem/Focus/FocusProvider.cs, Assets/MixedRealityToolkit/InputSystem/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IPointerResult.cs
Reorganized focus provider a bit and moved documentation to the interface.
=> Updated some docs focused around focus provider and pointers.

Assets/HoloToolkit-Examples/SharingWithUNET/Scripts/PlayerController.cs
Overview
---
From original PR:
>Updates the debug log from a SharingWithUNET component to be correct.
Changes
---
- Fixes #1679 
- Migrates over #1748
- Related to #2423
=> PlayerController.cs updates from Dev

Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Animations/RoundedCorner.anim, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/CubeBorderRoundedOpaque.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/CubeEnvironmentColor.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorder.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderBlue.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderCyan.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderGreen.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderOrange.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderPink.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderPurple.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderRed.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/PanelBorderRoundedBlue.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/ShaderBallGlass.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/ShaderBallNearPlaneFade.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/ShaderBallNormalMap.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Materials/ShaderBallNormalMapTransparent.mat, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Prefabs/Placard.prefab, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Scenes/MaterialGallery.unity, Assets/MixedRealityToolkit/_Core/Inspectors/HoverLightEditor.cs, Assets/MixedRealityToolkit/_Core/Inspectors/HoverLightEditor.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityStandardShaderGUI.cs, Assets/MixedRealityToolkit/_Core/Resources/Fonts/selawk.ttf.meta, Assets/MixedRealityToolkit/_Core/Resources/Fonts/selawkb.ttf.meta, Assets/MixedRealityToolkit/_Core/Resources/Fonts/selawkl.ttf.meta, Assets/MixedRealityToolkit/_Core/Resources/Fonts/selawksb.ttf.meta, Assets/MixedRealityToolkit/_Core/Resources/Fonts/selawksl.ttf.meta, Assets/MixedRealityToolkit/_Core/Resources/Shaders/MixedRealityStandard.shader, Assets/MixedRealityToolkit/_Core/Utilities/UX/Billboard.cs, Assets/MixedRealityToolkit/_Core/Utilities/UX/Billboard.cs.meta, Assets/MixedRealityToolkit/_Core/Utilities/UX/HoverLight.cs
Overview
---
Brings over the partial branching removal from June and general improvements from Dev/June.
Changes
---
- Migrates #2363
- Migrates #2424
=> Port shader updates from Dev_Working_Branch and June

Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/BaseInputHandler.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/BaseInputHandler.cs.meta, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/InputSystemGlobalListener.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/InputSystemGlobalListener.cs.meta, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/PointerClickHandler.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/PointerClickHandler.cs.meta, Assets/MixedRealityToolkit-SDK/Features/Input/Scripts/SpeechInputHandler.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/BaseInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/BaseInputHandlerInspector.cs.meta, Assets/MixedRealityToolkit-SDK/Inspectors/Input/PointerClickHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/PointerClickHandlerInspector.cs.meta, Assets/MixedRealityToolkit-SDK/Inspectors/Input/SpeechInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityConfigurationProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerConfigurationProfile.asset, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityInputActionsProfile.asset, Assets/MixedRealityToolkit/InputSystem/Focus/FocusProvider.cs, Assets/MixedRealityToolkit/InputSystem/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit/InputSystem/Utilities/HandDraggable.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/InputActionEventPair.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/InputActionEventPair.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputAction.cs, Assets/MixedRealityToolkit/_Core/Definitions/Physics/FocusDetails.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/Handlers/IMixedRealityPointerHandler.cs, ProjectSettings/QualitySettings.asset
Overview
---
- Added input system global listener helper component to SDK.
- Added Pointer Click Handler component to SDK.
- Updated Speech Input Handler SDK component.
- Updated FocusDetails to use properties.
- Updated MixedRealityInputActions to use equality and == operator for easier comparison.
- Updated Quality Settings from Unity Editor update
=> Some Input System Feature SDK components.

Assets/HoloToolkit-Examples/UX/Scenes/SliderSamples.unity
Overview
---
Two of the sliders had multiple Billboard scripts.
=> Removed extra Billboards from SliderSamples scene

CodingGuidelines.md
Overview
---
Adds C# code highlighting when viewed on GitHub.
Adds a section on platform dependent compilation.
Formats and cleans up the markdown.
Changes
---
- Fixes: #2143
=> CodingGuidelines formatting and adding platform dependent compilation

Assets/HoloToolkit/Utilities/Scripts/Editor/SceneSettingsWindow.cs
Overview
---
Adds an optional setting to the scene configuration window to quickly add the SpatialMapping prefab to the scene.
Changes
---
- Fixes #2203
=> Add "Add the Spatial Mapping Prefab" to the scene configuration window

Assets/MixedRealityToolkit-Examples/License.txt, Assets/MixedRealityToolkit-Examples/Version.txt, Assets/MixedRealityToolkit-SDK/License.txt, Assets/MixedRealityToolkit-SDK/Version.txt, Assets/MixedRealityToolkit-Tests/License.txt, Assets/MixedRealityToolkit-Tests/Version.txt, Assets/MixedRealityToolkit/License.txt, Assets/MixedRealityToolkit/Version.txt, License.txt
Overview
---
Added Version.txt file containing the following: Mixed Reality Toolkit <package subname> <version> to each root level package folder (ex: Assets\MixedRealityToolkit).
Add license.txt from the repository root to the packages roots.
- Fixes: #1858  .
=> Add version files (semver) and propogate license to package roots

Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/MixedRealityPosePropertyDrawer.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/MixedRealityPosePropertyDrawer.cs.meta
=> pose property drawer

Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDeviceManager.cs
Overview
---
Resolves an issue where source detected events were not raised
Changes
---
- Fixes: SourceDetected event was not being raised when it should have
=> Resolves an issue where source detected events were not raised

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Controllers/MixedRealityControllerVisualizer.cs
=> Controller visualizer cleanup

Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Controllers/MixedRealityControllerVisualizer.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityConfigurationProfile.asset, Assets/MixedRealityToolkit/_Core/Definitions/MixedRealityConfigurationProfile.cs, Assets/MixedRealityToolkit/_Core/Devices/BaseController.cs, Assets/MixedRealityToolkit/_Core/Inspectors/CanvasEditorExtension.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
- Updated some issues with setting world space on canvas and no MR Manager in scene.
- Updated Input System initialization to be a bit smarter.
- Updated usages of `ActiveProfile` null checks  to `HasActiveProfile`
- Updated usages of individual feature profile checks to `Enable<FeatureName>`
=> vNEXT - Misc Bug Fixes

Assets/MixedRealityToolkit/_Core/Devices/OpenVR/OpenVRDeviceManager.cs
- Create `GenericOpenVRController` based on type
=> Simplified type creation

Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs
Overview
---
adds a body to the camera if none exists.
fixes issue with pointer null refs
=> Input System Body Check.

Assets/MixedRealityToolkit-Examples/Demos/Boundary/Scenes/BoundaryVisualization.unity
Overview
---
This was done in a previous PR but has since been overwritten.
=> Re-add default cursor to BoundaryVisualization scene

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/BaseInputHandler.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/DragAndDropHandler.cs, Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/SpeechInputHandler.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Controllers/MixedRealityControllerVisualizer.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/CursorModifier.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/LinePointer.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/ParabolicTeleportPointer.cs, Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs, Assets/MixedRealityToolkit/_Core/EventDatum/GenericBaseEventData.cs, Assets/MixedRealityToolkit/_Core/Extensions/BoundsExtensions.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/EdgeUtilities.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/ParabolaConstrainedLineDataProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/ParabolaLineDataProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/RectangleLineDataProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/DataProviders/SimpleLineDataProvider.cs, Assets/MixedRealityToolkit/_Core/Utilities/Lines/LineFollower.cs, Assets/MixedRealityToolkit/_Core/Utilities/Physics/Distorters/Distorter.cs, Assets/MixedRealityToolkit/_Core/Utilities/Physics/Interpolator.cs, Assets/MixedRealityToolkit/_Core/Utilities/Physics/Solvers/Solver.cs, Assets/MixedRealityToolkit/_Core/Utilities/Physics/Solvers/SolverHandler.cs, Assets/MixedRealityToolkit/_Core/Utilities/WindowsDevicePortal/DataStructures/DeviceInfo.cs
Overview
---
Quick (probably incomplete) spellcheck pass pre-alpha
=> Quick (probably incomplete) spellcheck pass pre-alpha

Assets/MixedRealityToolkit-SDK/Features/Teleportation/MixedRealityTeleportManager.cs
Overview
---
Fixes an issue where the teleport system doesn't properly clean up after itself.
=> Cleaned up event system if teleport system creates one.

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBaseConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
Overview
---
Updated profile inspectors to live in the proper namespace that corresponds to their folder location.
=> Profile inspector namespace cleanup.

Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/MixedRealityControllerVisualizerInspector.cs.meta
=> updated missing icon

Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/InputActionPropertyDrawer.cs
Overview
---
Fixed an issue where the property drawer actions would get out of sync when input action profile is changed.
=> Input Action Property Drawer Fix

Assets/MixedRealityToolkit-SDK/Features/Teleportation/MixedRealityTeleportManager.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs
=> Initialized some vars to remove build warnings

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs
Overview
---
Removed some unused code that was causing the header to be out of place
Was:
Now:
=> Updated Input Action Header.

Assets/MixedRealityToolkit-Examples/Demos/Boundary/Scenes/BoundaryVisualization.unity
Overview
---
The guid reference to the DefaultCursor prefab in the BoundaryVisualization scene was stale.
=> Update cursor guid in BoundaryVisualization to the new guid

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Overview
---
Updated valid calculation up direction
Updated distance calculation used when rendering line.
Changes
---
- Fixes: #2591
=> Fixed teleporting when no hit is found.

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityControllerConfigurationProfile.asset, Assets/MixedRealityToolkit/_Core/Definitions/Devices/MixedRealityInteractionMapping.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/Editor/InvertAxesEnum.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/Editor/InvertAxesEnum.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs
- Added `InvertXAxis` property
Helps with #2610
=> Add InvertXAxis 

Assets/MixedRealityToolkit/_Core/Resources/Textures/OculusRemoteController_white_scaled.png.meta
Overview
---
#2654 was missing a meta file.
=> Adding missing meta file from #2654

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs
Updated controller model inspector to display a dialog when the model is missing a pose synchronizer component.
We can't add the component automatically bc it's an SDK layer component, and users may have their own implementation they'd like to use.
If the user accepts the dialog the model prefab is selected, so the user can add the component immediately.
=> Controller Profile Inspector: Warning when model is missing pose synchonizer

Assets/MixedRealityToolkit/_Core/Resources/Textures/MRTK_Logo_Black.png.meta, Assets/MixedRealityToolkit/_Core/Resources/Textures/OculusRemoteController_white_scaled.png.meta
Updated image to be a sprite and updated settings.
=> Fixed oculus remote texture settings

Assets/MixedRealityToolkit/_Core/Utilities/Editor/Setup/EnforceEditorSettings.cs
Overview
---
- Updates icons to match the current editor theme
=> Themed Icons

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
Overview
---
Added a button to get back to the main config profile
Changes
---
- Fixes: #2692
=> Added button to get back to main config profile

Assets/MixedRealityToolkit-SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs, Assets/MixedRealityToolkit-SDK/Features/Input/MixedRealityInputManager.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/SourcePoseEventData.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/Handlers/IMixedRealitySourcePoseHandler.cs
Overview
---
Updated the Source State Events to be more generic like the Input Source Events
=> Updated Source State Events to be more generic

Assets/MixedRealityToolkit-SDK/Features/Input/FocusProvider.cs
Overview
---
Fixed an issue where Focus Provider was not registering pointers for input sources that were already detected by the time our Focus Provider is started.
=> Focus Provider Registration Fix

Assets/MixedRealityToolkit/_Core/Definitions/Utilities/MixedRealityPose.cs
Overview
---
So you can pretty print it in the console
=> Added Mixed Reality Pose to string override

Assets/MixedRealityToolkit-SDK/Features/UX/Animations/Cursors/DefaultCursor/DefaultCursor.controller, Assets/MixedRealityToolkit-SDK/Features/UX/Meshes/Cursors/DefaultCursor.fbx.meta, Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Cursors/DefaultCursor.prefab, Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Cursors/TeleportCursor.prefab
Overview
---
- Updated Teleport Cursor to properly be on ignore raycast layer.
- Fixed DefaultCursor being "Pointy" by making sure the prefab is setup exactly like HTK
- Reset import scale
- Fixed state setting in animation controller
=> Fixed Cursors

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs
Overview
---
See https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2701#issuecomment-419513705
=> made gaze provider start virtual for proper overriding

Documentation/Architecture/Boundary_System/Boundary_System.md, Documentation/Architecture/Core_System/Core.md, Documentation/Architecture/Input_System/Input_System.md, Documentation/Architecture/Readme.md, Documentation/Architecture/Teleport_System/Teleport_System.md
Overview
---
Added some stub files for upcoming documentation
=> Added initial docs for architecture

Assets/MixedRealityToolkit/_Core/Devices/VoiceInput/WindowsDictationInputDeviceManager.cs
Overview
---
Fixed some issues with dictation manager lagging the editor when exiting play mode.
=> Dictation Device Manager Update

Assets/HoloToolkit-Examples/Utilities/Prefabs/SolverExample/OrbitalBodyLocked.prefab, Assets/HoloToolkit-Examples/Utilities/Prefabs/SolverExample/OrbitalBodyLocked.prefab.meta, Assets/HoloToolkit-Examples/Utilities/Prefabs/SolverExample/WristWrapper.prefab, Assets/HoloToolkit-Examples/Utilities/Scenes/SolverExamples.unity, Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverBodyLock.cs, Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverOrbital.cs, Assets/HoloToolkit/Utilities/Scripts/Solvers/SolverOrbital.cs.meta
This pull request creates an orbital solver to replace the body locked solver. The Orbital Solver fixes numerous issues with using the Body Locked solver, rotation issues, bad messaging, non-working features, and more.
Details are available at this proposal:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2250
=> created an orbital solver as an improved replacement to body lock solver

Assets/MixedRealityToolkit/_Core/Utilities/PlatformUtility.cs
Overview
---
The existing platform check had an early out that didn't quite feel right to me after going back and looking at it again.
There was also multiple very specific checks for individual flags values.
Modified the code to be easier to manage in the future
- add to the SupportedPlatforms enum
- update the conversion methods
=> simplify the platform check logic, make it easier to extend

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityRegisteredComponentsProfile.asset
Overview
---
spatial mouse still needs some work. Opt-in for now.
=> removed spatial mouse for now

Assets/MixedRealityToolkit-SDK/Features/Input/GazeProvider.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Pointers/ParabolicPointer.prefab, Assets/MixedRealityToolkit-SDK/Features/UX/Prefabs/Pointers/TouchPointer.prefab, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs, Assets/MixedRealityToolkit-SDK/Inspectors/UX/Pointers/BaseControllerPointerInspector.cs, Assets/MixedRealityToolkit/_Core/Interfaces/InputSystem/IMixedRealityCursor.cs
Overview
---
Cherry picked changes from Gesture PR
Fixes #2749 
Fixes #2752
=> Teleport Cursor Fix

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
=> Remove warning from BaseCursor

Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/BaseInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs, Assets/MixedRealityToolkit/_Core/Managers/BaseManager.cs, Assets/MixedRealityToolkit/_Core/Managers/MixedRealityManager.cs
- The ternary operator was a bit difficult to read, so I simplified it and removed the redundant else.
- Also added the teleport system to core managers.
- Fixed #2748
- Improved Speech Handler to be more resilient when missing Mixed Reality Manager or Speech System.
=> Fixed MixedRealityManager bugs

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Collections/BaseObjectCollection.cs, Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/CollationOrderType.cs, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/OrientationType.cs, Assets/MixedRealityToolkit/_Core/Inspectors/ClipPlaneInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/ControllerPopupWindow.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Data/ControllerInputActionOption.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Data/ControllerInputActionOptions.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityManagerInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityStandardShaderGUI.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBaseConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityRegisteredComponentsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/CanvasEditorExtension.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/EllipseLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/ParabolaPhysicalLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/ParabolicConstrainedLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/RectangleLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/SimpleLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/SplineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Overview
---
Some files had incorrect or old namespaces
=> Updated old or incorrect namespaces

Assets/MixedRealityToolkit/_Core/Utilities/Physics/Distorters/DistorterSimplex.cs
Overview
---
DistorterSimplex now creates more predictable noise in all 3 axis.
Changes
---
- Fixes reported problems with noise distortion behaving strangely or tapering off in line UX controls using DistorterSimplex.
=> Distortion fix

Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/ParabolicConstrainedLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/SimpleLineDataProviderInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Utilities/Lines/DataProviders/SplineDataProviderInspector.cs
Overview
---
No transforming required!
Best part is that it works without a camera in the scene.
Changes
---
- Fixes: https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/2816
=> Fixed line data provider gizmos when MRTK is not configured.

CodingGuidelines.md
Overview
---
- Added expression-bodied member and auto property guidelines.
- Fixed a few spelling errors.
- Added tooltip guidelines
- Added color to the code with c# syntax
=> vNEXT: Updated Coding Guidelines

MRTK-vNext.md
Overview
---
Changes
---
- Fixes: # .
=> clarified some wording with things I've learned over the last week

MRTK-vNext.md
It's in the  Work Roadmap now.
Friend of:
https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/2844
=> removed the task list

Assets/MixedRealityToolkit-SDK/Features/Diagnostics/DiagnosticsHandler.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Diagnostics/DiagnosticsEventData.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs.meta
Overview
---
Found a missing namespace reference (Current dev branch doesn't compile)
Fixed profile locking.
- Fixes: #2864
=> a few more diagnostics changes

Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityPreferences.cs
Overview
---
Editor preferences were not being set properly in MRTK Preferences window.
=> Properly set editor preference.

Assets/MixedRealityToolkit-Examples/Demos/Audio/Scenes/AudioLoFiEffectDemo.unity, Assets/MixedRealityToolkit-Examples/Demos/Audio/Scenes/AudioOcclusionDemo.unity, Assets/MixedRealityToolkit-Examples/Demos/Boundary/Scenes/BoundaryVisualization.unity, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Scenes/MaterialGallery.unity, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Scenes/StandardMaterialComparison.unity, Assets/MixedRealityToolkit-Examples/Demos/StandardShader/Scenes/StandardMaterials.unity, Assets/MixedRealityToolkit-Examples/Demos/UX/Collections/Scenes/ObjectCollectionGallery.unity, Assets/MixedRealityToolkit-Examples/Demos/UX/Lines/Scenes/LineGallery.unity
The content PR that renames Body to MixedRealityPlayspace and Head to Main Camera
=> Body/Head renamed to MixedRealityPlayspace/Main Camera

Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/BaseInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/PointerClickHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs, Assets/MixedRealityToolkit-SDK/Inspectors/MixedRealityToolkit.SDK.Inspectors.asmdef, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/BaseMixedRealityInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/BaseMixedRealityInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBaseConfigurationProfileInspector.cs
Overview
---
Pulled out Mixed Reality Manager Check and added it to base handler inspector to ensure proper setup if component is added before system is configured in the scene.
=> Input Handler Inspector Fix

.gitignore
Overview
---
- Added cert area.
- Added .out folder
- Added *.package (a unity generated file)
=> Updated git ignore definitions

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBaseConfigurationProfileInspector.cs
=> Decreased profile selector button width

Assets/MixedRealityToolkit-SDK/Features/Utilities/Solvers/Overlap.cs, Assets/MixedRealityToolkit-SDK/Features/Utilities/Solvers/Overlap.cs.meta
I keep finding myself recreating this solver in all my projects, so I figured maybe someone else would like it in the toolkit. You can get the same behavior from the right settings in other solvers, but this simplest form takes potential mistakes out of debugging, so I end up using it a lot.
=> Overlap Solver

Roadmap.md
=> Update roadmap for new version scheme

ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt
Overview
---
Updated editor version to 2018.2.13f1
=> Updated editor version to 2018.2.13f1

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs
Overview
---
Added gesture type filter so it's impossible to register the same gesture twice.
Changes
---
- Fixes: #2912
=> Gesture Profile Fixes

ProjectSettings/QualitySettings.asset
Overview
---
Added some missing changes from editor update
=> 2018.2.13f1 missing quality settings changes

Assets/MixedRealityToolkit-Examples/Demos/Solvers/Scripts/SwapVolume.cs.meta, Assets/MixedRealityToolkit-SDK/Inspectors/UX/Pointers/MousePointerInspector.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/Utilities/SolverOrientationType.cs.meta, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/BaseMixedRealityInspector.cs.meta
Overview
---
Updated missing icons
=> updated some missing MRTK icons on some scripts

Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/WindowsGestureSettings.cs
=> updated WinGestSettings summary

Assets/MixedRealityToolkit/_Core/Devices/VoiceInput/WindowsDictationInputDeviceManager.cs
Overview
---
- Cleaned up the dictation input device manager, and removed allocations when starting/stopping recording.
- Also added some safely checks to ensure we're in play mode when recording.
=> Windows Dictation Input Device Update

CodingGuidelines.md
Changed grammatical errors to improve clarity and flow.
=> Fixed grammatical errors

Assets/MixedRealityToolkit-SDK/Features/Diagnostics/DiagnosticsHandler.cs
Overview
---
Move initialization of the style object into Awake to eliminate NullReferenceException.
Changes
---
- Fixes: #2964 .
=> fix nullreferenceexception in diagnostics handler

Assets/MixedRealityToolkit-Tests/MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs
Overview
---
- Fixed all unit tests and made sure we're registering the correct interfaces by adding a debug error check in MixedRealityToolkit registration 
- Removed redundant control statements and updated error to raise correct type.
Changes
---
- Fixes: #2972
=> Updated MixedRealityToolkit Unit Tests

Assets/MixedRealityToolkit-SDK/Features/SpatialAwareness/System/MixedRealitySpatialAwarenessSystem.cs
Overview
---
- Fixed game object life cycle bypass checks.
- Fixed typos & misc formatting 
Changes
---
- Fixes: #2999
=> Fixed a few things  with SpatialAwarenessSystem implementation

Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Tidying up the Input System profile to reorder properties to make more sense, reordering inspector and properties to:
* Input Actions Profile
* Input Actions Rules
* Pointer Profile
* Gestures Profile
* Speech
* Controller Mapping Profile
* Controller Visualization Profile
- MixedRealityInputSystemProfile
- MixedRealityInputSystemProfileinspector
=> Tidying up the Input System profile 

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs, Assets/MixedRealityToolkit/_Core/Devices/MixedReality/WindowsMixedRealityDeviceManager.cs
Overview
---
- Fixed some registration issues WMR controllers.
- Destroy cursor if pointer is invalid. (Pointers will re-create cursors if needed)
Changes
---
- Fixes: #2994
=> Some misc input bug fixes

Assets/MixedRealityToolkit-Examples/Demos/README.md.meta, Assets/MixedRealityToolkit-Examples/StandardAssets/README.md.meta, Assets/MixedRealityToolkit-SDK/Features/README.md.meta, Assets/MixedRealityToolkit/InputSystem/Pointers/README.md.meta, Assets/MixedRealityToolkit/InputSystem/Sources/README.md.meta, Assets/MixedRealityToolkit/InputSystem/Utilities/README.md.meta, Assets/MixedRealityToolkit/_Core/Attributes/README.md.meta, Assets/MixedRealityToolkit/_Core/Devices/UnityInput/README.md.meta, Assets/MixedRealityToolkit/_Core/Devices/VoiceInput/README.md.meta, Assets/MixedRealityToolkit/_Core/EventDatum/README.md.meta, Assets/MixedRealityToolkit/_Core/Inspectors/README.md.meta, Assets/MixedRealityToolkit/_Core/Resources/README.md.meta
Overview
---
Meta file cleanup / tidy from stabilization merges
Changes
---
- Clears out redundant /metas
- Adds new .meta added by unity
=> Meta file cleanup / tidy from stabilization merges

ProjectSettings/ProjectVersion.txt
=> updated project version to 2018.2.14f1

BreakingChanges.md, CONTRIBUTING.md
checkins changed to check-ins and after Instead there should be a comma
=> Spelling and Punctuation changes are done

Assets/MixedRealityToolkit/_Core/Devices/Lumin/LuminController.cs, Assets/MixedRealityToolkit/_Core/Devices/Lumin/LuminDeviceManager.cs
Overview
---
Updated MixedRealityManager->MixedRealityToolkit
=> Lumin Update

Assets/MixedRealityToolkit-Examples/Version.txt, Assets/MixedRealityToolkit-SDK/Version.txt, Assets/MixedRealityToolkit-Tests/Version.txt, Assets/MixedRealityToolkit/Version.txt, ProjectSettings/ProjectSettings.asset
Overview
---
Updates the project and text files to the beta release version
=> update version to 2018.9

Assets/MixedRealityToolkit/_Core/Devices/UnityInput/MouseDeviceManager.cs
Overview
---
Fix for Editor bug when hitting "Esc" to release mouse
Changes
---
- Fixes: #3069
=> Fix for Editor bug when hitting "Esc" to release mouse

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Overview
---
Added `IsCustomProfile` check around message box section.
Changes
---
- Fixes: #3084
=> Fixed custom configuration message box

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Overview
---
Updated Base to check if InputSystem is null before attempting to unregistering managers.
=> Updated null checking in base cursor cleanup

Assets/MixedRealityToolkit-SDK/Features/SpatialAwareness/System/MixedRealitySpatialAwarenessSystem.cs
Overview
---
Removed inappropriate destroy call from spatial awareness system
Changes
---
- Fixes: #3098
=> Removed inappropriate destroy call from spatial awareness system

Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs
Overview
---
- Reduced service searching logs.
- Misc formatting.
- Added better handling for searching for services when shutting down.
Changes
---
- Fixes: #3077
=> Updated Service Locator logging

Assets/MixedRealityToolkit-Tests/MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit/_Core/Inspectors/MixedRealityToolkitInspector.cs, Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs
Overview
---
Fixed Service Locator instancing and added parent/child verification.
Updated test suite with new names.
Changes
---
- Fixes: #3097
- Fixes: #3091
=> Updated Service Locator Instancing and Veifications

Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Overview
---
- Fixed an issue in the Config Profile Inspector and Input System Profile Inspector, where end change check doesn't get called correctly on each gui update.
- Fixed an issue in the Registered Extension Service profile inspector where the config profile wasn't reset correctly when a service was removed.
=> Config profile inspector fixes

Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs
Overview
---
Updated MixedRealityToolkit to clear core system cache
Changes
---
- Fixes: #3122
=> fixed core system cache

Assets/HoloToolkit-Preview/QRTracker/README.md
I needed to reboot my PC for the `EnableQRTrackerDefault` toggle to work, seems restarting the MR portal wasn't sufficient.
So I'm adding it as a potential troubleshooting step.
=> Updated README for QRTracker

BranchGuide.md, README.md
Overview
---
Added a new Branch guide, needs replicating straight to the master and updated the homepage with a link
Replaces PR #3090 due to GitHub meh
Changes
---
- Fixes: #3088
=> Added Branch Guide (HTK) - resolves #3088 

BranchGuide.md, README.md
Overview
---
Added a new Branch guide, needs replicating straight to the mrtk_release and updated the homepage with a link
Replaces #3089 as GitHub got messed up
Changes
---
- Fixes: #3088
=> Added Branch Guide (mrtk) - resolves #3088

Assets/MixedRealityToolkit-SDK/Features/UX/Scripts/Tooltips/ToolTip.cs
Overview
---
fixed build warnings
Changes
---
- Fixes: #3133
=> fixed build warnings

ProjectSettings/ProjectVersion.txt
Overview
---
[Release Notes](https://unity3d.com/unity/whatsnew/unity-2018.2.16):
- IL2CPP: Add support for CultureInfo in WebGL when exceptions are disabled. (1083520)
- IL2CPP: COM Callable Wrappers for managed arrays now implement IReferenceArray interface. This fixes cases where Windows Runtime APIs expected objects to implement this interface, and if they don't, they report errors such as "Data of this type is not supported." and "Error trying to serialize the value to be written to the application data store". (1054327)
- IL2CPP: Fixed a call to GetGenericArguments on a MethodInfo not working for an inflated generic type. (1087317)
- IL2CPP: Fixed COM Objects representing Windows.Foundation.IAsyncAction and Windows.Foundation.IAsyncOperation getting destroyed after converting them …
=> Updated editor to 2018.2.16

Assets/MixedRealityToolkit/_Core/EventDatum/GenericBaseEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/Input/BaseInputEventData.cs, Assets/MixedRealityToolkit/_Core/EventDatum/SpatialAwareness/MixedRealitySpatialAwarenessEventData.cs
Overview
---
- Moved the spatial awareness `EventTime` to the base generic event data class. Shouldn't be a breaking change.
- Added `EventTime` to the base input event data class
=> Adds event time to all event datum

ProjectSettings/ProjectVersion.txt
- XR: Update Vuforia to version 7.5.26.
- Asset Bundles: Fixed Changing addressableNames doesn't trigger bundle rebuild. (996380)
- Editor: Fixed an issue where the camera frustum gizmo would always draw the near clipping plane at world origin. (1084269)
- iOS: Fixed a crash when using using static const std::string in Xcode 9. (1050875, 1096815)
- Licenses: Fixed an issue where licence activation didn't work when using the -nographics command line flag. (1043511, 1090055)
- Package Manager: Added a warning message if you disable a package and that causes dependencies to also be disabled.
- Package Manager: Added information to compiler errors explaining if a package has been disabled as a dependency of another package.
- Package Manager: Added information to info messages for disabled …
=> Updated unity editor to 2018.2.18f1

CODE_OF_CONDUCT.md
Add standard Microsoft Code of Conduct.
=> Add standard Microsoft Code of Conduct

Assets/MixedRealityToolkit/_Core/Services/MixedRealityToolkit.cs
Overview
---
- Removes the input mappings if the input system is disabled
=> Remove input mappings if toolkit's input system is disabled.

Assets/MixedRealityToolkit-SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs
Overview
---
From this:
To this:
=> Update capitalization of "keyword" in SpeechInputHandler Inspector

MRTK-SDK.md
Controls form how the user moves and interacts in the scene, ranging from:
to this
Controls from how the user moves and interacts in the scene, ranging from:
Overview
---
Changes
---
- Fixes: # .
=> Change form to from

ProjectSettings/ProjectVersion.txt
Updated Unity editor to [2018.2.19f1](https://unity3d.com/unity/whatsnew/unity-2018.2.19)
Fixes
---
- Animation: Fixed Animation Window selection of nested Animation component hierarchies children of Animator component hierarchies. (1089015)
- Animation: Fixed Animation Window selection of nested Animation component hierarchies children of Animator component hierarchies. (1089015, 1096352)
- Build Pipeline: Fixed "Couldn't call method ShowProfilerWindow" error during Build & Run with the Autoconnect Profiler option set. (1059763)
- Build Pipeline: Fixed Build & Run with Autoconnect Profiler. (1059763)
- Editor: Fixed this issue by restricting the insertion of menu items into a given submenu to a prescribed limit of 1000 items and displays a warning about the same. (1039181)
- GI: Fixed an …
=> Updated Unity Editor verison to 2018.2.19f1

Assets/MixedRealityToolkit-Examples/StandardAssets/Prefabs/SceneDescriptionPanel.prefab
Overview
---
Editor keeps trying to update this prefab.
=> SceneDescriptionPanel.prefab update

Assets/MixedRealityToolkit/_Core/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs, Assets/MixedRealityToolkit/_Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
=> Cleanup build warnings

Assets/MixedRealityToolkit-SDK/Profiles/DefaultMixedRealityBoundaryVisualizationProfile.asset, Assets/MixedRealityToolkit/_Core/Attributes/PhysicsLayerAttribute.cs, Assets/MixedRealityToolkit/_Core/Attributes/PhysicsLayerAttribute.cs.meta, Assets/MixedRealityToolkit/_Core/Definitions/BoundarySystem/MixedRealityBoundaryVisualizationProfile.cs, Assets/MixedRealityToolkit/_Core/Extensions/LayerExtensions.cs, Assets/MixedRealityToolkit/_Core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/PhysicsLayerAttributeDrawer.cs, Assets/MixedRealityToolkit/_Core/Inspectors/PropertyDrawers/PhysicsLayerAttributeDrawer.cs.meta, Assets/MixedRealityToolkit/_Core/Interfaces/BoundarySystem/IMixedRealityBoundarySystem.cs, Assets/MixedRealityToolkit/_Core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
Overview
---
Update the boundary system to have a configurable physics layer setting for the generated content.
Changes
---
- Fixes: #3235
=> Boundary system physics layer configuration settings

Assets/MixedRealityToolkit/_Core/Interfaces/IMixedRealityService.cs, Assets/MixedRealityToolkit/_Core/Services/BaseService.cs
Overview
---
Implements IDisposable pattern for services.
Changes
---
- Fixes: #3289
=> added Disposable pattern to service interface.

ProjectSettings/ProjectVersion.txt
Updates the project version file to the latest Unity 2018.3 release.
=> update unity version to 2018.3.2

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/Billboard.cs
Overview
---
Feature request from a partner, who were using the configurability in the HoloToolkit.
=> Make the Billboard's pivot axis configurable

Assets/MixedRealityToolkit/Definitions/Devices/ControllerMappingLibrary.cs, Assets/MixedRealityToolkit/Inspectors/ControllerPopupWindow.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
Overview
---
This change completes the MRTK v2 profile inspector UI changes related to foldouts. Modified inspectors are:
- Input System
- Controller Visualization
- Pointer
Also fixed were the relative paths to inspector images (MRTK logo, controller images) that were broken by the folder rename.
Fixes #3376
=> Profile foldout part2

ProjectSettings/ProjectVersion.txt
update project version to latest unity release
=> update to unity 2018.3.3

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/Handlers.meta
Overview
---
A variable name changed (`pointer` -> `pointerData`).
This also removes an unused meta file.
=> Fix variable naming

Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs
Overview
---
Fix potential null ref in `BaseSpatialObserver` if the spatial awareness system is turned off.
=> Add null check for the SpatialAwarenessSystem being turned off

Assets/MixedRealityToolkit/Extensions/BoundsExtensions.cs
Overview
Adding a few helper methods to the BoundsExtensions class.
- GetColliderBoundsPoints
- GetRenderBoundsPoints
- GetMeshFilterBoundsPoints
=> New static helper methods to BoundsExtensions

Assets/MixedRealityToolkit.Examples/Demos/UX/TwoHandManipulation/ManipulationExample.unity, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs.meta
Overview
---
Synchronizes the new GUID with the version partners have been using.
=> Synchronize ManipulationHandler GUID

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/HolographicButton.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/HolographicButtonToggle.prefab
Overview
---
In HolographicButton and HolographicButtonToggle prefab, replaced TextMesh Pro with 3D Text Mesh to avoid broken/forced TextMesh Pro import warning messages.
Changes
---
- Prefab file changes from: #3380. No code changes.
=> [vNext][UX] Interactable: Replaced TextMeshPro with TextMesh

Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Scenes/InteractablesGallery.unity, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonContent.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonPlate.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/HolographicButton.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/HolographicButton.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/HolographicButtonToggle.prefab
Overview
---
Updates GUIDs related to Interactables to the versions that have been in-use by our partners.
=> Sync interactable guids

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DragAndDropHandler.cs
Overview
---
#3389 removes the need for this interface in this script (they were all empty stubs).
=> Remove IMixedRealityInputHandler from DragAndDropHandler

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DragAndDropHandler.cs
Merge beta changes back in to dev branch
=> Beta2 stabilization -> mrtk_development

Assets/HoloToolkit-Examples/Input/Scripts/MicStreamDemo.cs, Assets/HoloToolkit/Sharing/Scripts/SharingStage.cs
non-code impacting comment changes
=> comment updates

Assets/HoloToolkit-Preview/SpectatorView/README.md
add more details to the spectator view plugin step. add some additional context to the building text
Overview
---
These changes add more detail to existing documentation
Changes
---
- Fixes: # .
=> Update SpectatorView (Preview) README.md

Assets/MixedRealityToolkit.Examples/Demos/Solvers/Prefabs/SolverSwappingVolume.prefab, Assets/MixedRealityToolkit.Examples/Demos/Solvers/Scripts/SwapVolume.cs
Overview
---
Update solvers example scene with an action filter and a fallback to `Head` if no handedness is detected.
=> Update solvers example

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Overview
---
Fixes pointer profile serialization.
Changes
---
- Fixes #3425
=> Fix pointer profile serialization

Assets/HoloToolkit-Preview/SpectatorView/README.md
Fix opencv version in readme
Overview
---
Changes
---
- Fixes: # .
=> Update Readme.md - SpectatorView Preview

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Overview
---
Update MixedRealityToolkit-Generated to .Generated to match style. This was changed in a few places already.
=> Update MixedRealityToolkit-Generated to .Generated to match style

External/Documentation/MixedRealityServices.md
- Substituted MixedRealityOrchestrator with MixedRealityToolkit
- Removed references to runtime services
- Fixed minor typos
Overview
---
Changes
---
- Fixes: # .
=> Updated Services documentation

CONTRIBUTING.md
Overview
---
Changes
---
- Fixes: # .
=> Fixed broken link to documentation guidelines

Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTipSpawner.cs
Overview
---
Our basic ToolTip example scene updated with latest prefabs and manipulation scripts. Also fixes some spawning logic in ToolTipSpawner class.
=> [vNext][UX] Tooltip Examples Scene

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/RadialView.cs, Assets/MixedRealityToolkit/Definitions/Utilities/RadialViewReferenceDirection.cs, Assets/MixedRealityToolkit/Definitions/Utilities/RadialViewReferenceDirection.cs.meta
Overview
---
Updates the RadialView solver to have public properties for all its settings.
=> Expose RadialView's settings as public properties

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit/Definitions/Utilities/MovementConstraintType.cs, Assets/MixedRealityToolkit/Definitions/Utilities/MovementConstraintType.cs.meta, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
A new parameter "Constraint On Movement" in analogy to the existing "Constraint On Rotation":
- Default remains "None" without changes in behavior
- So far only one alternative setting "FixDistanceFromHead" with self-explanatory behavior.
- Other settings to be added based on future use-cases.
=> Introduce MovementConstraintType.FixDistanceFromHead in ManipulationHandler

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/LinePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/InputSystemGlobalListener.cs, Assets/MixedRealityToolkit/Definitions/Physics/RayStep.cs, Assets/MixedRealityToolkit/Utilities/CameraCache.cs
Overview
---
Add performance and stability (reduce null reference exceptions) in input.
=> input stability and performance fixes

Assets/MixedRealityToolkit/Providers/BaseController.cs
Search all controller mappings before trying to assign a default interaction mapping.
=> Search all controller mappings before trying to assign a default interaction

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs
Overview
---
Fit and finish update to camera profile description message.
=> update camera profile description

README.md
Takes changes from 4d320ed and 5e39dc4
=> Cherry-pick readme changes from mrtk_release

Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_DefaultPointerLine.mat
Overview
---
Thanks to #3382, we can re-add color to the controller lines!
From 
to
Changes
---
- Fixes: #3268
=> Update controller pointer line to support color again

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Layout/ButtonBackgroundSizeOffset.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Layout/ButtonBorder.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTip.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTipBackgroundBlob.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTipLineHighlight.cs
Unity warns about private fields that are never initialized.
=> Fix warnings and spelling

Assets/MixedRealityToolkit.Providers/MixedReality.Toolkit.Providers.nuspec, Assets/MixedRealityToolkit.Providers/MixedReality.Toolkit.Providers.nuspec.meta, Assets/MixedRealityToolkit.Services/MixedReality.Toolkit.Services.nuspec, Assets/MixedRealityToolkit.Services/MixedReality.Toolkit.Services.nuspec.meta, build.ps1
=> Minor fixes for nuget pack

Assets/MixedRealityToolkit.Providers/OpenVR/OpenVRDeviceManager.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_Standard_Blue.mat.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_Standard_DarkBrown.mat
Overview
---
Initial pass on comment updates and stale serialization.
Also, includes a fix that prevents lost sources from being recreated if lost at the "wrong" time and an Update is still processing its data.
=> Beta2 minor clean-up

GettingStarted.md
Overview
---
Had a few repeated list levels: 2 and 5 appeared more than once
Changes
---
- Documentation only
=> Fix GettingStarted.md List indices

Assets/MixedRealityToolkit.Examples/Demos/UX/BoundingBox/BoundingBoxExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/Utilities/InspectorFields/Scenes/InspectorFieldsGallery.unity
Overview
---
Some of the example scenes had a stale setup pre-#3113
Changes
---
- Fixes: #3514
=> Fix example scenes setup around FocusProvider

Assets/MixedRealityToolkit.Examples/Demos/SpatialAwareness/Scenes/SpatialAwarenessMeshDemo.unity
removed bad script reference that got introduced during some experimentation.
fixes #3516
=> Fix spatial demo scene

ProjectSettings/ProjectVersion.txt
update recommendation to 2018.3.6f1
=> update recommended unity version

Assets/MixedRealityToolkit/Inspectors/Utilities/Lines/DataProviders/BezierDataProviderInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/Lines/DataProviders/BezierDataProviderInspector.cs.meta, Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/BezierDataProvider.cs, Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/BezierDataProvider.cs.meta
Overview
---
We've often found ourselves in need of a simpler / more lightweight alternative to the Spline data provider. This PR adds a Bezier line data provider and inspector.
=> Bezier Line Data Provider

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Overview
---
Brings over some changes made by @danielhofmann-ms to fix bounding box calculations.
Before change:
After change:
=> Fix bounding box creation issues

Assets/MixedRealityToolkit.Examples/Demos/SpatialAwareness/Scripts/DemoSpatialMeshHandler.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/IInteractableHandler.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/ReceiverBase.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/ReceiverBaseMonoBehavior.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/GazeHandHelper.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/ThemeInspector.cs, Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs, Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs, Assets/MixedRealityToolkit/Definitions/Devices/TrackingState.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/BaseSpatialAwarenessObject.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshLevelOfDetail.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessPlanarObject.cs, Assets/MixedRealityToolkit/Extensions/BoundsExtensions.cs, Assets/MixedRealityToolkit/Extensions/CollectionsExtensions.cs, Assets/MixedRealityToolkit/Extensions/VectorExtensions.cs, Assets/MixedRealityToolkit/Inspectors/ControllerPopupWindow.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/InspectorUIUtility.cs, Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs, Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/Observers/IMixedRealitySpatialAwarenessMeshObserver.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialAwarenessObserver.cs, Assets/MixedRealityToolkit/Services/BaseDataProvider.cs, Assets/MixedRealityToolkit/Utilities/DebugUtilities.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs, Assets/MixedRealityToolkit/Utilities/Physics/MixedRealityRaycaster.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
Overview
---
Fixed documentation errors.
Fixed [Unity.Object lifetime check bypass errors](https://github.com/JetBrains/resharper-unity/wiki/Possible-unintended-bypass-of-lifetime-check-of-underlying-Unity-engine-object)
=> Misc doc fixes and Unity Object lifetime check bypass fixes

Assets/MixedRealityToolkit/Utilities/Async/Internal/AsyncCoroutineRunner.cs
Overview
---
Async GameObject runner sometimes created multiple instances.
Better destruction calls on empty object.
=> Fixed an issue with creating multiple async runners.

ProjectSettings/ProjectSettings.asset, ProjectSettings/ProjectVersion.txt, ProjectSettings/UnityConnectSettings.asset
Overview
---
Updating to Unity 2018.3.7f1, as part of the [March 2019 Security Update Advisory](https://unity3d.com/security?utm_campaign=engine_global_service_190301-gbl-security-rce#CVE-2019-9197).
=> Update to Unity 2018.3.7f1

Assets/MixedRealityToolkit/Definitions/MixedRealityToolkitConfigurationProfile.cs
=> fix incorrect boundary system property updating

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs
=> MRTK line renderer fix

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Overview
---
Changes
---
- Fixes: #3579
=> Change order of checks

ProjectSettings/ProjectVersion.txt
=> Update to latest Unity (2018.3.8)

Assets/MixedRealityToolkit.Examples/toc.yml.meta, Assets/MixedRealityToolkit.SDK/Features/toc.yml.meta, Assets/MixedRealityToolkit.SDK/Profiles/toc.yml.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/toc.yml.meta, Assets/MixedRealityToolkit.SDK/toc.yml.meta, Assets/MixedRealityToolkit/toc.yml.meta
Overview
---
Some of the docfx files had meta files generated for them when opening in Unity.
=> Add missing meta files

Assets/MixedRealityToolkit.Providers/OpenVR/MixedRealityToolkit.Providers.OpenVR.asmdef
Overview
this is the only ASMDEF that has Linux 32 bit tagged
Changes
---
- Fixes: #3521
=> Removed Linux 32 bit

Roadmap.md
Overview
---
Keeps the branches in-sync.
=> Merge mrtk_release -> mrtk_development

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Overview
The Base Cursor was in a race condition with the MixedRealityToolkit updating Raycast data
Changes
---
- Fixes: part of #3614 .
=> BaseCursor LateUpdate instead of Update

Assets/MixedRealityToolkit/Utilities/Lines/LineFollower.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MeshLineRenderer.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/ParticleSystemLineRenderer.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/StripMeshLineRenderer.cs
Those classes accessed data in an undeterministic order (Update loops race condition), this fixes it for them.
- Fixes: #3581 and part of #3614 .
=> Changed relevant Updates to LateUpdate

README.md
Overview
---
- Adding status widget for Azure Pipelines CI
=> Add pipeline status widget to .md

docfx.json, templates/mrtk/partials/navbar.tmpl.partial, templates/mrtk/styles/main.css, templates/mrtk/styles/main.js, web/version.css, web/version.js
Overview
--- developer docs now have a dropdown in the main navigation that allows to switch between several versions
=> added support for multiple doc versions

Documentation/DevDocGuide.md
Overview
--- added section for describing the steps to perform when we release a new mrtk version
--- added guide for CI
=>  added section for versioning to mrtk dev doc guide

templates/mrtk/partials/navbar.tmpl.partial, templates/mrtk/styles/main.js, web/version.js
fixes broken links in dropdown
=> fixed paths in dropdown generation

Assets/MixedRealityToolkit/Services/BaseDataProvider.cs
must've typed in the wrong window , sry!
=> removed accidental /////

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs
Overview
fixes simple code mistake
=> fix wrong assignment

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Overview
---
Changes
---
- Fixes: #3681
=> Adds 'Don't show this again' to toolkit startup warning

Assets/MixedRealityToolkit/Utilities/DebugUtilities.cs
Overview
---
Adds a debug utility to draw a point in the Scene view using Unity Debug.DrawLine
=> Add DrawPoint to DebugUtilities

Assets/MixedRealityToolkit/Services/BaseEventSystem.cs
Fix a bug in input system where the event listeners array was being modified while an event was getting dispatched, because of nested dispatch.
=> Event system fix where the event listeners array was being modified while an event was getting dispatched

README.md
Overview
---
@Yoyozilla has been doing README updates in mrtk_release. This PR syncs them into mrtk_dev.
=> Sync mrtk_release -> mrtk_dev

Assets/MixedRealityToolkit/Utilities/WindowsApiChecker.cs
Overview
---
Add runtime validators for additional UWP API contract versions.
V7 is the October 2018 Update.
=> Add new UWP API contracts to WindowsApiChecker

Assets/MixedRealityToolkit/Definitions/Utilities/MixedRealityPose.cs
Overview
---
Adds `Forward`, `Up`, and `Right` to MixedRealityPose.
=> Add useful properties to MixedRealityPose

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs, Assets/MixedRealityToolkit/Definitions/Lines/LinePointTransformMode.cs.meta
First pass of cleanup that wasn't entangled in feature updates.
=> Assorted formatting and comment updates

Assets/MixedRealityToolkit.Extensions/PhotoCapture/CameraIntrinsics.cs, Assets/MixedRealityToolkit.Extensions/PhotoCapture/StreamDescription.cs
Overview
---
Address comments remaining for https://github.com/Microsoft/MixedRealityToolkit-Unity/pull/3698
=> Spectator view cleanup2

Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewSetup.md
Update readmes to call out unity package dependencies.
Overview
---
Update SpectatorViewSetup.md to include info on ARFoundation, ARCore and ARKit
=> Update SpectatorViewSetup.md to include info on ARFoundation, ARCore and ARKit

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
Adding scene list parsing for command line build
=> Add scenes list to command line build

README.md
- Remove redundant bullets
- Pull up supported platforms section
Overview
---
Changes
---
- Fixes: # .
=> Tighten up the intro

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/AppBar/AppBar.prefab
Overview
---
Fixing Un-Linked events in AppBar Buttons
Changes
---
Button events got un-linked after namespace change.
=> Fixing Un-Linked events in AppBar Buttons

Assets/MixedRealityToolkit/Definitions/Physics/RayStep.cs, Assets/MixedRealityToolkit/Utilities/InspectorFields/InspectorGenericFields.cs
Overview
---
Minor changes to ensure MRTK compiles with .NET in Unity 2018.3.3+. Logic is identical.
Changes
---
- Fixes: #3689
- Reinforces: #3656
=> Minor changes to ensure MRTK compiles with .NET

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Overview
---
Add public accessors for BaseCursor fields. This will be used for future cursor types.
=> Add public accessors for BaseCursor fields

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs
Overview
---
Mark eventData as being used in PressableButton and remove creation of stale finalMarker object
=> Small fixes for PressableButton

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Pointers/DefaultControllerPointer.prefab
Temporarily making the default pointer use a solid line when not focused on anything. Will fix Graphics.DrawMesh/DrawMeshInstanced  + Single Pass Instanced rendering at a later date.
Changes
---
- Fixes: #3776
=> Temporary Fix for Graphics.DrawMesh/DrawMeshInstanced  + Single Pass Instanced Rendering

Assets/MixedRealityToolkit/Providers/UnityInput/UnityJoystickManager.cs
=> Fixed joystick name check to correctly recognize Xbox controllers

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Receivers/InteractionReceiver.cs, Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityInputSystem.cs, Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
This implements the changes suggested in issue #3722
=> Renamed 'input pressed' to 'float input changed' and raise only on changes to inputs

Documentation/SpatialAwareness/ConfiguringSpatialAwarenessMeshObserver.md, Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.md
Overview
---
The spatial awareness PR broke the docs build.
I also integrated @thalbern's comments from after I merged the original PR.
=> Fix docs build

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs, Assets/MixedRealityToolkit/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs, Assets/MixedRealityToolkit/Interfaces/Diagnostics/IMixedRealityDiagnosticsSystem.cs, Assets/MixedRealityToolkit/StandardAssets/Shaders/InstancedColored.shader, Assets/MixedRealityToolkit/StandardAssets/Shaders/InstancedColored.shader.meta
Porting over latest changes from https://github.com/Microsoft/VisualProfiler-Unity including:
- Adding support for Unity's FrameTimingManager to get more accurate frame times on supported platforms (this also unlocks GPU frame timing for supported platforms).
- Optimizations around how strings are formatted and missed frame indicators are rendered (instanced when available).
- UX improvements around how the window can be anchored.
- Minor tooltip/documentation improvements.
=> Diagnostics Visual Profiler Improvements

README.md
Overview
---
Changes
---
- Fixes: # .
=> Fix hanging sentence on MRTK home page.

README.md
Overview
---
Fixing typo on the landing page (mrtk_release)
=> Fixing typo on the landing page (mrtk_release)

README.md
Overview
---
Update README.md - Fixing typo (mrtk_development)
=> Fixing typo on the landing page (mrtk_development) 

Assets/MixedRealityToolkit/Attributes/HelpAttribute.cs, Assets/MixedRealityToolkit/Attributes/HelpAttribute.cs.meta, Assets/MixedRealityToolkit/Attributes/ScenePickAttribute.cs, Assets/MixedRealityToolkit/Attributes/ScenePickAttribute.cs.meta, Assets/MixedRealityToolkit/Attributes/TagPropertyAttribute.cs, Assets/MixedRealityToolkit/Attributes/TagPropertyAttribute.cs.meta, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/HelpDrawer.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/HelpDrawer.cs.meta, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/ScenePickPropertyDrawer.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/ScenePickPropertyDrawer.cs.meta, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TagPropertyDrawer.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TagPropertyDrawer.cs.meta
Overview
---
Added some useful attributes from Longbow.
Changes
---
Added Help, TagProperty, and ScenePick.
- Fixes: # .
=> Added some useful attributes from Longbow.

README.md
Overview
---
Fix typos and improve clarity on README.md, also deleted some redundant content
=> Fix typos and improve clarity on README.md

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DictationHandler.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/DictationHandler.cs.meta
Created a script to provide basic access to the dictation service without having to resort to scripting, like SpeechInputHandler does for the speech service.
=> Create DictationHandler script for easy access to dictation service

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/BaseClasses/PanZoomBase.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/BaseClasses/PanZoomBase_RectTransf.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/BaseClasses/PanZoomBase_Texture.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/PanZoom_RectTransf.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/PanZoom_Texture.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/Scroll_RectTransf.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/Scroll_Texture.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Demo_ScrollPanZoom/Scripts/Target_MoveToCamera.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/mrtk_eyes_00_RootScene.unity, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/mrtk_eyes_03_Navigation.unity, ProjectSettings/ProjectVersion.txt
Overview
---
- Removed some deprecated parameters in the scroll scripts that were still shown in the Editor.
- Updated hand zoom parameter that was specific to zoom, but was shown for scroll.
=> Cleanup and update of ET navigation demo and scripts

Documentation/DevDocGuide.md, Documentation/InputSimulation/InputSimulationService.md, Documentation/MixedRealityConfigurationGuide.md, Documentation/README_AppBar.md, Documentation/README_BoundingBox.md, Documentation/README_Button.md, Documentation/README_FingertipVisualization.md, Documentation/README_Interactable.md, Documentation/README_ManipulationHandler.md, Documentation/README_Pointers.md, Documentation/README_Solver.md, Documentation/SpatialAwareness/ConfiguringSpatialAwarenessMeshObserver.md, Documentation/toc.yml
Overview
---
Quick pass on spelling in the documentation.
=> Spell check: documentation pass

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
fixes invisible hand in simulation mode
=> changed default behavior of hand visibility to be enabled

README.md
Overview
---
Merge README.md - removing duplicated sections. Merged Julia's updates. Adjusted section positions.
=> Merge README.md - removing duplicated sections

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButton.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs.meta, Assets/MixedRealityToolkit/Attributes/ReadOnlyAttribute.cs, Assets/MixedRealityToolkit/Attributes/ReadOnlyAttribute.cs.meta
Overview
---
This was created in response to feedback that the PressableButton settings were difficult to understand.
- Draggable handles for changing button press distance, release threshold and max push distance.
- Visible guides show you where these values exist in space.
- Labels attempt to explain what each plane represents. (These could be improved).
- PressableButton no longer creates / destroys transforms every time push events begin / end. Initial transform is created automatically by inspector. It will create transform if not found at runtime as a last resort.
- Button reports touch / pressed states in inspector.
- Button prefabs have been updated.
Would appreciate feedback on clarity.
=> PressableButton Inspector Improvement

Documentation/Authors.md, Documentation/toc.yml
Thanks to ALL who contributed to make MRTK v2 a reality!
=> add authors doc

Documentation/README_Pointers.md
- Flesh out pokepointer and mousepointer sections since they were very sparse.
- Fix broken link.
=> Pointer documentation improvement

Assets/MixedRealityToolkit.Examples/Version.txt, Assets/MixedRealityToolkit.Providers/Version.txt, Assets/MixedRealityToolkit.SDK/Version.txt, Assets/MixedRealityToolkit.Services/Version.txt, Assets/MixedRealityToolkit.Tests/Version.txt, Assets/MixedRealityToolkit/Version.txt, Documentation/GettingStartedWithTheMRTK.md, Documentation/HTKToMRTKPortingGuide.md, Documentation/README_AppBar.md, Documentation/README_BoundingBox.md, Documentation/README_Button.md, Documentation/README_FingertipVisualization.md, Documentation/README_HandInteractionExamples.md, Documentation/README_Interactable.md, Documentation/README_ManipulationHandler.md, Documentation/README_ObjectCollection.md, Documentation/README_Pointers.md, Documentation/README_Slate.md, Documentation/README_Solver.md, Documentation/README_SystemKeyboard.md, Documentation/README_Tooltip.md, Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.md, ProjectSettings/EditorBuildSettings.asset
So that we can get new docfx image fixes that came from rc1
=> Merge rc1 doc and version changes back into mrtk_development

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/mrtk_eyes_00_RootScene.unity, Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Glb-Loading-Demo.unity, Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Gltf-Loading-Demo.unity, Assets/MixedRealityToolkit.Examples/Demos/Utilities/InspectorFields/Scenes/InspectorFieldsExamples.unity
Overview
---
A few example scenes were missing the new input module, and some had stale cameras.
=> Properly set up example scenes with input module

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Overview
A lot of code is copy and pasted. This reduces the code paths to one
=> Reduces redundant code in MixedRealityToolkit

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
=> fix .net focusprovider build

README.md
/azp run mrtk_docs
Overview
---
Changes
---
- Fixes: # .
=> updated MR dev center content and icons

Assets/MixedRealityToolkit.Extensions/PhotoCapture/CameraExtrinsics.cs, Assets/MixedRealityToolkit.Extensions/PhotoCapture/CameraIntrinsics.cs, Assets/MixedRealityToolkit.Extensions/PhotoCapture/StreamDescription.cs
Overview
---
Update camera related items to be Serializable
Changes
---
- Fixes: # .
=> Make camera frame helper classes serializable for future networking synchronization

Assets/MixedRealityToolkit.Extensions/Socketer/Scripts/Socketer.cs
Overview
---
Fix socketer wsa build by moving using declaration
Changes
---
- Fixes: # .
=> Fix socketer wsa build by moving using declaration

Documentation/GettingStartedWithTheMRTK.md
We've gotten some feedback that the fact that the user sees 5 different profiles when they load in for the first time is really confusing - no where do we talk about what they do or why they're there. We're hoping to improve the flow here a little bit improving the documentation (i.e. explaining what to pick - the default one - and what the other ones are for - the example scenes) and by choosing a reasonable default (i.e. highlighting the default one when opening the picker)
=> Update the Getting Started doc to clarify what the other MRTK profiles are in the initial picker.

Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
In the Input Data Provider section, each data provider has an optional (or required) profile that configures that particular profile. There are a couple of issues:
1) The Add button doesn't actually work on these, because these data providers have abstract (BasedMixedRealityProfile) for their targets. This means pressing the + button ends up just throwing an exception. Unfortunately fixing this up requires some more invasive changes to the way services/data providers are configured, so I'm opting here to just kill off the + button in these cases (and then add documentation for each data provider about what configuration profile it needs).
2) If there already exist profiles that support that particular service (for example, input simulation), this change restricts the set of options in the …
=> Clean up some data provider profile selection confusion.

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Pointers/MousePointer.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/MousePointer.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Pointers/MousePointerInspector.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit.Services/InputSimulation/ManualCameraControl.cs, Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHandDataProvider.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityMousePointer.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs
Reverts Microsoft/MixedRealityToolkit-Unity#3982
reverting due to new comments that were made after completing the PR
=> Revert "Fixed Mouse pointer / controller"

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.unity
=> Removed reference to missing script in speech sample.

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs, Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHandDataProvider.cs, Assets/MixedRealityToolkit/Providers/UnityInput/UnityTouchDeviceManager.cs
Overview
---
MixedRealityToolkit.Update with default services used to allocate 476 B every frame. This reduces allocations to 0 B per frame.
=> Removes GC Alloc from various services

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
=> Fix bug in calculation of normal in local space

build.ps1
Added a switch to not build nuget packages from build.ps1
=> Added a switch to not build nuget packages from build.ps1

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
Fixes #3863. See issue for background details on the change.
=> Use pointer pose for one handed manipulation in manipulation handler

Assets/MixedRealityToolkit.SDK/Features/Input/Events/ManipulationEventData.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit/Utilities/ClippingPrimitive.cs
Overview
---
A few minor updates I'd like to add in before too much time passes.
Changes
Exposed a few extra properties on the `ManipulationEventData` class and updated `ManipulationHandler` accordingly. Currently there is no way to know what `ManipulationHandler` sent the ManipulationEvent. While I was in there I exposed a few other things that looked useful such as Pointer _position_, _velocity_, and _angular velocity_. 
Fixes
---
Added missing `OnEnable` preRender check on `ClippingPrimitive.cs`. #3886
=> Manipulation event data and clipping primitive fix

Documentation/howto_migrate.md, Documentation/toc.yml
There's already been an HTK->MRTK writeup which is already hooked up in the TOC, there's no need to keep this particular thing around.
=> Clean up a dead piece of documentation.

Documentation/README_Interactable.md, Documentation/README_ManipulationHandler.md, Documentation/README_Sliders.md, Documentation/README_Solver.md
Using some cool vscode extensions to help spell check, yay.
In response to:
https://github.com/Microsoft/MixedRealityToolkit-Unity/issues/4093
=> Fix spelling mistakes in our documentation.

Documentation/GettingStartedWithTheMRTK.md
Overview
---
Link was pointing to preview
Changes
---
- Fixes: # .
=> Updating with latest version of Windows SDK

Documentation/GettingStartedWithTheMRTK.md
Overview
---
Adding an explicit step to ask people to switch to the correct platform so the changes applied by adding the package are made to the correct one
=> Updates in the getting started

Assets/MixedRealityToolkit.Examples/Demos/Audio/Scripts/obj.meta
Overview
---
Looks like this was accidentally added.
=> Remove stale meta

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs
Also, raise pointer changed event.
Fixes: #4158
=> Raise pre focus changed event before focus exit when unregistering pointer

ProjectSettings/ProjectSettings.asset
This is similar as previous change, but for UWP. Again, this has no impact on consuming code, but does for Unity.
=> Fixing UWP Compat (last one was standalone)

Documentation/EyeTracking/EyeTracking_BasicSetup.md
Added additional information and clarity around the steps required for a successful eye tracking application.
=> Improvements to Eye Tracking Basic Setup

Assets/MixedRealityToolkit.Examples/Demos/Diagnostics/Scripts/DiagnosticsDemoControls.cs
Updates the demo script to use the registry to acquire the diagnostic system instance.
This change builds upon #4099 and is related to #3545
=> update diagnostic demo to get the service from the registry

Assets/MixedRealityToolkit/Inspectors/ExtensionTemplates/ExtensionServiceCreator.cs, Assets/MixedRealityToolkit/Inspectors/ExtensionTemplates/ExtensionServiceWizard.cs, ExtensionTemplates/ExtensionInspectorTemplate.txt, ExtensionTemplates/ExtensionInterfaceTemplate.txt, ExtensionTemplates/ExtensionProfileTemplate.txt, ExtensionTemplates/ExtensionScriptTemplate.txt
Overview
---
Updates the wizard to generate an optional service inspector (#3773) for the new service.
=> Updates Create Extension Service Wizard to generate service inspectors

Assets/MixedRealityToolkit/Definitions/Utilities/SupportedPlatforms.cs, Assets/MixedRealityToolkit/Utilities/PlatformUtility.cs
Simply adds Android as a supportable platform. Otherwise it's not possible to support any Android platforms at the moment.
=> Added Android as supportable platform

Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/TestFixture_02_InteractionDefinitionTests.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityInteractionMapping.cs
=> Fix check for value change when setting Vector2 values in interaction mappings

README.md
We introduced this dupe in this commit. Fixing. https://github.com/microsoft/MixedRealityToolkit-Unity/commit/55557c2e25b30e16cc845837cdbc5551a7b8c012#diff-04c6e90faac2675aa89e2176d2eec7d8
- Fixes: # .
>
>
> commands (substituting {PR_ID} with the ID of this …
=> Removing duplicate line

pipelines/ci.yaml, pipelines/pr.yaml
Need to disambiguate for setting up pipeline in internal project.
=> Disambiguate NuGetCommand task

Documentation/EyeTracking/EyeTracking_ExamplesOverview.md
Fixed a broken link.
- Fixes: broken link.
=> Fixed broken link "loaded additively"

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Creates a playspace transform and parents main camera under playspace transform in editor.
- Fixes: #4334
=> Ensures playspace transform is created in editor

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
=> Prevents multiple MRTK instance initializations on enter playmode

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3909
This issue has been around for a while, and has some interesting history. The underlying cause is a bug in a Unity API (see the code for details), which was fixed at some point in the past, but regressed at some unknown time. With no ETA on when the underlying Unity bug, we're checking in a workaround to our code so that customers can get unblocked.
Note that this scopes the fix to only situations where remoting is active. Otherwise this is the same as the workaround that was posted in the linked issue.
=> Fix for the air-tap gesture on HL1 holographic remoting.

Assets/MixedRealityToolkit/Definitions/Devices/ControllerMappingLibrary.cs, ProjectSettings/InputManager.asset
=> Changed dead zone in MRTK-created input axes to the Unity default (0.19)

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Loader.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Loader/IndeterminateLoader.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Loader/IndeterminateLoader.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Loader.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Loader/LoaderController.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Loader/LoaderController.cs.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_Standard_UnlitWhite.mat, Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_Standard_UnlitWhite.mat.meta
Addition of a simple Indeterminate Loader based on HoloLens 2 system design. Easily tunable for personal needs, the default settings match what the current design is.
Simply enable / disable the indeterminate loader prefab to visualize a loading state in your app.
This addresses feature request: #4408 
New files:
Indeterminate loader prefab
Loader controller script
MRTK standard shader material - Unlit white
=> Indeterminate loader

Documentation/README_MRTKStandardShader.md
Fixes the docs build (and some formatting and a typo).
=> Fix the docs build

Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4319
The controller type enumeration happens to look through every single assembly that is visible to the editor - it's possible that this certain classes of a module may not be loadable, so in that case we will end up using those best effort.
Note that I wasn't ultimately able to repro the reported issue, but doing some online searches I can see it is a not-uncommon issue, especially when you're enumerating every single visible asssembly like we are. Maybe it would be more appropriate to not handle the exception if we could scope our assemblies to just "MRTK" and "MRTK extending" ones, but there's no clean way of doing that.
=> Best-effort handle ReflectionTypeLoadExceptions in controller type assembly enumeration

pipelines/ci-release.yml, pipelines/templates/releasesigning.yml
Adds 'component governance' task for signing.
=> Add component governance task

Assets/MixedRealityToolkit.Extensions/PhotoCapture/HoloLensCamera.cs
This change ensures that accessing the frame pool in HoloLensCamera is thread-safe. Acquiring and releasing frames could happen from different threads, and simultaneous Acquire and Release would otherwise potentially corrupt the LinkedList being used to store frames.
=> Ensure that the HoloLensCamera pool of frames is thread-safe

pipelines/ci-release.yml, pipelines/ci.yaml, pipelines/pr.yaml, pipelines/templates/tasks/unitybuild.yml
=> Enable unity cache server for all builds

Assets/MixedRealityToolkit.Extensions/SpectatorView/Scripts/Calibration/CompositorWrapper.cs
=> fix uwp build

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
=> Wrap non-2019-compatible code

Documentation/GettingStartedWithTheMRTK.md
I wasn't prompted when opening the HandInteractionExamples. I think this was because I followed the steps in the previous section and was prompted then.
- Fixes: # .
>
>
> …
=> You may not get prompted

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs
UpdateSolverEntry already contains logic for handling the lifetime attribute in Solver, but SolverHandler only ever calls UpdateSolver.  
- SolverHandler now calls UpdateSolverEntry and setting a lifetime will now be respected in Solvers.
>
>
> commands …
=> Enable Lifetime setting in Solvers

README.md
Clarified the SDK version number vs the min required OS.
- Fixes: #4522
=> Add clarification on the SDK version vs desktop Windows version

Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.Android.prefab, Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.Android.prefab.meta, Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.HoloLens.prefab, Assets/MixedRealityToolkit.Extensions/SpectatorView/Prefabs/SpectatorView.ASA.HoloLens.prefab.meta, Assets/MixedRealityToolkit.Extensions/SpectatorView/Scenes/SpectatorView.ASA.Android.unity, Assets/MixedRealityToolkit.Extensions/SpectatorView/Scenes/SpectatorView.ASA.HoloLens.unity
Add scenes and prefabs into release
=> Code review followup

pipelines/templates/common.yml
Bringing over build step changes to the stabilization branch from #4389 and #4588.
=> Build step hotfix

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButtonHoloLens2.cs
Brings over the fix from #4624 to stabilization
- Fixes: #4615
=> Typo fix in PressableButtonHoloLens2.cs (issue #4615)

Documentation/GettingStartedWithTheMRTK.md
https://docs.microsoft.com/en-us/windows/mixed-reality/mrlearning-base
=> Added link to MR base module to GettingStartedWithTheMRTK.md

Documentation/InputSimulation/InputSimulationService.md
This question came up from some partners, and I noticed that these settings weren't documented.
=> Update the input simulation docs to explain a little more about camera control

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Change manip type for flattened bounding box from one handed to one and two handed:
- Fixes: #4749
=> Add two hand manip for flattened bounding box

Documentation/Diagnostics/ConfiguringDiagnostics.md
The docs are already somewhat comprehensive about editor-time visualization but don't provide instructions on how to access things via code.
=> Update the diagnostics system documentation to show how to programmatically access it

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/TouchHandler.cs
=> Add missing namespace to resolve asset retargeting failures

Documentation/GettingStartedWithTheMRTK.md
Documentation - Getting Started page update
Added clear instruction on 'how to reopen the scene'.  (feedback from the community)
Added a link to '[Text in Unity' guideline page.](https://docs.microsoft.com/en-us/windows/mixed-reality/text-in-unity)
=> Documentation - Getting Started page update

Documentation/ExperimentalFeatures.md, Documentation/toc.yml
- Fixes: #4828
- Also remove empty items QR code and Spatial audio from the Experimental toc.
=> Add experimental features guidance to documentation

Assets/MixedRealityToolkit.Examples/Version.txt, Assets/MixedRealityToolkit.Providers/Version.txt, Assets/MixedRealityToolkit.SDK/Version.txt, Assets/MixedRealityToolkit.Services/Version.txt, Assets/MixedRealityToolkit.Tests/Version.txt, Assets/MixedRealityToolkit/Version.txt, ProjectSettings/ProjectSettings.asset
We're patching the latest release with some pressable button fixes to make buttons work.
=> Update the version to RC2.1

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs, Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs, Assets/MixedRealityToolkit/Interfaces/Services/IMixedRealityCapabilityCheck.cs
Fixes doc generation error due to a badly formed xml doc tag.
=> fix bad xml doc tag

Documentation/README_TextPrefab.md
Fix links to point to github.com instead of github.io
- Fixes: #4939 
>
>
>
>
=> Fix links on text prefab documentation

pipelines/ci-packaging.yml, pipelines/ci.yaml, pipelines/templates/ci-common.yml
Quick fix for the templates - it turns out the variable expansion didn't work for the packagingEnabled parameter.
=> fix packagingEnabled pipeline parameter

Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/ball.mat, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/ball.mat.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/floor.mat, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/floor.mat.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/wall.mat, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Materials/wall.mat.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scenes.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scenes/ManipulationHandlerExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scenes/ManipulationHandlerExample.unity.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scripts.meta, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scripts/ChangeManipulation.cs, Assets/MixedRealityToolkit.Examples/Demos/UX/ManipulationHandler/Scripts/ChangeManipulation.cs.meta, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
ManipulationHandler now has a ForceEndManipulation that will end the currently active manipulation state and release the object
- change includes sample scene and playmode unit test
- Fixes: #4584 
Added sample scene that shows functionality
Moving sphere into the wall will call ForceEndManipulation
=> added ForceEndManipulation to ManipulationHandler

docfx.json
cleaned up docfx yml config file
Changes
- Fixes: #5059
=> removed obsolte doc paths, fixed paths to home button and favicon

Documentation/Contributing/DevDocGuide.md, Documentation/Contributing/UnitTests.md, Documentation/toc.yml
new documentation page about unit testing of mrtk
updated the coming soon part of docfx doc and added a little chapter about CI runs of docfx in github
- Fixes: #5066
=> added unit test documentation and updated docfx docs

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/CustomProfiles/HandInteractionGestureEventsMixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/CustomProfiles/HandInteractionRecordArticulatedHandPoseMixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Dictation/Dictation.MixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.MixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Profiles/Interactable_MixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityToolkitConfigurationProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2ConfigurationProfile.asset
#4858 changed the assembly names for two systems, but didn't update all the profiles.
=> Fix CameraSystem and SceneSystem assembly name references in profiles

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
=> BoundingBox Nullcheck removal

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystemEditorOperations.cs, Assets/MixedRealityToolkit/Definitions/SceneSystem/MixedRealitySceneSystemProfile.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySceneSystemProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoDrawer.cs
=> Fixes scene system profile inspector to better reflect state of build settings

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Tooltips/ToolTip.cs
Fixes ToolTip background plane size issues.
- Fixes: #4447, #5126
Leaving this as a draft until it's been tested on multiple devices.
>
>
=> Fixes ToolTip background plane size issues

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableUnityUI.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityRaycastHit.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/Services/BaseEventSystem.cs
This reduces allocations from ~15k per frame to ~100 bytes per frame, depending on what's going on in the scene.
- Fixes: #5107
- Debug.Assert has been replaced with if / Debug.LogError in cases where string formatting was used. String.Format was being invoked even when the asserts passed.
- BoundingBoxHelper no longer allocates new arrays for every operation.
- FocusProvider now uses SphereOverlapNonAlloc. A new FocusQueryBufferSize field has been added to the input profile. This follows the pattern established in PokePointer.
- NearInteractionTouchableUnityUI.Instances no longer returns a read-only collection. We simply iterate over the list.
- Removed Linq from BaseEventSystem.
- ~~We now omit lightmapCoords in MixedRealityRaycastHit by default via a preprocessor directive. Including …
=> Performance optimization with emphasis on HandInteractionExamples

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Reverts microsoft/MixedRealityToolkit-Unity#5132
=> Revert "Fixes build error when a scene with MRTK instance is open in editor"

Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseCursorTests.cs
This reverts commit 1d057749b4680cc0bad0657c23401b8697bcc084.
Reverting tests to a state that passed on CI
=> Revert "Some test changes"

Assets/MixedRealityToolkit.Tests/PlayModeTests/Components/FocusRaycastTestProxy.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Components/TestPointer.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderRaycastTests.cs
#4722 introduced some documentation that broke the docs build.
=> Fix crefs that were breaking the docs build

Assets/MixedRealityToolkit.Tests/PlayModeTests/DemoSceneTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/DemoSceneTests.cs.meta, ProjectSettings/EditorBuildSettings.asset
Adds a test to load and play HandInteractionExamples scene. Checks to ensure MRTK input system has been initialized.
Experimented with adding scenes to build settings prior to build via IPreprocessBuild but was unsuccessful. Instead I've added the test scene to the default build settings.
- Fixes: #5200
>
>
=> MRTK Demo Scene Loading Tests

Assets/link.xml.meta
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5274
Previous change forgot to include the .meta which gets generated by unity automagically
=> Add in the missing link.xml.meta

Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
change that got in between opening my last PR and completing caused compile error with new imports in test class
- Fixes: build error
=> fixed build - new import will cause conflight in Object usage

Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
added test for verifying triggering a button with far interaction
- part of  #4728
=> added test for checking far interaction click on button

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/FingerCursor.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Update finger cursor position calculations to match shell.
- Fixes: #4559.
=> Change finger cursor position to match shell

Documentation/toc.yml
=> adding link to the dependency window doc

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/BaseInputHandler.cs
=> Make BaseInputHandler.Update virtual

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Receivers.meta
The folder was deleted but the .meta file was not cleaned up.
=> Remove an unused meta file

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs
=> Offset calculation

Documentation/UpdatingToGA.md
Final fix for updating docs to deprecated component
- Fixes: #5251 
>
>
>
>
=> Adding pointerclickhandler to docs

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/ClippingExamples.unity.meta, Assets/MixedRealityToolkit.Tools/ReserializeAssetsUtility.meta, Assets/MixedRealityToolkit.Tools/ReserializeAssetsUtility/ReserializeAssetsUtility.cs, Assets/MixedRealityToolkit.Tools/ReserializeAssetsUtility/ReserializeAssetsUtility.cs.meta
This PR adds a version of the tool provided in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4914 to the repo, under our new Tools directory.
- Related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4914
=> Add ReserializeAssetsUtility

Documentation/GettingStartedWithTheMRTK.md
=> Typo in the title

pipelines/ci-packaging-dontpublish.yml
Fixes the name of a pipeline template
=> fix template name error

Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec.meta, Documentation/GettingStartedWithTheMRTK.md, Documentation/Packaging/MRTK_Packages.md, scripts/packaging/unitypackage.ps1
Adds a nuspec file allowing the extensions folder to be packaged separately from the foundation.
=> add nuspec for extensions folder

Documentation/KnownIssues.md, Documentation/toc.yml
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5469
While we track all of our issues on github, there are some that folks may hit more often - for the ones that are both common and have workarounds (where the real solution may be somewhat in the future) having this known issues page can be helpful.
=> Add a known issues page to the MRTK.

Documentation/GettingStartedWithTheMRTK.md
Sending on behalf of @rwinj in PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5444.
It looks like there were merge conflicts in that PR and I'm trying to close out older PRs
=> Updated the reference to HL2 tutorials
