Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/DefaultPrimaryPointerSelectorTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/GazePointerStateMachineTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/TestFixture_03_InputSystemTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/DemoSceneTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityCursor.cs, Assets/MixedRealityToolkit/Services/BaseEventSystem.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
This change has originally been triggered by #5116 to first of all ease test debugging, when test runtime environment is not clean after running another test.
So, the change should only have been messages in `BaseEventSystem`. However, adding these messages highlighted few fundamental issues:
* Mrtk had incorrect order of deinitialization for core systems. They should be disabled and destroyed in a reverse order to how they are initialized. This PR fixes that.
* Unregistering event handlers in unity `OnDestroy` is semantically incorrect: Mrtk tear down happens in the middle of `Update` loop, which Deinitializes and Destroys all global services. When components are then destroyed _in the end_ of the `Update` loop, they can't rely on valid state of services (e.g. Input System). Ideally we …
=> Add error logs on destroying event system with dangling listeners

pipelines/templates/ci-common.yml, pipelines/templates/publishpackages.yml, pipelines/templates/tasks/unitypackages.yml, scripts/packaging/unitypackage.ps1
Build.ps1 has been out of commission for a while now, and building .unitypackages has been a manual step for us prior to release.
This change removes build.ps1 and moves some of its functionality into a script that is just designed to do .unitypackages, and in a way that is also compatible with the way the rest of our pipelines work now.
This also updates our CI pipeline (not PR pipeline) to generate .unitypackage artifacts in the build (the Foundation and Examples package)
=> Reintroduce .unitypackage building into our build system

Assets/MixedRealityToolkit/Inspectors/ExtensionTemplates/ExtensionServiceWizard.cs
Change link to documentation page dedicated to service extension wizard
- Fixes: #4740 
Clicked the button, new url
=> Fix documentation link for service extension wizard

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs
=> Fixes MRTK inspector setting active instance when selected instance is disabled

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Spawning the PressableButtonHoloLens2 into the scene at runtime led to a short flicker caused by the SeeItSayItLabel being visible during the first frame. This is caused by the button updating its internal state the first time during Update, missing out Start.
This fix updates the internal State on Start, letting the Button appear smoothly.
=> Mrtk Interactable Update before first frame

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystem.cs, Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystemEditorOperations.cs, Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/FocusProviderInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/Microsoft.MixedReality.Toolkit.Editor.ServiceInspectors.asmdef, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/SceneSystemInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/ServiceFacadeInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/SpatialAwarenessSystemInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/TeleportSystemInspector.cs, Assets/MixedRealityToolkit/Interfaces/SceneSystem/IMixedRealitySceneSystemEditor.cs, Assets/MixedRealityToolkit/Interfaces/SceneSystem/IMixedRealitySceneSystemEditor.cs.meta
Service inspectors now work with service interfaces instead of concrete implementations.
For most inspectors this change was trivial. For `IMixedRealitySceneService` an optional `IMixedRealitySceneServiceEditor` interface was created for editor-only functionality used by the inspector.
- Fixes: #4825
>
>
=> Removes dependencies on individual service binaries from service inspectors

Documentation/MixedRealityConfigurationGuide.md
The doc contains a lot of references to things that are coming soon, and while we have items in the backlog to improve these, not all of these are going to be coming in the immediate future. It's misleading and confidence-draining to see things always listed as coming soon, so it's better to have our docs just say what the current state of things are.
=> Update the configuration guide to remove references to things coming soon.

scripts/packaging/unitypackage.ps1
I was looking at the output from the latest CI runs, and while there was the presence of the Foundation unity package, the examples package was missing:
It turns out, this exit statement was too aggressive, and was leading to us only building the Foundation package. Now we will only early exit in the case of failure.
=> Update the unitypackage.ps1 to actually build the examples package.

Documentation/README_Solver.md
Looking at this page, it seems like the link wasn't actually being formatted because it was too close to the sun (the image preceding it).
Adding another line in there makes it actually render the link and be all good.
=> Fix a broken link/non-formatted section

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityFocusChangedHandler.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/Handlers/IMixedRealityFocusHandler.cs
I was spending time updating the Periodic Table app from RC2 -> GA, and while mostly things were working, I noticed that this assert was firing (it was added after RC2.1) pretty much every time you had a near pointer around the molecule object. It turns out, there's an issue in the heirarchy of the app itself that leads to this issue, but I was initially super confused about this, since this assert seems bad, but there's really not that much guidance on how to fix it and what's wrong.
To that end, I've updated the assert to suggest where to look (i.e. the common case) and also updated the doccomments associated with the corresponding interfaces to provide more information about both state transition mechanics, and also the general warning to be careful about having different nesting …
=> Update the assert text to be more helpful, and update the doccomments of the focus handler interfaces.

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
There are occasions where the EditorBuildSettings enumerates all scenes, regardless whether they are missing or not. In that case the scene is reported as enabled, though has an empty path. The build process later fails, as is cant' find the scene at `""`. Therefore better be safe than sorry and filter out scenes that have an empty path.
=> Fix build failure due to empty scene paths

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs
The build pipeline sometimes produces `.msix` or `.msixbundle` package files instead of `.appx`. When trying to deploy those packages they're obviously not found by the MRTK deploy pipeline.
=> Add support for .msix package files

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
The host object position with one-handed near interaction was computed incorrectly, leading to the object drifting off the grab point when rotating.
The host position `P_h` should be computed such that the GrabPoint `P_g` of the controller stays fixed in space. For that purpose the _initial_ grab point (at the start of the manipulation) is computed in local host space:
```
L_g = R_h^T * (P_g - P_h)
```
where `R_h^T` is the inverse host rotation. The local grab point `L_g` is constant during manipulation, since we want the object to remain grabbed in the same place.
During manipulation the host rotation `R_h` is computed first. To then get the world space position `P_h` of the host can use the given world space grab point:
```
P_g = R_h * L_g + P_h
<=> P_h = P_g - R_h * L_g
```
- Fixes: …
=> Compute correct hostTransform position when rotating with one hand.

README.md
Our README intro was a bit wordy so I tried tightening it up a bit. Also moved the getting started table above the fold so people can see it without scrolling
=> Homepage README edits, move getting started higher

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/LinePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/ShellHandRayPointer.cs
The hand ray / line pointer should not be visible when IsInteractionEnabled == false, otherwise it looks to the user like he/she can manipulation content with rays when she cannot. For example, when hands are facing the user, we set IsInteractionEnabled to false to avoid users grabbing things unintentionally.
This change fixes the LinePointer and ShellPointer code to not render lines when IsInteractionEnabled == false.
* Fixes: #4377 
* Don't render line if !InteractionEnabled
* Refactor ShellRayPointer to take advantage of inheritance. Previous code was just a copy/paste of base classes.
* Improve readability by reducing extra lines / logic and moving variable declaration closer to variable use
* Tested in editor
* Not yet tested on device (need to test on HL2)
=> Turn off hand ray visuals if hands not facing you / interaction is not enabled

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
#Overview
The bounding box component now manages the rig it creates and destroys the rig on destruction and disablement. This bug is especially apparent when adding/removing bounding boxes dynamically. 
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5383
Tested in the BoundingBoxExamples, BoundingBoxRuntimeExample, and HandInteractionExamples scenes.
>
>
>
=> Bounding Box Rig GameObject Management

Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHandDataProvider.cs
Prior to this fix, when using gestures (GGV) style interactions, you would run into this bug:
1) Press space bar to engage the hand simulation.
2) Hold down left mouse to engage pinch.
3) Hold down the right mouse to rotate the camera.
4) Lift the left mouse to disengage pinch.
Step #4 wouldn't work (it would stay engaged in the pinch until you lifted the right mouse button) because the existing code would see that the right mouse button was down, and even though it was not configured to do anything (i.e. a configuration of "none" means "don't affect the state of the gesture simulation"). However because the function returned "none", this told the rest of the code to keep doing what it was doing before (which was, simulating the pinch gesture associated with the left mouse click.)
You …
=> Fixes gesture pinch release mechanics involving two mouse button interactions.

Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionServiceProfile.cs, Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/SpatialObjectMeshObserverProfile.cs, Assets/MixedRealityToolkit.Services/InputAnimation/MixedRealityInputRecordingProfile.cs
This change consolidates duplicate asset menus and places all profile options into the profile menu.
Before:
After
=> Fix MRTK asset menu layout / remove duplicate menu

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
It turns out that the existing logging isn't very helpful, because the inner message isn't logged. Thus, if the client here is creating something and has an exception in their code, all they will see right now is a TargetInvocationException, instead of a real callstack associated with their code.
This is SUPER hard to debug (you have to know to turn on all managed exceptions) so hopefully this increased logging will help clients figure out what happened when we try to new their objects up.
=> Add a somewhat helpful message on CreateInstance failure.

Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Scenes/InteractablesExamples.unity, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/Model_BuckyTheme.asset, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableReceiverListInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/ThemeInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/InspectorUIUtility.cs
This change does two primary things:
1) Modifies interactable inspector to be visually more in line with other components in Unity (see details below)
2) Fix interactables example scene
**Inspector changes:**
-> Added documentation link and goes to interactable readme
-> Converted existing "box" style to helpbox style which matches Unity and MRTK profiles
-> Removed redundant title of profile target (i.e gameobject being targeted) and just left target property field
-> Reduced amount of indentation, also cleaned up indent usage in code
-> Updated Events title to be a section foldout so we can hide long lists of receivers
-> Changed "Interactable" title to "General" since "Interactable" label is already listed right above for the component and thus reduces redundancy
-> Removed dividers …
=> Interactable scene & inspector updates

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshLevelOfDetail.cs, Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/Observers/IMixedRealitySpatialAwarenessMeshObserver.cs
This is a minor breaking change (values in the SpatialMeshLevelOfDetail enum) to eliminate direct triangles per cubic meter encoding in the enum.
This change adds a Medium LOD as well as a lookup method in the windows mesh observer.
Verified by changing the LOD in the observer profile and deploying / running on HoloLens.
=> Update spatial mesh level of detail values, translate in observer

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityGGVHand.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit/Inspectors/ControllerPopupWindow.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs, Documentation/UpdatingToGA.md
This PR redefines the clicker from an unhanded `WMRController` to an unhanded `GGVHand`, to better define and update the clicker (it's much closer to a HL1 hand to a motion controller). This both prevents irrelevant code (attempting to load the controller model) from running and better scopes the actions a clicker can actually perform.
As part of this, it adds a profile updating step that will run automatically the first time a controller mapping profile is opened.
- Fixes: #5397, #5287
1. Run on HoloLens 1.
2. Try using a clicker to select objects
3. Try using voice to select objects.
=> Add better support for HoloLens clicker

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
The build tooling currently has some issues finding instances of msbuild (especially on certain VS2019 installs)
This change adopts the change @julianloehr-kg from:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5356
With a modification to still fall back to the old one if the new one fails (this can happen if building in VS2017, like what happens on our build machines).
Thanks to @julianloehr-kg for this!
=> Update the build tools to use the new vswhere flag to find msbuild

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Panels/ToggleFeaturesPanel.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Slate/Slate.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/RadialView.cs
To achieve shell-parity 'Follow Me' behavior, added vertical position lock option to the Radial view Solver. Radial view already had min/max distance/degree allowance which allowed shell-style 'lazy following' behavior. We just needed to a way to lock vertical position. With original Radial view, object also moved vertically following the headset movement.
- Applied updated Radial view Solver to Slate.prefab and ToggleFeaturesPanel.prefab
- Optimized the min/max distance/degree allowance of the Radial view Solver to match shell behavior
Part of #4200 [MRTK Shell Parity] UX Controls Parity with HoloLens 2 Shell
- #5380 Toggle features panel solver moves menu directly in front of face
- #4983 [MRTK Shell Parity] Follow Me behavior does not match the shell
- #5393 [Solver] Add …
=> [Shell-Parity] Radial Solver update for the 'Follow Me' behavior

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/MixedRealityKeyboard.cs
It was only designed to handle the HL2 workaround, so we should at least write this down.
Note that there is more work here to make the general system keyboard example script work in immersive/HL1 cases.
=> Update the MixedRealityKeyboard doccomments to reflect the platforms it was intended for.

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/GestureEventsConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/GestureEventsInputSimulationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/GestureEventsInputSystemProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/RecordArticulatedHandPoseConfigurationProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/RecordArticulatedHandPoseInputSystemProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Profiles/RecordArticulatedHandPoseSpeechCommandsProfile.asset, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/TetheredPlacement.cs
When resetting the transform of the coffee cup in the HandInteraction example scene, the rigidbody was not being reset and thus whatever velocity/momentum was attained by falling is kept. If the physics breaks and the coffee cup goes so fast it falls through the counter, it will keep never-ending increasing in velocity. 
This change also fixes some asset renames for MRTK profiles from another previous change (See .asset files)
- Fixes: #5382 
Drop cup and now doesn't retain velocity
>
>
=> Fix coffee cup drop and update profile assets

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
These changes will make it that most manipulation options will rotate around the grab point for all types of interaction. This means that in most cases, it will not matter that the origin is not at the mesh centre. With smoothing this can still look weird if scaling or rotating quickly, however the object ends up where you expect it to go. 
As I've mentioned [here](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4910#issuecomment-513267204) I wasn't convinced that we should take these changes. There are better ways to do this, but they would require an overhaul of the `ManipulationHandler`, which is not a change we can make right now.
- Fixes: #4910 
- Overhaul of `TwoHandMoveLogic` so that it works for rotate around grab point.
- New `TwoHandMoveLogic` now works for one …
=> Fix manipulation offsets for when origin not mesh centre

Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs
While #5242 was approved, a slight mistake slipped in this corrects.
The deleted code lines went into the original MousePointer directly as they are not needed for the new SpatialMousePointer.
Without these gone, the spatial mouse suffers from being disabled and overlayed by the notification
=> Mrtk spatial mouse cursor amendment

Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
When ingesting MRTK for the first time (especially via git) you'll see an ArgumentException warning, which happens as MRTK is figuring out where its files are being placed. This shows as an error but is actualy benign (i.e. it happens in some processing of UPM packages that have no effect on the MRTK).
The cause here was an overly aggressive .Replace call - it replaced ALL instances of "Asset" with the application asset path (even when Asset was showing up much later in the path). It was really only intending to replace the prefix "Asset" string, so this fixes it to only do that.
=> Resolve the ArgumentException error in MRTK+Unity startup

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs, Documentation/InputSystem/HandTracking.md
There is currently a known issue with Master builds using the .NET backend. In .NET Native, `IInspectable` pointers cannot be marshaled from native to managed code using `Marshal.GetObjectForIUnknown`. The MRTK uses this to obtain the `SpatialCoordinateSystem` in order to receive hand and eye data from the platform.
Native source PR: https://github.com/microsoft/MixedRealityToolkit/pull/228
We are not shipping the binaries precompiled in this case, but users who need them can compile them themselves from the native source repo.
- Fixes: #4340 
1. Build the binary from the native repo
2. Include it in your plugins folder
3. Build the .NET backend as Master and deploy to your HL2.
4. Verify that hand joints properly render (the HandInteractions example scene is good for this).
=> Add workaround for hands/eyes on .NET Native

Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1CameraProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1CameraProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1ConfigurationProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1ConfigurationProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1HandTrackingProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1HandTrackingProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSimulationProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSimulationProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSystemProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSystemProfile.asset.meta
By default the MRTK config profile assumes articulated hand input using HoloLens 2 style hand rays + direct interaction, however many people using MRTK are still deploying to HoloLens 1. People often ask how they can [simulate HoloLens 1 style interactions in the Unity Editor](https://stackoverflow.com/questions/56821449/hl1-input-for-mrtk-v2-1).
People building and deploying HoloLens 1 apps can use this configuration in their MRTK.
This change adds an MRTK profile that people can use to simulate HoloLens 1 style GGV interactions.
Fixes: #5046 
* New profile to simulate HoloLens 1 interations.
* Profile uses "gesture hand" for input simulation, not the articulated hand
* Set Camera Clipping plane for HoloLens 1 to 0.3 per comfort guidelines at …
=> Config Profile for HoloLens 1

Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs, ExtensionTemplates/ExtensionInspectorTemplate.txt, ExtensionTemplates/ExtensionInterfaceTemplate.txt, ExtensionTemplates/ExtensionProfileTemplate.txt, ExtensionTemplates/ExtensionScriptTemplate.txt
1. ExtensionServiceCreator ignores namespace supplied by user, always takes default instead
2. ExtensionServiceCreator creates inspector even when "Generate Inspector" is unselected
1. ExtensionServiceCreator now uses NameSpace in stead of DefaultExtensionNamespace while creating the files. This also required adaption of the template files as those now have a missing "using" on top now they are no long in Microsoft.MixedReality.Toolkit.Extensions;
2. Added simple "if(UsesInspector)" around creation of inspector. This was read from the UI and clearly intended to use for this, but was not checked
=> Fixes two omissions in the ExtensionServiceCreator

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicBackPlateToggleState.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicBackPlateToggleState.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Toggle.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Toggle.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonToggleStateOff.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonToggleStateOff.asset.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonToggleStateOn.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonToggleStateOn.asset.meta
Currently, MRTK only has HoloLens 1 style toggle button. Adding HoloLens 2 shell-parity Toggle button.
- Created a new prefab variant **PressableButtonHoloLens2Toggle.prefab**
- Added related theme files and material
- Fixes: #5254 
Added additional quad for visualizing the toggle state(sky blue). The visibility is controlled by PressableButtonToggleStateOff and On theme files.
=> [Shell Parity] Adding HoloLens 2 shell-parity Toggle button

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/ClippingExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Slate/SlateExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Text/Scenes/TextPrefabExamples.unity, Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/ProgressIndicatorLoadingBarEmpty.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/ProgressIndicatorLoadingBarFilled.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorLoadingBar.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorLoadingBar.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorRotatingObject.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorRotatingObject.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorRotatingOrbs.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/ProgressIndicators/ProgressIndicatorRotatingOrbs.prefab.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorLoadingBar.cs.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorObjectDisplay.cs.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorOrbsRotator.cs.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1CameraProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1ConfigurationProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1HandTrackingProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSystemProfile.asset.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/3DTextSelawik.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/3DTextSelawikBold.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/3DTextSelawikLight.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/3DTextSelawikSemibold.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/3DTextSelawikSemilight.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/UITextSelawik.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/UITextSelawikBold.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/UITextSelawikLight.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/UITextSelawikSemibold.prefab.meta, Assets/MixedRealityToolkit.SDK/StandardAssets/Prefabs/Text/UITextSelawikSemilight.prefab.meta
A few files from the HoloToolkit were migrated to MRTK v2 post RC2.1 without their GUIDs being regenerated. This PR regenerates them and replaces their references.
Also regenerates the profile GUIDs added in #5431, which matched their HL2 profile counterparts.
This would be a breaking change for anybody actively consuming the dev branch, but does not break anybody using RC2.1
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5122#issuecomment-514980114
=> Regenerate some GUIDs to prevent HTK -> MRTK collisions

Assets/MixedRealityToolkit.SDK/Inspectors/Utilities/Solvers/SolverInspector.cs
Updates to build automation identified SolverInspector as not being in the correct namespace. In fact, it was not in _any_ namespace.
This change adds the class to the Microsoft.MixedReality.Toolkit.Utilities.Editor.Solvers namespace with other, related, inspectors.
=> Add namespace to SolverInspector

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/InteractiveMeshCursor.cs
We override UpdateCursorTransform in some of our custom cursor classes, and I wanted to be able to use the lerp functionality of the BaseCursor class without having to duplicate it. It's a pretty small change, and we can workaround it easily enough if it's not generally useful (but I thought it might be at least).
=> break out BaseCursor's target lerp functionality to make it accesible to derived classes

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/AnimatedCursor.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/BaseCursor.cs, Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs
We mostly handle cursor management on our own, and use a single cursor instance which gets passed around to whatever pointer is active at a given time. This was causing some problems as some of the cursor code assumes a pretty strong pairing between cursor and pointer, so I've made some changes to hopefully make it a little more flexible without any detrimental effects on the normal usage.
1. Various pointer/cursor null-checks so things don't break when they are detached from one another.
2. Make visibleSourcesCount and SourceDownIds refresh at certain points so that they don't get out-of-sync if the cursor missed some source state events.
=> modify BaseCursor to better handle swapping between pointers

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
If a core system is enabled but the service type is null or a profile object is not assigned, then the service will not be initialized by the MRTK gameobject. This happens silently without any warning or notice to users.
This change is in the MRTK configuration profile inspector that checks whether a system is enabled but not valid to be initialized. If so, then a warning message is displayed in the MRTK inspector.
- Fixes: #3094 
>
>
=> Add warnings for invalid system configurations

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/SystemKeyboardExample.cs
When running the HandInteractionExamples the Unity log is spammed with null reference exceptions from the SystemKeyboardExample due to the debug text not being set up in the inspector. This pull request address this by assigning the reference and performing runtime checks.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5501
1. Run the HandInteractionExamples on a HoloLens 2.
2. Download the UnityPlayer.log
3. Verify no exceptions from Microsoft.MixedReality.Toolkit.Examples.Demos.SystemKeyboardExample.Update
>
>
>
=> Fixing Null Reference Exception in SystemKeyboardExample 

pipelines/templates/ci-common.yml
There was an errant $ character in the ci template file that was merged from the stabilization branch.
Stabilization did not hit this as it does not publish packages as part of CI. Will cherry-pick this change there as well.
=> Fix typo in ci template

Assets/MixedRealityToolkit/Definitions/Utilities/ArticulatedHandPose.cs
A previous change to this updated an existing enum by adding a value in the middle of the enum - this is backwards incompatible because the same value is persisted in various profiles, where enums are stored as integer values, rather than string values.
This means that something that used to refer to "pinch" now referred to this new thing, and the same off-by-one problem would affect all of the other options below the new enum
See change:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5495
Original issue:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5450
Current issue:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5506
=> Fix the backwards-incompatible enum change

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
This change prepares for the RTW (release to world) for MRTK v2.0 by removing debug log warnings that are not actionable by the developer (system or app developer).
This addresses #4277
=> Pre-RTW cleanup: remove unactionable debug log messages

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonIconFontMaterial.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonIconHandJoint.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonIconHandMesh.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonIconPin.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicButtonIconProfiler.mat
A handful of materials are using the GUI/Text Shader which does not respect the depth buffer. This results in icons drawing though other objects. This icons should use the MRTK/Standard shader and be marked as TransparentCutout or Transparent.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5521
1. Open the HandInteractionExamples scene.
2. Look at the ToggleFeaturesPanel from the backside.
>
>
>
=> Fix Icon Materials that Don't Respect Depth

Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1CameraProfile.asset.meta, pipelines/templates/tasks/unitybuild.yml, scripts/ci/validatebuildlog.ps1
Recently we hit an issue in the MRTK where we had duplicate GUIDs checked in for a few different assets:
#5431
The root issue here was that the meta files were copy pasted, instead of being regenerated at the new location. There was a warning in the console but it was ignored, and since Unity will non-deterministically choose one of them (i.e. either of the duplicate GUIDs could be right) - you end up with cases where you will get one or the other of the assets (and hopefully Unity choose correctly for you!)
I looked into doing a custom logger (i.e. catching LogWarning) but found that it doesn't run soon enough (i.e. warnings will show up, this code will get compiled) so this had to resort to editor-log parsing.
In theory this could be extended in the future to other issues that we hit …
=> Update the build system to have a hook to check for validation errors in the MRTK build

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PhysicalPressEventRouter.cs
-added forcethemeupdate in interactable OnEnable to ensure the right theme is used on reenabling an interactable
-added missing physicaltouch set in handPressCompleted of physicalPressEventRouter
- rearranged if in untouched event in event router so it's behaving like the other events in that class
- Fixes: #4528
- run tests
- todo: device tests
=> fixed button highlights for buttons that use themes on leaving button sideways and disabling button

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Solver.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SurfaceMagnetism.cs, Assets/MixedRealityToolkit.SDK/Inspectors/Utilities/Solvers/SurfaceMagnetismInspector.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs, Documentation/README_Solver.md, Documentation/UpdatingToGA.md
This change fixes a faulty orientation setting in SurfaceMagnetism as well as provides clearer naming & documentation.
Fixes: 
- The Blended mode for OrientationMode in SurfaceMagnetism is supposed to blend rotation input calculated via the Tracked Transform and the normal at the surface hit point. The code was actually only blending between the current model rotation and the tracked transform rotation. And thus, the OrientationBlend property had no impact what so ever.
- Furthermore, the original OrientationMode *Vertical* in documentation is supposed to face the tracked transform (i.e user etc) but actually faced along the surface normal. 
- To simplify implementation, the property *KeepOrientationVertical* was added to give user's more control for their chosen OrientationMode (see …
=> Updates to fix SurfaceMagnetism orientation

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Currently, if the ActiveProfile field is null for the active MRTK instance, then the MRTK system will frustratingly do two things at the editor level:
1) Block the user from entering play mode ever 
2) Spam user to select a profile whenever the MRTK object is selected in the inspector
This change addresses the issue by warning the user but allowing them to continue unimpeded. 
- The entering playmode is only aborted if the developer selects "OK" with the new dialog warning
---> If user selects Ignore, then warning dialog will never be shown again for this Unity session
- The profile object picker is only shown if the user clicks the "Assign MRTK profile" button or they click "Add mrtk to scene & configure". 
- If ActiveProfile is null, then an error message is rendered in the inspector
- …
=> Avoid blocking developer when ActiveProfile null in Editor

README.md
Currently, stabilization won't merge cleanly into mrtk_release due to docs changes that happened in master that differed slightly from the changes made to mrtk_dev.
This merges those docs in and adds some markdown formatting updates as well.
I also migrated apllied the changes in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4096 to the documentation generation status as well, which is currently reporting "never built"
=> Merge mrtk_release docs into stabilization

pipelines/templates/compilemsbuild.yml
Previous PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5516 updated the way that the solution got named, but missed the pipelines YAML file that also referenced the same thing.
This should fix the build where it's failing at this step:
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=3969
MSBUILD : error MSB1009: Project file does not exist.
Switch: f:\aipmragent_work\9\s\MSBuild\Projects\MRTK.sln
=> Fix the broken CI build.

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs
Fix for issue #5423 [Controllers shown at original place after teleporting in VR.](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5423)
This fix addresses the issue #5423 [Controllers shown at original place after teleporting in VR.](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5423)
The fix is in the BaseController.cs file.
In the function:
protected virtual bool TryRenderControllerModel(Type controllerType, InputSourceType inputSourceType)
we add MixedRealityPlayspace.AddChild(controllerObject.transform);
This line should actually be moved inside TryAddControllerModelToSceneHierarchy function
so that even if we use the platform controller visualization, they will be correctly added to under MixedRealityPlaySpace game object.
=> Fix for issue #5423

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
This is largely a formatting / cleanup pass on GGVPointer, found as a result of my work on #5528.
Mostly, there was an interface that had entirely empty events. It also had a `Start` method that only called the base.
1. Make sure GGVPointer still works.
=> Remove unused events, interfaces, and patterns from GGVPointer

Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseCursorTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/TestHand.cs
I think while waiting for fixed update after setting the hand gesture in this test, the cursor state would transition to `Release` and then proceed to change to `InteractHover` before the test got a chance to verify the `Release` state.
This change gives us tighter control of the simulation so the test can verify the `Release` state before it changes again.
- Change the TestHand interface so that waiting for fixed update is optional. 
- Change ArticulatedCursorState so that we do not WaitForFixedUpdate when testing for cursor release.
- Ran test locally 160 times without changes and got a 6.25% failure rate, which approximately matches what we see on CI.
- Ran test locally 160 times with changes and got a 0% failure rate.
- Need to run PR validation.
=> Don't WaitForFixedUpdate for cursor release

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
Modified the TwoHandMoveLogic class to more closely match the TwoHandRotateLogic class in terms of passing in constraints to the Update function (allowing for a more flexible ManipulationHandler). 
This is needed so that the movement constraint type can be dynamically changed on the ManipulationHelper during runtime, so consumers of the SDK don't need to have several ManipulationHandler components on the same object for different movement constraint types. 
- Removed the constructor for TwoHandMoveLogic that passed in and defined the MovementConstraintType for the lifespan of the TwoHandMoveLogic component
- Modified the Update function to require a MovementConstraintType object to be passed in whenever called so it allows developers to use the same component for multiple types of …
=> [BugFix] Modified TwoHandMoveLogic to have parity with TwoHandRotateLogic in that the MovementConstraintType can change during runtime

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs, Assets/MixedRealityToolkit/Services/BaseDataProviderAccessCoreSystem.cs
Recently, a regression was introduced that caused data providers to not be enabled. Windows Mixed Reality controllers (including hands) rely on Enable to register for platform events.
This PR fixes this and a related error in the new core service base class.
Added calls to base class methods in input and spatial awareness systems.
Fixes: #5557
Verified running on Windows Mixed Reality immersive device.
=> Fix 5557 - Hand / controller input broken

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs
Running this code in the context of the deployed device will trigger an error (in the console) about failing to load a perception remoting binary. It turns out that calling https://docs.unity3d.com/ScriptReference/XR.WSA.HolographicRemoting.ConnectionState.html (which we do) will trigger this load attempt. Wrapping this in a UNITY_EDITOR ifdef to prevent us from trying to do this on device (where this workaround isn't necessary)
=> Update the holographic remoting workaround is only limited to editor scenarios.

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/RadialSet.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
You should be able to hover over radial buttons without getting debug asserts. I fixed this bug, added a test to verify the fix, fixed another issue highlighted by the test, and fixed a third logic issue I discovered just by reading the code.
- Fixes: #5553
- Add test to validate fix (verified that test does not pass without fix, and passes with fix)
- Test uncovered issue: IsToggled returns incorrect value when radial button instantiated. Fixed.
- Fixed another logic issue: bitwise AND was being used instead of boolean AND.
* Tested in editor
* Playmode tests pass.
=> Fix Debug.Assert when hovering over radial set buttons

Assets/MixedRealityToolkit.Examples/StandardAssets/Prefabs/Reticle.prefab
The Reticle's material was deleted, but its reference wasn't updated. This updates it to the MRTK_Standard_Gray shader.
=> Assign material to Reticle.prefab

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset
#5549 pointed out that the menu button mappings for the Windows Mixed Reality Motion Controllers were incorrect when running on OpenVR.
This was a result of the button identifiers being entered backwards (left as right, right as left) in the .cs and .asset files.
Verified using customer provided script, running both UWP and OpenVR targets in the editor and examining the debug console output.
=> Fix button mappings for WMR controllers in OpenVR - 5549

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Green Gem and MRTK Logo Slate in HandInteractionExample will immediately scale the mesh down on two-handed manipulation with hand ray.
Fixing the issue by properly assign the target object to the ManipulationHandler.
- Gem had wrong target object assigned to ManipulationHandler
- MRTL Logo Slate had missing target object in the ManipulationHandler
- Fixes: #5569 
prelease
=> Fix5569 Green Gem in HandInteractionExample will immediately scale the mesh down on interactio

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/TestCanvas.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/UnityUIBackground.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/UnityUIBackground.mat.meta
Minor changes to improve shell parity. Making the Unity UI example canvas background not semi-transparent and adding a proximity cursor shadow.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5586, and the shadow ask in this bug https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5587
Please try the UnityUI example in the HandInteractionExamples scene.
>
>
=> Making the Unity UI example canvas background not semi-transparent and adding a proximity cursor shadow.

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Some of the descriptions are not relevant on some platform/devices. Updated text to avoid any customer confusion.
- **Touch Interaction**: Only works on Hololens 2 with articulated hands
- **Launch External apps**: HoloLens 2/WMR can display apps in Unity apps. Hololens 1 exits the current app then launches the external app
- Other description updates to clearly communicate the examples
- Some Layout updates related to these text updates
- Removed the Bounding Box from the Lunar Module example. Bounding Box + Manipulation Handler examples already exist on the left side of the scene (coffee cup, cheese...)
- Fixes: #5595
=> Update incorrect descriptions in the HandInteractionExample scene

pipelines/pr.yaml, pipelines/templates/common.yml
We currently build four different flavors on each mrtk_pr run, each of which can take between 12-17 minutes. This particular build being disabled in mrtk_pr has high correlation with the other x86 .NET build and IL2CPP ARM build.
Note that this is still enabled on the ongoing rolling build, which still needs to validate that everything is good.
=> Update the mrtk_pr pipeline to not build the UWP x86 build.

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4491
The current type enumeration code uses Unity's assembly CompilationPipeline.GetAssemblies, which only captures things that are going through Unity's compilation pipeline. This doesn't work well when consuming MRTK as compiled binaries - these types are obviously not part of source files at that point.
=> Fix missing default types in profile configs when consumed via NuGet

Assets/MixedRealityToolkit.Examples/Demos/Gltf/Models/Avocado/glTF/AvocadoMaterial.mat, Assets/MixedRealityToolkit.Examples/StandardAssets/Models/Cheese.fbx.meta, Assets/MixedRealityToolkit.Examples/StandardAssets/Models/EarthCore.fbx.meta, Assets/MixedRealityToolkit.Examples/StandardAssets/Models/Tree.fbx.meta
This PR changes some models to use their embedded materials instead of trying to re-import them every time.
Specifically, Material_37 and Material_38 kept reimporting themselves from Cheese.fbx. We remapped the cheese's materials in the prefab, so the built-in materials were unused.
=> Turn off material import on certain models

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/GazeProvider.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityGazeProvider.cs
This PR moves UpdateGazeInfoFromHit into the interface definition to remove a cast in FocusProvider to the concrete type.
It also performs some formatting / comment updates to match current MRTK-style more.
- Fixes: #5545 (at least, as far as GazeProvider is concerned. There's also the note about potentially defining custom GazePointers, like other pointers are handled)
=> Remove concrete GazeProvider reference to allow custom providers

Packages/manifest.json
Our Packages/manifest.json file has old TextMesh Pro version (1.3.0) which causes alignment issues on certain cases. Manually updating through Unity Package Manager resolves the issue.
Since there is no specific reason for keeping 1.3.0, updating it to the latest version 1.4.1.
- Fixes: #5600
=> Update TextMesh Pro version to 1.4.1 in the Package manifest file

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/Overlap.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
Overlap solver was not updated to check if TransformTarget could be null (i.e no hand is shown). This fix adds that check and adds SolverTest for this type of Solver
- Fixes: #5604 
All tests pass
>
>
=> Overlap does not check for SolverHandler.TransformTarget null

Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
This change asks Unity for the set of supported virtual reality SDKs for the currently selected target platform and then explicitly sets those that are supported by MRTK v2.
Unity 2018 set default SDKs, 2019 appers to no longer do so.
Fixes: #5626 
Verification:
* Clean Unity 2018 and 2019 projects
* Import private test foundation package
* Apply settings via dialog
* Confirm correct settings
* Switch platform (to uwp or to sdk based on original setting)
* Reload project
* Apply settings via dialog
* Confirm correct settings
=> Fix #5626: Discover and set virtual reality SDK(s) for the target platform

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableReceiverListInspector.cs
When removing an interactable event receiver item, the for loop rendering will still proceed thinking the number of items in the list has not changed. Thus resulting in out of bounds index access. 
Fix now breaks out of rendering list till next redraw which happens immediately with changed object.
- Fixes: #5634 
One can now add and remove interactable event receivers 
>
>
=> Fix inspector event removal bug

Assets/MixedRealityToolkit.Services/InputSystem/GazePointerVisibilityStateMachine.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/GazePointerStateMachineTests.cs
This addresses issue #5580: "Gaze cursor shows up when hands are in near touch mode". An additional check was added to only show the eye gaze cursor when no other near or far pointers are active.
=> Hide eye cursor in near touch mode

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/Observers/IMixedRealitySpatialAwarenessObserver.cs
- Document that the observer origin is in world space.
- Update the observer volume update to properly transform the coordinate space.
@fast-slow-still, can you please validate this change (review the code and test your scenario)?
Fixes: #5625
=> Fix 5625 - fix observer volume

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildInfo.cs
The project solution produced by the Unity build step always targets Platform Toolset v141 (Visual Studio 2017), regardless of Visual Studio Version Build Settings or whether Visual Studio 2017 or 2019 is installed. Build failures arise, when there is no Platform Toolset v141 installed, i.e. only Visual Studio 2019 has been installed. 
This issue has been reported already to Unity : https://issuetracker.unity3d.com/issues/uwp-building-project-for-visual-studio-2019-generates-solution-that-targets-build-tools-for-vs-2017-tool-set-v141
Attempts to figure out whether Platform Toolset v141 is installed seem to be non-trivial. For the time being, a convenience workaround is to override the Platform Toolset when invoking MSBuild. For the user this override is exposed as Appx Build Option in the …
=> Add Platform Toolset switch to Build Window

Assets/MixedRealityToolkit.Examples/MRTK.Examples.sentinel.meta, Assets/MixedRealityToolkit.Extensions/MRTK.Extensions.sentinel.meta, Assets/MixedRealityToolkit.Providers/MRTK.Providers.sentinel.meta, Assets/MixedRealityToolkit.SDK/MRTK.SDK.sentinel.meta, Assets/MixedRealityToolkit.Services/MRTK.Services.sentinel.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitFilesTests.cs, Assets/MixedRealityToolkit.Tests/MRTK.Tests.sentinel.meta, Assets/MixedRealityToolkit.Tools/MRTK.Tools.sentinel.meta, Assets/MixedRealityToolkit/MRTK.Core.sentinel.meta, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
In looking into #5568, I found that the existing MRTK files code would look for specific folder names that MRTK gets put into (as in, containing folder names). It had very specific behaviors with respect to NuGetForUnity or consumption as .unitypackage - if you had consumed the code some other way (for example, used a manual nuget restore step separately from NuGetForUnity) this wouldn't work out, because the naming of the folders would be different (i.e. MRTK/*) instead of (Microsoft.MixedReality.Toolkit*/*).
This change works around all that by introducing the concept of "sentinel" files, which are empty files that are named in a specific way and uniquely identify the root of an MRTK module/subfolder. Thus, when the MRTK files code finds a file called MRTK.SDK.sentinel, it knows that …
=> Update the MRTK to support being placed in arbitrary folder names up to three directories deep.

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystem.cs, Assets/MixedRealityToolkit/Interfaces/SceneSystem/IMixedRealitySceneSystem.cs
IMixedRealitySceneSystem was defines as both a CoreSytem (inherits BaseCoreSystem) and an IMixedRealityDataProvider.
This is incorrect and was preventing the scene service from being loadable.
=> Fix 5641 - SceneSystem defined as a data provider

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/MixedRealityKeyboard.cs
We want our windows system keyboard to work not just for HoloLens 2, but also for HoloLens (HL1) and Windows Mixed Reality (WHR). In HL1 and WMR there are OS bugs where the keyboard showing and hiding events do not fire. Our keyboard example was assuming those events fired correctly, and therefore not showing a keyboard in OnShow if the keyboard was visible. Remove this check.
- Fixes: #5363
Tested on HL1, HL2 and WMR
=> Fix keyboard show/hide for HL1 and WMR 

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/GGVPointer.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/BoundingBoxTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities.cs
- With articulated hands and 6dof controllers the pointer rotation is the hand/controller's rotation. This is used in `TwoHandMoveLogic` (which is also used for one hand) so that the object rotates around the pointer as it rotates:
- For GGV hands, the pointer rotation was the `InternalGazePointer` rotation, which meant that as you rotated your head, using the logic above, the object would rotate around your hand:
- These changes instead create a rotation out of the vector from the head to the hand, which rotates as you rotate your hand around your body but stable is if you only turn your head.
- Fixes: #5640.
=> Change GGVPointer rotation to closer match shell

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SurfaceMagnetism.cs, Assets/MixedRealityToolkit.Services/InputSystem/DefaultRaycastProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InputSystem/DefaultRaycastProviderTest.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityRaycastHit.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityRaycastProvider.cs, Assets/MixedRealityToolkit/Utilities/Physics/MixedRealityRaycaster.cs
This PR addresses issue #5391. 
This change introduces a configuration property in the Input System Settings in MRTK profiles - "FocusIndividualCompoundCollider". This configurable property is passed as a argument to the Raycast provider implementation and ultimately propagates to the TryGetPrioritizedPhysicsHit logic to determines, if the raycast hit result should pick individual colliders or the root rigidbody transform.
When the hit is determined, the profile property is again used to determine which gameobject to set as the rayast hit object .
Validation requested from @anuraag016  via product integration.
Created a local scene with a rigidbody and compound colliders and verified that the correct item is focused.
FocusIndividualCompoundCollider = false;
FocusIndividualCompoundCollider …
=> Expose configuration in FocusProvider to target colliders instead of rigid bodies

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/TestFixture_01_MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceWizard.cs, Assets/MixedRealityToolkit/Utilities/MixedRealityServiceRegistry.cs
Extension services would all register under the interface type key IMixedRealityExtensionService. The MixedRealityServiceRegistry would only check under the interface key provided. This is problematic as a service may inherit and extend multiple interface types. Usage of GetService<MyInterfaceExtensionService>() and similar usage of TryGetService<MyInterfaceExtensionService> were broken.
This change extends the internal Registry TryGet* path to search all bins and return the first service found that matches the interface type and name query given. 
Furthermore, the tests were modified to check for more variety of GetService requests as well as the extension service documentation link fixed.
- Fixes: #5644 , #5653 
> As a reviewer, it is possible to check out this change locally by using …
=> Fix extension services registration and documentation link

Documentation/KnownIssues.md
Extension Service Wizard is broken for optional inspector and profile. This change adds information to the known issues list for GA
Related #5654 
>
>
=> Add service extension wizard known issue

Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs, pipelines/templates/common.yml, pipelines/templates/tasks/validatecode.yml, scripts/ci/validatecode.ps1
We've seen a couple of instances of Boo.Lang getting checked in, where we really should be using System.Collections. More generally, there can be other patterns that we may check in inadvertently that we should avoid going forward, and having this be checked by a linter/during the checkin pipeline is better than assuming that all PR will catch it.
=> Add a code validation step to the PR pipeline.

Documentation/ExperimentalFeatures.md, Documentation/SceneSystem/SceneSystemContentLoading.md, Documentation/SceneSystem/SceneSystemGettingStarted.md, Documentation/SceneSystem/SceneSystemLightingScenes.md, Documentation/SceneSystem/SceneSystemLoadProgress.md, Documentation/SceneSystem/SceneSystemSceneTypes.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5155
In preparation for release, these features are going to go live in the latest release, so these warnings are no longer relevant.
Going forward we should have separate versions for our docs to make this exercise not necessary
=> Update the docs to remove the mrtk_development specific warnings.

Documentation/Input/Dictation.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5683
The dictation system requires an internet connection because the underlying windows APIs (and Unity APIs which consume the windows APIs) requires those two capabilities to be enabled.
=> Update the Dictation documentation to specify the internet connection and microphone requirements

Documentation/DetectingPlatformCapabilities.md, Documentation/toc.yml
This page wasn't really about the architecture of the MRTK at all, and interrupted the flow of reading through the architecture section (which is written in a way where each section builds off of the learnings from the previous page)
This also moves it into the root, because there isn't really a great place to stick this (i.e. it would be good to get a "features" folder to match the TOC, but I wanted to keep this particular change scoped) - cross platform was interesting but it doesn't really fulfill the cross-platform notion to consumers (i.e. I would think there would be more about cross-platform information here, but it's just a system capability checker, which exists even if things weren't cross platform)
=> Move the platform capability documentation to the features section.

Documentation/Boundary/ConfiguringBoundaryVisualization.md, Documentation/InputSimulation/InputSimulationService.md, Documentation/TODO.md, Documentation/toc.yml
A couple of things this changes:
1) Removes TODO.md, which is a catch-all and is a crutch for folks who are writing docs. Inevitablty people forget to update their TODOs and this leads to stale and not-confidence-inspring experiences reading a TODO.
2) Removes existing usages of TODO, either by deleting them outright or updating them to point to the most relevant things that exist on our docs.
=> Remove TODO.md from the documentation.

ProjectSettings/EditorBuildSettings.asset
MRTK devs need to regularly remove these two scenes when building and deploying: 
Remove those from the defaults, they don't seem to be needed for day to day development.
- Fixes: #5685
=> Remove SceneManager and LightingManager in default build

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ProfileTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ProfileTests.cs.meta, Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Add test to ensure we don't hit issue #5671 again. The test just loads up MRTK with the default & HoloLens 1 profiles, and ensures that when hands show up that the rays do / do not show up as well.
- Fixes: #5671
Verified that playmode and editmode tests pass locally.
=> Add MRTK Profile tests: Default and HL1 profile

Assets/MixedRealityToolkit.Examples/Demos/Solvers/Scenes/SolverExamples.unity
The Manipulator Handler and Bounding Box of the Custom Target object didn't move the objects root transform, instead just the visual asset. The Solver Object tracks the root transform though, so the Custom Target example wasn't working properly. Further the axes gizmo and visual asset become dislodged.
Changes cherry picked from #5662.
Open the Solver Example Scene and run it in Play Mode. Select Custom Target. Move the Tracked Object using hand manipulator and/or its Bounding Box. Verify that its axes gizmo and the Solver Object moves accordingly.
=> Fix Custom Tracked Target in Solver Example Scene

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
The current, newly implemented algorithm for calculating BoundingBox bounds has a bug this fix addresses.
The code was written in a way that if a gameobject considered for bounds calculation did not have a collider, it skipped the MeshRenderer completely, even though the default configuration is "RendererOverCollider".
This means, meshes without colliders resulted in a zero bounds calculation.
This fixes that problem.
P.S.: the fact that every combination of Renderers and Colliders is possible, one or both must be fetched and then applied in according order. Continuing anything here was a mistake.
=> Fixed BoundingBox Bounds calculation

Documentation/EyeTracking/EyeTracking_ExamplesOverview.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4960
Just like building an eye tracking app from scratch, using the samples also requires the Gaze Input capability, but it isn't mentioned in the docs. As a result, people using the samples on device will wonder why it doesn't work (because we didn't tell them to use that special capability)
=> Update the eye tracking sample docs to reference the Gaze Input capability

README.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4968
As the linked issue suggestions, the current "documentation" link is really confusing because it basically is a circular reference - it brings you right back to the curent page.
The tricky part here is that the Getting started guide is probably the best landing page for the documentation we have - it is still helpful to have a reference to the API, so the second link should probably be "API Reference"
If you want to see what this is addressing, go to the readme (on github) and just click the documentation image - it will keep bringing you right to the same place (as the README.md that it took you from)
=> Update the README's docs and API reference links

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs
Fixes an issue where you could not modify the Moving Button Visuals on a PressableButton.
The call to serializedObject.Update() seems to revert the value, so to fix the issue I've called serializedObject.ApplyModifiedProperties() just after the EditorGUILayout.PropertyField() call which draws and modifies the Moving Button Visuals.  It's a bit unconventional to call ApplyModifiedProperties twice in a single call to OnInspectorGUI, but I don't think it will cause any issues.
@Troy-Ferrell, you introduced the call to serializedObject.Update() about a week ago.  I'm open to alternative suggestions for how to fix it if you have any concerns.
Also switch to PropertyScope instead of Begin/EndProperty
=> PressableButton MovingButtonVisuals inspector fix

docfx.json, web/version.js
-adjusted contribute link to always point to mrtk_development
-added version 2.0.0 ga drop down
=> added release 2.0.0 / ga to version dropdown in docs

scripts/test/run_playmode_tests.ps1
I was unable to run the test runner script locally as-is, seeing this:
I updated `‘Container’` to `Container` to fix it.
I also updated the version of Unity it looks for the the current version we have checked in to the repo: #5657
=> Update test runner script

Assets/MixedRealityToolkit.Extensions/SceneTransitionService/DefaultSceneTransitionServiceProfile.asset, Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/Profiles/DefaultObjectMeshObserverProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityInputRecordingProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySceneSystemProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1InputSimulationProfile.asset, Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestProfiles/TestMixedRealityInputSystemProfile.asset, Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestProfiles/TestMixedRealitySpatialAwarenessSystemProfile.asset, scripts/ci/validatecode.ps1
This PR extends the script added in #5632 to add a check for `isCustomProfile: 1` in all of our non-Examples assets.
- Fixes: #5717, #5679
I'll run the mrtk_PR pipeline to validate that this fails, then check in the fixed profiles and validate that this passes.
=> Update to check for `isCustomProfile: 1` during PR validation (and fix existing incorrect profiles)

Assets/MixedRealityToolkit.Tests/PlayModeTests/Core.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers/Hands.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs.meta, Assets/MixedRealityToolkit/Providers/Hands/BaseHandVisualizer.cs
On certain platforms it's possible for hand mesh vertex array sizes to decrease between events, and the current infrastructure doesn't support that.
This addresses it (using the fix provided in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4607) and adds a test that shows it working.
=> Fix error when the number of hand mesh vertices decreases

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildInfo.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
Introduces the usage of the msbuild multicore related flags for appx build.
Usage is available via UwpBuildInfo and through the BuildWindow.
Preference gets saved via EditorPrefs.
> Evolution of pull request: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4889
> Isolation of changes to the multicore feature
> related to feature request: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4890
If multicore build option gets enabled, the build process will add the necessary flags to the msbuild.exe call for creating the appx.
=> provide multicore appx build capabillity

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs
- Fixes: #5760 
It seems its possible for the following to happen:
- pointer added on thread 1
- start gets called, but gets delayed because input system is not ready
- focus provider updates on thread 2
- focus provider touches queryBuffer
- queryBuffer gets initialized
Moving the queryBuffer initilization into Awake should ensure it gets initialized before focusprovider touches the pointer, since I assume Awake gets called before FocusProvider touches the pointer.
Unfortunately, this does not repro in editor (at least, I couldn't figure out how to repro in editor), so for this one I will not be writing a test :-( 
@Kjakubzak would it be possible for you to try this fix instead of your nullptr check to verify this fixes the bug? Reason I'd prefer to do this is because in …
=> Fill nullptr in poke pointer

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs
This is a follow up fix for #5360. The `PlatformToolset` property of the `UwpBuildInfo` wasn't set when starting an appx build. Leaving it to the default empty string value, `/p:PlatformToolset` was ommited during msbuild invokation.
In addition, this PR also contains an fix for the copy-pasted `PlatformToolset` preferences API in-code documentation.
- Follow up fix for #5360
=> Fix Platform Toolset selection not applied for msbuild

pipelines/ci-release.yml
For this release I am removing the "prerelease" text string from NuGet package version as that currently isn't supported by NuGetForUnity. This is not necessary for this release.
=> Removing the 'prerelease' from the NuGet versioning.

pipelines/ci-release.yml
Delete the Test package from artifacts published by the release build as we do not intend to publish them at release time.
=> Remove Test package from release artifacts

.gitignore, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec, scripts/packaging/NuGetRestoreProject.csproj, scripts/packaging/createnugetpackages.ps1
The last change to the NuGet packages had a few errors in it and was causing only the main Foundation package to be generated correctly. This change fixes those issues and also adds logic for acquiring NuGet.exe if the machine does not have it installed globally.
- I missed checking in a csproj that's used for NuGet restores (it was being gitignored).
- The source paths in nuspecs were not taking into account the depth of the nuspec files
- The script now acquires NuGet if you didn't already have it. In order to support that I did remove the functionality of packing all NuGets in parallel. The Start-Job command causes the inner command to lose the environment variables and context. In this case it means the background jobs couldn't find the local downloaded NuGet.exe. The overall NuGet …
=> Fixes for the NuGet Packages

Assets/MixedRealityToolkit/Definitions/MixedRealitySpatialObserverConfiguration.cs, Assets/MixedRealityToolkit/Providers/BaseInputDeviceManager.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs
The spatial awareness system was incorrectly configured to only allow registration of mesh observers. This blocks support for non-mesh observers (ex: future platform growth).
The fix was to filter based on IMixedRealitySpatialAwarenessObserver instead of the more restrictive IMixedRealitySpatialAwarenessMeshObserver.
This change also pointed out that BaseSpatialObserver was mistakenly NOT marked as abstract. It does not provide any observation functionality and is suitable only as a base class (the original intent).
As a part of this change, the class doc comments for BaseInputDeviceManager and BaseSpatialObserver were improved or added.
- Fixes: #5835.
- Confirmed non-mesh observer is discovered and can be added.
- Confirmed that the base class does not appear in available observers
=> Fix for spatial awareness allowing only mesh observers to be registered (#5835)

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/SDKProjectTemplate.csproj.template
This change is to fix the CI Build which is failing because the System.Core.dll is being overwritten by MSBuild. The reason for why this started happening recently, is unclear, however, the fix is to set AddAdditionalExplicitAssemblyReferences to false.
Will test a CI build on this change before commiting.
=> CI Build Fix

Assets/MixedRealityToolkit.SDK/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit.Tools/DependencyWindow/DependencyWindow.cs, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceWizard.cs, Assets/MixedRealityToolkit.Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs, Assets/MixedRealityToolkit/Inspectors/ControllerPopupWindow.cs, Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/SceneSystemInspector.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs
This PR has two changes:
1) The Pointers profile used `ReordableList` to easily draw the inspector which is awesome...but when drawn as a subprofile, the entire inspector is reallocated every draw. Thus there is no way to save state between renders resulting in the bug #5004 . This PR draws the list manually with our own add/delete buttons similar to speech profile and other similar list inspectors in MRTK
2) A lot of old code still uses BeginHorizontal/Vertical which is both problematic and harder to read. Switching to EditorGUILayout.VerticalScope() {} clearly defines what is being draw in this horizontal/vertical and allows valid clean up if the logic returns early
The PR looks more deadly than it is. It's largely because of all the tab formating with the new using() { }
- Fixes: #5004 …
=> Fix pointer profile inspector

web/version.js
fixes broken link in version dropdown 
readd this entry once the 2.0.1 docs are live
=> removed version 2.0.1 from dropdown 

Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Scripts/CustomInteractablesReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableAudioReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableEvent.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnClickReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnFocusReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnGrabReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnHoldReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnPressReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnToggleReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableOnTouchReceiver.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/ReceiverBase.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableEventTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableEventTests.cs.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/TestHand.cs, Documentation/README_Interactable.md
Most UI frameworks allow for event listeners to be added not only from a GUI editor, but also from code. MRTK currently makes it easy for event listeners on Interactable (except OnClick) to be configured in the editor, but configuring at run-time from script is not possible.
This PR does the following:
1. Fixes bugs preventing adding events at run-time
1. Adds utility scripts to Interactable  to simplify adding Interactable event listeners 
1. Adds tests to verify all event listeners available in interactable by default
1. Adds examples to documentation
Here's the old way to listen to focus enter/exit events:
```csharp
public static void AddFocusEvents(Interactable interactable)
{
var ie = new InteractableEvent();
var fr = new InteractableOnFocusReceiver(ie.Event);
ie.Receiver = fr; …
```
=> Add Interactable event listeners via script

Documentation/MixedRealityConfigurationGuide.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5842
The usage of the word "pane" was confusing as highlighted in the issue - pane is technically correct here as well (it is, well, a pane) but looking through the rest of our docs, there isn't any other usage of the term pane so it is inconsistent. Switched to panel to be consistent with the rest of our docs.
=> Update the docs to address a term inconsistency in the MixedRealityConfigurationGuide

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5818
It looks like our build tooling has been setting the "Minimum Platform Version" to 18362, something that we actually recommend people don't do when building apps (regardless of their target device). We recommend people set the version to 10240 (per the getting started page/build page). Nevertheless, we still get occasional bug reports about why the app isn't deployable to hololens 1.
It turns out our tooling was doing the wrong thing. This makes it update the right things (i.e. the Target SDK version) while providing a good default (and warning if deviation of the default occurs) for the Minimum Platform Version.
=> Update the build tooling to correctly set the Minimum Platform Version and Target SDK Version separately and correctly.

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseMousePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/PointerUtils.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/PointerUtils.cs.meta, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Services/InputSystem/Utilities/CanvasUtility.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SlateTests.cs
The hand ray cursor should not get stuck on flat UI like UnityUI and the slate (backed by `HandIteractionPanZoom`). This change updates fixes this by setting `IsTargetPositionLockedOnFocusLocked = false` when using hand rays or motion controllers. Old value gets restored on pointer up.
Also added tests to prevent regression, and some utilities for accessing common pointer info.
- Fixes: #5236
- Add test to verify fix does not regress
- Add a few pointer utility functions (related to #5280)
- Tested in editor, articulated hands
- Need to test that HoloLens1 behavior remains as before
=> Fix ray sticking to slate when panning HandInteractionPanZoom or UnityUI

Assets/MixedRealityToolkit.SDK/Features/Utilities/PointerUtils.cs
Fills in some empty returns that were caught by #5864. Also standardized some capitalization and punctuation while I was editing this script anyway.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=4984
=> Fill in empty returns

Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
For positionless controllers like xbox controller, the pointer position and the head position were coincident at the head position. This change ensures that if this is the case, we do not perform a division by zero in `TwoHandMoveLogic`, as this was causing objects to disappear into infinity.
- Fixes: #5829.
=> Fix possible division by zero in TwoHandMoveLogic

Assets/MixedRealityToolkit/Utilities/Editor/MixedRealityPreferences.cs
Small cosmetic changes to the Project Settings menu item. The full name felt a little long for the default size of the panel, and capitalization of the menu item was inconsistent:
to
=> Cosmetic change to MixedRealityPreferences.cs

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/MousePointer.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityMouseInputProfile.asset, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityMouseInputProfileInspector.cs, Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityMouseDeviceManager.cs, Assets/MixedRealityToolkit/Providers/BaseInputDeviceManager.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MixedRealityMouseInputProfile.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs
```
NOTE: This is a breaking change that will impact any custom mouse data provider implementations. It was deemed a safe change to make at this time as most known client applications utilize motion controllers and hands, rather than mouse devices. Application code is not impacted unless it references the mouse profile from the IMixedRealityMouseDeviceManager interface.
```
This change updates the mouse device profile to expose the CursorSpeed property (formerly MouseSpeed) and adds a WheelSpeed property to allow for easy configuration at runtime.
To preserve existing profile compatibility, the CursorSpeed property is marked as having been formally serialized as mouseSpeed. The WheelSpeed uses a default value if not present in a profile.
The default value for the cursor speed has been …
=> Expose cursor speed and scroll wheel speed to mouse profile. Fix y axis inversion.

Assets/MixedRealityToolkit.Services/InputAnimation/InputRecordingService.cs
Input Recorgin Service doesn't work with Null Reference Exception when push a recording button from a recording window.
The reason is forgetting check if Action is null before invoking.
- OnRecordingStarted.Invoke(); ->OnRecordingStarted?.Invoke();
- OnRecordingStopped.Invoke(); ->OnRecordingStopped?.Invoke();
=> FIX: Input Recording Service

Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/Templates/ExtensionInspectorTemplate.txt, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/HandJointServiceInspector.cs
This PR replaces #5906 and #5907, rebased on mrtk_development
- HandJointServiceInspector: create inspector on IMixedRealityHandJointService in stead of MixedRealityHandJointService
- ExtensionInspectorTemplate.txt now references #INTERFACE_NAME# in stead of #SERVICE_NAME#
=> Fix service inspector creation & HandJointServiceInspector

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
The `Build Appx` button in the Unity build completion dialog did not trigger the same build as the `Build Appx` button in the Appx build window tab. Specifically most build preferences were not taken into account. 
I compared both `UwpBuildInfo` from `BuildPlayer` and `BuildAppx` and added the missing settings to the former one. Though I am not sure if there are still hidden preferences that must be matched as well. 
Start a Unity player build, then in the completion dialog use the `Build Appx` button to build the Appx right away. The Appx should be build using the correct settings from the Appx build tab.
=> Fix Appx building from Unity player completion dialog not using correct settings.

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs
It was `TriggerPress` for one hand and `ButtonPress` for the other
#5874 assumes `TriggerPress`, so I standardized on that.
This PR also adds code to allow profiles to double check their default interaction mappings to update when axes / buttons / etc change.
=> Standardize OpenVR WMR grip press as DeviceInputType.TriggerPress

CODEOWNERS
CODEOWNERS is a handy way to both:
1. Provide insight into who knows most about an area of the code.
2. Automatically assign PRs to individuals based on previously determined ownership (i.e. the CODEOWNERS file)
This reduces the guesswork (i.e. "who should I include on this review?") and is especially interesting for external contributors (i.e. those who don't have rights to assign reviewers)
This change adds the beginnings of a CODEOWNERS file covering the relatively critical Build / CI area. This is an area that must be reviewed by someone who has been working on the Build / CI tooling.
=> Add a CODEOWNERS to the MRTK.

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
This change is a fix for #5856, where we have a report of an invalid cast exception occurring if the focus target is not an Interactable.
The change replaces a c-style cast (which can cause invalid cast exceptions) with the c# as keyword (which results in null instead of an invalid cast).
I was unable to reproduce the reported issue, however @asugaya-apx has offered to help verify the fix.
- Fixes: #5856
=> 5856 - improve resiliency, use as instead of c-style cast

Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
The root cause of this issue was relying on specific folder names instead of using the MixedRealityToolkitFiles lookup.
The solution was to add a reverse lookup (from folder name to module type) that is called by the extension service attribute to find the correct module. This lookup will return a module type of None if the provided folder name does not begin with "MixedRealityToolkit" as the MRTK does not have mappings for third party folders.
In editor...
- using c# files (the source tree / .unitypackage file)
- Add new spatial awareness observer
- Select object mesh observer
- Note the profile is populated with the configured default
- using NuGet packages
- Add new spatial awareness observer
- Select object mesh observer
- Note the profile is populated with the configured default
=> Fix failure to populate default profile when using NuGet packages

Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader
A recent change broke mesh outling, this fix addresses the issue by making sure scale does nt influence smooth normal.
Before:
After:
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5926
>
>
=> Scale Should Not Influence Smooth Normals

Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs.meta
This PR addresses issue #5053.
This test checks whether the pointer is valid for the first frame.  It also checks if the pointer direction is facing the same general direction as camera forward.
[Video of Pointer Test](https://youtu.be/FRWSFsgt6PI)
- Added PointerTests.cs to Assets/MixedRealityToolkit.Tests/PlayModeTests/
- In Unity: Window -> General -> TestRunner
- Select PlayMode at the top of the window
- Select PointerTests and then Run Selected
=> Added test to verify that pointer is valid for first frame after hand appears - issue 5053

Documentation/Contributing/UnitTests.md
This PR updates the UnitTests.md doc play mode tests template section.   The new play mode test template inherits from BasePlayModeTests and the template includes a starter example that shows a test hand, moves it and gets the line pointer.
- Added BasePlayModeTests script in UnitTests.md
- Added example starter test to UnitTests.md
>
>
=> Updated template for play mode tests in UnitTests.md

Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities/Async.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs.meta, Assets/MixedRealityToolkit.Tests/PlayModeTests/Microsoft.MixedReality.Toolkit.Tests.PlayModeTests.asmdef, Assets/MixedRealityToolkit/Utilities/Async/Internal/AsyncCoroutineRunner.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5900
DontDestroyOnLoad is only valid to be called on an object that is at the root (i.e. it has a null parent). It's possible for the AsyncCoroutineRunner to have been attached to the mixed reality playspace (i.e. if the user manually created one under the playspace or under any other object).
This updates the code to do a one-time at runtime fixup of its location to make sure that it can properly be DontDestroyOnLoad-ed.
=> Update the AsyncCoroutineRunner to be properly rooted for DontDestroyOnLoad

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/HandConstraint.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5749
The Xbox controller is an IMixedRealityController, that, when plugged in, will trigger the hand menu because it's considered a valid target for the hand constraint solver.
This change makes it so that the solver will filter out any controllers that don't have a handedness specified (i.e. they should be left/right/any/both)
=> Fix the HandConstraint solver to only consider controllers with handedness != None to be valid targets.

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildInfoExtensions.cs
Due to the changes in #5897, the code to inject the configuration scripting symbols is now properly invoked. Previously it wasn't invoked at all, because the `BuildInfo.Configuration` was never set. However there are some type conversion errors in the code, resulting in scripting symbols along the lines of `debug;System.Linq.Enumerable+<ExceptIterator>d__57'1[System.String]`. Those type errors are fixed in this commit (a good example of `var` hiding a compile time error).
Related to this issue, what is the purpose of the `debug', 'release' and 'master' symbols injected in the first place? Those were never properly injected before and as far as i can tell everything ran fine. So are they obsolete? Maybe this question can be discussed in a separate issue, if there is no definite answer. …
=> Fix build tools generating malformed scripting symbols

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs
(This is future proofing for when these methods are callable in the Editor)
Due to the possibility of construction of this type at edit time (which is itself potentially a different issue):
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/89fb1f941856963b0012c6755ddaf61a94d4b999/Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs#L131
This code is not valid at edit-time, only runtime. This moves caching the interaction manager from the constructor to first-use.
=> Cache spatialInteractionManager on first use, not in constructor

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Bounds override transform changes were not taken into account in update of bounding box when bounding box was active.
not checking the bounds override changed while bounding box is active will result in the box not adjusting on bounds override transform changes.
- Fixes: #5414 
tested in bounding box runtime example scene
run bounding box tests
=> added check for bounds override changed to active part of bounding box update

scripts/packaging/updateMRTKVersion.ps1
Add a script that should make it easier to update MRTK version number across all files known to contain a version string (unfortunately it seems that we can't just store that version in one place at the moment). 
This won't replace a manual check and it's still necessary to verify that no location was omitted.
=> Add script to update MRTK version across all files

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/FingerCursor.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs
In #5920 I modified PokePointer to disable the finger cursor when poke pointer was not enabled (IsInteractionEnabled == false). Turns out, the finger cursor drives the proximity effect, so disabling it causes not only the finger cursor to not show up, but for all proximity effects to stop working. 
A longer term fix would be to ensure that the proximity effect is running even when poke interactions are off, or when the poke pointer is not present. A short term fix is just to always have the finger cursor on, and to just turn off the visual if interaction is not enabled.
- Fixes: #5962
Note: when hand is near a grabbable, the cursor is still off. In the shell the cursor is on even when you are near a grabbable but not a touchable. I think this is a bug in the shell, since the finger cursor …
=> Fix proximity effect 

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Add a null check while observing a proximity pointer's result, which I was seeing occasionally be queried while null.
Some of these times were due to bugs in other parts of my code, but we do null check the `Result` in other places, so it feels reasonable to do here too.
=> BoundingBox proximity pointer null check

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs
A constructor was recently added to DefaultPointerMediator.  This removed the implicit parameterless constructor, which was a breaking change that affected one of my projects.
- Fixes: #5989 .
- Adds an explicit parameterless constructor which passes null.  Also then added null checks where appropriate.
=> Add back a parameterless constructor to DefaultPointerMediator

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHololens2UnityUI.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonUnityUI.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
This fixes several small issues that affected a consuming app.
- Fixes #6024.  The instantiation sequence in the app called OnEnabled(), OnDisabled(), OnEnabled(), Start().  This sequence resulted in OnDisabled flattening the buttons to depth 0, then Start() read in that position as the 'start' position.
- Now OnDisabled() won't call UpdateVisualsPosition() if Start() has not executed.
- Fixes #6025.  The initial offset was stored as world location.  If you moved/rotated the buttons or their containers after Start(), it would result in the front plates being pushed in the original direction instead of the current direction.
- This affected the UnityUI-based buttons in the example scene.
- It did not affect the collider based buttons because:
- The collider based buttons don't have any …
=> Fix a few issues with PressableButton.

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs, Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionTouchableVolume.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/NearInteractionTouchableTests.cs
PokePointers would actually raise up events when in the middle of a touchable volume, for two reasons:
1) The ray that pokepointer was building was too short. When inside a volume, the ray would never actually hit any bounds of the volume, and therefore FocusProvider would thing that the pointer was no longer colliding with something, causing touch up.
2) The distance checks in OnPostSceneQuery were looking at the length of the poke to hit point, which can make sense for touchable planes (you maybe want to raise touch up after you've gone far enough behind a plane), but not for volumes (you only really want to exit when you exit the volume). 
In both cases I fixed this by  special-casing touchable volume in poke pointer, and making the ray longer as well as changing the distance check.
- …
=> PokePointer TouchableVolume fix touch up when in middle of volume

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/BoundingBox/BoundingBoxInspector.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityRaycastHit.cs
changed MixedRealityRaycastHit to use collider transform instead of Unity.RaycastHit.transform because this one potentially returns the transform of the gameobject that has a rigidbody attached instead of the actually collision transform.
This was the cause for not being able to interact with any handles of bounding box whenever a rigidbody component was attached. 
Unitys documentation on RaycastHit.transform is not clear on what's happening. It only states that: "The Transform of the rigidbody or collider that was hit."
While digging around I found other ppl running into this as well:
https://answers.unity.com/questions/190482/raycasthittranslatecollider.html
My observation while debugging confirms what's mentioned in that thread. Whenever we've no rigidbody component attached the …
=> Changed MixedRealityRaycastHit to use collider transform instead of RaycastHit.transform

Assets/MixedRealityToolkit.SDK/Features/Input/InputSimulationIndicators.cs
InputSimulationIndicators is part of a Prefab referenced in the MRTK profile for simulation purposes. The whole class is wrapped in #if UNITY_EDITOR and as we all know, that's bad if it contains serialized fields.
- Fixes: #6033
=> serialization fix

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs
The problem is that WindowsMixedRealitySpatialMeshObserver's CleanupObservedObjects detaches all children from observedObjectParent, if it exists and then destroys all the gameobjects using regular Destroy. This mix causes the errors and since the Editor should use DestroyImmediate anyways, this fixes it for the case of holographic remoting the Hololens and destroying generated meshes.
- Fixes: #4208
=> SpatialMesh Editor cleanup fix

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
added restoring of original local scaling value of rigroot which potentially gets messed up whenever rigroots parents scale is set to zero. 
The linked bug has two issues, this one and also that the collider transform changes weren't propagated properly and handles weren't updated during the animation of the bounding box gameobject. The update part was already fixed in this PR #5982 
- Fixes: #5006 
- tested in hand interaction example scene 
- run tests
=> fixed exploding handles when bounding box gets scaled to zero

Assets/MixedRealityToolkit/Inspectors/ClippingBoxInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingPlaneInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingPrimitiveInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingPrimitiveInspector.cs.meta, Assets/MixedRealityToolkit/Inspectors/ClippingSphereInspector.cs, Assets/MixedRealityToolkit/Utilities/StandardShader/ClippingPrimitive.cs
This change fixes an issue where clipping primitives were modifying a renderers shared material in the editor. Materials are now cloned (much like how renderer.material works at run time). This was done to support edit time manipulation without leaking materials into the scene.
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6001 relies on this change.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5993
Please try using a scene that uses primitive clipping such as the ClippingExamples or MaterialGallery scenes.
>
>
>
> git checkout …
=> Fix 5993 - Remove Usage of Shared Materials with Clipping Primitives

Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseCursorTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs
Two fixes:
1. Fixing failure `Microsoft.MixedReality.Toolkit.Tests.BaseCursorTests.CursorContextMove`, happened about 2/100 times. Issue seems similar -- Unity sometimes doesn't raycast when there's just one collider in scene. With a second collider, tests pass 100/100
2. Fix failure `Microsoft.MixedReality.Toolkit.Tests.InteractableTests.TestInputActionMenuInput` by adding function that ensures input system updates (all input events raised can get received). Also make the test easier to diagnose by also checking if input has gone down, and up.
- Fixes: another failure in #6058
> and validate the functionality …
=> Fix intermittent test failure

Assets/MixedRealityToolkit.Tests/PlayModeTests/PlayModeTestUtilities.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
This change ensures that TMP Essentials are imported prior to the pressable button tests being run.
Root cause
These tests have been failing with no data in the logs due to a dependence on TMP. The test attempted to import TMP Essentials as part of the startup method. Packages cannot be imported while Unity is in play mode, so the tests would quietly fail.
=> Fix pressable button test failures related to missing Text Mesh Pro Essentials

Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
Two PressableButton tests would occasionally fail.  This change tweaks the values of hand position to get them passing consistently.  I've tested both tests 10 times in a row with these changes and have not seen a failure.
- Partially addresses: #6058 .
- ReleaseButton("PressableButtonHoloLens2UnityUI.prefab")
- The pointer finger would spawn at exactly the starting "press" location.  In the case of the Unity UI button, sometimes this would cause the GraphicsRaycast never to hit it.  So the fix is to push it outward by 1mm.
- TriggerButtonFarInteraction("PressableButtonHoloLens2.prefab")
- When a simulated hand spawns, the far interaction ray seems to wobble for a frame or two.  My theory is that this caused this test to occasionally fail.  To fix it, I've adjusted the hand position so …
=> Improve robustness of 2 hand interaction tests

Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Instead of waiting for a frame, use `PlayModeTestUtilities.WaitForInputSystemUpdate` when using voice to press button.
- Fixes: another case in #6058
>
>
> …
=> Fix intermittent voice command failure

Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
Update the ray to be closer to the center of the box when targeting. Also discovered a few more rotation behaviors that don't work well with the test, so disable them (they caused the cube to move when you grab, which is expected).
- Fixes: #6058 
>
>
> …
=> Fix intermittent failure ManipulationHandlerOneHandMoveFar

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/Piano.prefab, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/PianoBlackKey.prefab, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/PianoBlackKey.prefab.meta
In HandInteractionExamples scene, black piano keys are not responding to finger press, very difficult to press.
- Updated overlapping key colliders, updated NearInteactionTouchable
- Adjusted the press distance values
- Created separate prefab variant for the black keys
- Fixes: #5943
**Before: Colliders were overlapping for the black & white keys**
**After**
=> Fix black piano key not responding to hand tracking input.

Assets/MixedRealityToolkit/Utilities/Scenes/RuntimeSceneUtils.cs
fixes a rare bug where it's possible to have 0 scene loaded when managing scenes from code.
- Fixes: # . https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5895
>
>
>
> git fetch …
=> apply same workaround as in EditorSceneUtils

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Tooltips/ToolTipConnectorInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Tooltips/ToolTipInspector.cs
Replaces SetDirty calls in ToolTip inspectors with RequireConstantRepaint.
- Fixes: #6096
>
>
=> Stops ToolTip inspectors from continuously refreshing

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Tooltips/ToolTipConnectorInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Tooltips/ToolTipInspector.cs
Stops ToolTip inspectors from continuously refreshing
=> Cherry-pick pull request #6097 from Railboy/tooltip_inspector_fixes

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs
This debug output was incorrectly pointing to the Pointer Profile.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6052
=> Update buffer size debug output for help mitigating issue

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
fix for #6088  
I removed a fix I did to compensate for a messed up scaling caused by animating the localscale of the bounding box target object. ( https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6017 )
This fix broke scaling behavior for bounding box children. 
Seems like scale changes to children are not propagated anymore once I set the localScale manually. This didn't show in the objects I tested with because the scaled objects were the target object itself. The broken cheese however has the scaled mesh as a child (same goes for slate, coffee, etc). 
I tried to add a different workaround for the messed up scaling (eg https://answers.unity.com/questions/770240/changing-the-scale-of-the-parent-messes-up-the-chi.html) but that didn't work with the test file I'm using from one …
=> removed patch for scaling issue while animating because it's breaking bounding box scaling

Assets/MixedRealityToolkit.Examples/Version.txt, Assets/MixedRealityToolkit.Extensions/Version.txt, Assets/MixedRealityToolkit.Providers/Version.txt, Assets/MixedRealityToolkit.SDK/Version.txt, Assets/MixedRealityToolkit.Services/Version.txt, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs, Assets/MixedRealityToolkit.Tests/Version.txt, Assets/MixedRealityToolkit.Tools/Version.txt, Assets/MixedRealityToolkit/Version.txt, Documentation/Contributing/Roadmap.md, ProjectSettings/ProjectSettings.asset, pipelines/ci-packaging-dontpublish.yml, pipelines/ci-packaging-internal.yml, pipelines/ci-packaging.yml, pipelines/ci-release.yml, pipelines/ci.yaml, pipelines/pr.yaml
Since we branched for stabilization of 2.1, we should update our mrtk_development to 2.2 as it's no longer a 2.1 feature set.
=> Update MRTK_Development to Version 2.2.0

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
After #5868 was merged, the asset retargeter failed due to .anim files potentially have script references as `script` instead of `m_Script`. This change accounts for that and improves logging this case to determine the actual file it was hit in.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=5553
I ran this locally and saw that retargeting succeeded.
=> Update asset retargeter to account for anim files with script references

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PhysicalPressEventRouter.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
Fix for issue #5833 where near interaction events were triggered when Interactable was disabled.
Added the fix by Julia to PhysicalPressEventRouter which only sets states and triggers near interaction events if Interactable is enabled.
Video of HandInteractionExample scene after the fix:
[Issue 5833 Fix](https://youtu.be/AhKWyaPgiH0)
- Added CanRouteInput() to PhysicalPressEventRouter
- Added doc comments to public methods
- Added a test to PressableButtonTests
>
>
=> Added Interactable enabled check to PhysicalPressEventRouter - fix for 5833

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Extensions.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Extensions/CameraExtensionTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Extensions/CameraExtensionTests.cs.meta, Assets/MixedRealityToolkit/Extensions/CameraExtensions.cs
IsInFov did not check against depth and more importantly against the near/farclip planes. Also added tests to confirm various points return expected results.
- Fixes: #5979
>
>
=> IsInFov Camera Extension Fix

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerHandlerExample.cs, Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/SpatialObjectMeshObserverProfileInspector.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs, Assets/MixedRealityToolkit/Utilities/StandardShader/StandardShaderUtility.cs
This change is a first-pass update to remove usages of ?. from objects that obviously derive from UnityEngine.Component (ex: GameObject)
Fixes: #6044 
- Use HandInteractionExample (in editor) and the InputSimulationService to verify no input related regressions.
=> fix ?. usages for obvious UnityEngine.Component derived objects

Assets/MixedRealityToolkit.Examples/Demos/ExamplesHub/Scenes/MRTKExamplesHub.meta, Assets/MixedRealityToolkit.Services/InputSystem/BaseNearInteractionTouchable.cs
Adds back ColliderNearInteractionTouchable but marks it as obsolete, use BaseNearInteractionTouchable instead. Also updated #5912 2.1 release notes.
- Fixes: #5922
- Also remove lingering meta file.
I verified that referencing `ColliderNearInteractionTouchable ` causes compile error with proper migration message. 
Also verified that docfx generation works with no warnings or errors.
>
> that …
=> Mark ColliderNearInteractionTouchable as obsolete

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs
This remoting bug, where the state of select pressed isn't properly remoted, is only valid for HL1. This adds a check for the source supporting grasp, which, since we already filter for hands, is only valid for HL2 in WMR devices.
- Part of adding remoting support for HL2 hands (breaking some initials small changes out)
=> Filter out HL2 for the remoting select bug

Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionServiceProfile.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/BaseObjectCollection.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssemblyDefinitionInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CSProjectDependency.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CSProjectInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CompilationPlatformInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/MSBuildTools.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/PluginAssemblyInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/ReferenceItemInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TargetFramework.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TemplateFiles.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/UnityProjectInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/Utilities.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs
There are quite a few classes in the Microsoft.MixedReality.Toolkit.MSBuild namespace that aren't being picked up by our docs generation.
Since these classes are already in an editor-only assembly, we shouldn't need to `#if UNITY_EDITOR` them as well.
=> Fix ms build docs and editor checks

Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/ConstructGltf.cs, Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs
As part of adding remoting support for HL2, there will be a new `.Windows` namespace. This change helps disambiguate these namespaces ahead of time.
- Part of adding remoting support for HL2 hands (breaking some initials small changes out)
=> Explicitly use Windows.Storage

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssemblyDefinitionInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CompilationPlatformInfo.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TargetFramework.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/Utilities.cs
#6146 broke the stabilization docs build, since the mrtk_docs pipeline isn't running on stabilization PR validation.
Built docs locally (since the mrtk_docs pipeline doesn't appear configured for stabilization PR validation.)
=> Fix 2.1.0 docs

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs.meta
When the input system initializes, it instantiates the registered gaze provider. When it is disabled, the gaze provider is destroyed. Unfortunately, enable was not re-creating the gaze provider, resulting in null reference exceptions.
This change creates the InstantiateGazeProvider method and calls it from Initialize and, if null, from Enable.
Fixes: #5085
Create simple scene in editor. 
Apply the script shown below to any object.
Disable and then re-enable the input system.
Use the input simulation provider to display a hand (ex: spacebar)
```c#
using Microsoft.MixedReality.Toolkit;
using Microsoft.MixedReality.Toolkit.Input;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public class EnableDisableSystemTest : MonoBehaviour
{
private …
```
=> fix null reference exception when re-enabling input system

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs
Property rename introduced in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6104
resulted in a regressions in Interactable Editor experience. This prevents users from setting an intractable as Toggle/MultiDimensional selection mode.
- Fixes: # .https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6161
>
>
> As a reviewer, …
=> Fix serialized property name in the inspector that was broken due to property rename

Documentation/MRTKNuGetPackage.md
This is a documentation change to emphasize that migration of a project to use MRTK NuGet is not yet supported.
=> NuGet Documentation Migration Emphasis

Assets/MixedRealityToolkit.Examples/Demos/ExamplesHub/Profiles/MRTKExamplesHubSceneTransitionServiceProfile.asset, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/Assets/CameraFaderMaterial.mat, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/Assets/CameraFaderMaterial.mat.meta, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/DefaultSceneTransitionServiceProfile.asset, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionService.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionServiceProfile.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/Scripts/CameraFaderQuad.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/Scripts/ICameraFader.cs
Updates CameraFaderQuad to use an unlit particle shader instead of the default sprite shader.
Also adds an optional camera fader material field to the scene transition profile to get around the issue of required shader variants not being included in the build.
- Fixes: #6136
>
>
This has been tested in editor and on HL2 devices.
=> Fixes SceneTransitionService glitches when using single pass instanced rendering in 2019.2.6+

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/PressableButtonInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/InspectorUIUtility.cs
Show warnings in the Inspector for several cases which will cause PressableButton to fail to function properly.
- A NearInteractionTouchable or NearInteractionTouchableUnityUI must be present.  Decide which to add based on presence of RectTransform.
- The Touchable's EventsToReceive must be Touch.
- In the UnityUI case, there must be a MovingButtonVisuals present with a Graphic (aka, Image, RawImage, etc.) present.
Fixes #6159.
=> PressableButton inspector warnings

Assets/MixedRealityToolkit.Services/InputSimulation/Editor/InputSimulationService.cs
This is a very simple change that disables camera controls when an XR device is present. Without this change, the camera position, returned by the camera cache, would jump upwards when the VR controller trigger was pulled. You can see this in the gifs below, as the profiling panel jumps up and down with the head position as the trigger is pulled.
When the head position jumped upwards, it was suddenly closer or further from the controller. This distance is used in `TwoHandMoveLogic` to scale the distance between the controller and the object. This was then causing the object to jump.
- Disabled camera controls when an XR device is present (equivalent to disabling `IsCameraControlEnabled` in the input simulation profile)
- Fixes: #6108
=> Fix objects jumping when manipulating with VR controllers in editor.

Documentation/Contributing/ExperimentalFeatures.md
Fix small typo in experimental guidelines, one line change.
- Fixes: #6156
=> Fix typo in experimental guidelines

Assets/MixedRealityToolkit.Examples/Demos/UX/BoundingBox/Scenes/BoundingBoxExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Collections/Scenes/ObjectCollectionExamples.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/PressableButton/Scenes/PressableButtonExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Slate/SlateExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Slider/Scenes/SliderExample.unity, Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity
This PR is a fix for issue #6168 where multiple MixedRealityPlayspace objects in certain example scenes caused issues while running the scene.
Scenes edited:
- Scenes with extra MixedRealityPlayspace objects
- BoundingBoxExample
- PressableButtonExample
- SlateExample
- SliderExample
- Scenes with no config profile assigned
- ObjectCollectionExamples
- TooltipExamples
- BoundingBoxExample Scene
Before:
After:
- ObjectCollectionExamples Scene
Before:
After:
- PressableButtonExample Scene
Before: 
After:
- SlateExample Scene
Before: 
After:
- SliderExample Scene
Before: 
After:
- TooltipExamples Scene
Before:
After:
> …
=> Deleted extra MixedRealityPlaypace objects from example scenes

Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/InputSystemTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Microsoft.MixedReality.Toolkit.Tests.EditModeTests.asmdef, Assets/MixedRealityToolkit/Providers/BaseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Add some tests to check that axes and buttons are properly set based on what the device manager / controller update loop expects. Also formats some things.
Before #6184:
After:
- Fixes: #6164 (and makes it harder for it to happen again)
=> Add controller mapping tests

Documentation/Rendering/MaterialInstance.md
Minor change, adding sample code to demonstrate why developers should use MaterialInstance.
=> MaterialInstance Documentation Leak Example

Documentation/GettingStartedWithTheMRTK.md
- Fix broken links
- Input simulation keys update
- Deleted duplicated/outdated copy of the UI building blocks and Tools table. Added link to the landing page's section instead for easier future maintenance. 
- Updated and polished content for 2.1.0
- Fixes #6201
=> [Docs] Getting Started page - Fix broken links, updated and polished content

pipelines/ci-release.yml
The signing configs will go out of sync any time add, remove or rename assemblies. We previously created a script to generate these configs, as writing them manually was a pain. It makes sense that we use this script in the pipelines as it's one less thing to think about.
=> Auto generate signing configs in release pipeline

Documentation/GettingStartedWithTheMRTK.md
Fixes a broken link (the header name should have been lower case)
Verified fix via a local doc build.
=> Fix link to tools info in getting started article

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitFilesTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/InputSystemTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/SpatialAwareness/SpatialAwarenessSystemTests.cs
There were a few test scripts with multiple TearDown attributes.
There were also at least two that were calling `EditorCreateScenes` in `CleanupMixedRealityToolkitTests`.
=> Combine multiple TearDown attributes

Assets/MixedRealityToolkit/Utilities/Rendering/MaterialInstance.cs
Fixing an issue where CreateInstances could be called before Awake. Which would in turn try and set the shared materials to null.
This would only occur in scenes with very specific hierarchy setups where a clipping primitive was placed in the hierarchy after a renderer it reference which is also initially disabled.
Issue found by @radicalad.
Please test scenes and scripts which heavily use ClippingPrimitives.
=> Fixing an issue where CreateInstances could be called before Awake

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs
[Not targeting stabilization]
Updates ControllerPoseSynchronizer to not have to set `IsTracked` manually everywhere. It was often simply setting it to the result of `TrackingState == Tracked`, so this simplifies any potential mistaken state management.
=> Change IsTracked to not have to be set manually

pipelines/ci-release.yml
We don't want to publish the tests package for the release pipeline. We use common pipeline paths, so as part of the release processes we need to delete it.
This updates the delete to happen after the signing of the NuGet packages so we don't run into an error.
=> Change when Tests Package is Deleted

pipelines/ci-release.yml
This change removes the alpha tag from the release pipeline.
=> Remove Alpha Tag

pipelines/ci-release.yml
SignCheck step is currently run as part of the Release Pipeline but we should be running it as part of mrtk_CI-release pipeline that does the signing.
=> Add SignCheck step to mrtk_CI-release pipeline

Assets/MixedReality.Toolkit.Foundation.nuspec
This change fixes duplicate metas packaged as part of the Foundation package by ignoring them from SDK folder.
=> Remove duplicate metas from being packaged

Documentation/ReleaseNotes.md
This change adds install and update instructions as well as a recommendation / pointer to NuGet for Unity.
=> 2.1.0 - Add nuget package information to release notes

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec
There is an issue with NugetForUnity with long paths, and the source is deeply nested in the NuGet package. This change excludes the source from being packaged, to avoid that issue for the time being. In 2.2 this will return, as well as a supported scenario for using this source to debug the binaries in the package.
=> Remove source packaged in NuGet for 2.1 Release

Documentation/Extensions/SceneTransitionService/SceneTransitionServiceOverview.md
In this documentation, the layout is broken.
https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Extensions/SceneTransitionService/SceneTransitionServiceOverview.html#fade-targets
This PR fixes the problem.
=> Fix broken layout in SceneTransitionServiceOverview.md

CODEOWNERS
This change assigns as set of code owners to the non-CI / build system portions of the tree. These owners have past experience in these areas and are a good starting point for suggested reviewers.
The collection of individuals is likely to change over time.
Fixes: #6124
=> Add first draft set of code owners for the non-ci code

Assets/MixedRealityToolkit.Examples/Demos/ExamplesHub/Scenes/MRTKExamplesHub.meta, Assets/MixedRealityToolkit/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs, Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityProfileUtility.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityProfileUtility.cs.meta
Major changes
- Adds the `MixedRealityProfileUtility` class. This class is responsible for listening for asset changes and caching available profiles by type and service type. Prior to this change inspectors were searching for ScriptableObject instances every redraw.
- Changes profiles from object fields to dropdown lists and moves profile drawing from `BaseMixedRealityProfileInspector` to `MixedRealityInspectorUtilities`. The GUIContent for these lists are cached.
- Adds a 'View Asset' button to profile fields - clicking this reveals the ScriptableObject asset in the project view.
- Removes object picker window functionality from MixedRealityToolkitInspector, since dropdowns are effectively the same.
- Addresses: #6120
> As a reviewer, it is possible to check out this change locally by …
=> MRTK Profile Inspector Performance Improvements

Assets/MixedRealityToolkit.Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs, Documentation/Performance/PerfGettingStarted.md, Documentation/Tools/OptimizeWindow.md, Documentation/hologram-stabilization.md
Update documentation and optimize window to give notice to users about 16-bit depth format not creating a stencil buffer in Unity.
- Fixes: #5970 
>
>
=> Stencil buffer issue with 16-bit depth format

Documentation/Contributing/CodingGuidelines.md
Removing the section warning about usage of foreach vs for. In Unity ~5.3+ the allocation issues have been resolved: https://forum.unity.com/threads/upgraded-c-compiler-on-5-3-5p8.417363/ And, here is a nice breakdown of memory usage: https://jacksondunstan.com/articles/3805 My general guidance is use foreach when you can to prevent bugs and improve readability, then profile often to find if foreach is an issue in "hot" loops.
=> Removing  Loop Guidance

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystem.cs, Assets/MixedRealityToolkit/Definitions/SceneSystem/SceneInfo.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoDrawer.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoUtils.cs, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoUtils.cs.meta
Ensures that SceneInfo fields found in ScriptableObjects and Components are kept up-to-date when assets are modified, when editor scene settings change, or when building. Previously these fields were only updated when they were drawn by an editor, which was leading to stale settings.
SceneInfo-related operations have been moved out of SceneInfoDrawer and into SceneInfoUtility.
This also adds better error handling / reporting to SceneSystem operations to make troubleshooting scene-related errors easier in general.
- Fixes: #6060
>
>
=> SceneSystem / SceneInfo Improvements

README.md
Suggesting renaming the "Simulator" square to "Emulator", and pointing it to the documentation for HL1 and HL2 emulators instead of a direct download link to the HL2 HoloLensEmulatorSetup.exe (so people can learn how to use it, it aligns better with the other "required software" links, and it gives the option to find the HL1 emulator if desired).
(also made a tiny grammar change to the main description, and fixed a typo)
=> Simulator->Emulator and link change, nit typo

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
The visual profiler does not write to the depth buffer which can cause rendering artifacts when using depth buffer sharing on HoloLens 2 (dLSR). To fix this the visual profiler now writes depth. The components in the profiler should still render correctly due to their custom render queues settings.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6302
>
>
=> Forcing the visual profiler to write depth for improved dLSR support.

Documentation/HTKToMRTKPortingGuide.md
Removed the starting "/" in three links that caused them to point to non-existent readme locations
=> Updating 404 links in porting guide

Assets/MixedRealityToolkit/Definitions/InputSystem/MixedRealityInputSystemProfile.cs, Assets/MixedRealityToolkit/Definitions/MixedRealitySpatialObserverConfiguration.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealitySpatialAwarenessSystemProfileInspector.cs
Two primary bugs here with profile inspectors
1) In RenderProfileInternal, the call to `MixedRealityProfileUtility.GetProfileTypesForService()` was incorrectly utitlized by selecting FirstOrDefault from the available list even if that profile was not a match for the given service type. Further, this call was made even if the profileType argument was already not null
2) Some inspectors were not properly providing a service type to RenderProfile(). They made erroneous checks before setting the serviceType argument.
With this change, now profile drop downs are actually filtered (where applicable like Spatial Mesh Observers) and correct value can now be set unblocking bug referenced below
- Fixes: #6294 
> …
=> Profile Type filtering inspector fix

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
This change adds Begin/EndChangeCheck calls in each of the anonymous delegates in the MixedRealityToolkitConfigurationProfileInspector.
The previous implementation noticed changes to the profiles, but not to the concrete service types.
fixes #6316
=> Fix #6316 - service type changes not detected

Assets/MixedRealityToolkit.SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Incorrectly formatted xml comments were creating an intellisense issue that was impacting the ability to debug while running in the Unity editor.
This change fixes the comments and resolves the preprocessor errors 
Thanks @andreiborodin for indentifying the issue!
=> fix preprocessor intellisense error

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/MaterialGallery.unity, scripts/ci/validatecode.ps1
This PR automates checking the number of MixedRealityPlayspaces in a Unity scene. This is a solution to issue #6202 where multiple MixedRealityPlayspace objects were found in example scenes during testing for the 2.1 release that caused issues at runtime.  PR #6197 deleted the extra playspaces found in the example scenes for the release.  
A check for multiple playspaces in each unity scene has been added to validatecode.ps1 to avoid issues in the future.  
- Added CheckUnityScenes function to validatecode.ps1
- Deleted extra MixedRealityPlayspace in MaterialGallery scene, which was identified by the update to validatecode.ps1
>
> git …
=> Added check for multiple MixedRealityPlayspace objects to validatecode.ps1 

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs
StabilizationPlaneModifier did not check if gaze raycast was valid and actually hit an item in it's plane setting. This change fixes that
- Fixes: #6263 
Follow steps in bug #6263 and notice gizmo plane now at correct distances in gazemode
>
>
=> Stabilization plane fix

Assets/MixedRealityToolkit.Tests/PlayModeTests/BoundingBoxTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs
Fixes intermittent test failures  #6121: 
- ScaleViaHoloLens1Interaction in BoundingBoxTests.cs
- TestGazeProviderTargetNotNull in FocusProviderTests.cs
ScaleViaHoloLens1Interaction and TestGazeProviderTargetNotNull were tested 200 times with 100% passing with an extra yield return null.
- Added extra yield return null for two tests
>
>
=> Fix intermittent test failures for ScaleViaHoloLens1Interaction and TestGazeProviderTargetNotNull

Assets/MixedRealityToolkit.SDK/StandardAssets/Materials/MRTK_FingerTipCursor.mat
Quick fix to exposed shader variables on MRTK_FingertipCursor.mat to more closely match the appearance of the shell fingertip cursor.
| Expected appearance  | Current appearance  | Suggested appearance |
| ------------- | ------------- | ------------- |
| ![MicrosoftTeams-image](https://user-images.githubusercontent.com/16657884/67342667-9ff88d80-f4e7-11e9-8f81-6279c7b34c91.png) | ![FingerTipPre](https://user-images.githubusercontent.com/16657884/67342697-c1597980-f4e7-11e9-8ef9-23f2bc7a95e2.PNG) | ![FingerTipPost](https://user-images.githubusercontent.com/16657884/67342714-ce766880-f4e7-11e9-9d5a-2dbd77a22a96.PNG) |
- Fixes: #6351
=> Edited shader variables to more closely resemble shell appearance

Assets/MixedRealityToolkit/Utilities/Async/Internal/AsyncCoroutineRunner.cs
This check was removed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5951, but is still needed.
>InvalidOperationException: The following game object is invoking the DontDestroyOnLoad method: AsyncCoroutineRunner. Notice that DontDestroyOnLoad can only be used in play mode and, as such, cannot be part of an editor script.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6353
=> Re-add #if !UNITY_EDITOR to AsyncCoroutineRunner

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, pipelines/ci-daily.yml, pipelines/ci-packaging-dontpublish.yml, pipelines/ci-packaging.yml, pipelines/ci-release.yml, pipelines/ci.yaml, pipelines/pr.yaml, pipelines/templates/assetretargeting.yml, pipelines/templates/ci-common.yml, pipelines/templates/common-Unity2019.yml, pipelines/templates/daily.yml, pipelines/templates/generateprojects.yml, pipelines/templates/tasks/unitybuild.yml, pipelines/templates/tests.yml
Adds a daily build intended to be scheduled once a day. This build allows us to verify additional build flavours without clogging the main CI and PR pipelines. To begin with, I've added an ARM64 build that only runs on the daily build.
Alongside these changes I needed to modify the build scripts to allow us to build ARM64 on CI. This included adding `ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch` to the VS project. I believe this issue has been seen elsewhere for ARM64 builds.
=> Add daily build with ARM64 build flavour

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Extensions/InteractionSourceExtensions.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit/Interfaces/Devices/IMixedRealityControllerPoseSynchronizer.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs
* Adds a controller model cache for platform models, so we aren't reallocating and reloading the glTF model every time the same controller is detected.
* Removes the haptics extensions, as they referenced a DLL we don't currently distribute, so they don't currently work.
* Fixes some null propagation issues
* Removes some duplicate methods
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5437
Deploy an MRTK example scene app to your WMR machine. Open the app, and open a slate while inside the immersive experience. Move your controller's pointer between the slate and the immersive experience. You should see the controller flip back and forth between the shell's model and the app model without much delay.
=> Cache controller model instead of reallocating each detection

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystemEditorOperations.cs, Assets/MixedRealityToolkit/Utilities/Scenes/EditorSceneUtils.cs
Adds a check to EditorSceneUtils to ensure we don't execute editor scene features while editing a prefab.
- Fixes: #6312
>
>
Try editing a prefab while the scene system is active and all editor features are enabled.
=> Scene System editor features no longer interfere with prefab editing

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs
When I put in a fix for UnityUI based buttons moving visuals getting moved incorrectly, I broke the case where the visual is itself (which it default to if it's null).
- Fixes: #6242.
=> Fix for issue #6242

pipelines/ci.yaml
Increase CI timeout from 90 to 120. We should have a follow-up task to determine if we can parallelize some of these tasks across machines and we if we can cut down on the runtime.
- Fixes: #6381
=> Increase CI timeout from 90 to 120

Assets/MixedRealityToolkit.SDK/Inspectors/Input/Handlers/MixedRealityControllerVisualizerInspector.cs
Any classes that derive from our base `MixedRealityControllerVisualizer` class didn't use its special inspector. This lead to some unclear inspectors, even for the WMR-specific visualizer we ship.
This change allows child classes to use the inspector we've specially defined.
Current:
With this PR:
- Related to #5820
=> Use controller visualizer inspector for child classes

Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2InputSimulationProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2InputSimulationProfile.asset.meta, Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2InputSystemProfile.asset
current Default Hololens2 Input System profile  uses the default inputsimulation profile which does not have eye tracking enabled.
this leads to strange behavior in unity as described in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6320
so, adding a DefaultHoloLens2InputSimulationProfile
with both eye tracking and articulated hands enabled
=> add hololens2 inputsimulationprofile

pipelines/ci-daily.yml, pipelines/pr.yaml, pipelines/templates/ci-common.yml
In order to light up more Unity scenarios in our repo, we need to (temporarily?) turn off the .NET build. 
This will unblock #6344.
This will also help #6381.
=> Turn off the .NET build

pipelines/ci-daily.yml
The daily build had been failing due to not finding the build artifacts. As far as I can tell, it's because it was looking for the wrong version number.
=> Daily build was pointing to the wrong MRTK version

Assets/MixedRealityToolkit.SDK/Features/UX/Materials/BoundingBox.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/BoundingBoxGrabbed.mat
Bounding Box becomes opaque black on grab/manipulation. It is prominent on MRC captures.
Adjusted Bounding Box's material color.
- Fixes: #6403
=> Bounding Box material update to match the shell. Transparent body on grab/manipulation.

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MixedRealityToolkit/Utilities/Editor/MixedRealityOptimizeUtils.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, ProjectSettings/ProjectSettings.asset
This change adds support for configuring the Android and iOS player settings required for building AR Foundation applications.
The new settings being configured are:
- Android
- Disable Multi-Threaded Rendering
- Min SDK version == 7.0
- iOS
- Min OS version == 11.0
- Architecture == ARM64
- Set Camera Usage Description
This change completes the work required for #6256
Validated by opening switching between Android, iOS and UWP platforms to ensure the correct settings are displayed in the dialog and modified on completion.
=> Add Android and iOS support to the configuration dialog

Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset, Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHub.unity, Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHubMainMenu.unity, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySceneSystemProfile.asset, Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoUtils.cs
Fixes incorrect scene asset reference in the examples hub scene system profile. Also updates SceneInfoUtils to prevent mis-identifying profile assets as scene assets.
- Fixes: #6384
>
>
=> Fix Example Hub scene error / SceneInfoUtils

Documentation/Contributing/CodingGuidelines.md, Documentation/Contributing/ExperimentalFeatures.md
Make a few improvements to coding, experimental guidelines:
1) Remove requirement about copyright block, it's no longer required: https://docs.opensource.microsoft.com/content/releasing/copyright-headers.html#copyright-headers-in-microsoft-oss-project
2) Add section about adding [Experimental] tag to experimental features.
- Fixes: #6198
=> Coding guidelines: copyright, [experimental] tag

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Unplated.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonIcon.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/PressableButtonIcon.asset.meta
Added icon lift feedback on focus/hover to PressableButtonHoloLens2 button series by adding a new profile with Interactable's offset theme.
- Fixes: part of shell parity items #4200
=> [Shell Parity] Added icon lift on focus to PressableButtonHoloLens2 button

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Removes the general logging if an extension service failed to register.
As far as I saw from my digging, every actual failure case prints its own specific log, except for the benign cases like this one, where the platform just isn't supported.
Also formatting.
- Fixes: #6421
=> Fix extension service registration logging

Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingService.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionService.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityRegisteredServiceProviderProfileInspector.cs
The current extension services were missing some fields in the MixedRealityExtensionService attribute, specifically:
- Name
- Default profile path 
- Package folder
In addition, the extension services profile inspector was not updating the name from the attribute.
Both are resolved by this change.
=> Fix extension services not updating the friendly name and default profile.

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs
RotateAboutGrabPoint now allows you to rotate an object at a distance using one handed far interaction as described in #5957.
This has been fixed on `feature/ux_refactor` for a few weeks, but we feel like it's worth getting this fix in for 2.2.
- `RotateAboutObjectCenter` now uses grip pose rotation, rather than pointer rotation.
- Fixes: #5957.
=> Port RotateAboutObjectCenter fix

Assets/MixedRealityToolkit.Services/InputSimulation/Editor/InputSimulationService.cs
Under certain conditions, the simulated hand would drift and the head would rotate. There are .gifs of this behaviour in the description of #6437.
Previously while converting vectors into different spaces in the InputSimulationService, we were performing superfluous transformations that were potentially introducing error. These changes update these functions to use the projection matrix directly to convert between these spaces.
- Fixes: #6437.
=> Fix for hand drift and head tilt

Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Pointers/DefaultControllerPointer.prefab, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs
This PR consists of changes to the DefaultControllerPointer prefab and MixedRealityLineRenderer.cs. 
Increased parity with shell appearance was made by tweaking public variables in the MixedRealityLineRenderercomponents. All states of the DefaultControllerPointer ray now appear very similar to the shell rays.
In addition to editor changes, I wrote a coroutine that occurs on enable of any DefaultControllerPointer. It dims the ray from 100% to 55% by default (these values are customizable). This animation accomplishes two things:
1. It answers feedback the design team received about the hand ray being too bright.
2. The initial brightness draws attention to the ray and the fade animation to a lower brightness is pleasant, in my opinion :) 
The video below is not a perfect demonstration of …
=> DefaultControllerPointer ray brightness

scripts/ci/validatecode.ps1
We've fixed a number of hardcoded path related issues in the past, and we're still seeing them get checked in. This adds a verifier to ensure that we don't add new ones, while still having a way to have exceptions in cases where they are actually legitimate.
This has exceptions for the existing custom profile generator and test code, along with the scene system .unity files that are breaking arbitrary folder moves.
=> Add build tooling to ensure that we don't check in more hardcoded paths

Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/PhysicsMaterials.meta, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/PhysicsMaterials/ManipulatorMaterial.physicMaterial, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/PhysicsMaterials/ManipulatorMaterial.physicMaterial.meta, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scenes/ObjectManipulatorExamplePhysics.unity, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scenes/ObjectManipulatorExamplePhysics.unity.meta, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scripts.meta, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scripts/ReturnToBounds.cs, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scripts/ReturnToBounds.cs.meta, Assets/MixedRealityToolkit.SDK/Experimental/Features/Input/Handlers/ObjectManipulator.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs, Assets/MixedRealityToolkit.SDK/Inspectors/Experimental/UX/ObjectManipulator/ObjectManipulatorInspector.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ObjectManipulatorTests.cs
Previously while manipulating a rigidbody object there was no collisions with static colliders, and the collisions with rigidbody objects were jittery and incorrect. Also, making a bounding box object into a rigidbody would in some cases cause the bounding box to collide with its own rotate/scale handles.
These changes ensure that rigidbody manipulation gives the manipulated object proper velocities and angular velocities, so that unity can do proper collision response. The velocities are assigned to emulate existing smoothing.
- `ObjectManipulator` uses lerp/slerp when no rigidbody attached, else uses velocity/angular velocity.
- Ensure that `BoundingBox` rigRoot is has the target object as its parent.
- Add new tests for new collision behaviour.
- Add sample scene.
- Fixes: #6268.
=> Proper collisions while manipulating

Assets/MixedRealityToolkit.Extensions/SceneTransitionService/ISceneTransitionService.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionService.cs
Adds new methods to Transition Service that let you specify fade out / fade in duration.
FadeInTime and FadeOutTime are now treated as defaults.
- Fixes: #6450
>
>
=> Adds fade out / fade in duration control in Transition Service

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/PalmUpHandMenu.prefab, Assets/MixedRealityToolkit.SDK/Features/Utilities/InputRayUtils.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/PointerUtils.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/HandConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/SolverHandler.cs, Assets/MixedRealityToolkit/Extensions/HandednessExtensions.cs, Assets/MixedRealityToolkit/Extensions/HandednessExtensions.cs.meta, Assets/MixedRealityToolkit/Providers/Hands/HandJointUtils.cs
HandConstraint is simplified to follow properties set in SolverHandler instead of overriding and tracking hands itself. Further, the UnityEvents have been updated to fire properly.
- HandConstraint now leverages SolverHandler's ability to track/switch between particular hands. 
- HandConstraint can choose to ignore the tracked hand if it considers it not valid or request SolverHandler to switch hands (if possible) via PreferredTrackedHandedness
- Added PreferredTrackedHandedness property which indicates which hand to default to when both are available
- UnityEvents now allocated by default so easier extension via code
- OnHandActivate/Deactivate fire whenever a hand is supported or not
- Created HandednessExtensions to simplify code interaction
- HandMenu prefab updated to hide …
=> Fix and simplify HandConstraint solver tracking

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoUtils.cs, Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs
Removes some `Debug.Log` messages when nothing actually changed. All of these have logs for when things change or fail to change, but not when the "regular" path is taken.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6468
=> Remove extraneous Debug.Log messages

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Materials/InvisibleBacking.mat, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Materials/InvisibleBacking.mat.meta, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity, Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/segoeui SDF.asset, Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/seguisb SDF.asset
Update font materials to write to depth by default. This primarily fixes the HandInteractionExamples scene from having wavy font with depth LSR on
Added invisible quad behind unity UI canvas example to write depth
Before:
After:
- Fixes: #6449 
>
>
=> Update text materials to write to depth by default

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs, Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs
The build configuration added in #5891 sometimes ran in contexts where it shouldn't, like IL2CPP builds where additional C# projects aren't generated.
I wrapped all calls, including making the checkbox visible, in a check for both .NET as the scripting backend and Unity C# Projects enabled.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6308
=> Update unsafe code build tool to only run when contextually relevant

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Bools resolve as false first, then true, in default ordering. This updates by using the `Descending` APIs instead.
- Fixes: #6297
=> Fix VS ordering in UwpAppxBuildTools

Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles_Object_Space.shader
This shader has some Unity warnings, including use of an old API. This change removes the old API and updates to `UnityObjectToClipPos`.
- Fixes part of #6475 (the `UNITY_MATRIX_MVP` part)
=> Update SR_Triangles_Object_Space.shader to use UnityObjectToClipPos

README.md
Before re-enabling listing the build status display of our previous releases, we should consider whether or not this is valuable information if the builds get run only once (at release time).
This change removes the release branch status display.
=> remove release branches from build status

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
When a HoloLens is detected attached, the build window will now display "HoloLens over USB" instead of "Local Machine". The IP Address was currently left alone to prevent downstream effects that are currently hardcoded for those words but behave correctly.
There is still more work to be done here to improve the build window, currently planned for 2.3.
- Helps with #5698
=> Update build tools deploy name when HoloLens is attached

Assets/MixedRealityToolkit/Utilities/Rendering/MaterialInstance.cs
Updates the warning in MaterialInstance according to #6271, to downgrade it from an assert error to a warning. It also updates the message slightly.
I wasn't able to add the `Renderer` name, since this is a static method and the renderer reference requires an instance.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6271
=> Update MaterialInstance warning

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/InteractableEvent.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
It's possible for Interactable to be working fine but to have some event receivers with empty `iEvent.ClassName` fields. When this happens, the Interactable works, but logs an error which can be disruptive to users (shows up in error console on HoloLens, for example). Since this is not actually breaking functionality and it is not clear how to fix this asset issue without rebuilding an asset. Since this is not actually an error customers can do anything about, log this as a warning instead.
The net result is after this change users no longer see error messages in their console window when using interactable, but will see warnings in the logs. Interactable functionality is not impacted.
I did not add tests for this bug fix because it's unclear how to actually get assets into this error …
=> Fix error when interactable asset has invalid even receivers

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Cursors/FingerCursor.cs
Currently, the fingertip cursor rotates to a target surface orientation while approaching touchable UI. It does not translate and is stationary at a location slightly above the fingertip. This only partially matches shell behavior. In the shell, the cursor rotates and translates to the pad of the fingertip while approaching UI. The amount it translates is relative to the perpendicularity of the fingertip's direction and the normal of the surface. 
Contained in this PR is functionality that translates the fingertip cursor in relation to touchable UI. See below for behavior comparison:
| Current behavior | Suggested behavior |
| ------------- | ------------- |
| ![FingertipCursorPre_Trim](https://user-images.githubusercontent.com/16657884/68256793-e5d44c00-ffe5-11e9-9b66-572f675e8edd.gif) …
=> Fingertip cursor translation/alignment

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/InteractableToggleCollection.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableToggleCollectionInspector.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Fix for issue #6274 
Changing the CurrentIndex property in InteractableToggleCollection via script or the inspector did not update toggle states within the group.  
The changes added get/set methods to the CurrentIndex property and updated SetSelection to trigger an OnClick event. 
- Added custom inspector for InteractableToggleCollection
- Updated InteractableToggleCollection.cs
- Added Test for the changes in InteractableTests
- pull the changes
- open unity project
- add MRTK to the unity project
- add the RadialSet prefab
- press play and change the index in the InteractableToggleCollection, the toggle should be updated to match the index input
> commands (substituting {PR_ID} with the ID of this …
=> Update to InteractableToggleCollection - Fix for 6274

Assets/MixedRealityToolkit.SDK/Features/Input/Events/ManipulationEventData.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs
I ran into a case when prototyping where it would be helpful to know which pointer initiated a manipulation start / end or a hover enter / exit. this change adds that field to the manipulation events, and creates a test to verify that field is not null.
- Fixes: #6498 
>
>
> As a reviewer, it is possible to check out this change locally by using …
=> ManipulationHandler: add Pointer field for manipulation started, ended, hover events

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs
Re-adds this option to the build window, only displayed when the .NET backend is selected.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6505
=> Re-add generate C# projects to build window, when relevant

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/ManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
RotateAboutGrabPoint was not applying hand rotations for far interaction, so that you can rotate objects from a distance. This fix enables that.
RotateAboutObjectCenter far interaction was working like RotateAboutGrabPoint was supposed to; objects could be rotated from a distance, but they were rotated about the grab point rather than the object centre.
- RotateAboutObjectCenter far interaction now rotates about the object centre as described in #6494.
- RotateAboutGrabPoint far interaction now rotates about the grab point using the hand rotation as described in #6495.
- RotateAboutObjectCenter manipulation is now relative to the hand grab point (between the index finger and thumb) rather than the palm. This makes far rotation feel more natural.
- Fixes: #6494, #6495.
=> Fix RotateAboutGrabPoint and RotateAboutObjectCenter far interaction

Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset, Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySceneSystemProfile.asset
These profiles keep reserializing themselves every time the repo is opened, since the referenced scenes don't exist in the repo project's build list.
These profiles should serialize themselves back in an end user's app when the necessary scenes are added.
=> Reserialize scene system profiles based on the state of the repo's scenes

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
We tried to set the enabled state before we had set up a statemanager yet and thus nothing was actually applied
- Fixes: #6508 
>
>
=> Fix interactable to change states after setup of statemanager

Assets/MixedRealityToolkit.Tests/PlayModeTests/CoreServicesTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Previously, the play mode tests relied upon behavior in MRTK where it creates a main camera if one cannot be found in the scene.
In preparation of MRTK enforcing correct scene setup by the developer (in 2.3.0), test preparation now ensures a main camera is present in the scene before adding the MRTK object.
=> Ensure test prep creates a main camera in the scene

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
The TeleportPointer has a few minor issues this fixes.
1. the input threshold check is a square shaped version. I made it round
2. The rotateActivationAngle is checked only for the pre-90-degree portion of the provided value, past 90, the threshold is not checked. the comments state that "Half the rotation activation angle" is calculated, but the value is actually used twice, as it's "mirrored" around the sides and not just used towards the front.
3. the backStrafeActivationAngle check misses out on 180 backwards exactly.
1. use common sense
2. try turning when pressing the analog stick to the slight but slightly to the back
3. try backstepping exactly backwards
=> Couple of fixes for the TeleportPointer

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
This change brings @Alexees' teleport pointer fixes into the 2.2.0 release and reduces the number of calls to Mathf.Pow()
=> cherry-pick teleport pointer fixes from Alexees

Assets/MixedRealityToolkit.Extensions/Providers/Experimental/UnityAR/UnityARCameraSettings.cs, Assets/MixedRealityToolkit.Services/CameraSystem/MixedRealityCameraSystem.cs, Assets/MixedRealityToolkit/Interfaces/CameraSystem/IMixedRealityCameraSettingsProvider.cs, Assets/MixedRealityToolkit/Providers/BaseCameraSettingsProvider.cs, Assets/MixedRealityToolkit/Providers/BaseCameraSettingsProvider.cs.meta
This change adds a base class to handle the required properties and methods defined in the IMixedRealityCameraSettingsProvider interface.
The experimental UnityAR provider has been updated (with some other small changes) to use the base class.
=> Add base class for camera settings providers

Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/RoomFileFormat/RoomFileSerializer.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Events/ReceiverBase.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/VisualThemes/ThemeInspector.cs, Assets/MixedRealityToolkit.Services/InputSimulation/Editor/BaseInputSimulationService.cs, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Components/FocusRaycastTestProxy.cs, Assets/MixedRealityToolkit/Attributes/SystemTypeAttribute.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MixedRealityToolkit/Providers/BaseInputDeviceManager.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs, Assets/MixedRealityToolkit/Providers/GenericPointer.cs, Assets/MixedRealityToolkit/Providers/Hands/BaseHand.cs, Assets/MixedRealityToolkit/Services/BaseCoreSystem.cs, Assets/MixedRealityToolkit/Services/BaseDataProvider.cs, Assets/MixedRealityToolkit/Services/BaseDataProviderAccessCoreSystem.cs, Assets/MixedRealityToolkit/Services/BaseExtensionService.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs, Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, Assets/MixedRealityToolkit/Utilities/GameObjectManagement/GameObjectCreator.cs, Assets/MixedRealityToolkit/Utilities/Physics/Distorters/Distorter.cs
1. Updates constructors of abstract classes to protected, since you can't create an instance of an abstract type.
1. https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1012?view=vs-2019
1. Update some data structures that don't get reallocated at runtime to readonly
1. Fixed some cases of incorrect null propagation on Unity objects
1. https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/
1. Added `static` to EditorProjectUtilities
1. https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1052?view=vs-2019
1. Formatting and some comment updates
=> Make abstract constructors protected, update some data structures to readonly, and some formatting and comment updates

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
apply rotation on bounds which is created based on `midpointVisual` to be applied to the box collider taht is created on `midpoint`.
- Fixes: #6507  .
>
>
> …
=> Bugfix boundingbox rotationhandle

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Editor.InEditor.Template.props.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Platform.Configuration.Template.props.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.Editor.meta.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.Standalone.meta.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.WSA.meta.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/SDKProjectTemplate.csproj.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/SolutionTemplate.sln.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Microsoft.MixedReality.Toolkit.MSBuild.asmdef.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssemblyDefinitionInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CSProjectDependency.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CSProjectInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/CompilationPlatformInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/MSBuildTools.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/MSBuildTools.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/PluginAssemblyInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/ReferenceItemInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/SourceFileInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TargetFramework.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TemplateFiles.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/UnityProjectInfo.cs.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/Utilities.cs.meta
The MSBuild folder, which itself came from the MSBuildForUnity project, contains some of the same GUIDs, which led to conflicts when both MRTK and the published MSBuildForUnity project were imported.
There were also some menu item conflicts. Both have been resolved in this PR.
=> Resolve MSBuildForUnity conflicts with published package

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/InspectorUIUtility.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityStylesUtility.cs
This change is a polish pass on Interactable inspector. Primarily event receivers and themes details of an interactable would render everything by default. Especially for complex Interactable prefabs, this could be a bit overwhelming and annoying to scroll/navigate. 
- Made theme details and event receiver foldouts hidden by default. 
- Removed unused size parameter in inspectoruiutility draw foldouts
- Added helpbox style around events section
After:
Before:
- Fixes: # .
>
>
=> Interactable inspector polish

NuGet/BuildSource.proj, pipelines/templates/compilemsbuild.yml, scripts/packaging/createnugetpackages.ps1
With the addition of the experimental Unity AR camera settings provider, MRTK has a need for precompiled Android and iOS players, when distributing via NuGet.
This change enables the build rules for these players. Once approved and merged, the nuspec files will be updated to include these player builds.
This is part 1 of the change that will resolve #6441
=> add build rule for android and ios players

pipelines/templates/compilemsbuild.yml
Removes a duplicate `Build InEditor WSA` step
- Fixes:
=> Remove duplicate build step

Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles.shader, Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles_Object_Space.shader, Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_triangles_Lost_Tracking.mat
After fixing an issue in #6476, it appears to have caused a second shader error.
This math / variable doesn't even appear to be used, so I've removed it from both shaders.
- Fixes: #6577 
Ensure the features that use these shaders (Lost Tracking Service) still render correctly.
=> Remove unused matrixVP to prevent shader error

Assets/MixedRealityToolkit.Examples/Demos/Boundary/Scripts/BoundaryVisualizationDemo.cs, Assets/MixedRealityToolkit.Services/BoundarySystem/MixedRealityBoundarySystem.cs, Assets/MixedRealityToolkit/Definitions/BoundarySystem/BoundaryType.cs, Assets/MixedRealityToolkit/Definitions/BoundarySystem/BoundaryType.cs.meta, Assets/MixedRealityToolkit/Interfaces/BoundarySystem/IMixedRealityBoundarySystem.cs, Documentation/Updating.md
In preparation for Unity's future boundary types, this PR looks to remove dependencies on Unity types.
=> Update boundary system to use MRTK type instead of Unity type

Assets/MixedRealityToolkit/Inspectors/Utilities/InspectorUIUtility.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs
#6597 identified an issue where non-destructive / informational controls were disabled in the profile inspector when showing sub-profile views.
This change renders View Asset and Documentation buttons enabled _always_.
=> Always enable View Asset and Documentation buttons in profile inspectors

Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingService.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionService.cs
A recent change to the extension services moved the location of the default profiles. This rendered automatic population of the default profile non-functional.
This change fixes the pathing issue.
=> fix auto-population of default profile

Documentation/hologram-stabilization.md
The pixels representing the sphere will have a different transform than the far away pixels representing the pillar if the user has **titled** their head slightly.
->
The pixels representing the sphere will have a different transform than the far away pixels representing the pillar if the user has **tilted** their head slightly.
=> Fix typo in hologram-stabilization documentation

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorObjectDisplay.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorOrbsRotator.cs
Two of our progress indicators serialized their state field. This gave the impression that the progress indicator's state could be set manually. The fields are now private to prevent unintended usage.
Fixes: #6593
=> Progress Indicator State Field Fix

Assets/MixedRealityToolkit.Providers/OpenVR/GenericOpenVRController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/OculusTouchController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/ViveKnucklesController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/ViveWandController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityGGVHand.cs, Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedArticulatedHand.cs, Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedGestureHand.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/InteractionDefinitionTests.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityInteractionMapping.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/UnityTouchController.cs
Updates a constructor `MixedRealityInputAction` to match the documented optional nature of this parameter.
This enables us to clean up some overly verbose additions of `MixedRealityInputAction.None` to many interaction mappings, something this constructor already takes care of.
=> Update MixedRealityInputAction constructor

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec
This change instructs the build pipeline to not include script source files in the nuget packages.
This is done because of an issue with NuGet for Unity and very long file names.
=> disable packaging of source code in nupkg files

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Following #6528, which introduces bug #6582
- Now rotating depending on the handle edge orientation (and no the visual mesh itself)
- Also fixes for scale handles : this seems to work fines with the example scene, but it's hard to know if it will work in every situation.
this fix will use the center of the mesh as the center of the box collider and will rotate accordingly ot the corner, another option would be to center iton the exact corner position (that's the commit jsut before that sets the center at Vector3.zero
A unittest checking if the mesh isinside the handleboxcollider won't guarantee it either (box collider size does not depends sololy on the mesh, but mosty on 'size' and 'padding' properties)
- Fixes: #6582 and #6507.
- Double check my math :)
- Feel free to cherrypick what …
=> Bugfix boundingbox rotationhandle #2

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.Android.meta.template, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.Android.meta.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.iOS.meta.template, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/Plugin.iOS.meta.template.meta, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
This change completes the work specified in #6441 by updating the build tooling to package prebuilt players in the foundation package.
Verified this change by running the packaging commands locally and inspecting the contents of the nupkg file,
=> package android and ios players in foundation (#6441)

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/GrabScaleTheme.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/HolographicButtonSeeItSayItLabel-Simple.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/HolographicButtonSeeItSayItLabel.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/Model_BuckyTheme.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/Core/ThemeDefinition.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/Core/ThemeProperty.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableOffsetTheme.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableRotationTheme.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableScaleTheme.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableThemeBase.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/ScaleOffsetColorTheme.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/VisualThemes/ThemeInspector.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/VisualThemeTests.cs, Assets/MixedRealityToolkit.Tools/ReserializeAssetsUtility/ReserializeAssetsUtility.cs
Make scale theme consistent with other themes by having a scale relative to initial object scale and not absolute.
- Fixes: #6459
>
>
> …
=> interactable scale theme now relative to gameobject initial scale

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
CanInteract() in Interactable was used in some of the wrong input handler and other input handlers did not have any guard at all. This change remedies those missing guards.
Ensure Touch input is not responsive when !IsEnabled
Remove CanInteract guard on focus
Add IsEnabled guard on TriggerOnClick
Tests
-> Merge TestSelectGlobalInput and TestSelectGlobalInputOnDisabled
-> Merge TestSelectMenuInput and TestInputActionMenuInput
-> Add test for touch states (both enabled & disabled)
-> Add test for TriggerOnClick public API
-> Add HasFocus asserts on InteractableToggleCollection test (aka RadialSet)
-> Clean up helper methods and variables for re-use in InteractableTests class
- Fixes: #6100 , #6489 
> …
=> Fix CanInteract in Interactable

Assets/MixedRealityToolkit.Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs
Removed System out of `#if UNITY_STANDALONE_WIN || UNITY_WSA || UNITY_EDITOR_WIN` in WindowsSpeechInputProvider.cs because of missing ref issues while using a Mac #6638
- Fixes: #6638
>
>
=> System namespace fix in WindowsSpeechInputProvider.cs

Documentation/README_Solver.md
Image references had weird path that was redundant and not necessary
Before:
- Fixes: #5929 
>
>
=> Fix Solver Doc Images

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.Services/InputSimulation/Editor/BaseInputSimulationService.cs, Assets/MixedRealityToolkit/Interfaces/Devices/IMixedRealityController.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs
This method was taking in an `InputSourceType`, though one is already saved for this controller as part of its `InputSource`.
Instead of having this second parameter, it's been marked as `Obsolete` and the type is now read from the `InputSource`
=> Update BaseController.SetupConfiguration parameters to no longer take in a source type

Documentation/Contributing/CodingGuidelines.md
I was reading this as part of reviewing another change, and noticed some immediate spelling errors really early on in the doc, which can reduce confidence on the quality of the rest of it (i.e. if the first thing you see is a spelling mistake in a long document, it can make you go like... huh...)
There was also a broken link (to CI) that was referencing a specific build from ages ago - that build information has long been cleared, so it was a dead link. I've updated that link to point the mrtk_pr build (which I believe is the most relevant given the other context in that area)
=> Fix spelling errors and dead links in the coding guidelines.

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
This change swaps out the Editor DLL that is packaged as part of MRTK Foundation. Instead of using the Editor DLL build for standalone platform, it uses the Editor DLL built for WSA platform.
- Fixes: #6391
=> Fix Editor Hands with VR

Documentation/README_SystemKeyboard.md
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6581
The old link was pointing to the wrong thing (or rather, it was right at one point but files have been moved) - this points it at the right/current thing.
=> Fix broken link to the System Keyboard Example

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs
When creating a new Interactable, the inputactionid was set to -1. This is actually kind of silly because on awake, the id is clamped to available values of the input actions profile list. This defaults it back to 0 so at least in the editor it appears correct
**Before:**
**After:**
- Fixes: #
>
>
=> Fix Interactable default input action

Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/ConstructGltf.cs
Fix for FileNotFoundException that appeared on import of the Examples package on a Mac.
- Fixes: #6643 
>
>
=> Fix for FileNotFoundException on Mac - Issue 6643

Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubRegisteredServiceProvidersProfile.asset, Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset, Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneTransitionServiceProfile.asset, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/Profiles/DefaultSceneTransitionServiceProfile.asset, scripts/ci/validatecode.ps1
The scene transition service profile had some invalid types, fix this by clicking "repair" button and updating assets. 
Invalid assets, I clicked "repair" to the right to fix these
Currently trying to see if I can write a CI script to detect all references to invalid types in assets.
- Fixes: #6669
- Add script to ensure that CI catches any invalid references to assemblies in the profile assets
=> Fix invalid scene transition service profile

Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles.shader, Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles_Object_Space.shader
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6609
The original change that added these shaders had a few warnings:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5988
In particular, there was some code that added while loop that would always end up running once (i.e. it would be equivalent to just not having the loop). This gives a warning in Unity, and the MRTK should be warning-free. This work just unrolls the loop manually (i.e. recognizing that it is only ever run once, just getting rid of the loop)
=> Fix SR_Triangles and SR_Triangles_Object_Space shader warnings

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/GrabReleaseDetector.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/OnSelectVisualizerInputController.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/TargetBehaviors/KeepFacingCamera.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Utils/KeepThisAlive.cs, Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Utils/StatusText.cs, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/DemoTouchButton.cs, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/GrabTouchExample.cs, Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/ToggleBoundingBox.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/PointerClickHandler.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Layout/ButtonBackgroundSize.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Layout/ButtonBackgroundSizeOffset.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/InteractableHighlight.cs, Assets/MixedRealityToolkit.Services/InputSystem/InputSystemGlobalListener.cs
Update AddComponentMenus to move obsolete monobehaviours to dedicated "folder" path so users know not to use them
- Fixes: #6567
>
>
> …
=> Add component menu to obsolete

pipelines/ci-release.yml
NuGetForUnity doesn't support SemVer2.0, so we can't make use of prerelease packages that have alpha prepended.
=> Remove the 'alpha' tag from Release CI

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/WindowsDevicePortal/DevicePortal.cs
After Unity reloads assemblies (which it does after a script changes), the authorization token was being lost, since it doesn't get serialized when state is reloaded.
Unity's web request API caches the previous authorization cookie. This causes two things:
1. Our next attempt to authorize succeeds but doesn't return a response, since we're contacting the device with the previous cookie
2. Code that assumed we'd get a response throws a nullref
Now, if the request succeeds but nothing is returned, we ignore the result and move on like normal, since we know we've been properly authenticated via the cached cookie.
Also cleans up some unused fields and adds some documentation.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5697
=> Fix deploy issue after Unity assembly reload

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs
Adds the namespaces from the DotNetWinRT adapter, currently blocked behind `#if DOTNETWINRT_PRESENT`.
This is part 1 of bringing in remoting support. With this change, HL2 remoting can be used by manually setting the define in the Unity player settings and manually importing https://www.nuget.org/packages/Microsoft.Windows.MixedReality.DotNetWinRT.
This flow will be improved in upcoming PRs.
- Part 1 of #6244
=> Update WMR scripts with DotNetWinRT support for Holographic Remoting

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableMaterialTheme.cs
Material Theme had invalid line of code controlling whether gameobject host was active or not...but the property for the theme engine was of type material, not bool
- Fixes: #6707 
>
>
=> Material theme should not active/deactivate host gameobject

Assets/MixedRealityToolkit.Tests/PlayModeTests/Components/TestInputGlobalListener.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InputEventSystemTests.cs, Assets/MixedRealityToolkit/Services/BaseEventSystem.cs
When firing regular events, Unity's event system is utilized. If the calling object throws an exception, Unity handles that and it does not crash the input system for the current frame. For global listeners, we are invoking the event handler's directly. Thus, any exceptions thrown in client code by consumers could crash our system. This change wraps the call in a try-catch to ensure the input system resumes running
Example class that can crash the input system from continuing execution
```c#
using Microsoft.MixedReality.Toolkit;
using Microsoft.MixedReality.Toolkit.Input;
using UnityEngine;
public class TestGlobal : MonoBehaviour, IMixedRealityFocusHandler
{
public void OnFocusEnter(FocusEventData eventData)
{
GameObject c = null;
c.transform.position = Vector3.zero;
}
public void …
```
=> Don't crash on global listeners

.gitignore, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter.meta, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/DotNetAdapter.csproj, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/DotNetAdapter.csproj.meta, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/NuGet.config, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/NuGet.config.meta, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs
Along with @davidkline-ms's #6718, this will pull down the DotNetWinRT dependency.
Along with #6702, this will support full holographic remoting for HoloLens 2!
Also a slight update to the eye gaze data provider.
Docs will be incoming, but I want to unblock testing.
- Part of #6244
=> Add csproj and nuget for DotNetWinRT

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
This change resolves a CI issue introduced by #6720 where the DotNetWinRT.dll was being scanned for asset retargeting and its namespace was not expected.
=> add support for dotnetwinrt adapter in asset retargeter

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
There was an incorrect check in asset retargeting that was failing on valid namespaces. This change addresses that error,.
=> fix logic error in asset retargeting

Assets/MixedReality.Toolkit.Foundation.nuspec
Portions of the MRTK foundation now require the Microsoft.Windows.MixedReality.DotNetWinRT package to make accessing some platform functionality significantly easier.
This change adds the dependency to the nuspec file and fixes #6631
=> Add new foundation package dependency

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs, Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, ProjectSettings/ProjectSettings.asset
#6718 added automatic modification of the package manifest to add MSBuild for Unity on project load.
This change moves this to the MRTK Configuration dialog to allow customers to choose when / if they wish it to be installed.
Fixes #6723
A Getting Started documentation update describing MSBuild for Unity and its benefits will follow this PR shortly.
Also included in this change is an update to how the configurator writes out the required iOS version (was writing "11" needs to be writing "11.0").
=> Move MSBuild for Unity enabling to MRTK Configurator

Packages/manifest.json
#6787 identified an issue that was causing the DotNetWinRT plugin to be packaged into the foundation unitypackage as part of CI.
This change updates the manifest.json file to address the packaging issue.
=> update manifest to not auto-pull msbuild for unity

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Profiles/DefaultWindowsMixedRealityCameraSettingsProfile.asset, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityCameraSettingsProfile.cs
This change addresses #6732 by adding a message qualifying which versions of Unity support the MRC capture settings provided by the Windows Mixed Reality camera settings provider.
It also marks this feature as experimental as there have been some issues with hologram stability in MRC recordings.
The default profile ships with the setting disabled. Customers can enable by cloning and modifying the profile.
=> Mark MRC capture settings as experimental, disabled by default

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs, Documentation/Contributing/CONTRIBUTING.md, Documentation/Contributing/CodingGuidelines.md, Documentation/Contributing/UnitTests.md
Updates the recommended version from 2018.4.12 to 2018.4.13.
Also, updates the Microsoft contribution header to the currently recommended internal guidelines on https://docs.opensource.microsoft.com/content/releasing/copyright-headers.html
=> Update recommended version for new MRC and header update

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/DotNetAdapter.csproj, Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs
This change picks up the latest version of MSBuild for Unity. 0.8.2 fixes a key issue with switch8ing API compat level in Unity.
Also included is a small change to the DotNetAdapter.csproj file that adds wildcards to the NuGet package and MSBuild version numbers.
=> update MSBuild for Unity reference to v0.8.2

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs
Fixes #6751 which was incorrectly laying out content when layout was `ColumnThenRow`. The root issue was that the component was always actually laying out using rows, then columns.
Before when number of items 10, 3 columns, layout ColumThenRow:
After using same setup (10 items, 3 columns):
Filed a follow-up issue #6752
=> Fix gridobjectcollection layout when using ColumnThenRow

Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs
While investigating #6765, it was found that the mouse device manager does not automatically set its default profile when selected.
Added "MixedRealityToolkit.SDK" to the data provider attribute to inform the system the location of the file.
=> fix mouse provider not auto selecting profile

Assets/MixedRealityToolkit/Attributes/MixedRealityServiceProfileAttribute.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityEyeTrackingProfile.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityProfileUtility.cs
Updates the `MixedRealityServiceProfileAttribute` to support multiple required types and multiple excluded types.
The default constructor still accepts one required type and no excluded types, so this is a non-breaking change.
Also updates the eye tracking profile to require both `IMixedRealityEyeGazeDataProvider` and `IMixedRealityEyeSaccadeProvider.` This requirement excludes eye tracking profiles from the input simulation profiles list:
- Fixes: #6765
>
>
=> Mrtk profile requirements

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
This removes the error icon from SystemType fields with missing types and replaces it with an error color. The icon was rendering inconsistently between different versions of Unity.
This fixes issues where service types were missing but not noticed due to a lack of visual feedback.
>
>
=> Fix missing error icon in TypeReferencePropertyDrawer

Assets/MixedRealityToolkit.SDK/Features/UX/Materials/HandIndexTip.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/HandIndexTip.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/HandJoint.mat, Assets/MixedRealityToolkit.SDK/Features/UX/Materials/HandJoint.mat.meta, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Hands/HandJointSmall.prefab, Assets/MixedRealityToolkit.SDK/Features/UX/Prefabs/Hands/HandJointSphere.prefab
This change creates two new materials to be used directly with the default hand joint mesh visualization. 
One material for the hand joint cubes. This new material is opaque instead of transparent allowing for true dynamic batching of all joints into a combined draw call. 
One material for the hand joint index tip spheres. This material turns off hover light and other unnecessary items and turns on GPU instancing so both index tips are drawn in one call.
**Before**
**After** 
- Fixes: # .
> on the specific scenarios and what you want …
=> Create optimize materials for hand joint mesh visualization

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs, Assets/MixedRealityToolkit.Services/InputSimulation/Editor/InputSimulationService.cs, Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs, Assets/MixedRealityToolkit/Utilities/MixedRealityServiceRegistry.cs
This change cleans up some of the unnecessary GC allocation every frame. Although these are minor in size, they do add up over time and more importantly can be easily avoided without changing functionality. 
MRTK.ExecuteOnAllServicesInOrder - 40B
Due to foreach loop on IEnumerable
DefaultPointerMediator.ApplyCustomPointerBehaviours - 366B
Due to action allocation that can be a standalone function
InputSimulationService.UpdateMouseDelta - 92B
Re-used MouseDelta class instead of allocating every update
- Fixes: #6772 
>
>
=> Clean up unnecessary GC allocation every frame

Assets/MixedReality.Toolkit.Foundation.nuspec
This change updates the nuspec file to specify an updated minimum version of the Microsoft.Windows.MixedReality.DotNetWinRT package.
=> update DotNetWinRT min version

Assets/MixedRealityToolkit/Definitions/BaseMixedRealityProfile.cs
Adds `[HideInInspector]` to BaseMixedRealityProfile, to clean up any profiles that inherit from this class but don't provide their own custom inspector.
- Fixes:
to this
=> Add [HideInInspector] to isCustomProfile

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitTests.cs, Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs, Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Minor fix for Facade handler and MRTK initialize.
- Facade Handler was destroying objects as it enumerated through the list but destruction cause an invalid enumerator. Change uses for loop instead of foreach and deletes in reverse
- When there is no active profile, MRTK initializes and logs error. In Unity Editor, it is more appropriate as a warning while it will be an error on device/runtime. This is because MRTK runs in edit mode.
- Fixes: #6794 6794
>
>
=> Fix FacadeHandler throwing exception

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6702 changed this `#if` from `ENABLE_DOTNET` to `NETFX_CORE`. For now, changing this back to the previously known-good `#if` while NuGet investigations are ongoing.
=> Revert ifdef changes

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs
This is part 2 of 2 to fix issue #6773. Previously, asset upgrade would detect if layout was `ColumnThenRow` and fix up columns field. However, in 2.1 and below layout would always run by `RowThenColumn`, even if layout was specified as `ColumnThenRow`. To ensure behavior for 2.1 assets is the same, change layout to be `RowThenColumn` for all assets that had layout `RowThenColumn`
- Fixes: #6773
Still need to test that assets are changed properly when updating from 2.1 to 2.2.
=> On asset upgrade change columnthenrow to rowthencolumn layout

Assets/MixedRealityToolkit/Utilities/MaintainBorderLightWidth.cs
MaintainBorderLightWidth.cs component scales the correct border light width value based on scale changes of the gameobject at runtime. Originally though, this calculation would be performed every lateupdate(). Although not incredibly noteworthy and expensive, this component is on ever button which in for example the HandInteractionExampleScene adds up. 
This change caches the previous lossyscale value for the GameObject and only performs the border width light update if the GameObject's scale has changed. 
Furthermore, the shader property id has been switched to static since it'll be a constant value for every component. 
- Fixes: # . …
=> Execute borderlight width calculation only on scale changes

Documentation/ReleaseNotes.md
This change adds details on the one-time setup steps for HoloLens 2 remoting as well as instructions for connecting to the device.
Also adds a note re: an observed issue with projects that have spaces in the path.
=> Update release notes: add remoting steps and a note re: projects with spaces.

Assets/MixedRealityToolkit.Tests/PlayModeTests/ManipulationHandlerTests.cs, Assets/MixedRealityToolkit/Utilities/Physics/TwoHandMoveLogic.cs
Previously, moving your hand down while you were manipulating an object moved the object further away. This was because the distance from the head was used to scale the manipulation distance. Now, we ignore y in this distance calculation, meaning you have to move your hand further from your body in order to scale the manipulation distance.
See .gifs below for comparison. The .gifs in #6589 demonstrate the problem very well.
- Fixes: #6589.
=> Only scale manipulation for xz distance

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs
Fixes #6814 by ensuring that newly created assets do not have ColumnThenRow layout, which is what triggers the asset upgrade in (asset version must be 0 and layout must be ColumnThenRow).
Additional changes:
- Update tooltip and logging
The bug is caused because newly created assets will have asset version 0, and also assets that actually are old and need to be upgraded will have asset version 0. This problem would happen in all cases when we are adding asset versions to assets that already exist.  It would be great to find another way to solve this problem, but for now this approach fixes #6814 and will prevent log messages from showing up whenever a grid object collection gets added in MRTK 2.2. See keveleigh's comments in #6814 for some more details. Until we find a better solution …
=> Change default GridObjectCollection layout order to "RowThenColumn" to avoid asset upgrade when new assets created

Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceWizard.cs, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/Templates/ExtensionScriptTemplate.txt
This change cleans up the extension service wizard. In particular,
Allow one folder quick selection for all files to be created
Fix registrar constructor from obsolete to valid in template
Fix supported platforms to be -1 when everything
Added MRTK logo to window and tab icon
Added progress bar instead of ellipsis for async
General polish and code clean up (use scopes, better disables, rich text logging, use string building and string formatting instead of concatenation and more)
- Fixes: #6776 , #6775 , #6774 
>
>
=> Extension service wizard fixes

Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs, Documentation/GettingStartedWithTheMRTK.md
the default profile is now automatically set in the mrtk gameobject on configuring the scene.
the documentation reflects the new change
- default profile is selected in case there's nothing selected when adding the mrtk gameobject to the scene
documentation explains to the user that they can chance the profile but we preselect the default profile for them
didn't add any pictures/screenshots on purpose as the text description should be enough and we shouldn't screenshot inspector properties 
tested adding the MRTK gameobject to a new scene and checked if default config profile is set
=> Added setting of default configuration profile in case there's none set for adding the mrtk gameobject to the scene

Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs
MSBuild for Unity is taking some changes that address issues discovered while using it with MRTK. This PR increases the version number that will be written to the manifest.
Please note this should NOT be merged until the new MSBuild update has been published.
=> Update version of MSBuild for Unity

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildMRTKTemplates/WSA.InEditor.Template.props.template, Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildMRTKTemplates/WSA.InEditor.Template.props.template.meta, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec, scripts/packaging/NuGetRestoreProject.csproj
1. Filters out the DotNetAdapter folder from being packaged in the NuGet package.
1. This prevents the csproj from being packaged, which would cause MSBuildForUnity (if present) to resolve its dependency and a duplicate DotNetWinRT DLL.
1. Adds a custom WSA.InEditor.Template.props, to add the `DOTNETWINRT_PRESENT` define and add a package reference to DotNetWinRT.
1. Adds `https://api.nuget.org/v3/index.json` to the package restore csproj, used during local NuGet packaging, due to the new DotNetWinRT dependency.
- Fixes: #6244 
1. The WSA Player DLL still needs to be updated with the define and reference. @andreiborodin is helping with the investigation.
=> Fix building NuGet locally and add support for DotNetWinRT in NuGet packages

Documentation/Contributing/DevDocGuide.md, Documentation/MRTKNuGetPackage.md, Documentation/ReleaseNotes.md
Updates the NuGet import steps to add the requirement of NuGetForUnity 2.0.0 or newer, which has some critical fixes for importing MRTK 2.2.
=> Update NuGet import steps

Documentation/Input/InputEvents.md
Fixes two issues in this doc:
1. Two lines ended in `)` instead of `;`.
2. Debug logs were identical between the source detected event and the source lost event, instead of logging the correct state.
- Fixes: #6830
=> Update code in InputEvents doc

pipelines/templates/compilemsbuild.yml
The new WSA InEditor build step needs its own NuGet restore, like the existing WSA Player build step. This is mostly copied and pasted from the existing one.
=> Add special WSA InEditor NuGet restore to CI

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec, scripts/packaging/createnugetpackages.ps1
1. Changes our `projectUrl` from the exact github URL to our managed aka.ms/mrtk URL. This could help us retarget that URL in the future, if needed.
2. Adds a reference to our logo in the package, so we get an icon on NuGet.org and in NuGetForUnity.
=> NuGet packaging update

web/version.js
This change removes prerelease/2.2.0_stabilization from the list of available documentation versions and replaces it with releases/2.2.0
=> Add 2.2.0 to the documentation version list

Documentation/Contributing/CodingGuidelines.md
This section of the coding guidelines survived some refactoring, but should have been deleted at some point in the past - it was part of a section that talks about using foreach vs for (mentioning to use for instead of foreach). This information is somewhat dated now (i.e. see https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4538#discussion_r295852607 - on newer version of Unity it's not really a thing based on those discussions)
See that this chunk of "do" code used to be in the foreach vs for section:
https://github.com/microsoft/MixedRealityToolkit-Unity/blame/22742fe3165cd062b4477cfbdaeaddd2d3734448/Documentation/Contributing/CodingGuidelines.md#L512
=> Removes a stale portion of the CodingGuidelines that talks about unrolled foreach vs. for loops.

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildMRTKTemplates/WSA.Player.Template.props.template
Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6827, fixing the known issue referenced there.
Adds the `#define` and adapter reference to the WSA player DLL to support https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6731
Part of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6244
=> Update WSA.Player.Template.props.template to reference the DotNetWinRT adapter

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityHandTrackingProfile.cs, Assets/MixedRealityToolkit/Providers/Hands/HandJointService.cs
Updates links to HandTracking docs, which changed folder names.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6857
=> Fix links to handtracking page

Assets/MixedRealityToolkit.SDK/Experimental/ScrollingObjectCollection/README.md, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Controllers/README.md, Assets/MixedRealityToolkit.SDK/Profiles/MixedRealityControllerConfigurationProfile.md, Assets/MixedRealityToolkit.SDK/Profiles/README.md, Documentation/Architecture/SystemsExtensionsProviders.md, Documentation/BuildAndDeploy.md, Documentation/Contributing/DevDocGuide.md, Documentation/DownloadingTheMRTK.md, Documentation/Input/InputState.md, Documentation/MixedRealityConfigurationGuide.md, Documentation/README_BoundingBox.md, Documentation/README_HandJointChaser.md, Documentation/README_Sliders.md, Documentation/SceneSystem/SceneSystemGettingStarted.md, Documentation/SceneSystem/SceneSystemSceneTypes.md, Documentation/Tools/DependencyWindow.md, Documentation/Tools/ScreenshotUtility.md
Some links were empty, possibly awaiting the existence of their corresponding docs. Now that those docs exist, I've updated the empty links I found.
I also converted a few crefs into xrefs, since it didn't appear that crefs work in our markdown.
I also added alt text to all our images that were missing them. This is important for the accessibility of our docs to ensure images have alt text for screen readers.
=> Add missing links, convert some crefs into xrefs, add alt text to images

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityDeviceManager.cs
This is a band-aid because the bug is annoying.
As mentioned in the the issue this fixes, checking interfaces for null is not sufficient in the case they were implemented by a UnityEngine.Object. This needs a more profound solution (maybe #5981) though.
- Fixes: #6587.
=> double check interface for null

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Pointers/SpherePointerInspector.cs
There was no way to edit the scene query buffer size for grab pointer in editor. This adds that field to the inspector.
- Fixes: #6878
>
>
> …
=> add scene query buffer size to sphere pointer inspector

Documentation/Contributing/ExperimentalFeatures.md
Following #6492 this pr provides guidance that menu items for experimental features should go under "experimental" sub-menu.
- Fixes: #6466
=> How to add menu items for experimental features

.gitignore
#6315 added a new project preferences object in the `.Generated` folder, but didn't also ignore its meta.
This adds that.
=> Include the MRTK.Generated meta file in .gitignore

Assets/MixedRealityToolkit.Staging/UnityAR/Editor/ConfigurationChecker/UnityARConfigurationChecker.cs
This change includes Unity 2019.1 in the asmdef file check.
Fixes #6854
=> UnityAR asmdef check: update #elif to include 2019_1

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
The capability checker uses api contract checks to ensure that functions are not called on platforms for which they are not supported.
The Windows Mixed Realtiy spatial mesh observer check was incorrectly using version 8 of the contract, which was preventing the code from correctly running on the first generation HoloLens.
This change updates the check to use version 4, which correctly maps to the introduction of SpatialSurfaceObserver.IsSupported
Fixes #6613
=> Correct the api contract version for the spatial issupported check

Documentation/Boundary/ConfiguringBoundaryVisualization.md, Documentation/Diagnostics/ConfiguringDiagnostics.md, Documentation/EyeTracking/EyeTracking_TargetSelection.md, Documentation/README_AppBar.md, Documentation/README_BoundingBox.md, Documentation/README_Button.md, Documentation/README_ExampleHub.md, Documentation/README_FingertipVisualization.md, Documentation/README_HandInteractionExamples.md, Documentation/README_LostTrackingService.md, Documentation/README_ManipulationHandler.md, Documentation/README_NearMenu.md, Documentation/README_ObjectCollection.md, Documentation/README_Slate.md, Documentation/README_Sliders.md, Documentation/README_SystemKeyboard.md, Documentation/README_Tooltip.md, Documentation/SceneSystem/SceneSystemGettingStarted.md, Documentation/Tools/DependencyWindow.md, Documentation/Tools/ScreenshotUtility.md
1. Converts some third level lines that were bolded into headers
2. Removes the trailing `#` from any closed headers, as most of our docs use the unclosed style
=> Standardize docs headers syntax

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Pressable Button get stuck in Gesture State if hand moves to out of focus position in between a pinch and open gestures.
Before:
After:
Interactable.cs handles button states and timeout for reseting HasPress when Input Position goes out of threshold. HasGesture timeout is not being handled.
We assume the following desirable behaviour:
1. Hand focus on Button with far pointer
2. Hand performs Pinch gesture
3. Button enters visual Pressed state
4. Hand Moves pointer to outside of Button focus
5. Button goes back to Default state
6. Interactable does NOT triggers OnClick.
- Fixes: #6641.
> and validate the …
=> Fix Pressable Button State Reset

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation-issue.md, .github/issue_template.md, Assets/MixedRealityToolkit.Examples/Demos/Gltf/Models/Avocado/README.md, Assets/MixedRealityToolkit.Examples/Demos/README.md, Assets/MixedRealityToolkit.Examples/Demos/StandardShader/README.md, Assets/MixedRealityToolkit.SDK/Experimental/PulseShader/README.md, Assets/MixedRealityToolkit.SDK/Experimental/ScrollingObjectCollection/README.md, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Controllers/README.md, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/README.md, Assets/MixedRealityToolkit.SDK/Profiles/MixedRealityControllerConfigurationProfile.md, Assets/MixedRealityToolkit/Providers/Hands/README.md, Documentation/Architecture/InputSystem/ControllersPointersAndFocus.md, Documentation/Architecture/InputSystem/CoreSystem.md, Documentation/Architecture/InputSystem/Terminology.md, Documentation/Architecture/SpatialAwareness.md, Documentation/Architecture/SystemsExtensionsProviders.md, Documentation/Boundary/BoundarySystemGettingStarted.md, Documentation/Boundary/ConfiguringBoundaryVisualization.md, Documentation/CameraSystem/CameraSystemOverview.md, Documentation/CameraSystem/CreateSettingsProvider.md, Documentation/CameraSystem/UnityArCameraSettings.md, Documentation/CameraSystem/WindowsMixedRealityCameraSettings.md, Documentation/Contributing/BreakingChanges.md
Our documentation guidelines recommend [using sentence case for headlines](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DocumentationGuide.html#capitalization), something our docs currently do inconsistently. This is phase 1 of a few (I broke them up so it isn't 100+ files all at once) to fix up our headers.
NOTE: These PRs are only intended to update headers. Some non-header casing changes may have made their way in, but I'm trying to split these changes into more reviewable chunks.
=> Update casing in docs headers (phase 1)

Documentation/Input/HandTracking.md, Documentation/Input/InputActions.md, Documentation/Input/InputProviders.md, Documentation/Input/InputState.md, Documentation/Input/Overview.md, Documentation/Input/Pointers.md, Documentation/Input/Speech.md, Documentation/InputSimulation/InputAnimationFileFormat.md, Documentation/InputSimulation/InputAnimationRecording.md, Documentation/InputSimulation/InputSimulationService.md, Documentation/MRTK_PackageContents.md, Documentation/MixedRealityConfigurationGuide.md, Documentation/Packaging/MRTK_Modularization.md, Documentation/Packaging/MRTK_Packages.md, Documentation/Performance/PerfGettingStarted.md, Documentation/Profiles/Profiles.md, Documentation/README_BoundingBox.md, Documentation/README_Button.md, Documentation/README_ExampleHub.md, Documentation/README_HandJointChaser.md, Documentation/README_Interactable.md, Documentation/README_LostTrackingService.md, Documentation/README_MRTKStandardShader.md
Our documentation guidelines recommend [using sentence case for headlines](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DocumentationGuide.html#capitalization), something our docs currently do inconsistently. This is phase 3 of #6893 and #6898 (I broke them up so it isn't 100+ files all at once) to fix up our headers.
NOTE: These PRs are only intended to update headers. Some non-header casing changes may have made their way in, but I'm trying to split these changes into more reviewable chunks.
=> Header capitalization phase 3

Documentation/README_NearMenu.md, Documentation/README_ObjectCollection.md, Documentation/README_Slate.md, Documentation/README_Sliders.md, Documentation/README_Solver.md, Documentation/README_TextPrefab.md, Documentation/ReleaseNotes.md, Documentation/Rendering/MaterialInstance.md, Documentation/SceneSystem/SceneSystemContentLoading.md, Documentation/SceneSystem/SceneSystemLightingScenes.md, Documentation/SceneSystem/SceneSystemLoadProgress.md, Documentation/SceneSystem/SceneSystemSceneTypes.md, Documentation/SpatialAwareness/ConfiguringSpatialAwarenessMeshObserver.md, Documentation/SpatialAwareness/CreateDataProvider.md, Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.md, Documentation/SpatialAwareness/SpatialObjectMeshObserver.md, Documentation/SpatialAwareness/UsageGuide.md, Documentation/TeleportSystem/Overview.md, Documentation/Tools/ControllerMappingTool.md, Documentation/Tools/DependencyWindow.md, Documentation/Tools/ExtensionServiceCreationWizard.md, Documentation/Tools/HolographicRemoting.md, Documentation/Tools/OptimizeWindow.md, Documentation/Tools/ScreenshotUtility.md, Documentation/VisualThemes.md, README.md
Our documentation guidelines recommend [using sentence case for headlines](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/DocumentationGuide.html#capitalization), something our docs currently do inconsistently. This is phase 4 of #6893, #6898, and #6899 (I broke them up so it isn't 100+ files all at once) to fix up our headers.
NOTE: These PRs are only intended to update headers. Some non-header casing changes may have made their way in, but I'm trying to split these changes into more reviewable chunks.
=> Header capitalization phase 4

Assets/MixedRealityToolkit.SDK/Experimental/Features/Input/Handlers/ObjectManipulator.cs, Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/Migration/ObjectManipulatorMigrationHandler.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/ConstraintManager.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FaceUserConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FaceUserConstraint.cs.meta, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FixedRotationToUserConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FixedRotationToUserConstraint.cs.meta, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FixedRotationToWorldConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/FixedRotationToWorldConstraint.cs.meta, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/Manipulation/ManipulationMoveLogic.cs, Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/MinMaxScaleConstraint.cs, Assets/MixedRealityToolkit.SDK/Inspectors/Experimental/UX/ObjectManipulator/ObjectManipulatorInspector.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ConstraintTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/ObjectManipulatorTests.cs, Assets/MixedRealityToolkit/Definitions/Utilities/ManipulationHandFlags.cs, Assets/MixedRealityToolkit/Definitions/Utilities/ManipulationHandFlags.cs.meta, Assets/MixedRealityToolkit/Definitions/Utilities/ManipulationProximityFlags.cs, Assets/MixedRealityToolkit/Definitions/Utilities/ManipulationProximityFlags.cs.meta
In #6321 the way that manipulation constraint options work was changed, so that they are individual components that the user can add to a manipulation object, tidying the `ObjectManipulator` inspector options and decoupling the manipulation logic from the constraint logic. 
However, the options in the `RotateInOneHandType` enum, also constrain rotation in some way. It feels strange to me that we have a unique set of constraints only for one handed rotation, when these constraints could easily be applied to two hand rotation as well. 
I believe that this will reduce confusion and clutter with the `ObjectManipulator` inspector options. I also think that it will bring potentially useful functionality to two hand manipulation that before only existed for one handed. It will also further …
=> Move RotateInOneHand options to constraint components

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
1. Adds `ARM64` as a valid build architecture when building in Unity 2019.
1. Fixes an issue with multiple VS versions installed side-by-side.
1. Now, it keys `vswhere` off the setting in the Unity build window, which is already the setting the VS solution in the previous step would have been built with.
- Fixes: #4349, #6532
=> Add ARM64 support to build window for Unity 2019 and support multiple VS versions side-by-side

Assets/MixedRealityToolkit.SDK/Inspectors/UX/ManipulationHandler/ManipulationHandlerInspector.cs
Removing migration warning and button for `ManipulationHandler` as we don't yet want to advise people to make the switch.
=> Remove migration warning and button

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/BoundingBoxTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/BoundsControlTests.cs
- added possibility to set target of bounding box / bounds control in code
- added tests to verify target setting works - test will create cube without bounding box / bounds control and create another empty gameobject unrelated to the cube that has bounding box / bounds control attached - target of bounding box / bounds control is set to cube gameobject and correct behavior is verified through near interaction scaling
- fixed bug where rigroot was attached to bounds control gameobject instead of target gameobject 
- Fixes: #5992
=> added possibility to set target of bounds control / bounding box in code

Assets/MixedRealityToolkit/Interfaces/InputSystem/IMixedRealityMouseDeviceManager.cs
This file is missing its namespace. Adds `namespace Microsoft.MixedReality.Toolkit.Input`.
=> Add missing namespace to IMixedRealityMouseDeviceManager

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs
GridObjectCollection was throwing errors on device because assets were being loaded without the asset version in runtime but saved with the asset version. See comment from @gilbdev  in #6938. Thank you for the help!
- Fixes: #6938
=> Remove if UNITY_EDITOR check

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SlateTests.cs
Slate Zooming in/out not working properly on Hololens 1. Issue can be replicated on the Editor. 
Before:
After:
- Touching point logic was modified on HandInteractionPanZoom.cs to account for both Right Hand and Left Hand controllers having same pointer/slate touch position on GGV.
- Fixes: #6371  .
>
>
> As a reviewer, it is possible to check …
=> Fix slate zooming for GGV Pointer

Documentation/ReleaseNotes.md, Documentation/Updating.md
1. Minor wording changes in the description of how to upgrade from one version of MRTK to another.  These are spread across the various MRTK versions.
2. Add a note in the Upgrading documentation, hinting to the reader that these instructions are in the release notes.
We may actually want to refactor even more, but this quick change is probably easier to get into the next MRTK release.
- Fixes: #6883 
It's not necessary to execute/test anything, since this is a documentation change.  Just look through the diffs.
=> Minor doc clarifications about upgrading to a new version of MRTK

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Adds missing check to validate unity ui touchables are in valid layer mask
- Fixes: #6967 
>
>
=> Fix poke pointer layer mask

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
As was pointed out by @darax in #6809, the Windows Mixed Reality spatial observer was not properly handling cases where there was an outstandingMeshObject at the time Suspend is called.
This change reclaims and nulls the outstandingMeshObject in Suspend().
Tested on a HoloLens using the SpatialAwareness demo scene and was successfully able to resume from over 20 suspends.
- Fixes: #6809, fixes #6425,
=> Reclaim outstandingMeshObject on suspend

Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/BaseSpatialAwarenessObject.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessPlanarObject.cs, Assets/MixedRealityToolkit/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessObject.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialMeshObserver.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialMeshObserver.cs.meta, Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs
Part of XR SDK implementation, to reduce duplicated code. Also a bit of an extension of #6919 
Moves some duplicated code down into `BaseSpatialObserver`, and also creates a new `BaseSpatialMeshObserver` to contain some duplicated mesh observer code.
Observer lifecycle can now be automatically handled by overriding `BaseSpatialObserver`'s `CreateObserver` and `CleanupObserver` methods.
Filled in a few missing docs along the way as well.
In-app behavior should be unchanged, other than `SpatialObjectMeshObserver`, where `CleanupObserver` no longer calls `ClearObservations`, to match the WMR implementation and separate the two cleanup methods.
The one outstanding thing I'll need to better address for the XR SDK implementation is `TrianglesPerCubicMeter`. Our native WMR implementation uses …
=> SpatialMeshObserver refactor

Assets/MixedRealityToolkit.SDK/Profiles/HoloLens2/DefaultHoloLens2ConfigurationProfile.asset, Assets/MixedRealityToolkit.Tests/PlayModeTests/SpatialObserverTests.cs, Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityEditorSettings.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialMeshObserver.cs, Assets/MixedRealityToolkit/Utilities/Editor/InputMappingAxisUtility.cs, Assets/MixedRealityToolkit/Utilities/Editor/MixedRealityOptimizeUtils.cs
1. Moves `BaseSpatialMeshObserver`'s `ReadProfile()` from constructor to `Initialize` to better support profile resetting.
1. Update `MixedRealityOptimizeUtils` typo and `#ifdef` to support versions past 2019.
1. Update `InputMappingAxisUtility` to use a static method in `MixedRealityOptimizeUtils` for loading the input settings asset.
=> BaseSpatialMeshObserver and MixedRealityOptimizeUtils updates for XR SDK

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/BoxDisplayConfiguration.cs
moved menu entry for box display of bounds control into experimental section - Must've forgotten to save that file when pushing my changes yesterday
=> added missing experimental entry for box display of bounds control

Assets/MixedRealityToolkit.Tools/DependencyWindow/DependencyWindow.cs
Adds .playable extension to assets to consider also fixed issue where folder-like assets were retrieved as dependencies, resulting in "empty" results being showed (actual values were like Resources/unity_builtin) etc.
- Fixes: #6980 
>
>
=> Update dependency graph

Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs
The current implementation for updating the controller mappings expects the currently active and newly aquired maps to be of the exact same size.
This PR handles size differences and tries to keep mapped actions active. Besides all the info a mapping can have, it ignores the ID because it's pretty much the index in the array, in order, which means inserting mappings breaks action transfer.
- Fixes: #6991
=> Added code to handle different mapping sizes

Assets/MixedRealityToolkit.Staging/UnityAR/UnityARCameraSettings.cs, Assets/MixedRealityToolkit.Staging/UnityAR/UnityARCameraSettingsProfile.cs, Assets/MixedRealityToolkit.Staging/UnityAR/Utilities/ArEnumConversion.cs
In Unity 2019, some existing types no longer exist in-engine and are instead distributed via the package manager. The `UnityEngine.SpatialTracking` namespace is one of them.
Also, this simplifies `#if (UNITY_IOS || UNITY_ANDROID) && ARFOUNDATION_PRESENT` checks down to just `#if ARFOUNDATION_PRESENT`, since we only set that define for specific platforms to begin with.
=> Fix UnityAR namespaces in Unity 2019.3

Assets/MixedRealityToolkit.Extensions/HandPhysicsService/HandPhysicsService.cs, Assets/MixedRealityToolkit.Extensions/HandPhysicsService/HandPhysicsServiceProfile.cs.meta
Fixes #6999
The hand physics extension service was not fully utilizing the extension service attribute. Notably, it was missing:
- Friendly name
- Default profile
- Profile folder root
Additionally, #6988 / #6133 introduced a new property to the attribute that informs the inspector as to whether or not the service requires a profile to properly function. This has been set to true for hand physics.
Verified:
- When selecting the service type, the profile and friendly name values are properly set
- When manually setting the profile to null, the appropriate warning message appears in the inspector
=> fully apply extension service attribute to hand physics service

Assets/MixedRealityToolkit/Inspectors/MixedRealityStandardShaderGUI.cs, Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader
The code attached to this pull request enhance the MixedRealityStandard shader and its custom GUI. 
It is simply adding to the 'Round Corners' feature the ability to manage each corner separately.
-  The editor tooltip over Corners Radius is not showing
- I would rather constrain anyhow the user to use values between 0 and 0.5 directly in the editor (One slider by corner? Custom editor?) instead of clamping the vectors values within the shader code. 
You can easily review the feature by tweaking the material values in the MaterialGallery scene.
>
>
> git checkout …
=> MixedRealityStandard shader - Manage round corners independently

Assets/MixedRealityToolkit.SDK/Inspectors/Experimental/UX/ObjectManipulator/ObjectManipulatorInspector.cs
Highlighting constraints in the ObjectManipulatorInspector was causing errors to be logged and the highlighter could end up highlighting random windows. I found this fix online.
=> Fixed errors when highlighting constraints

Documentation/Contributing/CodingGuidelines.md
Our PowerShell code is currently using some random style (which is somewhat consistent within the files themselves, but are not necessarily consistent across files). This change updates our coding guidelines to recommend/reference the PoshCode style.
I've looked at some other resources both internal to Microsoft and externally visible as well (i.e. https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-6, and https://docs.microsoft.com/en-us/contribute/powershell/powershell-style-code) however none were as extensive as PoshCode.
=> Updating the coding guidelines to recommend PoshStyle as the PowerShell coding guidelines

scripts/packaging/unitypackage.ps1
#7017 moved the UnityAR provider into Providers and removed the staging folder. It neglected, however, to update the packaging portion of the CI pipeline.
This change addresses that issue.
=> Remove staging package from CI's packaging steps

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/LinePointer.cs
#6863 and #6822 when merged together left an issue open with the managed MixedRealityLineRenderer component.
The pointer cache change made it such that pointers are re-used.
The line refactor change eliminated the redundant MRLineRenderer classes.
The LinePointer class had a bug in it whereby it disabled MRLineRenderers OnDisable() but did not re-enable on OnEnable(). Before these PRs, this was not evident to the user because there were redundant MRLineRenderers and not all were registered with the LinePointer class.
**Changes:**
This fix ensures correct lifecycle management by the LinePointer class
**BEFORE**
**AFTER**
- Fixes: #7005  …
=> Line pointer line fix

Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, pipelines/README.md, pipelines/ci-daily.yml, pipelines/ci-packaging-dontpublish.yml, pipelines/ci-packaging-internal.yml, pipelines/ci-release.yml, pipelines/pr.yaml
This updates our pipelines to run on the installed Unity 2018.4 versions instead of 2018.3.
Internal machines have Unity 2018.4.12 and external machines have Unity 2018.4.6.
I also added a README to remind myself which pipelines were used where.
=> Update pipelines to run Unity 2018.4 instead of Unity 2018.3

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs
Fixes a potential null ref, in cases where the utilities are being asked for platform data but we don't have a valid pointer. Specifically, this was being hit in the case where the root spatial coordinate system was being asked for, but we didn't have a headset attached and weren't running in the context of mixed reality, so none existed.
@julenka this should fix the in-editor issue you were seeing.
=> Fix potential nullref in WindowsMixedRealityUtilities

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs, Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
Fixes a MissingMethodException when running precompiled in the editor for WMR by patching in a correctly compiled WSA assembly instead of one compiled only for the editor.
```
MissingMethodException: Microsoft.MixedReality.Toolkit.WindowsMixedReality.IWindowsMixedRealityUtilitiesProvider Microsoft.MixedReality.Toolkit.WindowsMixedReality.WindowsMixedRealityUtilities.get_UtilitiesProvider()
Microsoft.MixedReality.Toolkit.BaseDataProviderAccessCoreSystem.Enable () (at <15332009bc6d452484cf8864bce900e4>:0)
Microsoft.MixedReality.Toolkit.Input.MixedRealityInputSystem.Enable () (at <0a9cec65677742e088c48dc0b5b98b15>:0)
Microsoft.MixedReality.Toolkit.MixedRealityToolkit+<>c.<EnableAllServices>b__62_0 (Microsoft.MixedReality.Toolkit.IMixedRealityService service) (at …
```
=> Patch both the existing WMR DLL and the shared DLL when packaging NuGet

Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/EllipseLineDataProvider.cs, Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/SimpleLineDataProvider.cs, Assets/MixedRealityToolkit/Utilities/Lines/DataProviders/SplineDataProvider.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/BaseMixedRealityLineRenderer.cs, Assets/MixedRealityToolkit/Utilities/Lines/Renderers/MixedRealityLineRenderer.cs
The `MixedRealityLineRenderer` class executes always and thus in edit mode. The control has the capability to fade in the line via a coroutine executed in OnEnable. The problem is the control directly modifies the gradient value and executes in edit mode. So the fade overwrites any defaults or changing of the gradient in edit mode
Also some clean up on related classes with comments etc
- Fixes: # .
>
>
=> Fix Line Renderer editor error

pipelines/templates/tasks/unitypackages.yml
#7038 introduced an issue with the unitypackage phase of CI. The unitypackage step used an explicit Unity version, so this updates it to use the defined variable instead.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=8445&view=logs&j=ae5f814d-d003-5afd-2125-fa0189ea8658&t=4f395fa6-3ac2-5732-7a27-84aace4a750b
=> Use variable instead of explicit Unity version in pipelines

scripts/ci/validatecode.ps1
Removes a false positive when a ProjectSettings .asset file is updated. These files don't need meta files, so the meta file checker doesn't need to run.
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=8449&view=logs&j=c1841906-0df4-5516-e3c5-68840a78c082&t=b0b212c9-e072-56eb-4467-a1e6a0002cf3
=> Filter out the ProjectSettings .asset files, which don't have a meta file

Assets/XR.meta, Assets/XR/Loaders.meta, Assets/XR/Loaders/Windows MR Loader.asset, Assets/XR/Loaders/Windows MR Loader.asset.meta, Assets/XR/Settings.meta, Assets/XR/Settings/Windows MR Package Settings.asset, Assets/XR/Settings/Windows MR Package Settings.asset.meta, Assets/XR/XRGeneralSettings.asset, Assets/XR/XRGeneralSettings.asset.meta, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/XRPackageSettings.asset, ProjectSettings/XRSettings.asset
Adds several new scriptable assets from Unity for XR SDK.
These files are settings files specific to our repo's project, and won't need to be distributed as part of our packages. I'm including them to help with testing and validating the project on XR SDK.
I've verified that these files don't prevent building or running on previous Unity versions, even when their scripts don't exist: 
and there's nothing in the console. PR validation and CI can double check :)
=> Add XR SDK settings files to repo

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBar.cs
Expose `[SerializeField] private` fields as properties and update class to use property references instead of fields.
This change allows for the runtime creation and modification of the AppBar script.
=> Expose [SerializeField] private fields as properties

Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
No longer limited to search depth of 3, since it's using `SearchOption.AllDirectories`, modified in a45ece4f8a19d88411a095d286668d34b3c2b71b
=> Remove outdated remark

pipelines/ci-packaging-internal.yml, pipelines/templates/ci-common.yml
So in one of the CI builds, we're seeing a failure on a nuget restore step due to some corrupted version that is being passed in the .csprojs.
Looking at the various machines/failures, I'm currently pretty stumped because:
1) This started failing a long time ago, and even when I re-queue a commit from way before then, the build is still failing at the same step. However, all of our pipelines are configured in YAML (which means running an older build *should* take the corresponding older pipeline configuration as well)
2) There is a similar pipeline that is succeeding, that is running on the same agent pool and same build machine (and same Unity version and other parameters) but is not failing. What the effffff.
I'm trying this change (not actually submitting) to try to tease apart to find …
=> Investigation into some failing CI steps

Assets/MixedRealityToolkit/Utilities/Editor/EditorProjectUtilities.cs
If 2018.3 is allowed (as the message implies), conditional should be UNITY_2018_3_OR_NEWER, not UNITY_2018_4_OR_NEWER
=> Fix Unity version check and message

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/TextMeshProMaterial.mat, Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/TextMeshProMaterial.mat.meta, Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/ClippingExamples.unity, Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityShaderUtils.cginc, Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityShaderUtils.cginc.meta, Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader, Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityTextMeshPro.shader, Assets/MixedRealityToolkit/StandardAssets/Shaders/Text3DShader.shader, Assets/MixedRealityToolkit/Utilities/StandardShader/ClippingPrimitive.cs, Documentation/README_MRTKStandardShader.md
The MRTK Standard and TextMeshPro shaders both supported clipping but the 3DTextShader did not. This change enables that capability and refactors common code to a new MRTKShaderUtils.cginc file to be shared across MRTK shaders. 
This feature will be useful for the scrolling list with TextMesh components and other clipping scenarios on labels.
- Fixes: #7025 
>
>
=> Add clipping primitives to 3DTextShader

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs
Fixed gazetarget not properly set in focusprovider:
Previously the gaze target only took physics raycast into account which will only cover 3d meshes.
After this change we will also take graphics raycast into account which includes Unity UI.
There's a test to verify that FocusProvider sets the gaze target correctly to a Unity UI element if it is in focus..
- Fixes: #6343 
FocusProvider test that checked that 3d objects as well as unity ui gameobjects can be focused / set as gazetargets.
=> Added support for Unity UI when setting a gaze target in FocusProvider

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBar.cs
The summaries were inline with the fields instead of the properties, causing them to be missed by docs generation and intellisense.
=> Move AppBar summaries to be inline with the properties instead of the fields

Assets/MixedRealityToolkit.Extensions/HandPhysicsService/HandPhysicsServiceProfile.cs, Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingServiceProfile.cs, Assets/MixedRealityToolkit.Extensions/SceneTransitionService/SceneTransitionServiceProfile.cs, Assets/MixedRealityToolkit.Providers/UnityAR/UnityARCameraSettingsProfile.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityCameraSettingsProfile.cs, Documentation/Contributing/CodingGuidelines.md
Started by noticing one was in its own path of `MixedRealityToolkit` vs `Mixed Reality Toolkit`, then started partitioning out some paths like our folder structure, to help structure the menus a bit more:
=> Update some asset menu paths

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
MRTK Visual Profiler is enabled by default. A lot of the MRC(Mixed Reality Capture) videos show the profiler, even for the showcase situations. Adding information text 'Say "Toggle Profiler' to help people understand that it can be hidden with the voice command.
- Fixes: #7044
- Added voice command information label
- Added "MRTK Visual Profiler" text. (for the viewers of videos who are not familiar with MRTK)
- Small padding adjustments.
=> Added voice command information text to Visual Profiler

Documentation/Contributing/ExperimentalFeatures.md, Documentation/toc.yml
carried over changes from @julenka s PR #7056 
changed experimental features folder name
also added more information / highlighted menu entry for experimental features in guideline
=> Guidance for adding documentation to experimental features

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/MSBuildTools.cs
One of the CI builds (that builds both NuGet and Standalone/UWP/etc) is currently on the floor due to in invalid version that's being piped back from Unity's wsaUWPSDK:
Error MSB4086: A numeric comparison was attempted on "$(TargetPlatformVersion)" that evaluates to "winv6.3" instead of a number, in condition "'$(TargetPlatformVersion)' >= '10.0.11000.0'".
winv6.3 isn't actually an interesting (or valid) version number.
Here's where things get a bit weird -
This issue actually started happening quite a while back (i.e. mid november). It's not actually an issue in the pipeline/code itself, because when we re-queue a really old commit, the same issue occurs
It's also not an issue with some specific build machines or different pool configurations (i.e. there successful CIs run on the same …
=> Unbork the CI build

Assets/MixedRealityToolkit.Providers/UnityAR/UnityARCameraSettings.cs, Assets/MixedRealityToolkit.Providers/XRSDK/Editor/ConfigurationChecker/XRSDKConfigurationChecker.cs, Assets/MixedRealityToolkit.Providers/XRSDK/GenericXRSDKCameraSettings.cs, Assets/MixedRealityToolkit.Providers/XRSDK/Profiles/DefaultXRSDKToolkitConfigurationProfile.asset
1. Add `TrackedPoseDriver` for XR SDK at runtime
1. Fix camera settings that didn't have a profile set
1. Update `UnityARCameraSettings` to read from its cached data instead of the profile again
=> Add TrackedPoseDriver for XR SDK at runtime

Documentation/MixedRealityConfigurationGuide.md
It's been a somewhat common ask about how to swap the MRTK profile at runtime BEFORE the MRTK has initialized. The most common usage of this is to say, build a single scene/app that can be deployed to a few different targets, and load a different profile based on the device (i.e. maybe I want to have certain extension systems on VR active, but not have them loaded on HoloLens).
People have worked around this by having multiple scenes (and dynamically loading scenes based on the platform) or by building different binaries for each device (but this kinda sucks to have to do).
This provides guidance (or actually, just the code you have to copy paste into Unity and instructions on how to do so) to unblock this scenario.
- Fixes: #7024
=> Add some documentation on how to do pre-MRTK initialization runtime swapping to allow for platform-specific configuration to be loaded.

Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
The extension service creator wizard today looks for the MixedRealityToolkit.Extensions folder in order to place its newly generated content. This fails when the default extensions package isn't installed, because the folder doesn't exist. Note that it's more than just the folder that needs to exist - each of the MRTK folders also require a 'sentinel' file to be placed in them, so that the MixedRealityToolkitFiles.cs code can find them even when they are placed in arbitrary folders/locations within the project (to support placing the MRTK at arbitrary locations). As a result, the code that tries to re-create the extensions folder doesn't work (i.e. it doesn't do the sentinel file creation).
In reality, because these are generated files, they should really go into the …
=> Update the extension service creator to work when the extension package isn't installed

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/Extensions/WindowsExtensions.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
1. Adds the DotNetWinRT namespace when valid
2. Removes an unused field that was throwing a warning
3. Fixes an incorrect null propagation on a Unity object
- Fixes: #7108, part of #7003
=> Allow Windows extensions to properly use DotNetWinRT (and some compiler warning fixes)

Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedGestureHand.cs, Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Fixes some warnings:
1. Updates the capitalization convention of a private property to be PascalCase.
1. Fixes several incorrect cases of Unity object null propagation.
1. Fixes an unused field warning by updating the code to actually use it.
=> Fix some Unity object null propagation and other warnings

Assets/MixedRealityToolkit/MixedReality.Toolkit.targets
Adds conditions to MixedReality.Toolkit.targets to enable MSBuildForUnity support.
Worked with @andreiborodin.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7121
>
>
=> Added conditions to MixedReality.Toolkit.targets for NuGet packages

Documentation/MRTKNuGetPackage.md, Documentation/MRTK_PackageContents.md, Documentation/ReleaseNotes.md, Documentation/toc.yml
The documentation page for nuget packaging with MRTK is not in the TOC and thus makes it more difficult to find.
[MRTK Nuget packages](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/MRTKNuGetPackage.html)
This change also cleans up some polish for the MRTK nuget doc page. Furthermore, add some see also links to related articles in the "Getting started with MRTK" section.
- Fixes: #7129 
>
>
=> Add nuget docs to TOC and polish

Assets/MixedRealityToolkit/Utilities/Editor/FileUtilities.cs
This change fixes a \ vs / path separator issue that was reported by @julenka when using MRTK on a Mac as part of #7109 
This is a companion change to #7122
=> Mac fix: Remove hardcoded '\' in GetPackageCache

Assets/MixedRealityToolkit.Providers/OpenVR/GenericOpenVRController.cs
The material accessed might not be assigned in the inspector. Furthermore, if the shader of the assignee is null, internally it will just be set to the MRKT Standard Shader so it's save to just check and not assign any if no material is found.
- Fixes: #7102
=> NullCheck before accessing shader

Assets/MixedRealityToolkit/Utilities/CameraFOVChecker.cs
Fix CI build break (WSA player) by explicitly defining the tuple.
=> Fix WSA player build break

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityEditorSettings.cs
This change delays initialization of the MREditorSettings class till after the editor has been fully initialized. Before this change, the MREditorSettings class would start up once compiled (and thus it's static constructor executes. With this change, we wait till `EditorApplication.update` starts firing but only subscribe to this event for one event execution because we only need to init. 
Need to do further testing concerning #7109 with this PR
- Fixes: #7109 
>
>
=> Delay initialization of project configurator window

Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Removes another hardcoded "\\" in file path when creating the MRTK autogenerated "Generated" folder used in MRTK's project preferences.
- Fixes: #7109
Needs to be tested on Windows, fix verified only on Mac.
I found a list of other potential hard coded strings we may want to fix in a follow-up:
```
$ find . -name *.cs -exec grep --with-filename -F '"\\"' {} \;
./MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Utils/Utils.cs:                    goName = g.parent.name + "\\" + goName;
./MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/BasicInputLogger.cs:                    string fullPath = logRootFolder.Path + "\\" + LogDirectory;
./MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/BasicInputLogger.cs:                    string …
```
=> Mac fix: remove another hardcoded '\' when creating mrtk auth-generated

Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs
When trying to import GLTF or GLB files with upper case File ending f.e. "Video camera.GLB" the GlbAssetImporter Script get's triggerd but inside GltfEditorImporter.OnImportGltfAsset the file get's ignored because the file ending is not lower case.
=> [GLTF-Import] Files get ignored, when File ending is not lower case

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/BaseWindowsMixedRealityCameraSettings.cs
Adds a null check before trying to access the profile. It's not required to add a profile (for example, these features don't exist on HL1).
- Fixes: #7095
=> Add null check if no (or incorrect type) camera settings profile is set

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs.meta, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityArticulatedHand.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Initial hand / controller rework, by separating out some of the WMR articulated hand definitions from any specific Unity API set.
This is a first step toward separating hand / controller definitions from the APIs that supply their data, which will also help unblock bringing new features like https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6973 to HL2 and beyond.
- Part of #7003,
=> Refactor out shared WMR articulated hand definition

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs
PressableButton does not trigger the ButtonPressed event when OnTouchCompleted is triggered by pointer getting closer to another NearInteractionTouchable
When a second pressable button is slightly overlapping with the back of a pressable button, ButtonPressed event trigger should be guaranteed if the following happens:
- Poke Pointer moves from the front of Button 1
- Poke Pointer touches Button 1 triggering OnTouchStarted
- Second button becomes the closest touchable to pointer in the same frame as pointer passes first button pressed plane or after
- ButtonPressed event is triggered
Checking button state whenever OnTouchComplete is called to avoid missing a press when a second NearInteractionTouchable is closer to the pointer than the button
- Fixes: #6968
> This optional section is a …
=> Overlapping pressable buttons fix

Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/HandConstraint.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs, Documentation/README_Solver.md
Addition of useHybridHandRotation for HandConstraintPalmUp.
- This adds an additional check in HandConstraintPalmUp's hand validation function, which changes the Rotation behavior if useHybridHandRotation is enabled.
Added better behavior for LookAtTrackedObject.
- This introduces a branch in CalculateProjectedSafeZoneRay of the HandConstraint base class, which computes the SafeZone Direction ray according to the rotation of the SolverHandler.TargetTransform, rather than exclusively from the head gaze.
The end result can be seen [here](https://twitter.com/prvncher/status/1211795961510584327)
With useHybridHandRotation enabled:
The menu matches your hand rotation until your palm and head gaze reach a threshold angle, which activates a different rotation behavior that makes the menu look at …
=> Improvements to Hand Constraint juicyness

Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableToggleCollectionInspector.cs
InteractableToggleCollectionInspector does not render public property OnSelectionEvents in a InteractableToggleCollection. Just adds serializedproperty field to inspector class
**BEFORE**
**AFTER**
- Fixes: #7167 
>
>
=> Fix toggle colleciton inspector

Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/BoundsControl/Scenes/BoundsControlRuntimeExample.unity, Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/BoundsControl/Scripts/BoundsControlRuntimeExample.cs, Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/Visuals/Links.cs
Runtime example demonstrates various runtime configurations / features of bounds control. This was carried over from BoundingBox but wasn't fully functional.
Change includes:
- Patching up scene to use the BoundsControl scripts
- Replacing all occurrences of BoundingBox with BoundsControl
- Fixed a bug when switching from a flattened state into a non flattened one
- Removed unnecessary caching of renderer components in BoundsControl links which introduces another possible source of error rather than bringing us a performance win (the renderers are just used for changing the visibility flag or when changing the flatten mode)
This change has to go in after #7096 has been merged
- Fixes: #6926
=> Fixed bounds control runtime example

Assets/MixedRealityToolkit.Tests/EditModeTests/BoundarySystem.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/BoundarySystem/InscribedRectangleTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/BoundarySystem/InscribedRectangleTests.cs.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/Microsoft.MixedReality.Toolkit.Tests.EditModeTests.asmdef, Assets/MixedRealityToolkit/Definitions/BoundarySystem/InscribedRectangle.cs
There's been a latent bug in the InscribedRectangle algorithm since it was checked in a few years ago (https://github.com/microsoft/MixedRealityToolkit-Unity/commit/e40334655740a7adfd6fae0389cef9b3e854ca44) - in particular, the code that figures out the candidate search space (i.e. the (minx, miny), (maxx, maxy) bounds). With the current code, generally things will work out because the set of edges passed to the algorithm will generally be okay and won't degenerate.
However, there are cases (where each pairwise point has at least one y coordinate that is super small) where the degenerancy ends up being really bad. In that case the incorrect usage of Math.min instead of Math.max causes us to flatten the search space substantially, in some cases dropping to the wrong location entirely.
The …
=> Fixes an issue on the InscribedRectangle algorithm to have a proper initial search space for candidates.

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseEventSystemTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseEventSystemTests.cs.meta, Assets/MixedRealityToolkit/Services/BaseEventSystem.cs
This change addresses a couple of issues, so let's talk about both of them:
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7126
This one actually is 99.999% addressed by this change: https://github.com/microsoft/MixedRealityToolkit-Unity/commit/9314eea6516450f86c20543460de80026786f62f. There still remains the slim possibility of bugs from ExecuteEvents.Execute slipping through (i.e. not catching an exceptions), but in reality the change here to add a try/catch around that shouldn't really be doing much. Nevertheless it's still a safeguard in case there's an issue there (so that our internal state doesn't get out of sync)
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6975
This one is more interesting, and happens because of the mismatch between the …
=> Update the base event system to handle per-event system cleanup properly

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs, Assets/MixedRealityToolkit/Definitions/SpatialAwareness/MixedRealitySpatialAwarenessMeshObserverProfile.cs, Assets/MixedRealityToolkit/Extensions/LayerExtensions.cs, Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs
This change fixes use of the `FocusProvider.GetPrioritizedHitResult` method. The layer extension FindLayerListIndex can return -1 which in `GetPrioritizedHitResult` will be selected as it's always the MIN value.
This change rewrites the comparison method to handle the -1 cases and adds a new test: TestPrioritizedLayerMask
Also add a const int for the default spatial awareness layer to track across project
- Fixes: #6481 
>
=> Fix prioritized layer mask usage in FocusProvider.GetPrioritizedHitResult

Documentation/Input/HowToAddNearInteractivity.md
The docs today mention how to add touch interaction to 3D objects, but the '3d objects' one has a primary focus on objects that have a BoxCollider (or generally are only supposed to be touchable on one plane). While there are docs about how to do objects with arbitrary colliders, it's not super clear until you hit an issue (see the related issue) and read on to the "NOTE"
i.e. Someone who is adding this to an object with a SphereCollider, for example, will wonder why those buttons don't exist.
- Fixes: #7177
=> Update the touch interactivity docs to be clearer about the type of NearInteractionTouch script needed

Assets/MixedRealityToolkit.Providers/XRSDK/GenericXRSDKCameraSettings.cs
This `#define` was added in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7083 but wasn't properly scoped.
- Fixes: #7174
=> Gate TrackedPoseDriver behind package existing

.gitignore
If you clone the MRTK repo and follow the default steps (i.e. configurator -> accept default changes) you'll start getting msb4u csproj and meta files being built and showing up in your status/workspace. This heavily clutters things and makes command line git tricky to use (and other forms of git as well).
=> Update the .gitignore to ignore the MSBuildForUnity generated csproj and sln files.

scripts/packaging/unitypackage.ps1
This change updates the MRTK CI unitypackage creation step to remove ar foundation and xr management related packages from the checked in manifest prior to package creation.
This was leading to #7192 due to the fact that, when creating unitypackage files, the project is opened into Unity and any methods decorated to run on project load (specifically the unityar configuration checker) are executed. Since MRTK has a checked in manifest containing arfoundation, this caused the unityar asmdf to incorrectly be modified during packaging.
Fixes: #7192
Special thanks to @keveleigh for his assistance (read: donation) with the powershell commands
=> Fix foundation unitypackage packaging: do not presume ar or xr plugins

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
The project configurator unfortunately did not take into account the current build target platform. Thus, some setting checks were not valid/necessary. Example: If targeting Standalone, we would still check if the recommended UWP capabilities were set. 
This change adds a buildtarget filter to the configuration getters.
Furthermore, if the project has been appropriately configured as recommended, the Configuration window now just displays a confirmation message instead of the "Hey we want to change stuff...but there is nothing to change"
**Users should no longer be able to see this**
- Fixes: #7197 
> …
=> Harden MRTK Project Configurator

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/EventSystemTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/EventSystemTests.cs.meta, Assets/MixedRealityToolkit/EventDatum/GenericBaseEventData.cs
Accessing the selectedObject on any field within any of the MRTK's event data (for example, DiagnosticSystemEventData or MixedRealityPointerEventData) will throw a NullReferenceException, because the majority (I think all) of these eventData objects get instantiated with a null EventSystem in their constructor (i.e. this is due to another startup mismatch where EventSystem.current is null when the input system is starting up).
As it turns out, passing a valid EventSystem doesn't seem to matter for the usage of ExecuteEvents in the rest of our stuff, so the simplest/safest option here is just to make sure that we don't end up NullRef-ing on the access of a specific field within our code. 
It would have also been possible to change up our startup mechanics to wait for the camera's event …
=> Update GenericBaseEventData to not throw when selectedObject is invoked.

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Cherry-picks #7199 and additionally gates the MSBuildForUnity option behind the UWP build target.
- Helps with #6947 by disabling MSBuild for Unity import unless the UWP build target is selected.
=> Cherrypick #7199 and mark MSBuildForUnity as WSA-only

.gitignore
Update the .gitignore to ignore the MSBuildForUnity generated csproj and sln files.
=> Cherry-pick pull request #7186 from wiwei/ignoremsb4ugenerated

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/XRSDKWindowsMixedRealityUtilitiesProvider.cs
Instead of assuming only one SpatialCoordinateSystem will ever exist, this change checks the `IntPtr`s to detect when the underlying root coordinate system has changed.
This helps scenarios like recentering, when a dev / user wants to realign the experience in a specific alignment. Can also help in scenarios when tracking is list and the original coordinate system is never regained. Might help in the scenario when a new scene is loaded, but I haven't tested this yet.
- Part of #7003, maybe helps with https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6974
=> Update cached coordinate system whenever the underlying IntPtr changes

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/HandJointServiceInspector.cs
These were the only two `EditorGUILayout.Foldout`s that didn't have `toggleOnLabelClick` set to true. For user convenience, I've updated them.
=> Update foldouts that didn't have toggleOnLabelClick set to true

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs, Assets/MixedRealityToolkit/Extensions/UnityObjectExtensions.cs
When in edit mode in editor, DestroyImmediate needs to be used except it cannot be called
"during physics trigger/contact, animation event callbacks or OnValidate. "
The MRTK system may be "reset" in the MRTK.OnValidate() if switching scenes or selecting a new profile in which case the old services and components will be destroyed. This triggers an error message in the editor console.
This change delays the DestroyImmediate call to avoid the scenario described above.
- Fixes: #6584 
>
>
=> Fix destroyimmediate for OnValidate() code path

Assets/MixedRealityToolkit.SDK/Experimental/FollowSolver/Follow.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
Discovered a possible issue with the follow solver. Although it was hard to repro, it was possible to get the follow object stuck in the inverted leashing frustum. This fix uses the angle from `toTarget` to the reference yz plane for horizontal leashing, but uses the angle from `currentRefForward` and `toTarget` projected onto the reference yz plane for vertical leashing. This ensures that positions in the inverted leashing frustum are not valid leasing positions.
=> Fix possible follow object stuck behind player

Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
MRTK 2.2.0 shipped with a dependency on MSBuild for Unity 0.8.3. With MRTK 2.3.0, MSB4U needs to be upgraded to 0.9.1.
This change compares the current version and will prompt the customer to enable msbuild if it needs to be updated,
=> Configure dialog will prompt if the version of MSBuild for Unity should be upgraded

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/PokePointer.cs
There are still a few places that have unnecessary OnValidate calls, which per https://github.com/microsoft/MixedRealityToolkit-Unity/pull/4899 and https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4202#issuecomment-495765433 isn't being used correctly in all cases.
In this case, the adjustment to some of the properties (i.e. touchableDistance/sceneQueryBufferSize) actually is fine, it's just the asserts that actually don't make sense.
Nevertheless this just moves things to Awake to be consistent with the way we've fixed some of other other OnValidate calls.
- Fixes: #https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7213
=> Update the PokePointer to avoid unnecessary work in OnValidate.

Assets/MixedRealityToolkit/Utilities/Editor/EditorAssemblyReloadManager.cs
Unity's documentation states that EditorApplication.focusedWindow is allowed to be null. Before referencing that value to call ShowNotification, MRTK should confirm that the value is valid.
=> Check for null focusedWindow before showing notification

.gitignore, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs, Assets/MixedRealityToolkit/Definitions/Utilities/ArticulatedHandPose.cs
XR SDK doesn't provide a palm pose for HL2 articulated hands, so we synthesize one in MRTK.
Instead of passing the grip pose in directly though, it needs a rotation offset to align with the expected coordinate system of other hand joints.
Also adds the new MSB4U-generated NuGet.config to the .gitignore.
Before this change: 
After:
=> Add offset for correct palm rotation on XR SDK

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildInfo.cs
Adjusted MRTK build scripts to allow callers of UWP build tools to specify arbitrary device capabilities
=> Device capability manifest support for uwp builds

Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
The MixedRealityToolkit.Generated folder was created twice. Once in the Foundation package, and again at the root of the Assets folder when a profile was cloned.
This fix removes the additional call to generate the MixedRealityToolkit.Generated within MixedRealityToolkitFiles to isolate a call to generate the folder in the MixedRealityProfileCloneWindow.
The MixedRealityToolkit.Generated folder now appears only at the root of the Assets folder.
- Fixes: #7184
>
>
=> Fix MixedRealityToolkit.Generated folder creation location

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/DotNetAdapter/DotNetAdapter.csproj, Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs
This change updates the minimum versions of DotNetWinRT and MSBuild for Unity to 0.5.1043 and 0.9.1-20200131.14, respectively.
Fixes build issue when using the .NET backend
=> Update to the latest DotNetWinRT and MSBuild for Unity packages

Documentation/Authors.md, Documentation/Contributing/Roadmap.md, Documentation/ReleaseNotes.md, Documentation/Updating.md
This change updates the release notes and upgrade guide with information on the changes and known issues in the upcoming MRTK 2.3.0 release.
Additionally, the roadmap has been updated to remove 2.3.0, add details on 2.4.0 and early looks at releases that are further out.
The list of authors has also been refreshed to add our newest contributors!
Fixes: #6922 and #7149
=> Update release notes, upgrade guide, roadmap and authors list for 2.3.0 release

Documentation/Contributing/DocumentationGuide.md
Our documentation contribution guideslines say to avoid using "you" yet the doc itself uses a ton of yous.
I couldn't unsee it once I saw it, and had to at least make ourselves be consistent within the same file.
=> Align our documentation guidelines to our own guidelines

Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs
The `GltfUtility` had an assert that the the bin chunk should be the same length as the JSON-defined buffer. The spec actually states that this can be up to 3 bytes different due to .glb padding.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5417
=> Update the valid size of the glb buffers according to the spec

Documentation/ReleaseNotes.md
The release notes were missing a line of text separating the 2.3.0 hyperlinks and describing the next list.
This change adds back "This release of the Microsoft Mixed Reality Toolkit supports the following devices and platforms."
=> restore missing line in release notes

Assets/MixedRealityToolkit.SDK/Inspectors/UX/ManipulationHandler/ManipulationHandlerInspector.cs, Assets/MixedRealityToolkit/Extensions/GameObjectExtensions.cs
Added a generic method that collects all MonoBehaviours on a GameObject that require a certain component and returns their names.
changed of ObjectManipulatorMigrationHandler shows its info box on the ManipulationHandlerComponent. It now shows an error and what component needs their RequireComponentAttribute removed, as well as disables the migrate button until that's done
- Fixes: #7243
=> RequireComponent checker

Documentation/ReleaseNotes.md
As pointed out in #7255, the 2.3.0 release notes do not mention the new Dependencies folder or the <project>.Dependencies.msb4u.csproj file.
This change adds entries into the "What's new section"
=> Add notes about Dependencies folder and *.msb4u.csproj file

Assets/MixedRealityToolkit/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
An errant, unused using statement was causing a missing assembly error on Unity 2019.3.
This change also adds in a missing #if !UNITY_2019_3_OR_NEWER in the configuration dialog as it was attempting to access a dictionary key that will not exist.
=> Fix missing assembly error on 2019.3

Assets/MixedRealityToolkit.Examples/Demos/UX/Slate/SlateExample.unity
Example scene polish - Slate Examples
- Deleted unused 3D Text mesh and reticle objects
- Fixes: #7252
=> Slate example scene polish - deleted unnecessary objects.

Assets/MixedRealityToolkit/Extensions/GameObjectExtensions.cs
Our CI build got broken due to a change that used the API:
Attributes.GetCustomAttributes
This function doesn't exist in UWP .NET, but Type.GetCustomAttributes does.
The other possibility here was to make this function an editor-only extension (should really only be used in editor-land only).
=> Fix the broken UWP app build

Documentation/README_ExampleHub.md, Documentation/ReleaseNotes.md, Documentation/Tools/HolographicRemoting.md
1. Adds a note on using MSB4U for your own project dependencies as well as MRTK's
1. Adds a note on the .bin and .obj folders that can be safely added to your gitignore
1. These folders are in this repo's .gitignore, but I don't believe that's distributed via our unity packages since it begins with a `.` and is thus ignored by Unity
1. Fixes the .csproj reference for step 2 of troubleshooting the DotNetWinRT dependency
=> Update docs for MSB4U resolution troubleshooting and add additional notes

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/DotNetAdapter/DotNetAdapter.csproj
Per https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7191#issuecomment-583081841, a new version has been shipped that should fix the issue when ASA and DotNetWinRT are both imported.
=> Update DotNetWinRT dependency version

Assets/MixedRealityToolkit/Extensions/GameObjectExtensions.cs
So previous change: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7264 didn't work because that other API also didn't exist on UWP. 
This goes with the other approach mentioned in the last PR, which is just to make it editor-only functionality.
=> Fix number two for broken CI

Assets/MixedReality.Toolkit.Foundation.nuspec, Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MixedRealityToolkit.Providers/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MixedRealityToolkit.Tests/TestUtilities/MixedReality.Toolkit.Tests.Utilities.nuspec, Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec
Nuget licenses should point to the documentation for the specific release. This change updates to .../releases/2.3.0/...
NOTE: The link will _not_ resolve until the release branch is created.
=> Update nuget package license links

Documentation/Tools/HolographicRemoting.md
One person who recently tried out the remoting work was hitting an error "file not found" when going through the dotnet/msbuild restore steps.
The actual cause was because Unity Hub was installed and launched first, which took a snapshot of the system PATH variable, which at the time lacked the reference to the location of dotnet.exe. Then, even though they were closing/restarting Unity itself, because Unity Hub was never closed, future instances of Unity would inherit the stale, old path of Unity Hub, leading it to see like it was permanently busted.
The simple solution here is just to reboot the machine (the other solution is to manually kill Unity Hub.exe using task manager).
Either way the error is super cryptic, and just adding a note here to reboot (simplest solution) in case …
=> Add another troubleshooting step for msb4u integration

Assets/MixedRealityToolkit.SDK/Inspectors/Experimental/FollowSolver/FollowInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs, Assets/MixedRealityToolkit.SDK/Inspectors/Utilities/Solvers/InBetweenInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingBoxInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingPlaneInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingPrimitiveInspector.cs, Assets/MixedRealityToolkit/Inspectors/ClippingSphereInspector.cs
Adding CanEditMultipleObjects tag to some components
https://docs.unity3d.com/ScriptReference/CanEditMultipleObjects.html
- Related: #4165
>
>
=> Add CanEditMultipleObjects tag

Documentation/CrossPlatform/UsingARFoundation.md
The ARFoundation capabilities are now in the Foundation package and not the separate UnityAR package, this change is now reflected in the Android/iOS doc.  Also changed 2019.x to 2019.3.
>
>
=> Update ARFoundation Doc for 2.3

pipelines/ci-release.yml
Change Release pipeline to reference built-tools repository instead of handling git clone in a separate task. This relies on a Service Connection and we won't have to maintain an access token in pipeline variables.
I issues this PR against 2.3.0-stabilization branch as it seems that's the branch release builds are running against. Let me know if this change needs to be cherry-picked anywhere else (or will it be merged with other changes after the release).
=> Use alternate sync method for build tools repository

Documentation/GettingStartedWithTheMRTK.md, Documentation/ReleaseNotes.md
The UnityAR package contents have been moved to the Foundation package for 2.3.  The references to the package have been removed from the Release Notes and GettingStartedWithMRTK docs.
>
>
=> Remove UnityAR package references in Release Notes and GettingStartedWithMRTK

Assets/MixedRealityToolkit.Providers/UnityAR/Editor/ConfigurationChecker/UnityARConfigurationChecker.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitFilesTests.cs, Assets/MixedRealityToolkit/Utilities/Editor/FileUtilities.cs, Assets/MixedRealityToolkit/Utilities/ScriptingUtilities.cs, Documentation/Tools/HolographicRemoting.md
The configuration checker for DotNetWinRT searched the filesystem instead of just Unity's visible assets. This was leading to a case where, because MSBuildForUnity 0.9.1 resolves nuget dependencies to a non-Unity-visible local cache before resolving the root dependencies folder, this checker was seeing DLLs that weren't actually visible to Unity.
This helps improve the steps for uninstalling MSBuildForUnity.
Also, added a test, updated some formatting, and added a line to the docs describing removing those local cache folders.
=> Update FindFilesInAssets to only search AssetDatabase

pipelines/ci-release.yml
I forgot to replace this path in previous PR (see latest MRTK-Release-CI failure). Sorry about that.
=> Fix path to signCheck script

Assets/MixedRealityToolkit/Utilities/Editor/FileUtilities.cs
Per in person discussion related to #7288, this change removes the off-by-default alternate implementation of FileUtilities.FindFilesInAssets as there did not exist a test for that implementation and the MRTK code base only used the default path.
=> Remove alternate implementation of FindFilesInAssets

pipelines/ci-release.yml
A step in our mrtk_ci_release pipeline is to delete the MixedReality.Toolkit.Tests package for the release, but the pipeline also removed the MixedReality.Toolkit.Test.Utilities in this process.  
This update excludes the MixedReality.Toolkit.Tests.Utilities from the MixedReality.Toolkit.Tests removal step.
>
>
=> Update pipeline to include MixedReality.Toolkit.Test.Utilities 

web/version.js
This change replaces "prerelease/2.3.0_stabilization" with "releases/2.3.0" in the documentation version list.
Please _do not_ merge until the 2.3.0 release has been completed.
=> Update the documentation version list to add 2.3.0

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs
Update the access modifier of the new method `UpdateNonAABoundsCornerPositions` to match the Obsolete method `UpdateNonAABoundingBoxCornerPositions`
=> Match access modifier

pipelines/ci-release.yml
I'm seeing an issue in the signing portion of the build where there's a failure to start the validation process (i.e. using nuget verify). It line that's triggering it is the one that's running the nuget command, so my best hypothesis now is that there's some build agent change that removed the nuget.exe tool from the path.
Trying this out to see if it resolves the issue.
=> Update the ci-release pipeline to ensure that nuget.exe is actually in the path

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
- The BoundingBox now properly ignores a collider when a renderer is found in case of RendererOverCollider and does the same vice versa
- In case the BoundingBox has itself as the target, it ignores itself so its own BoxCollider is not taken into account when calculating bounds
- Fixes: ##7300
=> Mrtk bb bounds calculation fix

Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader
When selecting the wireframe shading mode within the Unity Editor's scene viewport objects using the MRTK/Standard shader would occasionally render their wireframe representation in the wrong location (the model's identity location). Note, the coffee cup appears as a large version of itself at the origin:
I was able to narrow the issue down to the meta pass within the shader, it appears UnityMetaVertexPosition is not respecting the EDITOR_VISUALIZATION keyword. Moving the meta pass as the second pass (or anything but the first pass) seems to fix the issue. Unity now specifies the meta pass as the last pass in the Unity/Standard shader (IIRC this was not the case originally?) so this may be an undocumented requirement. 
Moving the meta pass to be the second pass declared within the …
=> Fixing Unity Editor Wireframe Shading Mode Error

Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
The MRTK Configurator window keeps showing up on 2019.3 because there's a certain configurator setting (enabling MSBuildForUnity) that is configured to not show up in the UI (i.e. there's no checkbox for MSBuildForUnity in 2019), but the code in the backend still checks to see if it's enabled (and will keep popping up the window if it's not enable).
The other root/underlying confusion here is how there are multiple dictionaries and sources of data, where maintaining multiple is tricky.
Another issue that we should probably solve (in a future case) is having a test that validates that IsProjectConfigured returns true after applying the defaults on a given project.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7332
=> MRTK Configurator keeps showing up 2019.3

Assets/MixedRealityToolkit.Services/InputSystem/NearInteractionGrabbable.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/NearInteractionGrabbableTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/NearInteractionGrabbableTests.cs.meta
Updates the validation in NearInteractionGrabbable to not log an error when there is actually a valid collider on the object. If the first collider on a game object isn't valid (i.e. it's not one of the supported colliders) we currently log an error (by newing up an exception, which we don't even throw).
This changes it so that if there is at least a single supported collider type, we don't log an error.
Also this changes it to just by an error log instead of newing an exception (and then logging the exception). Not much of a need to new up an exception only to not throw it.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7342
=> Update NearInteractionGrabbable to not warn when there is actually a valid collider on the game object

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/DirectionalIndicator.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
A couple of issues here:
1. As mentioned in the issue, the naming of IsVisible is somewhat confusing because it refers to whether or not the target itself is visible, but then is used to control the visibility of ourselves (in the negated form, obviously) further down the line. I opted to change it to reflect how we're going to be changing our own visibility, rather, than whether or not the target itself was actually visible.
2. Even with that fix, there's still an exception because SolverUpdate() is called in LateUpdate, after the target object could have been destroyed. This makes it so that we only do SolverUpdate() stuff in the target object is still around.
Also added a test to verify that it's been fixed!
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7334
=> Fix the DirectionalIndicator's handling of destroyed target game objects

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/PackageManifestUpdaterTests.cs, Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs
Previous parsing logic was failing when current culture was set to one that uses decimal comma instead of decimal point.
See also the list of countries that use decimal commas: https://en.wikipedia.org/wiki/Decimal_separator#Countries_using_decimal_comma
=> Changed the logic of MsBuild prerelease parsing so that it is not affected by current culture.

.github/stale.yml
This change adds an initial stale configuration for stale bot.
Going through our past issues, we have a lot of issues that were open for older version of the MRTK (i.e. release candidate and even pre-RC). While many of these have been addressed during our fixes/churn in the past, there's a non-trivial amount of time it takes to comb through a lot of stale issues.
There's likely to be some portion of the issues that actually are still relevant - these will still be marked stale, but can become un-stale as folks comment (or reopen issues that get closed). The hope really is here that the only old issues that we carry forward are ones that people are actively looking for fixes for (i.e. it gives us more data to know which issues to target).
Some rationale of the time:
Stale time of 150 - …
=> Add initial stale configuration

Assets/MixedRealityToolkit.Extensions/HandPhysicsService/Examples/HandPhysicsServiceExample.unity
We had some reports of this scene being set up in a way that caused errors at startup when switching profiles.
We may need to investigate this LoadProfilesAtStartup script, alongside @davidkline-ms' work around active profile switching (#4289, etc). Setting the profile to null at startup causes a null profile all the way through the first `Update`, until a `LateUpdate`, which isn't desirable and is causing exceptions. 
For now, I've updated this scene to just load the correct profile initially instead of swapping at runtime.
=> Update hand physics example scene to load correct profile at startup

Documentation/Input/CreateDataProvider.md, Documentation/Performance/PerfGettingStarted.md, Documentation/README_Solver.md, Documentation/SceneSystem/SceneSystemSceneTypes.md, Documentation/hologram-stabilization.md, scripts/ci/validatedocs.ps1
@CDiaz-MS noticed that our github.io docs had some broken links which were super interesting. There are actually a few different issues that are worth discussing here.
1. The reason the image was broken was because of a case-insensitive issue on the docs update pipeline that we have. At some point in the past, someone changed the name of one of the images from image.png to image.PNG. The markdown image name and the actual image name matched fine, but the problem is the docs pipeline never "noticed" the image filename change from image.png to image.PNG. As a result, it never pushed the change to the gh-pages branch. The reason this happened is because git uses the default case-sensitive setting of the environment it's running in, and at least for our docs pipeline (which use powershell on …
=> Add validators to ensure that we don't have mismatched image cases

Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerBehaviorTests.cs
Makes TestGrab more reliable by ensuring camera is looking at cube on start and waiting for input system to update before checking pointers.
- Fixes: #7359
Verified by running tests 100 times in a row.
>
>
> commands (substituting {PR_ID} with the ID of this …
=> Ensure camera is looking at cube and input system ticks.

Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs, Assets/MixedRealityToolkit/Definitions/Diagnostics/MixedRealityDiagnosticsProfile.cs, Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityDiagnosticsSystemProfileInspector.cs, Documentation/Diagnostics/UsingVisualProfiler.md
Adds some `AppCapture` API calls to detect when MRC is running and auto-hide the profiler.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7369
=> Hide visual profiler while MRC is running

Assets/MixedRealityToolkit.Examples/Demos/Solvers/Scripts/HideTapToPlaceLabel.cs, Assets/MixedRealityToolkit.SDK/Features/Utilities/Solvers/TapToPlace.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
Added 4 tests for Tap to Place:
1. Tests default behavior with the head as the TrackedTargetType
2. Tests default behavior with Controller Ray as the TrackedTargetType
3. Tests code configurability with the head as the TrackedTargetType
4. Tests object placement with colliders in the scene, uses Start/StopPlacement calls instead of clicking  
While writing the collider test I found that if an object is created via script, the bounds of the collider do not get updated before SurfaceNormalOffset is stored.   `UnityPhysics.SyncTransforms()` was added to TapToPlace before SurfaceNormalOffset is stored. Thanks @julenka 
There was also a namespace update for HideTapToPlaceLabel and TapToPlace, thanks to @keveleigh for pointing that out.
- Fixes: #7362
=> Tap to Place Tests

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs
The mrtk_CI build is currently broken due to the usage of UnassignedReferenceException. This is really weird and totally not clear from the get go, but something that we've dealt with in the past (see https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5215/files#diff-5a24b3ab8cfc7d46cbb7d009ef8b0424) because the build step when we run msbuild and generate player binaries.
This purely to unblock the build, despite it being less correct (i.e. it would be great to actually use UnassignedReferenceException and not just Exception)
Separately we have some workstreams going that should make it so that we can reasonably use things like that but we're not quite there yet.
=> Use a less interesting version of the exception to work around the nuget/build step

Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/Templates/ExtensionConstructorTemplate.txt, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/Templates/ExtensionConstructorTemplate.txt.meta, Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/Templates/ExtensionScriptTemplate.txt
When using the extension service wizard creator, if the profile/inspector files (which are marked optional) are not selected and thus not created, then the new service class will throw an error. This is because the service template attempts to always create a private field of the profile instance.
However if no special profile object is created, then the service class does not need the field or the constructor.
Also updated the service template to call base.initialize() and base.update by default. 
- Fixes: #5654 
>
>
=> Fix extension service wizard generation on optional profile

Assets/MixedRealityToolkit.Providers/OpenVR/GenericOpenVRController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/OculusRemoteController.cs, Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/Controllers/BaseWindowsMixedRealitySource.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs, Assets/MixedRealityToolkit/Providers/Hands/BaseHand.cs, Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/UnityTouchController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/XboxController.cs, Documentation/ReleaseNotes.md
`SetupDefaultInteractions` was originally abstract. As pointed out in #5847, it's possible not all controllers would need to implement this, even though they'll be required to.
Additionally, this method took in a specific handedness, even though the controller class itself has a handedness that's passed in with its constructor.
I refactored down a combination of the actual implementations of this class (which were largely identical) and made it virtual, for classes that still need to override the behavior.
- Part of #5847
=> Refactor down SetupDefaultInteractions into BaseController

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs
`spriteIconTexture` doesn't exist. It's actually `spriteIconTextures`.
=> Fix ButtonIconSet for Unity 2019.3

Assets/MixedRealityToolkit/Utilities/ScriptingUtilities.cs
This class had a typo in its obsolete message, a duplicate ending `</summary>` tag, and a stray `<returns>` tag.
=> Update ScriptingUtilities.cs summary tags

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Themes/Model_BuckyTheme.asset, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableRotationTheme.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/VisualThemes/ThemeEngines/InteractableThemeBase.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/VisualThemeTests.cs
The InteractableRotationTheme was originally designed to modify the local rotation values of the host target object. Although the original rotation and property setter components of the class correctly controlled the localEulerAngles property, the property getter component returned the host objects euler angles in world space.
This change fixes this bug as well as introduces a new theme property to the class that allows consumers to control whether values should be applied in local space or world space.
Added test to verify this functionality.
This PR is an extension from @Bertrand75014 's original PR #7081 
- Fixes: #7080 
>
> git …
=> Fix visual rotation theme for toggling local vs world space rotation

Documentation/ReleaseNotes.md
some of our links in the 2.3.0 release notes were leading to wrong articles
also added a note about Unity 2019.3 with nuget on top of the article, so users won't find out about it too late
fixes: #7410
=> fixed some links and added a note about nuget and unity 2019

pipelines/ci-daily.yml, pipelines/ci-packaging-dontpublish.yml, pipelines/ci-packaging-internal.yml, pipelines/ci-packaging.yml, pipelines/ci-release.yml, pipelines/ci.yaml, pipelines/config/settings.yml, pipelines/pr.yaml, pipelines/templates/assetretargeting.yml, pipelines/templates/ci-common.yml, pipelines/templates/common-Unity2019.yml, pipelines/templates/common.yml, pipelines/templates/compilemsbuild.yml, pipelines/templates/generateprojects.yml, pipelines/templates/tasks/unitybuild.yml, pipelines/templates/tasks/unitypackages.yml, pipelines/templates/tests.yml
This change addresses problems introduced in PR #7390 - i.e. it allows to use a different version of Unity when building on internal agents.
Unfortunately, it turns out that variable expansion still doesn't work when specifying agent capabilities, so I wasn't able to remove all duplication (although I made sure that the version numbers in "demands" sections are filled in consistently)
=> Pass correct Unity version for each of the agent pools

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Definitions/Devices/MixedRealityControllerMappingProfileTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Definitions/Devices/MixedRealityControllerMappingProfileTests.cs.meta, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/EventSystemTests.cs.meta, Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs
Adds some tests to catch the bug reported in #7405.
Also:
1. Updates a test script with the test icon
1. Fixes a quirk I found while testing this fix, where the mapping profiles aren't automatically saved when the update menu item is clicked
1. Removes an extra line from the controller mapping profile definition
- Follow-up to #7406
=> Add controller mapping migration tests

Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Clearing out old branches and found this commit leftover from some old PRs.
Small change, but there's no point in creating this variable since we don't use it and only need the property call to happen.
=> Use discard instead of saving unused variable for playspace

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/Extensions/InteractionSourceExtensions.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit/Utilities/WindowsApiChecker.cs
This change adds IsMethodAvailble() to WindowsApiChecker and marks the UniversalApiContractV#_IsAvailble properties as obsolete.
References tot he contract version check in MRTK have been updated to use the new method.
Fixes: #6886
=> Switch from API contract version to IsMethodPresent (#6886)

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/Migration/BoundsControlMigrationHandler.cs, Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
This PR updates the misleading property name `RotationHandleSlatePrefab` to `RotationHandlePrefab`.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6657
=> Rename property in BoundingBox

web/version.js
- added currently active version of docs to version selector
- removed currently active version from drop down list 
- removed some unnecessary code / cleanup in the version script
At least a temporary fix for users who get thrown out of the version specific documentation by clicking the direct links on the front page - that way they can see which version they're currently in on any page of the docs
=> improvements to version dropdown

Assets/MixedRealityToolkit.Tools/BuildWindow/BuildDeployWindow.cs, Assets/MixedRealityToolkit.Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs, Assets/MixedRealityToolkit/Extensions/DateTimeExtensions.cs, Assets/MixedRealityToolkit/Extensions/DateTimeExtensions.cs.meta, Assets/MixedRealityToolkit/Utilities/WindowsDevicePortal/DataStructures/DeviceInfo.cs, Assets/MixedRealityToolkit/Utilities/WindowsDevicePortal/DevicePortal.cs
There were a few issues found when testing the deploy window against local machine/hololens usb testing. 
For local machine, InstallAppOnDeviceAsync() would check for the Install.ps1 script but would only select if it is was the only script. This fix looks for the script directly.
If trying to deploy an x64 app to HoloLens, the install appx would fail but not report anything to the user. Added debug.log
DevicePortal.InstallAppAsync() would try to embed revelant dependencies with the install request. However, this was hardcoded to look for the x86 folder. The fix is to look at the appx path to determine what architecture is being targeted. 
Some general GUI fixes. Added UI to indicate if last test connection to target was successful or not. Also, sharing code with new datetime string …
=> Fix install appx on local via MRTK deploy window

Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfUtility.cs
The GLTF parser expected attributes of mesh primitives to have a specific formatting, like this:
```json
{
"attributes": {
"POSITION" : 0,
"NORMAL" : 1,
"TEXCOORD_0" : 2
},
"indices" : 3
}
````
(Note the lack of spaces between "attributes" and the following colon). Generally 
- Removing requirement for specific formatting in attributes.
- Fixes: #7223 
Try loading the following GLTF-Model without this change and with this change:
[cube.zip](https://github.com/microsoft/MixedRealityToolkit-Unity/files/4260435/cube.zip)
=> Removing specific formatting for GLTF mesh-primitive attributes

Assets/MixedRealityToolkit.Providers/OpenVR/OpenVRDeviceManager.cs, Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/Controllers/BaseWindowsMixedRealitySource.cs, Assets/MixedRealityToolkit.Providers/XRSDK/Controllers/GenericXRSDKController.cs, Assets/MixedRealityToolkit.Providers/XRSDK/XRSDKDeviceManager.cs, Assets/MixedRealityToolkit.Services/InputSimulation/BaseInputSimulationService.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities/PlayModeTestUtilities.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs, Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs, Assets/MixedRealityToolkit/Providers/UnityInput/UnityJoystickManager.cs, Assets/MixedRealityToolkit/Providers/UnityInput/UnityTouchDeviceManager.cs
`SetupConfiguration` was only ever called directly after creating the class. It wasn't abstract or virtual, so it couldn't be overridden. It takes in the class' its own type in order to perform some action, which all the information for is present at the time the constructor is called.
This PR moves all work done by `SetupConfiguration` into the constructor. Any custom class' constructor can do additional setup work as needed.
- Part of #5847
=> Deprecate SetupConfiguration in BaseController

Assets/MixedRealityToolkit.Extensions/HandPhysicsService/HandPhysicsService.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Definitions/Devices/MixedRealityHandTrackingProfileTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/ProjectPreferencesTest.cs, Assets/MixedRealityToolkit/Providers/Hands/BaseHandVisualizer.cs
1. Fixes two places where we were incorrectly using null propagation and coalescing on Unity objects.
1. https://blogs.unity3d.com/2014/05/16/custom-operator-should-we-keep-it/
1. Fixes an instance in the tests where we were `new`ing a scriptable object
1. `Microsoft.MixedReality.Toolkit.Input.MixedRealityHandTrackingProfile must be instantiated using the ScriptableObject.CreateInstance method instead of new MixedRealityHandTrackingProfile.`
1. Fixes an instance where one of our test classes was incorrectly marked as a `MonoBehaviour`
1. This was causing `You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent(). Alternatively, your script can inherit from ScriptableObject or no base class at all` on test …
=> Fix some Unity object null comparisons and test infrastructure

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/BaseWindowsMixedRealityCameraSettings.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/Shared/WindowsMixedRealityReprojectionUpdater.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityArticulatedHand.cs, Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs, Assets/MixedRealityToolkit/Utilities/WindowsApiChecker.cs
This change adds IsPropertyAvailale and IsTypeAvailable methods to the WindowsApiChecker class and updates MRTK code to use them instead of directly calling ApiInformation.Is*Present().
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7426
=> Add IsPropertyAvailable and IsTypeAvailable to WindowsApiChecker

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
This bool was added in #7402, but is unused. This is causing a warning in Unity.
```
Assets\MixedRealityToolkit.Providers\WindowsMixedReality\XRSDK\WindowsMixedRealityDeviceManager.cs(61,18): warning CS0219: The variable 'hasCapability' is assigned but its value is never used
```
=> Remove unused bool from WMRDeviceManager

Assets/MixedRealityToolkit.SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
there's a check that queries if the input controller currently used is setting a (spatial) position.
This prevents all platforms that won't have this information to interact / scroll the scroll view.
I haven't found a reason for this check to be there as none of the interactions in scrolling object collection is relying on that position but instead using the pointer result which is available for those platforms as well. 
Also we shouldn't use any controller specific code in any of the UX controls but instead work with the data the pointer provides us. 
I've removed this check now to allow users to use the control on android / touch platforms 
- Fixes: #7404
=> removed controller query about spatial position in scrolling object collection

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs
These `break`s are added after `returns`, so they're unreachable and throw warnings.
=> Remove unreachable code from WMRDeviceManager

Assets/MixedRealityToolkit.Tools/BuildWindow/BuildDeployWindow.cs, Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs
Make UseSSL default to false. Issues with using device portal on HTTPS vs HTTP atm. @keveleigh do you remember/know anything about this?
Also, update last connection time to null when a new test connection has been initiated but not validated yet. This way the UI updates to help indicate a change has occurred.
- Fixes: # .
>
>
=> Minor updates to build window

Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/InputSystemTests.cs, Assets/MixedRealityToolkit.Tests/EditModeTests/SpatialAwareness/SpatialAwarenessSystemTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/ButtonConfigHelperTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/CoreServicesTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/BoundsControlTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/LoadingIndicatorTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PinchSliderTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SlateTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/SpatialObserverTests.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/Utils/TestButtonUtilities.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/VisualThemeTests.cs, Assets/MixedRealityToolkit.Tests/TestUtilities/TestUtilities.cs, Assets/MixedRealityToolkit/Inspectors/ServiceInspectors/ServiceFacadeInspector.cs, Assets/MixedRealityToolkit/Inspectors/Utilities/MixedRealityInspectorUtility.cs, Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
In preparation for #7409, this updates all tests to load assets via GUID instead of hardcoded path. This will make our tests more robust to folder / path changes in the future, while also potentially alerting us to GUID changes that we'll need to mitigate.
- Fixes: #7438
=> Update test files to load assets via GUID instead of path

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs, Assets/MixedRealityToolkit/Providers/BaseController.cs
#7375 deprecated `SetupConfiguration` from the BaseController class, but not all instances were properly cleaned up. This PR removes those remaining instances.
It also updates the previously deprecated `SetupConfiguration` method signature (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6653) to point to `Enabled` instead of the other deprecated method.
=> Cleanup some missed usages of SetupConfiguration

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/PointerClickHandler.cs
Although this script is deprecated, it's currently throwing some build warnings:
This PR fixes them up.
=> Clean up warnings in PointerClickHandler

Documentation/ReleaseNotes.md, Documentation/Updating.md
This change adds details of the recent WindowsApiChecker changes (#7402, #7429). It also adds the template information for upgrading MRTK as well as moving obsolete method information recently added into the updating.md article.
=> update releasenotes and updating pages with recent changes

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildMRTKTemplates/WSA.Player.Template.props.template
This was previously updated in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7267 but this template wasn't changed. It doesn't cause problems, since MRTK didn't need to be built against a newer version, but we should keep it up to date.
=> Update adapter version in WSA.Player.Template.props.template

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs
Instead of assuming only one SpatialCoordinateSystem will ever exist, this change checks the `IntPtr`s to detect when the underlying root coordinate system has changed.
This helps scenarios like recentering, when a dev / user wants to realign the experience in a specific alignment. Can also help in scenarios when tracking is list and the original coordinate system is never regained. Also helps in the scenario when a new scene is loaded.
Note: This PR is going into an upcoming hotfix release of 2.2. It is already fixed in the current release of 2.3.
- Fixes: #6974
=> Cherry-pick #7205 to 2.2.1

Assets/MixedRealityToolkit.SDK/Features/Input/Handlers/CursorContextManipulationHandler.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/BaseCursorTests.cs
This will prevent the migration step from running, as of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7244.
This fixes the case where this script assumed the presence of ManipulationHandler. I chose this fix over `EnsureComponent`, because we have existing code that prevents migration based on `RequireComponent`.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7465
=> Add RequireComponent to CursorContextManipulationHandler

Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
A handful of tests fail locally for me, and not within our Azure pipeline. These two solver tests appear to fail due to the assumption that the test runner runs at 60fps. I'm not actually sure if the test runner runs at a certain vsync or as fast as it can? Anyway, changing two waits to be frame rate independent.
Before:
After:
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7483 (partially)
Please run the test runner locally.
>
>
>
=> Fixing Solver Tests Which Fail Locally

Assets/MixedRealityToolkit.Services/InputSystem/FocusProvider.cs, Assets/MixedRealityToolkit.Tests/PlayModeTests/FocusProviderTests.cs
This change is needed since the gaze provider isn't a required pointer. Some scenarios need to support the lack of a gaze pointer.
In those cases, this pointing data is never initialized and can null ref in a few spots.
- Fixes: #7427
=> Add null checks for gazeProviderPointingData

Assets/MRTK/Providers/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec
This change fixes the CI NuGet packaging step that was broken by moving the Providers packages down a level in the folder heirarchy (#7491)
=> Update UnityAR nuspec based on the new path depth

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs
Even if the API is present, it's possible eye tracking isn't actually supported on the current device. This ensures we don't actually call the APIs unless they're both present and supported.
@jwittner it'd be good if you can test this in your scenario! I wasn't able to repro your stack exactly, but did see other exceptions in your same scenario that this fixes.
- Fixes: #7482
=> Add check EyesPose.IsSupported to only call APIs when supported

Assets/MRTK/Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs
When the registrar was removed from the constructor in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6457, it looks like the new constructor was accidentally also marked with `Obsolete`. This PR removes that. The old constructor is still obsolete.
=> Remove incorrect obsolete from WindowsSpeechInputProvider

Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHub.unity, Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHubMainMenu.unity
This change addresses a CI failure where the examples hub scenes were failing path validation due to moving the examples folder (#7509).
=> Update ExamplesHub scene paths

Assets/MRTK/Core/Inspectors/Setup/MixedRealityEditorSettings.cs, Assets/MRTK/Core/Utilities/Editor/Preferences/MixedRealityProjectPreferences.cs, Documentation/Performance/PerfGettingStarted.md
Warning against the "Optimize Mesh Data" setting at build time during development.
I've heard this brought up by a few community members, but was never able to reproduce this within the MRTK Unity project. Build times in current _mrtk_development_:
```
Compiled shader 'Mixed Reality Toolkit/Standard' in 6.47s
d3d11 (total internal programs: 21504, unique: 7168)
```
But, I opened a project  the other day and did encounter an issue with shader compilation taking upward of 5 minutes. After doing some poking around I narrowed the issue down to the "Optimize Mesh Data" in the player settings.
If you need this setting, I would recommend disabling it while iterating on your application and only enabling it when you go to make final builds. The "Optimize Mesh Data" settings tries to remove unused …
=> Checking the Optimize Mesh Data setting at build time.

Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset, ProjectSettings/EditorBuildSettings.asset
The moving of folders accidentally added extra scenes by default to the build window.
This change restores the default scenes collection to just the hand examples scene.
It also ensures that the examples hub scene service profile has the correct paths.
=> Fix accidental addition of extra scenes by default

Assets/MRTK/Core/Utilities/WebRequestRest/Response.cs, Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs, Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs
The DownloadHandler performs data conversion in the case of accessing its text property.
For requests not using it, that's unnecessary CPU and garbage.
The PR moves the access into the Response, where executed only when needed.
- Fixes: #7526
=> Data gets converted only when accessed

Assets/MRTK/Core/Inspectors/HoverLightInspector.cs, Assets/MRTK/Core/Inspectors/ProximityLightInspector.cs, Assets/MRTK/Core/StandardAssets/Shaders/MixedRealityStandard.shader, Assets/MRTK/Core/StandardAssets/Shaders/MixedRealityTextMeshPro.shader, Assets/MRTK/Core/StandardAssets/Shaders/Text3DShader.shader, Assets/MRTK/Core/Utilities/StandardShader/ClippingBox.cs, Assets/MRTK/Core/Utilities/StandardShader/ClippingPlane.cs, Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs, Assets/MRTK/Core/Utilities/StandardShader/ClippingSphere.cs, Assets/MRTK/Core/Utilities/StandardShader/HoverLight.cs, Assets/MRTK/Core/Utilities/StandardShader/ProximityLight.cs, Assets/MRTK/Examples/Demos/StandardShader/Scenes/ClippingExamples.unity, Documentation/README_MRTKStandardShader.md, Documentation/Rendering/ClippingPrimitive.md, Documentation/Rendering/HoverLight.md, Documentation/Rendering/MaterialInstance.md, Documentation/Rendering/ProximityLight.md, Documentation/toc.yml
This change attempts to improve developer iteration times (and runtime memory size) by reducing the shader variants generated by the MRTK/Standard shader. The following are build stats before and after the changes when building the HandInteractionsExamples scene:
> Compiled shader 'Mixed Reality Toolkit/Standard' **in 7.90s**
d3d11 (**total internal programs: 18816, unique: 6272**)
Compressed shader 'Mixed Reality Toolkit/Standard' on d3d11 from 18.10MB to 1.95MB
============================================================
Build Report
Uncompressed usage by category (Percentages based on user generated assets only):
Textures               25.1 mb	 62.9% 
Meshes                 1.1 mb	 2.6% 
Animations             42.7 kb	 0.1% 
Sounds                 605.2 kb	 1.5% 
Shaders …
=> Shader Variant Removal

Assets/MRTK/Services/InputSimulation/SimulatedHandDataProvider.cs
This change makes it easier to hit pressable buttons using the mouse scroll wheel by smoothly moving the hand to a destination depth on every tick using interpolation. This solution contributed by @ADP-JoNeff
- Fixes: #7536
- Tested in editor
- Tests pass locally
=> Smooth z-movement of simulated hand

Assets/MRTK/Core/Definitions/Devices/MixedRealityHandTrackingProfile.cs, Assets/MRTK/Core/Extensions/SystemNumericsExtensions.cs, Assets/MRTK/Core/Interfaces/InputSystem/Handlers/IMixedRealityHandMeshHandler.cs, Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs, Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs
This PR is part of an upcoming set to address some of the hand mesh tracking performance issues. This particular PR fixes the problem of constant re-allocation and re-assignment of mesh data every frame. With this change, the MRTK hand interaction example scene renders at 60 FPS with one hand mesh shown. Unfortunately, two hand meshes will easily kick it below 60 still.  
To achieve this improvement, there were two primary changes in this PR:
1) Create re-usable vertex/normal buffers in WindowsMixedRealityArticulatedHandDefinition both for the Windows API buffer (i.e HandMeshVertex) and the UnityEngine.Vector3 vertex/normal buffers. These buffer pointers are passed through HandMeshInfo in the OnHandMeshUpdated events. 
**BEFORE** this change, MRTK was allocating 4 arrays of Vector3's …
=> Improve Hand Mesh Performance

Assets/MRTK/Tests/PlayModeTests/GltfTests.cs
The gltf tests were sporadically "freezing" with the test runner pausing indefinitely. I've added setup and teardown methods that the other UI methods use. This on it own didn't stop the freezing. It seemed it would freeze every other time. 
What seemed to really fix it was the manual addition of the `AsyncCoroutineRunner`. I think this relates to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6362.
This resolves an issue introduced in this pull request: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7535
To verify you should be able to re-run all playmode tests locally and see it not blocking. Additionally, kick off a CI build.
> commands (substituting {PR_ID} with the ID …
=> Prevent test freeze during gltf test

pipelines/ci-weekly-internal.yml, pipelines/config/PolicheckUserExclusion.xml
Add an internal pipeline running compliance and security checks once a week. This is a basic set of tasks and we might need to revise the config and expand to other checks later on.
=> Add compliance build configuration

Documentation/toc.yml
Adding a reference to the Dock Control to the table of contents.
>
>
=> Adding the Dock Control to the TOC

Assets/MRTK/Core/Providers/BaseController.cs
In many cases, handed interactions are overridden to point to the default interactions in classes that don't need different one:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/ec3ae303cf832bc532edb57083b7edd96eaeb075/Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/BaseWindowsMixedRealitySource.cs#L27-L31
However, this isn't a requirement that we've previously enforced. So, this PR updates the code to double check that the handed interactions aren't null before using them. If they're null, the non-handed default interactions are used.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7528
=> Fix case where a specific controller handedness is set but only non-handed interactions exist

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
This private reference is currently pointing to the MRTK-implemented `GazeProvider` type. Since we allow devs to create their own, it'd be good to only reference the interface. It doesn't look like we had a specific dependency on our implementation.
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7566
=> Genericize gazeProvider ref in GGVPointer

Assets/MRTK/Core/Services/BaseEventSystem.cs, Assets/MRTK/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs, Assets/MRTK/Tests/EditModeTests/SpatialAwareness/SpatialAwarenessSystemTests.cs, Assets/MRTK/Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs, Assets/MRTK/Tests/PlayModeTests/PointerTests.cs, Assets/MRTK/Tests/PlayModeTests/Utils/TestInputUtilities.cs, Assets/MRTK/Tests/TestUtilities/TestUtilities.cs
Convert the default MixedRealityInputSystem class to utilize IsEnable property via IsInputEnabled. If input system disabled, then will not respond to raised events and other public interfaces. Updated test to cover scenario.
**NOTE:** This is being committed to side branch, not MRTK_Dev.
Fixes: #5901
Related: #7100
>
>
=> Enable/Disable Input System (part of series)

Documentation/EyeTracking/EyeTracking_EyeGazeProvider.md, Documentation/EyeTracking/EyeTracking_IsUserCalibrated.md, Documentation/EyeTracking/EyeTracking_Main.md, Documentation/toc.yml
This change cleans up and organizes some of the existing documentation around eye tracking for MRTK. Many of the doc pages were not visible in the table of contents. Also grouped relevant links to a "See also" section in each article. Cleaned up some of the wording, formatting, adding xref links, removing informal uses, etc.
- Fixes: #6341 
>
>
=> Update eye tracking documentation

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7525 deprecated an enum value but didn't update the Unity 2019.3 path with the new one. This was leading to an obsolete warning when opening.
=> Update deprecated MRTK configurator enum value for 2019.3

Assets/MRTK/Core/Utilities/Editor/SizeUtilities.cs, Assets/MRTK/Core/Utilities/Editor/SizeUtilities.cs.meta
It can be quite annoying to know what the world-space size of an object is in Unity, especially with multiple hierarchy transforms applied. 
This PR adds a editor utility that allows one to get the Renderer or Collider world space bounds sizes for a selected GameObject. 
Right click gameobject > MRTK > Render/Collider Size => See output results in debug log console
- Fixes: # .
>
>
=> Add size utility calculator for editor

Assets/MRTK/Providers/OpenVR/Headers/openvr_api.cs.meta
The meta for this script wasn't updated when it was added in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6374. This can cause other packages, like SteamVR, to overwrite the file and cause compilation errors in MRTK.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7588
=> Update meta for openvr_api

Assets/MRTK/Core/Utilities/Editor/AssemblyDefinition.cs
@CDiaz-MS found an issue where saving a newly created AssemblyDefinition object would fail.
This change
- checks for file existence before inquring about the readonly attribute
- switches from File.WriteAllText to StreamWriter.Write
=> Fix save when creating a new file

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs, Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
#7590 introduced some breaks when opened in Unity 2019.3. This fixes them, by adding a missing namespace and removing unreachable code.
=> Fix Unity 2019.3 build

Assets/MRTK/Core/Providers/GenericPointer.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Services/InputSystem/GazePointerVisibilityStateMachine.cs
Since `IsInteractionEnabled` calls into the cursor to set its visibility, which might involve setting a GameObject active or not, there's a slight perf cost to going down this property / method stack every frame.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/e30acbd2705111e600b6f220863cce6b4fe42e62/Assets/MRTK/Core/Providers/GenericPointer.cs#L69-L81
I instead added change checks to both `IsInteractionEnabled` and the point where the state machine is queried for the gaze pointer's current state.
I also updated some docs and formatting.
=> Improve FocusProvider perf (slightly)

Assets/MRTK/Core/Utilities/Physics/MixedRealityRaycaster.cs, Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs, Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs, Assets/MRTK/Services/InputSystem/DefaultRaycastProvider.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs
This change extends the input system profiler markers (#7590) to the raycast implementation.
=> Add profiler instrumentation to MRTK's raycast logic

Packages/manifest.json, ProjectSettings/ProjectVersion.txt
Updating our Unity version to the latest 2018.4.20, which includes a fix for https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6807. Also upgrades our WMR package to 1.0.19, which includes updated remoting binaries https://docs.unity3d.com/Packages/com.unity.xr.windowsmr.metro@1.0/changelog/CHANGELOG.html.
=> Update Unity and WMR package versions

Assets/MRTK/Core/Extensions/EventSystemExtensions.cs, Assets/MRTK/Core/Utilities/Physics/MixedRealityRaycaster.cs
This change is a continuation of the work begun in #7600 and add/updates profiler markers related to raycasting.
It also replaces calls to Physics.RaycastAll and Physics.SphereCastAll with RaycastNonAlloc and SphereCastNonAlloc to reduce potential GC pressure.
NOTE: The max hit count has been set to 32 in this change. We can discuss refining this number based on customer feedback.
=> Reduce raycast allocations, update performance markers

Assets/MRTK/Examples/Experimental/Dialog/DialogExampleController.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/Dialog.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/DialogButton.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/DialogButtonType.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/DialogResult.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/DialogShell.cs, Assets/MRTK/SDK/Experimental/Dialog/Scripts/DialogState.cs
* Mostly formatting and slight comment updates for clarity.
* Also added a missing MSFT license header to a file which was ported from a licensed script in HTK: https://github.com/microsoft/MixedRealityToolkit-Unity/blob/htk_release/Assets/HoloToolkit/UX/Scripts/Dialog/DialogButton.cs
* Slightly updated existing headers to match our current style
* Updated to [auto properties where possible](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/CodingGuidelines.html#access-modifiers).
* Updated a flags enum [to match our guidance](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/CodingGuidelines.html#review-enum-use-for-bitfields).
- Follow-up to #6925
=> Follow-up pass on Dialog PR

Documentation/Contributing/UnitTests.md
Small change making it clear that unit tests need to be run in Unity 2018.4.1f1
=> Cleaned up test documentation

Assets/MRTK/Core/Utilities/Physics/MixedRealityRaycaster.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs, Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
This change adds instrumentation to input handlers to help identify the portions of the MRTK update loop that is application code (event handlers). When analyzing, if significant time is spent in these scopes, it is likely the issue is external to the MRTK.
Also instrumented the MixedRealityInputManager as well as migrating from the previous Begin/EndSample syntax to the prefered using (marker.Auto()) { .. }.
=> Add profiler instrumentation to input handlers and input manager

Assets/MRTK/Providers/XRSDK/Editor/XRSDKConfigurationChecker.cs
Looks like I previously left a reference to the Unity.XR.ARSubsystems package in the XR SDK configuration checker, but nothing in the assembly actually references this. Removing.
=> Remove unused reference from XR SDK Config Checker

Assets/MRTK/Services/InputSystem/DefaultRaycastProvider.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Services/InputSystem/GazeProvider.cs, Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
This change continues the migration from Begin/EndSample to the prefered using(...) syntax for improved accuracy and reliabilty.
Additonally, profiler markers have been added to the input module and in all input system Raise* methods.
For ease of reviewing, since indentation has changed, consider ignoring whitespace.
=> Cleanup input instrumentation

Documentation/EyeTracking/EyeTracking_BasicSetup.md
* Two different sections discussed workarounds for the GazeInput capability that is not yet available in Unity. I consolidated them into the first section (A note on the GazeInput capability) and stripped the second section (Testing your Unity app on a HoloLens 2) down to a simple reminder. I don't think the information about hand-editing the XML is necessary--people who are interested in that could make the edit in MRTK or Visual Studio and then look into the resulting changes for themselves.
* Added step to expand _'Input Data Providers' -- it isn't expanded by default and someone wouldn't see _'+ Add Data Provider'_ if that isn't expanded.
* Added step to clone DefaultMixedRealityInputSimpulationProfile.
* EyeGazeCursor now seems to be in Foundation, so MRTK Examples aren't needed. …
=> clarify some things I noticed in the eye tracking setup docs

Documentation/EyeTracking/EyeTracking_BasicSetup.md
Follow on to #7615 based on feedback from @sostel.
* add back the note about checking MRTK prerequisites if you don't see a GazeInput capability
* doc that capability was added in Unity 2019
* clarify "should stay untouched"
>
>
=> additional eye tracking setup docs

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs, Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Tests/PlayModeTests/SpherePointerTests.cs
Currently there is an issue where the sphere pointer that targets a specific layer can mistakenly grab an object that's not on that layer. This occurs when the non-target layer object is encapsulated/overlapped inside a target layer object. The error occurred because the pointers of type SceneQueryType.SphereOverlap where not processed properly by the focus provider
- Fixes: #7620
=> Fixes issue where sphere pointer can grab overlapping non-target layer objects

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityEyeGazeProvider.cs
A follow up from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7515, modifying the doccomments to reflect what to expect when using this interface.
Based on comments on that PR it looks like using the IsEyeTrackingAvailable property is the way to know when eye tracking is gone.
Note that this is still not exactly complete because there's no event that a developer can use to listen to changes on this property (you have to poll).
=> Update the doccomments about how to handle eye tracking loss.

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityRaycastHit.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs
Adds a guard to not try to get `textureCoord2` if the shared mesh isn't readable.
I'm also fine with leaving this code as-is, if we think this is something we should recommend instead ("Make sure to check `Read/Write Enabled` on your asset bundle meshes" or something?).
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7632
=> Only try to get textureCoord2 is the shared mesh is readable

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
When testing remoting without the DotNetWinRT adapter, I noticed that grab interactions weren't working, since I didn't have joints. Looking through the code, I realized we fall back to the pointer's position in all cases except if the controller is a hand.
With this change, we now try to get the hand joints if a controller is a hand, but, if that fails plus in all other cases, if the controller provides a position, we use that instead. Grab interactions now work even without hand joints, as long as a position is reported.
I also made updates to the profiler markers to fit the new `Auto()` style we've been using. Due to this, I recommend [hiding whitespace changes when reviewing](https://github.blog/2018-05-01-ignore-white-space-in-code-review/).
I also updated some formatting and …
=> Fix grasp point on hands without joints in SpherePointer

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Rewriting this overwritten auto-property with another auto-property seems to have introduced a serialization issue. This reverts that change.
- Fixes: #7642
=> Revert SceneQueryType rewrite

Assets/MRTK/Services/InputSimulation/ManualCameraControl.cs
This summary tag still refers to adding this script to the camera. This is a holdover from the original script, ported from HTK. The MRTK version of the script isn't a MonoBehaviour and is used directly by the simulation service.
=> Update ManualCameraControl.cs summary doc

Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
Some profiler code was left in GenericXRSDKController, which causes a compilation error in Unity 2019.3 due to the removed `using`.
=> Remove leftover Profiler.EndSample() code in GenericXRSDKController

Assets/MRTK/Core/Providers/BaseSpatialMeshObserver.cs, Assets/MRTK/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs, Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs, Assets/MRTK/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
This change adds unity profiler markers to the spatial awareness system and its data providers.
This is a part of #7565
=> Add profiler instrumentation to spatial awareness paths

Assets/MRTK/Core/Inspectors/Setup/MixedRealityEditorSettings.cs, Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, Assets/MRTK/Core/Utilities/Editor/XRSettingsUtilities.cs
First pass on making the configurator XR SDK aware. In this, a `bool` is added to `XRSettingsUtilities` which checks if an XR SDK plug-in is installed which disables legacy VR. In this PR, this stops the check for VR enabled from running, since the legacy API was always being checked against and returns false when an XR SDK package is installed. This was causing the configurator to pop-up on every asset reload when XR SDK is enabled.
Next pass would be to see if there's a way to configure the XR SDK loaders from code.
- Part of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7513
=> Update config checker to be aware of XR SDK

Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Prefabs/NonNativeKeyboard.prefab, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/NonNativeKeyboardTouchAssistant.cs, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/NonNativeKeyboardTouchAssistant.cs.meta
This makes the nonnative keyboard prefab respond to touch events
Added a new behaviour NonNativeKeyboardTouchAssistant to the NonNativeKeyboard that enables touch when articulated hand support is detected. By request of @provencher after reading http://dotnetbyexample.blogspot.com/2020/04/migrating-to-mrtk2-using-non-native.html
=> Made NonNativeKeyboard touchable

Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityGGVHand.cs, Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKGGVHand.cs, Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs, Assets/MRTK/Tests/PlayModeTests/SlateTests.cs, Documentation/Input/InputProviders.md, Documentation/InputSimulation/InputSimulationService.md, Documentation/README_SystemKeyboard.md
There are a few locations that will use GGV (being the first location that people will often read) which don't expand the acronym. I ended up adding notes on what GGV stands for so that it's then at least searchable afterward (i.e. oh I should look for 'gaze gesture voice').
Note that I also could have introduced an acronym page for the docs but opted to not go that route because I don't think that the page would be super large and I don't think that people would necessarily read it (i.e. explaining what something is inline feels easier to the reader, at least within the scope of these changes)
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7623
=> Update docs to explain a bit more about what GGV is.

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MRTK/Core/Utilities/Editor/Preferences/MixedRealityProjectPreferences.cs, Assets/MRTK/Core/Utilities/Editor/Preferences/ProjectPreferences.cs
After https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6315, all our MRTK settings are now on a per-project basis (some were previously global), serialized into a .asset file. Some of our settings descriptions still mentioned the previously global nature of things.
I also:
* updated some of the settings text, for example to explicitly call out the one that handles the project configurator
* updated some summary tags that were incorrect (copied and pasted from the first setting and not changed)
* added a note to the settings page about where these settings are serialized and how they can be shared
* Fixed some instances of incorrect Unity null propagation
* `Instance?.` in `ProjectPreferences`, where `Instance` is a `UnityEngine.ScriptableObject`.
* Removed an unused key
=> Improve MRTK project settings text

Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs, Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs
This was previously logging a warning that a controller of type `IMixedRealityHand` was needed, but actually the failing case is the palm joint being unobtainable from `jointedHand.TryGetJoint(TrackedHandJoint.Palm, out MixedRealityPose palmPose)`.
This class is intended to fall back gracefully when the controller isn't an `IMixedRealityHand`, so no additional logging is needed in that case.
- Helps with https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7245
=> Update HandConstraintPalmUp logs to be more accurate

Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs
This `Debug.LogWarning` is currently running anytime `IsOpaque` is called on a UWP build. This should instead only be called on a UWP build if the app hasn't properly converted over to the WMR camera settings provider.
To fix this, it's been moved inside the `else` scope, with the matching deprecated Unity API call adjusted as well.
=> Move WMR camera warning into correct scope

Assets/MRTK/SDK/Features/UX/Scripts/Collections/CollectionEnums/LayoutAlignment.cs, Assets/MRTK/SDK/Features/UX/Scripts/Collections/CollectionEnums/LayoutAlignment.cs.meta, Assets/MRTK/SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs, Assets/MRTK/SDK/Inspectors/UX/Collections/GridObjectCollectionInspector.cs, Assets/MRTK/Tests/PlayModeTests/GridObjectCollectionTests.cs, Documentation/ReleaseNotes.md
Allow the user to customize the behavior of the grid layout so that they can choose how the elements in the grid are aligned, whether they are aligned in the center or along the left/right axis (top/bottom axis when doing row then column layout)
- Fixes: #6813
=> Allow user to customize alignment of objects in grid layout

Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
This change restores a profiler marker that was accidentally removed during the merge of the development branch into the event_propagation branch.
=> Re-add accidentally removed profiler marker

Assets/MRTK/SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs, Assets/MRTK/SDK/Inspectors/UX/Collections/GridObjectCollectionInspector.cs, Assets/MRTK/Tests/PlayModeTests/GridObjectCollectionTests.cs, Documentation/ReleaseNotes.md
Changed the grid object collection's behavior so that the collection is anchored at the center of the cell in the upper left/upper right/lower left/lower right when in the appropriate mode
Previously: 
Now:
You can also toggle between the old and new behaviors
- Fixes: #7666
=> Adjusted anchor behavior to match unity's layout group behavior

Documentation/Contributing/CodingGuidelines.md
I noticed, when reviewing our naming conventions during some PR reviews, that we have some older guidance that doesn't really match the current state of the repo.
From my best attempt at regexing as many syntaxes as I could think of:
Examples of PascalCase `private static readonly` fields: 611
Examples of camelCase `private static readonly` fields: 104
Examples of UPPER_SNAKE_CASE `private static readonly` fields: 7
Examples of PascalCase `private` properties: 95
Examples of camelCase `private` properties: 11
Recommended while reviewing:
Or press this link:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7684/files?diff=unified&w=1
=> Update coding guidelines to match current state of the repo

Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputSimulationProfile.asset, Assets/MRTK/Services/InputSimulation/ManualCameraControl.cs, Documentation/ReleaseNotes.md
Untied the camera movespeed from the frame rate.
Adjusted the camera's movespeed accordingly
Changed the fast control key from Right Ctrl to Right Shift so the user can't accidentally call Ctrl + S
- Fixes: #7692
=> Input Simulation camera movespeed and profile adjustment

Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs
Fold in Playspace transform into hand mesh display to accommodate teleport.
The transforms for the hand meshes are missing the Playspace transform. Therefore, after teleport the hand meshes will appear in the wrong place. This fixes that.
Folds in a missing transform in WindowsMixedRealityArticulatedHandDefinition, following the pattern elsewhere in the code (e.g. WindowsMixedRealityArticulatedHand).
- Fixes: #7697.
Note that the performance cost is negligible, resulting in only a transform concatenation per mesh. This addition appears to just correct an easy to miss oversight. No architectural or otherwise significant changes are needed.
Note that I don't have context to know if this fix relates to new XR SDK surface, or whether it should. I've only tested and validated on the legacy …
=> Fold in Playspace transform into hand mesh display

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs, Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Adds a `WindowsMixedRealityUtilities.SpatialCoordinateSystem != null` check before passing it into `SpatialPointerPose.TryGetAtTimestamp`. In certain scenarios, like running in the editor without a headset attached, the app won't launch into the full holographic view and we won't have a valid spatial coordinate system.
- Fixes: #7698
=> Add WindowsMixedRealityUtilities.SpatialCoordinateSystem null checks

Assets/MRTK/SDK/Features/Utilities/Migration/Tools/MigrationTool.cs, Assets/MRTK/SDK/Inspectors/UX/ManipulationHandler/ManipulationHandlerInspector.cs, Assets/MRTK/Tests/EditModeTests/Experimental/MigrationToolTests.cs, Assets/MRTK/Tools/MigrationWindow/MigrationWindow.cs
On Migration Window, when trying to migrate entire project using the "Add Full Project for Migration" button, Migration tool lists all files of the project which is not a great user experience, as it's uncertain to the user if all their files will be affected by the upgrade.
It would be better to just list the files that actually contain the components we're planning to upgrade. That would also make the list shorter, make it easier to filter files and give a better overview before pressing the migration button.
This is part of Migration Tool graduation.
Tool goes through object hierarchy checking if migration is supported on any of the hierarchy objects. Only show upgradeable files in that list.
Before:
After:
- Fixes: #7690 .
=> Migration Tool: Only list files in migration tool project option that actually can be migrated

Assets/MRTK/Core/Providers/Hands/ArticulatedHandDefinition.cs, Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionDeviceManagerProfileInspector.cs, Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs, Assets/MRTK/Providers/LeapMotion/LeapMotionDeviceManager.cs, Assets/MRTK/Providers/LeapMotion/LeapMotionDeviceManagerProfile.cs
Added configurable pinch thresholds for a Leap Motion hand. 
| New Inspector | Current Value Appearance |  
|--------|-------|
|    ![PinchConfigure](https://user-images.githubusercontent.com/53493796/80049001-a41d5c00-84c6-11ea-9f43-c1508b374aab.png) | ![LeapPinchAfter](https://user-images.githubusercontent.com/53493796/80048917-720bfa00-84c6-11ea-98a9-8ead7271dd28.gif) |  
- Fixes: #7689 
>
>
=> Configurable pinch/air tap thresholds for Leap Motion

Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs, Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Incorporates suggestion from #7395 to fix bounding box handlers not growing to when the cursor was near them. Also includes refactoring out of date code comments and makes the corners and balls transforms correspond to the actual transforms of the in-editor objects
- Fixes: #7395
=> Fixed bounding box handlers not growing and added unit tests

Assets/MRTK/Core/Inspectors/Setup/MixedRealityEditorSettings.cs, Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs, Assets/MRTK/Core/Utilities/Editor/Preferences/MixedRealityProjectPreferences.cs, Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs, Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs, Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs.meta
This change enables easy configuration of newly installed audio spatializers, for example https://www.nuget.org/packages/Microsoft.SpatialAudio.Spatializer.Unity, by doing the following
1. Check to see if a spatializer is configured
2. Check to see if the configured spatializer is currently installed
3. Check to see if the count of installed spatializers has changed since the last time the project loaded
In the case of 3, it is possible, in some cases, for the collection to have the same count, yet contain different values. Other than scenario 2 failing, this is outside of the current change scope.
Fixes #6897
Opening to the  branch as this is a frequent request from audio focused customers and makes it easy for non-audio focused customers to select the best spatializer for their …
=> Update the configurator to detect an appropriate audio spatializer and respond to changes

Assets/MRTK/Examples/Experimental/Demos/UX/BoundsControl/Scripts/BoundsControlRuntimeExample.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControlTypes.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/BoxDisplay.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/BoxDisplayConfiguration.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/HandlesBaseConfiguration.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/LinksConfiguration.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/RotationHandlesConfiguration.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/ScaleHandlesConfiguration.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/HandlesBase.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Links.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/ProximityEffect/IProximityEffectObjectProvider.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/ProximityEffect/ProximityEffect.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/RotationHandles.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/ScaleHandles.cs, Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/VisualUtils.cs, Assets/MRTK/SDK/Experimental/Features/Utilities/Migration/BoundsControlMigrationHandler.cs, Assets/MRTK/Tests/EditModeTests/Experimental/BoundsControlTests.cs, Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs, Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs.meta, web/version.js
Old BoundingBox is recreating it's rig / handles / boxdisplay / links on every configuration change.
This PR is addressing this problem in BoundsControl.
Every configuration change will now only reload what is absolutely necessary (there's only a few cases where we actually have to recreate gameobjects eg. when we change the prefab of a handle during runtime)
Changes in detail:
- ProximityEffect
- added event to IProximityEffectObjectProvider to inform ProximityEffect whenever objects that the effect is applied to change.
- Visuals
- every configuration change has an event that the corresponding visual logic class subscribes to, handling every configuration change individually and only reloading necessary parts
- DrawTetherWhenManipulating and HandlesIgnoreCollider settings are now part …
=> BoundsControl is no longer recreating the rig on any of the configuration changes

Assets/MRTK/Providers/WindowsMixedReality/XR2018/Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.asmdef, Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs, Assets/MRTK/Services/InputSimulation/InputSimulationService.cs, Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs
Made it so the simulated gaze cursor will no longer appear if articulated hands are in view. Fix is specifically to address regression with holographic emulation in 2018.4
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7715
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7742
=> Gaze cursor now disabled when simulated articualted hands are in view

Assets/MRTK/SDK/Experimental/Dialog/README_Dialog.md.meta
#7740 added some new docs, but looks like one was missing a meta file.
=> Add missing meta for new docs page

scripts/ci/validatecode.ps1
Our AssetRetargetting phase in our CI build depends on all of our code to have a namespace. This isn't checked anywhere during PR validation, which means it's really easy to check in an error like this and then have it fail in a very un-understandable way once things have already been checked in for a while. On particularly crazy days this means that the build will probably get hosed for a while as you don't find out the error until your change has gotten through the queue and has finally run the ongoing CI.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7699
=> Add a namespace validation check to our CI scripts

Assets/MRTK/Tests/EditModeTests/Tools.meta, Assets/MRTK/Tests/EditModeTests/Tools/ExtensionServiceCreatorTests.cs, Assets/MRTK/Tests/EditModeTests/Tools/ExtensionServiceCreatorTests.cs.meta, Assets/MRTK/Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs
The extension service creator has an issue where the destination folder is null if the generated folder doesn't exist at the time of the wizard invocation. It turns out that the wizard is actually creating the folder, but it never re-sets its internal state after generating the default folder, which leads to this bug.
The fix here is to actually force a reconciliation of default folder state after creating the default extension folder.
This also adds a test to verify that it happens. Note that the test doesn't run in all cases - if you already have some local extension generated folder, it will no-op (to avoid blowing away local state). Still, this test should run on CI which will at least ensure that we have coverage of weird stuff happening.
- Fixes: …
=> Extension service creator tool defaults to a null path if Generated/Extensions does not previously exist

Assets/MRTK/Core/Extensions/UnityObjectExtensions.cs, Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs, Assets/MRTK/SDK/Features/Audio/Influencers/AudioInfluencerController.cs, Assets/MRTK/Tests/PlayModeTests/PointerTests.cs
Unity overrides a couple of operators to deal with the managed and native situation of objects. This is problematic when checking an interface for null as it does not take the implementer operators into account.
This PR adds a convenient way to check interfaces for null that have potentially been implemented by MonoBehaviours
I addition, it removes unnecessarily complicated null checks in locations where MonoBehaviours are used anyways
- Fixes: #5981
```
IEnumerator Start()
{
GameObject test = new GameObject("tester", typeof(Test));
ICollection @interface = test.GetComponent<ICollection>();
Destroy(test);
yield return null;
Debug.Log(@interface == null);
Debug.Log(@interface.Equals(null));
Debug.Log(IsNull(@interface));
}
```
=> IsNull check for interfaces

Documentation/Contributing/DocumentationGuide.md, Documentation/GettingStartedWithTheMRTK.md
Adds helpful notice in the tutorial to lower the gizmos size for the HandInteractionExamples.unity scene
Duplicate of this misconfigured PR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7755
=> Getting started gizmos notice

Assets/MRTK/Providers/LeapMotion/Editor/ConfigurationChecker/LeapMotionConfigurationChecker.cs
UltraLeap released a new version of the [Leap Motion Unity Core Assets](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.5.0) recently.
The current MRTK Leap Motion Data Provider only supported the Leap Core Assets version 4.4.0, this PR adds support for 4.5.0 as well.
The largest difference between 4.4.0 and 4.5.0 is the location of the tests directory.  If the 4.5.0 core assets are imported into MRTK, a new test assembly definition is added.
Both 4.4.0 and 4.5.0 will be supported.
- Fixes: #7764 
1. Download the [Leap Motion Unity Core Assets 4.5.0](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.5.0)
2. Import the package into either Unity 2019.3 or 2018.4
=> Add support for Leap Motion Core Assets version 4.5.0

Assets/MRTK/SDK/Experimental/HandCoach/README_HandCoach.md, Assets/MRTK/SDK/Features/UX/Interactable/README.md
There are a couple last broken images in the docs, and I want to fix these up so that I can then enable broken image detection on the Assets/ folder as well.
For a little background, I added some build infra a while back to detect broken images which would check all markdown files under the Documentation/ folder - this was because we would keep getting messages (not OFTEN but still enough that it's not great) that we had broken image links. Unlike doc links, docfx doesn't actually check for validity of linked images.
However, this was only enabled on Documentation/ because we really only put docs there - since that work went in, folks have been taking the process of putting docs for experimental features next to the code in the Assets/ folder.
After this I can enable the Assets/ folder to …
=> Fix the remaining broken image links in the documentation

Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityCameraSettingsProfile.cs, Documentation/CameraSystem/WindowsMixedRealityCameraSettings.md
Adds sample code and more information on the HL2 holographic reprojection method setting and how to change it at runtime.
Also removed a reference to "depth reprojection" in the setting, where the setting could be planar reprojection or autoplanar reprojection as well.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7718
=> Update HL2 holographic reprojection docs

Assets/MRTK/Services/InputSimulation/InputSimulationService.cs, Assets/MRTK/Services/InputSimulation/SimulatedHandDataProvider.cs, Assets/MRTK/Services/InputSystem/FocusProvider.cs, Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs
Fixes regression where the gaze cursor could still show up with articulated hands present. Also fixed edge case where gaze cursor would remain on the screen if hands were spawned while near an interactable 
Old broken behavior
New behavior
- Fixes: #7742
=> Fixed regression with the ggv pointer persisting when hands are up

Assets/MRTK/Providers/WindowsMixedReality/Shared/DotNetAdapter/DotNetAdapter.csproj, Assets/MixedReality.Toolkit.Foundation.nuspec
This change instructs MSBuild for Unity to the latest version, as of 2020-05-04. This version adds new functionality.
=> Update min version of DotNetWinRT to latest (0.5.1049)

Assets/MRTK/SDK/Features/UX/Scripts/Tooltips/ToolTipSpawner.cs, Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PrefabSpawner.cs, Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PrefabSpawner.cs.meta
ToolTipSpawner has a lot of logic that's generally interesting for GameObjects in total. But it currently only allows to spawn ToolTips specifically.
This PR extracts the basics into its own class to make them reusable for anything.
- Fixes: #7769
=> Extract ToolTipSpawner timed/type visualization capabilities

Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs
This change fixes #7782 and now correctly configures the project to not use an audio spatializer.
When selecting None in the configurator, the following message is now logged to the console and the appropriate value of null is configured as the audio spatializer.
"No spatializer was specified. The application will not support Spatial Sound."
=> Properly handle user selecting None for the spatializer

Assets/MRTK/Core/StandardAssets/FontsSDFTextures/seguisb SDF zwriteOff.asset, Assets/MRTK/Core/StandardAssets/FontsSDFTextures/seguisb SDF zwriteOff.asset.meta, Assets/MRTK/Core/StandardAssets/FontsSDFTextures/seguisb SDF.asset, Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUI.prefab
Unity UGUI Dropdown from Hand Interaction Example scene displays a visual zfight glitch. This is regression from release branch.
1. Make a fresh clone of  mrtk's prerelease/2.4.0_stabilization branch
2. Change build platform settings to Universal Windows Platform
3. Import TMPro essencial resources
4. Issue can be seen in the editor , WMH or after building and deploying to a HL1 device
Options on UGUI dropdown should appear clearly without visual glitches
2.4 Stabilization before fix:
2.4 Stabilization after fix:
- Unity Version  2018.4.12f1 and 2019.3.0f6
- MRTK prerelease/2.4.0_stabilization
- HoloLens1
- Unity editor 2018.4.12f1
- Unity editor 2019.3.0f6
- WMR headset
Changed zwrite on Font material from seguisb SDF.asset used on text right above dropdown element.
Fixes #7745
=> UGUI dropdown zfight visual glitch

Documentation/InputSimulation/InputSimulationService.md
The input simulation documentation wasn't clear that toggling the hands on was not the same as being able to manipulate them, so the updated documentation tries to be more clear on that language.
=> Clarified Toggle button functionality for input simulation

Assets/MRTK/Core/StandardAssets/FontsSDFTextures/seguisb SDF zwriteOff.asset
Unity keeps updating this asset's serialized name to match the file name whenever I open the project.
=> Update asset name to match filename

Assets/MRTK/Services/InputSystem/Editor/MixedRealityCanvasInspector.cs
Removed some duplicated canvas inspector code which was causing exceptions in some cases due to reflection. The vast majority of the code removed is now handled by asking Unity to create an editor instance for the canvas, which makes this code more robust to future Unity changes as well. Some MRTK-specific code was previously inserted in-line (mostly around disabling / not displaying certain fields in certain cases), which is no longer possible, but additional inspector warnings and context-specific configuration buttons were added for those cases (world space only for MRTK canvases and no camera should be set).
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7522
=> Fix canvas inspector exception with screen space canvases

Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs, Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs, Assets/MRTK/Examples/Demos/Gltf/Scripts/TestGlbLoading.cs
This [PR](https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7527) has moved the access to DownloadHandler text and data to the Response object, adding an action that can be executed only when text from response is really needed (saving performance cost of unecessary DownloadHandler data conversion).
Most of methods inside DevicePortal.cs (used bu Build Window buttons ) use the text property from rest calls Response Data but most UnityWebRequests objects are initialized inside a using scope from Rest.cs. DevicePortal.cs methods cannot access delegated methods from download handler destroyed when out of the initialization using scope.
This regression Issue can be seen when trying to communicate with Hololens device through Build Window or when playing the Glb Loading Demo. 
The …
=> Fixing Build Window access of Response Data 

Assets/MRTK/Core/Inspectors/Utilities/MixedRealityStylesUtility.cs, Assets/MRTK/Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs
Currently, the optimize window isn't respecting the editor theme with its titles:
this updates it to use a built-in theme as its base, so the color is inherited and managed by the editor:
=> Update Optimize Window UI to respect editor theme

Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Unity 2019.3.8f1 does not respond after attempting to switch to UWP from Standalone.
Destroying GameObjects immediately is not permitted during physics trigger/contact, animation event callbacks or OnValidate. You must use Destroy instead.
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene_Injected(Scene&)
UnityEditor.SceneManagement.EditorSceneManager:ClosePreviewScene(Scene)
UnityEditor.PreviewScene:Dispose()
UnityEditor.PreviewRenderUtility:Cleanup()
UnityEditor.MaterialEditor:OnDisable()
UnityEngine.Object:DestroyImmediate(Object, Boolean)
UnityEngine.Object:DestroyImmediate(Object)
UnityEditor.AssetPreviewUpdater:CreatePreviewForAsset(Object, Object[], String)
UnityEditor.AssetDatabase:Refresh(ImportAssetOptions)
UnityEditor.AssetDatabase:Refresh() …
=> Unity freezing when changing to UWP

Assets/MRTK/Core/Services/BaseDataProviderAccessCoreSystem.cs, Assets/MRTK/Examples/Demos/Gltf/Scripts/Editor/TestGltfLoadingEditor.cs, Assets/MRTK/Extensions/LostTrackingService/Editor/LostTrackingServiceInspector.cs, Assets/MRTK/SDK/Inspectors/UX/ManipulationHandler/ManipulationHandlerInspector.cs, Assets/MRTK/SDK/Inspectors/UX/VisualThemes/StatesInspector.cs, Assets/MRTK/SDK/Inspectors/UX/VisualThemes/ThemeInspector.cs, Assets/MRTK/Services/InputSystem/Editor/NearInteractionTouchableVolumeInspector.cs, Assets/MRTK/Services/InputSystem/Editor/NearInteractionTouchableVolumeInspector.cs.meta, Assets/MRTK/Services/InputSystem/NearInteractionTouchableVolume.cs
While looking into the number of `#if` defines we have (which has a direct effect on the number of different assemblies we need to build and support), I realized we have some extraneous `#if UNITY_EDITOR` defines. I resolved least impact defines here. The three cases this PR fixes:
1. Remove editor defines in editor-only assemblies
1. Refactor out custom inspectors into editor-only assemblies
1. Remove an unused UnityEditor namespace
There will likely be a few follow up PRs in the coming weeks.
=> Reconcile some unneeded #if UNITY_EDITOR defines

Assets/MRTK/Services/InputSystem/GazeProvider.cs, Documentation/ReleaseNotes.md, Documentation/Updating.md
Both the Release Notes and Updating guidance are missing info about how to upgrade old eye tracking api calls to new ones. There is also no updating guidance on changes of setup eye tracking.
This PR updates documentation about Eye gaze/ tracking setup and api for 2.4.
- Fixes: #7808 .
=> Adding eye gaze changes to release and updating notes

Assets/MRTK/SDK/Experimental/Dialog/README_Dialog.md, Assets/MRTK/SDK/Experimental/HandCoach/README_HandCoach.md, Documentation/README_MRTKStandardShader.md, Documentation/README_TextPrefab.md, scripts/ci/validatedocs.ps1
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7849
Our docs contain a few broken links, which are broken for a few reasons:
1. They are actually wrong (i.e. they are absolute relative to the root, rather than relative to the current folder).
1. There are some links that reference the Asset root (i.e. /Assets) which won't resolve correct on github.io - for the safety of ensuring that links will actually work on github.io we essentially have to ensure that we use relative paths for docs, forcing a check that you aren't using an absolute path.
Note that this allows the usage of "/Assets" because some of our docs (experimental ones) don't actually get published to github.io (and thus, these are valid from those locations)
This is kinda a workaround (i.e. ideally docfx would …
=> Fix broken links that use incorrect absolute paths and prevent regressions going forward

Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs
Allowed spatializer to be unset when checking settings, preventing the configurator from opening every time
- Fixes: #7332
Tested by creating new c# scripts and ensuring that the dialog didn't come up again and that the particular code path was hit.
=> Allow Spatializer to be set to None for the MRTK Project Configurator

Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs, Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs, Assets/MRTK/SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs, Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
This change fixes the controller and pointer errors reported in #7796 by partially reverting #6939.
It also prevents duplicate source detected/lost events from attempting to modify the controllers collection, which would result in errors / exceptions from the runtime.
Details on what was happening before this change.
The timing changes caused by awaiting the controller model was resulting in the following failure path:
1. The platform raises a source detected event
2. Pointer and cursor MonoBehaviours are instantiated
3. Input source is created
4. Controller object is created
5. Controller waits for the model to load
6. Update is called on the MonoBehaviours
7. Teleport cursor checks for the teleport pointer and fails to find it,
8. Teleport cursor deletes itself
9. The focus provider …
=> Fix for controller and pointer errors in VR (#7796)

Assets/MRTK/Core/Services/MixedRealityToolkit.cs
MixedRealityToolkit is throwing error message when using Migration Window from a scene without MixedRealityToolkit instance.
The Migration tool opens and closes scenes in the project. during this process, OnValidate is called from MixedRealityToolkit.cs on every scene containing an instance. The function DelayOnValidate() is only called when scene is changed, sending null value with RegisterInstance(this).
1. Open a new empty scene
2. Open Migration Window
3. Select "ObjectManipulatorMigrationHandler"  from dropdown list
4. Navigate to full project section
5. Click on "Add full project for migration"
6. An error message is displayed on the console
- Unity Version 2018.4.12f1
- MRTK Version 2.4
- Fixes: #7867.
=> Fixing MixedRealityToolkit null error on Register

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Currently, there's a bug in the hand tracking implementation that's preventing hand joints from having a correct rotation. The `if (x || y)` statement short circuits the `y` call, and so rotation is never actually read. 😳
=> Fix joint rotations not working with XR SDK

Assets/MRTK/SDK/Experimental/Features/Utilities/Migration/BoundsControlMigrationHandler.cs, Assets/MRTK/SDK/Features/Utilities/Migration/ObjectManipulatorMigrationHandler.cs, Assets/MRTK/SDK/Features/Utilities/Migration/Tools/MigrationTool.cs, Assets/MRTK/Tests/EditModeTests/Experimental/MigrationToolTests.cs
Migration Tool does not migrate inactive objects from selected scenes or prefabs.
1. Open Migration Window
2. Select ObjectManipulator migration from the dropdown
3. Drag the HandInteractionExample.unity into the scene section
4. Press migrate
Observe that the gameobject node_id30 has not been upgraded
objects to list of objects to be migrated
- Fixes: #7863 .
=> Migration Window: Adding inactive objects to migration list

Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Reverted a change that prevented the hand mesh from updating and reappearing after being toggled
- Fixes: #7871
Verified by manually deploying to HoloLens 2 and testing that the hand mesh would reappear
=> reverted hand mesh change so it reappears on toggle

Documentation/toc.yml
The push of the commit that added the new configuration dialog page to the table of contents failed due to a command line typeo.
This change adds in the missing contents link
=> Update table of contents to add the new configuration dialog page

Assets/MRTK/Providers/LeapMotion/Editor/ConfigurationChecker/LeapMotionConfigurationChecker.cs
The Leap Motion menu always appeared a the top under the Mixed Reality Toolkit > Utilities menu.  It was always at the top because the priority was 0, this pr removes the priority from the MenuItem.
BEFORE:
AFTER:
=> Remove priority from Leap Motion menu

Documentation/BuildAndDeploy.md
Selecting ARM as the build architecture in Unity 2019.3.x results in a fails to deploy to a HoloLens device.  A note has been added to the Build and Deploy doc for HL and HL2 devices to use ARM64 instead of ARM for Unity 2019.
- Fixes: #7858
=> Update Build and Deploy HoloLens Guidance Doc

Assets/MRTK/Core/Services/BaseBoundarySystem.cs, Assets/MRTK/Core/Services/BaseEventSystem.cs, Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs, Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs
Fixes the lack of floor and boundary when running an XR SDK app on-device.
The root issue was that the `XRDevice.isPresent` API is [not expected to work in XR SDK](https://forum.unity.com/threads/xrdevice-ispresent-with-xrmanagement-on-quest.817722/). This PR removes that call from the base class and replaces it with the corresponding XR SDK API call. The existing non-XR SDK service implementation already called this API, so it's left unchanged.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/9359fd71bac5bbcfe8db0803f0083e6f012f31a6/Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs#L35
I also removed the `UnityBoundary.visible = true;` call, which was causing issues on Oculus and is not configurable in MRTK. There is no corresponding API in XR SDK, so …
=> Fix XR SDK boundary on-device

Assets/MRTK/Core/Utilities/Editor/SizeUtilities.cs
removed debug menu entries from GameObject top menu (MRTK > Renderer Size , MRTK > Collider Size)
fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7864
=> removed debug menu entries

Assets/MRTK/Providers/WindowsMixedReality/Shared/Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.Shared.asmdef, Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Microsoft.MixedReality.Toolkit.Providers.XRSDK.WMR.asmdef
Although the WMR XR SDK data provider is already marked to work on Windows Standalone, the assemblies aren't actually included in the build. This fixes that, to unblock controller input on a WMR Windows Standalone build.
- Part of #7905
=> Update WMR XR SDK assemblies to include Windows standalone

Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Unplated.prefab, Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonConfigHelper.cs, Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs, Assets/MRTK/SDK/Features/Utilities/Migration/ButtonConfigHelperMigrationHandler.cs, Assets/MRTK/SDK/Features/Utilities/Migration/ButtonConfigHelperMigrationHandler.cs.meta, Assets/MRTK/SDK/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
(New branch based on #7886 to ensure a clean merge.)
Provides tools to migrate from old material-based custom icons to icon sets. (This PR does not upgrade any buttons in example scenes.)
Previously custom button icons required assigning a new material to the button's quad renderer. This is no longer necessary and we recommend moving custom icon textures into an IconSet. The inspector lets developers know this option exists:
Existing custom materials and icons are preserved. However they will be less optimal until upgraded. An additional warning is shown in the icon selection foldout:
The ButtonConfigHelperMigrationHandler type can migrate all button assets in the project.
If an icon is not found in the default icon set during migration, a custom icon set will be created in …
=> Custom Button Icon Migration Tools

Assets/XR/Loaders/AR Core Loader.asset, Assets/XR/Loaders/AR Core Loader.asset.meta, Assets/XR/Loaders/AR Kit Loader.asset, Assets/XR/Loaders/AR Kit Loader.asset.meta, Assets/XR/Settings/AR Core Loader Settings.asset, Assets/XR/Settings/AR Core Loader Settings.asset.meta, Assets/XR/Settings/AR Kit Loader Settings.asset, Assets/XR/Settings/AR Kit Loader Settings.asset.meta, Assets/XR/Settings/Windows MR Package Settings.asset, Assets/XR/XRGeneralSettings.asset, ProjectSettings/EditorBuildSettings.asset, ProjectSettings/XRPackageSettings.asset
Unity's XR Plugin Management package had a pretty large update for version 3.0, and all previous versions were unpublished. As a result, ARCore and ARKit are now managed via XR Management, so I'm adding those assets. I also recreated the WMR assets from scratch.
For these assets, since they don't exist in 2018.4, they simply state that fact and don't cause issues:
These files are only included in the repo to facilitate XR SDK work on MRTK. They are not distributed in any MRTK package or intended to be used by others, but exist as repo scaffolding.
=> Update XR assets for XR Management 3.0

Documentation/GettingStartedWithTheMRTK.md
Updates the docs by moving the extension package installation instructions ABOVE examples (i.e. since examples depends on extension now, you should install the extension one first)
Also updates the line for the examples package to mention the dependency on extensions.
=> Update the getting started docs to mention that the examples package depends on the extensions package

Assets/MRTK/SDK/Experimental/MixedRealityKeyboardPreview/MixedRealityKeyboardPreview.cs
Per the conversation in #7926, moving the initialization in the mixed reality keyboard preview code to Start(), where the solver handler / solver system would have been initialized by.
Fixes #7926
=> Move initialization to later (when solvers have been initialized)

Assets/MRTK/SDK/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs, Documentation/README_Button.md
Addresses errors and lack of clarity when trying to use the button upgrade migration tool without the tools package
- Fixes: #7950
> Change the material on a button's icon to an invalid one, prompting the upgrade tool, and then verified that the alert showed up properly when the menu item wasn't present
=> Added alerts and documentation to for button migration

Documentation/ReleaseNotes.md
Added the "Duplicate Assembly Version and Multiple Precompiled Assemblies Unity 2018.4" issue to known issues in the release notes and how to work around it.
- Fixes: #7948
=> Add assembly version errors to known issues to release notes 2.4

Documentation/BuildAndDeploy.md
Unity 2019.3 by default does not have the Windows Mixed Reality SDK added in the Player settings. If you switch to UWP and build, you will end up with your HL2 app as a 2D panel on device without these extra steps.
Added a Unity 2019.3 and HoloLens section with steps for legacy XR and the XR-plugin. Also moved the warning about ARM64 to this new section.
- Fixes: #7957
=> Update Build and Deploy documentation with steps for Unity 2019.3

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityEyeSaccadeProvider.cs, Assets/MRTK/Providers/WindowsMixedReality/Shared/BaseWindowsMixedRealityCameraSettings.cs, Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandRecorder.cs, Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs
Cleans up a couple examples of fields or methods not being properly scoped by `#if` blocks and appearing as "unused" in certain build configurations.
Also improved some docs in the files I was updating.
=> Clean up some "unused" warnings

Assets/MRTK/Core/Providers/UnityInput/UnityJoystickManager.cs, Assets/MRTK/Providers/OpenVR/OpenVRDeviceManager.cs, Assets/MRTK/Providers/WindowsVoiceInput/WindowsDictationInputProvider.cs, Assets/MRTK/Providers/WindowsVoiceInput/WindowsSpeechInputProvider.cs, Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6779 introduced the ability to specify a data provider's service type explicitly, but not all data providers were updated with this feature. This PR updates the rest to no longer cast their `Service` to the `IMixedRealityInputSystem` they already are.
=> Remove extra IMixedRealityInputSystem casts

Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs
In doing some research around the perf implications of structs and how MRTK uses them, I came across the fact that passing a struct as an `in` parameter doesn't always reduce the number of copies, but potentially increases them. Instead of copying at the time the struct is passed in, the method ends up copying ANY time a non-readonly property or method is called on the struct.
From https://devblogs.microsoft.com/premier-developer/the-in-modifier-and-the-readonly-structs-in-c/ (emphasis mine):
>To make sure that the parameter’s value stays the same the compiler **make a defensive copy of the parameter every time a method/property is used**.
>
>It means that you should never pass a non-readonly struct as in parameter. It almost always will make the performance worse. Yes, **the argument …
=> Update in param to ref param in BaseInputDeviceManager

Documentation/GettingStartedWithTheMRTK.md, Documentation/ReleaseNotes.md, Documentation/Updating.md
With some of the latest changes to 2.4.0 (i.e. button config helper, BoundsControl/ObjectManipulator), running the migration tool is extremely helpful in ensuring that upgraded projects can get into a good state.
In general, we want to push consumers to use this tooling to help auto-fix as much of their projects as is possible - as we make version to version changes, there's always some inevitable probability around breaking changes (even if the changes are relatively small), but having these changes be auto-fixed is way nicer than having to stumble through weird behaviors (or worse, deploying to device and realizing that something is off, and then trying to walk back from that).
As we add more handlers to this migration tooling, getting consumers in this habit will help ensure that good …
=> Update the upgrade instructions to heavily encourage use of the migration window.

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
The GrabPointer was not grabbing, because its TryGetNearGraspAxis returned bool was false, even though its forward Vector3 is to be considered valid.
- Fixes: #7961 .
=> Changes Controller Axis to valid axis

Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboard.cs.meta, Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboardBase.cs.meta
Swap the GUIDs in the MixedRealityKeyboard.cs.meta and MixedRealityKeyboardBase.cs.meta files to resolve the invalid script for the MixedRealityKeyboard component after an upgrade from 2.3 to 2.4.
- Fixes: #7972 
Confirmed fix by:
1. Importing 2.3 foundation package
2. Created new scene and added MRTK
3. Created empty game object with the MixedRealityKeyboard component attached
4. Closed Unity and followed upgrade steps
5. Imported foundation Unity package that was generated based on this branch
6. Confirmed the script was valid on the game object with the MixedRealityKeyboard component attached
=> Swap GUIDs in MixedRealityKeyboard files

Documentation/GettingStartedWithTheMRTK.md
NuGet packages are no longer supported as of MRTK 2.4.0. This should be clear to users.
- Fixes: Added a note to the NuGet Package comments of the Getting Started page to make it clear that NuGet packages are no longer supported as of MRTK 2.4.0.
=> Added a note about NuGet package support.

Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs, Assets/MRTK/Core/Services/MixedRealityToolkit.cs, Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
This PR:
1. Updates one of the profiler markers to be `static readonly`, which matches the rest of the markers.
1. Updates the MRTK instance access to be discarded, which matches the way we do this for the playspace:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/375f306d0af44e26335297b2fc988f4d612bf787/Assets/MRTK/Core/Services/MixedRealityToolkit.cs#L485-L486
1. Adds `HandTracking` devices to the list of devices we care about from XR SDK. This is because the WMR-plugin currently marks hands as both `HandTracking` and `Controller`, but other don't and it may not in the future if they standardize.
=> Use discard in MRTK access, add missing readonly modifier, add "hand tracking" devices to XR SDK

Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Backspace.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Close.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Dictation.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Down.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Left.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Right.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Shift_Symbols.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_UnShift_Symbols.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/KeyboardKeyGlyphs_Up.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/NonNativeKeyboardSprites.spriteatlas, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/NonNativeKeyboardSprites.spriteatlas.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Icons/Placeholder.png.meta, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Prefabs/NonNativeKeyboard.prefab, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/KeyboardValueKey.cs
The NonNativeKeyboard is using Text compoents instead of TextMeshPro, uses icons without mipmaps instead of with mipmaps and does not create an atlas for the used icons.
This PR fixes all of that, letting users decide if they want to build the atlas or not (since its an editor setting)
- Fixes: #7882 .
=> Improved NonNativeKeyboard

Assets/MRTK/Core/Inspectors/Utilities/MixedRealityStylesUtility.cs
Button rendering in the controller mapping profile is currently broken in Unity 2019:
This PR adds an explicit height value to the `GUIStyle`, which matches the hardcoded height of the button already:
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/6df48e126d779da4d82662b1bb16fb963f2986d0/Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs#L299
=> Fix controller mapping profile rendering in Unity 2019.3

Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs, Assets/MRTK/Tests/PlayModeTests/SlateTests.cs
Slate in HandInteractionExample is jumping in zoom levels when starting interaction with two hands. The issue is more visible when Slate is rotated in a way where hand click and drag only through z axis should trigger a slate zoom.
Changed GetContactDistance() method from HandInteractionPanZoom.cs to account for global z component of hand / controler position.
- Fixes: #7788.
Before:
After:
- MRTK 2.4
- Unity 2018.4
- Hololens 2
=> Fixing slate zoom when slate is rotated around up vector

Assets/MRTK/Providers/LeapMotion/Editor/ConfigurationChecker/LeapMotionConfigurationChecker.cs
When consuming MRTK through NuGet, the LeapMotionConfigurationChecker throw an IndexOutOfRangeException because the asmdef file does not exist. However, this is expected when using compiled NuGet binaries.
The fix here adds a length check, and does not continue configuration if the asmdef is not found in the assets directory.
- Fixes: 8021
=> Make sure to check that the AssemblyDefinition for LeapMotion exists before trying to use it

Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs, Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs, Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs, Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs, Documentation/ReleaseNotes.md
On certain devices, i.e. HoloLens 2, the device portal seems to be forcing SSL and even redirecting HTTP to HTTPS. To omit SSL errors rejecting the self-signed device portal certificates when using the MRTK Build Window Deploy Options tab, an option is added to turn off the SSL Certificate Verification.
This option is per default turned on, so to not alter the default behavior, as disabling SSL Verification may pose a security risk in some instances.
This change also displays the "Use SSL" checkbox for local USB connection, as HoloLens 2 uses a HTTPS connection at `https://127.0.0.1:10443/`.
- Fixes: #6877
=> Add option to omit SSL Certificate Verification for Device Portal

Packages/manifest.json
1.0.21 updated the remoting plugins to 2.1.3, which [fixes some stability bugs that some devs were hitting](https://docs.microsoft.com/en-us/windows/mixed-reality/holographic-remoting-version-history). A selection of changes between the previous version and this one:
> 1. Starting with version 2.1.3 HolographicSpace.CameraAdded is synchronized with pose data coming from the Holographic Remoting Player and users can expect that when a camera is added there is also a valid HolographicCameraPose available for that camera on the the next frame.
> 1. Added support for HolographicCameraRenderingParameters.CommitDirect3D11DepthBuffer.
=> Update WMR Plugin version to 1.0.21

Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboard.cs, Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/TMP_KeyboardInputField.cs, Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/UI_KeyboardInputField.cs, Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/UICollection.cs
Three components used identical `MixedRealityKeyboard` paths, and one was missing the `Scripts` entry in the path.
=> Fix some AddComponentMenu paths

Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs
From https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7989, if OnPointerUp happens during an OnSourceLost, and if the BaseControllerPointer handles the OnSourceLost after MixedRealityInputModule, then OnPointerUp here can throw a KeyNotFoundException.  MixedRealityInputModule should be resilient to the effects other handlers of OnSourceLost, and not throw an exception if the pointer has already been removed.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7989.
=> Ensure that the MixedRealityInputModule.OnPointerUp does not throw a KeyNotFoundException

Documentation/ReleaseNotes.md
Adding a direct download link from the release notes, so that you don't have to navigate some other structure in order to find the MRTK download bits.
I opted to only link to the .unitypackages because those are the core bits needed to start building.
=> Update the release notes to point to where to download the MRTK bits.

Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
We currently have a 2019 CI daily build which is busted for a few reasons (one of which being that we don't have VS2019 on that hosted agent, which is something I'm following up on separately).
Another issue in the code itself is that we look for only a single extension (.vcsproj) instead of both .vcsproj and .vcxproj (vcxproj being the VS2019 extension).
This is one of the (probably many) fixes needed to prep for the 2019 PR pipeline
=> Update the build tools to support VS2019's .vcxproj extension

Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs, Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs, Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs
In `BoundingBox`, you can set a `boundsOverride` collider which essentially provides a "proxy object" to provide the bounds to the `BoundingBox`. There is an optional `boxPadding` that can be applied to this collider, to space out the `BoundingBox` around the object.
Unfortunately, this padding is achieved by destructively resizing the provided `boundsOverride` `BoxCollider`.
In the existing code, there is a line that is intended to compensate for this destructive resizing operation; in `DestroyRig` the code resizes the `boundsOverride` in the _negative_ direction of the padding, effectively cancelling out the previous padding operation.
However, `DestroyRig` is actually called first when we are creating the rig (it's actually included inside `CreateRig`, ironically!), in addition to …
=> Bounds override fix

Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs, Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs, Assets/MRTK/SDK/Features/Utilities/Smoothing.cs, Assets/MRTK/SDK/Features/Utilities/Smoothing.cs.meta, Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs
Updates the rotation calculation method in `BoundsControl` to use an init-rotation method, instead of the per-frame method that was being used before.
- Before: a single-frame delta would be obtained from the controller/pointer position, and this single-frame delta would be applied to the object each frame, many times.
- Now: In the same way that the scale handles are calculated, an initial rotation is first calculated, and then a **_full_** delta is calculated, from the init rotation all the way to the current intended rotation. The object's rotation is then set according to this delta.
**Motivation for this change: ** the per-frame method actually induces a significant amount of error during rotations. Due to inherent jitter and imprecision in how the hand/pointer positions are …
=> Updated BoundsControl rotation calculations + lerp/smoothing

Assets/MRTK/Core/Inspectors/Utilities/MixedRealityInspectorUtility.cs, Assets/MRTK/Services/InputSimulation/Editor/InputSimulationWindow.cs
In support of #8058, this PR updates a few cases where textures attempt to load by path, and it's assumed the path is in `Assets`. Though, when consuming MRTK via UPM, those paths don't resolve correctly.
Using Unity's APIs and consistent GUID references allows these textures to be loaded regardless of where the file is located.
=> Update some textures to load by GUID

Assets/MRTK/Services/InputSimulation/Editor/InputSimulationWindow.cs
Currently, the button stays with the "play" icon even while playing:
the repo's icon set contains a pause button, so I updated the script to load it and display it when relevant:
Also, formatting.
=> Update InputSimulationWindow to show pause button

Documentation/ReleaseNotes.md, scripts/packaging/unitypackage.ps1
The TestUtility refactor that @CDiaz-MS did a while back added some cool NuGet package for the MRTK test infrastructure. This has been used internally by a few teams to build out their test infra, and up until now we haven't had a .unitypackage equivalent.
This PR publishes the core set of test infrastructure that the MRTK itself uses to write integration tests, things like:
1. Show hand there.
2. Pinch
3. Move hand over there.
4. Release
This lets you write automated tests that interact with things in your scene, so that instead of having to do manual test passes, you can have automated (i.e. CI-time) coverage of core/common things. The tests that we've written have helped us avoid regressions in components and to prove functionality, and it's like that consumers will also be able to …
=> Add a .unitypackage for MRTK's TestUtilities

Assets/MRTK/Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MRTK/Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MRTK/Providers/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MRTK/Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MRTK/Tests/TestUtilities/MixedReality.Toolkit.Tests.Utilities.nuspec, Assets/MRTK/Tools/MixedReality.Toolkit.Tools.nuspec, Assets/MixedReality.Toolkit.Foundation.nuspec
This change reverts https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6618 to enable source debugging of NuGet packages.
Note that this makes any generated nuget packages not work with Nuget4Unity (which we haven't supported from 2.4 and on). This primarily affects anyone who has stood up their own internal build/nuget pipeline to build their own packages. For those folks you'd have to strip out the sources (i.e. revert this revert)
Ideally we would actually use a different mechanism for source debugging (i.e. maybe something like https://devblogs.microsoft.com/nuget/introducing-source-code-link-for-nuget-packages/), but this is a cheap way of unblocking other work.
=> Re-enable source debugging for the nuget packages

Assets/MRTK/Examples/MixedReality.Toolkit.Examples.nuspec, Assets/MRTK/Extensions/MixedReality.Toolkit.Extensions.nuspec, Assets/MRTK/Providers/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec, Assets/MRTK/Tests/MixedReality.Toolkit.Tests.nuspec, Assets/MRTK/Tests/TestUtilities/MixedReality.Toolkit.Tests.Utilities.nuspec, Assets/MRTK/Tools/MixedReality.Toolkit.Tools.nuspec
From the MRTK folder rename, a new layer of folders was added. Not all of the .nuspec files were updated for the lines that were uncommented in #8074.
=> Add new layer to nuspec files to fix build

Assets/MRTK/Core/Extensions/BoundsExtensions.cs, Assets/MRTK/Tests/EditModeTests/Core/Extensions/BoundsExtensionsTests.cs, Assets/MRTK/Tests/EditModeTests/Core/Extensions/BoundsExtensionsTests.cs.meta
Add optional parameter to BoundsExtensions.ComputeBoundsPoints to compute bounds relative to another transform.
Also create a new test file for BoundsExtensions, and add two small tests to BoundsExtensions, including one to verify this change.
- Fixes: #8089
=> BoundsExtensions compute bounds relative to another transform
