pipelines/templates/ci-common.yml

Cherry-pick ci template fix from the mrtk_development branch

fix typo in ci template

---

Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorView.md
Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewArchitecture.md
Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewArchitectureOld.md
Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewDebugging.md
Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewDebuggingOld.md
Assets/MixedRealityToolkit.Extensions/SpectatorView/SpectatorViewOld.md
README.md

Add deprecation stubs to md files

---

Documentation/ServiceUtilities/MixedRealityServiceRegistryAndIMixedRealityServiceRegistrar.md
Documentation/toc.yml

This document strives to answer the questions:
- What are the MixedRealityServiceRegistry and IMixedRealityServiceRegistrar?
- Why two?
- How are they related?

Add conceptual docs on service registry and registrar

---

Documentation/Architecture/CrossPlatform/DeterminingPlatformCapabilities.md
Documentation/toc.yml

Add architecture / conceptual document for checking platform capabilities.

add platform capability check doc

---

.gitignore
NuGet/BuildSource.proj

This change fixes the missing BuildSource.proj file.

Checking in Missing BuildSource.proj file

---

Assets/MixedRealityToolkit.Services/InputSystem/MixedRealityInputSystem.cs
Assets/MixedRealityToolkit.Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Assets/MixedRealityToolkit/Services/BaseDataProviderAccessCoreSystem.cs

This change cherry-picks the fix for #5557 from the stabilization branch

Fix 5557 - Hand / controller input broken (cherry-pick 5561)

---

Assets/MixedRealityToolkit/StandardAssets/Shaders/MixedRealityStandard.shader

When enabling Normal Maps and Proximity Light on a MRTK/Standard material the MRTK/Standard shader fails to compile. This PR moves normal calculation above proximity light calculation so that world normals are accessible.
Thank you @railboy for finding this!
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5573
Please review the MaterialGallery and other example scenes.
>
>
>

Fixing MRTK/Standard Shader Normal Maps + Proximity Light Compilation Error

---

Assets/MixedRealityToolkit.Examples/Demos/Audio/Scenes/AudioOcclusionDemo.unity
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-00-RootScene.unity
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-02-TargetSelection.unity
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-03-Navigation.unity
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-04-TargetPositioning.unity
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-05-Visualizer.unity
Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Glb-Loading-Demo.unity
Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Gltf-Loading-Demo.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/PalmUpHandMenu.prefab
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionGestureEventsExample.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Scenes/HandInteractionUnityUIExample.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Dictation/Dictation.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/HandJointChaserExample.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputActions/InputActionsExample.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/PointerResult/PointerResultExample.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerExample.unity
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/Speech/Speech.unity
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/ClippingExamples.unity
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/MaterialGallery.unity
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/StandardMaterialComparison.unity
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/StandardMaterials.unity
Assets/MixedRealityToolkit.Examples/Demos/UX/Collections/Scenes/ObjectCollectionExamples.unity
Assets/MixedRealityToolkit.Examples/Demos/Utilities/InspectorFields/Scenes/InspectorFieldsExamples.unity

Continuation of my work on #5352 ,#5430, #5588, and #5581 preparing for release.
This is a first pass of the scenes, committing the ones that only had things moved around or changes external to MRTK (mostly Text Mesh Pro). I wanted to take a closer look at some changes in the other scenes but get this out first.
Reserialized using Unity 2018.4.2f1.
- Continuation of #4914

Reserialize scenes (first pass)

---

pipelines/ci-release.yml
pipelines/templates/releasesigning.yml

Nial Milsom and I suspect that the task is currently in the incorrect job - this PR updates it to match the requirements.

Move Component Governance task to the job responsible for signing

---

Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Prefabs/PressableRoundButton.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Unplated.prefab
Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs

Fix #5576: Adjusted press start/max/release distance in the button prefabs. 
Fix #5583: Moved audio feedback from PressableButton to Interactable to support near and far interactions.
This base prefab PressableButtonHoloLens2Unplated update will update other button prefab variants.
*Small offset from the backplate (Max Push Distance) is intentional per shell design spec.

Button prefab fix - press distance(#5576), audio for far interaction(#5583)

---

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs

The button's position calculation simply did not start with position.x
- Fixes: #5099.

Fixing position of the "Try Repair" button

---

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs

This cherry-picks @alexees' change from mrtk_dev to stabilization, to ensure this gets into GA.
- Fixes: #5099

Cherry-pick #5601 to stabilization

---

Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/OnSelectVisualizerInputController.cs
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputPlayback.cs
Assets/MixedRealityToolkit.Examples/Demos/EyeTracking/General/Scripts/Targeting/DwellSelection.cs
Assets/MixedRealityToolkit.Examples/Demos/HandTracking/Script/SystemKeyboardExample.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBarButton.cs
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableInspector.cs
Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/TemplateFiles.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MixedRealityToolkit/Inspectors/Utilities/Lines/DataProviders/ParabolicConstrainedLineDataProviderInspector.cs
Assets/MixedRealityToolkit/Inspectors/Utilities/Lines/DataProviders/SimpleLineDataProviderInspector.cs

Some of our build steps were generating warnings. This fixes them! And some formatting.
For some reason, these didn't show up in our "normal" build steps, just in some of the later steps.

Fix build warnings

---

ProjectSettings/ProjectVersion.txt

Updating Unity version to the latest LTS 2018.4.6f1

Updating Unity version to the latest LTS 2018.4.6f1

---

Assets/MixedRealityToolkit.SDK/Profiles/HoloLens1/DefaultHoloLens1ConfigurationProfile.asset

Make HL1 config point to HL1 input, camera profiles

---

Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedHand.cs

Fix broken html tags in docomments.

Fix html tags in SimulatedHandData docs.

---

Documentation/InputSimulation/InputSimulationService.md

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5071
The input simulation code supports eye tracking simulation, adding it here!

Update supported interactions of the input simulation docs

---

Documentation/GettingStartedWithTheMRTK.md

Added section about how to use the hand input simulation in GettingStartedWithTheMRTK.md. The section describes the basics in scene navigation and using the hand input simulation.
- Added section to GettingStartedWithTheMRTK.md

Added section to GettingStartedWithTheMRTK.md about using hand input simulation 

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

Cherry-pick #5711 into stabilization

fixed bounds calculation (#5711)

---

Documentation/BuildAndDeploy.md
Documentation/Contributing/CONTRIBUTING.md
Documentation/GettingStartedWithTheMRTK.md
Documentation/toc.yml

Cherry pick docs #5720

---

Documentation/GettingStartedWithTheMRTK.md

Fixed link by deleting blank space in GettingStartedWithTheMRTK.md

Link fix in GettingStartedWithTheMRTK.md

---

Documentation/Contributing/UnitTests.md

I tried using the template, and one thing that didn't work was that Setup was incorrectly capitalized - it should be SetUp.

Update the play mode test template to have the correct [SetUp] attribute

---

web/version.js

files already moved on github pages branch

adjusted version dropdown (prerelease to release)

---

Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/Profiles/DefaultObjectMeshObserverProfile.asset
Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MixedRealityToolkit.SDK/Inspectors/Input/Handlers/ControllerPoseSynchronizerInspector.cs
Assets/MixedRealityToolkit.SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset
Assets/MixedRealityToolkit/Extensions/EditorClassExtensions/EditorLayerExtensions.cs
Assets/MixedRealityToolkit/Extensions/EditorClassExtensions/EditorLayerExtensions.cs.meta
Assets/MixedRealityToolkit/Extensions/LayerExtensions.cs
Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/PhysicsLayerAttributeDrawer.cs
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Assets/MixedRealityToolkit/Utilities/Editor/Microsoft.MixedReality.Toolkit.Editor.Utilities.asmdef
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityEditorSettings.cs

This changes fixes some minor configurations and editor behavior issues.
- Fix isCustomProfile to false for DefaultSpatialAwarenessSystemProfile
- Fix check for SpatialAwareness layer 31
- Fix HelpURL and documentation inspector button for pointers
- Fixes: #5679 , #5680 , #4648 
All tests passed
>
>

Minor Editor/Config level fixes

---

Assets/MixedRealityToolkit.Examples/MRTK.Examples.sentinel.meta
Assets/MixedRealityToolkit.Extensions/MRTK.Extensions.sentinel.meta
Assets/MixedRealityToolkit.Providers/MRTK.Providers.sentinel.meta
Assets/MixedRealityToolkit.SDK/MRTK.SDK.sentinel.meta
Assets/MixedRealityToolkit.Services/MRTK.Services.sentinel.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitFilesTests.cs
Assets/MixedRealityToolkit.Tests/MRTK.Tests.sentinel.meta
Assets/MixedRealityToolkit.Tools/MRTK.Tools.sentinel.meta
Assets/MixedRealityToolkit/MRTK.Core.sentinel.meta
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs

Cherry-picking https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5603
This is one of the changes needed to get NuGet packages to work well end-to-end.

Cherry pick pull/5603 into 2.0.1

---

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs

This brings in the PR 5589 change into 2.0.1 branch.

Chery-Pick of PR 5589 into 2.0.1

---

Documentation/MixedRealityConfigurationGuide.md

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5790
There's a duplicated sentence where one shouldn't be! Oh my

Remove a stray duplicate sentence from the configuration guide

---

Documentation/Input/Pointers.md

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5269

Update the docs to provide guidance on how to increase the maximum pointer extent

---

Documentation/ReleaseNotes.md

The upgrade instructions need to be correct in the release branches, so cherry picking to the various current branches.

Cherry pick PR #5813 into the 2.0.1 stabilization branch

---

Documentation/ReleaseNotes.md

Cherry pick this into the release/2.0.0 branch, because docs are generated out of this and the upgrade instructions should be correct.

Cherry pick PR #5813 to releases/2.0.0

---

Documentation/ReleaseNotes.md

Cherry pick this into the mrtk_release branch so that people who are looking at the default code branch will have the right instructions

Cherry pick PR #5813 to mrtk_release

---

Assets/MixedRealityToolkit.Examples/Experimental.meta

just a missing meta file from the Experimental folder missing

missing meta file

---

Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildTemplates/SDKProjectTemplate.csproj.template

This brings over the build fix into the 2.0.1 release.

Cherry-Pick Build fix into 2.0.1 Release

---

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs
Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs.meta

This change fixes the DLL Guid issue for the Plugins being imported, as well as an issue with scripted
importers.

Fix NuGet Related Bugs

---

Assets/MixedRealityToolkit.Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs
Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs.meta

I am bringing the NuGet fixes I made in mrtk_development.

Cherry Pick the NuGet Fixes

---

Assets/MixedRealityToolkit/Attributes/MixedRealityExtensionServiceAttribute.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs

This brings in David's spatial mesh observer fix.

Cherry-Picking David's Fix

---

Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs

This is a small mistake that I made.

Fixing a bug in Re-Import

---

Assets/MixedRealityToolkit/Utilities/Editor/ScriptedImporterAssetReimporter.cs

This is a very simple bug fix.

Cherry-Picking Simple Bug Fix

---

Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/segoeui SDF.asset
Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/segoeuib SDF.asset
Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/segoeuil SDF.asset
Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/segoeuisl SDF.asset
Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/seguibl SDF.asset
Assets/MixedRealityToolkit/StandardAssets/FontsSDFTextures/seguisb SDF.asset

These files keep reserializing themselves (I've heard from a few others as well).

Reserialize segoe assets

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/MixedRealityToolkitTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/BaseTestExtensionService.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/BaseTestExtensionService.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/ITestExtensionService2.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/ITestExtensionService3.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/ITestExtensionService3.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestExtensionService2.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestExtensionService3.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestExtensionService3.cs.meta
Assets/MixedRealityToolkit/Services/MixedRealityToolkit.cs
Assets/MixedRealityToolkit/Utilities/MixedRealityServiceRegistry.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5942
The core MRTK update loop was allocating a new List<> (actually, two, if you look at both Update and LateUpdate). This is because each call to MixedRealityServiceRegistry wasn't being cached. In addition, LINQ adds its own GC overhead (i.e. after re-creating the same identical list, the same list was then sorted again... and again... and again...)
This change avoids that by updating the GetAllServices call to return a cached list of services, which are sorted in priority order. That way the MRTK instead of having to re-copy and resort, can just use the same list on every single frame.
I had also considered keeping the original "sort order" (i.e. random, or actually, insertion order into the registry) but we never formally …

Update the MRTK runtime to not allocate a new list on each Update loop.

---

Documentation/README_MRTKStandardShader.md

Fix typo on README_MRTKStandardShader.html

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Utilities/ToggleHandVisualisation.cs

While I was looking through this class, I updated some documentation, explicit method visibility, and method name casing.

Update formatting and method casing in ToggleHandVisualization

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5968
The issue here is that the facades themselves are persisted to disk when saving (because they are just game objects that exist in the scene)
This change makes it so that the act of saving will cause us to delete those facades (and then also not generate new facades until the save has completed).

Duplicated service displayed under MixedRealityToolkit hierarchy (Service Inspector)

---

scripts/test/run_playmode_tests.ps1

This allows running only a subset of tests instead of the full suite.

Add optional parameter to test script for passing through a test filter.

---

Assets/MixedRealityToolkit/Inspectors/MixedRealityStandardShaderGUI.cs

The way the "Albedo Alpha Mode" was drawn in the inspector was not correct.
- Fixes: #5978

StandardShaderGUIFix

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs

added missing class description and doc comments for public / inspector properties
fixes #5742

added missing doc comments for bounding box

---

Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputData/InputDataExample.cs
Assets/MixedRealityToolkit.Examples/Demos/Input/Scenes/InputData/InputDataExample.unity
Assets/MixedRealityToolkit.SDK/Features/Utilities/InputRayUtils.cs

- Fixes: #5996 by using TextMesh instead of UnityUI text, which re-lays out every time text changes.
>
>
>
>
> git checkout …

Get InputData example scene to 60 fps

---

Assets/MixedRealityToolkit/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs

MRTK 2019.1 deprecation fix

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MixedRealityToolkit/Extensions/TypeExtensions.cs

Addresses fixes for:
- #4967 
- #4481 
Fixes incorrect focus state when enabling/disabling interactable and fixes a button depth issue.
Both issues above explain that when interactable (within the script) is disabled and then enabled, the button remains in the focus state. This is shown in the video below under the label "Enable/Disable Interactable".   This issue was addressed by adding `SetFocus(false)` in `SetDisable`.
While working on this issue another issue was discovered when enabling/disabling the game object and the script, the button depth issue.  The button depth issue is also shown in the video below where the depth of the button does not reset after the game object or script is disabled.  This issue was addressed by removing `RefreshSetup` in `OnEnable`.
The video tests 3 …

Fix for focus state when enabling/disabling Interactable

---

Assets/MixedRealityToolkit/Providers/UnityInput/MouseDeviceManager.cs

Assigns the default profile on creation like all other profiles that have one do
- Fixes: #4306

added default profile

---

Documentation/Architecture/FrameworkAndRuntime.md

Fix typo in FrameworkAndRuntime documentation.

Fix typo: Apart form -> Apart from

---

Assets/MixedRealityToolkit.Examples/Demos/UX/Tooltips/Scenes/TooltipExamples.unity

The MRKT in this scene does not have a profile by default

Tooltip examples missing profile

---

Documentation/Contributing/BreakingChanges.md
Documentation/Contributing/CONTRIBUTING.md
Documentation/Contributing/CodingGuidelines.md
Documentation/Contributing/DocumentationGuide.md
Documentation/Contributing/ExperimentalFeatures.md
Documentation/Contributing/Feature_Contribution_Process.md
Documentation/Contributing/PullRequests.md
Documentation/toc.yml
README.md

As our contributors get more diverse, having clear expectations for contributions (code, tests, documentation, pull requests) will help ensure we maintain quality and reliability of MRTK.
This change expands our coding guidelines to discuss coding philosophy/approach. It also clarify expectations for pull requests, and experimental features. Finally, the contributing page has been updated to include latest contact info and process.
I have also removed all references to the Feature_Contribution_Process.md page, which contains guidance for contributing large features to MRTK before the 2.0 release. The guidance there is no longer accurate, however keeping the page there so we can reference it as we revise guidance for large features.
- Fixes: #6156 
docfx generation passes
> This optional …

Improve Contributing, Coding, and Pull Request Guidelines

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Definitions/Devices/MixedRealityHandTrackingProfileTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Extensions/CameraExtensionTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/BaseTestExtensionService.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/ITestExtensionService3.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestExtensionService3.cs.meta
Assets/MixedRealityToolkit.Tests/Microsoft.MixedReality.Toolkit.Tests.asmdef
Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/InputRayUtilsTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerBehaviorTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/ProfileTests.cs.meta
Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Documentation/Contributing/UnitTests.md

Adds test icons to tests that didn't have them

Update test icons for stabilization polish

---

web/version.js

Adds prerelease/2.1.0_stabilization to our docs for prerelease docs testing

Add prerelease/2.1.0 to docs version dropdown

---

Assets/MixedRealityToolkit.Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Definitions/Devices/MixedRealityHandTrackingProfileTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Extensions/CameraExtensionTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/ControllerMappingTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/InputSystem/InputSystemTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Microsoft.MixedReality.Toolkit.Tests.EditModeTests.asmdef
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/BaseTestExtensionService.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Services/TestExtensionService3.cs.meta
Assets/MixedRealityToolkit.Tests/Microsoft.MixedReality.Toolkit.Tests.asmdef
Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/InputRayUtilsTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerBehaviorTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/ProfileTests.cs.meta
Assets/MixedRealityToolkit.Tests/TestUtilities.cs
Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMappingProfile.cs
Assets/MixedRealityToolkit/Providers/BaseController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs
Assets/MixedRealityToolkit/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Documentation/Contributing/UnitTests.md

Merge stabilization -> dev

---

Documentation/ReleaseNotes.md

The 2.1 release notes were missing breaking changes and several "what's new" items. Add these.
- Fixes: #5912 
Verified that docs generation succeeded
>
>
> …

Add more whats new to 2.1 release notes, also add breaking changes.

---

Assets/MixedReality.Toolkit.Foundation.nuspec
pipelines/ci-release.yml

Merge some nuget pipeline changes from 2.0.1 to 2.1.0

Merge 2.0.1 -> 2.1.0

---

Assets/MixedRealityToolkit/Utilities/Lines/LineFollower.cs

Added some features to the LineFollower script that include Rotation, and Scale over the normalized length.
- Updated: LineFollower.cs

Added features to the LineFollower

---

Assets/MixedRealityToolkit/Providers/Hands/BaseHandVisualizer.cs

#5750 added support for the hand mesh changing had a small bug. Added a null check and a potential perf optimization (only recalculate the bounds if the mesh changed)

Fix 6234 (no input after toggling hand mesh)

---

Documentation/Contributing/Roadmap.md

update the roadmap to include 2.2.0 plan and early 2.3.0 thoughts

roadmap updates

---

web/version.js

Update version.js for 2.1.0 docs

Update version.js for 2.1.0 docs

---

Assets/MixedRealityToolkit/Extensions/GameObjectExtensions.cs

Fixed SetChildrenActive function which explicitly set children to inactive
SetChildrenActive in GameObjectExtensions.cs
>
>
>
>
> git …

Fixed SetChildrenActive function

---

Documentation/MRTKNuGetPackage.md

fixed a missing word in nuget advantages section and corrected some style guide violations

fixed missing word in nuget advantages and some style guide violations

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/SpherePointer.cs

user request to make code more readable

split up if statement where sphere pointer looks for nearest nearInteractionGrabbable 

---

.github/write-good.yml

Testing out adding a PR-based spellchecker extension, prosebot. Looks like it enables more features than just spellchecking, so I'm turning those off.
https://github.com/apps/prosebot

Configure prosebot

---

Documentation/InputSimulation/InputSimulationService.md

Nested list requires 4 spaces instead of 2.

[Docs] Fix nested list in InputSimulationService

---

Documentation/Input/Pointers.md

Minor tweaks to Pointers doc for readability
- Fixes: # .
>
>

Minor tweaks to Pointers doc for readability

---

Documentation/Authors.md

This change includes 2.1.0 and recent development branch contributors.

Authors update

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/Visuals/ProximityEffect/ProximityEffect.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/BoundsControlTests.cs

made sure that all recent changes applied to bounding box are also integrated in boundscontrol
part of #5340

ported over bounding box fixes and tests from sept / october

---

Assets/MixedRealityToolkit.Providers/OpenVR/OculusTouchController.cs
Assets/MixedRealityToolkit.Providers/OpenVR/ViveKnucklesController.cs
Assets/MixedRealityToolkit.Providers/OpenVR/ViveWandController.cs
Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedArticulatedHand.cs
Assets/MixedRealityToolkit.Services/InputSimulation/SimulatedGestureHand.cs
Assets/MixedRealityToolkit/Providers/BaseController.cs
Assets/MixedRealityToolkit/Providers/Hands/BaseHand.cs

Noticed while investigating #6164.

Remove duplicate overrides in controllers

---

Documentation/Profiles/Profiles.md

Clean up profiles page
- Fixes: # .
>
>

Clean up profiles page

---

Documentation/Packaging/MRTK_Packages.md

Clean up the layout of page and add helpful links to service documentation etc.
Redundancy of packages within packages was a bit confusing so keeping to just the four packages
- Fixes: # .
>
>

Clean up MRTK packages page

---

Documentation/README_Pointers.md

Fix link in old pointers page

---

Assets/MixedRealityToolkit.Services/SceneSystem/MixedRealitySceneSystem.cs

Error messages now offer better feedback when a scene isn't found.
- Fixes: #6314

Adds more verbose error messages to SceneSystem

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Textures/CircleIcon.png.meta

This file keeps reserializing itself with its sprite ID.

Reserialize CircleIcon.png.meta

---

Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/ClippingPlane.mat
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Materials/ClippingPlane.mat.meta
Assets/MixedRealityToolkit.Examples/Demos/StandardShader/Scenes/ClippingExamples.unity

Adds clipping plane to example scene to demonstrate fixed axis
- Fixes: #5803 
>
>

Add clipping plane to example

---

Documentation/GettingStartedWithTheMRTK.md

We have received feedback that some of our documentation is a challenge to navigate. at the suggestion of @grbury, made some small changes.

Doc changes to make it easier to navigate 

---

Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingService.cs
Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingServiceInspector.cs
Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingServiceProfile.cs
Assets/MixedRealityToolkit.Extensions/LostTrackingService/Scripts/BasicLostTrackingVisual.cs

Added some missing documentation and `<inheritdoc />` tags from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/5988.
Also fixes some incorrect null propagation.

Improve docs for Lost Tracking Service

---

Documentation/InputSimulation/InputSimulationService.md

Hand rotation was inaccurate
- Fixes: # .
>
>

Fix mouse rotation documentation

---

Assets/MixedRealityToolkit/Inspectors/PropertyDrawers/SceneInfoUtils.cs

This updates SceneInfoUtils to drill deeper into component and scriptable object fields to ensure SceneInfo data are up-to-date in editor and when building.
SceneInfoUtils will also not try to cache component types while the player is building.
- Fixes: #6429, #6448
Try moving the entire MRTK into a new folder.
- If you open the examples hub scene and enter play mode, the examples hub should still work.
- If you build the project _without first opening any scenes_, the examples hub should also work.
>
>

Extends SceneInfo refresh to arrays and lists

---

Assets/MixedRealityToolkit.Examples/Version.txt
Assets/MixedRealityToolkit.Extensions/Version.txt
Assets/MixedRealityToolkit.Providers/Version.txt
Assets/MixedRealityToolkit.SDK/Version.txt
Assets/MixedRealityToolkit.Services/Version.txt
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
Assets/MixedRealityToolkit.Tests/Version.txt
Assets/MixedRealityToolkit.Tools/Version.txt
Assets/MixedRealityToolkit/Version.txt
ProjectSettings/ProjectSettings.asset
pipelines/ci-daily.yml
pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml
pipelines/ci-release.yml
pipelines/ci.yaml
pipelines/pr.yaml

Now that we have branched for 2.2.0 stabilization, the development branch becomes v2.3.0

update mrtk_development version number from 2.2.0 -> 2.3.0

---

web/version.js

Add prerelease/2.2.0 to the docs version dropdown

Add prerelease/2.2.0 to the docs version dropdown

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/NearInteractionTouchableTests.cs
Assets/MixedRealityToolkit/Inspectors/MixedRealityToolkitFacadeHandler.cs
Assets/MixedRealityToolkit/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MixedRealityToolkit/Utilities/Rendering/DepthBufferRenderer.cs

Fixes some warnings that have been popping up recently.
- Fixes: #6517

Fix CI NuGet warnings

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/AppBar/AppBar.cs
Assets/MixedRealityToolkit.SDK/Features/Utilities/HeadPositionOffset.cs
Assets/MixedRealityToolkit.Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/PointerTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/SolverTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/StandardShaderTests.cs
Assets/MixedRealityToolkit.Tools/ScreenshotUtility/ScreenshotUtility.cs
Assets/MixedRealityToolkit/Definitions/Utilities/SolverOrientationType.cs
Assets/MixedRealityToolkit/Extensions/CanvasExtensions.cs
scripts/ci/validatecode.ps1

Updates all existing references to `CameraCache.Main` and adds PR code validation to prevent additional references from entering the repo.
- Related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/848

Update Camera.main references -> CameraCache

---

Assets/MixedRealityToolkit.Tests/TestUtilities.cs

Updates the InitializeCamera method to honor the code validation rule re: calling Camera.main

fix helper method to honor new code validation rule

---

Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Scripts/InteractableToggleCollection.cs
Assets/MixedRealityToolkit.SDK/Inspectors/UX/Interactable/InteractableToggleCollectionInspector.cs

The PR with the original fixes for issue #6274 was accidentally merged early #6473.
This PR is the remaining updates to InteractableToggleCollection based on feedback.
- Updates to ToggleList set behavior in InteractableToggleCollection
- Updates to InteractableToggleCollectionInspector - check for out of range index
>
>

Updates to InteractableToggleCollection - Part 2 

---

Documentation/EyeTracking/EyeTracking_ExamplesOverview.md
Documentation/Input/InputEvents.md

Brings over #6545 and #6530 to stabilization.

Cherry pick docs to stabilization

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/InteractableTests.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/Prefabs/Model_PushButton_DisabledOnStart.prefab
Assets/MixedRealityToolkit.Tests/PlayModeTests/Prefabs/Model_PushButton_DisabledOnStart.prefab.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/PressableButtonTests.cs

Fix for #6508 went into stabilization branch but did not add a test to cover this case for the future. This change does that.
- Fixes: #6508 
>
>

Add test for Interactable disabled on start

---

Assets/MixedRealityToolkit.Extensions/LostTrackingService/LostTrackingServiceProfile.cs

Fixes double entry in Create Menu

---

Documentation/toc.yml

This change re-orders the Features section of the documentation nav-bar to help with discovery of articles.
This will not effect the 2.0.0 or 2.1.0 documentation sub-sites.

alphabetization and minor refactoring of the Features section

---

NuGet/BuildSource.proj
pipelines/templates/compilemsbuild.yml
scripts/packaging/createnugetpackages.ps1

Issue #6391 needs build support for in-editor wsa nuget packages.
This is an independent subset of the changes that are in review as part of #6544.

add wsa editor build support - unblock #6391

---

Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec

There were some relative pathing errors in the unityar nuspec file.
verified fix by running scripts locally

fix nuget packaging error

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/BaseWindowsMixedRealitySource.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityController.cs
Assets/MixedRealityToolkit.Tests/PlayModeTests/GridObjectCollectionTests.cs.meta
Assets/MixedRealityToolkit/Providers/UnityInput/GenericJoystickController.cs
Assets/MixedRealityToolkit/Providers/UnityInput/MouseController.cs

Updates some comments and docs that I've been updating as I see them.
Also updates a test icon.

Minor comment and doc updates for 2.2

---

Assets/MixedRealityToolkit.Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxExampleTest.cs

Add null check when unregistering global handler

---

Documentation/Authors.md

update the collection of authors to highlight contributions

add new authors for 2.2.0

---

Assets/MixedRealityToolkit.Tools/MSBuild/AssemblyInfo.cs.meta
Assets/MixedRealityToolkit.Tools/RuntimeTools/Tools/AssemblyInfo.cs.meta

Some metas for AssemblyInfo.cs files were missing.

Add some missing metas

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityUtilities.cs
Assets/MixedRealityToolkit/Extensions/SystemNumericsExtensions.cs
Assets/MixedRealityToolkit/Extensions/SystemNumericsExtensions.cs.meta

Moves some methods from WindowsMixedRealityExtensions into a new extensions class in the core.
These methods aren't specific to the WMR provider.

Moves some methods from WindowsMixedRealityExtensions to SystemNumericsExtensions

---

Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Profiles/Interactable_MixedRealitySpeechCommandsProfile.asset
Assets/MixedRealityToolkit.Examples/Demos/UX/Interactables/Scenes/InteractablesExamples.unity
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/AnimationButton.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/Button.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/CheckBox.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/RadialSet.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/ToggleButton.prefab
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Prefabs/ToggleSwitch.prefab

Polishing InteractableExamples scene
- Fixes: #6632 .
- Added AudioReceiver to all Interactable Buttons
- Added BoxCollider to Quads that serve as backing for buttons 
- Updated the speech profile asset for the interactable scene to enable Toggle Profiler and Toggle Diagnostics commands
>
>
> As a reviewer, it is possible to check out this change …

Add audio and colliders

---

Documentation/README_Button.md

Simplified Unity UI instructions based on Adam's one-click inspector setup scripts (no need to manually add the Canvas Utility component or set Render Mode to World Space anymore). Also fixed a nearby typo
Went through these new steps several times using the MRTK 2.1 release

README_Button.md Unity UI tweak

---

Assets/MixedRealityToolkit.Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MixedRealityToolkit/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs
Assets/MixedRealityToolkit/Providers/BaseSpatialObserver.cs
Documentation/Architecture/ConfigurationAndProfiles.md
Documentation/Architecture/FrameworkAndRuntime.md
Documentation/Architecture/InputSystem/CoreSystem.md
Documentation/Architecture/InputSystem/Terminology.md
Documentation/Architecture/Overview.md
Documentation/Architecture/SystemsExtensionsProviders.md
Documentation/Boundary/BoundarySystemGettingStarted.md
Documentation/CameraSystem/CreateSettingsProvider.md
Documentation/CameraSystem/UnityArCameraSettings.md
Documentation/Contributing/BreakingChanges.md
Documentation/Contributing/CodingGuidelines.md
Documentation/Contributing/DevDocGuide.md
Documentation/Contributing/DocumentationGuide.md
Documentation/Contributing/ExperimentalFeatures.md
Documentation/Contributing/Feature_Contribution_Process.md
Documentation/Contributing/PullRequests.md
Documentation/Contributing/Roadmap.md
Documentation/Contributing/UnitTests.md

Cherry-picked some formatting changes I've made in working branches for stabilization.
Also went through some of our docs (would like to get to the rest, on my next bus ride 😜) and fixed up some minor nit formatting and spelling.
~There will be some merge conflicts with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6659/, which I can resolve after both are merged.~
There were some merge conflicts with https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6659/, which I've cherry-picked into this branch to get them in for stabilization.

First pass on docs formatting, spelling, and updates

---

Documentation/README_ExampleHub.md

Fix path in examples hub documentation

---

Assets/MixedRealityToolkit.Extensions/LostTrackingService/Assets/SR_Triangles_Lost_Tracking.mat

This was renamed in #6664, but was reserialized again in a merge.

Update SR_Triangles_Lost_Tracking.mat name

---

Documentation/Contributing/Feature_Contribution_Process.md
Documentation/Diagnostics/UsingVisualProfiler.md
Documentation/Extensions/ExtensionServices.md
Documentation/Extensions/SceneTransitionService/SceneTransitionServiceOverview.md
Documentation/EyeTracking/EyeTracking_BasicSetup.md
Documentation/EyeTracking/EyeTracking_ExamplesOverview.md
Documentation/EyeTracking/EyeTracking_EyeGazeProvider.md
Documentation/EyeTracking/EyeTracking_EyesAndHands.md
Documentation/EyeTracking/EyeTracking_IsUserCalibrated.md
Documentation/EyeTracking/EyeTracking_Main.md
Documentation/EyeTracking/EyeTracking_Navigation.md
Documentation/EyeTracking/EyeTracking_TargetSelection.md
Documentation/Input/CreateDataProvider.md
Documentation/Input/Gaze.md
Documentation/Input/InputEvents.md
Documentation/Input/InputState.md
Documentation/Input/Overview.md
Documentation/Input/Pointers.md
Documentation/Input/Speech.md
Documentation/InputSimulation/InputAnimationRecording.md
Documentation/InputSimulation/InputSimulationService.md

Updates formatting and spelling in various documentation. Continuation of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6661

Second phase of stabilization docs formatting, spelling, and updates

---

Assets/MixedRealityToolkit.SDK/Experimental/PulseShader/README.md

Adding GIF image links from the PR #6486 . Additional information on the materials and shader.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/a7b26e51a8e2b571a7aaa1622459724819d49a07/Assets/MixedRealityToolkit.SDK/Experimental/PulseShader/README.md

[Docs] Pulse shader documentation improvement

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityArticulatedHand.cs
Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs

Updates some `ApiInformation` checks with proper namespaces.

Fix namespaces for type checks

---

Documentation/Contributing/Roadmap.md

This change updates the 2.2.0 documentation with version 2.3.0 plans and some early thinking for 2.4.0

update roadmap to include 2.3 plan and 2.4 early ideas

---

Assets/MixedRealityToolkit/Definitions/Utilities/TrackedObjectType.cs

Missed comment during change. Fixing now
- Fixes: #6788 
>
>

Fix obsolete message for SolverHandler enum

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/DotNetAdapter/DotNetAdapter.csproj
Assets/MixedRealityToolkit.Tools/MSBuild/MSBuildMRTKTemplates/WSA.Player.Template.props.template

Updates the csproj layout to better match updated MSBuildForUnity template. The content versions and packages themselves are unchanged.
Part of #6244

Update csproj to better match updated MSBuildForUnity template

---

Assets/MixedRealityToolkit.Examples/Demos/Boundary/Scenes/BoundaryVisualization.unity
Assets/MixedRealityToolkit.Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/HolographicBackPlateBorderOnly.mat
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/MRTK_GrabbableDots2RowsH.mat
Assets/MixedRealityToolkit.SDK/Features/UX/Interactable/Materials/MRTK_GrabbableDots2RowsV1.mat

As part of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4914, I'm aiming to keep serialization up to date each time we release.

Reserialize some assets for 2.2 release

---

Documentation/ReleaseNotes.md

Minor links and stuff
- Fixes: # .
>
>

Minor updates to release notes

---

Documentation/ReleaseNotes.md

This change adds an entry to the known issues section of the release notes to describe #6807

add #6807 to known issues

---

Assets/MixedReality.Toolkit.Foundation.nuspec
Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec
Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec
Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec
Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec
Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec

Update NuGet license URL to point to releases/2.2.0 branch

Update license URL to point to releases/2.2.0 branch

---

Assets/MixedReality.Toolkit.Foundation.nuspec
Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec
Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec
Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec
Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec
Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec

Update iconUrl to point to renamed icon. See #6847

Update iconUrl to point to renamed icon

---

Documentation/Tools/HolographicRemoting.md

Added note to Holographic Remoting page about making sure your HoloLens is not plugged in while remoting.

Add note to Holographic Remoting page

---

Assets/MixedReality.Toolkit.Foundation.nuspec
Assets/MixedRealityToolkit.Examples/MixedReality.Toolkit.Examples.nuspec
Assets/MixedRealityToolkit.Extensions/MixedReality.Toolkit.Extensions.nuspec
Assets/MixedRealityToolkit.Staging/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec
Assets/MixedRealityToolkit.Tests/MixedReality.Toolkit.Tests.nuspec
Assets/MixedRealityToolkit.Tools/MixedReality.Toolkit.Tools.nuspec

Reverts #6845 in the dev branch

Revert license path back to mrtk_dev

---

Documentation/Input/HandTracking.md

The code to obtain IMixedRealityHandJointService has changed since the 2.0 release, but the documentation hasn't kept up to date.

Documentation on how to get the HandJointService is out of date.

---

Assets/MixedRealityToolkit.SDK/Profiles/MixedRealityControllerConfigurationProfile.md
Documentation/MixedRealityConfigurationGuide.md

I found some docs that reference features that have since been implemented, like platform controller model loading.
WMR: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/3673
OpenVR: #6374

Update controller docs to more correctly represent the current state of features

---

Assets/MixedRealityToolkit.SDK/Experimental/Inspectors/Microsoft.MixedReality.Toolkit.SDK.Experimental.Inspectors.asmdef
Assets/MixedRealityToolkit.SDK/Experimental/Inspectors/NonNativeKeyboard.meta
Assets/MixedRealityToolkit.SDK/Experimental/Inspectors/NonNativeKeyboard/SliderInputFieldInspector.cs
Assets/MixedRealityToolkit.SDK/Experimental/Inspectors/NonNativeKeyboard/SliderInputFieldInspector.cs.meta
Assets/MixedRealityToolkit.SDK/Experimental/NonNativeKeyboard/Scripts/SliderInputField.cs
Assets/MixedRealityToolkit.Tools/ExtensionServiceCreator/ExtensionServiceWizard.cs

A few warnings popped up recently in the NuGet build:
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6517

Clean-up warnings during NuGet build

---

Documentation/toc.yml

Creates new sub-section "Example Scenes" and adds ExampleHub page there with handsinteraction and eyetracking
- Fixes: # .
>
>

Add examples hub to TOC documentation

---

Documentation/SpatialAwareness/SpatialAwarenessGettingStarted.md

Add dedicated section in SA getting started to directly point people to more detailed setup and information
- Fixes: #6881
>
>

Dedicate documentation info for observers

---

Documentation/Contributing/CodingGuidelines.md

Minor change to add =>
- Fixes: # .
>
>

Update coding guidelines to use =>

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/UX/BoundsControl/Visuals/ProximityEffect/IProximityEffectObjectProvider.cs
Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/ProximityEffect.meta
Documentation/README_BoundingBox.md

fixed broken cref
replaced transformscalehandler in docs by new constraint
added missing meta

fixed broken docs and missing meta file

---

Documentation/README_BoundingBox.md

Migrates some changes from https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6961, since that PR has merge conflicts after #6964.

Migrate changes from #6961

---

web/version.js

Add prerelease/2.3.0 to the docs version dropdown

Add prerelease/2.3.0 to the docs version dropdown

---

Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Glb-Loading-Demo.unity
Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scenes/Gltf-Loading-Demo.unity
Assets/MixedRealityToolkit.Examples/Demos/Gltf/Scripts/TestGltfLoading.cs
Assets/MixedRealityToolkit/Utilities/Gltf/Serialization/GltfConversions.cs

This change addresses some of the issues with GLTF loading utility in MRTK. Note this is more of a stop gap then holistic fixes.
The GLTF utility is a weird feature because documentation and testing are mostly non-existent. There are also reliable alternatives such as [UnityGLTF](https://github.com/KhronosGroup/UnityGLTF).
**Change:**
Added AsyncCoroutineRunner to both gltf/glb scenes to work on device
Added index array access guards to the GltfConversions.cs file
- Fixes: #6955
Related:  #6983 #6362
Verified on HL2 device 
>
>

GLTF scene fixes

---

Assets/MixedRealityToolkit.Providers/UnityAR/MixedReality.Toolkit.Providers.UnityAR.nuspec

#7017 forgot to update the folder path in the unityar nuspec file. this change fixes and unblocks the ci build.

Fix nuget build of unityar (had old folder name)

---

Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/BoundsControlTests.cs

added 4 tests:
- far interaction scale
- near interaction rotate
- far interaction rotate
- GGV rotate
- Fixes: #6284

added tests to bounds control

---

pipelines/pr.yaml
pipelines/templates/common.yml
pipelines/templates/tasks/githubchanges.yml
pipelines/templates/tasks/validatecode.yml
scripts/ci/common.psm1
scripts/ci/githubchanges.ps1
scripts/ci/validatebuildlog.ps1
scripts/ci/validatecode.ps1
scripts/ci/validatedocs.ps1

Cherry-picks https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7027 to stabilization.

Cherry-pick #7027 to stabilization

---

pipelines/pr.yaml

Cherry-picks https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7039 to stabilization.

Cherrypick PR #7039 from wiwei/fastervalidation to stabilization

---

scripts/packaging/unitypackage.ps1

Small capitalization update in PS script

---

pipelines/templates/common.yml

FWIW I think I'm doing this is a fairly inefficient way (I should have just updated the pipelines to have variables that let you turn off certain parts) but I'm almost done with this part (I think).

One more test to see if it was the arm build or the x86 build being weird

---

Assets/MixedRealityToolkit.Providers/UnityAR/UnityARCameraSettings.cs

The path was changed in #7017.

Fix profile path location for UnityAR

---

Assets/MixedRealityToolkit.Examples/License.txt
Assets/MixedRealityToolkit.Extensions/License.txt
Assets/MixedRealityToolkit.Providers/License.txt
Assets/MixedRealityToolkit.SDK/License.txt
Assets/MixedRealityToolkit.Services/License.txt
Assets/MixedRealityToolkit.Tests/License.txt
Assets/MixedRealityToolkit.Tools/License.txt
Assets/MixedRealityToolkit/License.txt
License.txt

One benefit is that this removes the current year, so we don't go out of date!
Copied from https://docs.opensource.microsoft.com/content/releasing/license.html (this may be locked down to Microsoft employees).

Update License.txt files to currently recommended verbiage

---

Assets/MixedRealityToolkit.Extensions/HandPhysicsService/README.md
Assets/XR/Settings/Windows MR Package Settings.asset
Assets/XR/XRGeneralSettings.asset
Documentation/GettingStartedWithTheMRTK.md

Add some initial "getting started" docs for XR SDK.
Also, reserializes some XR SDK assets that were updated while testing my steps.
Also, updates some minor formatting in other docs.

Add initial XR SDK docs and reserialize some XR SDK assets

---

Assets/MixedRealityToolkit.SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Assets/MixedRealityToolkit.Services/TeleportSystem/MixedRealityTeleportSystem.cs
Assets/MixedRealityToolkit/EventDatum/Input/BaseInputEventData.cs
Assets/MixedRealityToolkit/Interfaces/EventSystem/IMixedRealityEventSource.cs

While investigating #7100 and #6527, I cleaned up some documentation and some redundant variable assignments.
The larger investigation will take a bit longer, but I wanted to get these in now.

TeleportSystem comment updates and minor updates

---

Documentation/Tools/HolographicRemoting.md

Documentation for holographic remoting has a duplicated image.
Correcting one of the image links
[Holographic remoting documentation](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Tools/HolographicRemoting.html?q=remote)
>
>
> commands …

Fix holographic remoting doc

---

Assets/MixedRealityToolkit.Providers/XRSDK/XRSDKDeviceManager.cs

Improves input device management on HoloLens 1, where the names of each input device for each hand are the same.
Overall, makes XR SDK device management more generic, instead of depending on a left / right hand.

Update input device management for XR SDK

---

Assets/MixedRealityToolkit.Providers/XRSDK/Controllers/GenericXRSDKController.cs

Some of the motion controller mappings were updated as part of shipping XR SDK.

Fix mappings for motion controllers on XR SDK

---

scripts/tools/experimental_stats.py

I was doing some digging into the relative stats and types of growth of code that we're introducing. In particular, we've done some work to introduce new experimental work under the experimental namespace.
The portion of the codebase with experimental stuff has naturally grown over time as we've added newer experimental features, and this is an interesting way to track that progression.

Adds a python script that will figure out the percent/stats of experimental features.

---

Assets/MixedRealityToolkit.SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs

Found two more usages of legacy XR APIs. Since these are experimental features, I've opted to `#pragma` them.
Continuation of #7193

Fix-up more usages of legacy XR APIs

---

Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs

This change updates MSBuild for Unity from 0.8.3 to 0.9.1

Update to latest msbuild for unity

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/PackageManifestUpdaterTests.cs
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/PackageManifestUpdaterTests.cs.meta
Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs

This change improves the package manifest logic by making it better contained, more reusable and adds testability.
Fixes #7218

Improve package manifest update logic, add test cases

---

Documentation/ReleaseNotes.md

Adds several missing new experimental features to the "what's new in 2.3" page.
- Fixes: #7241

What's new add experimental features

---

Documentation/MRTK_PackageContents.md

Updates our package contents doc with the new state of things for 2.3.

Update packages doc for 2.3

---

Documentation/README_ExampleHub.md

Remove non-relative link to docs

---

Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/PackageManifestUpdaterTests.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Core/Utilities/ProjectPreferencesTest.cs.meta
Assets/MixedRealityToolkit.Tests/EditModeTests/Experimental/BoundsControlTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/ConstraintTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/BoundsControlTests.cs.meta
Assets/MixedRealityToolkit.Tests/PlayModeTests/Experimental/ObjectManipulatorTests.cs.meta

Updates the Unity icons for our test files to match the current standard. Nice spread of new coverage tests this release!

Update test icons for new 2.3 test files

---

Documentation/Tools/HolographicRemoting.md

Cherry-pick over #7269 and add note on a potentially missing DotNetAdapter.csproj (thanks @julenka!)

Add additional debugging steps for MSB4U and HL2 remoting

---

Documentation/ReleaseNotes.md

Add recently discovered issues to the release notes.

Update known issues in release notes

---

Documentation/GettingStartedWithTheMRTK.md

Clarify Unity version and add XR SDK docs reference

Clarify Unity version and add XR SDK docs reference

---

Assets/MixedRealityToolkit.Examples/Experimental/Demos/UX/ObjectManipulator/Scenes/ObjectManipulatorExample.unity

They were still referring to primitive manipulator instead of object manipulator

fixed labels in object manipulator scene

---

Documentation/Contributing/Roadmap.md
Documentation/ReleaseNotes.md
Documentation/Updating.md

This change updates roadmap.md, releasenotes.md and updating.md to contain the sections that are to be filled in during the development of v2.4.0

Add scaffolding for 2.4.0 release notes, etc

---

Documentation/Updating.md

Fixed minor spelling error

---

Assets/MixedRealityToolkit/Utilities/StandardShader/HoverLight.cs

Expands the properties Color and Radius so they can be set via code
- Fixes: #7323

HoverLight Color and Radius are now accessible from code

---

Assets/MixedRealityToolkit/Utilities/Editor/PackageManifest/PackageManifestUpdater.cs

Cleaning up some branches and found this change. Figured I'd get it merged in!
Should do a full spell check pass again soon.

Spell check PackageManifestUpdater

---

Assets/MixedRealityToolkit/Utilities/WebRequestRest/Rest.cs

Added possibility to pass a DownloadHandler

---

Documentation/GettingStartedWithTheMRTK.md
Documentation/ReleaseNotes.md

Docs update in #7411 
Releases/2.3.0 -> mrtk_release

Releases/2.3.0 -> mrtk_release

---

Documentation/ReleaseNotes.md

Docs update in #7411
mrtk_release -> mrtk_dev

mrtk_release -> mrtk_dev

---

Assets/MixedRealityToolkit/Definitions/Devices/MixedRealityControllerMapping.cs

Basically inverts an Equal test that should have been that way from the beginning.
Write new values if they are different and not ignore them.
- Fixes: #7405

Mrtk controller mapping update fix

---

Assets/MRTK/Extensions/MixedReality.Toolkit.Extensions.nuspec

Was missing an extra level of redirection. This should now be fixed

Extensions NuGet packaging fix

---

Assets/MixedRealityToolkit.Providers/WindowsMixedReality/WindowsMixedRealityEyeGazeDataProvider.cs

Add check EyesPose.IsSupported to only call APIs when supported

---

Assets/MRTK/Core/Utilities/MixedRealityPlayspace.cs

Fixes an issue with an exception being thrown from within MRTK when opening the project:
```
ArgumentException: The scene is not loaded.
UnityEngine.SceneManagement.Scene.GetRootGameObjects (System.Collections.Generic.List`1[T] rootGameObjects) (at C:/buildslave/unity/build/Runtime/Export/SceneManager/Scene.cs:91)
UnityEngine.SceneManagement.Scene.GetRootGameObjects () (at C:/buildslave/unity/build/Runtime/Export/SceneManager/Scene.cs:75)
Microsoft.MixedReality.Toolkit.MixedRealityPlayspace.EditorSceneManagerSceneOpened (UnityEngine.SceneManagement.Scene scene, UnityEditor.SceneManagement.OpenSceneMode mode) (at Assets/MixedRealityToolkit/Utilities/MixedRealityPlayspace.cs:205)
UnityEditor.SceneManagement.EditorSceneManager.Internal_SceneOpened (UnityEngine.SceneManagement.Scene scene, …
```

Checking if scene has been loaded before we try to search it for extra playspaces

---

Documentation/Performance/PerfGettingStarted.md

Add useful links found by @Cameron-Micka to optimization page
- Fixes: # .
>
>

Add links to optimization page

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs

MixedRealityProjectConfigurator inhabits a lot of anonymous methods that add a little overhead to the overall readability and lambdas are just shorter and nicer and... you know, lambdas.
This PR converts them all.

MixedRealityProjectConfigurator Lambdas instead of anonymous methods

---

Assets/MRTK/SDK/Experimental/Dock/Dockable.cs
Assets/MRTK/SDK/Experimental/Dock/README_Dock.md

Attempting to fix a documentation warning by providing full namespace to the cref.
>
>

Documentation Warning Fix

---

Assets/MRTK/SDK/Features/Utilities/Solvers/SurfaceMagnetism.cs

Adds the option of having the object face the origin of the raycast.

Add additional orientation option

---

Documentation/EyeTracking/EyeTracking_Main.md

Follow up on @sostel 's comments in #7568 
- Fixes: #6341
>
>

Eye Tracking docs quick fix

---

Documentation/InputSimulation/InputSimulationService.md

fixed typo in eye tracking link

fixed broken link referring to eye tracking docs

---

Assets/MRTK/Core/Providers/BaseController.cs
Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs
Assets/MRTK/Core/Providers/Hands/ArticulatedHandDefinition.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs
Assets/MRTK/Services/InputSimulation/SimulatedArticulatedHand.cs
Assets/MRTK/Services/InputSimulation/SimulatedHand.cs

Mostly this PR adds some profiling markers to a couple hands classes.
I also threw in some small changes to other scripts that I found while investigating this profiling. Mostly formatting and removing a duplicated case in a switch statement.
- Follow-on from #7600 and other profiling PRs from @davidkline-ms

Add some profiling to hands (and formatting / cleanup)

---

Assets/MRTK/Tests/PlayModeTests/Components/TestInputGlobalListener.cs
Assets/MRTK/Tests/PlayModeTests/InputEventSystemTests.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs

Added more comprehensive voice command tests, also changed the Teardown script order so bugs involving a prematurely destroyed MixedRealityToolkit and MixedRealityPlayspace game objects don't hide the actual test errors
- Fixes: #5216

Added more comprehensive voice command tests

---

Assets/MRTK/Core/Inspectors/ServiceInspectors/ServiceFacadeInspector.cs

Fix service facade inspector headers

---

Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/BoxDisplay.cs
Assets/MRTK/SDK/Features/UX/Scripts/AppBar/AppBar.cs
Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
Assets/MRTK/Tests/PlayModeTests/InputEventSystemTests.cs

After #7635 was merged, it looks like a few comments hadn't been updated to the newly enforced style. This PR should fix the last of them.
https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=10576&view=logs&j=ae5f814d-d003-5afd-2125-fa0189ea8658&t=12d627c1-3bb6-55bf-f915-b77e58828cea
- Fixes: CI failure found by #7635

Fix comments flagged by comment style checker

---

Assets/MRTK/Services/InputSystem/FocusProvider.cs

Addressing Will's comment on this PR
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7625/files/209ae88a6bcfba8cf42b027672e4628dbcd7df3b#diff-8a90c91db20ded15531d97d45cd9a163R1240

Code cleanup removing extrneous totalNumColliders variable

---

Assets/MRTK/Services/TeleportSystem/MixedRealityTeleportSystem.cs

This change is the portion of #7565 addressing the teleport system.

Add profiler markers to the teleport system

---

Assets/MRTK/Services/DiagnosticsSystem/MixedRealityDiagnosticsSystem.cs
Assets/MRTK/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs

This is the part of #7565 that adds unity profiler instrumentation to the diagnostics system and the visual profiler.

Add profiler markers to diags system and visual profiler

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs

This change is part of #7565 and adds markers to the fallback path in the camera system as well as to the XRSDK generic spatial mesh observer.

Add profiler markers to camera system and the generic xr sdk mesh observer

---

Assets/MRTK/Services/SceneSystem/MixedRealitySceneSystem.cs

This change adds instrumentation to the scene system as part of #7565

Add profiler instrumentation to scene system

---

Assets/MRTK/Extensions/HandPhysicsService/HandPhysicsService.cs
Assets/MRTK/Extensions/HandPhysicsService/JointKinematicBody.cs
Assets/MRTK/Extensions/LostTrackingService/LostTrackingService.cs
Assets/MRTK/Extensions/SceneTransitionService/CameraFaderQuad.cs
Assets/MRTK/Extensions/SceneTransitionService/LoadContentScene.cs
Assets/MRTK/Extensions/SceneTransitionService/SceneTransitionService.cs

This change adds the profiler instrumentation described in (#7565) for the following extension services
- HandPhysics
- LostTracking
- SceneTransition

Add profiler instrumentation to extension services

---

Documentation/Performance/PerfGettingStarted.md

This change adds recommendations to instrument application code using a similar pattern to MRTK, especially in event handlers.

Add instrumentation recommendation to performance getting started page.

---

Assets/MRTK/Services/InputSimulation/SimulatedHandDataProvider.cs
Assets/MRTK/Tests/PlayModeTests/ProfileTests.cs

Fixes a regression with TestDefaultProfiles

BugFix PR for the TestDefaultProfiles Test

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/LeapCoreAssetsDetector.cs

Add missing MixedReality namespace to LeapCoreAssetsDetector

Add missing namespace to LeapCoreAssetsDetector

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/LeapCoreAssetsDetector.cs

This change didn't quite make it over, so let's gooooo

Cherry pick https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7694 into stabilization

---

web/version.js

Adds 2.4.0 docs to our version dropdown in the docs list.

Add 2.4.0 stabilization to our docs list

---

Assets/MRTK/SDK/Features/Utilities/Migration/Tools/MigrationTool.cs
Assets/MRTK/Tools/MigrationWindow/MigrationWindow.cs

Right now after performing any kind of upgrade the progress bar just disappears and the user won't have any information if the upgrade succeeded and which files got upgraded. (there is some message in the log, but not all users will have that open all the time)
Describe the solution you'd like
Proposed changes:
Let user know that upgrade process is finished by showing a message (popup or notification) after the progress bar is finished.
Keep the list of items that were added for upgrading in the UI and show a green tick or a red X to indicate if the asset has been upgraded. Green tick ones can have a tooltip like: Asset has been upgraded successfully - where red ones can show a truncated version of the error and on double click lead the user to the actual log message that gives the full …

Migration Tool UX improve

---

Assets/MRTK/Tests/EditModeTests/Core/Definitions/Devices/MixedRealityControllerMappingProfileTests.cs

#7750 has revealed that one of our test files was missing a namespace. This adds one.

Add missing namespace

---

Documentation/Authors.md

This change adds recent contributors to the authors file.

Update authors with recent 2.4.0 changes

---

Assets/MRTK/Core/Services/BaseDataProviderAccessCoreSystem.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/PlatformUtility.cs
Assets/MRTK/SDK/Experimental/ServiceManagers/Support/Scripts/BaseServiceManager.cs

Moves the 3 preprocessor directives into one method so it can easily be called
- Fixes: ##7747

Merged and Moved IsSupportedPlatform into PlatfomUtility

---

Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs

Although we don't yet fully support Unity 2020, there are a couple deprecated methods we can fix up to ease use:

Update some deprecated methods in Unity 2020

---

Assets/MRTK/Extensions/HandPhysicsService/HandPhysicsService.cs

Added HandPhysicsServiceRoot null check
Fixes the code issues descibed in #7786
- Fixes: #7786 
>
>
>
>
> git checkout …

CreateKinematicBodies called after the prefab setters set to new value

---

Documentation/ReleaseNotes.md

Adding UX building blocks updates to the 2.4.0 Release Note
Fixes #7803 
**Button Config Helper added to Pressable Buttons**
**Toggle Checkbox/Switch/Radio Buttons**
**Hand Menu Improvements**
**Hand Menu Examples update**
**Dialog (Experimental)**
**Dock (Experimental)**
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/cre8ivepark-patch-1/Documentation/ReleaseNotes.md

Adding UX building blocks updates to the 2.4.0 Release Note

---

Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputSimulationProfile.asset
Assets/MRTK/Services/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MRTK/Services/InputSimulation/InputSimulationService.cs
Assets/MRTK/Services/InputSimulation/MixedRealityInputSimulationProfile.cs
Assets/MRTK/Tests/PlayModeTests/ProfileTests.cs
Documentation/InputSimulation/InputSimulationService.md

Added an option to disable hands free input to maintain experience for mrtk 2.3
- Fixes: #7811

Added an option to disable hands free input

---

Documentation/ReleaseNotes.md

Just so that we don't forget to clean it up if we ultimately don't add any known issues,, deleting this for now. 
I'm generally non-favorable of "coming soon" messages which are equivalently evil like untracked TODOs.

Clean up the known issues part of the 2.4 release notes

---

Documentation/ReleaseNotes.md

Points the updating link so that the reader first sees how to upgrade, and then sees the next section (i.e. what to upgrade)
- Fixes: #7977

Update the updating link so that it provides actual "how to upgrade your project" guidance

---

Documentation/README_ObjectManipulator.md
Documentation/ReleaseNotes.md

and fixed typo in object manipulator doc
- Fixes:  https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7799 
completes graduation task: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7357

added release notes for object manipulator, bounds control, migration window

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

they now refer to object manipulator

Fixed two strings that were still pointing to ManipulationHandler in HandInteractionExample

---

Documentation/ReleaseNotes.md

Starting a known issues section and documenting MSBuild2019 issue

Adding Known Unity 2019 MSBuild Issue

---

Documentation/ReleaseNotes.md

Added Leap Motion support to the top of the release notes with a new gif and added Tap to Place.
- Fixes: #7798

Add Leap and Tap to Place to Release Notes

---

Documentation/README_Button.md
Documentation/Updating.md

Adding documentation for #7886
- Part of the fix for: ##7810

Initial draft of button upgrading docs

---

Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonConfigHelper.cs
Assets/MRTK/Tests/EditModeTests/Experimental/MigrationToolTests.cs

Adds unit tests for #7906
- Fixes: #7810

Added unit tests for custom button migration tool

---

Documentation/CrossPlatform/LeapMotionMRTK.md

Updated wording on the Ultraleap documentation based on recommendations from Ultraleap.

Ultraleap Documentation Update Part 2

---

Documentation/CrossPlatform/LeapMotionMRTK.md

Updated Ultraleap wording in the documentation, requested by Ultraleap.

Update Ultraleap Documentation Part 3

---

Documentation/ReleaseNotes.md

In preparation for the 2.4.0 release, this change adds to the known issues section of the release notes.
Fixes: #7845

Add known issues to release notes

---

web/version.js

Updating the dropdown to where it will end up being, rather than just where it is now.

Update the version dropdowns in preparation for 2.4.0 release.

---

Documentation/LargeProjects.md

Also using ...DotNetAdapter.csproj* so that DotNetAdapter.csproj.meta is included.
- Fixes: # .
>
>
>
>
> git checkout …

Updated MRTK path as introduced in 2.4

---

Documentation/CrossPlatform/LeapMotionMRTK.md

Update 4.5.0 download link in the Ultraleap documentation at the request of Ultraleap.

Ultraleap Documentation Update Part 4

---

Assets/MRTK/Tests/EditModeTests/BoundarySystem/InscribedRectangleTests.cs.meta
Assets/MRTK/Tests/EditModeTests/Editor/ToolboxWindowTests.cs.meta
Assets/MRTK/Tests/EditModeTests/Tools/ExtensionServiceCreatorTests.cs.meta
Assets/MRTK/Tests/PlayModeTests/BaseEventSystemTests.cs.meta
Assets/MRTK/Tests/PlayModeTests/GltfTests.cs.meta
Assets/MRTK/Tests/PlayModeTests/NearInteractionGrabbableTests.cs.meta
Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs.meta

A few tests were missing the test icons.

Update test icons

---

Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/NonNativeKeyboard.cs

Adds two new events to the Experimental NonNativeKeyboard
1. OnKeyboardValueKeyPressed
2. OnKeyboardKeyFuncPressed
Fixes:#8098

NonNativeKeyboard add events for when char and function keys pressed

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoPointerProfile.asset
Assets/MRTK/Examples/Demos/Input/Scenes/DisablePointers/DisablePointersExamplePointerProfile.asset
Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubPointerProfile.asset
Assets/MRTK/Examples/Experimental/NonNativeKeyboard/Profiles/NonNativeKeyboardMixedRealityInputPointerProfile.asset
Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputPointerProfile.asset
Documentation/ReleaseNotes.md

Ports the change to turn `SpatialPointerPose.Head` off by default in 2.4.1 (#8100)

Port #8100 to 2.4.1

---

Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs

I found the extra log information helpful when debugging some incorrectly configured assets.
- Related to: #8137

More helpful error message when interactable has incorrect dimension index.

---

Assets/MRTK/Core/Providers/Hands/HandBounds.cs

There were several outstanding improvements requested on the last PR regarding the local AABB system. The requested improvements have been implemented and are ready to be merged.
- Previously, the associated local bounds data was not removed `OnSourceLost`. This has been resolved.
- An option for rendering the local bounds as a gizmo has been added. This involved adding an extra dictionary to cache the transformation matrices under which the local bounds are calculated. The `OnDrawGizmos` uses this cached `Matrix4x4` to correctly render the local bounds.
- Comments have been clarified to make the distinction between proxy-space and hand-space clearer.
Unit tests relying on `HandBounds` for correct hand data have been re-run and verified.

Implementing requested improvements to HandBounds

---

Assets/MRTK/Core/Providers/InputSimulation/InputSimulationEnum.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/MixedRealityInputSimulationProfile.cs
Documentation/ReleaseNotes.md

Documentation and compatability cleanup for eye gaze simulation

---

Assets/MRTK/Tests/PlayModeTests/Experimental/ElasticTests.cs

Adds a series of unit tests to cover most of the core functionality of all three existing elastic implementations, `LinearElasticSystem`, `VolumeElasticSystem`, and `QuaternionElasticSystem`.
- Adds unit tests for the existing elastic implementations.
- Covers snap point snapping, interval snapping, bounds stretching, and endcap snapping/stretching.

Elastic Systems unit testing suite

---

Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs

Cleaning up some comments I missed and the end of the last PR

Cleaning up lingering comments from #8211

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/LaunchUri.cs

This API is a wrapper around the Windows API we were previously calling. Updating to use the Unity API allows this to be called in more contexts, like remoting.

Update LaunchUri.cs to use Unity-defined URI launcher

---

scripts/ci/validatecode.ps1

This change updates CI to barf when it sees a new instance of InitializeOnLoad.
As is called out in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8188, InitializeOnLoad is really powerful but also really painful, because it leads to the overall slowdown of the inner loop as new InitializeOnLoad handlers get added.
We should not be adding any new InitializeOnLoad handlers (i.e. ones that run on startup/compiletime/play mode entry) - this is blanket statement where we may have some exceptions going forward (i.e. in some cases maybe having it at startup could be useful where the ongoing pain it causes is zero). However, we're adding this CI step to fail explicitly to force us to evaluate future additions when/if they appear. This is an intentional speed bump (actually maybe …

No more InitializeOnLoad please

---

Documentation/CrossPlatform/UsingARFoundation.md

The ARFoundation CrossPlatform documentation is a bit confusing about the setting up of the scene. 
I added a side note about the fact that you can manually install the ARFoundation components to take advantage of this framework strengths.
- Related to an issue I did #8261

Further information about AR platform support installation and update of packages versions

---

Documentation/EyeTracking/EyeTracking_EyesAndHands.md
Documentation/Updating.md

MRTK documentation about hand and gaze setup is missing information on how to have eye gaze always on even when hand are detected.
- Fixes: #8262 .
- Fixes: #8140.

Documentation - adding eye gaze behavior changes

---

Documentation/Packaging/MRTK_Packages.md

Updates MRTK_Packages.md to replace "handing" with "handling"
- Fixes: # Replaced "handing" with "handling"

Update MRTK_Packages.md to handle spelling error

---

Documentation/Architecture/InputSystem/ControllersPointersAndFocus.md

Update ControllersPointersAndFocus.md adding a missing word
- Fixes: # Adds "device manager" where it looks like it was originally meant to be

Update ControllersPointersAndFocus.md adding a missing word

---

pipelines/templates/publishpackages.yml
scripts/packaging/publishupmpackages.ps1

This change adds in a fix that was made in feature branch that failed to make it back into the previous PR.

Add missing change that enables publishing of upm packages

---

pipelines/ci-packaging-dontpublish.yml

I missed updating one of the pipeline demands in #8116.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=13295&jobId=ae5f814d-d003-5afd-2125-fa0189ea8658&view=results

Update CI demand to Unity 2018.4.26f1

---

Assets/MRTK/SDK/Features/UX/Prefabs/Cursors/MouseCursor.prefab

Adjusted mouse pointer's cursor size. Updated MouseCursor.prefab properties.
'Resize cursor with distance' checked.
'Cursor angular size' updated to 7.
- Fixes: #8318

Mouse cursor size update

---

Assets/MRTK/Core/Interfaces/SpatialAwareness/Observers/Experimental/IMixedRealitySpatialAwarenessSceneUnderstandingObserver.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

Add comments to WindowsSceneUnderstandingObserver as part of SU feature work. Also cleaned up a little.

Add some comments to WindowsSceneUnderstandingObserver

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

This PR adds a missing SCENE_UNDERSTANDING_PRESENT flag check to ensure successful compilation when scene understanding is not present.

Add a missing SU flag check

---

Assets/MRTK/Core/Definitions/Utilities/MixedRealityPose.cs
Assets/MRTK/Tests/EditModeTests/Core/Definitions/Utilities.meta
Assets/MRTK/Tests/EditModeTests/Core/Definitions/Utilities/MixedRealityPoseTests.cs
Assets/MRTK/Tests/EditModeTests/Core/Definitions/Utilities/MixedRealityPoseTests.cs.meta

- Added multiplication operator for MixedRealityPose, for convenient pose operations.

Added multiplication operator for MixedRealityPose

---

Assets/MRTK/Core/Providers/InputSimulation/SimulatedMotionControllerButtonState.cs

Add the copyright header to SimulatedMotionControllerButtonState.cs

Add header to SimulatedMotionControllerButtonState.cs

---

Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs
Assets/MRTK/Tests/EditModeTests/Services/TestSpatialAwarenessDataProvider.cs

Remove the WaitingForSceneObserverAccess bool from TestSpatialAwarenessDataProvider.cs and restore SpatialObjectMeshObserver to the mrtk_dev version.

Remove more WaitingForSceneObserverAccess

---

pipelines/ci-packaging-internal.yml
pipelines/ci-release.yml
pipelines/ci-weekly-internal.yml

This should be temporary, as we're figuring out why the latest images don't work for us.
DON'T MERGE until the pool is up and running.

Update internal pool from Analog On-Prem to N-1

---

Assets/MRTK/Core/Definitions/BoundarySystem/InscribedRectangle.cs
Assets/MRTK/Core/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs
Assets/MRTK/Core/Definitions/Utilities/ArticulatedHandPose.cs
Assets/MRTK/Providers/OpenVR/OpenVRRenderModel.cs
Assets/MRTK/SDK/Experimental/Dock/Dockable.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs

It's that time in the release cycle where I try to catch up on all my stray branches and random changes I've made to make sure everything gets into the release.
**This one's going into mrtk_dev, not stabilization.**
Updates some `static readonly` and `const` capitalization to match [our coding guidelines](https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/CodingGuidelines.html#naming-conventions). Also converts some `static readonly` private fields to `const` where possible and adds some `readonly` modifiers to private fields that are treated that way.
**All changes are to private fields, so there isn't a worry of a breaking change.**

Update private static readonly capitalization and add some readonly modifiers where reasonable

---

Assets/MRTK/Core/Providers/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/ManualCameraControl.cs
Assets/MRTK/Core/Providers/InputSimulation/MixedRealityInputSimulationProfile.cs
Assets/MRTK/Examples/Experimental/CameraOffset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSimulationProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSimulationProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSystemProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSystemProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetTest.unity
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetTest.unity.meta

This change cherry-picks the camera height change in #8451 into the 2.5.0_stabilization branch.

Cherry-pick #8451

---

Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ParabolicPointer.prefab
Documentation/ReleaseNotes.md

Added release notes for the teleport pointer improvements associated with #8259 and #8386

Added release notes for teleport pointer improvements added teleport completed sound

---

Documentation/Input/Pointers.md

Update method name in Pointers.md document

---

Documentation/toc.yml

Adding entry on table of contents for Tools / Migration Window
- Fixes: #8540

Adding Migration Window entry to toc

---

scripts/docs/templates/mrtk/partials/head.tmpl.partial
scripts/docs/templates/mrtk/styles/main.js

This PR changes the way Google Analytics is added to our doc site so it actually works.
- Replaces #8532.

Fix doc site analytics

---

scripts/docs/templates/mrtk/partials/head.tmpl.partial
scripts/docs/templates/mrtk/styles/main.js

Cherry pick changes made in the stabilization branch that fixes the analytics on the github.io documentation site.

Fix doc site analytics cherry pick

---

Assets/MRTK/Core/Utilities/StandardShader/HoverLight.cs
Assets/MRTK/Examples/Demos/StandardShader/Scenes/HoverLightExamples.unity
Assets/MRTK/Examples/Demos/StandardShader/Scenes/HoverLightExamples.unity.meta
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.anim
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.anim.meta
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.controller
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.controller.meta
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightGray.mat
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightGray.mat.meta
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightParticle.mat
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightParticle.mat.meta
Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader
Documentation/Rendering/HoverLight.md

Cherry-pick #8596 to the 2.5 branch, as the issue it fixed was marked as a release blocker.
- Fixes: #8543

Cherry-pick #8596 (Adding scalable hover light support) to 2.5

---

Documentation/MRTK_PackageContents.md
Documentation/toc.yml

#8496 introduced some broken links. this change fixes them

Fix links that were broken in 8496

---

Documentation/ReleaseNotes.md

Updates our known issue with the latest issue we found in https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8556.

Update the known issues to mention the UnityUI/TMP issue

---

Assets/MRTK/SDK/Editor/Inspectors/UX/ScrollingObjectCollection/ScrollingObjectCollectionInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/ScrollingObjectCollection/ScrollingObjectCollection.cs

Fixing issue related to one of the scroll properties changes not being saved.
- Fixes: #8605

Fixing scroll MaskEnabled property serialization issue

---

README.md

Cherry-pick pull request #8622 to 2.5
- Related to https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8482

Cherry-pick pull request #8622 to 2.5

---

Assets/MRTK/Examples/Demos/Input/Scenes/Dictation/DictationExample.unity

This PR replaces the standalone input module with MixedRealityInputModule in the DictationExample scene.
- Fixes: #8656.

Update input module in the DictationExample scene

---

Documentation/ReleaseNotes.md

This change adds a release note for the issue described in #8459.

Add release note for 8459

---

Documentation/ReleaseNotes.md

added release notes entry for bounds control and constraint manager + links to new docs articles
- Fixes: #7358

added release notes entry for bounds control and constraint manager

---

Assets/MRTK/Providers/Oculus/XRSDK/Editor/OculusXRSDKConfigurationChecker.cs

Additional changes made to clean up our config checkers to not modify asmdefs

Changed oculus xrsdk configuration checker to not modify asmdefs

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

This PR replaces the generic debug message above the piano in the hand interaction examples scene to "Interaction with the piano". Missing references to the debug text mesh are added to the EFlat, FSharp, GSharp and BFlat keys so that pressing those keys now correctly shows a message.
- Fixes #8567

Fix some piano related bugs in the hand interaction examples scene

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8701
Applies the same workaround we did for Oculus Quest here: https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8583

Fix the broken CI

---

Documentation/ReleaseNotes.md

Remove mentions of Oculus Quest specific improvements in the release notes to not send mixed messages. We'll shoutout those improvements when they are available on all platforms.

removed mention of quest specific improvements

---

Documentation/ReleaseNotes.md

Cherrypick #8711 to 2.5. @RogPodge @polar-kev let me know if this was only intended to go into mrtk_dev, but since it was an edit to the 2.5 release notes I wanted to open this to make sure it doesn't get lost for the upcoming release.

Cherrypick #8711 to 2.5

---

Documentation/ReleaseNotes.md
Documentation/Tools/HolographicRemoting.md

Co-Authored-By: Kurtis <3580640+keveleigh@users.noreply.github.com>
Additional improvement to the remoting page based on feedback from @keveleigh in #8717

Additional improvement to remoting doc

---

Documentation/ReleaseNotes.md

quick cleanup... the release notes are not a draft

remove 'draft' from title

---

Documentation/Packaging/MRTK_Packages.md

Fix table in MRTK_Packages document

---

Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/MoveObjByEyeGaze.cs
Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs
Assets/MRTK/Services/SceneSystem/MixedRealitySceneSystem.cs
Assets/MRTK/Services/SceneSystem/MixedRealitySceneSystemEditorOperations.cs

Found a branch from April where I had updated some private property casing to match our code style conventions. Rebased it to clean up some of my old branches (along the lines of https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8442)
- Fixes: https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/Contributing/CodingGuidelines.html#naming-conventions

Update some private property casing

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity

This change cherry-picks the fix for #8719 so that the updated UPM packages no longer display the error,.

Cherry-pick fix for #8719 into 2.5.1 release

---

Documentation/ReleaseNotes.md
Documentation/usingupm.md

This change updates the release notes for the 2.5.1 UPM release.

Release notes for v2.5.1

---

Assets/MRTK/SDK/Experimental/RiggedHandVisualizer/RiggedHandVisualizer.cs

I removed a duplicate line of RiggedHandVisualizer.cs
- Fixes: # .
>
>
>
>

removed duplicate line.

---

Assets/MRTK/Core/Extensions/TypeExtensions.cs
Assets/MRTK/Core/Inspectors/Profiles/DataProviderAccessServiceInspector.cs
Assets/MRTK/StandardAssets/EditorUtilities.meta
Assets/MRTK/StandardAssets/EditorUtilities/MRTK.StandardAssets.Editor.asmdef
Assets/MRTK/StandardAssets/EditorUtilities/MRTK.StandardAssets.Editor.asmdef.meta
Assets/MRTK/StandardAssets/EditorUtilities/OnLoadUtilities.cs
Assets/MRTK/StandardAssets/EditorUtilities/OnLoadUtilities.cs.meta
Assets/MRTK/StandardAssets/Shaders/MRTK.Shaders.sentinel.meta
Documentation/ReleaseNotes.md
Documentation/usingupm.md
scripts/ci/validatecode.ps1
scripts/packaging/createupmpackages.ps1

Merge stabilization -> mrtk_dev

Merge stabilization -> mrtk_dev

---

Documentation/usingupm.md

Documentation was missing a quote. Added a quote.

Added a missing quote

---

Assets/MRTK/Core/Inspectors/ClippingSphereInspector.cs
Assets/MRTK/Core/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingBox.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingPlane.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingSphere.cs
Assets/MRTK/Examples/Demos/StandardShader/Scenes/ClippingInstancedExamples.unity
Assets/MRTK/Examples/Demos/StandardShader/Scenes/ClippingInstancedExamples.unity.meta
Assets/MRTK/Examples/StandardAssets/Materials/ShaderBallClippingBox.mat
Assets/MRTK/Examples/StandardAssets/Materials/ShaderBallClippingPlane.mat
Assets/MRTK/Examples/StandardAssets/Materials/ShaderBallClippingPlaneInner.mat
Assets/MRTK/Examples/StandardAssets/Materials/ShaderBallClippingSphere.mat
Assets/MRTK/Examples/StandardAssets/Materials/ShaderBallClippingSphereInner.mat
Assets/MRTK/StandardAssets/Shaders/MixedRealityShaderUtils.cginc
Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader
Assets/MRTK/StandardAssets/Shaders/MixedRealityTextMeshPro.shader
Assets/MRTK/StandardAssets/Shaders/Text3DShader.shader
Documentation/Rendering/ClippingPrimitive.md

This PR includes:
* GPU instancing of `Renderers` that are clipped by `ClippingPrimitives`
* Ellipsoid support for `ClippingSphere`
* Optimizations.
Features:
* `ClippingPrimitive` now exposes a property to control how materials are affected. Enabling `Apply To Shared Materials` will result in the clipping feature being toggled on the `Renderer.sharedMaterials` rather than the default of creating new material instances.
* `MixedRealityStandard` and `Text3DShader` shaders were updated to support instancing of the clipping properties.
* `ClippingSphere` functionality updated to operate on an inverse matrix, supporting ellipsoids. `Radius` is deprecated, replaced by `Radii`.
* Created an example scene, `ClippingInstancedExamples` that shows the above features in action.
* To support this, …

Clipping Enhancements: GPU Instancing, Ellipsoids, and other changes.

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs

followup on final comment on #8847

Updated Oculus Project Config debug message

---

Documentation/Contributing/Roadmap.md

Updated roadmap to reflect MRTK 2.6 plans.
>
>
>
>

MRTK Roadmap update for 2.6

---

Documentation/Contributing/Roadmap.md

The header was updated, but this link wasn't.
- Fixes broken docs build

Fix broken link

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs
Assets/MRTK/Tests/EditModeTests/Editor/OculusIntegrationSetupTests.cs
Documentation/CrossPlatform/OculusQuestMRTK.md

Followup of the work done here #8861 to streamline using Oculus with MRTK
related to #8849

Oculus Integration tool no longer modifies all Device Manager Profiles

---

Documentation/Tools/HolographicRemoting.md

Make the enable flag step clearer in the docs.

Add an enable flag step to remoting with NuGet instructions

---

Documentation/Installation.md

Minor spacing fix for an image. Text polish.
Fixing this layout issue:

Minor spacing fix for an image. Text polish.

---

pipelines/pr-2019.yaml

Add a pipeline template specifically for Unity 2019 and VS 2019.

Add Unity 2019 pipeline template

---

CODEOWNERS

Remove exited team members, add new owners

update code owners based on team changes

---

pipelines/pr-2019.yaml
pipelines/pr.yaml

Comment out scoped validation until VM issue is sorted

Comment out scoped validation until VM issue is sorted

---

Assets/MRTK/Core/Definitions/Utilities/MixedRealityPose.cs
Assets/MRTK/Core/Definitions/Utilities/MixedRealityTransform.cs
Assets/MRTK/Core/Providers/BaseGenericInputSource.cs
Assets/MRTK/Core/Providers/BaseSpatialObserver.cs
Assets/MRTK/Core/Providers/GenericPointer.cs
Assets/MRTK/Core/Providers/InputSimulation/KeyBinding.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DataStructures/DeviceInfo.cs
Assets/MRTK/SDK/Features/UX/Scripts/VisualThemes/States/State.cs
Assets/MRTK/StandardAssets/EditorUtilities/OnLoadUtilities.cs
Assets/MRTK/Tests/PlayModeTests/EventCatcherTestUtilities.cs
pipelines/pr.yaml

Fix Shader import error seen on Mac editor when imported via UPM
Cherry-pick pull request #8909 to 2.5.2
Also brings over #8974 to unblock CI
Also https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8932 to unblock CI

Cherry-pick pull request #8909 to 2.5.2

---

Documentation/ReleaseNotes.md

Updated the message about the ARM64 compiler issue with instructions to update to Visual Studio 2019 v16.8.
- Fixes: # .
>
>
>
>
> git …

Visual Studio v16.8 Docs Message Update

---

Documentation/ReleaseNotes.md

Added section to the release notes highlighting support for the HP Motion Controllers

Added HP Controller support to release notes

---

Documentation/ReleaseNotes.md

Updated the ARM64 compiler message to state the Visual Studio 2019 v16.8 is released.
- Fixes: # .
>
>
>
>
> git checkout …

Visual Studio 2019 v16.8 docs bug fix message for 2.5.1

---

Assets/MRTK/Examples/packagetemplate.json
Assets/MRTK/Extensions/packagetemplate.json
Assets/MRTK/StandardAssets/packagetemplate.json
Assets/MRTK/Tests/TestUtilities/packagetemplate.json
Assets/MRTK/Tools/packagetemplate.json
Assets/MRTK/packagetemplate.json

This change adds a custom field to the package manifests. It adds the "featureCategory" field and sets the value to "Mixed Reality Toolkit". This tag will be used in the future and has no impact if a tool or process is not expecting to see it.

Add featureCategory field to package template

---

Assets/MRTK/Core/Providers/Hands/ArticulatedHandDefinition.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Assets/MRTK/Tests/PlayModeTests/PointerTests.cs

Addressing comments left here:
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8977

Addressing lingering comments on teleport PR

---

Assets/MRTK/Examples/packagetemplate.json
Assets/MRTK/Extensions/packagetemplate.json
Assets/MRTK/StandardAssets/packagetemplate.json
Assets/MRTK/Tests/TestUtilities/packagetemplate.json
Assets/MRTK/Tools/packagetemplate.json
Assets/MRTK/packagetemplate.json

This change brings #9023 into the 2.5.2 relelease

Cherry-pick msftFeatureCategory field change to packaging templates

---

Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs

Cherrypick #8925 to 2.5.2
Small fixes for Unity 2020.1

Cherrypick #8925 to 2.5.2

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
Documentation/Contributing/Roadmap.md
Documentation/ReleaseNotes.md
Documentation/usingupm.md
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/docs/web/version.js

Update versioning to 2.5.2

---

Assets/MRTK/Extensions/HandPhysicsService/Examples/HandPhysicsServiceExample.unity
Assets/MRTK/Extensions/HandPhysicsService/MRTK.HandPhysics.asmdef
Assets/MRTK/Extensions/HandPhysicsService/Profiles/HandPhysicsMixedRealityRegisteredServiceProvidersProfile.asset

Made the hand physics module work on android and had the extension now properly work in editor as well. Also adjusted the texture on an object from MRTK_Wireframe to MRTK_Standard_LightGray in the scene to fix rendering issues on the Quest.
- Fixes: #9041

Enabled hand physics to work on android

---

README.md

Updates the list with OpenXR and Oculus, as well as clarifying specific devices on specific platforms

Update supported platforms in docs

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
Documentation/Contributing/Roadmap.md
Documentation/ReleaseNotes.md
Documentation/usingupm.md
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/docs/web/version.js

This reverts commit 979238397b835e36fde03b9b763f8e1c0c387481, reversing
changes made to 5e038984a0e6343723e1ffd47e0adac422596113.
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9083

Revert "Merge pull request #9075 from RogPodge/oculushandrayfix" for 2.5.3

---

Assets/MRTK/Examples/Demos/HandCoach/Scenes/HandCoachExample.unity
Assets/MRTK/Examples/Demos/ScrollingObjectCollection/Prefabs/ScrollingOC_PressableBtn_32x96.prefab
Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset
Assets/MRTK/SDK/Features/UX/Scripts/HandCoach/HandInteractionHint.cs

Addressing feedback on the hand coach graduation.
>
>
>
>

Hand coach graduation feedback PR 

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitPreserveSettings.cs
Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
Documentation/Contributing/Roadmap.md
Documentation/ReleaseNotes.md
Documentation/usingupm.md
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/docs/web/version.js

Cherrypick #9112 and increment version for 2.5.4

Cherrypick #9112 and increment version for 2.5.4

---

pipelines/mergetool.yml
scripts/ci/mergetool.py
scripts/ci/requirements.txt

For transparency and versioning, this PR extracts the[ mergetool pipeline](https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build?definitionId=65) out into a checked-in script and a yml pipeline definition.

Extracts the mergetool pipeline out into actual scripts and yml

---

Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManagerProfile.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Documentation/CrossPlatform/OculusQuestMRTK.md
Documentation/GettingStartedWithMRTKAndXRSDK.md

Updated documentation to consistently refer to XR SDK, rewrote the getting started with XRSDK guide.

Updated XR SDK documentation

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs

Updating the Unity version recommendations as per this issue tracked #8066

Update recommended Unity version for mixed reality capture

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs

* Update Profile Camera info message
* Update Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs
Co-authored-by: Kurtis <kurtie@microsoft.com>
* updated info messages
* Update Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs
Co-authored-by: Kurtis <kurtie@microsoft.com>
Co-authored-by: Kurtis <kurtie@microsoft.com>
- Fixes: # .
>
> If there are specific areas of …

Update recommended Unity version for mixed reality capture (#9170)

---

Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManagerProfile.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Documentation/CrossPlatform/OculusQuestMRTK.md
Documentation/GettingStartedWithMRTKAndXRSDK.md

* Updated to consistently refer to XR SDK, rewrote the getting started documentation
* fixed doc errors
* Update Documentation/GettingStartedWithMRTKAndXRSDK.md
Co-authored-by: Kurtis <kurtie@microsoft.com>
Co-authored-by: Kurtis <kurtie@microsoft.com>
- Fixes: # .
>
>
> As a reviewer, it is possible to check out this change locally by using the …

Cherry-pick Updated XR SDK documentation (#9173)

---

Assets/MRTK/Core/Inspectors/Utilities/MixedRealityInspectorUtility.cs

Dirty scene after adding MRTK to scene

---

Documentation/README_PulseShader.md

Updating pulse shader documentation to match the latest updates.

Documentation update - Pulse shader

---

Assets/MRTK/Examples/Demos/PulseShader/Profile/PulseShaderSpatialAwarenessMeshObserverProfile.asset
Assets/MRTK/Examples/Demos/PulseShader/Scenes/PulseShaderSpatialMeshExample.unity
Assets/MRTK/SDK/Features/UX/Scripts/PulseShader/PulseShaderSpatialMeshHandler.cs
Assets/MRTK/SDK/StandardAssets/Prefabs/PulseShaderSpatialMeshParent.prefab
Assets/MRTK/SDK/StandardAssets/Prefabs/PulseShaderSpatialMeshParent.prefab.meta
Documentation/README_PulseShader.md

- Integrated the changes made in #9191 to the Pulse Shader Spatial Mesh example scene 
- Updated documentation to reflect the changes
- Pulse Shader Graduation Part 1: #9140 
>
>

Pulse Shader Graduation Part 2

---

Assets/MRTK/SDK/Experimental/InteractiveElement/Examples/InteractiveElementExampleScene.unity
Assets/MRTK/SDK/Experimental/InteractiveElement/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Experimental/InteractiveElement/InteractiveElement/InteractiveElement.cs
Assets/MRTK/Tests/PlayModeTests/InteractiveElementTests.cs

Final polish pass on Interactive Element before merging into mrtk_development.
- Updated temporary place holder class comment
- Added new test that adds and removes all states
- Added more informative error messages to a commonly used method + missing doc comment
- Added active profile to the InteractiveElementExample scene 
>
>

Polish Pass on Interactive Element 

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

Add the Interactive Element assemblies to the UnityProjInfo file

Add 2019 assemblies to UnityProjectInfo

---

Assets/MRTK/Tools/MSBuild/Scripts/CompilationPlatformInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/TargetFramework.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

This PR modifies certain MSBuild related scripts so that it works with Unity 2020.

Fix MSBuild for Unity 2020

---

pipelines/templates/tasks/unitybuild.yml

Put WSAPlayer in quotes to fix build
- Fixes: https://microsoft.visualstudio.com/Analog/_build/results?buildId=31273794&view=results

Put WSAPlayer in quotes to fix build

---

pipelines/templates/assetretargeting.yml
pipelines/templates/generateprojects.yml
pipelines/templates/tasks/unitybuild.yml

Adding some debugging for the build break

Always print Unity logs in pipeline

---

pipelines/templates/tasks/unitybuild.yml
pipelines/templates/tests.yml

Rework AppX build steps to not timeout

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

Update version in dev branch after branching for stabilization

Update version in dev branch after branching for stabilization

---

pipelines/ci-daily.yml
pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci.yaml
pipelines/pr.yaml
pipelines/templates/ci-common.yml
pipelines/templates/common-nonUnity.yml
pipelines/templates/tasks/pack-upm.yml
pipelines/templates/tasks/publish-nuget.yml
pipelines/templates/tasks/validateassets.yml
pipelines/templates/tasks/validatecode.yml
pipelines/templates/validation.yml

Move UPM packing to the non-Unity portion of the pipeline and enable it for PR, now that it's in the non-blocking portion of the pipeline

Move UPM packing to the non-Unity portion of the pipeline

---

pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml
pipelines/templates/common-nonUnity.yml

The internal UPM push needs to happen on hosted machines for feed permissions

Fix internal CI push

---

Documentation/Authors.md
scripts/ci/contributors.py

Update Authors list for 2.6

---

Assets/MRTK/SDK/Editor/Inspectors/Experimental/InteractiveElement/MRTK.SDK.Editor.Experimental.Interactive.asmdef
Assets/MRTK/SDK/Experimental/InteractiveElement/MRTK.SDK.Experimental.Interactive.asmdef
pipelines/config/settings.yml
pipelines/docs-binaries.yml
scripts/packaging/createbinariesfordocs.ps1

This PR adds a new pipeline to generate the binaries needed for API reference docs.

Create a pipeline for docs binaries generation

---

Assets/MRTK/Tools/MSBuild/MSBuildMRTKTemplates/SDKProjectTemplate.csproj.template
Assets/MRTK/Tools/MSBuild/Scripts/CSProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/CompilationPlatformInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/TargetFramework.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/Utilities.cs
NuGet/BuildSource.proj

Port #9113, #9152 and #9226 to 2.5.4.

Port additional doc related commits to 2.5.4

---

Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/MoveObjByEyeGaze.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

Addressing additional feedback on #9364
- Fixes: #9336

Addressing remaining feedback on #9364

---

Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/MoveObjByEyeGaze.cs
Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityInputSimulationProfile.asset
Assets/MRTK/Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerHandlerExample.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

This is a pull request initiated by an automated process to keep prerelease/2.6.0_stabilization and mrtk_development in sync

Branch synchronization: prerelease/2.6.0_stabilization --> mrtk_development

---

Documentation/ReleaseNotes.md

Update release notes to include the pulse shader graduation.

Add Pulse Shader Graduation to Release Notes

---

Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scenes/SceneUnderstandingExample.unity
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs
pipelines/config/settings.yml
pipelines/docs-binaries.yml

Remove Scene Understanding's dependency on the dotnetwinrt package.

Remove dotnetwinrt dependency in Scene Understanding

---

Documentation/GettingStartedWithMRTKAndXRSDK.md
Documentation/Profiles/Profiles.md

Clarifies some use cases and current restrictions on using existing XR SDK profiles. https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9419 tracks improvements in this space.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9185

Improve clarity on when / how to use XRSDK profiles

---

pipelines/mergetool.yml

Turn off auto mergetool (for now), now that 2.6 has shipped!

Turn off auto mergetool (for now)

---

scripts/docs/templates/mrtk/partials/navbar.tmpl.partial
scripts/docs/templates/mrtk/styles/docfx.css

Add a we've moved banner to all conceptual doc and API reference pages on GitHub.io doc site.

Add a we've moved banner to doc site

---

Documentation/GettingStartedWithTheMRTK.md
Documentation/WelcomeToMRTK.md
README.md

Changed the redirect links to point to https://docs.microsoft.com/windows/mixed-reality/mrtk-unity/
- Fixes: # .
>
>
>
>
> git …

Broken redirect links in mrtk docs

---

README.md

Add we've moved to README

---

ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

This change increments the MRTK version to 3.0.0 for the v3_developement branch

increment MRTK version number

---

Documentation/GettingStartedWithMRTKAndXRSDK.md
Documentation/GettingStartedWithTheMRTK.md
Documentation/Input/HandTracking.md
Documentation/Input/Pointers.md
Documentation/Installation.md
Documentation/README_Button.md
Documentation/README_MRTKStandardShader.md
Documentation/README_Solver.md
Documentation/WelcomeToMRTK.md
Documentation/usingupm.md
README.md
scripts/docs/templates/mrtk/partials/navbar.tmpl.partial
scripts/docs/templates/mrtk/styles/docfx.css

Cherry pick #9439, #9341 and #9436 to the 2.5.3 branch.

Port banner to 2.5.3 branch

---

Assets/MRTK/Examples/Experimental/Dwell/DwellExample.unity

Switched to the HoloLens 1 style profile in the dwell sample scene to solve pointer related problem and also updated the text shown in the scene to help developers understand what to watch out for.
- Fixes #9483

Fix the profile issue in the dwell sample scene

---

Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scenes/SceneUnderstandingExample.unity

Update the Scene Understanding sample scene to show the SU package is now available

---

Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs

check that the controller position is available before expecting that the joints have been added to the controller.
(I'm also VERY curious why line 208 returns true)
- Fixes: # .
>
>
>
> git …

Reduce log spam from HandConstraintPalmUp

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionRecordArticulatedHandPose.unity

Add description to the HandInteractionRecordArticulatedHandPose scene

---

Assets/MRTK/Examples/Demos/Audio/Scenes/TextToSpeechExamples.unity
Assets/MRTK/Examples/Demos/Audio/Scenes/TextToSpeechExamples.unity.meta
Assets/MRTK/Examples/Demos/Audio/Scripts/TextToSpeechSample.cs
Assets/MRTK/Examples/Demos/Audio/Scripts/TextToSpeechSample.cs.meta
Assets/MRTK/SDK/Features/Audio/TextToSpeech.cs
Assets/MRTK/SDK/Features/Audio/TextToSpeech.cs.meta

This PR ports the Text To Speech feature from HTK to MRTK. Sample scene and script are also included. Note this feature/demo scene is only supported on Windows device (i.e. not in editor).
- Fixes #3569

Port TextToSpeech to MRTK

---

Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scripts/DemoSceneUnderstandingController.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

Added a function to retrieve all observed scene object of a certain kind in the Scene Understanding demo script. Also did some refactoring.
- Fixes #9442

Improving the Scene Understanding demo

---

Assets/MRTK/Core/Interfaces/SpatialAwareness/Observers/IMixedRealitySpatialAwarenessObserver.cs
Assets/MRTK/Core/Providers/BaseSpatialMeshObserver.cs
Assets/MRTK/Core/Providers/BaseSpatialObserver.cs
Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs
Assets/MRTK/Providers/OpenXR/Profiles/DefaultOpenXRSpatialAwarenessSystemProfile.asset
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

Using the [Mixed Reality OpenXR package](https://docs.microsoft.com/en-us/windows/mixed-reality/develop/unity/openxr-supported-features) 0.9.0-preview.1, spatial mapping is available!
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9491

Update XR SDK spatial mapping to support additional platforms (OpenXR)

---

scripts/ci/validatecode.ps1

Update asmdef path in validate code script based on changes from #9570

Update asmdef path in validate code script

---

pipelines/packageupmpublic.yaml
pipelines/templates/tasks/pack-upm.yml

update packaging pipeline to support specifying arbitrary preview numbers

Packaging pipeline changes

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKInputSystemProfile.asset

Also slightly updates the namespace ordering post #9584

Add WindowsSpeechInputProvider to XRSDK input profile

---

pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml

Finally sunsetting the nuget distribution entirely

Turn off nuget pack in internal pipeline

---

Assets/MRTK/Core/Definitions/Devices/MixedRealityControllerModelHelpers.cs
Assets/MRTK/Core/Definitions/Devices/MixedRealityControllerModelHelpers.cs.meta
Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Profiles/ObsoleteOpenXRControllerVisualizationProfile.asset
Assets/MRTK/Providers/OpenXR/Scripts/HPReverbG2Controller.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftControllerModelProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftControllerModelProvider.cs.meta
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/AssemblyInfo.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/AssemblyInfo.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityControllerModelProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerVisualizationProfile.asset
Assets/MRTK/SDK/Profiles/HoloLens2/DefaultHoloLens2ConfigurationProfile.asset

Adds support for the controller render models via OpenXR.
Also works in-editor!
- Fixes: #9699

Add support for OpenXR controller model

---

Assets/MRTK/Core/Utilities/Editor/SpatializerUtilities.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfUtility.cs
Assets/MRTK/Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxExampleTest.cs
Assets/MRTK/Examples/Demos/UX/BoundsControl/Scripts/BoundsControlRuntimeExample.cs
Assets/MRTK/Examples/Demos/UX/ManipulationHandler/Scripts/ChangeManipulation.cs
Assets/MRTK/Extensions/HandPhysicsService/Examples/HandPhysicsServiceExample.unity
Assets/MRTK/SDK/Editor/Migration/ObjectManipulatorMigrationHandler.cs

Some of the warnings were actually informational messages. Switch those to simple Log calls. Others could be removed altogether.
Also add some missing required components.
This is not yet a complete fix, though it is a step towards addressing #9603.

Eliminate some unneeded warning messages on project load.

---

ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

increments the version of the main branch

increment main branch version to 2.8

---

pipelines/mergetool.yml
scripts/ci/mergetool.py

Re-enable mergetool for 2.7 stabilization

Re-enable mergetool for 2.7 stabilization

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

Make sure the texts wrap properly for certain texts that could be potentially truncated. Fixes #9708

Fix some word not wrapping issues in the Configurator

---

Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scripts/DemoSceneUnderstandingController.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/MRTK.WSU.asmdef
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

Add Scene Understanding support to the OpenXR pipeline. Also fixed a bug in the demo script.
- Fixes #9632, fixes #9706

Support Scene Understanding via OpenXR pipeline

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

This adds the missing commit from #9801

update menu text

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Examples/Demos/PulseShader/Scenes/PulseShaderHandMeshExample.unity
Assets/MRTK/Examples/Demos/PulseShader/Scenes/PulseShaderSpatialMeshExample.unity

The toggles feature panel used to not be parented to the main MixedRealitySceneContent object, causing it to not be adjusted for the user's height in VR. This PR corrects that
old:
new:

Updated scenes to group ToggleFeaturesPanel with the main scene content

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs
Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionDeviceManagerProfileInspector.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs
Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs

We recently moved around some documentation regarding cross-platform devices. This PR updates our code comments to point to the correct locations

Updated our code comments after adjusting cross-platform documentation

---

Assets/MRTK/Examples/Common/Prefabs/HandMenu_Large_AutoWorldLock_On_HandDrop.prefab
Assets/MRTK/Examples/Common/Prefabs/HandMenu_Large_WorldLock_On_GrabAndPull.prefab
Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Examples/Demos/Input/Scenes/DisablePointers/DisablePointersExample.unity
Assets/MRTK/Examples/Demos/Input/Scenes/InputData/InputDataExample.unity
Assets/MRTK/Examples/Demos/ScrollingObjectCollection/Prefabs/DynamicScrollPopulator.prefab
Assets/MRTK/Examples/Demos/Solvers/Scenes/FollowSolverExample.unity
Assets/MRTK/Examples/Demos/Solvers/Scenes/SolverExamples.unity
Assets/MRTK/Examples/Demos/StandardShader/Scenes/ClippingExamples.unity
Assets/MRTK/Examples/Demos/UX/BoundingBox/Scenes/BoundingBoxExamples.unity
Assets/MRTK/Examples/Demos/UX/ObjectManipulator/Scenes/ObjectManipulatorExample.unity
Assets/MRTK/Examples/Demos/UX/ObjectManipulator/Scenes/ObjectManipulatorExamplePhysics.unity
Assets/MRTK/Examples/Experimental/ColorPicker/ColorPickerExample.unity
Assets/MRTK/Examples/Experimental/ColorPicker/Prefabs/ColorPickerPrefab.prefab
Assets/MRTK/Examples/Experimental/Dock/DockExample.unity
Assets/MRTK/Examples/Experimental/Elastic/Scenes/ElasticSystemExamples.unity
Assets/MRTK/Examples/Experimental/ExamplesHub/Prefabs/ToggleFeaturesPanelExamplesHub.prefab
Assets/MRTK/Examples/Experimental/ExamplesHub/Prefabs/ToggleFeaturesPanelExamplesHubStore.prefab
Assets/MRTK/Examples/Experimental/ExamplesHub/Prefabs/ToggleFeaturesPanelHubHand.prefab
Assets/MRTK/Examples/Experimental/HandMenuLayout/Prefabs/PalmUpHandMenu_AboveFingertips_3x4.prefab
Assets/MRTK/Examples/Experimental/TouchSlider/Scenes/TouchSliderExample.unity

Update the prefabs in the examples package to pre-save the required ConstraintManager component.
Fixes : #9802

Fix some missed "missing ConstraintManager" warnings in the Examples package 

---

Assets/MRTK/Examples/Demos/Input/Scenes/Speech/SpeechInputExamples.unity

Updating the Speech Input Examples scene to include examples of using speech inputs with common interactables like buttons

Updating the speech input examples scene with interactables

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

Add logging to XR pipeline/package installation related operations so that the user can know the exact operations the configurator performed to the project.

Log pipeline related operations done by the configurator

---

ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

This change increments the version number used in CI / Packaging

increment the version to 2.6.2

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs

Repeat of PR https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9874
- Fixes: #9873  .
>
>
>
>
> git checkout …

Fix for OpenXR hand meshes with non-identity transform on Playspace.

---

Assets/MRTK/Core/Definitions/MixedRealityToolkitConfigurationProfile.cs
Assets/MRTK/Core/MRTK.Core.asmdef
Assets/MRTK/Core/Services/BaseDataProviderAccessCoreSystem.cs
Assets/MRTK/Core/Utilities/XRSettingsUtilities.cs

Improve the XR pipeline detection logic and change the name of the property to better align with its behavior.
- Fixes: #9817

Improve XR pipeline detection to prevent regression

---

Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs
Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs

This PR ensures users receive warning if AsyncCoroutineRunner is not properly set up in the scene when it is required.
- Fixes #9863

Fix some AsyncCoroutineRunner related issues

---

Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftControllerModelProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRReprojectionUpdater.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs

Since this assembly only builds for Windows, we should only try to call this code on Windows.
- Fixes: #9895

Fix building OpenXR for Android

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

Update SU observer to align with LoadHelprs

---

Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scripts/DemoSceneUnderstandingController.cs

Fixed an issue from SU from working when starting from the example hub scene (see #9905).

SU Demo script fix

---

pipelines/packageupmpublic.yaml

Re-add IsFinal

---

pipelines/packageupmpublic.yaml

Scope more under the ifs

---

scripts/packaging/createupmpackages.ps1

Updates the UPM packing script to copy the Authors.md file at the repo root to the Documentation~ folder.
Also cleans up some typos.

Copy the Authors.md file to our UPM packages

---

pipelines/docs-binaries.yml

Updates the docs binary pipeline to clean the checkout folder on every run. In tests, this appears to have mitigated our previous failures.

Update docs pipeline

---

README.md

Landing page updates:
- Moved Docs information to the 'Documentation' section.
- Applying updates from MSDocs landing page (supported platform table)

Moved Docs information to 'Documentation' section.

---

README.md

Add missing 'we've moved' callout

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Providers/UnityInput/UnityJoystickManager.cs
Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/ci-packaging-internal.yml
pipelines/ci-release.yml
pipelines/ci-weekly-internal.yml
pipelines/config/settings.yml
pipelines/docs-binaries.yml
pipelines/packageupmpublic.yaml
pipelines/templates/tasks/pack-upm.yml
scripts/packaging/createupmpackages.ps1

Cherry-picks over
* Due to CI pool changes
* Update internal CI to run on regular pool (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9944)
* Update docs pipeline (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9933)
* 2.7.0 regressions
* Experience Settings profile can now be set to None (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9982)
* Marked Unity Joystick Manager as supported on XR SDK pipeline (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9954)
* Packaging
* Add ability to repack in the packaging pipeline for properly versioned assemblies (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9928)
* Depends on Squash some syntax in the packing pipeline (https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9923) …

2.7.1 cherry-picks

---

Assets/MRTK/Core/Inspectors/Setup/MRTKVersionPopup.cs
Assets/MRTK/Core/Inspectors/Setup/MRTKVersionPopup.cs.meta
Assets/MRTK/Examples/Demos/PulseShader/Profile/PulseShaderSpatialAwarenessSystemProfile.asset
Assets/MRTK/Extensions/HandPhysicsService/Examples/HandPhysicsServiceExample.unity
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset

2.7.1 cherrypicks round 2

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

This PR updates the instructions for using the Mixed Reality OpenXR plugin to provide a better setup experience.
- Fixes: #10000.

Improve configurator instructions for OpenXR

---

Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs

Fixes the button icon set inpsectors in two ways.
1. no longer throws errors due to cascading EditorFoldoutGroups
2. Exceptions no longer thrown when preview textures aren't able to be displayed. Instead, the button config inspector displays appropriate warnings and N/A when the previews can't load
- Fixes: #9458, #9557

Fixes for the button iconset inspectors

---

.gitignore
ProjectSettings/PackageManagerSettings.asset
ProjectSettings/TimelineSettings.asset
ProjectSettings/UnityConnectSettings.asset
ProjectSettings/VersionControlSettings.asset

Unity's been adding some new project settings assets over the last couple releases. This PR adds the new ones (but not the changed ones, to maintain back compat with Unity 2018).

Update Unity settings assets

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
Assets/MRTK/Core/Providers/UnityInput/UnityJoystickManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs
Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs

Needed a manual merge (mostly around the version numbers having been incremented in both branches).

Merge 2.7.1 -> main

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/packaging/createupmpackages.ps1

Updates the packing/repacking regex to update the dependencies lines as well.

Update regex to catch dependencies

---

scripts/packaging/createupmpackages.ps1

Merge 2.7.2 -> main

---

Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs

Fix to the input animation script to prevent the hand mesh from behaving unexpectedly during playback.
Credits to @austinbhale for discovering and providing the fix 
- Fixes: #9831

austinbhale's hand mesh animation playback fix

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

The hand interaction examples had misaligned colliders, causing some near interactions to be wonky. This PR fixes that scene to behave properly.
old:
new:

Fixed hand interaction scene to have proper pinch slider colliders

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs

The actual bug was fixed on the Unity side, but this improves our messaging now that bug fixes are out across the board!
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8707

Improve PV camera version messages

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

Introduces a new `enum` in the `FollowMeToggle` class, which specifies the behavior of the optional interactable assigned to the script. As explained in #10070, sometimes the user of `FollowMeToggle` might want different behavior for the `Interactable`, depending on the state of the `FollowMeToggle` component.
- Fixes: #10070  .

Introducing an enum and controlling the behavior

---

Assets/MRTK/Core/Utilities/WebRequestRest/Response.cs
Assets/MRTK/Core/Utilities/WebRequestRest/ResponseUtils.cs
Assets/MRTK/Core/Utilities/WebRequestRest/ResponseUtils.cs.meta
Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs

Fixed freezing app when receiving data by Rest class
Added:
- waiting for webRequest text
Changes:
- public string ResponseBody to public async Task<string> GetResponseBody()
- added ResponseUtils with public static Func<byte[], Task<string>> BytesToString

Fixed freezing app when receiving data

---

pipelines/mergetool.yml

I left a stray line in #10022, causing the yml syntax to be poorly constructed. This PR fixes it.

Fix syntax in mergetool.yml

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandJointProvider.cs

Fixes an issue where the namespaces were incorrect when MROpenXR is installed.

Update usings to support OpenXR

---

Assets/MRTK/Core/Interfaces/Services/IMixedRealityService.cs

#7474 describes unexpected behavior that is by-design. This PR ensures that the code summaries provide information on this behavior. A doc change is incoming as well.
- Fixes: #7474

Update summary to clarify when Initialize runs

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs

Fixed a NullReferenceException issue in LinePointer

---

Assets/MRTK/Examples/Demos/Solvers/Scripts/SolverExampleManager.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/SolverHandlerInspector.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

Minor typo cleanup in a field and property related to solvers.

Fix handness -> handedness

---

Assets/MRTK/Tools/ReserializeAssetsUtility/ReserializeAssetsUtility.cs

Backporting some minor changes made in a recent porting effort.

Minor updates to ReserializeAssetsUtility.cs

---

README.md

Adding AWE 2021 Auggie Awards Banner

Adding AWE 2021 Auggie Awards Banner

---

Assets/MRTK/Tests/PlayModeTests/InputSystem/ConeCastTrackingTargetTest.cs.meta

Assign missing test icon

---

Assets/MRTK/Core/Providers/Hands/HandRay/HandRay.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedArticulatedHandPoses.cs
Assets/MRTK/Core/Utilities/CameraFOVChecker.cs
Assets/MRTK/Core/Utilities/Editor/Preferences/SerializableDictionary.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/FingerCursor.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs
Assets/MRTK/Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs

Revived an old branch from a while ago and added some assorted scripts I've had sitting in my working directory for a while.
Mostly code style and formatting, but also updated a private method in FingerCursor to actually use its parameter instead of the member field (which is what's passed in anyway...).

Assorted formatting and minor changes accumulated in my working dir

---

README.md

Updating AWE 2021 Auggie Awards Banner based on the official graphics

Updating AWE 2021 Auggie Awards Banner based on the official graphics

---

Assets/XR/Settings/Open XR Package Settings.asset

Updates the serialization in our sample project to the latest release.

Update Open XR Package Settings.asset

---

Assets/MRTK/Examples/Common/Prefabs/FingerChaser.prefab
Assets/MRTK/Examples/Demos/Input/Scenes/HandJointChaserExample.unity
Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs

This scene was still set up with obsolete values and not working on device.

Fix hand joint chaser in 2.7.3

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManagerProfile.cs
Assets/MRTK/Providers/Oculus/XRSDK/Profiles/DefaultOculusXRSDKDeviceManagerProfile.asset

* Oculus visualization now merged seemlessly with MRTK
* addressing code review comments
* Update Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Co-authored-by: Kurtis <kurtie@microsoft.com>
Co-authored-by: Kurtis <kurtie@microsoft.com>
Cherry-picks #10067. trying to deploy the quest gives errors without this fix

Oculus visualization now integrated with MRTK (#10067)

---

ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

When the 2.7.3 branch was created, we missed updating the version number. Update from 2.7.2 to 2.7.3

update version number to 2.7.3

---

Assets/MRTK/Examples/Common/Prefabs/FingerChaser.prefab
Assets/MRTK/Examples/Demos/Input/Scenes/HandJointChaserExample.unity
Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHubMainMenu.unity
Assets/MRTK/Examples/Experimental/SceneUnderstanding/Profiles/DemoSceneUnderstandingMixedRealityToolkitConfigurationProfile.asset
Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs

Merge 2.7.3 -> main

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs

The implementation of `TryGetNormalToNearestSurface()` for `PokePointer` always returned true, even when no proximate collider was found. This could cause zero-vectors to be returned by that function, which created mathematical errors and log spam down the line.
I've altered this implementation to return false when there's no nearby collider and set the output to a valid unit vector regardless (this is the same output as `GrabPointer` in this situation).

Prevent PokePointer from returning zero-vector normals

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs
Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs
Assets/MRTK/Providers/LeapMotion/LeapMotionDeviceManager.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKCameraSettings.cs
Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs
Assets/MRTK/Services/InputSystem/ConeCastGazeProvider.cs
Assets/MRTK/Services/InputSystem/GazeConePointer.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
Assets/MRTK/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/ChangeActiveProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/Components/TestInputFocusListener.cs
Assets/MRTK/Tests/PlayModeTests/DwellTests.cs
Assets/MRTK/Tests/PlayModeTests/LoadingIndicatorTests.cs
Assets/MRTK/Tests/PlayModeTests/PinchSliderTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs
Assets/MRTK/Tests/PlayModeTests/ProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs
Assets/MRTK/Tools/AssetSwapUtility/AssetSwapUtility.cs
Assets/MRTK/Tools/MSBuild/Scripts/CSProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

An initial quick auto-formatting pass in VS. It's been a while!
Splitting this up into multiple PRs for ease of review.

Formatting pass 3

---

Assets/MRTK/Core/Definitions/MixedRealityExperienceSettingsProfile.cs
Assets/MRTK/Core/Inspectors/MixedRealityShaderGUI.cs
Assets/MRTK/Core/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
Assets/MRTK/Core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Assets/MRTK/Core/Interfaces/Devices/IMixedRealityHandVisualizer.cs
Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityQueryablePointer.cs
Assets/MRTK/Core/Providers/BaseController.cs
Assets/MRTK/Core/Providers/BaseGenericInputSource.cs
Assets/MRTK/Core/Providers/GenericPointer.cs
Assets/MRTK/Core/Providers/UnityInput/UnityTouchDeviceManager.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Assets/MRTK/Core/Utilities/Editor/XRSettingsUtilities.cs
Assets/MRTK/Core/Utilities/SceneContent/MixedRealitySceneContent.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs
Assets/MRTK/Core/Utilities/XRSettingsUtilities.cs
Assets/MRTK/Examples/Common/Prefabs/HandMenuSliderAssets/Scripts/UpdateSliderTrackLine.cs
Assets/MRTK/Examples/Common/Scripts/Slider/ShowSliderValue.cs
Assets/MRTK/Examples/Common/Scripts/Slider/SliderChangeColor.cs
Assets/MRTK/Examples/Demos/Audio/Scripts/MicrophoneAmplitudeDemo.cs
Assets/MRTK/Examples/Demos/HandTracking/Scripts/LeapMotionOrientationDisplay.cs
Assets/MRTK/Examples/Demos/UX/ManipulationHandler/Scripts/ChangeManipulation.cs
Assets/MRTK/Examples/Demos/UX/ProgressIndicator/Scripts/ProgressIndicatorDemo.cs
Assets/MRTK/Examples/Demos/UX/Slider/Scripts/SliderLunarLander.cs
Assets/MRTK/Examples/Experimental/Joystick/JoystickSliders.cs
Assets/MRTK/Examples/Experimental/SceneUnderstanding/Scripts/DemoSceneUnderstandingController.cs

An initial quick auto-formatting pass in VS. It's been a while!
Splitting this up into multiple PRs for ease of review.

Formatting pass 1

---

Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs

the press intensity property no longer throws exceptions
- Fixes: #10388

Changed press intensity error to a warning

---

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityQueryablePointer.cs
Assets/MRTK/Core/Utilities/Lines/DataProviders/BaseMixedRealityLineDataProvider.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Services/InputSystem/GazeConePointer.cs

Fixing a regression introduced all the way back in #10146 😬
Part of the fix necessary to make certain raycast interactions feel sane again
- Helps with #10387, #10126 and probably a few others
Old:
New:

Fixed issues where rayDistance and rayStepIndex were calculated incorrectly

---

scripts/packaging/createbinariesfordocs.ps1

Update log file name

---

scripts/packaging/createbinariesfordocs.ps1

Add the public nuget.org feed manually

Add the public nuget.org feed manually

---

pipelines/docs-binaries.yml

Add a step to install nuget

---

scripts/packaging/createbinariesfordocs.ps1

Remove unnecessary step

---

scripts/packaging/createbinariesfordocs.ps1

Add nuget source manually (again)!

Add nuget source

---

Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Core/Providers/InputSimulation/BaseInputSimulationService.cs
Assets/MRTK/SDK/Features/UX/Prefabs/RiggedHandVisualizer/RiggedHandLeft.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/RiggedHandVisualizer/RiggedHandRight.prefab
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerVisualizationProfile.asset
Assets/MRTK/Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs

This PR unifies the articulated hand visualization scripts into a single script, removing the need to have different hand visual implementations between hololens and other platforms.

Unifying articulated hand visualizer scripts

---

Assets/MRTK/Providers/LeapMotion/LeapMotionDeviceManager.cs

A local field was removed in #10440 but not updated in all cases.

Fix build break in LeapMotionDeviceManager.cs

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs

The previous define was confusing and appeared to be referring to the other OpenXR package.

Change to MSFT_OPENXR_1_4_0_OR_NEWER

---

Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerVisualizationProfile.asset
Assets/MRTK/SDK/StandardAssets/Controllers/DebugControllers/OculusControllerLeft.prefab
Assets/MRTK/SDK/StandardAssets/Controllers/DebugControllers/OculusControllerRight.prefab

Removes a couple duplicate entries in the visualization profile, as well as fixing some prefab serialization for the Oculus fallbacks.

Fix serialization for controller/hand visualization

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/packaging/updateMRTKVersion.ps1

Update version to 2.9.0

---

Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs

Wraps some variable with the OCULUSINTEGRATION_PRESENT flag

Fixing bug due to missing flag ifdefs

---

pipelines/ci-packaging-internal.yml
pipelines/docs-binaries.yml
pipelines/pr-internal.yaml

Fixes a build issue with the MRTK2 internal CI.

Add demand due to current image issue

---

Assets/MRTK/Core/Utilities/Async/AssemblyInfo.cs
Assets/MRTK/Core/Utilities/Async/AssemblyInfo.cs.meta
Assets/MRTK/Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs
Assets/MRTK/Tests/PlayModeTests/SpherePointerTests.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs

This script logs whenever it's accessed and added manually to the scene. With this change, we now ensure the test scene is more properly configured and remove the extra log.

Add AsyncCoroutineRunner manually to clean up test logs

---

.gitignore
scripts/test/generate_repeat_tests.py
scripts/test/run_repeat_tests.ps1

Updates some paths to catch both main and mrtk3

Format additional scripts and update .gitignore for cross-branch compat

---

.github/workflows/docs_mrtk2.yaml
scripts/ci/validatedocs.ps1

Part of getting mrtk3 CI/PR validation working is porting us off the AIPMR instance 😬

Port mrtk_docs pipeline to GitHub actions

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitHelpLinks.cs

Update the links embedded in our code to aka.ms links.

Update the links to our docs and API ref page

---

.gitignore
Pipelines/Templates/Tasks/build-unity.yaml
Pipelines/Templates/unity.yaml
Pipelines/pr.yaml
Tooling/Test/generate_repeat_tests.py
Tooling/Test/run_playmode_tests.ps1
Tooling/Test/run_repeat_tests.ps1
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/BuildApp.cs
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/BuildApp.cs.meta
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/MRTK.Examples.Build.asmdef
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/MRTK.Examples.Build.asmdef.meta
UnityProjects/MRTKDevTemplate/Packages/manifest.json
pipelines/Config/settings.yaml
pipelines/Scripts/pack-upm.ps1
pipelines/Templates/Tasks/build-appx.yaml
pipelines/Templates/upm.yaml
pipelines/UPM/Documentation~/README.md
pipelines/ci.yaml

Adds all the initial infrastructure needed to test and further build out our pipelines for MRTK3.

Add initial CI and PR validation pipelines for MRTK3

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitHelpLinks.cs
Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs
Assets/MRTK/Core/Providers/Hands/HandPoseUtils.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/CameraFOVChecker.cs
Assets/MRTK/Core/Utilities/CoreServices.cs
Assets/MRTK/Core/Utilities/MixedRealityServiceRegistry.cs
Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftOpenXRGGVHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftOpenXRGGVHand.cs.meta
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Assets/MRTK/SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/VisualUtils.cs
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/SDK/Features/Utilities/LRUCache.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Tests/PlayModeTests/Core/Utilities/LRUCacheUnitTests.cs
Packages/manifest.json

Merge 2.8.1 -> main

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

Update to 2.8.2

---

Pipelines/Templates/Tasks/build-appx.yaml
Pipelines/Templates/unity.yaml
Pipelines/Templates/upm.yaml
Pipelines/ci.yaml
Pipelines/pr.yaml

Enable Unity build in pipelines

Enable Unity build in pipelines

---

Authors.md
scripts/ci/contributors.py

Ran scripts/ci/contributors.py to update our Authors file.

Update Authors list

---

Pipelines/Templates/Tasks/publish-upm.yaml
Pipelines/Templates/upm.yaml

Update relative paths in CI

---

com.microsoft.mrtk.accessibility/Documentation~/Accessibility.md
com.microsoft.mrtk.audio/Documentation~/Audio.md
com.microsoft.mrtk.data/Documentation~/DataBinding.md
com.microsoft.mrtk.environment/Documentation~/Environment.md
com.microsoft.mrtk.environment/package.json

Fixes some typos and updates some formatting.

Update some in-package descriptions and docs

---

pipelines/ci-packaging-internal.yml
pipelines/templates/tasks/pack-upm.yml
scripts/packaging/createupmpackages.ps1

Updates the CI build number to display the same number the preview packages are built as.

Update CI displayed build number

---

cgmanifest.json

WIP for checking in a new package dependency.

Updating for component governance

---

Pipelines/Templates/Tasks/build-unity.yaml
Pipelines/Templates/unity.yaml
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/BuildApp.cs

* Updates the build script to explicitly set the exit code based on build success
* Updates the Unity build steps to use a cache server

Pipeline updates

---

Pipelines/Config/settings.yaml

Bump CI to pre.7

---

com.microsoft.mrtk.spatialmanipulation/Utilities/SolverHandler.cs

The list wasn't initialized anywhere!

Fix null ref in solver registration

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/SampleSceneHelper/SampleSceneHandMenu.prefab
UnityProjects/MRTKDevTemplate/Assets/Scenes/FontIconExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/InputFieldExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VirtualizedScrollRectList.unity

Ensures all sample scenes include the SampleSceneHandMenu for scene navigation + settings. Also, fixes icons.
- Fixes #10757

Ensuring all sample scenes have SampleSceneHandMenu + fixing icons

---

com.microsoft.mrtk.windowsspeech/MRTK.Speech.Windows.asmdef
com.microsoft.mrtk.windowsspeech/Subsystems/WindowsPhraseRecognitionSubsystem.cs

Allow users to use the "select" keyword on HoloLens 2 via a new API in the Mixed Reality OpenXR Plugin.

Fix the select voice command keyword for MRTK3

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.core/package.json
com.microsoft.mrtk.input/package.json
com.microsoft.mrtk.spatialmanipulation/package.json
com.microsoft.mrtk.uxcore/package.json

Bumping XRI to 2.0.2. Not going to their 2.1 preview (yet)!

Bump XRI to 2.0.2

---

Pipelines/Templates/docs.yaml
Pipelines/ci.yaml
Pipelines/pr.yaml

Create a new pipeline to generate the binaries for API reference docs.

Create a pipeline for MRTK3 API reference docs generation

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioLoFiExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioOcclusionExample.unity

Make it easier to test the audio samples :)
Fixes: #10805

[pre.8] add sample scene hand menu to audio samples - issue 10805

---

Pipelines/pr.yaml

Remove the docs binaries gen job from pr.yaml

---

Pipelines/Config/settings.yaml

Bumping CI to pre.8

---

Pipelines/Config/settings.yaml

Bumping CI to pre.9

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/ScrollRectCurve.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/SystemKeyboardExample.cs

There were a couple a minor warnings; this resolves them.

Cleaning up minor warnings

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

Fixes an issue on the Quest runtime which was causing hand joints to be incorrectly reported.

Update MR OpenXR to 1.4.4

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/SampleSceneHelper/SampleSceneHandMenu.prefab
UnityProjects/MRTKDevTemplate/Assets/Scripts/SampleSceneHandMenu.cs
com.microsoft.mrtk.spatialmanipulation/BoundsControl/BoundsControl.cs

- Resolves #10810 
- Fixes #10806 , BoundsControl wasn't automatically getting a reference to its ConstraintManager!

Adds scene name to hand menu, fix BoundsControl not finding ConstraintManagers

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioLoFiExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/BandPassFilterSelection.cs
com.microsoft.mrtk.uxcore/Toggle/ToggleCollection.cs

This rewrites the UI in LoFiExampleScene, as well as fixes #10859 , which I'm surprised nobody found by this point!
- Fixes #10859 
- Fixes #10822

Fixes UI in the LoFiExample scene, as well as fixing a sneaky ToggleCollection bug

---

com.microsoft.mrtk.input/Subsystems/Hands/OpenXRHandsSubsystem.cs

Removes a stray IsTracked check that was intended to be removed in #10704 .

Removing stray IsTracked check from OpenXRHandsSubsystem

---

com.microsoft.mrtk.input/Subsystems/Hands/OpenXRHandsSubsystem.cs

#10861 actually broke poke interactions on device, so, this fixes that.

Fixing poke regression

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasExample.unity

Fixes the last few objects that were missing `MinMaxScaleConstraints`.
- Fixes: #10865

Last few missing MinMaxScaleConstraints

---

com.microsoft.mrtk.core/Editor/AboutMRTK.cs

Let users know that they are waiting for package info to load on the about screen so they don't just look at an empty list.

Inform users about loading on the about window

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.core/package.json
com.microsoft.mrtk.input/MRTK.Input.asmdef
com.microsoft.mrtk.input/package.json
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/MRTK.SpatialManipulation.RuntimeTests.asmdef

Clean up some dependencies that are not necessary.

Clean up dependencies in ASMDEFs and manifests

---

com.microsoft.mrtk.core/Interactors/IPokeInteractor.cs
com.microsoft.mrtk.input/Assets/Prefabs/MRTK Hand Controller.prefab
com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs
com.microsoft.mrtk.input/InteractionModes/FlatScreenModeDetector.cs
com.microsoft.mrtk.input/InteractionModes/IInteractionModeDetector.cs
com.microsoft.mrtk.input/InteractionModes/InteractionDetector.cs
com.microsoft.mrtk.input/Interactors/Gaze/FuzzyGazeInteractor.cs
com.microsoft.mrtk.input/Interactors/Gaze/GazeInteractor.cs
com.microsoft.mrtk.input/Interactors/GazePinch/GazePinchInteractor.cs
com.microsoft.mrtk.input/Interactors/HandJointInteractor.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/IMRTKInteractorVisuals.cs
com.microsoft.mrtk.input/Interactors/Poke/PokeInteractor.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractor.cs
com.microsoft.mrtk.spatialmanipulation/ObjectManipulator/MoveLogics/UnifiedMoveLogic.cs
com.microsoft.mrtk.uxcore/Interop/UGUIInputAdapter.cs

* Organizes our interactors into regions according to which interface/class the method is coming from
* Updates some typos and formatting stuff

Assorted interactor organization

---

Pipelines/Config/settings.yaml

Bumping CI to pre.10

---

Assets/MRTK/Core/Definitions/SceneSystem/RuntimeRenderSettings.cs
Assets/MRTK/Core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Assets/MRTK/Core/Utilities/PlatformUtility.cs
Assets/MRTK/Core/Utilities/Scenes/EditorSceneUtils.cs
Assets/MRTK/Core/Utilities/WebRequestRest/Rest.cs
Assets/MRTK/SDK/Editor/Inspectors/Exp/InteractiveEl/CompressableButtonInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/PressableButtonInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Sliders/PinchSliderInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Tooltips/ToolTipInspector.cs
Assets/MRTK/Services/SceneSystem/MixedRealitySceneSystem.cs

Updates MRTK2 with all changed APIs in Unity 2022.
- Fixes: #10892

Fix MRTK2 in Unity 2022

---

scripts/packaging/createbinariesfordocs.ps1

Helps with debugging when the pipeline fails

Log build log if docs build failed

---

.github/workflows/pr_labeler.yaml

Adding PR labeling hooks for editing.

Adjusting pull_request_target hooks

---

com.microsoft.mrtk.input/Interactors/GazePinch/GazePinchInteractor.cs
com.microsoft.mrtk.input/Interactors/Grab/GrabInteractor.cs
com.microsoft.mrtk.input/Interactors/HandJointInteractor.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractor.cs
com.microsoft.mrtk.input/Utilities/FollowJoint.cs
com.microsoft.mrtk.input/Utilities/PoseSource/FallbackCompositePoseSource.cs
com.microsoft.mrtk.input/Utilities/PoseSource/HandBasedPoseSource.cs
com.microsoft.mrtk.input/Utilities/PoseSource/HandBasedPoseSource.cs.meta
com.microsoft.mrtk.input/Utilities/PoseSource/HandJointPoseSource.cs
com.microsoft.mrtk.input/Utilities/PoseSource/PinchPoseSource.cs

Follow-up to #10897. For some work I'm doing, refactoring out this base class will be useful!

Refactor out HandBasedPoseSource

---

.github/workflows/validation_mrtk3.yaml

Ported out from #10726. Migrates our validation action to Ubuntu to ensure our pwsh scripts are usable cross-platform.

Migrating to Ubuntu for validation

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

Update to MR OpenXR to 1.5.0.
Also sets "Conforming to Controller" as the default hand joint state for motion controller hand joints.

Update MR OpenXR to 1.5.0

---

UnityProjects/MRTKDevTemplate/ProjectSettings/BurstAotSettings_Android.json
UnityProjects/MRTKDevTemplate/ProjectSettings/BurstAotSettings_StandaloneWindows.json
UnityProjects/MRTKDevTemplate/ProjectSettings/BurstAotSettings_WSAPlayer.json
UnityProjects/MRTKDevTemplate/ProjectSettings/CommonBurstAotSettings.json

These keep being generated on build, now that we have Burst as a dependency via GLTFast. May as well check them in!

Check in BurstAotSettings

---

Pipelines/Scripts/validatecode.ps1

Fix some typos in the CI script.

Fix typos in validatecode.ps1

---

com.microsoft.mrtk.core/Utilities/CameraFOVChecker.cs

Update CameraFOVChecker.cs to use new tuple syntax.
Followup to #10977

Update CameraFOVChecker.cs to use new tuple syntax

---

com.microsoft.mrtk.input/Visualizers/ControllerVisualizer/ControllerVisualizer.cs

Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10787#discussion_r965356548

Remove unused variable from ControllerVisualizer.cs

---

com.microsoft.mrtk.core/Subsystems/Hands/HandsAggregatorSubsystem.cs
com.microsoft.mrtk.core/Utilities/HandBounds.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/RingReticle.cs
com.microsoft.mrtk.input/Interactors/Poke/PokeInteractor.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractorVisual.cs
com.microsoft.mrtk.input/Simulation/Devices/SimulatedController.cs
com.microsoft.mrtk.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
com.microsoft.mrtk.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs
com.microsoft.mrtk.input/Visualizers/RiggedHandVisualizer/RiggedHandMeshVisualizer.cs
com.microsoft.mrtk.uxcore/Interop/UGUIInputAdapterDraggable.cs

Assorted updates made during various investigations.

Assorted style, formatting, and general updates

---

com.microsoft.mrtk.input/Interactors/InteractorVisuals/BaseReticleVisual.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/MRTKRayReticleVisual.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/RingReticle.cs

Followup PR addressing some additional comments left on #11022

Reticle Visual Feedback changes

---

UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

@Cameron-Micka made some GREAT improvements to the Visual Profiler, moving it from 1.x to 2.x (https://github.com/microsoft/VisualProfiler-Unity/pull/11)! We've been including it in this project for testing purposes (and encouraging others to use it 🙂), so this moves us onto the latest and greatest.

Update to 2.2.0 version of Visual Profiler

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.core/package.json
com.microsoft.mrtk.input/package.json

Bumping up the version now that 2.1.0 is officially released.

Update required XR Core Utils version to 2.1.0

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/LegacyConstraintsExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/LegacyConstraintsExample.unity.meta
com.microsoft.mrtk.spatialmanipulation/Constraints/FixedDistanceConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/FixedRotationToUserConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/FixedRotationToWorldConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/MaintainApparentSizeConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/MoveAxisConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/RotationAxisConstraint.cs

#11085 introduced a bunch of warnings associated with the old constraints; this fixes those and adds a sample scene (with a comment mentioning we're working on a replacement)
- Fixes #11103

[pre.12 blocking] Fixing constraint warnings, add sample scene

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

I noticed that this message was slightly out of date.

Clarify OpenXR support statement 

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/SampleSceneHelper/DescriptionPanel.prefab
UnityProjects/MRTKDevTemplate/Assets/Scenes/SampleEmptyMRTKScene.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VanillaUGUIExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VanillaUGUIExample.unity.meta

@MaxWang-MS and others have been waiting for this for a little while now! This is a very simple example scene showing how to use vanilla/unmodified UGUI canvases. 
- Resolves #11114 
- Removes unnecessary GraphicRaycaster from DescriptionPanel to save us a few milliseconds every once in a while :)
- Fixes our sample empty scene to not have the simulator disabled

Vanilla UGUI demo scene

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Post-release version incrementation

Update to pre.12

---

UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.accessibility/.npmrc
com.microsoft.mrtk.audio/.npmrc
com.microsoft.mrtk.core/.npmrc
com.microsoft.mrtk.data/.npmrc
com.microsoft.mrtk.diagnostics/.npmrc
com.microsoft.mrtk.extendedassets/.npmrc
com.microsoft.mrtk.input/.npmrc
com.microsoft.mrtk.spatialmanipulation/.npmrc
com.microsoft.mrtk.standardassets/.npmrc
com.microsoft.mrtk.tools/.npmrc
com.microsoft.mrtk.uxcomponents.noncanvas/.npmrc
com.microsoft.mrtk.uxcomponents/.npmrc
com.microsoft.mrtk.uxcore/.npmrc
com.microsoft.mrtk.windowsspeech/.npmrc

[MSFT compliance]
Fixes: "Node.js project(s) are missing feed configuration"
Also updates our `packages-lock.json` to the latest state of the project.

Add .npmrc files for feed hardening

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs

Makes the GGV pointer use the registered raycast provider
- Fixes: #11140

Change GGVPointer to use registered raycast provider

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Update to MROpenXR Plugin 1.6.0

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioOcclusionExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasUITearsheet.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeGazeExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/FontIconExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandMenuExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/InteractableButtonExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/LegacyConstraintsExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/MagicWindowExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/NearMenuExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/TopNavigationExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/UITearSheet.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VanillaUGUIExample.unity

Reserialize sample scenes

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/EventSystem.prefab
UnityProjects/MRTKDevTemplate/Assets/Prefabs/EventSystem.prefab.meta
UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasUITearsheet.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/DialogExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeGazeExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/FontIconExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandMenuExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/InputFieldExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/InteractableButtonExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/LegacyConstraintsExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/MagicWindowExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/NearMenuExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/ObjectBarExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/SampleEmptyMRTKScene.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/SlateDrawingExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/SpatialMappingExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/ToggleCollectionExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/TopNavigationExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/UIBackplateExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/UITearSheet.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VanillaUGUIExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/VirtualizedScrollRectList.unity

A minor rework of our sample scenes to use a specific sample prefab with an `EventSystem` and an `XRUIInputModule` in place.

Refactor out EventSystem.prefab for sample scenes

---

Assets/MRTK/Providers/OpenXR/Editor/MRTK.OpenXR.Editor.asmdef
Assets/MRTK/Providers/OpenXR/Editor/OpenXRCameraSettingsProfileInspector.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityCameraSettingsProfileInspector.cs

Adds some clarification around how this is handled in Unity with OpenXR. MR docs updates incoming...
- Fixes #11117

Add OpenXR "render from PV cam" note

---

com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs
com.microsoft.mrtk.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs
com.microsoft.mrtk.input/Utilities/InputActionExtensions.cs
com.microsoft.mrtk.input/Utilities/PoseSource/InputActionPoseSource.cs

This seemed like a useful extension method!

Refactor out HasAnyControls()

---

Assets/MRTK/Providers/OpenXR/Editor/OpenXRCameraSettingsProfileInspector.cs

Should fix the docs build for real this time.

Scope mrcSettingsButtonContent behind the same define that it's used in

---

README.md

Update info regarding the MRTK2 tutorial.

Update MRTK2 README

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml

Update version numbers to 2.8.3

Update version numbers to 2.8.3

---

Authors.md
scripts/ci/contributors.py

Update authors list for 2.8.3

---

.editorconfig
Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityQueryablePointer.cs
Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Core/Utilities/CoreServices.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManagerProfile.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftOpenXRGGVHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/MeshOutline/BaseMeshOutlineInspector.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Scripts/Controllers/WindowsMixedRealityControllerVisualizer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/ShellHandRayPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/ReorientContent.cs
Assets/MRTK/Tests/EditModeTests/Tools/MigrationToolTests.cs
Assets/MRTK/Tests/PlayModeTests/NearInteractionTouchableTests.cs

Probably should have done this before 2.8.3, but may as well catch the next train!

Formatting pass

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

Fixes #11302 
https://github.com/microsoft/OpenXR-Unity-MixedReality-Samples/releases/tag/v1.7.0

Upgrade to MR OpenXR 1.7.0

---

com.microsoft.mrtk.uxcomponents.noncanvas/Button/128x32/PressableButton_128x32mm_TextOnly.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/Empty Button.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/PressableButton_Custom_Cube.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/PressableButton_Custom_Cylinder.prefab
com.microsoft.mrtk.uxcomponents/NearMenu/NearMenuBase.prefab

This reverts commit 4b1b4ad6c30cf541f4aa14fb344e7f2e149d5fa4 to fix PR validation.

Revert "Audio spatializer support part 2:  add configuration script to root prefabs (#11285)"

---

Pipelines/Templates/unity.yaml
Pipelines/ci.yaml
Pipelines/pr.yaml
UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset

Splits out the builds into different jobs, adds an Android build to PR validation, and fix the Android build.

Fix Android build, refactor build pipeline, add Android build to PR validation

---

README.md

Updates the readme with @MaxWang-MS's changes from https://github.com/MicrosoftDocs/mixed-reality/commit/a5b6c41d0c723e9d801e114feed792bc44af3d1d.

Update MRTK2 README.md

---

Assets/MRTK/Core/Providers/InputSimulation/KeyBinding.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboard.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboardBase.cs

Starting my end-of-year clean-up of local branches 😅

Formatting and auto properties

---

Assets/MRTK/Core/Providers/InputSimulation/SimulatedControllerDataProvider.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandDataProvider.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedMotionControllerDataProvider.cs

Found another branch from 2020 😬 mostly style updates

Updating SimulatedControllerDataProvider.cs and SimulatedHandDataProvider.cs

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

MRTK3 pre.13 is released! https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11351
Time to bump preview tag.

Bumping to pre.13

---

com.microsoft.mrtk.windowsspeech/Subsystems/TextToSpeech/WindowsTextToSpeechSubsystem.cs

Minor warning fix.
- Removes duplicate using statement

Fixing using/namespace warning

---

UnityProjects/MRTKDevTemplate/Assets/BuildAssets/BuildApp.cs
UnityProjects/MRTKDevTemplate/Assets/MRTK.Generated/MRTKSettings.asset
UnityProjects/MRTKDevTemplate/Assets/Profiles/MRTKSamplesProfile.asset
UnityProjects/MRTKDevTemplate/Assets/Profiles/MRTKSamplesProfile.asset.meta

Add all most of the sample scenes, ensure that TMPro gets added to the pipeline builds, create a new MRTK3 profile that enables the dictation subsystem and performance stats subsystem for use with the sample scenes.
>
>
> commands (substituting {PR_ID} with …

Changes to make life easier for manual testing.

---

Pipelines/Templates/unity.yaml
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/BuildApp.cs

Remove TMPro import in command line builds.  It doesn't work in the command line, or as a separate step in the pipeline yaml.  More research is needed.  We may be able to migrate to TextCore now that we are on 2021.
>
>
> commands (substituting {PR_ID} with …

Remove TMPro import in command line builds

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Updating the `MRTK3's` preview version to -pre15.
-pre15 was already released.  In the future updating this number should happen prior to releasing.  The release notes for 3.0.0-pre15 can be found at:
- https://github.com/microsoft/MixedRealityToolkit-Unity/discussions/11536
>
>
> As a reviewer, it is possible to check out this change locally by …

Updating MRTK3's preview version to 15

---

Pipelines/Scripts/repackage-for-release.ps1
Pipelines/Templates/upm.yaml
Pipelines/rc.yaml

Creates a new pipeline to create the package names as described in #11556.  
Creates a repackage script to take release candidate packages and reversion them for release
- Fixes: #11556 .
>
> …

Create a release candidate pipeline

---

Pipelines/rc.yaml

Disable CI and PR triggers for the release candidate pipeline

Disable CI and PR triggers for the release candidate pipeline

---

Pipelines/Config/settings.yaml

Updating version tag to -pre.16

Updating MRTK3 version tag to -pre.16

---

Pipelines/Config/settings.yaml

Updating version tag to -pre.16

Updating MRTK3 version tag to -pre.16 (#11577)

---

com.microsoft.mrtk.core/Subsystems/Speech/TextToSpeechSubsystem.cs
com.microsoft.mrtk.core/Utilities/Attributes/VariableRangeAttribute.cs
com.microsoft.mrtk.core/Utilities/TransformFlags.cs
com.microsoft.mrtk.input/Utilities/HandDataContainer.cs

Add comment blocks to some classes and methods for doc generation
>
>
>
>

Adding missing comment blocks

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Updating MRTK3 version to pre.17

Updating MRTK3 version to pre.17

---

.github/ISSUE_TEMPLATE/bug-report.md

In some cases, a bug is opened for something not released yet, or against source code in the git repository. In these cases, the bug opener should provide a commit #.

Update bug-report.md to include commit #

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasUITearsheet.unity
com.microsoft.mrtk.uxcomponents/ToggleIndicators/Checkbox.prefab
com.microsoft.mrtk.uxcomponents/ToggleIndicators/ToggleSwitch.prefab

Changing depth of toggle dots and checkboxes to help with z-fighting
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11518

Fixing Z-Fighting with MRTK3 canvas toggles 

---

com.microsoft.mrtk.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs

Exposes transformSmoothingLogicType as a public property. 
- Fixes: #11593.

Add TransformSmoothingLogicType  to Object Manipulator

---

com.microsoft.mrtk.input/Controllers/ArticulatedHandControllerState.cs
com.microsoft.mrtk.input/Interactors/GazePinch/GazePinchInteractor.cs
com.microsoft.mrtk.input/Interactors/HandJointInteractor.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractor.cs
com.microsoft.mrtk.input/Subsystems/Hands/OpenXRHandsSubsystem.cs
com.microsoft.mrtk.input/Subsystems/Hands/XRSDKHandsSubsystem.cs
com.microsoft.mrtk.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
com.microsoft.mrtk.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs

Fixing MRTK3 bugs with <summary> blocks...and adding a couple more summaries,
This resolves some warnings and errors in document generation.

Fixing MRTK3 bugs with <summary> blocks...and adding a couple more summaries

---

UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.accessibility/package.json
com.microsoft.mrtk.input/package.json
com.microsoft.mrtk.standardassets/package.json
com.microsoft.mrtk.uxcomponents/package.json
com.microsoft.mrtk.uxcore/package.json

Update GraphicsTools package to 0.5.12 in samples and package dependencies
- Fixes: #11584 .
>
>
>
>
> git checkout …

Update GraphicsTools package to 0.5.12 in samples and package dependencies

---

com.microsoft.mrtk.uxcore/Tests/Runtime/StateVisualizerTests.cs

Add more delay time to frequently failing unit test
>
>
>
>

Add more delay time to frequently failing unit test

---

com.microsoft.mrtk.core/Configuration/MRTKProfile.cs
com.microsoft.mrtk.core/Experimental/Interactables/InteractableEventRouter.cs
com.microsoft.mrtk.core/Interactables/IScrollable.cs
com.microsoft.mrtk.core/Interactables/MRTKBaseInteractable.cs
com.microsoft.mrtk.core/Interactables/StatefulInteractable.cs
com.microsoft.mrtk.core/Interactors/IProxyInteractor.cs
com.microsoft.mrtk.core/Subsystems/Hands/HandsAggregatorSubsystem.cs
com.microsoft.mrtk.core/Subsystems/Hands/IHandsAggregatorSubsystem.cs
com.microsoft.mrtk.core/Subsystems/MRTKSubsystemAttribute.cs
com.microsoft.mrtk.core/Subsystems/Speech/TextToSpeechSubsystemDescriptor.cs
com.microsoft.mrtk.core/Utilities/Attributes/LabelWidthAttribute.cs
com.microsoft.mrtk.core/Utilities/ColorUtilities.cs
com.microsoft.mrtk.core/Utilities/ConfigureSpatializationSettings.cs
com.microsoft.mrtk.core/Utilities/PoseUtilities.cs
com.microsoft.mrtk.core/Utilities/TimedFlag.cs

Fixing summary/remarks block errors in MRTK3 code base
There were numerous malformed summary comments.  Fixing these.

Fixing summary/remarks block errors in MRTK3 code base

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Updating MRTK3 version to pre.18

Updating MRTK3 version to pre.18

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/SpatialMouseSample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/SpatialMouseSample.unity.meta

Adds a sample scene which includes the MRTKSpatialMouseController in the MRTK XR Rig. In this scene, the mouse can be used to select and move objects.

Add Sample Scene For Spatial Mouse

---

com.microsoft.mrtk.core/Camera/CameraSettingsManager.cs

Disable unknown display type warning when in editor
>
>
>
>

Disable unknown display type warning when in editor

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/DwellExample.unity

Added sample hand menu prefab to DwellExample scene to avoid getting stuck in the scene on manual test passes.
- Fixes: #11727 .
>
>
> …

Add sample hand menu to DwellExample (fix #11727)

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/DwellExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/SolverExampleManager.cs

Fix SolverExampleManager to use both left and right interactors
- Fixes: #11728 .
>
>
>
>

Fix SolverExampleManager to use both left and right interactors

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlRuntimeExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/BoundsControlRuntimeExample.cs

The bounding box runtime example needs to cycle around to start.  Also adding the ability to move bounding box runtime scene content.  And added simple profiler to this scene.
>
>
>
> git …

MRTK3's bounding box runtime example needs to cycle around to start.
