Assets/MRTK/Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoPointerProfile.asset
Assets/MRTK/Examples/Demos/Input/Scenes/DisablePointers/DisablePointersExamplePointerProfile.asset
Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubPointerProfile.asset
Assets/MRTK/Examples/Experimental/NonNativeKeyboard/Profiles/NonNativeKeyboardMixedRealityInputPointerProfile.asset
Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputPointerProfile.asset

As the platform feature begins roll-out, it'd be best to allow this feature to be opt-in until broad deployment of the feature is achieved.
Request from the platform team.

Turn off head gaze override by default

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs

When Unity is paused and then resumed, the InteractionManager gets in a bad state, and some InteractionSources never have their SourceLost event raised even if the sources are no longer relevant. This change is making the RemoveController API public so that applications like Remote Assist can work around this problem while waiting for a proper fix from Unity.
Here's the additional code we plan to add to our application as part of this workaround:
```
public class StaleInteractionSourceMonitor : MonoBehaviour
{
private static readonly TimeSpan staleSourceWaitTime = TimeSpan.FromMilliseconds(500);
private CancellationTokenSource cancelInteractionSourceCleanup;
private void OnApplicationPause(bool pause)
{
this.cancelInteractionSourceCleanup?.Cancel();
if (!pause)
{ …
```

Make the RemoveController API public so that applications can work around stale sources when the app is paused

---

Assets/MRTK/Core/Utilities/WindowsDevicePortal/DataStructures/DeviceInfo.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DevicePortal.cs
Assets/MRTK/Examples/Demos/Gltf/Scripts/TestGlbLoading.cs

This updates some of our usage of Rest.cs (i.e. our internal rest helper) to provide more fully qualified paths so that we can avoid conflicts with other code (i.e. Microsoft.Rest) when integrating with other Azure services.
Ideally we would just rename Rest.cs to RestHelper.cs, but unfortunately that would end up being a breaking change (of which the value here hasn't quite gotten there yet to ingest that breaking change pain).
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8104

Update references to Rest to specify more fully qualified names.

---

Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Prefabs/ScrollingOC_Objects_Plated32x32.prefab
Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Prefabs/ScrollingOC_PressableBtn_32x96.prefab
Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollableListPopulator.cs
Assets/MRTK/SDK/Experimental/Inspectors/ScrollingObjectCollection/ScrollingObjectCollectionInspector.cs
Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs.meta

This PR is part of Scroll View graduation and addresses the following issues / fixes:
#7444, #7445, #7447 .
- **Issue:** When user engage in a scroll drag, pointer, touch, and input event data have eventData.used set to true on Scroll Object Collection. MixedRealityInputSystem halts event dispatch if event data is used by global listener, so children buttons cannot proper receive OnTouchCompleted events. 
- **Fix:** using propagation event routing, events dispatch is not stopped when eventdata.used == true. Tests added.
#7446 .
- **Issue:** Scroll engage should trigger children interaction reset
- **Fix:** Instead of directly accessing children code, focus on children is unlocked and moved to a scroll background collider setup on runtime. Tests added.
#8068 .
- **Issue:** Scroll View …

Scroll Graduation 

---

Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

Fixed bug where we wouldn't add devices with either handtracking or controller inputdevicecharacterisitcs, but not both.

Fixed XRSDK not adding controller devices

---

Assets/MixedReality.Toolkit.Foundation.nuspec

This change fixes CI by removing link.xml and link.xml.meta from MixedReality.Toolkit.Foundation.nuspec

Fix CI: remove link.xml* from the foundation nuspec, it is auto generated

---

Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/BaseWindowsMixedRealityXRSDKSource.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs
Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
Assets/MRTK/Providers/XRSDK/CustomUsages.cs
Assets/MRTK/Providers/XRSDK/CustomUsages.cs.meta

1. Flips the generic handling of thumbstick / touchpad as primary / secondary axes to a more common case.
1. Overrides this flip in the WMR motion controller class correspondingly
1. Re-serializes a scene profile to match the repo's build state
1. Refactors out a WindowsMRUsage into an MRTK-defined `CustomUsage`, as the `pointerPosition` and `pointerRotation` features are shared across several packages.

Update mappings for generic XR SDK controller

---

Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKInputSystemProfile.asset

Adds the input simulation service to the XR SDK profile, so people can use it in-editor like they're used to.

Add input simulation to XRSDK profile

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityArticulatedHandDefinition.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs

To reduce the amount of platform-specific code stored in a strict inheritance chain, I've split out the mesh code from the controller definition concept. Now, WMR articulated hands can use the base definition, while still defining their own way of providing the hand mesh (in this case, directly from the Windows APIs. In the future, other hand definitions may grab this from XR plug-in extensions).

Split out WMR hand definition and WMR hand mesh provider

---

Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandDataProvider.cs
Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs

Object no longer shifts when performing a near grab interaction
- Fixes: #7936
Old behavior
New behavior

Fixed issue of object shifting when doing a near grab interaction

---

Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollableListPopulator.cs
Assets/MRTK/SDK/Experimental/Inspectors/ScrollingObjectCollection/ScrollingObjectCollectionInspector.cs
Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

This PR is part of Scroll View graduation and addresses the following issues / fixes:
#8148 
- **Issue:** Scroll Object collection should only engage if touch comes from front of scroll slate but currently the user is able to trigger scroll even when hand comes from behind, top, bottom or sides of the scroll slate
- **Fix:** Checking for previous position of poke pointer when touch started is handled
#8064 
- **Issue:** Currently there is no safe way of deleting child items from scroll collection. Destroying an object throw errors on console.
- **Fix:** Added methods for safely for adding and deleting items.
MissingReferenceException: The object of type 'BoxCollider' has been destroyed but you are still trying to access it.
Your script should either check if it is null or you should not …

scroll view graduation part 2

---

Assets/MRTK/SDK/Features/Input/Handlers/EyeTrackingTarget.cs

- Fixes: #8138
- Expose static variables to easily see which object eyes are currently gazing at, which item was last selected.
- Ensure mulitple click events are not raised from the same hand.
- Add methods for manually invoking OnTapDown and OnTapUp events
>
>
> As a reviewer, it is possible to check out this change locally by using the …

Several fixes and improvements to EyeTrackingTarget

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Pointers/SpherePointerInspector.cs
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ConicalGrabPointer.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/GrabPointer.prefab
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/Tests/PlayModeTests/SpherePointerTests.cs

Currently the IsNearObject detection is very sensitive, meaning the user can be subject to hand rays suddenly flickering in and out of view. This PR adds a smoothing factor in order to reduce the sensitivity of the IsNearObject detection. 
Basically, when an object is inside the query radius, it then has to be outside queryRadius * (1+smoothingFactor) to no longer be detected
- Fixes: #7938

Added smoothing factor for near object interaction

---

Assets/MRTK/Tools/DependencyWindow/DependencyWindow.cs

Files that exist within the unity `Packages` folder do not get tracked by the Dependency Window. This could be especially bad if the MRTK is a package within a project.
When a user clicks on a file within a package they are greeted with this cryptic warning:
With this change files within packages are correctly added to the dependency graph.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8161
> Please open the Dependency Window and note that more files are now searched.
>
>
>

The Dependency Window Now Searches for Meta Files Within Packages

---

pipelines/templates/tasks/versionmetadata.yml

#8133 had an incorrect path to a `.ps1` script for the CI to run, causing CI failures. This updates it to correctly point to [scripts/packaging/versionmetadata.ps1](https://github.com/microsoft/MixedRealityToolkit-Unity/blob/mrtk_development/scripts/packaging/versionmetadata.ps1)

Fix path to script for CI

---

Assets/MRTK/Core/Providers/Hands/HandBounds.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

The HandConstraint system is quite robust, including the HandConstraintPalmUp extension; however, there is currently no way to constrain to the palm joint. Different safe zones targeting modes are available, but the palm is not one of them!
This small PR adds the ability to target an `AtopPalm` safe zone, which is either generated with the same raycast method that is already used for the other safe zones (not recommended) or is directly bound to the palm joint (recommended).
Most notably, this palm-based target is compatible with all existing palm-up hand constraint systems (gaze targeting, proximity checks, etc).
Note: above-palm targeting is _NOT_ recommended for menu placement, as noted in the official hand menu documentation! This feature is intended to constrain/target _other_ kinds …

Re-implement hand bounds in local space, and added palm-based hand constraint safe zone targeting

---

pipelines/templates/tasks/versionmetadata.yml
scripts/packaging/versionmetadata.ps1

The CI yaml format uses `${{ ... }}` for parameter expansion, which is apparently different from how you can specify things like `$(Build.SourcesDirectory)` on the line above.
This was causing
>Formatted command: . 'f:\aipmragent_work\9\s\scripts\packaging\versionmetadata.ps1' -Directory: 'f:\aipmragent_work\9\s' -Version: '$(parameters.MRTKVersion)'
when CI runs.

Fix parameter expansion in CI versioning

---

Documentation/CrossPlatform/LeapMotionMRTK.md

Adds a note at the top of the leap documentation that says the leap provider can be used in editor while on UWP but not in a build.
Also clarifies that the provider only supports standalone builds at the top instead of only in step 5.
- Fixes: #7945

Add note about UWP in editor support for Leap

---

Assets/MRTK/SDK/Experimental/Dock/Dockable.cs

Currently dockable objects create assertion failures when being reenabled after being disabled in the docked state. The fix resets the docking state back to undocked when the object gets disabled.
- Fixes: #8065 .

Fix dockable object assertion failure

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

It turns out that with the styling changes in Unity 2019, the "selection" state doesn't actually show up when we use boldLabel. We could probably do some custom styling so that it has the right highlight/select thing, but in this case using the default selection style works:
Before:
After:
Unity 2018:

Update the MRTK object inspector tabs to properly render selection in Unity 2019

---

Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandDataProvider.cs

Add on to PR #8156 
The previous PR makes it so the pinch gesture isn't raised immediately when using hands free input simulation. This PR improves the responsiveness by making the pinch gesture get raised as soon as the pinch button is pressed.

Made hands free input simulation more responsive

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

The Cube2 object had two ObjectManipulator scripts, which were identical except for the manipulation events section.
The duplicate one ended up having the wrong ordered configuration:
i.e. on start, it would play the "end" audio clip, and on end it would play the start one.
Note that the other object manip script actually had the right configuration (i.e. start -> start, end ->end)
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8126

Remove duplicate ObjectManipulator script in HandInteractionExamples

---

Assets/MRTK/Core/Utilities/Gltf/Serialization/ConstructGltf.cs

The parser sometimes fails when one of the texture channels is null. This simply add a null check so things can continue on without failing.

Perform null check on glTF material parsing

---

Assets/MRTK/SDK/Features/Utilities/Solvers/TapToPlace.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

Due to the unpredictable execution order of Start() in Unity, StartPlacement() could be called by the Start() of another script before its own Start() is called, where expected behavior will not happen and user receives no warning.
- Fixes: #8080 .

Fix a TapToPlace issue caused by Start() execution order

---

Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs

As detailed in #8187, two-handed near interaction has a serious issue where the grab centroid is incorrectly calculated, resulting in erratic, incorrect grab behavior.
The root cause of this issue was that the code that is typically used for calculating hand-ray poses was also being used to compute the near-interaction grab point. This resulted in very wiggly and erratic grab poses being generated (because near interactions use fundamentally different principles than hand rays.) The main fix is to simply use the grab-centroid instead of the rotation-aware pose for two-handed interactions when `IsNearManipulation()` returns true.
This root cause is present in both the new `ObjectManipulator` and the legacy `ManipulationHandler`. **This PR fixes both of these components.**
However, another …

Fix + test coverage for broken near interactions with ObjectManipulator and legacy ManipulationHandler

---

Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs

This is a slight mitigation for: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8188
The issue here is that anything that we have that is InitializeOnLoad, it ends up running on editor launch, on recompile, and on play mode entrance. 
This is a workaround to make it not happen on play mode entrance.
The bigger fix here is going to require more work to do correctly.

Update the Unity AR configuration checker to not run during play mode changes

---

Assets/MRTK/Core/Definitions/Utilities/AxisFlags.cs
Assets/MRTK/Core/Definitions/Utilities/RotationConstraintType.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/MoveAxisConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/RotationAxisConstraint.cs

Previously the AxisFlags Enum does not have a "None" member, but 0 is used as a "None" member in some part of the MRTK. While this does not seem to create problems when running relevant code in the Editor, @fast-slow-still reported that this may be a problem on Android builds.
- Fixes: #7463.

Add None to AxisFlags

---

Assets/MRTK/Core/Definitions/Devices/MixedRealityInteractionMapping.cs

The largely overlapping constructors in MixedRealityInteractionMapping all had the same default initialization regardless of parameters for many of the internally serialized fields. This PR de-duplicates much of that code to ensure all are initialized consistently, and reduce the number of places changes would need to be made.
Also switched some field references to property references for consistency (and for an upcoming change to this class).

Clean-up duplicate constructor bodies in MixedRealityInteractionMapping

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

Currently the the setter of AutoFollowAtDistance doesn't check whether the script is enabled or the GameObject it is attached to is active before calling StartCoroutine(), which causes an error under certain circumstances. Besides, the auto follow behavior cannot be disabled by changing the AutoFollowAtDistance property as SetFollowMeBehavior(false) is never called.
- Fixes: #8028 and call SetFollowMeBehavior(false) when AutoFollowAtDistance is set to false.

Fix the switching of AutoFollowAtDistance

---

Assets/MRTK/Tests/PlayModeTests/SolverTests.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs

With ~5 remaining failing tests in Unity 2019, one of the remaining ones has to do with floating point comparison issues in tests.
Basically there's one test that ends up failing due to a comparison like:
LessThanOrEqual(2.00000024, 2.0)
This change actually ends up modifying a lot more of the file to use this new test utility (to handle floating point approximate comparison) just to keep things consistent within the file, even though the only one actually needed is in one of the follow distance tests.

Unity 2019 tests: Update SolverTests to use some tolerance in the LessThanOrEqual case

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

So this one was... really interesting.
The last stragglers in our 2019 play mode tests was actually a real issue that's only present in 2019 and not in 2018. If you try using the HandInteractionExample scene and use a ray (or GGV) on the slate and try to scroll, you'll notice that today, when you try to scroll from side to side, it actually moves things vertically.
This is because on 2019, the default quad mesh vertices appear to be different:
If you call mesh.vertices on 2019, here's the order you get:
```
+        [0]    "(-0.5, -0.5, 0.0)"    UnityEngine.Vector3
+        [1]    "(0.5, -0.5, 0.0)"    UnityEngine.Vector3
+        [2]    "(-0.5, 0.5, 0.0)"    UnityEngine.Vector3
+        [3]    "(0.5, 0.5, 0.0)"    UnityEngine.Vector3
```
The same call on 2018 gets this:
```
+        [0] …
```

Unity 2019 tests: Slate/Pan/Zoom test fix

---

Assets/MRTK/Providers/Windows/WindowsDictationInputProvider.cs

Currently in WindowsDictationInputProvider the dictationRecognizer is not disposed when Disable() is called (unlike the behavior of the same function of WindowsSpeechInputProvider). This can cause the Garbage Collector to try to clean up the object, which can lead to Destroy() being called on a non-main thread generating exceptions.
- Fixes: Dispose the dictationRecognizer when Disable() is called.

Dispose the dictationRecognizer in Disable()

---

Assets/MRTK/Core/Definitions/Utilities/MixedRealityTransform.cs
Assets/MRTK/SDK/Editor/Migration/ObjectManipulatorMigrationHandler.cs
Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/ConstraintManager.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/FixedDistanceConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/FixedRotationToUserConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/MaintainApparentSizeConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs
Assets/MRTK/SDK/Features/Input/Handlers/MinMaxScaleConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/Tests/PlayModeTests/ConstraintTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs
Documentation/ReleaseNotes.md

- removed transform target from transform constraint - wasn't used by constraints as the transforms we're operating on are passed into initialize and apply functions.
- changed initial world pose storage to be full transform (including scale) instead of just translation / rotation, so scaling based constraints don't have to manually store the initial scaling value.
- added breaking changes entry for both changes and directions for users that might have used transform target for their own constraints
Misc:
- added ctor for MixedRealityTransform to allow create from Unity Transform
- Fixes: #8040 & #7841

changed initial worldpose data type and removed ununsed target transform in constraints

---

scripts/packaging/.npmrc.official
scripts/packaging/.npmrc.test
scripts/packaging/createupmpackages.ps1

This change removes the automatic publishing support from the upm packaging script. We will publish using a separate task,
This will enable creation of upm artifacts during each mrtk_ci build.

modify script to only pack. publishing will be done separately

---

Documentation/Architecture/InputSystem/CoreSystem.md

The link to Microsoft.MixedReality.Toolkit.Input.IMixedRealityTouchHandler was leading to a 404 page. 
I updated the link to use xref like IMixedRealityEventSystem.
I couldn't test it because github won't generate that link for me to click. Can someone test that it's leading to the right page ? 
The correct link should lead to https://microsoft.github.io/MixedRealityToolkit-Unity/api/Microsoft.MixedReality.Toolkit.Input.IMixedRealityTouchHandler.html\

Updated link to IMixedRealityTouchHandler

---

Assets/MRTK/Examples/Demos/EyeTracking/General/Scripts/TargetBehaviors/OnLoadStartScene.cs

Add a "load option" in one of the eye tracking example scripts to allow additive scene loading only on device.
- Fixes: #8224

Eye tracking example: OnLoadStartScene improvements

---

Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollableListPopulator.cs
Assets/MRTK/SDK/Experimental/Inspectors/ScrollingObjectCollection/ScrollingObjectCollectionInspector.cs
Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

This PR is part of Scroll View graduation and handles the following issues:
**1. Allow Scroll view to be manipulated / scaled / rotated.**
- Updating the scroll collection when scroll object has scale different than Vector.one gives wrong bounds dimension to the clipping box.
- Adjusted clipping box local scale calculation to account for parents scale. Tests added.
_Clipping box after parent scale is doubled:_
**2. Make sure pagination works as expected.** 
- Moving scroll by Tiers or by page gives weird results, causing the scroll container to get stuck or move only a limited amount of tiers when using left-right scroll view. 
_Before change:_
_After change:_
**3. Scroll Object Collection inspector should draw the interaction planes.**
_After change:_
- Fixes: #7451
- Fixes: #7450
- …

Scroll View Graduation - Part 3

---

Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs

Currently, the profile inspector doesn't make it very clear to the user which controllers are loaded for the current profile. For example, when a user imports a package for support for a new type of controller, it is not immediately obvious whether the new controller definition they imported is being used, as it may share fit under a different controller definition (ie, Oculus XRSDK controller and Oculus OpenVR controller). This PR adds UI elements to the controller mapping window to make this more transparent (and save headaches when determining if a controller is actually currently being used by the profile)
All names WIP

surfaced which controllers are affected when tweaking a controller mapping

---

Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoPointerProfile.asset

The pointer profile list had a cursor prefab in one of the slots, instead of the correct pointer prefab:
This was leading to an error on start-up.
>DefaultCursor (UnityEngine.GameObject) does not have IMixedRealityPointer component. Cannot create and utilize pointer
Since this input type is covered by a different (correctly assigned) pointer rule, I removed the entry.
- Part of fixing: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8125

Remove incorrect prefab from ET pointer profile

---

Assets/MRTK/Providers/Windows/WindowsDictationInputProvider.cs

Adds #ifdef guard around code that should not run when compiles for non-windows platforms.
- Fixes: #8226

WindowsDictationInputProvider fix to compile for Mac

---

Assets/MRTK/Core/Services/BaseBoundarySystem.cs
Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs

This change separates the boundary system fixes from the change profile PR (#8050). The issue that is being fixed is unrelated and was originally included there to allow a profile change test case to run correctly.
The changes made are:
* Add a ReadProfile method to BaseBoundarySystem.cs
* Check for a null profile in ReadProfile
* Call ReadProfile at the top of Initialize to ensure that the profile is always read before any decisions are made (THIS was the bug that broke the profile change test)
* Ensure that the base.Initialize() method is always called in MixedRealityBoundarySystem.cs (this was a contributing factor the the bug)

Split boundary system fixes from #8050

---

scripts/ci/validatecode.ps1

I've been doing a little bit of digging into some of the non-runtime perf aspects of our setup, and one thing that I've looked into is the overhead associated with the split up of the asmdefs that we have today. Here's a rough wall of text of some thoughts/findings:
Amsdefs can be a useful tool in grouping code to reduce overall compilation times in the context of very large projects. About a year ago we went through the process of putting all our code into smaller asmdefs, in the goals of optimizing compile time. 
There are tradeoffs, however, beyond just the project window bloat that occurs in Visual Studio when you have a large amount of asmdefs (this document doesn’t go into this, but note that this specific issue will be addressed with some of the UPM work that we're doing now). …

Add an asmdef checker roadblock to PR/CI validation

---

Assets/MRTK/Core/Utilities/Rendering/MaterialInstance.cs

This PR is part of Scroll View graduation.
**1. Scrolling Object Collection causes TextMeshPro MissingReferenceExceptions .**
- Using material instance component on game objects that are using TMPro renderers throws error messages when transitioning from editor mode to playmode.
TMPro also does material life management and caches the renderer shared material during editor mode. When transitioning from editor mode to playmode the MaterialInstance class defers the destruction of the material instanced during editor mode. This destruction only happens after Awake in playmode, breaking TMPro reference. 
This PR suggests letting Unity handle the unloading of unused assets only when transitioning from editor mode to playmode. Profiling this approach shows no extra memory leaking. The error …

Fixing broken TMPro material references when using Material Instance on same object

---

Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MRTK/Services/InputSystem/GazeProvider.cs
Assets/MRTK/Tests/PlayModeTests/ChangeActiveProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/ChangeActiveProfileTests.cs.meta
Assets/MRTK/Tests/PlayModeTests/SpatialObserverTests.cs
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestBoundaryOnly.asset
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestBoundaryOnly.asset.meta
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestBoundaryVisualization.asset
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestBoundaryVisualization.asset.meta
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs

This PR is based on efforts made in #8050, which attempted to address multiple issues at once. Instead, this PR focuses on the specific issues related to allowing developers to change the active profile of MRTK during runtime.
- In this PR, the behavior of runtime profile change is modified to first take the request, then destroy current profile services after all LateUpdate()s of current profile services have been called, and finally initialize the new services associated with the new profile in the next frame before any Update() for a service is called. This solves the problem of potentially performing the profile change in the middle of an Update or LateUpdate of a service which causes a variety of problems. Delaying the initialization of new services to the next frame also helps to …

Enabling runtime profile switching

---

Assets/MRTK/Core/Utilities/Editor/XRSettingsUtilities.cs

Currently, this property iterates through all subsystem descriptors and checks which ones are `XRDisplaySubsystemDescriptor`s. I missed the fact that I could ask for specific descriptor types in the original implementation...this PR fixes that, to save some iterations and casts.

Improve XRSettingsUtilities.IsLegacyXRActive check

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/Microsoft.MixedReality.Toolkit.Providers.WindowsMixedReality.asmdef
Assets/MRTK/Services/BoundarySystem/XR2018/Microsoft.MixedReality.Toolkit.Services.BoundarySystem.asmdef

Adds a constraint to the two XR2018 assemblies we have, preventing them from loading on Unity 2020.1 or newer, where the legacy XR pipeline has been removed from Unity.

Don't try loading Unity-deprecated assemblies in 2020+

---

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/XRSDKWindowsMixedRealityUtilitiesProvider.cs

Now that Windows XR Plugin 2.2.0 is the Unity 2019.4 verified / recommended / installed by default version, we can include this feature that was added in that package (`WindowsMREnvironment.CurrentHolographicRenderFrame`).
This allows the `WindowsMixedRealityReprojectionUpdater` to work and allows apps to switch between depth reprojection and autoplanar on XR SDK.

Update XRSDKWindowsMixedRealityUtilitiesProvider.cs to provide HolographicFrame access

---

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityPointerMediator.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/TestCustomPointerMediator.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/TestCustomPointerMediator.cs.meta
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestCustomPointerMediatorInputProfile.asset
Assets/MRTK/Tests/PlayModeTests/TestProfiles/TestCustomPointerMediatorInputProfile.asset.meta
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs
Documentation/ReleaseNotes.md

Was surprised to see this but then took a look at the code and was not surprised to see this!
Here's what happens:
When you set the pointer preferences (stored on the FocusProvider), the preferences themselves get stored. However, when the FocusProvider is creating the pointer mediator, it only passes the pointer preferences along to the object IF the object has as constructor that takes an IPointerPreferences.
There are a couple of things wrong with this:
1. The DefaultPointerMediator has pointerPreferences marked as private, so even if someone wanted to save the pointer preferences, they couldn't do so in an way that would make the base class (DefaultPointerMediator) be able to functionally retrieve its pointer preferences. (Yes, you could do a bunch of repeat work but that's not …

PointerUtils doesn't work with custom PointerMediator

---

Assets/MRTK/Core/Providers/ObjectMeshObserver/RoomFileFormat/RoomFileImporter.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GlbAssetImporter.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GltfAssetImporter.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GltfEditorImporter.cs
Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs

Opening some PRs as I go. This PR:
1. Updates the namespace for Unity's `ScriptedImporter` in Unity 2020.2
1. Uses the new `VersionControlSettings` properties in Unity 2020.2 for setting meta file visibility.
1. Compiles out `ApplyXRSettings`, which references `PlayerSettings.SetVirtualRealitySupported`. I haven't yet found a corresponding API in XR SDK.
1. Compiles out a path in the camera system which talked to WSA APIs for device opaqueness. This was already a deprecated flow in MRTK in favor of our platform-specific camera settings providers.

Update some deprecated APIs in Unity 2020

---

Assets/MRTK/Core/Utilities/XRSubsystemHelpers.cs
Assets/MRTK/Core/Utilities/XRSubsystemHelpers.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityCameraSettings.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/Editor/XRSDKConfigurationChecker.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKCameraSettings.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Assets/MRTK/Providers/XRSDK/XRSDKSubsystemHelpers.cs

Rewrote the helpers to no longer have a dependency on the Unity XR Management package. Now that it only has a dependency on the engine, I've moved it to the MRTK core, to allow other components to use it without needing to take a dependency on the XRSDK provider package.
This was done for a similar reason as #8270, to allow components to call methods on these subsystems without taking a dependency on the XRSDK package.

Update and move XRSubsystem helpers into core

---

Assets/MRTK/Providers/Oculus/XRSDK/Editor/OculusXRSDKConfigurationChecker.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Editor/WindowsMixedRealityXRSDKConfigurationChecker.cs
Assets/MRTK/Providers/XRSDK/Editor/XRSDKConfigurationChecker.cs

Per https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8188, we're working on cleaning up a lot of our InitializeOnLoad handlers.
Some of them only need to be run at Unity editor startup time (because they need to do diverging behavior based on whether or not it's being launched in Unity 2019 vs Unity 2018). These ones don't need to run after each compile and prior to entering play mode (which they do right now) - i.e. prior to this change these three things would run their asmdef checkers (which would do file I/O, which can be expensive and is unnecessary). Obviously the Unity editor version is not going to change as the Unity editor is running.
This change uses the volatile SessionState storage space to store whether or not these particular handlers have run in this editor …

Update a subset of the XRSDK configuration checkers to only run on editor startup

---

Assets/MRTK/Examples/packagetemplate.json

The upm version of the examples package was incorrectly marking the StandardAssets folder as hidden in the editor (appended with a ~).
This change fixes this issue and the package contents are shown below. (In the editor, right click on the package and select "Show in Explorer"

Fix examples upm package

---

Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandDataProvider.cs
Assets/MRTK/Core/Utilities/DeviceUtility.cs
Assets/MRTK/Core/Utilities/DeviceUtility.cs.meta

`XRDevice.isPresent` doesn't work with XR SDK (see #7904 for another example of this). Following Unity's [recommendation to check the running status of the XRDisplaySubsystems instead](https://docs.unity3d.com/2019.4/Documentation/ScriptReference/XR.XRDevice-isPresent.html), I added a helper function to wrap both the legacy and XR SDK APIs for getting this data.

Refactor out DeviceUtility.IsPresent to wrap legacy + XR SDK code

---

Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/RotationHandles.cs
Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs

- changed reset condition (early out) to allow hiding rotation handles when all axis are disabled 
- made visibility check more readable in rotation handles
- added test condition for rotation handle visibility test to cover bug scenario
- Fixes: #8239 
added test scenario to existing handle visibility test
verified behavior in bounds control example scene

fixed reset of handles when all rotation axis flags are disabled

---

Assets/MRTK/Core/Utilities/Editor/EditorProjectUtilities.cs

Per, https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8188, we're working on making it so that InitializeOnLoad isn't as costly for ongoing compile time/play mode entry times.
This particular handler is fairly pricey but only needs to be run on Editor launch.

Update the last project-load InitializeOnLoad handler to only run on project startup

---

Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs

In some of our experimentation, we've found a limitation to PressableButton where when multiple poke pointers exist for the same input source, the code down below considers the 'wrong' one (i.e. it chooses the first poke pointer, which might not actually be mid-poke, whereas the second one is actually doing the poking).
I was looking at adding tests for this, but we don't actually have any built in input config that has multiple poke pointers per input source (and wasn't sure if doing so would be widely valuable/not confusing)

Update PressableButton to support multiple pokepointers on the same input source

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs
Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs
Documentation/CrossPlatform/LeapMotionMRTK.md
Documentation/CrossPlatform/UsingARFoundation.md
Documentation/ReleaseNotes.md

A subset of our InitializeOnLoad handlers run all the time, but actually add extremely low value because the times where they could actually affect change are extremely rare. These two specifically only need to run once after a new platform is being lit up for the first time (i.e. it's generally a one-time per-project setup step). However, their InitializeOnLoad handlers end up running on each compile, prior to entering play mode, etc, etc.
The benefit-to-cost ratio here is really not great (in that the number of times where this actually does work vs the number of times it is run is a super low ratio), so these are being moved to instead trigger manually (and be listed explicitly in project setup steps). I could have converted these to on-editor-startup, but actually that isn't very …

Updates the LeapMotion and UnityAR configuration checkers to be manually triggered

---

Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

This PR is part of Scroll View graduation and handles the following issues:
**1. Scroll should work as expected using GGV and HL1 .**
- TryGetPointerPositionOnPlane() method was using pointer.result.point for all far pointers. On GGVPointer this is the point of focus from gaze.
- Changed method to use pointer.position projection instead. Tests added.
**2. Content click should happen on Touch up (Web Browser).** 
- In order to avoid false clicks when user engage on a scroll drag and match HL web browser behavior, child button should be configured to trigger clicks only on touch up. Adding tests to check if configuring buttons with correct settings ensures click on touch up.
_Scroll child button clicking on touch up:_
- Fixes: #7151
- Fixes: #7455
( _This PR merges into …

Scroll graduation - Part 4

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs
Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs
Documentation/CrossPlatform/LeapMotionMRTK.md
Documentation/CrossPlatform/UsingARFoundation.md
Documentation/ReleaseNotes.md

Reverts microsoft/MixedRealityToolkit-Unity#8287
This is causing a build break because our build machines are still using an older version of Unity 2018 (where missing assemblies leads to an error rather than a warning).
Temporarily reverting this while I get the Unity version updated on the build machines.

Revert "Updates the LeapMotion and UnityAR configuration checkers to be manually triggered"

---

Assets/MRTK/SDK/Experimental/Editor/Inspectors/BoundsControl/BoundsControlInspector.cs
Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControlTypes.cs
Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/Visuals/Configuration/ScaleHandlesConfiguration.cs
Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs

- Added precise scaling mode to bounds control scale handles. 
- Added test to verify behavior for near interaction with control.
Note: there's another branch where I integrated the constraint manager into BC which will allow to combine non uniform scaling with scale axis locking. 
- Fixes: #6734 
- added new test to verify proper scaling behavior as well as position / center modification when scaling is performed 
- manual tests on example scenes

Added non uniform scaling support for bounds control

---

Assets/MRTK/SDK/Editor/Migration/Tools/MigrationTool.cs

Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8004. This class was moved to an editor-only assembly, but the `#define` was left in, which prevents it from showing up in our docs.

Remove UNITY_EDITOR define from MigrationTool.cs in editor-only assembly

---

Assets/MRTK/Core/Providers/InputSimulation/BaseInputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/Editor/InputSimulationWindow.cs
Assets/MRTK/Core/Providers/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MRTK/Core/Providers/InputSimulation/IInputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/InputPlaybackService.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationEnum.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/MixedRealityInputSimulationProfile.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedArticulatedHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedGestureHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandDataProvider.cs
Assets/MRTK/SDK/Features/Input/InputSimulationIndicators.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputSimulationProfile.asset
Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/InteractableEventTests.cs
Assets/MRTK/Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs
Assets/MRTK/Tests/PlayModeTests/PinchSliderTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs
Assets/MRTK/Tests/PlayModeTests/SlateTests.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs
Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestHand.cs

This is the first of a set of PRs that will eventually add motion controller simulation and test support to MRTK. This PR specifically focuses on making name changes so that simulation is no longer confined to just hands but applies to controllers in general.
- Change reference to "hand" to a more generic term "controller" to get ready for the upcoming support of simulated controller in editor play mode and tests.

Renaming hand to controller in input simulation related files

---

Assets/MRTK/SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs
Assets/MRTK/SDK/Experimental/Features/Utilities/WorldAnchorManager.cs
Assets/MRTK/SDK/Microsoft.MixedReality.Toolkit.SDK.asmdef

1. Compiles out calls to legacy `XR.WSA` APIs on 2020.1+, where the APIs no longer exist.
1. Adds support for XR SDK's `SetFocusPlane` API in StabilizationPlaneModifier, to add back the functionality when running on non-legacy XR.
1. Removed an unused assembly reference in the SDK .asmdef.
1. Some formatting and code style updates.
WorldAnchorManager could be converted to the XR{ReferencePoint|Anchor}Subsystem, but there's still some active work on the WMR implementation of that subsystem underway that prevents testing. Once that work is done, we can revisit this component.

Update WorldAnchorManager and StabilizationPlaneModifier for Unity 2020

---

Assets/MRTK/SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs

The legacy XR check happens in an editor-only assembly. This updates it to instead check for a display subsystem running, which implies XR SDK vs legacy.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=13266&view=results

Convert from legacy XR check to display subsystem running check

---

Assets/MRTK/Core/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs

A partial change to start moving editor references in the core assembly into more logical editor-only assemblies.
This change moves the code where the input actions are set from MRTK.cs in an `if` that checks for the input system being enabled into the profile's inspector in an `if` that checks the same data.
Also some minor cleanup of related files.
- Part of https://github.com/microsoft/MixedRealityToolkit-Unity/issues/3952

Move Editor reference from MRTK.cs to config profile inspector

---

pipelines/ci-daily.yml
pipelines/ci-packaging.yml
pipelines/ci.yaml
pipelines/config/settings.yml
pipelines/pr.yaml

A CI machine was updated with these latest Unity versions, so this PR intends to test out the installs / new machine.
We may want to hold off merging until additional machines are updated, or else we'll be stuck with a single machine for both CI and PR validation.

Update Unity versions for public CI / PR validation

---

Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/ObjectManipulator/ObjectManipulatorInspector.cs
Assets/MRTK/SDK/Experimental/Editor/Inspectors/BoundsControl/BoundsControlInspector.cs
Assets/MRTK/SDK/Experimental/Features/UX/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/ConstraintManager.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/FixedDistanceConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/TransformConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/Tests/PlayModeTests/Experimental/BoundsControlTests.cs

PR integrates Constraint Manager into Bounds Control. 
- removed hardcoded min max scale constraint
- bounds control now supports scale and rotation constraints (translation constraints to be added once translation handles are in)
- adjusted min max scale constraint test and added test to verify rotation constraint
- adjusted constraint manager to check for added constraints during runtime (old design only allowed to have constraints registered that were added before the component that includes the constraint manager)
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8304
part of #5340

Constraint Manager now available for Bounds Control

---

Assets/MRTK/Core/Utilities/CoreServices.cs

Accessing CoreServices properties shows up as a performance hot path for Remote Assist. This fix makes performance better for CoreServices.GetService by avoiding looking up the service twice in the dictionary (once from ContainsKey and another time from the indexer).

Improve CoreServices.GetService by removing a double Dictionary lookup

---

pipelines/ci-packaging-internal.yml
pipelines/ci-release.yml
pipelines/ci-weekly-internal.yml
pipelines/config/settings.yml

The internal machines have a newer version of Unity 2018.4 installed, so let's use that!

Update internal CI Unity versions

---

Assets/MRTK/Core/Utilities/Editor/MixedRealityOptimizeUtils.cs

First pass to get things compiling in Unity 2020.
Second pass will be to complete #7514/#7513, which will enable 2019, 2020, etc.

Compile out non-2020-compliant code in MixedRealityOptimizeUtils

---

Assets/MRTK/Extensions/LostTrackingService/LostTrackingService.cs
Assets/MRTK/Extensions/LostTrackingService/Microsoft.MixedReality.Toolkit.Extensions.Tracking.asmdef
Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs

Updates the LostTrackingService to no longer call into removed legacy XR APIs (`WorldManager`) on Unity 2020.
Also adds support for the replacement APIs in ARSubsystems' XRSessionSubsystem. This required a new reference to that assembly, and I reused the existing `ARFOUNDATION_PRESENT` define, since have ARFoundation implies ARSubsystems.

Update LostTrackingService for Unity 2020 and XRSDK/WMR

---

Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKConfigurationProfile.asset
Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKInputSystemProfile.asset

[On Slack](https://holodevelopers.slack.com/archives/C2H4HT858/p1597784419352700), it was pointed out that our hand menu samples depend on the hand joint service being registered in the input providers. This PR adds the service to the XR SDK profile so hand menus work again!

Add HandJointService to XR SDK profile

---

Documentation/Contributing/Roadmap.md
Documentation/Contributing/UnitTests.md
scripts/test/run_playmode_tests.ps1
scripts/test/run_repeat_tests.ps1

I have updated the Unity 2018 LTS version to the latest 2018.4.26f1 in examples in the documents and the two test scripts in Scripts/test/run_*.ps1. I also updated the current release in the roadmap.md to v2.4.0 from v2.3.0.
- Fixes: Updated version numbers in documents and two CI test scripts.

Unity 2018 LTS version updates

---

Assets/MRTK/SDK/StandardAssets/Materials/MRTK_PressableInteractablesButtonBox.mat

Updated HoloLens 2 Button's front cage material to transparent to remove black color in MRC. 
(we already did this update for Bounding Box while ago)
Removes black color on the button's front box in Mixed Reality Capture:
**MRTK_PressableInteractablesButtonBox.mat**  Adjusted alpha from 255 to 0:

HoloLens 2 Button material update

---

Documentation/Updating.md

Adds a note to double check your Library folder for unrecoverable data (for example, Unity Collab saves data there) before deleting the folder.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7991

Add note about tools that save to Library

---

Assets/MRTK/Core/Inspectors/PropertyDrawers/SceneInfoUtils.cs
scripts/ci/validatecode.ps1

Usage of Assembly.LoadTypes() has bitten us at least four times in the past:
https://github.com/microsoft/MixedRealityToolkit-Unity/pulls?q=is%3Apr+gettypes+is%3Aclosed+
This change removes the latest case that is problematic and also adds some code checkers so that we don't do this again, because this is the legit 5th time I've had to solve this problem.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8331

GetLoadableTypes strikes again

---

scripts/ci/validatecode.ps1

This new code checker didn't escape the `.`, so it was matching any character that preceded `GetTypes()`. We have a test called `TestTargetTypes`, which was triggering this code issue.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=13459&view=logs&j=ae5f814d-d003-5afd-2125-fa0189ea8658&t=12d627c1-3bb6-55bf-f915-b77e58828cea

Update new code checker to escape .

---

Assets/MRTK/SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs

I missed two cases in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8294 that called into legacy APIs. This should be the final PR for 2020 compilation support.
- Fixes: #8269

Update additional cases in StabilizationPlaneModifier for XR SDK

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Documentation/MRTK_Configuration_Dialog.md

See linked issue https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8326 for more details - this is a pretty bad issue for folks using Unity 2019 and trying to deploy to HL2.
This updates the configurator to turn off this setting by default for 2019 (and when under UWP). This is obviously not specific to HL2 (since HL1 also uses UWP and WMR as well) but is the level of detail that we can distinguish to make sure we don't affect standalone or other platforms.

Update the MRTK configurator to turn off "Graphics Jobs" by default in Unity 2019

---

scripts/ci/validatecode.ps1

CI warning about new InitializeOnLoad markers were hidden, resulting in silent build failures. Fixing that here.

Made CI pipleine warning visible

---

Assets/MRTK/Core/Definitions/Devices/ControllerMappingLibrary.cs
Assets/MRTK/Core/Providers/UnityInput/XboxController.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Assets/MRTK/Providers/OpenVR/OculusRemoteController.cs
Assets/MRTK/Providers/OpenVR/OculusTouchController.cs
Assets/MRTK/Providers/OpenVR/ViveWandController.cs
Assets/MRTK/Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs
Assets/MRTK/StandardAssets/MRTK.StandardAssets.sentinel.meta

With the addition of the standalone Standard Assets package in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8232, the controller mapping images began failing to load. This is because they're currently still loaded via a file path, and the new StandardAssets folder didn't have a sentinel file.
This PR adds the sentinel file, updates MRTKFiles to allow loading from the new module, and updates the paths for the controller mapping images.
- Fixes:

Fix standard assets loading and fix controller mapping profile image loading

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
Assets/MRTK/Tests/EditModeTests/Core/MixedRealityToolkitFilesTests.cs

Some of our existing MixedRealityToolkitFilesTests used `Asset.Equals` instead of an assert `Assert.AreEqual` when comparing, so no test comparison was run.
After fixing this, one of the existing edge cases (`inputPath = @"c:\projects\AssetsViewer\Assets\materials\test.mat";`) started failing the test due to Assets existing in the path twice.
Initially to fix this, I changed the MRTKFiles from checking `IndexOf` to `LastIndexOf`, but then I realized this would start failing if we were looking for something in the StandardAssets folder in an Assets folder (I added this as a test case).
To solve that, MRTKFiles now uses a lookup including the slashes on either side, so we can be sure we're indexing on a folder with the exact same name.

Fix MRTKFiles tests

---

pipelines/packageupmpublic-preview.yaml
pipelines/packageupmpublic.yaml

This change reads the registry path from the pipeline run and publishes the artifacts. This completes the UPM publishing work!

Enable publishing of upm packages in release pipelines

---

Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs
Documentation/CrossPlatform/UsingARFoundation.md
Documentation/ReleaseNotes.md
scripts/ci/validatecode.ps1

This is a revert of a revert - basically the original PR hit an issue in CI related to build machine versions, and we recently updated some of dependencies on our build machines, so now this should be good to go.
Reverts #8292
This also accounts for the fact that LeapMotion was recently fixed up by @CDiaz-MS 
Also yes I realize I made a spelling mistake on my branch name ardoundation.

Make the ARFoundation InitializeOnLoad work be manually triggered

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8259/files led to a CI pipeline break in the msbuildforunity project generation step - in particular it looks like the system has some indigestion when dealing with new Oculus.VR.* packages that we've added dependencies on in a few cases.
Since we've turned down the public NuGet updates in favor of upcoming UPM work for 2.5, I've made a tweak to the project generation step to ignore any asmdefs that we have that reference Oculus.VR packages (which should unblock the build)

Update UnityProjectInfo to avoid the build break

---

Assets/MRTK/Examples/Demos/UX/Interactables/Prefabs/Model_Bucky.prefab

The DocExample's Model_Bucky had a random CINEMA_4D_Editor object which wasn't necesary.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8076

Remove an unneeded object from DockExample prefab

---

Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MRTK/Tests/PlayModeTests/InteractableTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerTests.cs
Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestMotionController.cs

This is the final PR of a series of four that adds motion controller simulation and test support to MRTK. This PR specifically focuses on adding more motion controller related tests based on the test infrastructure introduced earlier. Some bugs discovered when creating the tests are also fixed.
- Continuation of #8313, #8296 and #8348.

Add more motion controller tests

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitFiles.cs
scripts/ci/validatecode.ps1

The MixedRealityToolkitFiles InitializeOnLoad handler runs on every play mode entry/script recompile, even if the MRTK object/features aren't being used in the current scene. This overhead is painful for folks who want to have MRTK in their project but not have to use it on every single scene.
This removes the InitializeOnLoad handler and makes things become lazy-inited (i.e. the first usage of any of the public APIs of this file will end up causing the initialization to happen only when the MRTK files functionality is needed. This will have the effect, however, of causing a micro-delay in any Unity editor UI that ends up invoking this, but that should be better than having the same delay happen on every single compile of non-MRTK code (which is what happens today)

Remove the MRTK files InitializeOnLoad handler

---

Assets/MRTK/Examples/Experimental/Dock/DockExample.unity

The DockExample has a few DockPosition objects that don't have a BoxCollider.
This is weird, because DockPosition.cs requires some type of collider in order to work - i.e. the example is currently set up in an impossible way given the current code. I'm guessing this happened due to how the work was staged (i.e. I'm guessing the example scene was worked on to prove things out, and the RequireComponent was added after)
Basically this makes our example scene align to how our current code actually works
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8061

Update the DockPosition objects to have a BoxCollider

---

Documentation/ReleaseNotes.md

This change adds a release note re: UPM package availability. This was missed in the earlier UPM series of PRs.

Add UPM to release notes

---

Assets/MRTK/SDK/Features/UX/Scripts/AppBar/AppBar.cs

If a custom button is added to Appbar prefab, in hidden or manipulation state the button is shown
Remove check for custom button in UpdateButton, so the logic in the GetButtonVisible method can be executed
Copy and paste a button in AppBar prefab and change type to custom, the button is always visible also when hide or manipulate button is checked

fix appbar custom button visibility

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Resources/MRTK-OculusConfig.asset
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Config/MRTKOculusConfig.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs

Fields on the prefabs were hidden due to OCULUSINTEGRATION_PRESENT flags, which probably broke CI

Fixes to the Oculus Quest prefabs for CI

---

Assets/MRTK/SDK/Experimental/Features/UX.meta

CI is currently broken on the code validation step because there's a stale meta file (i.e. the folder got removed).

Remove stale meta file

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/Editor/SceneUnderstandingObserverProfileInspector.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/Profiles/DefaultSceneUnderstandingObserverProfile.asset
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/Profiles/DefaultSceneUnderstandingObserverProfile.asset.meta
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/SceneUnderstandingObserverProfile.cs.meta
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

This change continues the feature branch work for scene understanding.
This one re-creates the default profile and specifies materials that are contained within the standard assets package, instead of examples assets.
Other included changes:
* Minor rearranging of some variables in the inspector
* Remove unneeded comments
* Mark the data provider as _requiring_ a profile

Scene understanding: re-create default profile and some minor code changes in the inspector and attrib usage

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

Reverts microsoft/MixedRealityToolkit-Unity#8384
This was the wrong way of fixing things (see the right way here: 
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8403)

Revert "Update UnityProjectInfo to avoid the build break"

---

Assets/MRTK/Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs

Guid issue due to having Unity 2019+ code compile on Unity 2018 versions

Hack to stop guid from breaking CI

---

Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/InteractableEventTests.cs

Add controller simulation tests to bounds control tests as the feature is no longer experimental. Also add some tests to InteractableEvent.
- Follows #8401.

Add bounds control controller simulation tests

---

Assets/MRTK/Examples/Demos/SpatialAwareness/Scripts/DemoSpatialMeshHandler.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Documentation/ReleaseNotes.md

This change improves how materials are handled in the spatial mesh observers.
The first change (fixes #8394) determines the material and always applies it to the renderer, even if the display option in use is None.
The second change (fixes #8396), determines (earlier than in previous releases) whether or not the mesh event will be an add or an update. If update, the material for the mesh being replaced is applied to the new mesh.
Combining the two fixes enables developers who customize their spatial mesh materials to have the changes persist through mesh updates and toggles between Visible and None display options without requiring the application to continually reset the material.
This change does _not_ address #8397.

Improve spatial mesh material handling - fix 8394 and 8396

---

Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs

With the move of SpatialObjectMeshObserver from the Providers to the Core/Providers folder, it failed to auto populate the default profile on selection.
This change fixes the data provider attribute values.

Fix object mesh observer not auto finding the profile

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/Editor/WindowsMixedRealityConfigurationChecker.cs
Documentation/ReleaseNotes.md
Documentation/Tools/HolographicRemoting.md

This change continues the work started by @wiwei to replace InitOnLoad classes with discrete menu options.
The new Mixed Reality Toolkit > Utilities > Windows Mixed Reality > Check Configuration menu item checks to see if the Dot Net WinRT NuGet package has been imported and appropriately sets the DOTNETWINRT_PRESENT flag.

Replace InitOnLoad with MRTK > Utils > WMR > Check Config

---

scripts/docs/web/version.js

As part of getting ready for 2.5 release, we're updating the dropdown menu for docs so that we can see the generated docs (and also to allow others to see a preview of what we're going to be releasing).

Add the prerelease branch to the mrtk docs dropdown

---

Assets/MRTK/Tests/EditModeTests/Core/Utilities/BuildAndDeploy/UwpAppxBuildToolsTest.cs
ProjectSettings/ProjectSettings.asset
pipelines/config/settings.yml
scripts/packaging/updateMRTKVersion.ps1

Now that we've created a 2.5 stabilization branch, we're updating the version associated with the mainline dev branch to the next version (2.6). Note that this change will affect the following release (i.e. not the upcoming, but the one after that).
Doing this early on so that it's one less thing for us to think about in the future.

Update dev branch mrtk version to the next release version.

---

Assets/MRTK/Examples/packagetemplate.json
Assets/MRTK/Extensions/packagetemplate.json
Assets/MRTK/StandardAssets/packagetemplate.json
Assets/MRTK/Tests/TestUtilities/packagetemplate.json
Assets/MRTK/Tools/packagetemplate.json
Assets/MRTK/packagetemplate.json

We're using Microsoft Corporation, while other packages are using Microsoft. To align these (since Unity uses them to group packages by source), we're updating our packages to just be Microsoft.

Update author name to align with other UPM packages

---

.github/workflows/main.yml

During the stabilization process, we have to periodically (usually daily) create PRs to merge the latest prerelease/*stabilization branch into mrtk_development, to ensure that our mainline doesn't get out of sync with the 'true latest' (i.e. more people are working out of stabilization than mrtk_development during the earlier phases of stabilization).
This is somewhat onerous, so this change sets up a github actions workflow to automate this process every day (i.e. every morning we'll have a PR if there are changes between stabilization and development)

Initial workflow for syncing stabilization and development

---

Assets/MRTK/Core/Providers/BaseSpatialObserver.cs
Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs
Assets/MRTK/Tests/PlayModeTests/SpatialObserverTests.cs

Remove the WaitingForSceneObserverAccess bool from BaseSpatialObserver and related files. References are replaced with the IsRunning flag.

Remove WaitingForSceneObserverAccess from BaseSpatialObserver

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/Editor/InputMappingAxisUtility.cs

The change in #8315 inadvertantly moved it to an area that only runs when the input tab in the configuration profile is visible. Reverted this code to run when the MRTK initializes instead.
A larger PR to add this to the configurator and fix the core -> editor references will be opened on the dev branch, but that's a bit too much for the stabilization branch.
Also updated some code style capitalization of a private field and added an optional bool to the input axis setter method for future use.

Fix input axis mappings in 2.5

---

Assets/MRTK/Tests/TestUtilities/Microsoft.MixedReality.Toolkit.Tests.Utilities.asmdef
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs

During UPM pre-release testing, it was found that there was an issue with accessing the MRTK test utilities assembly when it was imported as a UPM package. When the files were copied into the Assets folder, or imported via a .unitypackage file, it succeeded.
After quite a bit of investigation, it appears that there is behavior where an assembly marked as a test assembly, is not auto-added and does not appear able to be used if it is in the Library/PackageCache.
This change removes the dependency on NUnit and marks the assembly as NOT being a test asm. As part of this change, existing NUnit assertions have been replaced with UnityEngine assertions.
This was validated by spot-running some play mode tests as well as verifying that the assembly was referenceable via a custom script.
Special …

Fix test utilities access in 2019.4 when imported via UPM

---

Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs

Remote Assist has a voice-based manipulation system for moving slates using a voice command and gaze pointer updates. This was blocked from working due to exceptions thrown by the ManipulationHandler (which didn't check the Controller of the pointer it was manipulated with to see in TryGetGripRotation). For the GazePointer, the controller is null.
This change updates both ManipulationHandler and ObjectManipulator to check these values for null. I've also added two playmode tests that emulate the logic that exists in Remote Assist today to prevent future regressions.

Allow manipulation with the GazePointer for both ManipulationHandler and ObjectManipulator

---

Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PrefabSpawner.cs

Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7467
As I was looking at issues that were set to the 2.5 milestone, I noticed this one which seemed like a fun break from other work. There's a few things to note here:
1. vanishDelay is not used in the code prior to this, because the default case never ran.
2. I couldn't just update the VanishOnFocusExit to use vanishDelay, because other consumers may already be dependent on the immediate vanish behavior.
3. So I ended up adding another option (that actually honors vanishDelay), so that people can opt into this correct behavior while not breaking existing users.
4. Opted not to write a test for this specific case because it involves timers, and I don't want to add sleeps to our tests without having some system of …

Update the prefab spawner to have an option that actually honors vanishDelay

---

Documentation/README_Solver.md

Fixed typo in first sentence of README_Solver.md
- Fixes: "predefine" -> "predefined"

Fixed Typo in README_Solver.md

---

Assets/MRTK/Core/MixedReality.Toolkit.targets

When the checked-in link.xml was removed, this build target that copies link.xml from the nuget package into the Unity project was not removed. It is no longer necessary, as the link.xml file is generated inside the Unity project. This unblocks Remote Assist from ingesting new nuget packages.

Remove link.xml from build targets since it is now generated

---

Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollableListPopulator.cs
Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollablePagination.cs
Assets/MRTK/Examples/Experimental/ScrollingObjectCollection/Scripts/ScrollablePagination.cs.meta
Assets/MRTK/SDK/Experimental/Inspectors/ScrollingObjectCollection/ScrollingObjectCollectionInspector.cs
Assets/MRTK/SDK/Experimental/ScrollingObjectCollection/ScrollingObjectCollection.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

This PR is part of the Scroll graduation and addresses the following issues:
**Revert input event subscription to global.** In order to get the graduation into MRTK 2.5 without the latest changes on the Event Propagation branch, we are reverting the scroll event handlers to globally subscribe to pointer and touch events. 
**Enabling mask disabled.** While upgrading the demo scene it became important to have this feature to make the process of editing and layouting of scroll content easier. 
**Inspector and Tests adjusted to the changes.**
**Example Scripts.** Added a pagination example of how to use the scroll pagination methods from unity events in the inspector. Used for demo scene pagination buttons.
**Further reformats.** Some fields / methods were renamed or moved moved in the class. …

Scroll View Graduation - Part 6 - Reverting propagation

---

Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/InteractableEventTests.cs
Assets/MRTK/Tests/PlayModeTests/PinchSliderTests.cs
Assets/MRTK/Tests/PlayModeTests/SlateTests.cs

This PR removes the use of PushControllerSimulationProfile() and PopControllerSimulationProfile() when trying to switch input simulation mode in tests (e.g. from articulated hand to gesture hand). Those two functions manipulate the profile of input simulation service, which does not have any impact on simulation mode after the initialization of the service. In this PR the current simulation mode is cached before switching and will be restored after the test is finished. This technique has been used in some other existing tests.
- Fixes: #8468.

Properly switch input simulation mode in tests

---

Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityInputSimulationProfile.asset

This PR changes the input simulation mode of InputActions.MixedRealityInputSimulationProfile.asset from articulated hand to gesture hand to match the description shown in the InputActionsExample scene.
- Fixes: #8476.

Change the input simulation mode in InputActions.MixedRealityInputSimulationProfile

---

Assets/MRTK/Core/Providers/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/ManualCameraControl.cs
Assets/MRTK/Core/Providers/InputSimulation/MixedRealityInputSimulationProfile.cs
Assets/MRTK/Examples/Experimental/CameraOffset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSimulationProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSimulationProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSystemProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetInputSystemProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetProfile.asset
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetProfile.asset.meta
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetTest.unity
Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetTest.unity.meta

Allows the camera to be at eye-position above the floor, like VR
Adds a new setting `cameraOriginOffset` to `MixedRealityInputSimulationProfile`, which specifies the amount to offset the camera when first turning on simulated input.
Ultimately this allows the camera to start 1.7m up, giving a similar feel to VR tracking the distance from the floor.
See the sample scene at `Assets/MRTK/Examples/Experimental/CameraOffset/CameraOffsetTest.unity`
- Addresses some of #7913
Some sharp edges
* This only affects simulated inputs - MR and VR will still have different interpretations of the camera origin
* This is applied at _play_ time - the camera reset code in `MixedRealityToolkit.EnsureMixedRealityRequirements` will still be applied at edit time, which may be confusing with editor previews. I …

Support for camera offset to the input simulation

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

This PR addresses two related issues:
1. The bounding box script does not allow proper scaling when the its target is set to a child of the GameObject the script is attached to. This issue is resolved by making sure target.transform instead of transform is used when initializing scale constraint. A test is added to help verify the fix.
2. The existing test utility seems to work (tests pass), but the way it is working is unintended. The change of bounding box's scale in InstantiateSceneAndDefaultBbox() happens after the instantiation of bounding box and the assignment of its target, which causes scale constraint never getting the correct "initial scale" information. The location of scale change is now moved so that scale constraint now gets the correct value. Also, the "initial scale" …

Fix scaling issue of bounding box

---

Assets/MRTK/Examples/Demos/HandTracking/Profiles/RecordArticulatedHandPoseInputSystemProfile.asset

This PR addresses the issue of Input Playback Service missing from RecordArticulatedHandPoseInputSystemProfile causing record and playback errors in the HandInteractionRecordArticulatedHandPose scene.
- Fixes: #8499.

Add Input Playback Service to RecordArticulatedHandPoseInputSystemProfile

---

Assets/MRTK/Examples/Experimental/Solvers/FollowSolverExample.unity
Assets/MRTK/Examples/Experimental/Solvers/FollowSolverExample.unity.meta
Assets/MRTK/SDK/Experimental/FollowSolver/Follow.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

Follow Solver was added back in January but only scripts were added. 
https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6981
Adding an example scene with a near menu example that demonstrates the behavior. Updated default values in the Follow.cs to match the shell behavior.
- Added FollowSolverExample.unity scene (still under Experimental folder)
- Updated default values in Follow.cs
- Tested on HoloLens 2 device

Adding Follow Solver Example scene

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs

Fixed lingering concern from #8386 where we don't always update the previous stickinput state

Teleport cleanup

---

Assets/MRTK/Providers/Oculus/XRSDK/Profiles/OculusXRSDKDeviceManagerProfile.asset

Missing gameobject references on the xrsdk device manager profile caused CI breaks, fixing it here

Fixed missing gameobject references on xrsdk device manager profile

---

Assets/MRTK/Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs

There's a GUID workaround for AssetRetargeting for Unity 2019-specific code, but that GUID changed in #8386.

Update GUID which changed in #8386

---

Documentation/GettingStartedWithMRTKAndXRSDK.md

Currently XR remoting does not work when using the XR SDK. A workaround has been found but the current documentation does not include that.
- Provide a workaround to #8044 in the documentation.

Provide a workaround in doc for an issue preventing XRSDK remoting to work

---

scripts/docs/templates/mrtk/styles/main.js

This PR adds Google Analytics to our documentation site hosted on GitHub.

Add analytics to doc site

---

Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/RadialSet.prefab

This PR fixes the problem of radial buttons in the radial set prefab are sometimes unresponsive. Investigation of the matter showed that in the pressable button script (Press distance - release distance delta) must be larger than start push distance or the button will not work properly.
- Fixes: #8517.
1. Add the RadialSet prefab to your scene
2. Press each toggle once via near interaction
3. Try to press the toggles again and notice they still respond properly
Also validated on a HoloLens 2 device.

Fix unresponsive radial button

---

Assets/MRTK/Core/Utilities/XRSubsystemHelpers.cs
Documentation/GettingStartedWithTheMRTK.md
Documentation/Performance/PerfGettingStarted.md

2019.2 appears to have moved one subsystem definition while leaving the others in the experimental namespace. We don't want the actually functionality here, since most of it isn't stable or fully usable until 2019.3, but I'm adding this so it still builds.
- Fixes: #8501

Fix XRSubsystemHelpers on 2019.2

---

Documentation/Updating.md

This PR contains a couple of tweaks to the updating guide to make things a little clearer:
Removes specific references to 2.4.0 as being the latest (we generally just recommend using the migration tool from here on out, so there's no reason to call out 2.4.0 in the 2.5.0 release)
Changes the phrase "most of" to "the following" because the instructions actually say which folders to delete, and "most of" is terribly, terribly imprecise when it comes to telling people to delete things ("delete most of it, it's fine!")

Upgrading documentation fixes/updates

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8563
See comments on that issue for what's going on. Usually once the .4 LTS release shows up we focus our support on that (instead of trying to "backport" fixes to earlier Unity tech releases) but in this case it's a pretty trivial change.

Slate PanZoom example is panning vertically with horizontal hand movement

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/PerAxisHandles.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

- disabled collider on visuals before removing them in case they get updated before they're removed at the end of the frame (could cause a warning)
- readded unconditional collider removal on rotation handles as colliders for handles are directly attached to the handle object itself and not the visuals
- added test to verify that handles will always attach the handle collider on the handle gameobject and not the visual
- Fixes:  #8550 
added test

Fixed occasional warning on null size collider when instantiating bounds control with activation on start

---

Assets/MRTK/Examples/Common/Prefabs/Help_Panel_Viewer.prefab

Input simulation helper text overly was occupying too much space in regular DPI monitors and small window sizes.
- Updated helper prefab: Polished the text size, anchor and the placement.
- Fixes: #8564

Input Simulation key help text overlay polish.

---

scripts/docs/templates/mrtk/styles/main.js

This change cherry-picks the analytics change in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8532 into the latest release.
So the reason we have to do this is interesting:
Prior to last month-ish, the default branch that showed up on our github.io was mrtk_development, which meant that the previous change would have worked about a month ago. We recently made a change to switch our default github.io branch (https://microsoft.github.io/MixedRealityToolkit-Unity/Documentation/GettingStartedWithTheMRTK.html) to point to the latest release (i.e. right now, 2.4), which means that the previous change didn't actually show up in the default/root folder.
In order to make this change show up, we need to cherry pick the change and then rebuild the docs (which will happen automatically …

Pull in the analytics update into the latest release (i.e. default github.io page)

---

Assets/MRTK/Core/Services/BaseBoundarySystem.cs
Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs
Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs

This PR fixes warnings created by MixedRealityBoundarySystem by checking whether there is any XR device before performing subsequent steps that require such device (e.g. SetTrackingSpace()). Thanks @keveleigh for coming up with the idea of adding the virtual IsXRDevicePresent property in base class that defaults to true to prevent a breaking change.
- Fixes: #8568.

Check the presence of XR device before dependent subsequent steps

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs
scripts/ci/validatecode.ps1

Unit tests for the Oculus Integration tool have dependencies on asmdefs that are for Unity 2019.3+ 
This caused breaks in the CI pipeline. We're removing those dependencies when building the nuget packages as those tests are disabled for Unity 2018 versions anyways.

Remove 2019 test dependencies when building on 2018

---

Documentation/Updating.md

Going through the upgrade instructions, I found that there are a few locations that are out of date and also not clear enough:
1. The folder got renamed last release, so we can update the instructions to the 2.4 naming
2. I wanted to be clearer about what the instructions are for (2.4.0 to 2.5.0), and point folks at the previous if they were on 2.3
3. Updated the migration tool instructions to be clearer about how to run it (since it's not actually immediately obvious how to migrate).
4. There's a line where we tell people to watch out when deleting the Library/ folder, but we do that after telling them a few steps after telling them to delete the Library folder... which isn't very helpful.
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8551

Update the upgrade instruction docs to be clearer about how to actually do the upgrade

---

Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerMappingProfileInspector.cs

Adds a check before creating the `ControllerPopupWindow` that the MRTK object is initialized. If it's not initialized, we can't get the input action profile, and thus can't get the input actions to display in the window.
Also removed some unused variables.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8368

Fix controller popup window when MRTK isn't initialized

---

Assets/MRTK/Core/Utilities/StandardShader/HoverLight.cs
Assets/MRTK/Examples/Demos/StandardShader/Scenes/HoverLightExamples.unity
Assets/MRTK/Examples/Demos/StandardShader/Scenes/HoverLightExamples.unity.meta
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.anim
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.anim.meta
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.controller
Assets/MRTK/Examples/StandardAssets/Animations/HoverLightRotate.controller.meta
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightGray.mat
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightGray.mat.meta
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightParticle.mat
Assets/MRTK/Examples/StandardAssets/Materials/HoverLightParticle.mat.meta
Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader
Documentation/Rendering/HoverLight.md

This pull request primarily addresses a recent warning about 3 hover lights present (#8543), but it also addresses a portion of a request for more lights (#5888).
To keep existing performance characteristics the same I've added two new multi compile shader keywords that get enabled/disabled as more lights are added and removed. This means by default the MRTK/Standard shader only calculates up to two HoverLights but will begin to calculate more in tiers (4 and 10) as more are added. Users should profiler their applications to see if their scenario can handle up to 4 or 10 dynamic lights.
I've also create a new HoverLight example scene showing off this functionality and updated the docs.
Note, this change does introduce more shader permutations in the final build. But, the delta is modest. …

Adding Scalable HoverLight Support

---

Assets/MRTK/Tools/BuildWindow/Arm64Workaround.cs
Assets/MRTK/Tools/BuildWindow/Arm64Workaround.cs.meta

With some of our recent testing, we found that the ARM64 compiler bug described here https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7624 is actually affecting some new code that was introduced in the 2.5 timeframe. This time around, it's actually a lot worse because it's leading to crashes.
While there's been a fix to the VS compiler that should be coming in a future VS update, there's still going to be some time between the latest MRTK 2.5 release and the VS compiler update, during which things will be a lot worse.
There's a workaround that was identified in the linked issue, and I figured it would be best to add some auto-magic to the build process that will automatically update your IL2CPP project to add this compiler flag ONLY to the ARM64 build option.
This code will …

Add a workaround for the ARM64 issue for IL2CPP + WSA builds

---

Assets/MRTK/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs

Instancing isn't supported on all platforms, so the visual profiler should only attempt it if supported. See the fixed bug below for more info.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8600

Check if instancing is supported before attempting it in visual profiler

---

Assets/MRTK/Core/Definitions/Utilities/AxisFlags.cs
Assets/MRTK/Core/Definitions/Utilities/RotationConstraintType.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/MoveAxisConstraint.cs
Assets/MRTK/SDK/Features/Input/Handlers/Constraints/RotationAxisConstraint.cs

This reverts commit 121c4573f2ffb4dc5853f2571f5f74905e572273, reversing
changes made to 5730fa18cbe5f300a5145ebd1013d35e203ef9b9.
reverted the changes to axis flag as it's breaking user asset files (and mrtk example scenes)
there needs to be more investigation on android side to tackle the original issue. 
- Reopens: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/7463
- Fixes parts of: #8555

Revert "Merge pull request #8190 from MaxWang-MS/AxisFlags_fix"

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Extensions/InteractionSourceExtensions.cs

1. Getting the SpatialInteractionManager, which involves jumping over to the UI thread, is something we do in a couple places, so it makes sense to provide that alongside the other native resources we provide in WindowsMixedRealityUtilities.
1. Typically when the manager is needed, it's to iterate through all `SpatialInteractionSource`s and find the one that represents the current Unity `InteractionSource`. This logic has also been refactored out, provided as an `InteractionSource` extension method.

Refactor SpatialInteractionManager access and conversions from Unity to native SpatialInteractionSource

---

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityNearPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs

I was doing a diff between our core interfaces between 2.4 and 2.5 to see if we had any breaking changes in that layer. I found three:
1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8258 adds a new required method to IMixedRealityPointerMediator, which seems unavoidable because it's a required contract for the mediator respecting pointer preferences.
1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8227, which could be split out into an IMixedRealityDictationAudio interface.
1. https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7712, which added a grasp axis method to IMixedRealityNearPointer that seems to be only internally used by the sphere pointer at this time.
This PR updates the change made in IMixedRealityNearPointer to instead define that …

Remove breaking change from IMixedRealityNearPointer

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Documentation/ReleaseNotes.md

During testing, it was discovered that a duplication of AudioSpatializerMSHRTF.dll occurs in the following scenario:
* Unity 2019.4
* XR SDK
* Click "Apply" on MRTK Configuration dialog.
This was caused by the configuration dialog attempting to check the legacy XR option, which was triggering the installation of the legacy Windows Mixed Reality UPM package.
Unfortunately, this install is not reflected in Packages/manifest.json which makes it difficult for customers to identify a means of resolving the duplication.
This change suppresses attempts to enable legacy XR on Unity 2019 and newer and was verified by creating and importing a local version of the foundation package.

Fix implied install of legacy Windows Mixed Reality package with config dlg

---

Assets/MRTK/Examples/Experimental/ExamplesHub/Prefabs/ExampleHubButton.prefab

This PR removes the non-convex mesh collider from the logo so that when a hand touches the button the ClosestPoint warnings will no longer appear.
- Fixes: #8649.

Remove collider from MRTK logo on example hub button

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity

This PR removes a non-working close button from the "Grab to manipulate the entire scene" TitleBar. Further more the world anchor is removed from SceneContent to enable grab titlebar manipulation in remoting mode and on HL2 device.
- Fixes: #8553.

Fix the titlebar in the HandInteractionExamples scene

---

Assets/MRTK/Providers/UnityAR/Editor/UnityARConfigurationChecker.cs
Assets/MRTK/Providers/UnityAR/Microsoft.MixedReality.Toolkit.Providers.UnityAR.asmdef
Documentation/CrossPlatform/UsingARFoundation.md

Updates the UnityAR asmdef for Unity 2019, so the configuration checker doesn't have to edit an immutable file.
- Part of #8574, follow-up to #8591 and #8655

Update UnityAR asmdef

---

Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PrefabSpawner.cs

This PR fixes two issues in the Examples Hub Tooltip scene:
1. The blue platonic now shows a tooltip when pressed as expected
2. The scale of tooltip generated after looking at the green platonic is now correct
- Fixes: #8578

Fix tooltip in the Examples Hub Tooltip scene

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

Since we're only using this script to build packages for Unity 2018, where certain projects might not exist, we can safely skip it. Since we're also migrating off support for the NuGet packages (no longer publishing publicly), this is an okay scenario.
Still logs, in case we need to debug any issues. This will resolve any asmdef references that only exist in Unity 2019 for https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8574.

(Fix CI) Make a missing asmdef a warning instead of an exception in MSBuild scripts

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs
Assets/MRTK/Providers/LeapMotion/MRTK.LeapMotion.asmdef

- Removes the editing of the formerly named `Microsoft.MixedReality.Toolkit.Providers.LeapMotion` asmdef in the configuration checker because Unity 2020 does not support editing asmdefs for UPM 
- Adds placeholders to the root leap asmdef now named `MRTK.Leap`

Update Leap Configuration Checker for 2020 Support

---

Documentation/ReleaseNotes.md

This change adds a release not describing how to resolve a "No spatializer was specified" warning from Unity.

Add release note re: no spatializer warning

---

Assets/MRTK/Tools/BuildWindow/Arm64Workaround.cs

This change wraps the ARM64 workaround in a try/catch to make sure the workaround itself is best effort. There are a few operations in there that do file I/O which could throw if: the csproj file isn't found (i.e. some other step does post processing to rename files), the csproj file is locked for editing (some other build step opens the file and locks it for editing).
This should make it so that even in those cases, there won't be a stray exception on build.

Update the ARM64 workaround to be best effort

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

With some of the Generate SDK Project failures that we've encountered, there's an error in CI but no error actually logged there.
The exception doesn't appear to be captured and logged (i.e. it just kills the process). This updates the code to actually log before killing off the process, so hopefully future errors that we encounter, we can have more immediately actionable build logs.

Update the CI process to log a warning/error when there's an unknown project failure

---

Assets/MRTK/Core/Utilities/StandardShader/HoverLight.cs

The messages that were added for the hover light increase/decrease tends to clutter the console output - they're valuable for us as things increase/decrease, though probably less so for normal use cases like with leap hands.
https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8700
I'm removing the more routine logs and keeping the limit one (i.e. when you hit the max value)

Remove the verbose hoverlight debug log messages

---

Documentation/ReleaseNotes.md
Documentation/Tools/HolographicRemoting.md

This PR improves the remoting documentation by including separate paths for people to enable remoting based on whether legacy XR or XR SDK is used.
- Fixes: #8716

Add instructions for remoting when using XR SDK

---

scripts/docs/web/version.js

This change adds 2.5.0 to the collection of documentation versions and sets the default to the latest (2.5.0).
Do NOT merge this until the final release process is complete.

Update github.io documentation version list and default

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/Extensions/InteractionSourceExtensions.cs

Follow-up to #8592. Re-adds the haptics extensions that were removed in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/6364, and additional adds in-editor support via DotNetWinRT.

Re-add haptics to InteractionSourceExtensions

---

scripts/ci/validatecode.ps1

As part of #8574, several `[InitializeOnLoad]` tags and asmdefs were removed. We can go ahead and trim down the exceptions lists!

Clean up CI exceptions list

---

Assets/MRTK/SDK/Editor/Migration/Tools/MigrationTool.cs
Documentation/ReleaseNotes.md

#8733 identified a bug in the migration tool in which it is searching for assets in immutable folders. With the MRTK being provided as UPM packages, this causes a failure to load scene error when the scene system scenes (ex: DefaultLightingScene) are encountered.
This change limits the migration tool to only work on files in the Assets folder tree.
It does _not_ fix the inability to load the scenes (that change is forthcoming in a new PR_)
**_This change should be considered for a 2.5.1 UPM release as it prevents customers from using the Migration Tool._**
Fixes: #8733

Fix for #8733: Limit migration tool to Assets folder tree

---

Documentation/CrossPlatform/OculusQuestMRTK.md

#8359  Overview
Updated docs to more clearly indicate that the prefab references for the OculusXRSDKDeviceManager should get populated.

Added common issue for OculusXRSDKDeviceManagerProfile Prefab 

---

Assets/MRTK/Examples/Experimental/ColorPicker/ColorPickerExample.unity

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8720
Was looking at this issue earlier and thought maybe there was some deeper regression, but after some quick digging found that it was just an error in the scene itself (i.e. it had duplicate EventSystem objects on the main camera).
Since I was already looking at this, I decided it would be good just to get this patched up.

Remove duplicate EventSystems in ColorPickerExample

---

pipelines/ci-daily.yml
pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml
pipelines/ci-release.yml
pipelines/ci-weekly-internal.yml
pipelines/ci.yaml
pipelines/pr.yaml

I think this didn't used to work or something? But I found while working on a different repo's pipeline that I could do this now. Helps reduce the number of places we need to update version numbers to one for the pipelines.

Use variable expansion for CI/PR demands

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/LeapMotionHandTrackingExample.unity

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8654
Basic example scene cleanup - opening example scenes shouldn't show warnings in the Unity editor. I was already looking at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8720, this was in the same neighborhood so I opted to fix this one as well.
Basically, the main camera had two EventSystems on it (so we deleted the duplicate one)

Remove duplicate EventSystem in LeapMotion Hand Tracking Example

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs

Fix issue where profile changes would not be saved between closing and reopening unity instances. Also made the integration tool affect all profiles of the relevant type
- Fixes: #8767, #8768

Fixed issue where the oculus profile would not save between integrations

---

Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/InteractableToggleCollection.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Simulation/InteractablePointerSimulator.cs
Assets/MRTK/Tests/PlayModeTests/InteractableTests.cs

Interactable should always check for `CanInteract` no matter it is responding to far interaction or near interaction.
Thanks @rfurmaniak for proposing the change!
- Fixes #8479

Make sure NearInteraction triggers CanInteract check

---

Assets/MRTK/SDK/Features/UX/Animations/Cursors/TeleportCursor/TeleportCursorController.controller
Assets/MRTK/SDK/Features/UX/Animations/Cursors/TeleportCursor/TeleportInvalid.anim
Assets/MRTK/SDK/Features/UX/Animations/Cursors/TeleportCursor/TeleportValid.anim
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs

#Overview
Previously the SetVisibility function would set the hand visual object as active/inactive for the teleport cursor. This interfered with the cursor since it's animation state was tied to the hand visual object. This PR changes the SetVisiblity script and the animation so that they no longer conflict with each other.
- Fixes: #8755
>
>
> …

Fixed teleport animations/scripts to not reset animator state

---

Documentation/README_ScrollingObjectCollection.md

I assume this text was copied from README_TapToPlace.md and this line was forgotten to be deleted.

Remove unnecessary sentence in README_ScrollingObjectCollection.md

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionTouchablesExample.unity

https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8719
This has been around for a bit - I'm doing a cleanup pass of example scenes and this was on my radar for the day.
Per the information in the issue, this has been around for some time when the script attached to this plane was deleted. I've opted to just delete the broken functionality here so that we don't have missing script warnings in the scene itself. I've also updated the text for the scene description panel to remove the mention of that plane.

Remove the broken touchable plane from HandInteractionTouchableExamples

---

Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs

When we had a big list of scenes to be included in the build, the layout of the "Unity Build Options" tab in the Build Window would keep growing. Thus, the buttons to open Visual Studio and build the Unity Project can easily become clipped and out of reach. This pull request adds a scroll view to surround the list of scenes in order to avoid this issue.
- Fixes: Add a scroll view around the list of scenes to be included in the "Unity Build Options" tab of the Build and Deploy Window.

Add a scroll view to the list of included scenes on the Build Window

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/LeapMotionHandTrackingExample.unity

This change cherry-picks the fix for issue #8654 so that the sample in 2.5.1 is implemented correctly and does not display the multiple event systems warning.

Cherry-pick fix for #8654 for 2.5.1 release

---

Assets/MRTK/Core/Extensions/TypeExtensions.cs

Fixes an exception that prevents the use of the Receivers dropdown in an Interactable when some assembly types can't be loaded (e.g. some Cecil assemblies etc. that have weird types).
There was already AssemblyExtensions.GetLoadableTypes so this is now properly used in TypeExtensions.GetAllSubClassesOf. No new code added besides renaming "GetTypes" to "GetLoadableTypes".
In recent Unity versions any of these "walk assembly, get types" constructs could be vastly sped up by using the [TypeCache API](https://docs.unity3d.com/2019.2/Documentation/ScriptReference/TypeCache.GetTypesDerivedFrom.html) available from 2019.2. This would reduce domain reload times considerably.

fix ReflectionTypeLoadException when opening the Receivers dropdown

---

Assets/MRTK/Core/Inspectors/Profiles/DataProviderAccessServiceInspector.cs

Partially fixes #8802 
Some of the error messages there seem to be "by design but misleading", e.g. a new data provider is created without a concrete type (type is "(None)") and then an error is logged that the type (obviously) is not a concrete type, so I'm not quite sure what the best approach would be – maybe this should be a warning in the editor and an error in a build?

Sanitize data provider array access

---

Documentation/ReleaseNotes.md
Documentation/usingupm.md

This change adds the following note to ReleaseNotes.md and usingupm.md
> [!IMPORTANT]
> There is a known compiler issue that impacts applications built for Microsoft HoloLens 2 using
> ARM64. This issue is addressed in the forthcoming 16.8 update for Visual Studio 2019. Until the 
> update is available, please import the `com.microsoft.mixedreality.toolkit.tools` package to apply 
> a workaround.

Add additional references to the ARM64 workaround to ReleaseNotes and UsingUpm articles

---

scripts/docs/web/version.js

This change adds 2.5.1 to the available docs list and sets the default version displayed to 2.5.1

update the docs list and default to 2.5.1

---

Assets/MRTK/Core/Inspectors/MixedRealityStandardShaderGUI.cs
Assets/MRTK/SDK/Features/UX/Interactable/Materials/HolographicButtonIconFontMaterial.mat
Assets/MRTK/StandardAssets/Shaders/MixedRealityStandard.shader

Icon rendering is noticeably blurry on VR devices Hololens 2 (slightly less so for the latter). By adding super sampling (https://medium.com/@bgolus/sharper-mipmapping-using-shader-based-supersampling-ed7aadb47bec) we can improve the icon rendering quality without too much performance impact.
- Fixes: #8713

Add super sampling option for mrtk standard shader

---

Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs

The input module is required by MRTK but in Windows Mixed Reality headset builds the module sometimes cannot be correctly activated due to the `IsModuleSupported` function not being properly overridden.
- Fixes #4821

Mark MixedRealityInputModule as always supported

---

Assets/MRTK/Tools/RuntimeTools/Tools/InputFeatureUsageTool/ListInputFeatureUsages.cs

There was an edge case where no input devices were detected _and_ the textMesh was already empty that caused this `if` and `continue` to be skipped, which led to an IndexOutOfRangeException a few lines lower. We want to always `continue` if no input devices are detected and clear the text if it's not already empty.

Separate out if checks so we don't skip the continue and cause IndexOutOfRangeException

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Art/Shaders/RimOutline.shader

Renamed the path for the shader so it fell under the same folder.
Previously:
Now:
>
>

Rename RimOutline so there's only one 'Mixed Reality Toolkit' item in the Shader list.

---

Documentation/Authors.md
Documentation/ReleaseNotes.md

This change removes the note that 2.5.1 is a UPM only release. It also fixes an authors list formatting issue.

Update release notes, fix authors formatting

---

Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset
Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset

The Oculus controller types had their types changed but the profile serialization wasn't committed. This _should_ be a non-issue for users, as these profiles can be pretty aggressive at reserializing locally, but we may as well check them in correctly.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/fecccf9e3bdadd67cd21409667a65f3843c83afd/Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs#L15-L21
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/fecccf9e3bdadd67cd21409667a65f3843c83afd/Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs#L42-L50

Update mapping profile serialization for Oculus types

---

Assets/MRTK/Core/Extensions/GameObjectExtensions.cs
Assets/MRTK/Core/Extensions/UnityObjectExtensions.cs
Assets/MRTK/Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerHandlerExample.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/InteractableToggleCollection.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs
Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonConfigHelper.cs
Assets/MRTK/SDK/Features/UX/Scripts/PressableButtons/PressableButton.cs
Assets/MRTK/SDK/Features/UX/Scripts/Tooltips/ToolTip.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/ToggleHandVisualisation.cs
Assets/MRTK/Services/InputSystem/GazeProvider.cs
Assets/MRTK/Tests/PlayModeTests/PointerTests.cs

Using https://github.com/microsoft/Microsoft.Unity.Analyzers (which I think is included in VS by default? or maybe the [extension](https://docs.microsoft.com/en-us/visualstudio/cross-platform/using-visual-studio-tools-for-unity?view=vs-2019)?), a few common cases were flagged.
Fixes:
1. [UNT0003 Usage of non generic GetComponent](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0003.md)
1. [UNT0008 Null propagation on Unity objects](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0008.md)
1. [UNT0014 GetComponent called with non-Component or non-Interface Type](https://github.com/microsoft/Microsoft.Unity.Analyzers/blob/main/doc/UNT0014.md)
I wouldn't be surprised if I missed some (especially UNT0008), but it'd be good to clean these up when …

Fix up some Unity behavioral warnings

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Prefabs/Panels/ToggleFeaturesPanel.prefab
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/FeaturesPanelVisuals.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/FeaturesPanelVisuals.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/ToggleHandVisualisation.cs

Makes the Oculus hand mesh rendering controlled by the Hand Visualization Profile
- Fixes: #8793
>
>
>
>
> git checkout …

Make oculus hand rendering controled by the hand visualization profile

---

Assets/MRTK/Providers/Oculus/XRSDK/Profiles/DefaultOculusXRSDKDeviceManagerProfile.asset

When using UPM, changes made to the default profiles are not saved due to using existing inside the Packages directory. Thus, we have to ensure that the DeviceManager is initialized with the relevant prefabs at startup, even if those prefabs contain missing references that require the Oculus Integration package.
Previous iterations of this solution broke CI, but the latest Unity versions seem to not raise those CI errors, so trying this fix once again.
- Partially Fixes: #8849

Oculus Device Manager initialized with Oculus Prefabs

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/DefaultPointerMediator.cs
Assets/MRTK/SDK/Profiles/HoloLens1/DefaultHoloLens1InputSystemProfile.asset
Assets/MRTK/SDK/Profiles/HoloLens1/DefaultHoloLens1PointerProfile.asset
Assets/MRTK/SDK/Profiles/HoloLens1/DefaultHoloLens1PointerProfile.asset.meta

Currently there are some issues with HoloLens 1 style interaction on HoloLens 2 and other devices:
- Using the DefaultHoloLens1ConfigurationProfile on HL2 does not bring HL1 style interaction as the DefaultMixedRealityInputPointerProfile is used for both HL1 and HL2 configuration profiles.
- Without profile switching, one should be able to switch between those two interaction styles by specifying articulated hand for both default controller pointer and the GGV pointer and then toggle the hand ray on or off at runtime. However the existing pointer mediator does not include logic for prioritizing non-GGV far pointer of an input source over a GGV pointer causing unexpected behavior. 
- Add a new pointer profile and associate it with the HL1 configuration profile
- Add logic to handle both …

Various GGV pointer related fixes

---

Documentation/Contributing/Roadmap.md
Documentation/usingupm.md

#8825 fixed an error in the sample we give for people to copy and paste into their manifest.json, which feels important to have on our default docs version.
#8862 retooled our roadmap, which also feels important to have on our default docs version.

Cherry pick some recent docs changes to 2.5.1

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

HandInteractionPanZoom.EndAllTouches no longer calls RaisePanEnded when there is no hand data in the map.
- Fixes: #8874

Added check for hand data count in EndAllTouches before calling RaisePanEnded

---

Assets/MRTK/Core/Definitions/Devices/MixedRealityInteractionMapping.cs
Assets/MRTK/Core/Definitions/Devices/MixedRealityInteractionMappingLegacyInput.cs
Assets/MRTK/Core/Definitions/Devices/MixedRealityInteractionMappingLegacyInput.cs.meta
Assets/MRTK/Core/Definitions/Devices/WindowsMixedRealityControllerDefinition.cs
Assets/MRTK/Core/Definitions/Devices/WindowsMixedRealityControllerDefinition.cs.meta
Assets/MRTK/Core/Providers/InputSimulation/SimulatedMotionController.cs
Assets/MRTK/Core/Providers/UnityInput/GenericJoystickController.cs
Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset
Assets/MRTK/Providers/OpenVR/WindowsMixedRealityOpenVRMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/BaseWindowsMixedRealitySource.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/BaseWindowsMixedRealityXRSDKSource.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset

Continues defining specific "definitions" for controllers, separating that from the input APIs.
- Part of the controller mapping profile rework
- Follow-up to PRs like https://github.com/microsoft/MixedRealityToolkit-Unity/pull/7146

Refactor out WMR controller definition

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs

Fix some typos in ButtonConfigHelperInspector that are causing exceptions in the inspector.
- Continuation of #8848

ButtonConfigHelperInspector typo fix

---

scripts/ci/common.psm1
scripts/ci/githubchanges.ps1
scripts/ci/validatebuildlog.ps1
scripts/ci/validatecode.ps1
scripts/ci/validatedocs.ps1
scripts/lint/prettyjson.ps1
scripts/packaging/createnugetpackages.ps1
scripts/packaging/createupmpackages.ps1
scripts/packaging/examplesfolderpreupm.ps1
scripts/packaging/extensionsfolderpreupm.ps1
scripts/packaging/foundationpreupm.ps1
scripts/packaging/publishupmpackages.ps1
scripts/packaging/unitypackage.ps1
scripts/packaging/updateMRTKVersion.ps1
scripts/packaging/versionmetadata.ps1
scripts/test/generate_repeat_tests.py
scripts/test/run_playmode_tests.ps1
scripts/test/run_repeat_tests.ps1

To make sure we're in compliance with the [copyright header rules](https://docs.opensource.microsoft.com/content/releasing/copyright-headers.html), this adds the header to any Powershell or Python script that was contributed by a Microsoft employee. Most of these are custom to do with our CI.
We normally keep on top of this for C# scripts well, but seems we've overlooked some non-C# scripts.
Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8102.

Add Microsoft copyright header to scripts contributed by Microsoft

---

Assets/MRTK/StandardAssets/EditorUtilities/OnLoadUtilities.cs

OnLoadUtilities.cs fails to copy shaders when running on MacOS due to a filename sensitivity issue.
The constant `ShaderSentinelFile = "MRTK.Shaders.Sentinel";` refers to a file that is actually named `MRTK.Shaders.sentinel` with a lowercase `s` on sentinel.
On MacOS DirectoryInfo.GetFiles appears to be case-sensitive even if the underlying filesystem is not. This causes the script to not find MRTK.Shaders.sentinel and thus not be able to copy the shaders.
Fix the issue by using a lowercase `s` in the constant.
Fixes #8826

Fix Shader import error seen on Mac editor

---

Assets/MRTK/SDK/Features/UX/Scripts/Collections/BaseObjectCollection.cs

I've found myself making data driven lists with the built-in object collection implementations (specifically, the grid collection). What's nice about this approach is I can keep the list component completely separate from the app code driving the data binding. The only issue is the `ObjectCollectionNode` list isn't accessible to any other component. I completely understand why it shouldn't be _modified_, but the accessibility level prevents some simple tasks like "is this object a part of this collection?" My fix is to add a public, read only version of the  `ObjectCollectionNode` list. Additionally I've changed the Contains check method to public as well, for the same reasons above.
> you want from …

Object collection list accessibility, adding a read only list

---

Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs

Opening MRTK in Unity 2020.1 highlights some issues regarding the new Unity 2020.1 API changes.
- use Unity 2020.1 C# directive 
Open MRTK in a Unity 2020.1 and you should not see any errors.

Small fixes for Unity 2020.1

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

The Generic XRSDK Spatial Mesh Observer had carried over an adapter. In the Legacy WMR Spatial Mesh Observer, a WorldAnchor was a part of the API for getting the spatial meshes from the platform. The WorldAnchor ignored the transform on the MRTKPlayspace. So an adapter was necessary to fold in the transform from the camera hierarchy.
In the new XRSDK, there is no such anchor. Therefore, the adapter is no longer necessary. Furthermore, since the adapter was trying to compensate for a WorldAnchor which wasn't actually there, it was overcompensating and putting the spatial meshes in the wrong position.
Fix is simply to delete the adapter. 
- Fixes: #8920 .
@davidkline-ms , it looked like there was some cut&paste error with the profiling tags. The +PlayspaceAdapter tag carried on beyond the …

Remove unnecessary PlayspaceAdapter

---

Assets/MRTK/Core/Definitions/Utilities/MixedRealityPose.cs
Assets/MRTK/Core/Definitions/Utilities/MixedRealityTransform.cs
Assets/MRTK/Core/Providers/BaseGenericInputSource.cs
Assets/MRTK/Core/Providers/BaseSpatialObserver.cs
Assets/MRTK/Core/Providers/GenericPointer.cs
Assets/MRTK/Core/Providers/InputSimulation/KeyBinding.cs
Assets/MRTK/Core/Utilities/WindowsDevicePortal/DataStructures/DeviceInfo.cs
Assets/MRTK/SDK/Features/UX/Scripts/VisualThemes/States/State.cs
Assets/MRTK/Tests/PlayModeTests/EventCatcherTestUtilities.cs

Looks like when running the latest docfx (our pipeline was recently updated) with VS 2019 (our pipeline was recently updated), some in-box overridden methods aren't able to have their docs inherited. This cleans those tags up.

Clean up some inheritdoc tags

---

pipelines/templates/tasks/unitybuild.yml

Currently, the IP address for the Unity cache server is stored in a pipeline-local variable. Since this value is part of our machine demands anyway
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/497b78606ffa58393ea70976215c20bb48af92f2/pipelines/pr.yaml#L11-L14
we can read it directly from the env variable.

Read CacheServerIPAddress from env instead of local variable

---

Assets/MRTK/SDK/Editor/Inspectors/UX/BoundsControl/BoundsControlInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/Links.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/PerAxisHandles.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/VisualUtils.cs
Documentation/README_BoundsControl.md

This PR addresses the following problems:
1. Currently setting flatten axis to anything other than nothing or auto creates exceptions at scene start if bounds control is set to active on start.
2. After setting the flattened axis a user can still scale the bounded gameObject along that axis. This PR changes the behavior to the following: if uniform scaling is used, the user can choose whether the flattened axis is also uniformly scaled with the other axes through `UniformScaleOnFlattenedAxis`; if non-uniform scaling is used, the user cannot scale along the flattened axis.
3. If the target's transform is modified externally, the bounds does not update to correctly reflect the change. This PR renames `OnTargetBoundsChanged` to `UpdateBounds` and makes it public so that developers can invoke …

Various BoundsControl fixes

---

Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs

When looking at the "Deploy Options" tab, if we delete a build from the AppPackages folder, the entry for that build will keep being rendered until the build list is refreshed. The only noticeable change is that the build date will change to a default value.
We can see this behavior here:
This pull request just adds a check to skip rendering entries whose folder were deleted. It doesn't actually remove them from the build list. However, if you feel that we should remove those folders from the list I can make that change.
- Fixes: Test whether the package build folder exists and skip rendering a build entry when it doesn't.

Skip rendering build entries when their folder was deleted

---

Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/BaseInteractiveElementInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/TouchEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/TouchEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceiverManager.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/FocusReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/TouchReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/TouchReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/TouchInteractionEvent.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/TouchInteractionEvent.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/StateManager.cs
Assets/MRTK/Tests/PlayModeTests/InteractiveElementTests.cs

Added the `Active` property and support for the Touch state to Interactive Element.  
Also added 2 new tests.
When the Touch state is added via inspector, a Near Interaction Touchable Volume is also added as a Near Interaction Touchable is required for touch input.  If a user adds the Touch state during runtime, a Near Interaction Touchable is added as well. 
Once a button class is added, a Near Interaction Touchable will be attached instead of a Near Interaction Touchable Volume.
The `Active` property controls whether or not the Interactive Element updates state changes internally.  The `Active` property maps to Interactable's `Enabled` property.  The naming was changed from `Enabled` to `Active` to limit the confusion between a Monobehaviour's `Enabled` property and Interactable's …

Add Active property and Touch state to Interactive Element 

---

Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Examples/Common/Scripts/LoadProfilesOnStartup.cs
Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHub.unity
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs
Assets/MRTK/Tests/PlayModeTests/PointerProfileTests.cs
Documentation/MixedRealityConfigurationGuide.md

As @keveleigh pointed out in #8787, it might be preferable to keep the UI camera during active profile switch process. The advantage includes reasigning ui camera to Unity UI(UGUI) canvas will no longer be necessary. However the existing approach makes sure the ui camera life cycle is in sync with the services of a profile.
Also modified `LoadProfilesOnStartup.cs` to make sure it no longer generates error messages.
- Continuation of #8787
Tested in editor play mode, editor remoting and HL2 device.

Keep the ui camera during active profile switch

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityInputActionsProfileInspector.cs

This height is good when rendered as a sub profile, so it doesn't take up the entire inspector.
However, when viewing as a standalone profile, it led to views like
Now it looks like

Improve scroll bar in input actions profile when not rendered as a sub profile

---

Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/BaseInteractiveElementInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/StateSelectionMenu.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/StateSelectionMenu.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceiverManager.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/CoreInteractionState.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/InteractionType.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/InteractionType.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/InteractionState.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/StateManager.cs
Assets/MRTK/Tests/PlayModeTests/InteractiveElementTests.cs

Adds a state sorting menu to Interactive Element.  When a user selects "Add Core State", the states are now sorted based on the Interaction Type. 
During play mode, when a state is active, it is highlighted with cyan in the inspector.  This makes a state change more obvious to the user. 
The Focus state encompasses both near and far interaction but the addition of FocusNear and FocusFar allows users to track whether an object is in near focus or far focus.  For example, if an object comes into focus with the controller ray pointer, that is considered far interaction.  If an object comes into Focus with the poke pointer, that is considered near interaction.   Added a test for these states. 
The gif below demonstrates the state value highlight in the inspector and how the object responds to …

Add state sorting menu and the FocusNear/FocusFar states to Interactive Element

---

Assets/MRTK/SDK/Features/UX/Scripts/Cursors/TeleportCursor.cs

Added a null check to prevent an exception that occurs when using Oculus Quest and moving the hands in and out of view.  This can be especially problematic when testing in the editor and being forced to remove the headset and unpause to allow execution to continue.

Prevent exception when using Oculus Quest with hand tracking and the TeleportCursor

---

Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKInputSystemProfile.asset
Assets/MRTK/SDK/Profiles/DefaultMixedRealityXRSDKControllerVisualizationProfile.asset

Mistaken profile change broke the camera on oculus quest. reverting

Hotfix reverting change breaking oculus quest camera

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Constraints/ConstraintManagerInspector.cs

Currently there is a bug associated with the constraint manager. To reproduce:
1. Add a cube to a scene with MRTK properly set up
2. Add `BoundsControl` to the cube
3. Go to the constraint manager component, switch to manual mode, add a constraint and then remove it
4. Click play and try to scale the cube. Note `NullReferenceException`s appear in the console
The bug is related to a call to `SerializedProperty.DeleteArrayElementAtIndex`, which supposedly should "delete the element at the specified index in the array", but instead it actually sets the element to null if it is not already null at the time of the call (otherwise it removes the element). Some on the Internet said this behavior ensured such removal did not break the indexing of the array and should "just work" when being …

Fix a DeleteArrayElementAtIndex related issue

---

pipelines/templates/common.yml
pipelines/templates/tests.yml

Our daily 2019 build has been failing tests for a long time. @CDiaz-MS recently added a Unity 2019 PR validation pipeline, which...doesn't fail tests 😲 PR validation runs tests after a Standalone build, while the daily 2019 pipeline builds UWP ARM64 first, which means the tests then attempt to run in the context of UWP, which attempts to start-up VR and seems to be the cause of many of the failures.
This PR
1. Adds `-buildTarget StandaloneWindows` to our test running command, which should reset the editor out of UWP
1. Updates our existing standalone build from x86 to x64, the more common architecture target for standalone

Lock tests to run on StandaloneWindows to try to improve daily CI

---

pipelines/ci-daily.yml

Like the 2019 PR validation pipeline, our daily 2019 build also depends on VS 2019 existing on the VM it's running on. Not all of our VMs have 2019 installed, so this ensures it'll only run on a supported machine.

Only run 2019 daily on a machine with VS2019

---

Assets/MRTK/SDK/Features/UX/Prefabs/Menus/NearMenu2x4.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Menus/NearMenu3x2.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Menus/NearMenu4x2.prefab

Some NearMenu prefabs have the buttons prefabs out of order and instances of labels not matching the names of the buttons (or vice-versa). We can see an example of this in the image below. 
This does **not** affect functionality in any way. Is just misleading that when we try to click a button with a given name in the hierarchy, it may not select the button with the same label in the scene viewport.
This pull request only reviews those occurrences and makes button names, labels and, order coherent across all NearMenu prefabs.
- Fixes: Organize and match the labels with buttons names in NearMenu prefabs.

Fix button names so that they match their labels in NearMenu prefabs

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs

Updates the line pointer so that its endpoint now tracks the cursor one to 1 instead of lagging behind somewhat noticeably
old line pointer behavior:
new line pointer behavior:
- Fixes: #8710
>
>
> commands (substituting {PR_ID} with the ID of this pull …

Adjusted line pointer endpoint to match the cursor 1 to 1

---

Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/BaseInteractiveElementInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/StateSelectionMenu.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ClickedEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ClickedEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/SelectFarEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/SelectFarEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ToggleOffEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ToggleOffEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ToggleOnEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/ToggleOnEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceiverManager.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ClickedReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ClickedReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/SelectFarReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/SelectFarReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ToggleOffReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ToggleOffReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ToggleOnReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/ToggleOnReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/SelectFarInteractionEvent.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/SelectFarInteractionEvent.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/CoreInteractionState.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/InteractionType.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/InteractionState.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/StateManager.cs
Assets/MRTK/Tests/PlayModeTests/InteractiveElementTests.cs

Added support for the following states:
- Selection of an object via far interaction 
|SelectFar State Behavior| SelectFar State Global option behavior |
|---|---|
| ![SelectFarState](https://user-images.githubusercontent.com/53493796/101115405-2b23ce00-3598-11eb-8784-5cf643885e62.gif)| ![SelectFarGlobalProperty](https://user-images.githubusercontent.com/53493796/101222366-7abcd500-363e-11eb-9624-bb35c4a0c686.gif)|
- The ToggleOn and ToggleOff states together create a toggle button.  These states are set by a far interaction click by default but can be set from any entry point using the `SetToggleStates()` method 
- This state is trigged with a far interaction click by default but can be triggered from any entry point using the `TriggerClickedState()` method.
The following figure …

Add SelectFar, Clicked and Toggle states to Interactive Element 

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs

HandInteractionPanZoom should now properly work with NearInteractionGrabbable, and the texture should not jump after the initial pointer down event.
- Fixes: #8869

Added check to see if Pointer is a IMixedRealityNearPointer to HandInteractionPanZoom.OnPointerDown

---

Documentation/CrossPlatform/OculusQuestMRTK.md

Removing a run on trailing line in the documentation.
Clarifying the functionality of the Oculus XRSDK Data provider and how it automatically sets up the OVR Camera Rig and OVR Hands for the user.
- Fixes: #8991, #8993

Oculus Documentation Data Provider Cleanup

---

Assets/MRTK/Providers/XRSDK/Profiles/DefaultHololens2XRSDKConfigurationProfile.asset
Assets/MRTK/Providers/XRSDK/Profiles/DefaultHololens2XRSDKConfigurationProfile.asset.meta
Assets/MRTK/Providers/XRSDK/Profiles/DefaultXRSDKConfigurationProfile.asset

fixes missing profiler in hand interaction scene if you're starting the examples with xr sdk default profile (unity 2019.4)
disabled spatial awareness setting
both flags now match the hl2 profile

enabled diagnostics / disabled spatial awareness for default xrsdk config

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MRTK/Services/InputSystem/GazeProvider.cs

Playspace transform was being ignored by EyeGazeDataProvider, but GazeProvider assumed incoming data was in world space.
- Fixes: #9049  .
> 
> This fix has the EyeGazeDataProvider transform the platform data, which is relative to the MRTKPlayspace, into world space before passing it to the consuming GazeProvider. Arguments could be made that the EyeGazeDataProvider should pass the data as is, and let the GazeProvider transform it to whatever space it wants. 
> 
> That approach, however, assumes that all platform data providers will have raw data in the same space, or else that another data provider which might have the data in world space, would have to transform it to playspace, then have the GazeProvider transform it back to world space.
>
> So I have taken the approach which I have, …

Apply playspace transform to eye gaze data

---

Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/BaseInteractiveElementInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/SpeechKeywordEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/SpeechKeywordEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/SpeechKeywordReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/SpeechKeywordReceiver.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/KeywordEvent.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/KeywordEvent.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/SpeechInteractionEvent.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/UnityEventDefinitions/SpeechInteractionEvent.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/Definitions/CoreInteractionState.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/States/StateManager.cs

Added support for the SpeechKeyword state in Interactive Element.  This state has a custom inspector.
In MRTK, a keyword has to be registered in the Speech Profile first.  If a user tries to add a keyword in this state, directions will appear on how to add a keyword in the Speech profile first.
If the keyword is registered in the Speech profile then an event for that keyword will be displayed.
1. Checkout the branch
1. Open new unity scene
1. Add MRTK to the scene
1. Add a cube to the scene
1. Attach the Interactive Element component
1. Select Add Core State button in the Interactive Element inspector
1. Add the SpeechKeyword state

Add SpeechKeyword state to Interactive Element

---

Assets/MRTK/Core/Services/BaseBoundarySystem.cs

In testing #9060, I realized that the boundary floor never shows up. In debugging, I realized we had a PR for 2.5.0 that moved the profile read before the bounds calculation, which means the visualization is never triggered. This is a regression from 2.4, so we're choosing to take this change in 2.5.2.
This change
1. Refactors out some common code from the property setters, so we only have to make changes to the flow in one place (and allows us to refresh the visualization without raising events)
2. Gates the event behind initialization, so we don't send a stream of them during profile read
3. Refreshes the visualization near the end of initialization

Fix boundary visualization for 2.5.2

---

Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/BaseInteractiveElementInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/CompressableButtonInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/InteractiveElement/CompressableButtonInspector.cs.meta
Assets/MRTK/SDK/Features/UX/Prefabs/InteractiveElement.meta
Assets/MRTK/SDK/Features/UX/Prefabs/InteractiveElement/CompressableButtonCube.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/InteractiveElement/CompressableButtonCube.prefab.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/BaseInteractiveElement.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/CompressableButton.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/CompressableButton.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/PressedNearEvents.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventConfigurations/PressedNearEvents.cs.meta
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/PressedNearReceiver.cs
Assets/MRTK/SDK/Features/UX/Scripts/InteractiveElement/Events/EventReceivers/PressedNearReceiver.cs.meta
Assets/MRTK/Tests/PlayModeTests/InteractiveElementTests.cs

`CompressableButton` is a component that contains the same exact logic and properties as `PressableButtonHoloLens2`.
The difference between `CompressableButton` and `PressableHoloLens2` is that CompressableButton inherits from `BaseInteractiveElement`.  The inheritance from `BaseInteractiveElement` adds far interaction support to CompressableButton, which eliminates the need for the `PhysicalPressEventRouter` component. 
The purpose of the `PhysicalPressEventRouter` was to trigger a clicked event in the `Interactable` component when a button was pressed via near interaction.  Now a near interaction press and a far interaction pointer down selection trigger the same clicked state. 
For MRTK 2.6, the current PressableButtonHoloLens2 prefabs will NOT be modified to avoid breaking changes for …

Add CompressableButton component with PressedNear state

---

Assets/MRTK/SDK/Features/Utilities/Solvers/Follow.cs

Fixes the re-centering logic in the Follow Solver for both Recenter() method.
- Fixes: recenterNextUpdate wasn't being considered in several calculations. Now when this flag is set, the follow solver will instantaneously move the object in front of the user at the default distance.
Fixes: #8152

Fix Follow recenter behavior

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs

Fixed regression with Oculus Hand pointer not displaying properly after moving towards using the Articulated Hand Definition for detecting Teleport Gestures

Fixed hand ray not showing up on Oculus

---

Assets/MRTK/Providers/Windows/WindowsDictationInputProvider.cs
Assets/MRTK/Providers/Windows/WindowsSpeechInputProvider.cs

To prevent our play mode test logs from being 18300 lines long, mostly [filled with speech exceptions](https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=15958&view=logs&j=c1841906-0df4-5516-e3c5-68840a78c082&t=74fd8acb-620e-53b4-2aaa-89fc9e6ab02f&l=18300), this PR blocks our log from printing when running via batch mode. Speech not being supported in batch mode is expected.

Clean up speech recognizer logs in test runner batch mode

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs

In the case where the hand hasn't moved, so no `OnInputChanged<MixedRealityPose>` event has been raised (which is the case in several of our tests), this method will fail and print out "Look rotation viewing vector is zero", because...it's hard to look in no direction. This updates the method to always look in a valid direction.
- Fixes

Update GGVPointer look rotation

---

Assets/MRTK/Tests/EditModeTests/Core/MixedRealityToolkitTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MRTK/Tests/PlayModeTests/ConstraintTests.cs
Assets/MRTK/Tests/PlayModeTests/InteractableTests.cs
Assets/MRTK/Tests/PlayModeTests/NearInteractionGrabbableTests.cs
Assets/MRTK/Tests/PlayModeTests/PressableButtonTests.cs
Assets/MRTK/Tests/PlayModeTests/VisualThemeTests.cs

Follow-up to #9080 and #9081. Removes the following logs:
1. `Can't add component 'MeshRenderer' to Cube because such a component is already added to the game object!`
1. We were trying to add a mesh renderer when we didn't need to. Uses `EnsureComponent` now
1. `Parent of RectTransform is being set with parent property. Consider using the SetParent method instead, with the worldPositionStays argument set to false. This will retain local orientation and scale rather than world orientation and scale, which can prevent common UI scaling issues.`
1. `BoxCollider is null, cannot set bounds of NearInteractionTouchable plane`
and some other assorted clean-up of unused local variables and method call simplification.

Clean up more test logs

---

Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityControllerMappingProfile.asset
Assets/MRTK/SDK/Profiles/DefaultMixedRealityControllerMappingProfile.asset

Reserializes the controller mapping profiles, adding `HPMotionController` to the InputActions example scene profile, as well as cleaning up some duplicated mappings in our default profile (extra left-handed WMRController and extra right-handed WMRArticulatedHand).
This PR also assigns `Select` to the HP Motion Controller's A button.

Reserialize mapping profiles

---

Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/OpenVR/HPMotionController.cs
Assets/MRTK/Providers/OpenXR/Profiles/DefaultOpenXRControllerMappingProfile.asset
Assets/MRTK/Providers/OpenXR/Scripts/HPReverbG2Controller.cs
Assets/MRTK/Providers/OpenXR/Scripts/HPReverbG2Controller.cs.meta
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftMotionController.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/HPMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs
Assets/MRTK/Tools/RuntimeTools/Tools/InputFeatureUsageTool/ListInputFeatureUsages.cs

1. Adds OpenXR support for HP Reverb G2 controllers
1. Fixes some cases where the controller image wasn't loading properly
2. Refactor out the existing WMRController definition for the OpenXR class

Add support for HP Reverb G2 controllers and update WMRController with definition

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

changed the setter for the config properties so everytime the config is changed, the visuals will be updated.
fix for #9044 and #8157
I am not fully sure whats happening to the old configs when overwriting them. Maybe some listeners need to be unregistered. Some help on this would be nice.

BoundsControl config fix

---

Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
scripts/ci/validatecode.ps1

This empty param field has been missed by our docs validation since it contains `_`. This adds docs for the tag and updates the validator.

Add missing underscore from docs validation param regex

---

Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs

If the input subsystem happens to be null at the time this is called, this line will null ref.

Fix potential null ref in boundary system

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitPreserveSettings.cs

This is currently a manual step for 2.5.3, since I completely missed adding it. Will add the step to the 2.5.3 docs.
We should probably try to find a better way to do this, instead of blanket-preserving the entire assemblies, as pointed out at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5273#issuecomment-513974004.

Add OpenXR to link.xml

---

Assets/MRTK/Core/Attributes/MixedRealityServiceProfileAttribute.cs
Assets/MRTK/Core/Definitions/Devices/MixedRealityControllerMappingProfile.cs
Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Core/Inspectors/Utilities/Search/MixedRealitySearchUtility.cs
Assets/MRTK/Core/Providers/Hands/HandJointService.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Services/BaseService.cs
Assets/MRTK/Core/Utilities/Editor/AssemblyDefinition.cs
Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetSelections/Scripts/TargetGroupIterator.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Scripts/TargetBehaviors/OnLookAtShowHoverFeedback.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Scripts/Targeting/DwellSelection.cs
Assets/MRTK/SDK/Experimental/NonNativeKeyboard/Scripts/NonNativeKeyboard.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/TapToPlace.cs
Assets/MRTK/Services/SceneSystem/MixedRealitySceneSystem.cs

1. Update to use the null coalescing expression `??` when Unity objects aren't involved
1. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0029-ide0030
1. Simplify conditional checks when explicit `true` and `false` are used
1. For example, `if (foo != null ? foo.IsValid : false)` can just be `if (foo != null && foo.IsValid)`
1. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0075
1. Use conditional delegate calls instead of explicit null checks
1. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide1005

Code style pass for null conditions

---

Assets/MRTK/Core/Definitions/SpatialAwareness/SpatialAwarenessPlanarObject.cs

The `name` parameter in `CreateSpatialObject` was previously unused.
This change aligns with the mesh observer, which uses the name to name the GameObject
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/d0884451fcc2516f769f416863893b0387a1facc/Assets/MRTK/Core/Definitions/SpatialAwareness/SpatialAwarenessMeshObject.cs#L51

Use unused param in SpatialAwarenessPlanarObject

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/SystemKeyboardExample.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/KeyboardInputFieldBase.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKTMPInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKTMPInputField.cs.meta
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKUGUIInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKUGUIInputField.cs.meta
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboardBase.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/Prefabs/MRKeyboardInputField_TMP.prefab
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/Prefabs/MRKeyboardInputField_UGUI.prefab
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/TMP_KeyboardInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/UI_KeyboardInputField.cs
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUI.prefab
Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs

This PR addresses a few keyboard related bugs across Unity 208.4/2019.4, Unity UI input field, TMP input field and the MixedRealityKeyboard class. Some of the bugs being addressed have been filed as issues (see the Changes section), but for this PR all combinations of Unity versions and keyboard invocation methods have been tested and in each combination the state of keyboard is improved to the point where further improvement are constrained by external issues (e.g. Unity side bug). Please see #9056 for the aimed state of native keyboard after merging this PR.
This PR also adds a `DisableUIInteractionWhenTyping` property to MixedRealityKeyboardBase so that the user will be distracted less often due to inadvertent interactions with other UI elements. Note this property is not available to …

Various keyboard improvements & Chinese, Japanese, Korean input fix

---

Assets/MRTK/Core/Extensions/LayerExtensions.cs
Assets/MRTK/Core/Inspectors/Utilities/Lines/DataProviders/SplineDataProviderInspector.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedControllerDataProvider.cs
Assets/MRTK/Core/Utilities/Lines/DataProviders/BezierDataProvider.cs
Assets/MRTK/Core/Utilities/Lines/DataProviders/BezierInertia.cs
Assets/MRTK/Core/Utilities/Lines/DataProviders/SplineDataProvider.cs
Assets/MRTK/Core/Utilities/Physics/Distorters/DistorterBulge.cs
Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/MoveObjByEyeGaze.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Scripts/TargetBehaviors/OnLookAtRotateByEyeGaze.cs
Assets/MRTK/SDK/Experimental/Elastic/Scripts/QuaternionElasticSystem.cs
Assets/MRTK/SDK/Features/UX/Scripts/Tooltips/ToolTipBackgroundBlob.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/Orbital.cs
Assets/MRTK/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tools/MSBuild/Scripts/Utilities.cs

1. Updates to prefer syntax like `foo += 1` instead of `foo = foo + 1`.
1. https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0054-ide0074

Code style pass for compound assignment

---

Assets/MRTK/Tools/MSBuild/MSBuildMRTKTemplates/SDKProjectTemplate.csproj.template
Assets/MRTK/Tools/MSBuild/Scripts/CSProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/Utilities.cs
NuGet/BuildSource.proj

Fix issues preventing MSBuild from working in Unity 2019. Some of the changes are specific to the doc generation task.

Fix MSBuild in Unity 2019 for docs

---

Assets/MRTK/Core/Utilities/CameraCache.cs

There is no option to set cached maincamera externally.
Scenario where there are multiple cameras in the scene and they interchange role as main camera when needed. At the moment there is no option to set them manually. Giving an option to set them would be nice.
- Fixes: # .
- Manually update the cached main camera
>
>
> As a reviewer, it is …

Manually update cached main camera

---

Assets/MRTK/Tools/MSBuild/MSBuildMRTKTemplates/SDKProjectTemplate.csproj.template

Currently due to the way CI is set up the XML files are not produced causing the xcopy command to fail. This PR fixes the issue by suppressing the copy error on XML files.

Ignore xcopy error for xml files to resolve CI issue

---

Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs

BuildDeployWindow would produce an error when Windows 10 SDK was installed on any disk other than C:\.
This was due to a hard-coded path in the script.
This PR remedies that by checking the registry first to obtain the actual installation path.
- Fixes: #9146
- Install Windows 10 Sdk (10.0.18368) and other necessary tools on D: drive
- Try to build project with build window

Build Deploy Window: detect Windows 10 SDK installation path by checking registry fix #9146

---

Assets/MRTK/SDK/Features/UX/Prefabs/Sliders/PinchSlider.prefab

Made adjustments to the prefab to ensure that the slider would not get offset after being rotated.
This was done by readjusting the positions of the gameobjects in the hierarchy. 
- Fixes: #8856
>
>
> commands (substituting {PR_ID} with the ID of this pull …

Fixed the pinch slider prefab to not be offset when rotated in play mode

---

Documentation/Authors.md
scripts/ci/contributors.py
scripts/ci/mergetool.py

Adds a Python script for auto-generating our Authors.md file. I'm also going to create a GitHub Action or Azure Pipeline to auto-run this every so often.
Uses pygithub to grab the contributors list from the repo, then sorts alphabetically by name, if present, or login, if name isn't present. Writes out into the MarkDown file formatted according to our existing file.
Also, this PR updates the Authors.md file according to the output of this new script.

Update Authors.md and add Python script for auto-generating using pygithub

---

Assets/MRTK/Services/InputSystem/NearInteractionTouchableVolume.cs
Assets/MRTK/Tests/PlayModeTests/NearInteractionTouchableTests.cs

Adding a `NearInteractionTouchableVolume` at runtime outside the editor doesn't currently work, since the collider is only currently cached in `OnValidate`, which is only called inside the editor.
This PR adds an additional cache in `Awake` in case the collider is currently null, which it will be when added at runtime outside the editor.
I tried adding a test for this but, since the tests all run in the editor, I couldn't think of a way to make this scenario happen.
Also formatted the test script a bit. Removed an `#if false` and replaced it with `Assert.Ignore()`, which is more visible that we have a disabled test. The test still needs fixing (there's a large comment above the test with more specifics).
- Fixes: #9143

Add additional caching of the collider at runtime in NearInteractionTouchableVolume

---

Assets/MRTK/SDK/Editor/Inspectors/UX/ObjectManipulator/ObjectManipulatorInspector.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs

Added a Near Interaction Support foldout to the Object Manipulator inspector to indicate the need for the NearInteractionGrabbable component for enabling near interaction support. 
Also added error message to ObjectManipulator if AllowFarManipulation is false and a NearInteractionGrabbable is not attached. 
- Fixes: #8083

Add Near Interaction Support foldout to ObjectManipulator inspector

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/Definitions/ProjectionOverride.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityUtilities.cs

Create internal access to non-DotNetWinRT HolographicFrame, even when DotNetWinRT is installed. This prevents a build issue when DotNetWinRT is installed, as not all types or methods needed for reading mode are yet defined there.
- Fixes: https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=16589&view=logs&j=ae5f814d-d003-5afd-2125-fa0189ea8658&t=83fc26c9-1bf2-50a8-274a-0ed525137015&l=3509

Create internal access to non-DotNetWinRT HolographicFrame

---

Assets/MRTK/Core/Definitions/SpatialAwareness/MixedRealitySpatialAwarenessMeshObserverProfile.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealitySpatialAwarenessMeshObserverProfileInspector.cs
Assets/MRTK/Core/Providers/BaseSpatialMeshObserver.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

Adding a component to the runtime spatial mesh is currently only achievable via script:
```
CoreServices.SpatialAwarenessSystem.SpatialAwarenessObjectParent.AddComponent<>()
```
This PR adds a field in the Spatial Observer Profile that enables users to add componets to a prefab in editor, which will then be appended to the runtime spatial awareness hierarchy. 
Default Runtime Spatial Awareness Hierarchy:
```
Spatial Awareness System 
Windows Mixed Reality Spatial Mesh Observer
Spatial Mesh - ID
Spatial Mesh - ID
...
```
Runtime Spatial Awareness Hierarchy with new prefab:
```
Spatial Awareness System 
Runtime Spatial Mesh Prefab
Windows Mixed Reality Spatial Mesh Observer
Spatial Mesh - ID
Spatial Mesh - ID
...
```
The motivation for this change is to enable an easier path for configuring …

Add Runtime Spatial Mesh Prefab field to the Windows Mixed Reality Spatial Mesh Observer Profile

---

Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

Adds a test for the changes in #9045 which involves setting a new visual configuration scriptable object during runtime. 
- Fixes: #9099

Add Set Visual Configuration test to Bounds Control Tests

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs

Fixes several issues where the button config helper was not clear with whether the materials on objects were derived from the current icon sets. In addition, added warnings for when certain kinds of iconsets were not loaded, and fixed issues where the icon sets would not load properly in the editor, while also adding the option for users to automatically refresh the sprite icons view
- Fixes: #9142, #9061

Improved button config helper Quality of Life.

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/ShellHandRayPointer.cs

This enables Select to be performed with one button (Thumb stick/Touchpad) and dragging with another (e.g. Trigger).
- pointer controller enhancements.

Decouple dragging events from Select action. 

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

This method doesn't exist unless `SCENE_UNDERSTANDING_PRESENT` is true.
- Fixes: https://microsoft.visualstudio.com/Analog/_build/results?buildId=31113603&view=logs&j=ae5f814d-d003-5afd-2125-fa0189ea8658&t=b9749889-d1f2-55ee-d51f-1633d691309c&l=2778

Update #define to include SCENE_UNDERSTANDING_PRESENT

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityEditorSettings.cs
Assets/MRTK/Core/Utilities/Editor/ScriptedImporterAssetReimporter.cs
Documentation/Tools/OptimizeWindow.md

This change fixes #7897 by adding "Please note: The Mixed Reality Toolkit Tools package is required to use the Optimize Window." to the debug log messages related to the optimize window.
It also changes the warning about no spatializer to a simple message and fixes: #7949

add note of tools package requirement for optimize window

---

Assets/MRTK/Examples/Common/Scripts/ColorChanger.cs

A single function add to a sample class.
It has an increment function but lacks a decrement function.
Fixes #9202 
I do not think this needs anything more than visual verification. I tested it locally and it works
The only 'change' is this line as a way to 'decrement and loop when below zero'
cur = (cur - 1 + mats.Length) % mats.Length;
If there are 5 items in mats:
Cur starts at 4:
4 - 1 + 5= 8 % 5 become 3 (a normal decrement operation)
Cur starts at 0
0 - 1 + 5 % 5 becomes 4 (the last index of the array)

Added decrement function to ColorChanger

---

pipelines/pr-2019.yaml
pipelines/pr.yaml
pipelines/templates/ci-common.yml
pipelines/templates/common.yml
pipelines/templates/tasks/githubchanges.yml
pipelines/templates/validation.yml
scripts/ci/githubchanges.ps1

This allows these tasks to run on a the generic pool of machines, instead of taking up time on the special hosted machines with Unity installed.
This PR also fixes the issue with scoped code validation we've been having. Turns out, ADO changed the name of the branch they check out during PR validation. Instead of relying on a branch name, I updated the script to just use whatever branch is checked out (which will be the PR branch).
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8975

Refactor non-Unity validation out into new template

---

Assets/MRTK/Examples/Common/Scripts/DwellProfileWithDecay.cs
Assets/MRTK/Examples/Experimental/Dwell/ButtonDwellProfile.asset
Assets/MRTK/Examples/Experimental/Dwell/ButtonDwellProfile.asset.meta
Assets/MRTK/Examples/Experimental/Dwell/CustomDwellHandler.cs
Assets/MRTK/Examples/Experimental/Dwell/DwellExample.unity
Assets/MRTK/Examples/Experimental/Dwell/DwellProfileWithDecay.asset
Assets/MRTK/Examples/Experimental/Dwell/Editor/DwellProfileWithDecayInspector.cs
Assets/MRTK/Examples/Experimental/Dwell/InstantDwellProfile.asset
Assets/MRTK/Examples/Experimental/Dwell/ToggleDwellProfile.asset
Assets/MRTK/SDK/Experimental/Features/Dwell/DwellHandler.cs

This PR fixes the following bugs in the dwell feature/example:
- No profile error when entering play mode in editor
- The dwell timer does not stop after the object is no longer being focused on
- For the decay dwell example, the focus time was not calculated correctly after user looking away and then back at the object due to the "decayed time" was not accounted for
- Fixes: #9168

Various Dwell related bug fixes

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealitySpatialAwarenessSystemProfileInspector.cs
Assets/MRTK/Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxExampleTest.cs
Assets/MRTK/Examples/Demos/UX/BoundsControl/Scripts/BoundsControlRuntimeExample.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/FeaturesPanelVisuals.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/ToggleHandVisualisation.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

This change cleans up null propagation and null coalescence usages with Unity objects. 
Recommend taking for 2.6 as it should resolve potential race condition bugs based on when Unity objects actually get set to null.

remove null propagation with unity object

---

Assets/MRTK/Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs

Add condition to bypass an exception in the Asset Retargeter.  Interactive Element is only supported in Unity 2019.

Update Asset Retargeter to bypass Interactive Element

---

pipelines/templates/assetretargeting.yml
pipelines/templates/generateprojects.yml
pipelines/templates/tasks/unitybuild.yml
pipelines/templates/tests.yml

Uses https://github.com/microsoft/unitysetup.powershell for finding and running Unity instances, instead of searching the file tree manually.
Build errors are caught like https://dev.azure.com/aipmr/MixedRealityToolkit-Unity-CI/_build/results?buildId=16847&view=logs&j=ac44c712-4e8b-53f6-2852-2edd3c73b43a&t=ee209e73-1529-516b-c222-0767be9b653d
- Fixes: #7554

Update pipelines to use unitysetup.powershell

---

pipelines/ci-daily.yml
pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci.yaml
pipelines/pr.yaml
pipelines/templates/ci-common.yml
pipelines/templates/validation.yml

Follow-up to #9242, to use the new non-Unity validation template on regular windows VMs in CI as well as PR validation. This should help speed up CI a bit, as global code validation takes ~10 minutes and can now happen in parallel.

Update CI to run non-Unity validation on "regular" windows-2019 VMs

---

pipelines/mergetool.yml

Now that the interactive element feature branch has been merged in, we no longer need to update it from dev. Luckily, we newly have a need to keep the dev branch in-sync with the stabilization branch! This PR updates the pipeline to monitor that instead.

Update mergetool to monitor merges from stabilization to dev

---

Assets/MRTK/StandardAssets/License.txt
Assets/MRTK/StandardAssets/License.txt.meta
pipelines/ci-daily.yml
pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml
pipelines/ci.yaml
pipelines/templates/ci-common.yml
pipelines/templates/common-Unity2019.yml
pipelines/templates/common.yml
pipelines/templates/end.yml
pipelines/templates/tasks/signing.yml
pipelines/templates/tasks/versionmetadata.yml
scripts/packaging/versionmetadata.ps1

* Adds StandardAssets to the version script, as it was missing
* Adds a License.txt file to the StandardAssets to match the other top level MRTK folder
* Updates the versioning template to use the global MRTK version by default

Update versioning step pre-packaging in pipeline

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs

Previously, only controllers with the spatial grip inputType could rotate object manipulators via 1-handed or 2-handed interactions. This PR allows for all kinds of controllers which raise source pose events to manipulate those objects.
Old behavior on Quest: https://streamable.com/07fvq0
New behavior on Quest: https://streamable.com/5x912h
- Fixes: #9109

Allow controllers to rotate object manipulators

---

pipelines/ci-packaging-dontpublish.yml
pipelines/ci-packaging-internal.yml
pipelines/ci-packaging.yml
pipelines/templates/ci-common.yml

Move NuGet steps out of general CI, since we've deprecated this distribution method. We no longer need to spend this time spinning on the public VMs (which also run PR validation).

Move NuGet steps out of general CI

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

This optional dependency was added in #9225, so we need to tell the project generator to ignore it. 
- Fixes: https://microsoft.visualstudio.com/Analog/_build/results?buildId=31350849&view=logs&j=00a17365-9fc3-5f6d-b77f-ab9491956439&t=0ca905f7-f9e2-5349-86e3-35e9a0856f8c

Add Microsoft.MixedReality.Toolkit.PlaneFinding to exclusion list

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/Slate.prefab

- Updated text label 'BoundingBox.cs to BoundsControl.cs'. (we no longer use BoundingBox.cs in the examples)
- Updated ObjectManipulator option in the Slate prefab and cheese object: Checked Near Smoothing. (it was unchecked, made the movement jitter)

[2.6.0 Stabilization] HandInteractionExample scene updates

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs

`FrameTime` was graduated from the Preview namespace, so this change brings us into compliance with the obsolete warning.
- Fixes: #9289

Update to be compatible with multiple OpenXR package versions

---

Assets/MRTK/Examples/Demos/UX/Dialog/Scripts/DialogExampleController.cs

4 Tooltips had typos about the placement for near/far interaction.
- Fixes: Adjusted tooltips to correspond to values of variables used in code.
No functional changes are made, but the near / far adjustment can be verified by checking the value of `bool placeForNearInteraction` in the parameters of `Dialog.Open(..., bool placeForNearInteraction)`, where false corresponds to far, and true to near. The title tooltips already correctly reflect this as well, so this is a very minor change.

Typo fixes in tooltips

---

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/HPMotionController.cs

When testing 2.6 stabilization, I realized I accidentally removed a namespace in https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9106.

Fix XR SDK with HP motion controller

---

Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs

There was a backing field, but it was never actually set. This now prevents the property from calling `CoreServices.GetInputSystemDataProvider` every time.

Actually cache handJointService in SolverHandler

---

Assets/MRTK/Extensions/HandPhysicsService/HandPhysicsService.cs
Assets/MRTK/Extensions/HandPhysicsService/MRTK.HandPhysics.asmdef
Assets/MRTK/Extensions/HandPhysicsService/Profiles/HandPhysicsMixedRealityRegisteredServiceProvidersProfile.asset

This change addresses #9322 by enabling the hand physics extension assembly to load on any target platform.  when originally written, the only mrtk supported platform with hand support was HoloLens 2. Since then, Leap Motion and Quest have been added.

enable handphysics asm on any platform

---

Assets/MRTK/Core/Services/BaseService.cs

Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8906, which is new for 2.6, this updates the visibility of the backing fields and setters. The enabled and initialized state should be visible outside the class, but doesn't need to be set from outside the class.

Update backing fields to private and setters to protected in BaseService

---

Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/MRTK.WMR.XRSDK.asmdef
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/XRSDK/MRTK.XRSDK.asmdef
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

Reworks some of the contributions from #9249 to support more cases and rely more on the new (in 2.6) service state tracking.
Now, we ensure `IsEnabled` is set to false if we aren't the provider for the active loader. Then from there, any `Update`s are blocked on that bool. This required a rework of the `#if`s in some of the code, to scope them down a bit and expose more non-platform-specific backing code, because we don't want the `IsEnabled` flag to accidentally be enabled just because the expected package isn't installed.
- Fixes: Build issue with WMR XR SDK due to reference to internal WindowsMRLoader class

Update XR SDK loader checking in data providers

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/NearMenuExamples.unity
Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

[Stabilization 2.6.0] NearMenuExamples: 1m auto follow example toggle pin state is not updated when auto follow is triggered.
Fix: Added 'Auto Follow Trigger' event to the FollwMeToggle script. Toggle Pin button using this event properly.
https://user-images.githubusercontent.com/13754172/108447107-26c09600-7214-11eb-9fcc-becaf748244d.mp4
https://user-images.githubusercontent.com/13754172/108447172-46f05500-7214-11eb-9087-ad94436d6621.mp4
- Fixes: #9335

[Stabilization 2.6.0] NearMenuExamples: 1m auto follow example toggle pin state is not updated when auto follow is triggered.

---

Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUI.prefab

[Stabilization 2.6.0] HandInteractionExamples scene: Unity UI Slate text filed : text wrapping is not supported but input field is vertically big.
- Fixes: #9331

[Stabilization 2.6.0] HandInteractionExamples scene: Unity UI Slate text filed : text wrapping is not supported but input field is vertically big.

---

Assets/MRTK/Examples/Demos/ReadingMode/Scenes/ReadingModeDemo.unity
Assets/MRTK/Examples/StandardAssets/Prefabs/SceneDescriptionPanel.prefab
ProjectSettings/ProjectVersion.txt

This PR replaces the serialized script references with their 2018 counterparts. Unity can update them going from 2018 -> 2019 but doesn't downgrade them going in the other direction.
Also, removed some unneeded graphics raycasting components from the scene description panel prefab, as they can have perf implications and aren't needed on a text-only canvas.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9330

Fix reading mode demo in Unity 2018

---

Assets/MRTK/Core/Inspectors/MixedRealityStandardShaderGUI.cs

This is a small fix to an issue found by @cre8ivepark where `Enable Stencil Testing` and `Ignore Z Scale` would be disabled in the UI when `Enable GPU Instancing` was also disabled in the UI. These should be mutually exclusive. 
The inspector should now look like this:
>
>

Re-enabling shader inspector for later properties.

---

Assets/MRTK/Core/Utilities/WindowsApiChecker.cs
Assets/MRTK/Services/InputSystem/InputSystemGlobalListener.cs

The code looks a bit cleaner when we don't need to have `#pragma warning disable` all over, and I think adding additional `Obsolete` tags where necessary is a more visible and actionable approach.

Clean up extra uses of #pragma warning disable

---

Assets/MRTK/SDK/Features/UX/Prefabs/Slate/Slate.prefab
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/TranslationHandles.cs

This PR fixes the issue of the translation handles of bounds control having wrong rotation and the issue of some slates cannot be scaled with near interaction.
- Fixes: #9334 and #9346.
Please see the issues above for steps to verify these fixes.

Fix two bounds control related issues

---

Assets/MRTK/SDK/Features/UX/Materials/BoundingBoxSlate.mat
Assets/MRTK/SDK/Features/UX/Materials/BoundingBoxSlate.mat.meta
Assets/MRTK/SDK/Features/UX/Materials/BoundingBoxSlateGrabbed.mat
Assets/MRTK/SDK/Features/UX/Materials/BoundingBoxSlateGrabbed.mat.meta
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/Slate.prefab

Part of issue #9334 
Slate's Bounding Box wire is not visible. 
Based on the shader fix #9349 , added BoundingBoxSlate.mat with 'ignore z-scale' enabled. Assigned to the Slate prefab.
##Before & After

[Stabilization 2.6.0] Fix Bounding Box material for Slate prefab

---

Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetPositioning/Scripts/MoveObjByEyeGaze.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

Previously, the eye gaze controls were broken and would not let the users pinch to manipulate objects. This PR fixes this by removing the hard-coded dependency on controller names, and it also fixes a bug introduced with pointer naming
old naming:
new naming:
- Fixes: #9336
>
>
> As a reviewer, it is possible to check out this change locally by …

Fix for eye gaze pinch controls and fix pointer naming bug

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/Slate.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUI.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUIHoloLens2Buttons.prefab

In the HandInteractionExamples scene:
1. UGUI Slate example's UGUI Input Field is squashed and cannot press, cannot invoke keyboard.
- Deleted the UGUI slate example in the scene and replaced it with the prefab
2. UGUI HL2 button example slate's Bounding Box rotation handle behavior shows an unexpected pivot movement.
3. Slate's side rotation handles are hard to grab. It feels the grabbable area is very limited and has offset from the actual handle visual.
- Fixes: #9359
https://user-images.githubusercontent.com/13754172/108907991-ac0ec680-75d7-11eb-952d-36d26c0f6ef7.mp4
https://user-images.githubusercontent.com/13754172/108908891-b54c6300-75d8-11eb-96b5-eec3575f4ea6.mp4

[Stabilization 2.6.0] Slate example issues

---

Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs

This `#if` block was missing a namespace
- Fixes: #9372

Debug -> UnityEngine.Debug in OculusXRSDKDeviceManager

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

This PR fixes the currently incorrect calculation of the center of bounds in world space.
- Fixes: #9366

Fix BoundsControl incorrectly calculates world space center of bounds

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/BaseWindowsMixedRealityCameraSettings.cs

This method was checking the wrong field for null to initialize `ProjectionOverride`

Fix wrong field reference in BaseWindowsMixedRealityCameraSettings

---

Assets/MRTK/Examples/Demos/Input/Scenes/InputActions/InputActions.MixedRealityInputSimulationProfile.asset
Assets/MRTK/Examples/Demos/Input/Scenes/PrimaryPointer/PrimaryPointerHandlerExample.cs

Adds a workaround for the issue described in **#9367**. Because of how the gaze cursor is handled in relation to the GGVPointer and the GazeProvider, there is no straightforward catchall solution for this at the moment, so we some implementation specific workaround code for now. We're hoping to have a more catch-all fix as we work towards separating out the co-dependencies between cursors and pointers in the current MRTK.
This PR also fixes issue **#9369** in the InputActions scene but fixing the InputAction profile
- Fixes: #9367, #9369

Primary Cursor and InputAction's Profile fixes

---

Assets/MRTK/Tools/MSBuild/MSBuildMRTKTemplates/WSA.Player.Template.props.template
NuGet/BuildSource.proj
scripts/packaging/createnugetpackages.ps1

This change allows a user to pass an arbitrary VS path instead of it being hardcoded.
Also updates to use Visual Studio 2019.
@MaxWang-MS, do you think this will affect the docs binary generation scripts?
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/6996

Update build scripts to allow for arbitrary VS versions

---

Assets/MRTK/Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs
Assets/MRTK/Tools/MSBuild/Scripts/Utilities.cs
Assets/MRTK/Tools/MSBuild/mrtk_guid_remapping_dictionary.txt
Assets/MRTK/Tools/MSBuild/mrtk_guid_remapping_dictionary.txt.meta
Assets/MRTK/Tools/MixedReality.Toolkit.Tools.nuspec
pipelines/templates/tasks/assetretargeting.yml
pipelines/templates/tasks/publish-nuget.yml
pipelines/templates/tasks/publish-upm.yml

This change writes out a txt file during our pipelines to make the mappings between the NuGet GUIDs and the script GUIDs accessible. It also adds a pop-up window for choosing a dictionary file, if multiple exist, and applying it to the codebase:
Also:
1. Updates the remapping to only look for `UnityEngine.Object`s, since prefabs retain their GUIDs across distributions.
2. Clean-up and formatting

Adds groundwork for migrating projects off NuGet to UPM/.unitypackages

---

Assets/MRTK/Examples/Demos/ReadingMode/Scripts/ReadingModeSceneBehavior.cs

Previously, XRSettings was trying to change some values when it didn't actually have an underlying XR session. This change makes it so we only try to change the scale if an XRDevice is actually present.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9340, #9386

Only update renderViewPortScale if an XR device is present

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs

Adds a check so controllers which are classified as articulated hands will not be named HP Motion Controllers
- Fixes: #9403

Fixed articulated hands being classified as HP Motion Controllers

---

Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

When XR is disabled, `XRGeneralSettings.Instance.Manager.activeLoader` is null, so we were causing a null ref in the WMR provider which cascaded into the Oculus provider not running through its init fully.
Fixing this null check prevented the reported errors.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9392

Add null check for XR not initialized

---

Assets/MRTK/Tools/MSBuild/Scripts/AssetScriptReferenceRetargeter.cs

Fix the CI not handling the 2019 only scene understanding problem.

Add Scene Understanding to the Asset Retargeter ignore list

---

Assets/MRTK/Examples/Demos/ReadingMode/Scripts/ReadingModeSceneBehavior.cs

`XRSubsystemHelpers.DisplaySubsystem.scaleOfAllViewports` doesn't appear to do anything (yet?). This change aligns the implementation to `XRSettings.renderViewportScale` across both legacy and XR SDK while the other method is investigated.
Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9398

Update legacy and XR SDK implementation for renderViewportScaleSlider

---

Documentation/GettingStartedWithMRTKAndXRSDK.md
Documentation/GettingStartedWithTheMRTK.md
Documentation/Input/HandTracking.md
Documentation/Input/Pointers.md
Documentation/Installation.md
Documentation/README_Button.md
Documentation/README_MRTKStandardShader.md
Documentation/README_Solver.md
Documentation/WelcomeToMRTK.md
Documentation/usingupm.md
README.md

Added redirect URLs for popular docs pages.
- General landing pages link to the new "Welcome to MRTK" page.
- Popular conceptual docs link to their corresponding URL.
- URLs won't work until new docs pages go live
- Fixes: # .

Docs Migration redirect URLs

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs

On UWP, the type is now OpenXRLoaderNoPreInit. This line is updated to refer to the shared base class.

Fix OpenXR on UWP

---

Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

Clipping primitive now unregisters its event upon deletion, which fixes a series of null reference exceptions that would get raised otherwise.
Fixes #9450

Clipping primitive now removes OnPreRender event upon deletion

---

Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs

Leap Articulated Hands now raise the "SourcePoseChanged" Event, allowing them to work with Object Manipulator Rotation again.
- Fixes: #9474
@CDiaz-MS when you get a chance can you confirm the fix?

Fixed Object Manipulator Rotation for Leap Hands 

---

Assets/MRTK/Core/Utilities/StandardShader/ClippingPrimitive.cs
Assets/MRTK/Examples/Demos/UX/Dialog/Scripts/DialogExampleController.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

Cherry-picks
* Fixes OpenXR not working on UWP https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9430
* Fixes clipping primitive not properly cleaning up and causing `MissingReferenceException`s https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9449
* Fixes some incorrect, confusing tooltips for the dialog component #9297
- Fixes: #9450

2.6.1 cherrypicks

---

Assets/MRTK/SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorObjectDisplay.cs
Assets/MRTK/SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorOrbsRotator.cs
Assets/MRTK/Tests/PlayModeTests/LoadingIndicatorTests.cs

If a UI task is awaiting on a progress indicator to close (e.g. to perform an animation) and the object is hidden (disabled/deactivated), the CloseAsync() method will never return, causing the progress indicator to be forever stuck.
Async/awaitable logic should not depend on the animations while the object is visible, since the object might be hidden by some other piece of code before the animation completes, blocking the async operation forever.
This change makes the progress indicators short circuit their waiting logic if the underlying object is disabled or deactivated, not delaying any processing due to invisible animations.
- Fixes: #9462 
See #9462 for repro steps. Verified on Editor.

Ensure async operations on progress indicators don't wait on animations if the object is hidden

---

Assets/MRTK/Core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
Assets/MRTK/Services/InputSystem/GazeProvider.cs

Setting a type reference property to (None) always results in undesired behavior or unpleasant experience for developers. This PR removes this option, ensuring that the type reference property is always set to something.
This PR also fixes a redundant interface declaration with the GazeProvider class.
old:
new:
In the case where there are no types which implement the interface we are looking for (This is a very rare edge case and we shouldn't be hitting this in the first place)
Part of the work done for #8910

Removed the ability for users to set a TypeReferenceProperty to None

---

Packages/manifest.json

When building for Oculus Quest, you will encounter gradle build errors and be unable to deploy due to incompatible gradle versions, ARCore requires minimum 5.6.4 while the Unity android defaults are 5.1.1
https://stackoverflow.com/questions/64381387/cant-compile-unity-project-with-arcore-sdk-problem-with-gradle
Since we don't use ARCore or ARKit directly in MRTK, this PR removes our dependency on those 2 packages to make the Oculus Quest experience less painful, and to allow our users to not have to discover this quirk themselves.

Removed arkit and arcore due to incompatible gradle versions

---

Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

Previously users would get a NullPointerException followed up other non-crashing errors when running in editor while targetting a platform which uses XRSDK. This fix prevents the propogation of errors in editor
- Fixes: #9469

Added checks for null for XRGeneralSettings.Instance and XRGeneralSettings.Instance.Manager

---

Assets/MRTK/Core/Definitions/Utilities/MixedRealityTransform.cs

Adds the scale to `ToString()` to properly print the full state of the transform.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9536

Add scale to MRTransform ToString()

---

Assets/MRTK/Tools/MSBuild/Scripts/CSProjectInfo.cs
Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

Currently we maintain a two sets that contain all the packages that we are not including when generating the binaries for API reference docs. Some of those packages are MRTK ones that only need to be excluded because they apply to specific versions of Unity. The rest are excluded because they are external-to-MRTK packages and we do not have the source. Right now both sets of packages are being tracked and we have to edit the sets once a new external reference is added into an asmdef file. This PR removes the need of tracking the second kind of packages and consolidates the two sets into one so that we do not have to modify the set as often.

Change the handling of missing assemblies in build script

---

Assets/MRTK/Core/Definitions/Devices/MixedRealityControllerVisualizationSetting.cs
Assets/MRTK/Core/Providers/BaseController.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/Extensions/WindowsExtensions.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/MRTK.WMR.Shared.asmdef
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityControllerModelProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityControllerModelProvider.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/HPMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/MRTK.WMR.asmdef
Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealityXRSDKControllerVisualizationProfile.asset

Refactors out a WindowsMixedRealityControllerModelProvider to call into the WinRT API and load the corresponding glTF model across both legacy XR and XR SDK.
We also probably need a follow-up to improve the materials we use when loading the models.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8971

Add support for motion controller models at runtime in WMR/XRSDK

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs

Mixed Reality OpenXR should be shipping 0.2.0 today (3/24). This PR puts us into compatibility with it, while maintaining previous compatibility.
Changes:
1. Several hand-based APIs came out of Preview, so their namespaces changed
2. `HandTracker` changed to a global static model, with one existing per-hand
3. Fixed incorrectly named profiler markers

Update to Mixed Reality OpenXR package 0.2.0

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs

The pinch strength values were inverted, making the pinch bool flicker on oculus. This fixes the values so that it's harder to exit pinch once the gesture is raised
- Fixes: #9544

Fixed bug where the pinch strength defaults were inverted

---

Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs

Using the `HandMeshTracker` class added in the 0.2.0 Mixed Reality OpenXR package release, this PR adds support via the MRTK's APIs.
Also does some minor rework of what's stored in the hand visualizer between events to try to help perf (no need to store the full array when we only need the count).

Add support for hand mesh on OpenXR

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs

Previously, the teleport pointer's raycast layer mask targets were the global defaults. Now, Valid and Invalid Layers will be raycast against, and all other layers will be ignored.
- Fixes: #9552

Teleport pointer controls the layers masks it raycasts against

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpBuildInfo.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs
Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs

This PR adds the option to specify a path to nuget.exe and use that to perform package restore instead of using msbuild (the default option).

Adding the option to use nuget.exe for restore in build tools

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs

Wrap namespace in #if MSFT_OPENXR_0_2_0_OR_NEWER
- Fixes: build break in 2020 without OpenXR installed

Wrap namespace in #if MSFT_OPENXR_0_2_0_OR_NEWER

---

Assets/MRTK/Core/Definitions/Devices/MixedRealityControllerVisualizationProfile.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MRTK/Core/Providers/BaseController.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/OpenVR/GenericOpenVRController.cs

Cleaned up some of the confusing controller visualization code and added QoL improvements to feedback given by the profile.
Oculus XRSDK Touch controllers can now opt to not use MRTK for controller visualization, since the oculus integration package has their own standalone visualization (some of our users were confused and complaining that they could not get rid of the default gizmos)
Fixes #9590

Refactored Controller visualization code, Oculus Touch uses their own standalone visualizer

---

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKMotionController.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9589 deprecated `GetUseDefaultModelsOverride`, but one of the classes is still calling it. Updated to the new `GetUsePlatformModelsOverride` instead.
This was preventing building in Unity 2019+

Update to use non-obsolete method in WMR controller

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealitySpatialAwarenessMeshObserverProfileInspector.cs
Assets/MRTK/Core/Interfaces/SpatialAwareness/Observers/Experimental/IMixedRealityOnDemandObserver.cs
Assets/MRTK/Core/Interfaces/SpatialAwareness/Observers/Experimental/IMixedRealitySceneUnderstandingObserver.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationHelpGuide.cs
Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserver.cs
Assets/MRTK/Core/Providers/ObjectMeshObserver/SpatialObjectMeshObserverProfileInspector.cs
Assets/MRTK/Examples/Demos/ScrollingObjectCollection/Scripts/ScrollablePagination.cs
Assets/MRTK/Examples/Demos/SpatialAwareness/Scripts/ShowPlaneFindingInstructions.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/Editor/SceneUnderstandingObserverProfileInspector.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/SceneUnderstandingObserverProfile.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/SDK/Experimental/ColorPicker/ColorPicker.cs
Assets/MRTK/SDK/Experimental/SpatialAwareness/SurfaceMeshesToPlanes.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs
Assets/MRTK/Tests/EditModeTests/Core/Extensions/BoundsExtensionsTests.cs
Assets/MRTK/Tests/PlayModeTests/ChangeActiveProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/ScrollViewTests.cs

Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8102. Looks like a few more snuck in with the old style.

Standardize license headers

---

Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/TapToPlaceInspector.cs

Fix issue #9645
TopToPlaceInspector references properties which don't exists in TapToPlace. This causes an error in the console and the Magnetic Surface inspector settings will not be rendered as described in #9645.
- Fixes: Orphaned properties in TapToPlaceInspector

Remove orphaned properties from TapToPlaceInspector

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs

Adds support for the 4.6.0, 4.7.0, 4.7.1 [Leap Motion Unity Modules](https://github.com/leapmotion/UnityModules/releases). The latest version MRTK currently supports is 4.5.1. 
[Leap Modules Version 4.6.0](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.6.0) 
[Leap Modules Version 4.7.0](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.7.0) 
[Leap Modules Version 4.7.1](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.7.1)
An item to note is that Leap has not updated the Version.txt since 4.5.1: https://github.com/leapmotion/UnityModules/blob/release-4.7.0/Assets/Plugins/LeapMotion/Core/Version.txt. The version.txt for 4.6.0, 4.7.0, and 4.7.1 has 4.5.1 listed. 
- Fixes: #8928

Leap Motion Unity Modules Support for version 4.6.0, 4.7.0 and 4.7.1 

---

Assets/MRTK/Core/Definitions/MixedRealityInputDataProviderConfiguration.cs
Assets/MRTK/Core/Definitions/MixedRealityServiceConfiguration.cs
Assets/MRTK/Core/Inspectors/Profiles/BaseMixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/DataProviderAccessServiceInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityEyeTrackingProfileInspector.cs
Assets/MRTK/Core/Providers/InputSimulation/Editor/MixedRealityInputSimulationProfileInspector.cs
Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionDeviceManagerProfileInspector.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs

`DeviceManagerProfile` has the exact same type as the `Profile` a couple lines higher, so it can be safely deprecated in favor of the inherited property.
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/4f7a007c7dfadb725613667cef34470db8c7d038/Assets/MRTK/Core/Definitions/MixedRealityInputDataProviderConfiguration.cs#L42-L43

Deprecate `DeviceManagerProfile` in favor of inherited property

---

pipelines/docs-binaries.yml

Currently, the 2019 and 2020 docs binary generation steps `always()` try to publish artifacts, even if previous steps failed. This can get into a state like the linked pipeline below, where the checkout step failed initially, succeeded on a re-run, but can't publish binaries because the failed run published an empty artifact.
- Fixes: https://microsoft.visualstudio.com/Analog/_build/results?buildId=33400250&view=artifacts&pathAsName=false&type=publishedArtifacts

Only publish docs binaries if checkout and generation succeed

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs

The tag was referencing the previously deprecated (and where this was refactored from) `WindowsMixedRealityArticulatedHandDefinition` class. This PR updates it and uses `nameof` to help make it more robust to name changes.
Also adds a profiler marker to the OpenXRHandMeshProvider.

Fix profiler tag in WMRHandMeshProvider

---

Assets/MRTK/SDK/StandardAssets/Prefabs/UI Backplate.prefab
Assets/MRTK/SDK/StandardAssets/Prefabs/UI Backplate.prefab.meta

Adding UI Backplate prefab to align with [Figma Toolkit](https://docs.microsoft.com/en-us/windows/mixed-reality/design/figma-toolkit). Backplate is a common component used for creating UI layout. It is a Unity quad with Holographic backplate material. It can be resized without corner round distortion.
Examples of use in UI panels:

Adding UI Backplate prefab to align with Figma Toolkit

---

Assets/MRTK/Core/Utilities/Editor/ScriptUtilities.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GlbAssetImporter.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GltfAssetImporter.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/Importers/GltfEditorImporter.cs

This enables them to be turned off if they collide with other importers like TriLib.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9653

Wrap glTF scripted importers with !MRTK_GLTF_IMPORTER_OFF

---

Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs

When using voice commands to trigger an `Interactable` while `RequiresFocus` is `false`, the focus of the cursor would get stuck on the triggered `Interactable`. When airtapping on another `Interactable` the previous (voice-activated) `Interactable` would still be triggered.
- Fixes: the focus getting stuck on the voice-activated `Interactable` by resetting the focus to it's state before handling the interaction.

Fix: focus getting stuck on `Interactable` when `RequiresFocus` is `false`.

---

Assets/MRTK/Core/Utilities/CameraCache.cs

This change updates the warning message displayed when the CameraCache cannot determine which camera is the main.

improve camera cache warning message

---

Assets/MRTK/Providers/OpenVR/MRTK.OpenVR.asmdef
Assets/MRTK/Tests/EditModeTests/Core/Definitions/Devices/MixedRealityControllerMappingProfileTests.cs
Assets/MRTK/Tests/EditModeTests/InputSystem/ControllerMappingTests.cs
Assets/MRTK/Tests/EditModeTests/MRTK.EditModeTests.asmdef

Similar to how we've handled the legacy WMR assembly, we shouldn't try loading the legacy OpenVR assembly to make it clear that those types aren't compatible here.
Also updates the tests to account for these types missing in Unity 2020+.
- Part of #9419

Don't load legacy OpenVR assembly on Unity 2020

---

Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXREyeGazeDataProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/LoaderHelpers.cs
Assets/MRTK/Providers/XRSDK/LoaderHelpers.cs.meta
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

Slightly updates the existing pattern, refactors the methods out so other non-input providers can use them, and ensures all XR SDK providers across spatial and input check their loader before enabling.
- Part of #9419, follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9338

Ensure XR SDK providers only run on their specified loaders

---

Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs

Checks if the folder provided by `SOFTWARE\Microsoft\Windows Kits\Installed Roots` exists. If it doesn't, checks `SOFTWARE\WOW6432Node\Microsoft\Windows Kits\Installed Roots`. If that also doesn't exist, falls back to the default path.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9507

Add fallback reg key in case the default one doesn't work in BuildDeployWindow

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitInspector.cs

`MixedRealityToolkitInspector` was recreating the configuration profile's inspector in `OnInspectorGUI`, which happens...a lot. This lead to unexpected behavior in `OnEnable` for things that weren't expected to happen often.
This change makes it so we reuse the most recent editor unless the editor has gone null, or the profile is changed
- Part of #9419

Don't constantly recreate the base profile editor

---

Assets/MRTK/Core/Inspectors/Profiles/DataProviderAccessServiceInspector.cs
Assets/MRTK/Core/Utilities/Editor/Preferences/MixedRealityProjectPreferences.cs

Makes showing null data providers in the UI optional (doesn't apply to newly added providers which haven't yet been assigned a type).
This becomes important for filtering provider types in the UI, since filtering happens via the attribute (incoming in #9670). If the type isn't loadable, the attribute isn't loadable, and the type is unfiltered in the UI and can be confusing.
For debugging purposes, the checkbox in settings can be enabled to make all providers visible.
- Part of #9419

Add configurable UI filter for null providers

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubSceneSystemProfile.asset
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs
Assets/MRTK/SDK/Features/UX/Scripts/PulseShader/PulseShaderHandMeshHandler.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/FeaturesPanelVisuals.cs
Assets/MRTK/SDK/StandardAssets/Prefabs/ArticulatedHandMesh.prefab

* Reverts a couple changes in #9613 which made the hand mesh impossible to trigger in the HandInteractionExamples scene
* Reverts the material change on the hand mesh prefab back to the "always visible" material vs the pulse material
* Re-enables the hand feature toggle panel in the scene
* Update the scene system profile, which Unity keeps reserializing, to the checked-in state of the repo
* Fixes the obsolete `WindowsMixedRealityHandMeshProvider` to still function properly
* Minor syntax updates in `FeaturesPanelVisuals` and `PulseShaderHandMeshHandler` for clarity

Hand mesh and scene updates

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs

Removed references to poke pointer visuals and line renderers which were unused on the prefab. Move the visualization functions into the OnDrawGizmos() to retain some of the usability when debugging.
- Fixes: #9608

Fixed errors raised by the poke pointer regrading disabled and missing visuals.

---

Assets/MRTK/Core/Services/BaseEventSystem.cs

When I was running verbose logging for some testing, I noticed that some handler `ToString()` representations (mostly the input module) ended with some newlines for some reason. This change trims those out for better formatting.

Better format the handler type in the BaseEventSystem log

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs

This PR makes the build tool only use scenes specified by the sceneList or sceneListFile flags when the flags are present.
- Fixes #9677

Only use scenes specified in command line when flags are present

---

Assets/MRTK/Tools/RuntimeTools/Tools/InputFeatureUsageTool/InputFeatureUsageTool.unity
Assets/MRTK/Tools/RuntimeTools/Tools/InputFeatureUsageTool/ListInputFeatureUsages.cs
Assets/MRTK/Tools/RuntimeTools/Tools/MRTK.Tools.Runtime.asmdef

Updates the feature usage runtime tool to be more dynamic, spawning additional panels as needed instead of hardcoding to two panels. It resizes the panels vertically as needed to fit all usages. It arranges the panels using a GridObjectCollection in a cylinder around the origin.
It also updates to use the built-in `As<T>()` method for converting InputFeatureUsages to their actual type.

Update feature usage runtime tool scene

---

Assets/MRTK/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs

1. `appCapture.IsCapturingVideo` can be expensive, so instead of checking it every frame we now key off the event.
2. The camera's reported FoV changes while MRC is running, so we now cache the most recent FoV and use that instead while MRC is running
3. Increased the min distance for display to 0.5 instead of "near clipping plane + 0.25" so it's more predictable
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9560, fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9596

Fix some diagnostics panel bugs

---

Assets/MRTK/Core/Definitions/MixedRealityToolkitConfigurationProfile.cs
Assets/MRTK/Core/Services/BaseBoundarySystem.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/SceneContent/MixedRealitySceneContent.cs
Assets/MRTK/Core/Utilities/XRSettingsUtilities.cs
Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs
Assets/MRTK/SDK/Profiles/HoloLens2/DefaultHoloLens2ConfigurationProfile.asset
Assets/MRTK/Services/BoundarySystem/XR2018/MixedRealityBoundarySystem.cs
Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
Assets/MRTK/Tests/PlayModeTests/BaseEventSystemTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundingBoxTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs
Assets/MRTK/Tests/PlayModeTests/Experimental/ElasticTests.cs
Assets/MRTK/Tests/PlayModeTests/SpatialObserverTests.cs
scripts/test/run_playmode_tests.ps1

There were some quirks on legacy vs Windows XR Plugin vs OpenXR.
1. Non-legacy in the editor seemed to need to wait ~4 frames instead of 1 to align scene content. Defaulting to 5 to be safe
2. Boundary was broken in 2020, since it was looking specifically at the legacy type which is null in 2020 and returning that boundary was always disabled
3. Reworked BaseBoundarySystem a bit to use a built-in MRTK utility for detecting device presence, as well as allowing it to late-init in the editor since there were a few frames of the device not being "present" in OpenXR
4. Minor formatting (made some unshipped things private that didn't need to be public)

Update scene content alignment and boundary system

---

Assets/MRTK/Tests/PlayModeTests/ConstraintTests.cs
Assets/MRTK/Tests/PlayModeTests/Core/Providers/Hands/RiggedHandVisualizerTests.cs
Assets/MRTK/Tests/PlayModeTests/DialogTests.cs
Assets/MRTK/Tests/PlayModeTests/FocusProviderRaycastTests.cs
Assets/MRTK/Tests/PlayModeTests/FocusProviderTests.cs
Assets/MRTK/Tests/PlayModeTests/GltfTests.cs
Assets/MRTK/Tests/PlayModeTests/GridObjectCollectionTests.cs
Assets/MRTK/Tests/PlayModeTests/HandCoachTests.cs
Assets/MRTK/Tests/PlayModeTests/InputEventSystemTests.cs
Assets/MRTK/Tests/PlayModeTests/InputRayUtilsTests.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/DefaultRaycastProviderTest.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/DisableEnableInputSystemTest.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/EyeTrackingTargetTest.cs
Assets/MRTK/Tests/PlayModeTests/InteractableEventTests.cs
Assets/MRTK/Tests/PlayModeTests/JoystickTests.cs
Assets/MRTK/Tests/PlayModeTests/ManipulationHandlerTests.cs
Assets/MRTK/Tests/PlayModeTests/NearInteractionGrabbableTests.cs
Assets/MRTK/Tests/PlayModeTests/NearInteractionTouchableTests.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs
Assets/MRTK/Tests/PlayModeTests/PinchSliderTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerEventsTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/PointerTests.cs
Assets/MRTK/Tests/PlayModeTests/SlateTests.cs
Assets/MRTK/Tests/PlayModeTests/SpeechTests.cs
Assets/MRTK/Tests/PlayModeTests/UserInputSimulationTest.cs
Assets/MRTK/Tests/PlayModeTests/VisualThemeTests.cs

Follow-up to #9714, which exposed some of the inconsistencies in our play mode test set up and tear down. I fixed up the min set for that PR to succeed, but this is a follow-up to fill out much of the rest of the test classes.

Update more play mode test scripts to inherit BasePlayModeTests for consistent setup / teardown

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/SystemKeyboardExample.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKTMPInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MRTKUGUIInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/MixedRealityKeyboardBase.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/TMP_KeyboardInputField.cs
Assets/MRTK/SDK/Experimental/MixedRealityKeyboard/UI_KeyboardInputField.cs

This PR updates the MRTK keyboard implementations/workarounds to align with Unity's keyboard behavior after its recent fixes in 2019.4.25 and 2020.3.2. Note Unity 2019 and 2020 customers need to update to those two versions or later to get the expected experience.

Update MRTK keyboard based on Unity 2019.4.25/2020.3.2 fixes

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef

Add Android to support Quest on OpenXR. Although [Unity currently says](https://docs.unity3d.com/Packages/com.unity.xr.openxr@1.1/manual/index.html)
> At this time, deploying directly to Oculus Quest/Quest 2 is not supported.
we don't want to block developers once that changes.
- Part of unblocking https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9499, as Unity's support comes online

Add Android to support Quest on OpenXR

---

Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs

Fixed Object Manipulator behavior to maintain velocity on release
This fix also entailed fixing the GenericXRSDKController to properly read Velocity and Angular Velocity Data from the input devices. However, this also required a fix from the XRSDK side of things, so this PR combined with the to be completed update to the Windows XRSDK plugin will solve this issue completely
Additionally, I found that objects that are thrown with the controller's velocity feel a bit dampened and unnaturally stiff compared to letting them maintain their velocity. I have included examples of both behavior in the video clips below, which looks the best/most natural?
Old Behavior:
https://user-images.githubusercontent.com/39840334/116744273-f3864a00-a9ae-11eb-90d8-4e99e120f932.mp4
Controller dampened velocity: …

Object Manipulator now maintains velocity on release

---

Assets/MRTK/Core/Interfaces/Devices/IMixedRealityHapticFeedback.cs
Assets/MRTK/Core/Interfaces/Devices/IMixedRealityHapticFeedback.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityController.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Extensions/InteractionSourceExtensions.cs
Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs

Add support for controller haptics across legacy, Windows XR Plugin, and OpenXR (might work for Oculus too). It can be accessed by querying an object (likely an `IMixedRealityController` if it supports `IMixedRealityHapticFeedback`.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9734

Add support for controller haptics across legacy, Windows XR Plugin, and OpenXR

---

Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs

`RiggedHandVisualizer` is instantiated when hand tracking is regained. At that point, the `HandRenderer` is enabled and actually rendering, making the hand mesh visible - even if hand mesh visualization is disabled in MRTK scene settings.
Afterwards, `OnHandJointsUpdated` is called in a subsequent frame, which will evaluate if the profile has hand mesh visualisation enabled, and disable it if not. This results in a bug where, if you had hand mesh visualization enabled, you see the hand mesh popping in at its original location, and then see it disappear again because it is being hidden. If you had hand mesh visualization enabled, you would also see this popping, because the location of the mesh wasn't updated until later.
Disabling the hand mesh rendering on start (until we've been able to …

Fix hand meshes popping in and out quickly as hand tracking is regained

---

pipelines/packageupmpublic.yaml
pipelines/templates/tasks/pack-upm.yml
scripts/packaging/createupmpackages.ps1

Slightly simplifies the UPM pack pipeline and script, renaming `buildNumber` to the more descriptive `previewNumber` and removing an extra bool that represented whether to use the `previewNumber`. It now keys off whether `previewNumber` is provided or not.

Key off previewNumber instead of additional bool for UPM pack

---

Assets/MRTK/Examples/Experimental/ExamplesHub/Prefabs/ToggleFeaturesPanelHubHand.prefab
Assets/MRTK/SDK/Experimental/Joystick/JoystickPrefab.prefab
Assets/MRTK/SDK/Experimental/MixedRealityKeyboardPreview/Prefabs/MixedRealityKeyboardPreview.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Menus/NearMenu4x1.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Panels/ToggleFeaturesPanel.prefab
Assets/MRTK/SDK/StandardAssets/Prefabs/SceneDescriptionPanelRev.prefab

This change updates prefabs that use the objectmanipulator to explicitly have a constraintmanager attached.
Addresses all but a few of the remaining warnings reported in #9603

Eliminate missing constraint manager warnings in Unity 2020

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityInputSystemProfile.cs
Assets/MRTK/Core/Definitions/Utilities/ArticulatedHandPose.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs
Assets/MRTK/Core/Providers/InputAnimation/InputAnimation.cs
Assets/MRTK/Core/Providers/InputAnimation/InputAnimationSerializationUtils.cs
Assets/MRTK/Core/Providers/InputAnimation/InputRecordingService.cs
Assets/MRTK/Core/Providers/InputSimulation/BaseInputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/InputPlaybackService.cs
Assets/MRTK/Core/Providers/InputSimulation/InputSimulationService.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedArticulatedHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedGestureHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHandUtils.cs
Assets/MRTK/Core/Utilities/MaintainBorderLightWidth.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandRecorder.cs
Assets/MRTK/SDK/Features/UX/Scripts/AppBar/AppBar.cs
Assets/MRTK/SDK/Features/UX/Scripts/Slate/HandInteractionPanZoom.cs
Assets/MRTK/SDK/Profiles/HoloLens2/DefaultHoloLens2InputSystemProfile.asset
Assets/MRTK/Services/InputSystem/FocusProvider.cs

1. Makes the graphics raycast optional for apps who don't use Unity UI
1. Defaults to true. Is controlled in the input profile via `shouldUseGraphicsRaycast`
2. Updates to use one central definition for `JointCount`
3. Removes an every-frame list allocation in `HandInteractionPanZoom`
4. Remove some frequent `ConfigurationProfile as MixedRealityInputSystemProfile` casts in FocusProvider

Assorted perf improvements

---

Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationMoveLogic.cs

Fix manipulation behavior when the collider is not centered on the object.
Currently the offset between the grab point and the object's position is being multiplied through the distanceRatio. For example if the grab point is above the object's position, pushing/pulling the object will change its vertical position because the grabToObject delta vector gets distance-ramped. Similarly if the grab point is to the side, pushing/pulling the object will also move it laterally. The amount of this unintended movement is proportional to how far the grab point is from the object's center.
This change moves the grabToObject vector outside of the distanceRatio multiplication.
- Fixes: #9750 .

Fix unexpected manipulation behavior when collider isn't centered on object

---

Assets/MRTK/Services/InputSystem/Editor/NearInteractionTouchableInspector.cs

This PR adds some messages in the editor to let users know the caveats of using NearInteractionTouchable with non-box colliders.
- Fixes: #9696

Show warning messages when using NearInteractionTouchable with non-box collider

---

Assets/MRTK/Core/Providers/BaseGenericInputSource.cs
Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Core/Providers/Hands/HandJointUtils.cs
Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ProximityEffect/ProximityEffect.cs
Assets/MRTK/SDK/Features/Utilities/InputRayUtils.cs
Assets/MRTK/SDK/Features/Utilities/PointerUtils.cs
Assets/MRTK/Tests/PlayModeTests/ProfileTests.cs

While testing MRTK perf with various systems turned off, I hit several null reference exceptions where scripts weren't properly checking for the input system's existence.
Also added some missing `ConstraintManager`s to some objects and fixed up a misconfigured constraint in HandInteractionExamples to reduce logging noise.

Fix some null refs when the input system is turned off

---

Documentation/Contributing/CONTRIBUTING.md
Documentation/Contributing/PullRequests.md
Documentation/Contributing/UnitTests.md
Documentation/README_Dialog.md
Documentation/README_HandCoach.md
Documentation/README_TextPrefab.md
README.md
pipelines/ci-weekly-internal.yml
scripts/ci/githubchanges.ps1
scripts/docs/docfx.json

Fix references to mrtk_development branch (it's now called main)
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9763

Fix references to mrtk_development branch (it's now called main)

---

Assets/MRTK/SDK/Features/Utilities/Solvers/SolverHandler.cs

SolverHandler allocates a new string and game object when it switches targets. HandConstraint switches targets every frame if the target doesn't match its criteria (e.g. palm up for HandConstraintPalmUp), and so causes an allocation every frame.
This updates SolverHandler to only create the tracking transform once and just reparent it.
- Fixes: #9758

Improve solver performance

---

Assets/MRTK/Core/Providers/InputSimulation/InputSimulationHelpGuide.cs
Assets/MRTK/Examples/Common/Prefabs/Help_Panel_Viewer.prefab
Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/SDK/Features/UX/Prefabs/Slate/SlateUGUI.prefab
Assets/MRTK/SDK/StandardAssets/Prefabs/SceneDescriptionPanelRev.prefab

* Cleans up some extra graphic raycasters, as extra graphic raycasters lead to a longer time spent raycasting in the scene.
* Also disables the input simulation help guide when a device is attached, as overlay canvases in VR have a rendering hit without being visible
* Updates InputSimulationHelpGuide to be `internal` and have the correct namespace
* This is a **BREAKING CHANGE**, but I don't expect anybody to be talking to this component directly (and I'm not convinced they should, hence the change to `internal`)
* Updates the "close" button to play the audio before setting the GameObject inactive, as currently the audio is logging an issue with trying to play a disabled audio source
> Can not play a disabled audio source
> UnityEngine.AudioSource:PlayOneShot(AudioClip, Single)

Another perf pass on HandInteractionExamples

---

Assets/MRTK/Core/Definitions/Utilities/VolumeType.cs
Assets/MRTK/Core/Providers/BaseSpatialMeshObserver.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs.meta
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset

The 0.9.4 release of Mixed Reality OpenXR plugin is going to expose a new `MeshComputeSettings` struct for setting specific settings. This aligns with the scene understanding capabilities going forward and will ensure we have forward compatibility as the OpenXR plugin comes online.
There's a fairly straight forward mapping from MRTK settings to these new OpenXR settings.

Add support for new OpenXR mesh settings

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

This change adds a new item to the Mixed Reality > Toolkit > Utilities menu to enable fast access to importing demos and examples when using the NPM packages (ex: via Mixed Reality Feature Tool).
If the examples package is not installed (or if .unitypackage files are being used), the new menu is disabled
When the examples package is present, the menu item is enabled and will display the examples package in the UPM UI
Fixes: #9798

Add "Import Examples from Package" menu item

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs

Marked IsNearObject as virtual so users can extend off sphere and poke pointer
- Fixes: #9794

Marked instances of IsNearObject virtual

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

When the spatial mesh's transform was getting attached to the ObservedObjectParent using the parent property, the default behavior of preserving world space position was kicking in. 
This _sounds_ right, but isn't. It meant that the current ObservedObjectParent's transform (which ultimately resolves to the MRTK Playspace transform) was getting discarded (or more specifically, absorbed into the mesh's local transform).
This led to the observed behavior, that when the MRTK Playspace transform changed, existing spatial meshes remained in correct position (because they were attached to the MRTK Playspace). But new spatial meshes, because they essentially discarded the playspace transform, would appear offset from their physical counterparts.
- Fixes: #9810  .
The issue was most easily seen by …

Correct parenting of spatial mesh to preserve local transform.

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs

Disabling the teleport pose on Hololens, due to not having a good way to specify valid teleport surfaces, as well as not having a great use case for teleporting on Hololens yet.
- Fixes: #9807

Disable Teleport Gesture on Hololens

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs

Reverts changes made to make teleport not be raised on Hololens 2. For users who do not wish to have the teleport gesture raise the teleport pointer, we currently allow them to disable the teleport system.

Reverting change which disabled the teleport gesture #9814

---

Assets/MRTK/SDK/Features/UX/Scripts/ScrollingObjectCollection/ScrollingObjectCollection.cs

Store the renderers in a HashSet instead of a List as there could be many calls to Contains() per frame. Thanks @nuernber for bringing this up!
- Fixes: #9553

Use hashset instead of list to get better perf in SOC

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs

The OpenXR preview API had a late-breaking change, so this brings us up to date with the latest.
Also updates the asmdef to be usable with an OpenXR package preview.
- Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9786

OpenXR mesh settings update

---

Assets/MRTK/Examples/Experimental/MixedRealityKeyboard/Scenes/MixedRealityKeyboardExample.unity

Enable near interaction on the two input fields in the MixedRealityKeyboardExample scene.
- Fixes #9579

Support near interaction in MixedRealityKeyboardExample

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityHandTrackingProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityInputSystemProfileInspector.cs

The hand tracking profile is not super clear that it refers mainly to full articulated hand visualization settings, this PR helps address this issue
Helps with #9823

Renamed parts of the handtracking profile inspector to improve clarity

---

Assets/MRTK/Providers/OpenXR/Profiles/DefaultOpenXRCameraSettingsProfile.asset
Assets/MRTK/Providers/OpenXR/Scripts/HolographicReprojectionMethod.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRCameraSettingsProfile.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRReprojectionUpdater.cs

The OpenXR plugin's API went through a slight change before shipping. This brings us up to date with the latest expected behavior.
1. `NoReprojection` moved to `-1` so that `0` defaults to `Depth`
2. Removed some stale, copied remarks
3. Remove the `IsReprojectionModeSupported` check, since the extension string may change in the future

Update reprojection mode API for OpenXR

---

Assets/MRTK/SDK/StandardAssets/Profiles.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/BoxDisplayConfiguration_HoloLens2_Slate.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/BoxDisplayConfiguration_HoloLens2_Slate.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/LinksConfiguration_HoloLens2_Slate.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/LinksConfiguration_HoloLens2_Slate.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/ProximityEffectConfiguration_HoloLens2_Slate.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/ProximityEffectConfiguration_HoloLens2_Slate.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/RotationHandlesConfiguration_HoloLens2_Slate.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/RotationHandlesConfiguration_HoloLens2_Slate.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/ScaleHandlesConfiguration_HoloLens2_Slate.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Slate/ScaleHandlesConfiguration_HoloLens2_Slate.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/BoxDisplayConfiguration_HoloLens2_Volumetric.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/BoxDisplayConfiguration_HoloLens2_Volumetric.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/LinksConfiguration_HoloLens2_Volumetric.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/LinksConfiguration_HoloLens2_Volumetric.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/ProximityEffectConfiguration_HoloLens2_Volumetric.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/ProximityEffectConfiguration_HoloLens2_Volumetric.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/RotationHandlesConfiguration_HoloLens2_Volumetric.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/RotationHandlesConfiguration_HoloLens2_Volumetric.asset.meta
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/ScaleHandlesConfiguration_HoloLens2_Volumetric.asset
Assets/MRTK/SDK/StandardAssets/Profiles/BoundsControl/HoloLens2Style_Volumetric/ScaleHandlesConfiguration_HoloLens2_Volumetric.asset.meta

BoundsControl.cs provides the capability for customizing visuals through Configuration (profile) files. However, currently, there are no configuration files in the assets. Users have to use configuration files under specific example (Cheese.prefab) which can cause problems when those prefabs are deleted or removed from the project.
- Fixes: #9829
Added two types of configuration files - volumetric and slate. These config files were extracted from Cheese.prefab and Slate.prefab.

Adding Bounds Control's Configuration files to SharedAssets

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKCameraSettings.cs

https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9740 exposed that some of our edit mode tests aren't working on Unity 2020. The culprit appears to have been an attempt at using `Object.Destroy` from edit mode.
Instead, this now uses the MRTK extension which calls the correct `Destroy`/`DestroyImmediate` method depending on context.

Fix tests on Unity 2020

---

Assets/MRTK/Examples/Demos/HandCoach/Scenes/HandCoachExample.unity
Assets/MRTK/Examples/Experimental/ColorPicker/Prefabs/ColorPickerPrefab.prefab

This change fixes the missing constraint manager warning from the ColorPicker example (#9821) and the duplicate EventHandler warning in the HandCoach example (#9812)

Fixes for #9812 and #9821 (import and load time warnings)

---

UPM/Documentation~/README.md

This file, which is packaged in our UPM packages, was still pointing to our deprecated github.io docs. It now correctly points to docs.microsoft.com.

Update UPM Readme.md

---

Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs

Adjusts #9589  so that the Oculus Quest uses the MRTK controller visualizations by default.
Previously, we disabled the MRTK visualization since the Oculus Integration Package comes with it's own visualization. However, this resulted in invisible controllers when the Oculus Integration Package was not present
The crux of the fix is that the previous implementation attempted to stop the TryRenderController() function from running, however, that is only called on controller initialization. The new implementation introduces a mechanism to disable the visualizer after the controller was instantiated.
- Fixes: #9861

Make Oculus use MRTK visualization by default

---

Assets/MRTK/Examples/Demos/UX/Dwell/DwellExample.unity
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2ToggleDwell.prefab
Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2Toggle_32x96_Dwell.prefab
Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2_32x96_Dwell.prefab
Assets/MRTK/SDK/Features/UX/Interactable/Prefabs/PressableButtonHoloLens2_Dwell.prefab

- One of the dwell toggle button examples had an unintended override for the Interactable's Toggle option. Reverted this in the prefab.
- Assigned missing audio clip to dwell button prefab's Interactable > OnClick() event.
- Added/updated Debug Text position in the example scene based on Max's feedback.
Audio clip assigned to Interactable's OnClick() event.
Debug texts:
- Fixes: # .

Dwell graduation - Bugfix on toggle button example

---

Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

Correct parenting of spatial mesh to preserve local transform.
Cherry-picked for a 2.6.2 patch

[2.6.2] Cherry-pick #9819 

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs

Leap released the 4.8.0 Unity Modules yesterday: https://github.com/leapmotion/UnityModules/releases/tag/UM-4.8.0
Support for the 4.8.0 modules did not require a code change, this PR adds comments to the Leap MotionConfigurationChecker file about version 4.8.0.
There are no differences between the 4.7.1 core package and the 4.8.0 core package.  The primary changes from 4.7.1 to 4.8.0 are in the Hands modules, which MRTK does not depend on.  The MRTK Leap Motion support only depends on the presence of the Core unity package:
Due to the lack of differences in the core package between 4.7.1 and 4.8.0, the version will be marked as 4.7.1 even if it is version 4.8.0 because the Version.txt file has remained version 4.5.1.

Add support for the Leap Motion 4.8.0 Unity Modules 

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK.Oculus.asmdef
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRCameraSettings.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXREyeGazeDataProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/MRTK.WMR.XRSDK.asmdef
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityCameraSettings.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityEyeGazeDataProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/LoaderHelpers.cs
Assets/MRTK/Providers/XRSDK/MRTK.XRSDK.asmdef
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

Adds an optional waiting period in the various data providers to ensure that XR is properly initialized before assuming they're properly enabled/disabled.
Previously, data providers would check if their specified loader is the active loader once at initialization, though in some scenarios (like holographic remoting), XR itself isn't initialized until some point later (like when remoting makes a successful connection, which might not be instant).
Now, data providers will wait until an active loader exists before determining their enabled state.
Also fixes a potential null ref in `ArticulatedHandDefinition` which I noticed during shutdown of remoting when a hand is detected.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9682, fixes …

Fix automatic remoting for Windows XR Plugin

---

Assets/MRTK/Core/Utilities/SceneContent/MixedRealitySceneContent.cs
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs

Latency when connecting via holographic remoting is not standard, and on the 2.8.0 version of the windows XR plugin, the time it takes to register the Hololens is a bit longer, causing the scene content system to mistakenly place the scene content in a different area. This PR increases the wait time before setting the scene content's position, giving Unity a bit more time to initialize the camera in the proper place
- Fixes: #9867

Increased the frame wait timer to account for Holographic Remoting latency

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef

Marks the MRTK OpenXR asmdef as valid for all platforms.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9856

Include OpenXR on all platforms

---

Assets/MRTK/Providers/OpenVR/OpenVRDeviceManager.cs

Turns out we've been using the wrong look-up name for a while! This fixes things.

Fix Knuckles name lookup

---

pipelines/mergetool.yml

Without this flag, the pipeline will only run if something changes on the `main` branch, which doesn't always happen daily during stabilization.

Ensure mergetool always runs

---

Assets/MRTK/Providers/Windows/WindowsSpeechInputProvider.cs

We didn't initialize the global input source variable initially, causing warnings to appear.
Fixed error introduced by #9770

Initialize global input source variable

---

Assets/MRTK/Core/Inspectors/Setup/MixedRealityProjectConfiguratorWindow.cs

Update the doc URL in the configurator window so that when the MRTK specific pipeline selection page goes live we can direct users to that page.

Update XR pipeline doc URL

---

Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs

After Unity fixed their head tracking bug on pause/resume, it revealed that we still had _some_ issue with hands not being thoroughly cleaned up.
Thanks to @Holo-Fiedel's research at https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9238#issuecomment-774459693, and verifying the logs locally, this was fixable by guarding against an incorrect hand pose throwing an exception in the hand mesh provider.
The underlying issue appears to be if Windows XR Plugin reports an InputDevice that represents a SpatialInteractionSource that happens to be lost between the time Windows XR Plugin reported its devices and the time MRTK asks the platform for a hand mesh. This should only really happen within the span of a single frame, so the next frame will properly report the InputDevice as lost. …

Fixes floating stale hands and doubled mesh with Windows XR Plugin

---

Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityInputSystem.cs
Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityPointer.cs
Assets/MRTK/Core/Providers/BaseGlobalInputSource.cs
Assets/MRTK/Core/Providers/BaseGlobalInputSource.cs.meta
Assets/MRTK/Providers/Windows/WindowsSpeechInputProvider.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
Assets/MRTK/Tests/PlayModeTests/Components/TestInputFocusListener.cs
Assets/MRTK/Tests/PlayModeTests/Components/TestInputFocusListener.cs.meta
Assets/MRTK/Tests/PlayModeTests/InputEventSystemTests.cs

Cherry-picking #9770 for 2.7 as well as it's followup bugfix #9889
Introduced the concept of a global input source and enabled it with speech (#9770)

Cherry-picking global input source for speech for 2.7

---

Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs

This PR takes a more flexible approach to cases where multiple AsyncCoroutineRunner are present in the scene in recognition of the necessity of such arrangement under certain circumstances (e.g. scene transition).
- Fixes: #9896

Better handling of multiple AsyncCoroutineRunner

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityProfileCloneWindow.cs

Currently, the clone window auto-creates this folder even if the user then changes the clone's destination.
Now the window will only create the folder when a profile is actually being cloned there.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/5806

Don't create CustomProfiles folder unless a profile is actually being cloned there

---

Assets/MRTK/Extensions/HandPhysicsService/Examples/HandPhysicsServiceExample.unity

The hand physics example scene was using the obsolete XR SDK profile instead of its feature-specific hand physics profile.

Restore hand physics profile to example scene

---

pipelines/packageupmpublic.yaml

Follow-up to https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9728, https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9909, and https://github.com/microsoft/MixedRealityToolkit-Unity/pull/9910.
Re-removes the `IsFinal` flag in favor of keying off whether the passed-in preview number is `>= 0` or `< 0`. Defaults to `-1`.

Squash some syntax in the packing pipeline

---

pipelines/packageupmpublic.yaml
pipelines/templates/tasks/pack-upm.yml
scripts/packaging/createupmpackages.ps1

This allows us to include the Version.txt and AssemblyInfo.cs that's generated by the CI pipelines. This will fix versioning our UPM packages and ensure the metadata is standardized across our various distributions.
This PR works by downloading the completed artifacts of a previous pipeline's run, unpacking the artifacts, patching the MRTK version, and repacking.
Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9927

Add ability to repack in the packaging pipeline

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs

Some interactable code was not guarded against a null input system profile. This PR adds checks that match other instances in the code where we check against null input system profiles
- Fixes: #9882

Added checks to interactable inspector code to prevent null errors

---

Assets/MRTK/Core/Utilities/Gltf/Serialization/ConstructGltf.cs
Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetSelections/Scripts/TargetGroupCreatorRadial.cs
Assets/MRTK/Examples/Demos/EyeTracking/DemoTargetSelections/Scripts/TargetGroupIterator.cs
Assets/MRTK/Examples/Demos/EyeTracking/DemoVisualizer/Scripts/InputPointerVisualizer.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
Assets/MRTK/SDK/Experimental/Features/Utilities/StabilizationPlaneModifier.cs
Assets/MRTK/SDK/Features/UX/Scripts/ProgressIndicators/ProgressIndicatorOrbsRotator.cs
Assets/MRTK/SDK/Features/UX/Scripts/Utilities/PrefabSpawner.cs
Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

This indirection is unnecessary (you already have the GameObject directly!) and _can_ have some amount of perf impact if done too often.

Remove calls to .gameObject on GameObjects

---

pipelines/ci-packaging-internal.yml
pipelines/ci-release.yml
pipelines/ci-weekly-internal.yml
pipelines/config/settings.yml
pipelines/docs-binaries.yml

In preparation for some upcoming changes, this PR moves us back off the custom one-off pool and back onto the "regular" shared pool of VMs.
Adding the workspace clean step seems to have fixed the issues we were previously seeing.

Update internal CI to run on regular pool

---

Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs

To check if a pointer is focus locked, we see if there are any IMixedRealityPointerHandler when the OnPointerDown event is raised. 
This PR fixes an edge case where an component implements that interface, but is itself disabled.
- Fixes: #9921

Disabled components no longer focus lock pointers.

---

Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Assets/MRTK/Core/Utilities/Scenes/EditorSceneUtils.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBox.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tools/BuildWindow/BuildDeployWindow.cs
Assets/MRTK/Tools/MSBuild/Scripts/Utilities.cs

1. Updates the namespace (no longer experimental) for `PrefabStageUtility`
2. Fixes `Assets\MRTK\Tools\MSBuild\Scripts\Utilities.cs(132,17): error CS0269: Use of unassigned out parameter 'guid'`
3. Fixes multiple instances of `error CS0618: 'EditorUserBuildSettings.wsaSubtarget' is obsolete: 'EditorUserBuildSettings.wsaSubtarget is obsolete and has no effect. It will be removed in a subsequent Unity release.'`
4. Fixes multiple instances of `error CS0618: 'WSASubtarget' is obsolete: 'WSASubtarget is obsolete and has no effect. It will be removed in a subsequent Unity release.'`
4. Fixes multiple instances of `error CS0165: Use of unassigned local variable 'colliderByTransform'`
5. Fixes multiple instances of `error CS0165: Use of unassigned local variable 'rendererBoundsByTransform'`
6. …

Updates with Unity 2021 changes

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityToolkitPreserveSettings.cs

Updates the default link.xml text to include `ignoreIfMissing="1"`.
Also adds a patching step to any MRTK entries in existing link.xml files in the MRTK.Generated folder.
- Fixes: #9936

Fix link.xml for Unity 2021

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonIconSet.cs

Updating the button config helper to display the icon's texture name.
https://user-images.githubusercontent.com/39840334/121963508-0cf51280-cd1f-11eb-97f9-17f2476cb387.png
- Fixes: #9969

Updated button config inspector to show icon names

---

Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs

Currently, the "affected controllers" list header doesn't change color based on the Unity theme, so we run into cases like
With this PR:
1. The header is updated to use a built-in Unity style, which will adjust according to the Unity theme
2. Split logic depending on if the current mapping has a texture or not is removed, as the result was sometimes misaligned (see screenshot above)

Update controller mapping list header and alignment

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/Collections/GridObjectCollection.cs
Assets/MRTK/Tests/EditModeTests/Tools/MigrationToolTests.cs

1. Removes some uses of `?.` on ScriptableObjects, which isn't supported due to [Unity's custom == operator](https://blog.unity.com/technology/custom-operator-should-we-keep-it).
2. Rescopes an `#if` to not leave an empty method behind
3. Updates a test to use Unity's methods for creating a ScriptableObject instead of `new`ing it

Assorted Unity improvements

---

Assets/MRTK/Core/Inspectors/Setup/MRTKVersionPopup.cs
Assets/MRTK/Core/Inspectors/Setup/MRTKVersionPopup.cs.meta

For ease of figuring out which MRTK version you're running, this PR adds a menu item and corresponding pop-up to discover it!
IMPORTANT: This feature uses the AssemblyInfo.cs files that our CI generates. Therefore, if run from a clone of the repo, it will display `0.0.0.0` instead of any meaningful number.
- Fixes: I thought we had an issue for this, but I can't find it...

Add editor window and menu item for displaying the current MRTK version

---

Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs
Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs

This change cleans up some unneeded code and improves consistency.
1. Merge Radial and Ulnar/default in the HandConstraintPalmUp switch as they performed idential code.
2. Replace instances of == Handeness with IsHand().  ex: == Handedness.Right -> IsRight()

Some cleanup to the HandConstraint* scripts

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs

Some quirks with how the Unity Assets are loaded vs when the inspector code runs causes issues in Unity 2020 with MRTK profiles. This PR fixes two points.
1. Experience settings profiles can now be set to None by default. This fixes issues with new profiles not having their experience settings loaded correctly by default upon creation. Additional checks and warnings are raised in the case of the Experience Settings profile being set to None
2. Cloning a profile no longer forces focus back to the MixedRealityToolkit object. Previously, the inspector of the profile would update to reflect the new, editable status of the profile, but as of Unity 2020, the profile will appear to still be a "default" profile and have it's fields disabled. By changing the selection focus, we circumvent this …

Experience Settings profile can now be set to None

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/PerAxisHandles.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ProximityEffect/ProximityEffect.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

Currently, `BoundsControl` has several issues and inconsistencies regarding the handles and activation mechanisms. This PR is the first in a series to address these problems.
This PR adjusts how the colliders on the per-axis handles are constructed and aligned, resolving the collider alignment issues _**for the rotate and translate handle types only.**_ Currently, scale handles are a different type of Handle entirely, and this PR will not resolve scale handle collider issues. A future PR will address those issues.
`BoundsControl` constructs a container transform for each handle and an accompanying child transform which holds the "visual" of the handle. This separation allows `BoundsControl` to independently scale the handle visual without affecting the collider, which improves reliability …

Partial fix for BoundsControl collider issues and inconsistency

---

Assets/MRTK/Core/Providers/UnityInput/UnityJoystickManager.cs

The recent inclusion of UnityJoystickManager for XR SDK in #9954 led to a need to increase the filtering cases for sources that are handled by other device managers.
- Fixes: #9993

Update filtering for UnityJoystickManager

---

ProjectSettings/ProjectVersion.txt

Per the linked message in Unity's forum, 2018.4.36f1 will be the final release of the 2018 product.
https://forum.unity.com/threads/unity-lts-release-announcements.529171/page-3#post-7249982
This change updates the repository's project version to match.

update repository's project version to last 2018.4 lts

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

This is a _non-breaking_ fix for the collider alignment behavior of the scale handles on BoundsControl-equipped objects. This change brings many of the calculations and behaviors of the scale handles inline with what the newer rotation and translation handles are already doing; i.e., instead of using a two-stage container-scale-visual hierarchy, it uses a single container-visual structure, exactly the same as the rotation and translation handles. This also moves the job of realigning the collider to the container, instead of the visual. Part of this is reworking the scale handles to use _rotation_ realignment, instead of _scaling_ realignment. Previously, the scale handles realigned the colliders by simply flipping the scale of an intermediary object ("visualsScale"), but this causes …

Fixing BC Scale Handles

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/Shared/WindowsMixedRealityHandMeshProvider.cs

In a specific holographic app remoting case, this API may return an empty array. On first look, this shouldn't be a normal case, but we still account for it but then attempt to access the 0th index a couple lines later.

Add early return if array length is 0

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/ScaleHandles.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/Visuals/VisualUtils.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs

Since a while ago (at least 2.6.x) BoundsControl's `FlattenAuto` mode has been broken, such that per-axis handles are not properly disabling themselves when flattened. This has resulted in "doubled up" handles, where there are rotation handles "inside" scale handles, causing inconsistent manipulations.
This was the result of FlattenAuto being passed as the "current flattening axis" to the per-axis handles, which actually need a proper axis in order to determine which handles to disable. When "FlattenAuto" was passed instead of an actual axis, the handles did not know what to do, and as a result did not actually disable any handles.
This is because the per-axis handles used `VisualUtils.GetFlattenedIndices`, which, when given `FlattenAuto` as the axis, would simply not return any flattened …

Fixing BoundsControl auto-flatten and scale handle orientation

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

Last two small changes, based on @keveleigh 's feedback on the last PR.
- Caches ActualFlattenAxis result for multiple calls to `Reset()` on dependent handles
- Uses `if-else` for scale axis parsing of the `FlattenModeType` result

PR re-nits for BC flattening fix

---

pipelines/mergetool.yml

Now that 2.7.0 stabilization is over, this isn't currently needed.

Turn off mergetool

---

Assets/MRTK/Core/Definitions/SpatialAwareness/SpatialAwarenessSurfaceTypes.cs
Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

This PR fixes the issue of the set surface types in the SU profile does not correctly translate into matching behavior due to the way the enum was setup. Also added logging when the SU observer's task fails.
- Fixes: #9987

Logging and SpatialAwarenessSurfaceTypes fix for Scene Understanding

---

Assets/MRTK/SDK/Features/Utilities/ConstraintExecOrderComparer.cs

CI didn't run on the last commit on the constraints priority PR. Accidentally changed the protection level on the IComparer implementation, causing compilation issues.
- Changes IComparer.Compare implementation to public, instead of internal. Class is still internal.

Fixing protection level

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

A regression was introduced in a previous `BoundsControl` fix that impacted activation behavior when a non-default activation type was specified in-editor. Behavior was correct when a `BoundsControl` was set up at runtime, as `OnEnable` would run with the default activation type, and any subsequent `set`s to `BoundsControlActivationType` would properly evaluate the activation policy. The regression only impacted scenarios when a non-default activation type was specified in-editor, and `OnEnable` ran with that activation type.
As a result, this is technically a symptom of missing test coverage. However, this bug is only visible when an option is specified in edit-mode, and then the scene is played. As we can't really write tests that cover a transition from edit to play mode, @CDiaz-MS …

Fixing BC OnEnable issue when non-default activation type specified in-editor

---

Assets/MRTK/Tools/DependencyWindow/DependencyWindow.cs

[Embedded packages](https://docs.unity3d.com/Manual/upm-embed.html) go into the Packages folder directly:
> Any package that appears under your project’s Packages folder is embedded in that project.
This change ensures we load from that folder too.

Add support for embedded packages in the dependency window

---

Assets/MRTK/Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-00-RootScene.unity
Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Examples/Demos/SpatialAwareness/Scenes/SpatialAwarenessMeshDemo.unity

Add a slight offset (25cm) to the starting positions on several demos, to earlier catch problems arising from assumption of an identity transform on the MRTK playspace.
- Fixes: #7695 .
The three scenes are test scenes for the features most susceptible to breakage.
HandInteractionExamples - goto scene for smoke tests.
EyeTrackingDemo-RootScene - Eyegaze needs to be tested on device.
SpatialAwarenessMeshDemo - Likewise must be tested on device.
PR #8256 added validation of non-identity playspace to the automated tests. Putting the offset in these test scenes extends that protection to manual tests run for build-call.
All 3 scenes are saved with Unity v2018.4.34f1.

Offset tests

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs

Unity made some fixes to harden the requirement to call `EditorUtility.ClearProgressBar()` after calling `EditorUtility.DisplayProgressBar`, which ended up causing us to end up in an infinite loop. Adding this call resolves it.
Tested in Unity 2020.3.13f1
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9723

Add ClearProgressBar call to fix Build Window freeze on Unity 2020

---

Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
pipelines/config/settings.yml
pipelines/pr-2020.yaml
pipelines/pr.yaml

- Modified the pr.yaml file to include Unity 2018, 2019 ~~and 2020 validation~~ 
- Removed 2020 validation from pr.yaml due to the failing Base Cursor Test for now 
- Renamed the pr-2019.yaml file to pr-2020.yaml and added 2020 variables

Update pr.yaml and add Unity 2020 Pipeline 

---

Assets/MRTK/Examples/Demos/HandTracking/Scenes/HandInteractionExamples.unity
Assets/MRTK/Examples/Demos/Input/Scenes/DisablePointers/DisablePointersExample.unity
Assets/MRTK/Examples/Demos/UX/Slider/Scenes/SliderExample.unity
Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHubMainMenu.unity

- Some of the example scenes that use MRTK logo image had to be updated. (scale change)
- Polished description panel in the Slider Example scene
**Slider Example scene's description panel polish:**

Example scene logo size update

---

Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/segoeui SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/segoeuib SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/segoeuil SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/segoeuisl SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/seguibl SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOff/seguisb SDF_zwrite_off.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOn/segoeuisl SDF.asset
Assets/MRTK/StandardAssets/FontsSDFTextures/DepthWriteOn/seguibl SDF.asset

Unity keeps reimporting and reserializing these assets, so their serialized names match their file names. This PR gets them in the state Unity appears to require.

Update serialization for font assets

---

Assets/MRTK/SDK/Features/Utilities/Solvers/SurfaceMagnetism.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs

Currently, SurfaceMagnetism uses `Vector3.up` as the up vector for all surface normal `Quaternion.LookRotation` calculations. This causes gimbal-lock-like behavior when the surface that is being magnetized to is mostly looking upwards. This manifests in ugly temporal instability when a hologram is magnetized to the floor of the scene reconstruction mesh.
The quaternion math in `SurfaceMagnetism` has been fixed to now use the "best guess" up vector, derived from the current working rotation's up vector. This ensures temporal stability in all cases. Compatibility has been ensured with both modes of `KeepOrientationVertical`, as well as `OrientationMode.TrackedTarget`.
A unit test has been added that verifies the absence of any gimbal locking behavior when a floor-like surface is …

Fixing SurfaceMagnetism quaternion math

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManagerProfile.cs
Assets/MRTK/Providers/Oculus/XRSDK/Profiles/DefaultOculusXRSDKDeviceManagerProfile.asset

Previously Oculus controllers managed their visuals completely separately from MRTK. This PR refactors the Oculus Touch Controllers to use the visualizer in a similar manner as the WMR controllers. For consistency, it also makes it so avatar hands can be rendered at the same time as the controller models, since Oculus's OvrAvatar functionality operates in it's own system and cannot be managed easily by MRTK.
- Fixes: #10002

Oculus visualization now integrated with MRTK

---

Assets/MRTK/SDK/Features/UX/Scripts/Sliders/SliderSounds.cs

Added option to only play slider sounds during manipulation. When enabled, a flag is flipped on when the slider is being manipulated, which allows the sounds to play. This ensures that the sound only plays during manipulation, and not when the value is modified via scripts.
- Fixes: #10065

Added option to only have slider sounds play during manipulation

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundingBox/BoundingBoxHelper.cs

When `GetRawBBCorners` was deprecated in favor of `GetRawBoundsCorners`, the protection level of `GetRawBoundsCorners` was not set to public. In addition, the Obsolete warning comment was incorrectly written to refer to the obsolete method, instead of the new one. 
It should be safe to mark this as `public`, as it seems to be the intended behavior (the other methods in this class that replaced their obsolete counterparts are all public, to match their deprecated siblings.)
- Fixes: #10083  
- Makes `GetRawBoundsCorners` public, as it is the recommended replacement for a previously-public function.
- Fixes the obsolete warning to refer to the correct method.

Fixing BoundingBoxHelper.GetRawBoundsCorners protection level

---

Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfUtility.cs

The GltfUtility was splitting the extension support logs across multiple messages, which was a little unclear which messages were related or not.
This PR instead builds all the extension names into one log and reports the whole message at once.

Update glTF import logs to be one log instead of multiple

---

ProjectSettings/ProjectSettings.asset

This change doesn't have any effect on our distributed packages, just our in-repo test project.
Several bugs (like https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9238) are specifically reproable when run in background is not on, which is the default and recommended state. This setting has been used as a bug workaround in the past (largely in the HL1 timeframe) but should no longer be used in most cases.
To help our team more properly discover, diagnose, and fix issues in the default state, this PR turns this setting off.

Turn off run in background

---

Assets/MRTK/Tools/RuntimeTools/Tools/ControllerMappingTool/ControllerMappingTool.unity
Assets/MRTK/Tools/RuntimeTools/Tools/InputFeatureUsageTool/InputFeatureUsageTool.unity

These two tool-based scenes don't have MRTK objects in them (by-design, as they only talk directly to Unity in order to help with mapping various pieces into MRTK), so the MRSceneContent script was failing due to a lack of MRTK.

Remove MRSceneContent script from scenes that don't have MRTK in them

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/HPReverbG2Controller.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftControllerModelProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftMotionController.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandMeshProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRReprojectionUpdater.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs

Now that 1.0.0 is out, we should only support that and newer. This is a breaking change, but one that I think is worth taking as:
1. It reduces the matrix of versions we're trying to support at once
2. Only removes pre-1.0 preview versions, which we want users to update to a stable release anyway
3. Is an easy fix: update any preview MROpenXR package to 1.0.0 or newer

Remove support for preview MROpenXR versions

---

Assets/MRTK/SDK/Features/Input/Handlers/EyeTrackingTarget.cs

Fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10106
Changed assignmnet in accordance to variable documentation:
"GameObject eye gaze is currently targeting, updated once per frame. null if no object with collider is currently being looked at."
Previous behaviour only changed variable if gameobject that was hit had an EyeTrackingTarget attached, if no collider was hit it was set to null and if a collider was hit on a gameobject that did not have any eyetrackingtarget then it was not updated.
Documentation specifies it should be the "GameObject eye gaze is currently targeting", and not anything relating to if it has eyetrackingtarget or not. Not sure if intention is/was for it to be null if the gameobject does not have eyetrackingtarget, but then documentation as well …

Fix for: "EyeTrackingTarget not triggering OnLookAway when passing from collider with EyeTrackingTarget to collider without"

---

Assets/MRTK/Providers/OpenXR/Editor/MRTK.OpenXR.Editor.asmdef

Looking through our assemblies, I accidentally created one that matched our asmdef filenames and not our assembly name standards.
This updates things to match. Since it's a small assembly with only one file, came out in our most recent release, and is editor-only, I don't think there should be any external assemblies with dependencies on this.

Update assembly name to match MRTK standards

---

Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandJointProvider.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandJointProvider.cs.meta

A first step towards supporting hand joints across both actual articulated hands and motion controllers, which can provide a hand joint representation on OpenXR on various runtimes.
- Part of fixing/improving https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9849

Refactor out OpenXRHandJointProvider

---

Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/MousePointer.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ScreenSpaceMousePointer.prefab

Changes the default pointing extent for the screen space mouse pointer to be much smaller, thus making the mouse pointer interactions with the sliders much more natural and intuitive.
The reason for this change is because a mouse pointer's "position" is determined by the following
Camera Position + mouse pointer forward transform * DefaultPointerExtent.
This means that the mouse pointer's position is always DefaultPointerExtent units away from the camera, which makes the mosue pointer's position in world space change pretty drastically. In the current architecture, it's quite a bit more work to make the mouse pointer's position coincide with the position of it's raycast hit target, so this PR alleviates the high variance issue by decreasing DefaultPointerExtent to a more reasonable value …

Changed default pointer extent to make mouse pointer behavior more intuitive

---

.gitignore
Assets/XR.meta
Assets/XR/Loaders.meta
Assets/XR/Loaders/AR Core Loader.asset
Assets/XR/Loaders/AR Core Loader.asset.meta
Assets/XR/Loaders/Oculus Loader.asset
Assets/XR/Loaders/Oculus Loader.asset.meta
Assets/XR/Loaders/Open XR Loader No Pre Init.asset
Assets/XR/Loaders/Open XR Loader No Pre Init.asset.meta
Assets/XR/Loaders/Open XR Loader.asset
Assets/XR/Loaders/Open XR Loader.asset.meta
Assets/XR/Loaders/Windows MR Loader.asset
Assets/XR/Loaders/Windows MR Loader.asset.meta
Assets/XR/Settings.meta
Assets/XR/Settings/AR Core Settings.asset
Assets/XR/Settings/AR Core Settings.asset.meta
Assets/XR/Settings/Oculus Settings.asset
Assets/XR/Settings/Oculus Settings.asset.meta
Assets/XR/Settings/Open XR Package Settings.asset
Assets/XR/Settings/Open XR Package Settings.asset.meta
Assets/XR/Settings/OpenXR Editor Settings.asset
Assets/XR/Settings/OpenXR Editor Settings.asset.meta
Assets/XR/Settings/Windows MR Package Settings.asset
Assets/XR/Settings/Windows MR Package Settings.asset.meta
Assets/XR/XRGeneralSettings.asset
Assets/XR/XRGeneralSettings.asset.meta
ProjectSettings/EditorBuildSettings.asset

Reverts https://github.com/microsoft/MixedRealityToolkit-Unity/pull/8223.
Especially with OpenXR, we now want the repo in a known-good state with specific features enabled, and it feels like the assets have stabilized enough for it to be resonable to check these in again.
This shouldn't have any effect on consumers of the Toolkit, just those who clone the repo and open it in Unity directly. This also gets us closer to being able to produce usable appxs from various XR pipelines in our CI.

Re-add XR folder

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

BoundsControl exhibited unexpected behaviour when using NonUniform scaling on a rotated GameObject. This PR fixes that.
- Fixes: #8992.
Open BoundsControlExamples scene. Change the ScaleBehavour under ScaleHandlesConfiguration to NonUniform. Using the scale handles on an arbitrarily rotated GameObject now behaves as expected (opposite corner stays fixed in world space)

Fix for Bounds Control With Non Uniform Scale Issues

---

Assets/MRTK/Core/Utilities/Editor/Setup/MixedRealityProjectConfigurator.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs

Using CultureInfo.InvariantCulture for Configurations.IOSMinOSVersion because some cultures use other decimal separators than a dot ('.'). For example, in pl-PL it is a comma (',').

Correctly handling IOSMinOSVersion in different cultures

---

Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs

Make pointer event callbacks virtual in order to more closely track and interact with them.
- Make the following functions virtual:
- Start
- OnPointerDown
- OnPointerDragged
- OnPointerUp
>
>

Make ObjectManipulator Start and OnPointerX functions Virtual

---

Assets/MRTK/Core/Attributes/SpeechKeywordAttribute.cs
Assets/MRTK/Core/Attributes/SpeechKeywordAttribute.cs.meta
Assets/MRTK/Core/Definitions/InputSystem/KeywordAndResponse.cs
Assets/MRTK/Core/Inspectors/PropertyDrawers/SpeechKeywordPropertyDrawer.cs
Assets/MRTK/Core/Inspectors/PropertyDrawers/SpeechKeywordPropertyDrawer.cs.meta
Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Core/Inspectors/Utilities/SpeechKeywordUtility.cs
Assets/MRTK/Core/Inspectors/Utilities/SpeechKeywordUtility.cs.meta
Assets/MRTK/Examples/Demos/EyeTracking/DemoVisualizer/Prefabs/RecordButton.prefab
Assets/MRTK/Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoSpeechCommandsProfile.asset
Assets/MRTK/Examples/Demos/EyeTracking/Scenes/EyeTrackingDemo-05-Visualizer.unity
Assets/MRTK/SDK/Editor/Inspectors/Input/Handlers/SpeechInputHandlerInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/InteractableInspector.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs

Updates the keywords and labels in the ET sample to no longer clash with [system keywords](https://docs.microsoft.com/en-us/hololens/hololens-cortana#general-speech-commands). The new keywords are "record eye gaze" and "end recording".
While investigating this, I also noticed some general speech command issues that I fixed up, including
1. The KeywordAndResponse not filling the entire inspector
2. Voice command not being settable from a Unity event
I unified the speech command dropdown behavior into a single utility class, which is now used across `Interactable` and `SpeechInputHandler`, which previously had their own distinct implementations.
Additionally, `SpeechInputHandler` had a bug from porting from HTK that was preventing the custom dropdown from showing up in the first place.
- …

Fix speech command dropdown and update commands in ET example

---

cgmanifest.json
scripts/ci/requirements.txt

The version field is apparently required when the "other" type is used.

Add version to cgmanifest and format

---

Assets/MRTK/Core/Utilities/Gltf/Serialization/ConstructGltf.cs

GLTF object appears black if it is loaded with Unity's Standard shader.
When loading gltf, and if there's no MixedRealityStandard shader, ConstructGLTF creates materials using Unity's Standard shader.
And if the main color data is null, CreateStandardShaderMaterial() assigns the null data to the main color of the material so the gltf object appears black.
This can be avoided by checking the color data is null as like the same as CreateMRTKShaderMaterial() does.
- Fixes: #10195
Assign main color only if the gltf material has color value.

Fix gltf object appears black

---

Assets/MRTK/Core/Providers/UnityInput/UnityTouchDeviceManager.cs

UnityTouchDeviceManager, as other data providers (eg. XRSDKDeviceManager), should not Update itself if its IsEnabled property is false.
- Fixes: # .
>
>
> …

UnityTouchDeviceManager now respects its IsEnabled property

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/Tests/PlayModeTests/SpherePointerTests.cs

This PR makes it so that the sphere pointer now prioritizes the object with less volume when determining which object to grab in overlapping cases. This is a sufficiently usable solution for our OverlapSphere based implementation of grab pointers, only failing in cases of corner overlap and convex colliders.
- Fixes: #7629

Fixed inconsistent interaction behavior for overlapping objects

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs

Update the voiceCommand property name in the editor script to fix a null pointer problem caused by the case change introduced in #10197.

Update a property name in button config helper

---

Assets/MRTK/Core/Utilities/OBJWriterUtility.cs
Assets/MRTK/SDK/Features/Utilities/SpatialMeshExporter.cs

Unity and OBJ differ! Unity is right-handed, OBJ is left-handed. Unity is CW, OBJ is CCW.
Also slightly adjusted the ordering of new lines for consistency.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8475

Update obj exporter to fix coordinate space, winding order, and culture formatting

---

Assets/MRTK/Tools/MigrationWindow/MigrationWindow.cs
scripts/ci/validatecode.ps1

#10220 fixed our pipeline and code validation but revealed that we have some unaccounted for hardcoded paths that entered the repo while validation wasn't working! This PR adds the required ones (in ExamplesHub) and updates some comment-based paths to stop triggering the regex.

Fix some cases of hardcoded paths

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs

The grasp pointer by default is positioned between the thumb and index finger. However this is confusing if a fingertip cursor is rendered (either because one is added to the grasp pointer or because grabbable elements are near pokable ones). This adds an option to move the grasp point to the fingertip if desired.
- Fixes: # .
>
>
> As a …

Add option to move grasp point to fingertip

---

Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionConfigurationChecker.cs

Add support for 4.9.1 UnityModules - release notes available [here](https://github.com/leapmotion/UnityModules/releases/tag/UM-4.9.1).
Run through [Using Leap](https://docs.microsoft.com/en-gb/windows/mixed-reality/mrtk-unity/supported-devices/leap-motion-mrtk?view=mrtkunity-2021-05) and try out the example scenes in Head and Desk mode. 4.9.1 can be downloaded from the release page above or from the [Ultraleap Developer Site](https://developer.leapmotion.com/unity).
Pull request for the docs repo to come shortly.

Add support for Leap UnityModules 4.9.1

---

Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityGesturesProfileInspector.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
Assets/MRTK/Core/Inspectors/Utilities/InspectorFieldsUtility.cs
Assets/MRTK/Core/Inspectors/Utilities/InspectorUIUtility.cs
Assets/MRTK/Providers/LeapMotion/Editor/LeapMotionDeviceManagerProfileInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Exp/InteractiveEl/CompressableButtonInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Input/Handlers/ControllerPoseSynchronizerInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Collections/GridObjectCollectionInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/ButtonConfigHelperInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Interactable/PressableButtonInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Tooltips/ToolTipConnectorInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/VisualThemes/ThemeInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/FollowInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/InBetweenInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/SolverHandlerInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/Solvers/SurfaceMagnetismInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/Buttons/ButtonConfigHelper.cs

In almost every case, we care about intValue over enumValueIndex in serialized properties.
I'm bad at explaining this, but here goes:
enumValueIndex represents the ordinal placement of the enum value in the enum definition. This will always increase by 1 as we go down the enum definition, regardless of if the enum entry is defined as some other number.
intValue is the actual underlying int representation of the enum, so any time a cast or comparison with an enum value is used, this int is represents what we're trying to compare.
In many cases, this won't be an issue, but if there are duplicately defined int values or gaps in the enum, these numbers will differ.

Convert incorrect usages of enumValueIndex to intValue

---

Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationHandler.cs
Assets/MRTK/SDK/Features/Input/Handlers/Manipulation/ManipulationMoveLogic.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/Tests/PlayModeTests/ObjectManipulatorTests.cs

Fixed issue with the Object Manipulator causing objects to drift during near manipulationl
- Fixes: #10198

Fixed objects drifting during Near Manipulation

---

Assets/MRTK/SDK/Editor/Inspectors/UX/BoundsControl/BoundsControlInspector.cs
Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

Bounds control will no longer remove boxcollider and neargrabbable components on disable
- Fixes: #10290

Fixed cases where bounds control would aggressively remove other components

---

Assets/MRTK/Core/Utilities/StandardShader/ProximityLight.cs

We notice a small but distracting flicker when moving from a poke to a grab pointer when pokable and grabbable objects are in close proximity. There's a single frame when there are no lights enabled.
Adding a forced update to `OnEnable()` (similarly to the behaviour of `OnDisable()`) fixes the issue.

Fix for flickering Proximity Lighting

---

Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraint.cs

This change brings to 2.x a recent change made to v3 that reduces the number of Debug.LogWarning events originating in the HandConstraint solver.

Backport recent v3 update to reduce debug log spam

---

Assets/MRTK/SDK/Features/Utilities/Solvers/HandConstraintPalmUp.cs

The HandConstraintPalmUp.cs script is logging a warning whenever it cannot find the palm joint. However this scenario happens quite often when the HL detects a partial hand with palm joint missing. In that scenario, the hand input is considered invalid which causes no harm at all.
The solution is to remove the debug log for this legitimate and common scenario to not flood our logs with unnecessary warnings.

Fixed log spam that is coming from HandConstraintPalmUp.cs

---

Assets/MRTK/SDK/Editor/Inspectors/UX/Pointers/SpherePointerInspector.cs

#10206 added a new serialized field but didn't update the inspector to expose it.

Add missing inspector change from #10206

---

Assets/MRTK/Core/Utilities/Physics/ConeCastUtility.cs
Assets/MRTK/Services/InputSystem/ConeCastGazeProvider.cs

License headers were missing on some of the cone cast files, this PR adds them in

Added missing license headers

---

Assets/MRTK/Providers/Experimental/WindowsSceneUnderstanding/WindowsSceneUnderstandingObserver.cs

This PR adds support for Scene Understanding in remoting via the OpenXR pipeline, which is made possible by the recent improvements made to the Microsoft Mixed Reality OpenXR plugin.
- Fixes: #10307.

Enable Scene Understanding in remoting via OpenXR

---

Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Events/InteractableOnClickReceiver.cs

Add a parameterless constructor to InteractableOnClickReceiver to allow lines like `var onClickReceiver = interactable.AddReceiver<InteractableOnClickReceiver>();`
- Fixes: #10341. Thanks @iweinbau for spotting the issue and proposing a fix!

Add a parameterless constructor to InteractableOnClickReceiver

---

Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs

To fix #10304, we'll likely need a change on the Unity side. To account for this change, we'll need to add a new fallback for the articulated hand on OpenXR. This will allow us to both be compatible with existing versions and future versions (assuming the change is made on the Unity side).
- Part of fixing #10304

Add fallback case for articulated hand select on OpenXR

---

Assets/MRTK/Core/Inspectors/PropertyDrawers/SceneInfoUtils.cs

We found that this was causing intermittent pauses when entering/exiting PlayMode.  Upwards of 5 seconds.  
(This is a slice of an earlier PR that was too big)
- Fixes: # .
>
>
>
> git fetch …

Skip Scriptable object reflection if scene system isn't enabled

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityRaycastHit.cs

This PR fixes two issues:
1. Similar to #7632, which we apparently fixed in too-targeted of a fashion, there are three other calls that we needed to gate behind the mesh being readable.
2. Starting in Unity 2021, there are error logs every time you try to read a texture coordinate that doesn't exist. Luckily, Unity added some helper methods in Unity 2019 to check if the mesh has specific texture coordinate attributes.
- Fixes: #10233 and fixes #10339

[2.7.3] Improve raycast hit to prevent log spam on Unity 2021 and prevent a crash when using assetbundles

---

Assets/MRTK/Core/Services/BaseService.cs

Pulls out a fix from #10310 into 2.7.3

[2.7.3] Update strings to const and cache type to reduce allocs

---

Assets/MRTK/Core/Providers/BaseSpatialMeshObserver.cs
Assets/MRTK/Core/Providers/BaseSpatialObserver.cs
Assets/MRTK/Examples/Demos/PulseShader/Profile/PulseShaderSpatialAwarenessSystemProfile.asset
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs
Assets/MRTK/SDK/Profiles/DefaultMixedRealitySpatialAwarenessSystemProfile.asset
Assets/MRTK/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs

Updates our XRSDK-based mesh observers to:
1. Properly refresh their mesh subsystem when XR is initialized _after_ MRTK is initialized
2. Ensure that more than one observer is not running when the "generic" observer is used with a more specific observer (like the one specific to OpenXR)
3. Ensured that we don't try to use a mesh subsystem that isn't actively running. This was leading to 
3. Ensured that we don't try to set values on the mesh subsystem unless the app is running (the underlying bug here would probably also be solved by fix 3)
- Fixes: #10293, fixes https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10244, might fix #10245 (but I couldn't get a repro)

Fix mesh when using app-based holographic remoting

---

Assets/MRTK/SDK/Features/UX/Scripts/BoundsControl/BoundsControl.cs

As part of fixing some missing BC doccomments, I discovered that the public `BoundsCorners` property was actually dead code and was never referenced by anything. This fixes the doccomments and removes this dead property.
- Fixes: #10346 
- Obsoletes `BoundsControl.BoundsCorners`. This property was completely un-referenced and was never actually populated by any data.
All BoundsControl tests pass.

Fix for missing BC docs + dead property

---

Assets/MRTK/Examples/Experimental/ExamplesHub/Scenes/MRTKExamplesHubMainMenu.unity
Assets/MRTK/Examples/Experimental/SceneUnderstanding/Profiles/DemoSceneUnderstandingMixedRealityToolkitConfigurationProfile.asset

When we load SceneUnderstandingExample scene from the MRTKExamplesHubMainMenu, we load DemoSceneUnderstandingMixedRealityToolkitConfigurationProfile. To be able to come back to HubMainMenu, Scene System option is checked and 'MRTKExamplesHubSceneSystemProfile' is selected. 
Uncheck the Scene System in the DemoSceneUnderstandingMixedRealityToolkitConfigurationProfile since it is only needed specifically when you build as part of Examples Hub.

2.7.3 SU Example scene profile fix

---

Assets/MRTK/Core/Extensions/UnityObjectExtensions.cs
Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/SDK/Features/Input/Handlers/SpeechInputHandler.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/GGVPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Assets/MRTK/Services/InputSystem/GazeProvider.cs

We've encountered a number of input callbacks that can cause `NullReferenceException` in rare circumstances. These incidents seem to occur most often when suspending the app by returning to the holographic shell and resuming while tapping repeatedly.
I've added null checks in a variety of places where we've observed problems.
I've replaced `if (this == null)` with `if ((MonoBehaviour)this == null)` (as well as adding this check in a few places) to ensure that the correct overload of `==` is resolved.
> on the specific scenarios and what …

Add null reference checks to callbacks

---

Assets/MRTK/Core/Utilities/Gltf/Schema/GltfObject.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/ConstructGltf.cs

added NodeGameObjectPairs to easily get gameobject from GltfNode id
- Fixes: #10399.

Gltf nodeId-gameObject dictionary

---

Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs

Fix to ensure that LeapMotionArticulatedHand, which implements IMixedRealityController, correctly sets the IsPositionAvailable and IsRotationAvailable properties.
Before the fix, they defaulted to and stayed false. This manifested as an issue in the HandMenuExamples scene where, while using LeapMotionDeviceManager as an Input Data Provider, the hand menu would not appear when the palm was turned towards the camera. This was due to a check of IsPositionAvailable in HandConstraintPalmUp.cs returning false thus preventing the menu becoming active.
- LeapMotionArticulatedHand: set _IsPositionAvailable_ and _IsRotationAvailable_ correctly after checking whether a Leap hand is being tracked.
I have tested the following set up to ensure the fix took effect.
- MRTK 2.7.3
- Unity 2019.4.34
- …

Fix Leap hand not reporting position and rotation availability correctly

---

Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/PokePointer.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ShellHandRayPointer.prefab
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/FingerCursor.cs

The offending cursor prefabs have by default their visuals enabled. When handtracking starts and the cursors are spawned, it takes the system a frame to figure out they're not needed and to disable them. This results in the cursors flashing.
The solution is to simply check `disableCursorOnStart` for the offending cursors and have the visuals properly disabled for the poke pointer (properly as in not only a transparent material, but disabling the visuals GameObject).
The latter change also fixes a cutout on your index finger when using the handmesh visualization:
_After - Before:_
- Fixes: #10270
- Fixes: #10236

Fix single-frame cursor flickering

---

Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

This change applies playspace awareness from the WinMR XR2018 spatial mesh observer to the WinMR XRSDK and OpenXR observers.
Caviat: The OpenXR observer supports only AxisAlignedCube per Unity's API specification ( https://docs.unity3d.com/ScriptReference/XR.XRMeshSubsystem.SetBoundingVolume.html )
@fast-slow-still @peterneil-bimholoview this should fix https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10343.

Apply playspace alignment from the WinMR XR2018 observer to the WinMR XRSDK and OpenXR observers

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs

Force the perceptionSensorsExperimental element to come first.
According to https://docs.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities , it's necessary.
- Prioritize ResearchMode capability first in BuildAppx 
>
>
> As a reviewer, it is possible to check out this change locally by using the …

[BuildAndDeploy] perceptionSensorsExperimental should be first

---

Assets/MRTK/Core/Providers/Hands/HandRay/HandRay.cs
Assets/MRTK/Tests/PlayModeTests/BoundsControlTests.cs
Assets/MRTK/Tests/PlayModeTests/SolverTests.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs

Hand rays had a slightly different update function based on handedness. This PR fixes the discrepancy
old:
new:

Fixing difference in hand ray pointing math between left and right hands

---

Assets/MRTK/Core/Definitions/Utilities/ArticulatedHandPose.cs
Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Core/Providers/Hands/HandBounds.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs

Removes everywhere we used to iterate through the dictionary, its keys, or its values with `foreach`, as all of these cause the enumerator to be allocated. Instead, we now use lists where possible and index into them instead of checking a dictionary.
Also optimizes some code paths where we were doing multiple dictionary calls for the same key.
Drops the per-frame allocs from 40B per-hand to 0.
Also feels like it drops the average time spent in this method, though it fluctuates a bit and is harder to measure.
- Part of fixing #9400

Improvements to hand joint visualizer perf

---

Assets/MRTK/SDK/StandardAssets/Shaders/FingerTipCursor.shader

Batching calls to the fingertip cursor shader caused some strange elongation errors in certain edge cases.
- Fixes the following scenario

Fixed issue where cursors would elongate in special circumstances

---

Assets/MRTK/SDK/Editor/Inspectors/Audio.meta
Assets/MRTK/SDK/Editor/Inspectors/Audio/TextToSpeechInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Audio/TextToSpeechInspector.cs.meta
Assets/MRTK/SDK/Features/Audio/TextToSpeech.cs

Modified the TextToSpeech script so that it now supports user specified voices. This is useful when performing TTS in locale other than en-US.
- Fixes: #10395

Allow custom TTS voices

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/UX/Pointers/TeleportPointerInspector.cs
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ParabolicTeleportPointer.prefab
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TeleportPointer.cs
Assets/MRTK/Tests/PlayModeTests/PointerBehaviorTests.cs

The raycast layermask path is pretty confusing between the pointer profile and the individual pointer settings. This PR does some work in clarifying these, and makes the teleport pointer more in line with the other pointers (poke, grab)
Potentially a breaking change, as the PrioritizedRaycastLayerMask returned by the interface is no longer a union of the Valid and Invalid layers.
- Fixes: #10387 and others

Clarifying raycast layermask descriptions and fixed teleport pointer overloading definitions

---

Assets/MRTK/Core/Services/MixedRealityToolkit.cs

The way we were reinitializing profiles called into a systems Disable() function, causing side effects. In particular, for the gaze provider, it would aggressively remove and repopulate the gaze provider.
This PR changes that.
- Fixes: #10485

fixed issue where gaze provider gets forcibly reset on profile modification

---

Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/ConeCastTrackingTargetTest.cs
Assets/MRTK/Tests/PlayModeTests/InputSystem/EyeTrackingTargetTest.cs

Remove unused variable in some file ```PokePointer.cs```, ```ConeCastTrackingTargetTest.cs``` & ```EyeTrackingTargetTest.cs```
- Remove unused variable ```private Vector3 endPoint```.
- Remove unused variable ```private GameObject target```.

Remove Unused Variable

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRSpatialAwarenessMeshObserver.cs

The mesh visual/collider setting was never really hooked up on the OpenXR side and is being obsoleted in the upcoming 1.4.0 MR OpenXR package. The plugin returns visual meshes in all cases, like legacy XR did.
Also adjusted a usage of `Dispose()` vs `Destroy()` in the gesture recognizer.

Adapt obsolete method/property usage for compatibility with Mixed Reality OpenXR 1.4.0

---

Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealityDeviceManager.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKGGVHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityDeviceManager.cs

Adds explicit support for the `SpatialInteractionManager`s source pressed/released with voice.
This will _not_ work over remoting, but the normal keyword recognition should catch this case in that scenario.
- Fixes: #8582

Add support for "select" voice command with Windows XR Plugin

---

Assets/MRTK/Providers/XRSDK/XRSDKBoundarySystem.cs

Adds a mapping for World == Unbounded on Unity 2020+. This is a new concept which maps more closely with our definition of "world" space vs device space.
- Fixes: #10523

Add support for TrackingOriginModeFlags.Unbounded

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MRTK/Core/Interfaces/InputSystem/IMixedRealityEyeGazeProvider.cs

Reworded the profile inspector settings to reflect their actual usage, and added a button directly in the inspector to bring users to our Eye Gaze setup documentation.
- Fixes: #8390

Clarified eye tracking settings wording and added links to documentation

---

pipelines/ci-packaging-internal.yml
pipelines/ci-weekly-internal.yml
pipelines/config/settings.yml
pipelines/docs-binaries.yml

The new pool doesn't have a Unity 2018 installation, but we'll continue validating that on the public pools.

Update to new internal pool for CI

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/OculusController.cs
Assets/MRTK/Providers/OpenXR/Scripts/OculusController.cs.meta
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs

This PR adds several fallbacks for input actions for when hand joint data is available but not raw device data. This makes our OpenXR deployment story much more complete on non-Hololens platforms, and will greatly help drive cross-platform development.
Video sooooooon
- Fixes: Several issues and is a big step towards removing our dependencies on Leap Motion and Oculus Packages.
#10477

OpenXR general hand interaction support

---

pipelines/docs-binaries.yml

These represent DLLs when successful and the log when unsuccessful.

Always publish artifacts in docs pipeline

---

Assets/MRTK/Tools/MSBuild/Scripts/UnityProjectInfo.cs

Unity 2019.4 has some recent changes in its way of handling Unity UI dependencies of TMP. This PR addresses the issue.

Remove unnecessary #if

---

Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs

On OpenXR, there's a bit of an unusual state where we're reconciling two different `InputDevice`s together in order to get the full picture of hand joints, button data, positional data, etc.
This was hitting a weird case where, when controllers were reporting hand joint data, the hand joint `InputDevice` was inadvertently being used to read the pose data, even though it doesn't provide any. This change ensures we only report real pose data.
- Fixes: I couldn't find the exact issues, but I've seen this come up in a couple places

Fix issue where WMR controllers weren't reporting spatial data in "controller" mode when hand joints were enabled

---

Assets/MRTK/Tools/MSBuild/Scripts/MSBuildTools.cs

Use a newer C# version for 2020.2+ C# project generation to resolve a docs pipeline failure caused by #10561.

Define Build Tool C# version based on Unity version

---

Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs

If the event data did not contain entries for all joints, the hand visualizer would throw an exception as it does a lookup on a hand joint which doesn't exist. This PR fixes that, stabilizing Oculus Visuals for 39.0 and beyond for 2019.

Fixed issue where hand joint lookup would throw dictionary exceptions for visualizers

---

Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Editor/OculusXRSDKHandtrackingConfigurationChecker.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/BaseControllerPointer.cs

When deploying to Oculus the 618 error will still pop up, this adds that code to the csc to fix that issue.
Fixed some whitespace that was introduced accidentally.

Fixing Oculus Deployment Issue, whitespace error

---

.editorconfig
Assets/MRTK/Core/Attributes/SystemTypeAttribute.cs
Assets/MRTK/Core/Services/BaseEventSystem.cs
Assets/MRTK/Core/Utilities/DebugUtilities.cs
Assets/MRTK/Core/Utilities/Gltf/Serialization/GltfUtility.cs
Assets/MRTK/Examples/Demos/UX/BoundingBox/Scripts/BoundingBoxExampleTest.cs
Assets/MRTK/Examples/Demos/UX/BoundsControl/Scripts/BoundsControlRuntimeExample.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs

Pulling some additional fixes from 10310 for 2.8

---

Assets/MRTK/Examples/Demos/HandTracking/Scripts/TetheredPlacement.cs

As the scene can be dragged around, the platform the objects should sit on can move around, causing the objects to respawn into nothingness.
This change allows the objects to remember their relative poses and correctly spawn back above the platform.

Update TetheredPlacement.cs to use local pose

---

Assets/MRTK/Core/Definitions/InputSystem/MixedRealityPointerProfile.cs
Assets/MRTK/Core/Definitions/InputSystem/PointerOption.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Profiles/EyeTrackingDemoPointerProfile.asset
Assets/MRTK/Examples/Demos/Input/Scenes/DisablePointers/DisablePointersExamplePointerProfile.asset
Assets/MRTK/Examples/Demos/LookAndPinch/General/Profile/LookAndPinchDemoPointerProfile.asset
Assets/MRTK/Examples/Experimental/ExamplesHub/Profiles/MRTKExamplesHubPointerProfile.asset
Assets/MRTK/Examples/Experimental/NonNativeKeyboard/Profiles/NonNativeKeyboardMixedRealityInputPointerProfile.asset
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/ConicalGrabPointer.prefab
Assets/MRTK/SDK/Features/UX/Prefabs/Pointers/GrabPointer.prefab
Assets/MRTK/SDK/Profiles/DefaultMixedRealityInputPointerProfile.asset
Assets/MRTK/SDK/Profiles/HoloLens1/DefaultHoloLens1PointerProfile.asset

I found that the pointer profiles could go out of sync if they were reserialized without the inspector open. This change ensures that
1. The pointer itself is the source of truth if there's any serialization present
2. If no serialization is present in the pointer, default to either the global default (if initializing the field for the first time) or to whatever's in the profile serialization
3. If the profile is changed through the inspector, immediately sync the result back to the prefab and save

[2.8] Fix pointer profile layer mask syncing with prefabs

---

Assets/MRTK/SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs

While digging into https://github.com/microsoft/MixedRealityToolkit-Unity/pull/10310, I noticed a couple spots where `GetComponent` on objects _without_ the corresponding component were both costly and caused allocations. Unity 2019 introduced `TryGetComponent`, which helps reduce those side effects.
Before: 
After:

Some minor reworks to use TryGetComponent in every-frame pointer code

---

Assets/MRTK/Examples/Common/Scripts/DemoSpatialMeshHandler.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/WindowsMixedRealitySpatialMeshObserver.cs
Assets/MRTK/Providers/XRSDK/GenericXRSDKSpatialMeshObserver.cs

Adds a null check, in case the GameObject was destroyed before the system is cleaned up.
- Fixes: #10587

Fix null ref when stopping playmode with spatial mapping

---

Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs

Adding a param to the constructor a while back broke the fallback case...
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10200

Add four-param constructor to GenericXRSDKController for fallback

---

Assets/MRTK/SDK/Experimental/SpatialAwareness/SurfaceMeshesToPlanes.cs

The package only contains Windows binaries, so this will prevent builds for other platforms.

Guard planefinding native DLL package calls only to Windows

---

Assets/MRTK/Core/Definitions/Devices/ArticulatedHandDefinition.cs
Assets/MRTK/Core/Providers/Hands/BaseHandVisualizer.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRHandJointProvider.cs
Assets/MRTK/Providers/Windows/WindowsSpeechInputProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Materials/HandJoint.mat
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/FingerCursor.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/ParabolicTeleportPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/PokePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/TouchPointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputModule.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
Assets/MRTK/Tests/PlayModeTests/Core/Providers/Hands/BaseHandVisualizerTests.cs

These traces are using in-editor remoting.
Before:
After:
* Updated several hand joint code paths to prefer arrays over dictionaries
* Cached various `for` loop end conditions, so we don't continually query properties or `Length` or `Count` values
* Cached a handful of `CoreServices` calls in hot loops
* Updated several pointers to return early from `OnPreSceneQuery` if they aren't enabled and their enabled state doesn't depend on work in `OnPreSceneQuery`

Assorted perf improvements in hot code paths

---

Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

`FollowMeToggle` has an `AutoFollowAtDistance` feature which breaks if the `FollowMeToggle` component is ever disabled and re-enabled. This is because the `AutoFollowAtDistance` property setter checks if the `autoFollowDistanceCheck` coroutine is null before starting the coroutine. If the component is disabled, the coroutine will _stop_ but not become null. When the component is re-enabled, the coroutine does not start again because the previous instance is non-null, even though it is no longer running.
This is fixed by simply setting `autoFollowDistanceCheck` to null in `OnDisable()`.
- Fixes: #10619.

Fix FollowMeToggle's auto-follow breaking if the component is disabled

---

Assets/MRTK/Core/Providers/BaseInputDeviceManager.cs

Currently, the pointer uses its parent to spawn its cursor. During the initial creation flow, that logic is hit _before_ we actually put the pointer under the playspace. With this change, the pointer is now put under the playspace immediately at creation, before the cursor is spawned.

Fix cursors spawning at the root on initial source detection

---

Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/SDK/Features/UX/Scripts/Slate/FollowMeToggle.cs

Cherry-picked over two bug-fix PRs that have been merged to main since 2.8.0.
#10620 and #10613

2.8.1 cherry-picks from main

---

Assets/MRTK/Providers/Oculus/XRSDK/Controllers/OculusXRSDKTouchController.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs

The Oculus Controller's Visuals property would not be initialized prior to OnSourceDetected getting raised, despite it behaving differently on other platforms. This change realigns the behavior to match other platforms
- Fixes: #10002

Fixed issue where Controller Visuals weren't initialized before OnSourceDetected

---

Assets/MRTK/Core/Providers/Hands/HandPoseUtils.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/CameraFOVChecker.cs
Assets/MRTK/Core/Utilities/CoreServices.cs
Assets/MRTK/Core/Utilities/MixedRealityServiceRegistry.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs
Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs
Assets/MRTK/SDK/Features/Input/Handlers/ControllerPoseSynchronizer.cs
Assets/MRTK/SDK/Features/Input/Handlers/ObjectManipulator.cs
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/BaseCursor.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/LinePointer.cs
Assets/MRTK/SDK/Features/UX/Scripts/Pointers/SpherePointer.cs
Assets/MRTK/SDK/Features/Utilities/LRUCache.cs
Assets/MRTK/Services/InputSystem/FocusProvider.cs
Assets/MRTK/Tests/PlayModeTests/Core/Utilities/LRUCacheUnitTests.cs
Packages/manifest.json

* Removes some allocations in `CameraFOVChecker`, `ObjectManipulator`, `ObjectManipulator`, and `LRUCache`
* Returns early in `MicrosoftArticulatedHand`, `GenericXRSDKController`, and `FocusProvider` at an earlier point where we know there's no work to be done
* Cache the result of some expensive (at least, when you call them as much as we do) calls in `OpenXRDeviceManager`, `XRSDKDeviceManager`, `BaseCursor`, and `FocusProvider`
* Migrate `XRSDKDeviceManager` to use the `InputDevices` events instead of polling every frame (which can be expensive for this method)
* Update `ControllerPoseSynchronizer` and `FocusProvider` to use `SetPositionAndRotation` in hot loops
* Update `ObjectManipulator` to not update twice per frame when doing two handed manipulation...
* Disable the `LinePointer`'s …

[2.8.1] perf pass

---

Assets/MRTK/Core/AssemblyInfo.cs
Assets/MRTK/Core/AssemblyInfo.cs.meta
Assets/MRTK/Core/Definitions/InputSystem/MixedRealityInputSystemProfile.cs
Assets/MRTK/Core/Definitions/MixedRealityExperienceSettingsProfile.cs
Assets/MRTK/Core/Definitions/MixedRealityToolkitConfigurationProfile.cs
Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs

We mark multiple classes with `[assembly: InternalsVisibleTo(` in the core, so it seems reasonable to refactor that out into a single AssemblyInfo.cs.

Simplify InternalsVisibleTo in Core

---

Assets/MRTK/Core/Utilities/CameraFOVChecker.cs

`ValueType` doesn't exist there 😭

Update CameraFOVChecker.cs to fix .NET build in Unity 2018

---

Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftOpenXRGGVHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftOpenXRGGVHand.cs.meta
Assets/MRTK/Providers/OpenXR/Scripts/OpenXRDeviceManager.cs

Allow HoloLens 2 to act on the "select" keyword in OpenXR by subscribing to `SpatialInteractionManager.SourcePressed`. Follow up & very similar to #10533.
- Fixes: #10604, #10154.

Add support for "select" voice command with OpenXR

---

com.microsoft.mrtk.windowsspeech/Subsystems/WindowsPhraseRecognitionSubsystem.cs

Speech recognition does not work at all because at adding the first keyword, the Update method goes in to an endless Destroy/Start loop because keywordListChanged never gets set to false
Set keywordListChanged to false before starting the Destroy/Start sequence

Fix: Update goes into endless Destroy/Start

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Assets/XR/XRGeneralSettings.asset

1. Enables Oculus Touch controllers on Standalone for Oculus Link
2. Assign the correct OpenXR loader for UWP

Update OpenXR settings

---

com.microsoft.mrtk.uxcore/StateVisualizer/Effects/GraphicTintEffect.cs
com.microsoft.mrtk.uxcore/StateVisualizer/Effects/SpriteTintEffect.cs

Adds nullchecks to tintables. Null tintables and uninitialized tintables list will no longer NRE and break StateViz effects.
For @katie-msft :) 
- Fixes: #10685

Adding nullchecks to tintables

---

Assets/MRTK/SDK/Editor/Inspectors/Utilities/MeshOutline.meta
Assets/MRTK/SDK/Editor/Inspectors/Utilities/MeshOutline/BaseMeshOutlineInspector.cs
Assets/MRTK/SDK/Editor/Inspectors/Utilities/MeshOutline/BaseMeshOutlineInspector.cs.meta

- Fixes: #10657 
Added simple inspector helper for BaseMeshOutline abstract class, 
used in MeshOutline && MeshOutlineHierarchy, (mb in other custom classes)
- check current material settings
- force update material settings to default outline mat settings
- add new correct material
- Inspector for BaseMeshOutline abstract class

Add BaseMeshOutline inspector

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
com.microsoft.mrtk.extendedassets/Models/Piano.prefab
com.microsoft.mrtk.extendedassets/Models/PianoBlackKey.prefab
com.microsoft.mrtk.extendedassets/Models/PianoKey.prefab
com.microsoft.mrtk.uxcomponents/Buttons/128x32/PressableButton_128x32mm_TextOnly.prefab
com.microsoft.mrtk.uxcomponents/Buttons/Canvas/Empty Button.prefab
com.microsoft.mrtk.uxcomponents/Buttons/PressableButton_Custom_Cube.prefab
com.microsoft.mrtk.uxcomponents/Buttons/PressableButton_Custom_Cylinder.prefab

We previously had artificial collider padding on our buttons, as our poke algorithm/heuristic was discrete and required thicker colliders for reliable button presses.
Now that we're using our custom continuous poke heuristic, we can make the colliders on all the pressables "skin-tight" so things like cursor/reticle magnetism and gaze hit tests are more accurate.
- Changes base prefabs for both Canvas and non-Canvas rich buttons
- Changes example prefabs in HandInteractionExample (piano keys, cube/cylinder buttons)

Tuning all colliders on pressables to be "skin-tight"

---

com.microsoft.mrtk.uxcore/StateVisualizer/StateVisualizer.cs
com.microsoft.mrtk.uxcore/Tests/Runtime/StateVisualizerTests.cs

Makes `StateVisualizer` explicitly require an `Animator`. A test is included to verify.
- Fixes: #10693

Stateviz animator fix

---

com.microsoft.mrtk.core/Editor/Inspectors/StatefulInteractableInspector.cs
com.microsoft.mrtk.uxcore/Button/PressableButton.cs

`PressableButton` was squashing `LastHoverExit`s by not calling the base impl.
- This fixes that.
- Also makes the OnEnable/OnDisable events in the inspector not ugly, which was bothering me for a while 🙃

LastHoverExit fix

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json

Update MR OpenXR to 1.4.2
* Fixed a bug where the anchors are located incorrectly after user clear all holograms in user's settings page.
* Fixed a bug where rendering framerate might be dropped due to hand and controller tracking cost.
* Fixed a bug where ARPlanes might be incorrectly reported as updated or removed before they are reported as added.
* Added feature validation to warn developer about missing internet capabilities in appxmanifest for remoting apps.

Update MR OpenXR to 1.4.2

---

com.microsoft.mrtk.uxcore/Editor/Inspectors/FontIconSet/FontIconSelectorInspector.cs
com.microsoft.mrtk.uxcore/FontIcons/FontIconSelector.cs

The FontIconSelector wasn't correctly recording changes to objects when it was updating icons, resulting in broken prefab modifications and all kinds of chaos. Fixes problems associated with #10706.
- Fixes: that.
- Cleans up `FontIconSelector`, adding missing doccomments, etc

Prefab/undo fixes for FontIconSelectorInspector

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityPointerProfileInspector.cs
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs

Added a handful of null checks for `CameraCache.Main` and updated some paths to use existing helper functions. This will help reduce the likelihood of hitting null refs when a camera isn't properly tagged as "main".
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10712

Fix NullReferenceException when opening PointerProfile without main camera in scene

---

Assets/MRTK/Core/Utilities/CameraCache.cs
Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs

Upgrades the "no main camera found, but at least one camera found in the scene" case to an error. There are too many assumptions MRTK would have to make to handle any other case, like auto-tagging existing camera.
Also adds a cache for `IsOpaque` in some hot loops, which can be expensive.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9395 (essentially, at least, by upgrading the log to an error.)

Update CameraCache failure case + perf

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/CanvasExample/HeroShadow.mat

A previous breaking change regarding material blend modes in MRGT broke our `CanvasExample` hero button shadows. This takes advantage of the new alpha gradient feature in MRGT and fixes the shadows.
- Adjusts gradient on `HeroShadow.mat` in sample scene.

Making HeroShadow.mat use new alpha gradient feature

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/BoundsControl/CheeseBoundsControl.prefab
UnityProjects/MRTKDevTemplate/Assets/Prefabs/BoundsControl/CoffeeBoundsControl.prefab
UnityProjects/MRTKDevTemplate/Assets/Prefabs/ObjectManipulator/CheeseObjectManipulator.prefab
UnityProjects/MRTKDevTemplate/Assets/Prefabs/Whiteboard/WhiteboardExample.prefab
UnityProjects/MRTKDevTemplate/Assets/Scenes/BoundsControlExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/InteractableButtonExamples.unity
com.microsoft.mrtk.extendedassets/Models/PianoKey.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab
com.microsoft.mrtk.input/Utilities/PlatformAwarePhysicsRaycaster.cs
com.microsoft.mrtk.input/Utilities/PlatformAwarePhysicsRaycaster.cs.meta
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/RotateHandle.prefab
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/ScaleHandleOcclusion.prefab
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/ScaleHandleTraditional.prefab
com.microsoft.mrtk.uxcomponents/Buttons/128x32/PressableButton_128x32mm_TextOnly.prefab
com.microsoft.mrtk.uxcomponents/Buttons/PressableButton_Custom_Cube.prefab
com.microsoft.mrtk.uxcomponents/Buttons/PressableButton_Custom_Cylinder.prefab
com.microsoft.mrtk.uxcomponents/Slates/Slate.prefab
com.microsoft.mrtk.uxcomponents/Sliders/NonCanvasSliderBase.prefab
com.microsoft.mrtk.uxcore/Interop/UGUIInputAdapter.cs

Makes basic 2D mouse input work out of the box on pancake platforms (web, desktop, etc)
- Adds `PlatformAwarePhysicsRaycaster`, which is a `PhysicsRaycaster` that disables itself on XR platforms for perf
- Bakes the above script into the rig prefab
- Bakes a `CanvasProxyInteractor` into the rig prefab
- Adds `UGUIInputAdapter` to all of our example prefabs and scenes where applicable
- Improves rolloff/cancel support for `UGUIInputAdapter`
- Fixes non-canvas Slider using non-draggable UGUIInputAdapter

Baking mouse support into the rig, by default

---

com.microsoft.mrtk.spatialmanipulation/BoundsControl/BoundsCalculator.cs
com.microsoft.mrtk.spatialmanipulation/Solvers/DirectionalIndicator.cs
com.microsoft.mrtk.spatialmanipulation/Utilities/Solver.cs
com.microsoft.mrtk.spatialmanipulation/Utilities/SolverHandler.cs

Performance review showed that we can reduce some allocs by caching the results using GetComponents(List<T>). This PR also removes a potentially costly Linq call from a fixed update function, reducing risks there.

Caching get component calls and removing hot path risks

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/FontIconExample.unity

Assigned SceneContent object to ObjectManipulator's host transform
- Fixes: #10756

Fix - Icon examples scene has misconfigured+wonky title backplate

---

UnityProjects/MRTKDevTemplate/Assets/XR/Settings/OpenXR Package Settings.asset
com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab

The znear/far on the MRTK Rig prefab was set to **1cm** and **1km**, which is excessive for most MR applications and can lead to Z inaccuracy on our UI sometimes (most visible with our toggle-switches in the sample scenes). This makes nearZ/farZ 2cm to100m.
- Fixes: #10755

Fixes poorly-configured znear/far

---

com.microsoft.mrtk.uxcore/Toggle/ToggleCollection.cs

Toggling `allowSwitchOff` in-editor previously had no effect as the relevant logic was in the public property setter. This resolves that with an `OnValidate` as well as a check in `Start`.
- Fixes #10776

Ensure serialized allowSwitchOff is propagated to all managed interactables

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/VirtualizedScrollRectList/VirtualizedListButton.prefab
UnityProjects/MRTKDevTemplate/Assets/Scenes/VirtualizedScrollRectList.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/ScrollRectCurve.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/ScrollRectCurve.cs.meta
UnityProjects/MRTKDevTemplate/Assets/Scripts/VirtualizedScrollRectListTester.cs

A short script demonstrating curving the content of a ScrollRect. It stands by itself just fine and looks pretty neat, but is perhaps a bit off the beaten path as far as MRTK features go. This is added as a sample script used in the VirtualizedScrollRectList scene.
This PR also includes some small adjustment to the scene's UI to fix clipping and icon issues that drifted in.

ScrollRectCurve example script

---

com.microsoft.mrtk.uxcomponents/Buttons/Canvas/Action Button.prefab

The newly-added SDF icons on the Action Button prefab were using the non-Canvas TMPro objects, which caused severe problems with masking + clipping.
- Changes `ActionButton.prefab` to use `TextMeshPro Text (UI)` and replacing `MeshRenderer` with `CanvasRenderer`

Fixing Action Button prefab to use TextMeshPro UI text instead of Mesh text

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioLoFiExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/Audio/AudioOcclusionExample.unity
com.microsoft.mrtk.audio/Effects/AudioInfluencerController.cs

This change brings improvements to the audio effect sample scenes.
1. Enable 'Spatialize Post Effects' (in both example scenes) to ensure that the effects are properly applied when using an Audio Spatializer
2. Lo-Fi example: Adapt to changes in the button bar prefab (a text icon was added that was obscuring the button text)
3. Simplify AudioInfluencerController - the script is designed to be placed on each emitter so we will always get the audio source from the attached game object.

[MRTK3] Fix audio sample scenes, some script simplification

---

com.microsoft.mrtk.spatialmanipulation/BoundsControl/BoundsHandleInteractable.cs
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Visuals/SqueezableBoxVisuals.cs

We tell people to subclass `BoundsHandleInteractable` to make new/custom bounds handles. Unfortunately, it's `internal`! Oops. This fixes that.
In addition, it adds a requested feature to allow users to customize the maintain-global-size behavior. (Some folks like their handles thicc)
- Makes `BoundsHandleInteractable` public
- Adds `MaintainGlobalSize` setting to `BoundsHandleInteractable`
- Removes unused properties from `SqueezableBoxVisuals`

Make BoundsHandleInteractable public

---

com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractor.cs

This extends the polyfill from #10749 to also cover the tracking state. This resolves several... oddities that happened as a result of that PR.
- Fixes: #10821 
- Polyfills tracking state when joints are available but no position action is bound
- Ensures MRTKRayInteractor can't select when the controller isn't tracked

Polyfilling tracking state

---

Assets/MRTK/Core/Interfaces/Devices/IMixedRealityHand.cs
Assets/MRTK/Core/Providers/Hands/BaseHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHand.cs
Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs

There is a timing when the hand controller is already tracked and provides a position, though no joint data is available yet. I.e. when you move hands quickly into the HL2 tracking view. This results in the hand mesh being rendered already, while the joint data hasn't been set and the mesh is stuck at origin.
This change will now make sure the hand mesh is only rendered when there is actual joint data available.
- Fixes: #10646

Fix flashing RiggedHandMesh

---

Assets/MRTK/Core/Interfaces/Devices/IMixedRealityHand.cs
Assets/MRTK/Core/Providers/Hands/BaseHand.cs
Assets/MRTK/Core/Providers/InputSimulation/SimulatedHand.cs
Assets/MRTK/Providers/LeapMotion/LeapMotionArticulatedHand.cs
Assets/MRTK/Providers/Oculus/XRSDK/MRTK-Quest/Scripts/Input/Controllers/OculusHand.cs
Assets/MRTK/Providers/OpenXR/Scripts/MicrosoftArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XR2018/Controllers/WindowsMixedRealityArticulatedHand.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/Controllers/WindowsMixedRealityXRSDKArticulatedHand.cs
Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs

Follow-up to #10754. At this point in MRTK2's lifecycle, we're trying to avoid breaking changes, especially to interfaces that might be implemented in any number of other projects.
This PR reverts the breaking change and updates the rigged hand logic to render if the palm joint is accessible.
I also added some `#if`s that I should have added a while back, since I was in this code anyway.

Update rigged hand mesh flicker bug fix to not be a breaking interface change

---

com.microsoft.mrtk.input/Assets/Prefabs/MRTK Hand Controller.prefab
com.microsoft.mrtk.input/Interactors/InteractorVisuals/ReticleMagnetism.cs

This fixes an awkward poke reticle lerping bug on devices without an input action for position/rotation, and finally removes the "dev art" blue sphere for grabs ("MRTK2 parity" haha)
- Fixes the poke reticle "zooming" back into place after the IMM switches the `PokeInteractor` back on, on devices like Quest
- Burninates the blue sphere

Poke reticle bugfix, burninate the blue sphere

---

com.microsoft.mrtk.uxcore/Interop/UGUIInputAdapter.cs

#10838 exposed an assumption in CanvasProxyInteractor that wasn't well-tested. `UGUIInputAdapter` assumed that a proxy interactor would stay registered throughout its lifetime, which #10838 made untrue.
Now, we nullcheck proxy interactors in the `UGUIInputAdapter`, as well as reducing the work done when referencing the `ProxyInteractor` getter while no proxy interactor is actually available. Before, it would re-query the list of all interactors from the manager every single time the getter was called while no interactor was available. Now, it grabs the interactor reference once at `Awake`, and then re-grabs it subsequently on each registration event.
- Fixes #10872
- Fixes #10740 , as we now gracefully avoid NREs when no proxy interactor is available.

Fixes for NREs in CanvasProxyInteractor

---

com.microsoft.mrtk.tools/SubsystemWizard/SubsystemWizardWindow.cs

This change fixes a reference to "Company name" that was missed in the previous checkin. Now uses "Organization name" in the UI.

ui polish: company name -> organization name

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/CanvasUITearsheet.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/ObjectBarExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/SpatialMappingExample.unity
com.microsoft.mrtk.core/Interactors/IModeManagedInteractor.cs
com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab

The MRTK Rig had an error introduced into it where the near mode detector had a null object set as a managed controller. This PR also cleans up several scenes which had leftover CanvasProxyInteractors in the scene. The CanvasProxyInteractor is now automatically included in the MRTK rig.
This PR also fixes some other instances in the examples where there were unnecessary overrides placed on the base MRTK rig.
It also adds a missing license header to a class.
- Fixes: #10882

Fixed errors introduced to the XR Rig. Cleaned up some scene overrides. Added missing license header

---

com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs

The hand ray fallback in the hand controller was getting its reference spaces all mixed up. This fixes that!
Suggestion: we should add a random rig offset to all of our sample scenes, plus start testing locomotion/teleport :) 
- Fixes #10847

[pre.10 blocker] Fixing ray coordinate space in controller

---

README.md

It currently points to the old, no longer in use pipeline: 
This now points to the GitHub action for docs validation:

Update docs pipeline status badge on README

---

pipelines/docs-binaries.yml

Looks like a change went into the VM image we use for docs generation that's causing things to break.
This reverts to an LFG image that we already use for MRTK2 CI.
I'll have a follow up investigation to get us back on the latest VMs, but this is at least a quick unblocker (hopefully!).

Fix docs pipeline

---

com.microsoft.mrtk.core/Editor/Inspectors/PropertyDrawers/InterfaceSelectorDrawer.cs
com.microsoft.mrtk.core/Utilities/Attributes/InterfaceSelectorAttribute.cs

I hit an issue where `InterfaceSelector` was displaying an abstract class to me but throwing an exception when I tried to select it.
This converts the type lookup to use Unity's performant `TypeCache` as well as filtering out uninstantiatable types, like abstract classes and interfaces.

Update InterfaceSelector to use Unity TypeCache and filter out uninstantiatable types

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
com.microsoft.mrtk.spatialmanipulation/ObjectManipulator/ObjectManipulator.cs

ObjManip had a bug wherein it would corrupt the physics settings on objects by recording the "previous settings" *during* a multihanded interaction. This fixes that bug.
In addition, our rigidbodies in the HIE sample scene had unrealistically configured weights, as well as no interpolation settings, which was causing unreliable interactions as well as jittery manipulations when the display refresh rate != physics tickrate.
Lastly, the sample rigidbodies had some very wonky collider setups, too. This resolves those.
- Fixes #10894 
- Fixes #10883 
- Fixes jittery manipulations/framerate problems
- Some clarity edits to labels in the scene
- Fixes wonky colliders

Physics fixes

---

com.microsoft.mrtk.uxcomponents/Buttons/Canvas/Action Button.prefab

The font icon wasn't referenced in the Disabled effect on our buttons, plus the transition time was incorrect.
- Adds font icon reference to StateViz in `Action Button`
- Fixes transition time

Fixing incorrect transition time + missing font icon reference

---

.github/workflows/issue_labeler.yaml
.github/workflows/pr_labeler.yaml

This cherrypicks a few commits from the mrtk3 branch to bring the CI autolabeler actions over to our "default" branch.

Porting auto-labeler CI actions from mrtk3 branch

---

com.microsoft.mrtk.input/Simulation/Devices/SimulatedEyeGaze.cs
com.microsoft.mrtk.input/Simulation/InputSimulator.cs

There's a fun quirk with the Unity input system when two types of the same name are registered. And unfortunately, both the Input System and Unity's OpenXR package _both_ register types of `PoseControl`. This causes one of the types (often the Input System's, since the OpenXR package has a bit of a delayed registration logic) to be overwritten by the other.
To work around this, we added an explicit re-registration of the Input System type with a _different_ identifying name, so the input system sees this as two separate types.
Unfortunately, something in Unity's rebinding logic sees these two controls as the same, even though the Input System itself sees them as unique. Therefore, when OpenXR registers its control while the simulated eye gaze is registered (which happens basically always …

Fix eye gaze simulation when XR isn't enabled

---

UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectVersion.txt
com.microsoft.mrtk.accessibility/package.json
com.microsoft.mrtk.core/package.json
com.microsoft.mrtk.input/package.json
com.microsoft.mrtk.spatialmanipulation/package.json
com.microsoft.mrtk.standardassets/package.json
com.microsoft.mrtk.uxcore/package.json

This change updates to the v2.0.3 of the Unity XRI package plus the following changes:
* Sync all references to xr.core-utilities to v 2.1.0-pre.1 (previously adopted by the core defs packages)
* MRGT 0.3.15 -> 0.4.0 (latest published package)
* Ensure all XRI package references are 2.0.3
* Update to the latest Unity 2020.3 LTS (38f1)

Dependency updates in package manifests

---

CODEOWNERS

This change adds and initial set of code owners (subject to review and change) to help specify the most appropriate MRTK team PR reviewers.

add code owners file to help route PR feedback requests

---

UnityProjects/MRTKDevTemplate/Assets/MRTK.Generated/MRTKSettings.asset
com.microsoft.mrtk.core/Editor/MRTKBuildPreferences.cs
com.microsoft.mrtk.core/Editor/MRTKBuildPreferences.cs.meta
com.microsoft.mrtk.core/Editor/MRTKBuildProcessor.cs
com.microsoft.mrtk.core/Editor/MRTKSettings.cs

Adds the ability to set a 3D app launcher model for WMR UWP.
https://docs.microsoft.com/en-us/windows/mixed-reality/distribute/creating-3d-models-for-use-in-the-windows-mixed-reality-home
The settings can be found under Project Settings -> MRTK3 -> Build Settings
Works great with #10923 🥳
- Fixes: #10929

Add 3D app icon setting for UWP

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitInspector.cs

- Fixes: #10720
Fixed micro issue with MixedRealityToolkit Inspector
Issue: error stack when we have active MixedRealityToolkit Inspector in editor and active profile is changed
- OnInspectorGUI method in MixedRealityToolkitInspector.cs

Update OnInspectorGUI for Toolkit Inspector

---

Assets/MRTK/Core/Attributes/MixedRealityExtensionServiceAttribute.cs
Assets/MRTK/Core/Definitions/Devices/ControllerMappingLibrary.cs
Assets/MRTK/Core/Definitions/Utilities/ArticulatedHandPose.cs
Assets/MRTK/Core/Inspectors/ControllerPopupWindow.cs
Assets/MRTK/Core/Utilities/Editor/EditorProjectUtilities.cs
Assets/MRTK/Tests/PlayModeTests/Core/Utilities/LRUCacheUnitTests.cs.meta
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs
Assets/MRTK/Tools/ExtensionServiceCreator/ExtensionServiceCreator.cs

MixedRealityToolkitFiles has always had some issues around Assets vs Packages, relative vs absolute, and some less-standard forms of referencing MRTK2.
This PR moves away from most of the more problematic cases for in-MRTK code to use Unity's `AssetDatabase` APIs instead.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/4904

Move some codepaths away from MixedRealityToolkitFiles

---

com.microsoft.mrtk.core/Utilities/CameraFOVChecker.cs
com.microsoft.mrtk.core/Utilities/CameraFOVChecker.cs.meta

This change adds the CameraFOVChecker script from MRTK2 into the core definitions package. While the logic is unchanged, some minor comment / formatting changes have been made.
Although this script will initially be used by the accessibility package, it has additional applications (ex: determining if a tracked hand is visible).

CameraFOVChecker from MRTK2

---

com.microsoft.mrtk.input/Utilities/FollowJoint.cs

Using the `OnAfterDeserialize` callback for migration seems a bit more reliable, since `OnValidate` is hooked specifically to the inspector. This pattern follows what some Unity-written components do to ensure version migration.

Update FollowJoint to use serialization callbacks for migration

---

com.microsoft.mrtk.uxcomponents.noncanvas/package.json

The location of this package in the UPM UI is slightly misaligned contextually
from this
to this

Update Non-canvas package display name for UPM alphabetical ordering

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/HandInteractionExamples.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/MagicWindowExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/MagicWindowExample.unity.meta

Based on our official recommendations for 16-bit depth for performance, separate the magic window example out of the HandInteractionExamples scene. Created 'MagicWindowExamples' scene.
Left MRTK logo object with touch rotation example in the HandInteractionExamples scene. (without magic window effect)
- Fixes: #10971

[MRTK3] Separate the magic window example out of the HandInteractionExamples scene

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/MagicWindow/MagicWindowExample.prefab

Removes a disabled collider and explicitly assigns two colliders to interactables to prevent the need for the scene search for colliders, which was picking up the same collider twice.
Fixes

Remove unused collider and add explicit references to Magic Window prefab

---

com.microsoft.mrtk.input/Assets/Prefabs/MRTK Hand Controller.prefab

It was set to `Translate Anchor` instead of `Tracking State`
to

Update tracking state mapping for base hand controller prefab

---

com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractor.cs
com.microsoft.mrtk.input/Interactors/Ray/MRTKRayInteractorVisual.cs

`DevicePoseSource` already return its pose with PlayspaceUtilities.ReferenceTransform.rotation applied
https://github.com/microsoft/MixedRealityToolkit-Unity/blob/46fd40f0b88ae03810187447b2e1becac47a963a/com.microsoft.mrtk.input/Utilities/PoseSource/InputActionPoseSource.cs#L42-L43

Remove duplicate PlayspaceUtilities.ReferenceTransform.rotation application

---

com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs
com.microsoft.mrtk.input/Controllers/ArticulatedHandControllerState.cs

Follow up to #10897. Adds an additional obsolete attribute to an `internal` class to further dissuade usage of this PinchPose.

Further obsolete ArticulatedHandController's PinchPose

---

com.microsoft.mrtk.input/Subsystems/Hands/OpenXRHandsSubsystem.cs
com.microsoft.mrtk.input/Subsystems/Hands/XRSDKHandsSubsystem.cs
com.microsoft.mrtk.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
com.microsoft.mrtk.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs

Updates the lifecycle of the hands subsystems to be more consistent and predictable with the input system's update cycle.
(Potentially) fixes an issue where hand joints couldn't be queried the same frame a hand was detected.

Improve reset logic for hand data

---

Pipelines/Scripts/publish-upm.ps1

Update publish-upm.ps1 to use the command suggested by ADO. I ran into a 404 error stating "The package 'vsts-npm-auth' was not found in feed 'my-feed'".

Explicitly specify registry in npm install

---

com.microsoft.mrtk.uxcomponents.noncanvas/HandMenu/HandMenu2x4.prefab
com.microsoft.mrtk.uxcomponents.noncanvas/NearMenu/NearMenu4x2.prefab

HandMenu & NearMenu prefabs were using CanvasBackplate.mat from the MRGT package which was not updated to Linear color space. Assigned CanvasBackplate.mat from the StandardAssets package.
(Pin button was already using the correct material)
We are going to need to document this difference + update MRGT one to avoid confusion.
- Fixes: #11008

[MRTK3] Updated HandMenu & NearMenu prefabs to use CanvasBackplate.mat in the  StandardAssets package

---

com.microsoft.mrtk.uxcomponents.noncanvas/HandMenu/HandMenu2x4.prefab
com.microsoft.mrtk.uxcomponents.noncanvas/NearMenu/NearMenu4x2.prefab

The backplate radius was updated to match the tearsheet version.

[MRTK3] Near menu & Hand menu - backplate radius update

---

com.microsoft.mrtk.core/Interactable/StatefulInteractable.cs

Adds a single-arg overload to ForceSetToggled, so that it can be invoked from a UnityEvent. Based on discussion with Matt R and Matt F, the single-arg overload _will_ invoke toggle events.
- Fixes #11006

Adding single-arg overload to ForceSetToggled for UnityEvents

---

Assets/MRTK/SDK/Features/UX/Interactable/Scripts/Interactable.cs
Assets/MRTK/SDK/Features/UX/Scripts/Cursors/BaseCursor.cs

Fixed the NullReferenceException that occurs when using the TouchPointer on mobile devices (MRTK 2.8.2).
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/10771.

Fix TouchPointer NullReferenceException

---

com.microsoft.mrtk.input/Interactors/GazePinch/GazePinchInteractor.cs

GazePinch had been broken since #10787 , which had subtly altered the calculations for gazepinch interactions. This broke sliders + made rotation manipulations unreliable.
- Fixes: #11055 
There are still more math errors throughout; #11035 will fix the rest of them.

Fixing GazePinch calculations

---

com.microsoft.mrtk.input/Interactors/Gaze/FuzzyGazeInteractor.cs
com.microsoft.mrtk.input/Interactors/Gaze/GazeInteractor.cs

This was quite the rabbit hole. The original symptom was "Can't gazepinch Sliders in simulation!" The cause was:
- FuzzyGaze hits Slider, adds to ValidTargets
- GazePinch gets ValidTargets from FuzzyGaze
- GazePinch initiates selection on Slider
- < next frame >
- FuzzyGaze hits Slider, but IsSelectableBy() _**fails**_, because Slider rejects all incoming selections after the first selection
- FuzzyGaze no longer has Slider in ValidTargets
- GazePinch gets ValidTargets from FuzzyGaze
- Slider is no longer in ValidTargets, GazePinch drops selection
Solution: For some reason FuzzyGaze was checking to see if each interactable was actually _selectable_ when evaluating whether it was a valid hit or not. The fix is to make FuzzyGaze only check to see if the interactable is _hoverable_.

Fixing FuzzyGaze being too "shy"

---

com.microsoft.mrtk.core/Interactables/MRTKBaseInteractable.cs

This `private HashSet` property wasn't actually used anywhere except to fill it. The `private List` field is used instead, so this removal simplifies the script a bit.

Remove unused DisabledInteractorTypes

---

com.microsoft.mrtk.spatialmanipulation/BoundsControl/Visuals/SqueezableBoxVisuals.cs

An old bug #10686 requested that `SqueezableBoxVisuals` allow for no box renderer at all. Turns out we were 99% of the way there already, just needed a nullcheck. Note, `unpinchScaleOffset` and `pinchScaleOffset` default to `Vector3.zero` which is the correct value.
- Fixes #10686

Changing SqueezableBoxVisuals to allow no box renderer

---

Assets/MRTK/Providers/XRSDK/Controllers/GenericXRSDKController.cs

The touch bindings from Unity's `CommonUsages` were missing from `GenericXRSDKController`.
- Fixes: [#10486 
](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11019)

Add missing mappings for Quest Touch controller "touch" bindings

---

com.microsoft.mrtk.accessibility/Tests/Runtime/DescribableObjectTests.cs
com.microsoft.mrtk.input/Simulation/Devices/SimulatedController.cs
com.microsoft.mrtk.input/Tests/Runtime/BasicInputTests.cs
com.microsoft.mrtk.input/Tests/Runtime/FuzzyGazeInteractorTests.cs
com.microsoft.mrtk.input/Tests/Runtime/InteractionModeManagerTests.cs
com.microsoft.mrtk.input/Tests/Runtime/InteractorDwellManagerTests.cs
com.microsoft.mrtk.input/Tests/Runtime/MRTK.Input.RuntimeTests.asmdef
com.microsoft.mrtk.input/Tests/Runtime/Utilities/BaseRuntimeInputTests.cs
com.microsoft.mrtk.input/Tests/Runtime/Utilities/InputTestUtilities.cs
com.microsoft.mrtk.input/Tests/Runtime/Utilities/TestController.cs
com.microsoft.mrtk.input/Tests/Runtime/Utilities/TestHand.cs
com.microsoft.mrtk.input/Utilities/HandRay.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/BoundsControlTests.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/ObjectManipulatorTests.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/TransformViaInteractorTests.cs
com.microsoft.mrtk.uxcore/Tests/Runtime/StateVisualizerTests.cs

There's been some test rot over the past week or so. We're working on getting PRs blocking on failing unit tests so this doesn't keep happening in #11027.
- `DescribableObjectTests` were duplicating the rig setup, causing subsequent tests in other packages to fail, introduced in #11021 , tracked here #11119
- Removed aliased `System.Collections.Generic` namespace in `DescribableObjectTests`
- Absolute world-space object placements in unit tests would fail when they required gaze, because the user (even in unit tests) is now 1.6m tall #11120
- Ray aiming broke due to changes in how the simulator/test harness computed hand rays from hand joints. Now, all unit tests direct the simulated controllers to `useRayVector = false`, which causes the `pointerRotation == deviceRotation` , tracked by …

Fixing tests, again

---

com.microsoft.mrtk.input/Subsystems/SyntheticHands/SyntheticHandsSubsystem.cs
com.microsoft.mrtk.input/Visualizers/ControllerVisualizer/ControllerVisualizer.cs

XRI has a helper for only controlling the lifecycle of directly serialized actions, leaving action references to be controlled by their source (in most cases, an Input Action Asset filled with mappings).
```c#
/// <remarks>
/// This can make it easier to allow the enabled state of the <see cref="InputAction"/> serialized with
/// a <see cref="MonoBehaviour"/> to be owned by the behavior itself, but let a reference type be managed
/// elsewhere.
/// </remarks>
```

Update to ControllerVisualizer.cs to only control the lifecycle of direct actions

---

Assets/MRTK/Services/InputSystem/FocusProvider.cs

Prevents non-gaze pointers from overwriting the GazeTarget information in GazeProvider
- Fixes: #11145

Fix for GazeTarget getting overwritten by non-gaze pointers

---

UnityProjects/MRTKDevTemplate/Assets/XRI/Settings/Resources/InteractionLayerSettings.asset
UnityProjects/MRTKDevTemplate/Packages/manifest.json
UnityProjects/MRTKDevTemplate/Packages/packages-lock.json
com.microsoft.mrtk.core/package.json
com.microsoft.mrtk.input/package.json
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/ObjectManipulatorTests.cs
com.microsoft.mrtk.spatialmanipulation/package.json
com.microsoft.mrtk.uxcore/package.json

This PR bumps our XRI version to 2.2. We are doing this to keep up with the new API additions such as GrabTransformers
https://docs.unity3d.com/Packages/com.unity.xr.interaction.toolkit@2.2/manual/whats-new-2.2.0.html
Some tests and settings updated to be less flakey and clean up some of our warnings.

Upgrading XRI to 2.2

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs

Although parsing the folder names is still not the most robust, this is the most straight forward fix for now unless (until?) we rethink this log entirely.
- Fixes: #11124

Update build logic for finding sdk

---

com.microsoft.mrtk.core/Editor/Inspectors/PropertyDrawers/InterfaceSelectorDrawer.cs
com.microsoft.mrtk.input/Assets/Prefabs/MRTK Gaze Controller.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK Hand Controller.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK LeftHand Controller.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK RightHand Controller.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab
com.microsoft.mrtk.input/Utilities/PoseSource/FallbackCompositePoseSource.cs

A less breaking version of #11182
Updates `InterfaceSelectorDrawer` to account for the type being an array or a list and properly extracting out the type for the dropdown

Update InterfaceSelector to work with arrays/lists

---

.gitignore
Assets/MRTK/Providers/OpenXR/Editor/OpenXRCameraSettingsProfileInspector.cs

#11127 broke the Unity 2020 docs build, but it's unclear exactly why. This is an attempt to fix.

Fix the docs build

---

Assets/MRTK/Core/Utilities/Async/AwaiterExtensions.cs

As Unity 2023.1 introduces await support for many constructs (including AsyncOperation), the package is running into compilation issues where there are ambiguous method calls when trying to resolve GetAwaiter method.
This PR makes disambiguate them by conditionally compile GetAwaiter extension methods depending on Unity Version
- Fixes: #11171
I would be feeling much better about this PR if the CI ran tests with 2023.1 (2023.1.0a17 is publicly available and has the Awaitable support). There has been other API deprecations that may impact the package as well in addition to this.

Don't introduce GetAwaiter extension methods conflicting with Unity's Awaitable in 2023.1+

---

com.microsoft.mrtk.core/Editor/Inspectors/PropertyDrawers/DrawIfPropertyDrawer.cs
com.microsoft.mrtk.core/Editor/Inspectors/PropertyDrawers/VariableRangeAttributeDrawer.cs
com.microsoft.mrtk.core/Editor/Inspectors/PropertyDrawers/VariableRangeAttributeDrawer.cs.meta
com.microsoft.mrtk.core/Utilities/Attributes/VariableRangeAttribute.cs
com.microsoft.mrtk.core/Utilities/Attributes/VariableRangeAttribute.cs.meta
com.microsoft.mrtk.uxcore/Slider/Slider.cs
com.microsoft.mrtk.uxcore/Slider/Visuals/CanvasSliderVisuals.cs
com.microsoft.mrtk.uxcore/Slider/Visuals/SliderVisuals.cs

This PR allows for min and max values to be defined for the slider and adds corresponding helpful inspector UI.
This also adds `NormalizedSliderValue` to accomodate for `SliderValue` no longer always being a normalized value between 0 and 1
- Fixes: #10803

Allow for custom min and max ranges for sliders

---

com.microsoft.mrtk.core/Editor/MRTKProfileInspector.cs
com.microsoft.mrtk.core/Editor/MRTKSettingsEditor.cs
com.microsoft.mrtk.core/Utilities/XRSubsystemHelpers.cs

Unfortunately, when consuming MRTK via tarballs, Unity's asset picker doesn't include assets from immutable folders...
This change adds a button to the MRTK Profile inspector to auto-populate the field with the default profile that we ship
I also changed some asserts to full `if`/`log`s to prevent null refs and changed a class from `internal` to `private` to better fit its usage.

Add button to populate the profile field with the MRTK default

---

Assets/MRTK/Core/Providers/UnityInput/UnityJoystickManager.cs
Assets/MRTK/Core/Providers/UnityInput/UnityTouchDeviceManager.cs
Assets/MRTK/Providers/OpenXR/Scripts/OpenXREyeGazeDataProvider.cs
Assets/MRTK/Providers/XRSDK/XRSDKDeviceManager.cs

I found that the logs were actually coming from the "not" running Windows XR Plugin device manager, since these collections are shared between instances of XRSDKDeviceManager. Updates all local collections in device managers to no longer be `static` to fix this issue.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11265

Don't share controller and source collections between instances

---

Assets/MRTK/SDK/Features/UX/Scripts/RiggedHandVisualizer/RiggedHandVisualizer.cs
Assets/MRTK/SDK/Profiles/ObsoleteMixedRealityXRSDKControllerVisualizationProfile.asset

This PR updates the rigged hands logic to not display when a transparent display is used, like over remoting. We'd been getting reports of rigged hands not aligning well with the physical hands and causing confusion.
This also fixes some potential null refs when the rigged hand material isn't set.
This also simplifies one of the controller visualization profiles that wasn't using "both" handedness for certain entries.
This also includes some like formatting and style updates for simplification.

Fix rigged hands in remoting

---

Assets/MRTK/Providers/OpenXR/MRTK.OpenXR.asmdef
Assets/MRTK/Providers/OpenXR/Scripts/OpenXREyeGazeDataProvider.cs
Assets/MRTK/Providers/WindowsMixedReality/XRSDK/WindowsMixedRealityEyeGazeDataProvider.cs

This change properly queries the runtime for the calibration status instead of keying off the eye data availability.
- Fixes: #10887

Expose eye calibration state when using XR SDK

---

Assets/MRTK/Core/Providers/InputSimulation/SimulatedMotionController.cs

Simulated motion controller grab wasn't working in Editor, because it raised a float input event instead of a boolean.
This PR fixes this, by changing the input event to boolean, like the simulated grab for articulated hands.
Create a new scene with the MRTK rig. Make sure to use profiles that use the Motion Controller Simulation Mode (Input -> Input Data Providers -> Input Simulation Service -> Default Controller Simulation Mode: `Motion Controller`)
Add a simple cube to the scene with an `Object Manipulator` with disabled far manipulation and a `NearInteractionGrabbable`. In Play Mode, use either the left or right controller and the mapped grab key (Default `G`) to grab and move the cube.

Fix simulated motion controller grab

---

com.microsoft.mrtk.uxcomponents.noncanvas/Button/128x32/PressableButton_128x32mm_TextOnly.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/Empty Button.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/PressableButton_Custom_Cube.prefab
com.microsoft.mrtk.uxcomponents/Button/Prefabs/PressableButton_Custom_Cylinder.prefab
com.microsoft.mrtk.uxcomponents/NearMenu/NearMenuBase.prefab

This change adds the ConfigureSpatializationSettings script to the root prefabs in the uxcomponents packages.
This change does not _yet_ adjust the default roll-off curve settings for these prefabs. That will be the focus of part 3.

Audio spatializer support part 2:  add configuration script to root prefabs

---

Pipelines/Templates/Tasks/build-appx.yaml
Pipelines/Templates/unity.yaml
UnityProjects/MRTKDevTemplate/Assets/BuildAssets/IconBlackBackground.png.meta
com.microsoft.mrtk.windowsspeech/Subsystems/TextToSpeech/WindowsTextToSpeechSubsystem.cs

Fixes `D:\a\_work\1\s\MixedRealityToolkit-Unity\com.microsoft.mrtk.windowsspeech\Subsystems\TextToSpeech\WindowsTextToSpeechSubsystem.cs(162,35): error CS0411: The type arguments for method 'Task.FromResult<TResult>(TResult)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`.
Also fixes `Compressed texture IconBlackBackground is used as icon. This might compromise visual quality of the final image. Uncompressed format might be considered as better import option.`
Also fixes an issue where some artifacts were being inadvertantly published multiple times.

Fix Android build and multiple artifact publication

---

com.microsoft.mrtk.core/Utilities/ColorUtilities.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/MRTKLineVisual.cs

Over long distances, the gradient applied to the ray interactor can become near invisible or jarring because it is applied uniformly across the entire length of the ray. In cases where the ray stretches out for very long distances, this is undesirable.
This PR introduces a tunable parameter which allows users to specify a maximum length that the gradient can be applied over. The actual distance that the gradient is applied over is relative to the maxRaycast distance of the ray interactor.

Added parameter to tune the gradient's max length

---

com.microsoft.mrtk.core/Subsystems/Hands/HandsAggregatorSubsystem.cs
com.microsoft.mrtk.core/Subsystems/Hands/IHandsAggregatorSubsystem.cs
com.microsoft.mrtk.core/Utilities/TrackedHandJoint.cs
com.microsoft.mrtk.input/Controllers/ArticulatedHandController.cs
com.microsoft.mrtk.input/Controllers/ArticulatedHandControllerState.cs
com.microsoft.mrtk.input/InteractionModes/InteractionModeDefinition.cs
com.microsoft.mrtk.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/MinMaxScaleConstraint.cs
com.microsoft.mrtk.spatialmanipulation/Constraints/TransformConstraint.cs

This PR burninates any API surface that was marked obsolete at least 5 months ago. Does _not_ include some of the more recent playspace/rig/transformation API changes, and also doesn't include some of the more recent PoseSource changes.
- Deletes obsolete `TryGetHandCenter` from the hands API
- Deletes obsolete joint names from `TrackedHandJoint`
- Deletes obsolete `PinchSelectProgress` and `PinchSelectPose` from `ArticulatedHandController`
- Deletes obsolete `PinchPose` state from `ArticulatedHandControllerState`
- Deletes obsolete `IsEnabled` and `Id` properties from `InteractionModeDefinition`
- Deletes obsolete `ScaleMinimum` and `ScaleMaximum` properties from `MinMaxScaleConstraint` (legacy)
- Deletes obsolete field `worldPoseOnManipulationStart` and obsolete method `Initialize` from …

Burninate obsolete API surface >= 5mo old

---

com.microsoft.mrtk.input/Assets/Prefabs/MRTK LeftHand Controller.prefab
com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab
com.microsoft.mrtk.input/Utilities/PlatformAwarePhysicsRaycaster.cs

Quick fix for #11321: this PR Moves NearInteractionModeDetector and `GrabInteractor`'s attach transform onto the "Ignore Raycast" layer.
It also updates the `PlatformAwarePhysicsRaycaster` on the MRTK XR Rig to ignore that layer by default.
- Fixes: #11321

Update raycast layers on NearInteractionModeDetector and GrabInteractor

---

com.microsoft.mrtk.input/Visualizers/RiggedHandVisualizer/RiggedHand-InvertedShell.mat
com.microsoft.mrtk.input/Visualizers/RiggedHandVisualizer/RiggedHand-Main.mat

We never updated the rigged hand materials for Linear colorspace. This resulted in materials that were too bright vs the original intent.
Before vs After
Quest Shell vs MRTK3
Some inconsistencies are due to differences in Unity editor screenshot vs Quest in-HMD screenshot. Don't really know why.
- Tweaks illumination + base color
- Makes outline thickness ever so slightly thicker

Updated hand materials for Linear colorspace

---

com.microsoft.mrtk.accessibility/AssemblyInfo.cs

While working on breaking change detection, I discovered that the accessibility package had the wrong assembly version number (3.0.0 vs 1.0.0).
This change fixes that :smile:

Fix assembly version to match file/package

---

com.microsoft.mrtk.accessibility/Editor/AssemblyInfo.cs

Fixed an incorrect assembly version in the accessibility editor assembly, It was 3.0 when it should have been 1.0.
This should be the last remaining incorrect version in the current mrtk3 branch,

fix assembly version (accessibility editor was 3.0 instead of 1.0)

---

Assets/MRTK/Core/Inspectors/Profiles/MixedRealityInputActionRulesInspector.cs
Assets/MRTK/Core/Inspectors/PropertyDrawers/MixedRealityPosePropertyDrawer.cs
Assets/MRTK/Core/Inspectors/Utilities/Lines/DataProviders/EllipseLineDataProviderInspector.cs

Another found branch. Updates some editor code paths to use the built-in `EditorGUI.IndentLevelScope()` instead of managing indentation manually.

Change to use IndentLevelScope

---

Assets/MRTK/Services/CameraSystem/MixedRealityCameraSystem.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs

Another branch from a couple of years ago. Updates some MRTK logs to be more clear on the full component type being registered, as well as adding a new log for the camera system.
By default, these changes won't add any additional logging. It's only if you change the MRTK logging setting to "Verbose" that you'll start to see a difference.

A couple changes to help with logging

---

Assets/MRTK/Core/Utilities/BuildAndDeploy/MixedRealityBuildPreferences.cs
Assets/MRTK/Core/Utilities/Editor/Preferences/MixedRealityProjectPreferences.cs

When other loaders (like trilib or glTFast) are imported and the MRTK glTF loader is disabled, the 3D app launcher field becomes confusing and rejects all models. This was an artificial limitation, as there's no real dependency on the MRTK glTF loader.
This PR updates the field to be more in line with the MRTK3 version, allowing for arbitrary .glb files regardless of the Unity importer.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9592

Update the asset selector to allow arbitrary glb files regardless of loader

---

com.microsoft.mrtk.spatialmanipulation/Solvers/SolverHandler.cs

There was a minor typo in a previous revision to the Solver base class that would cause it to not be able to track the right hand.
In addition, "correctly" implementing IsHandTracked in SolverHandler actually broke it (in #11333) so this reverts that. Not sure what the root cause is.
- Fixes typo
- Reverts the IsHandTracked change from #11333
Hand menus should work correctly now.

[pre.14 build call] Fixing typo + reverting earlier change that broke hand constraints

---

com.microsoft.mrtk.input/Interactors/Poke/PokeInteractor.cs
com.microsoft.mrtk.input/Simulation/Devices/SimulatedController.cs

A few lingering missing nullchecks.
Also, fixes some deprecated usage introduced in a simultaneous PR #11372 .
- Addendum to #11333

Adding some missing nullchecks from the previous #11333

---

com.microsoft.mrtk.core/Editor/Editors/StatefulInteractableEditor.cs
com.microsoft.mrtk.core/Interactables/StatefulInteractable.cs

Added a (default false) "RequiresHover" field to StatefulInteractable, of which the only inheritor in the package is PressableButton. Setting this field to true (through inspector or code) prevents basic (also non-MRTK) interactors to trigger a OnClick event when not hovering and ending the selection (on button release, etc.).
- Added a (default false) "RequiresHover" field to StatefulInteractable, of which the only inheritor in the package is PressableButton.
- Make that field accessible through the editor panel / inspector in Unity.
- Made changes to CanClickOnLastSelectExited method in StatefulInteractable, so that a OnClick event is only invoked when the interactable is being hovered over when RequiresHover field is set.
- Minor bugfix: add isCancelled check as well - when …

add RequiresHover field to StatefulInteractable

---

com.microsoft.mrtk.uxcore/StateVisualizer/Effects/AnimationEffect.cs

Bug: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11436
DrawIf operates on the object being serialized. In this case, we have a StateVisualizer that is being serialized, which contains a simple serializable class: AnimationEffect. AnimationEffect makes use of 'drawif' referencing one of its members, but AnimationEffect is not a monobehavior and will only ever be serialized in the context of another object. In this case, StateVisualizer. When the DrawIf attribute code is invoked, it looks for the specified property name (weightMode) on the object being serialized (a StateVisualizer) and throws an error because that doesn't exist.
-BUG 11436 remove DrawIf usage from AnimationEffect

BUG 11436 remove DrawIf usage from AnimationEffect

---

Assets/MRTK/Extensions/LostTrackingService/LostTrackingService.cs

OpenXR implementation is less likely to drop all the way to TrackingState.None when the XR device has lost its tracking.
- Fixes: #11340 - Splash image is not set when tracking is lost in hololens.
I only tested this code in HoloLens 2, but I think it is harmless for all other XR devices, as it is less restrictive.

Fixes #11340 - Splash image is not set when tracking is lost in hololens

---

com.microsoft.mrtk.input/Simulation/InputSimulator.cs

Rotating the simulated hand also results in the hand's position moving. This makes it very difficult to rotate objects accurately without them also moving off screen. MRTK 2 would lock the position of the hand when it was rotating. This PR changes the InputSimulator.cs script to mirror the same behavior.
- Fixes part of: #10789

Lock position of hand when rotating in simulator

---

com.microsoft.mrtk.input/Simulation/InputSimulator.cs

My last PR broke the "Face the Camera" action on the InputSimulator as the hand rotation mode was not set unless the manual keys were being pressed. This moves the rotation mode logic outside of the manual control check.
- Fixes: #10789

Fix input simulator Face Camera action

---

com.microsoft.mrtk.input/Interactors/Speech/SpeechInteractor.cs

Update the SpeechInteractor component so that voice commands are enabled when an interactable isHovered instead of IsGazeHovered. Allows the use of voice commands with far rays, pinch interactors.

Voice Commands When Interactable isHovered

---

Pipelines/Config/settings.yaml
UnityProjects/MRTKDevTemplate/ProjectSettings/ProjectSettings.asset

Updating release tag to pre.14 to match the latest published version of MRTK3
Version was updated using MRTK3's helper script:
` .\edit-version.ps1 -NewPreview pre.14`

Updating release tag to pre.14 to match the latest published version of MRTK3

---

com.microsoft.mrtk.spatialmanipulation/ObjectManipulator/MoveLogics/ScaleLogic.cs

Change ScaleLogic.cs to scale relative to the distance between two interactors instead of the distance between their attach points.
- Fixes: #11208.
>
>
> …

Fix 11208: Scale relative to the position of the interactors, not the attach points

---

com.microsoft.mrtk.uxcore/ScrollRect/VirtualizedScrollRectList.cs

When VirtualizedScrollRectList is initialized, the pool size is always being set to the number of items that could possibly be visible on the screen. EX For a 3x3 grid, the Scroll Rect content will always have 15 GameObjects, even if the item count is lower. VirtualizedScrollRectList 'recycles' these GameObjects to display the information for the item that is in view, relying on the user to (re)set the information upon the OnVisible event. This information is not cleared when the item becomes invisible and the GameObject is not disabled.
The result is that scrolling down and then back up on lists of a certain size will result in duplicate items: when it scrolls up it pulls a new GameObject out of the pool and adds the item information, while the old GameObject is still there, …

Fixing edge case duplication bug in VirtualizedScrollRectList

---

com.microsoft.mrtk.spatialmanipulation/Solvers/SolverHandler.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/SolverHandlerTests.cs

Fixes SolverHandler issues when handedness flag is set to `Everything` (i.e. 0xFFFFFFFF or -1)
When selecting `Everything` in the inspector, the serialized value gets set to -1 (or 0xFFFFFFFF) and not 0x3.  Because of the way `SolverHandler` was checking the handedness flag, this caused bug #11398.  
This change updates `SolverHandler` to use the `&` operator to correctly check for `handiness` including both `Left` and `Right` flags. 
The change also resolves the _TODO_ in `SolverHandler.IsHandTracked`.  The `XRSubsystemHelpers.HandsAggregator.TryGetJoint(...)` now appears to be correctly returning `false` when the joint is not found, and `true` when it is.  Prior to resolving the _TODO_ in `IsHandTracked`, `IsHandTracked` would always return true if there was a hand tracking system.  As …

Fixes SolverHandler issues when handedness flag is set to "everything" (i.e. 0xFFFFFFFF or -1)

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/TapToPlaceExample.unity
com.microsoft.mrtk.spatialmanipulation/Editor/Solvers/TapToPlaceEditor.cs
com.microsoft.mrtk.spatialmanipulation/Solvers/TapToPlace.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs
com.microsoft.mrtk.spatialmanipulation/Tests/Runtime/SolverTapToPlaceTests.cs.meta

Fixes MRTK3's `Tap to Place` solver to work with any hand and any interactor (even speech). This change, on `StartPlacement`, queries the `XRInteractionManager` for all registered interactors, and then registers for the interactors' select events.  This is an alternative to requiring the developer to specify particular actions. 
Note, this change also removes the `StatefulInteractable` requirement.  The consumer of `TapToPlace` is now required to determine when `StartPlacement` is invoked. This change is meant to provide extensibility for future scenarios which may not require or use `StatefulInteractables`.
This also adds Unit Tests to validate `TapToPlace`.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11527
> This optional section is a place where you can …

Fixes MRTK3's `Tap to Place` solver to work with any hand and interactor

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/NonCanvasDialogExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/NonCanvasDialogExample.unity.meta
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/Dialog_168x140mm.prefab
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/Dialog_168x88mm.prefab
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogAnimator.controller
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogAnimator.controller.meta
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogDismiss.anim
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogDismiss.anim.meta
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogShow.anim
com.microsoft.mrtk.uxcomponents.noncanvas/Dialog/NonCanvasDialogShow.anim.meta
com.microsoft.mrtk.uxcomponents.noncanvas/Tests/Runtime/DialogTests.cs
com.microsoft.mrtk.uxcomponents.noncanvas/Tests/Runtime/MRTK.UXComponents.NonCanvas.RuntimeTests.asmdef

Replace deprecated dialog component with new `Dialog` component and add appropriate animations.  The old deprecated `Dialog` component is still in the code base, but might be removed at a later date.
This also updates the non-canvas unit tests to use similar tests as the canvas dialogs.
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11547

Update Non-Canvas Dialog Prefab

---

UnityProjects/.gitignore

This change updates the `.gitignore` file in this Unity projects directory, so to ignore scenes generated by Unity's test runner.

Updating gitignore in Unity projects dir, so to ignore scenes generated by Unity's test runner

---

com.microsoft.mrtk.input/Interactors/InteractorVisuals/MRTKRayReticleVisual.cs

The graphics tools ProximityLight class updates in LateUpdate().  This moves positioning of the reticle and prox light to Update() to make sure the position changes happen before ProximityLight.cs updates the shader parameters.
- Fixes: #10933  .
>
>
> …

Fix execution order with ProximityLights

---

com.microsoft.mrtk.uxcomponents/Keyboard/NonNativeKeyboard/NonNativeKeyboard.prefab

There's noticeable z-fighting in the keyboard preview text box on the non-native keyboard prefab. This change fixed that.

Fixing z flighting in non native keyboard when using 16bit depth buffer

---

com.microsoft.mrtk.uxcomponents/Keyboard/NonNativeKeyboard/NonNativeKeyboard.prefab

Updates the keyboard to use sprites from the MRTK Standard Assets package.
- Fixes: #11606 .

Update NonNativeKeyboard Sprite References

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/ScrollRectCurve.cs
com.microsoft.mrtk.core/Camera/CameraSettings.cs
com.microsoft.mrtk.core/Data/Binding Templates/UXBindingProfileTemplate.cs
com.microsoft.mrtk.core/Interactables/StatefulInteractable.cs
com.microsoft.mrtk.core/Subsystems/MRTKSubsystemProvider.cs
com.microsoft.mrtk.core/Utilities/Attributes/LabelWidthAttribute.cs
com.microsoft.mrtk.core/Utilities/Extensions/MathfExtensions.cs
com.microsoft.mrtk.core/Utilities/Extensions/VectorExtensions.cs
com.microsoft.mrtk.core/Utilities/RayStep.cs
com.microsoft.mrtk.core/Utilities/SystemInterfaceType.cs
com.microsoft.mrtk.core/Utilities/SystemType.cs
com.microsoft.mrtk.core/Utilities/TimedFlag.cs
com.microsoft.mrtk.input/Editor/Inspectors/InteractionModeManagerEditor.cs
com.microsoft.mrtk.input/Editor/Inspectors/InteractionModePropertyDrawer.cs
com.microsoft.mrtk.input/InteractionModes/InteractionMode.cs
com.microsoft.mrtk.input/InteractionModes/InteractionModeDefinition.cs
com.microsoft.mrtk.input/InteractionModes/InteractionModeManager.cs
com.microsoft.mrtk.input/Interactors/Gaze/FuzzyGazeInteractor.cs
com.microsoft.mrtk.input/Interactors/HandJointInteractor.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/Lines/DataProviders/BezierDataProvider.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/Lines/DataProviders/BezierInertia.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/Lines/Definitions/InterpolationType.cs
com.microsoft.mrtk.input/Subsystems/HandsAggregator/MRTKHandsAggregatorSubsystem.cs
com.microsoft.mrtk.input/Utilities/HandshapeTypes.cs
com.microsoft.mrtk.input/Utilities/PoseSource/InputActionPoseSource.cs
com.microsoft.mrtk.spatialmanipulation/Solvers/SurfaceMagnetism.cs
com.microsoft.mrtk.spatialmanipulation/Solvers/TapToPlace.cs
com.microsoft.mrtk.uxcore/Keyboard/KeyboardPreview.cs

Adding in some missing documentation to the MRTK3 source.  
This also replaces some `ref` parameters with `in` parameters, in cases where it was obvious that only "const refs" were needed.  This also removed the `InterpolationType.Hermite` since it was never handled or used.
The following were documentated:
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11596
- https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11590

Adding in some missing documentation to the MRTK3 source.

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/Experimental/NonNativeKeyboard.unity
com.microsoft.mrtk.uxcomponents/Experimental/NonNativeKeyboard/NonNativeKeyboard.prefab

Fixing z-fighting in MRTK3's non native keyboard prefab
- Fixes: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/11657

Fixing z-fighting in MRTK3's non native keyboard prefab

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/DictationHandler.cs

Adds logic to start and stop the speech recognition subsystem in the dictation example scene, so that both speech recognition and dictation can work in the scene. 
Known issue: Dictation will not work if app is closed and reopened #11695.
- Fixes: #11690.

Update DictationHandler Example Script to work with SpeechRecognitionSubsystem

---

com.microsoft.mrtk.spatialmanipulation/BoundsControl/BoundsHandleInteractable.cs
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/RotateHandle.prefab
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/ScaleHandleOcclusion.prefab
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Prefabs/ScaleHandleTraditional.prefab
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Visuals/SqueezableBoxVisuals.cs

Fixes a bug in which bounding box handles would not appear after a GO was disabled. Problem caused by Animator behavior described [here](https://forum.unity.com/threads/animator-default-values-can-change-through-the-animations-itself.509668/), solved by setting WriteDefaultValuesOnDisable to true, and adding logic to occlude the handles on start up. 
Removes unused private variable initialLocalScale.
- Fixes: #11655.

Fix BoundsControl Bug

---

com.microsoft.mrtk.input/Experimental/SpatialMouse/Interactor/SpatialMouseInteractorCursorVisual.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/Lines/LineUtility.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/MRTKLineVisual.cs
com.microsoft.mrtk.input/Interactors/InteractorVisuals/MRTKRayReticleVisual.cs
com.microsoft.mrtk.input/Interactors/XRRayInteractorExtensions.cs
com.microsoft.mrtk.input/Interactors/XRRayInteractorExtensions.cs.meta
com.microsoft.mrtk.spatialmanipulation/BoundsControl/Visuals/SqueezableBoxVisuals.cs

Consolidating the three LocateTargetHitPoint methods into one, a static helper which lives in the LineUtility class. This will take an XRRayInteractor and an IXRSelectInteractable, and will return the target local hit point, target local hit normal, target transform, and a reference point for calculating hit distance. 
- Fixes: #11649.

Consolidate LocateTargetHitPoint methods

---

UnityProjects/MRTKDevTemplate/Assets/Prefabs/EyeTrackingExamples/Visualizer/Controls.prefab
UnityProjects/MRTKDevTemplate/Assets/Scenes/EyeTracking/EyeTrackingTargetPositioningExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scripts/DisableInteractors.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/EyeTrackingUtilities.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/ScrollPanZoom/PanZoomBaseTexture.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/ScrollPanZoom/PanZoomTexture.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/ScrollPanZoom/ScrollRectTransform.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/TargetPositioning/MoveObjectByEyeGaze.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/TargetPositioning/ObjectGoalZone.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/Visualizer/DrawOnTexture.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/Visualizer/UserInputRecorder.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/InteractorBehaviorControls.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/PenInteractor.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/SolverExampleManager.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/SpeechKeywordRecognitionHandler.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/TextToSpeechHandler.cs
UnityProjects/MRTKDevTemplate/Assets/UX Theming Example/Scripts/BatteryLevelDataSource.cs
UnityProjects/MRTKDevTemplate/Assets/UX Theming Example/Themes/MusicInformationProfile.cs
com.microsoft.mrtk.data/Runtime/Scripts/DataConsumers/DataConsumerCommandDispatcher.cs
com.microsoft.mrtk.data/Runtime/Scripts/DataConsumers/DataConsumerThemableBase.cs
com.microsoft.mrtk.data/Runtime/Scripts/DataConsumers/DataConsumerThemeHelper.cs
com.microsoft.mrtk.data/Runtime/Scripts/Interfaces/IDataNode.cs
com.microsoft.mrtk.data/Runtime/Scripts/Interfaces/IDataSource.cs
com.microsoft.mrtk.input/Editor/Inspectors/CameraSimulationSettingsDrawer.cs
com.microsoft.mrtk.input/Tests/Runtime/Utilities/InputTestUtilities.cs
com.microsoft.mrtk.uxcomponents.noncanvas/Experimental/Theming/ProfileTemplates/UXThemeProfile.cs
com.microsoft.mrtk.windowsspeech/Subsystems/TextToSpeech/TextToSpeechHelpers.cs

Fixing some additional XML documentation warnings that were missed in the previous 2 passes.
This is also fixing some spellings of variables in the new set of example scripts.

Fixing XML documentation warnings and some variable spellings, pass 3

---

UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/EyeTrackingUtilities.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/TargetPositioning/MoveObjectByEyeGaze.cs
UnityProjects/MRTKDevTemplate/Assets/Scripts/EyeTracking/Visualizer/DrawOnTexture.cs

Fixing XML Documentation warnings. Pass 4

Fixing XML Documentation warnings. Pass 4

---

UnityProjects/MRTKDevTemplate/Assets/Scenes/DwellExample.unity
UnityProjects/MRTKDevTemplate/Assets/Scenes/TextToSpeechExamples.unity

Center logo on back of description, add spatial audio to the voices in TextToSpeechExamples (Fix #11729)
Change handmenu in scene to SampleHandMenu prefab
- Fixes: #11729 
>
>
>
> git fetch …

TextToSpeech example fixes

---

com.microsoft.mrtk.uxcomponents.noncanvas/Tests/Runtime/SliderTests.cs
com.microsoft.mrtk.uxcore/Slider/Slider.cs
com.microsoft.mrtk.uxcore/Slider/Visuals/CanvasSliderVisuals.cs

Uses normalized instead of actual value in order to correct slider visuals for ranges other than 0-1. Also, makes a change to pull the normalized value on slider movement, and then convert to the actual value, in order to avoid undesirable behavior where it is slower to move the slider for larger ranges.  
- Fixes: #11718.

Fix Slider to Support Non-Default Range

---

com.microsoft.mrtk.input/Assets/Prefabs/MRTK XR Rig.prefab
com.microsoft.mrtk.input/Editor/Inspectors/UnboundedTrackingModeInspector.cs
com.microsoft.mrtk.input/Editor/Inspectors/UnboundedTrackingModeInspector.cs.meta
com.microsoft.mrtk.input/Editor/MRTK.Input.Editor.asmdef
com.microsoft.mrtk.input/MRTK.Input.asmdef
com.microsoft.mrtk.input/Tracking.meta
com.microsoft.mrtk.input/Tracking/UnboundedTrackingMode.cs
com.microsoft.mrtk.input/Tracking/UnboundedTrackingMode.cs.meta

The `Microsoft.MixedReality.OpenXR.EyeLevelSceneOrigin` component in Microsoft's MR OpenXR plugin will soon be deprecated (so to avoid having mono behaviours within this plugin).  Also, Unity doesn't have UI to set the tracking mode to `TrackingOriginModeFlags.Unbounded` on the `XRInputSubsystem`.
So, to replace  `Microsoft.MixedReality.OpenXR.EyeLevelSceneOrigin`, an `UnboundedTrackingMode` MonoBehaviour has been added to MRTK3. This behavior has been applied to MRTK's XR Rig and will force HL2 into unbounded mode if Unity's `XROrigin.RequestedTrackingOriginMode` is set to "Not Specified". If the platform does not support unbounded mode, the new behavior does nothing.
Unbounded mode is preferred on HL2 (the only device currently supporting this mode).
For more information on unbounded …

[MRTK3] Adding support for unbounded tracking mode

---

Assets/MRTK/Core/Inspectors/MixedRealityToolkitFacadeHandler.cs
Assets/MRTK/Core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
Assets/MRTK/Core/Inspectors/PropertyDrawers/SceneInfoUtils.cs
Assets/MRTK/Core/MRTK.Core.asmdef
Assets/MRTK/Core/Services/MixedRealityToolkit.cs
Assets/MRTK/Core/Utilities/Async/Internal/AsyncCoroutineRunner.cs
Assets/MRTK/Core/Utilities/Async/MRTK.Async.asmdef
Assets/MRTK/Core/Utilities/CameraCache.cs
Assets/MRTK/Core/Utilities/FindObjectUtility.cs
Assets/MRTK/Core/Utilities/FindObjectUtility.cs.meta
Assets/MRTK/Examples/Demos/EyeTracking/DemoVisualizer/Scripts/UserInputRecorder.cs
Assets/MRTK/Examples/Demos/EyeTracking/General/Scripts/Utils/StatusText.cs
Assets/MRTK/Extensions/SceneTransitionService/SceneTransitionService.cs
Assets/MRTK/Providers/Oculus/XRSDK/OculusXRSDKDeviceManager.cs
Assets/MRTK/SDK/Editor/Migration/BoundsControlMigrationHandler.cs
Assets/MRTK/SDK/Experimental/Features/Utilities/WorldAnchorManager.cs
Assets/MRTK/SDK/Experimental/ServiceManagers/Input/Scripts/InputSystemManager.cs
Assets/MRTK/Services/InputSystem/MixedRealityInputSystem.cs
Assets/MRTK/Services/TeleportSystem/MixedRealityTeleportSystem.cs
Assets/MRTK/Tests/EditModeTests/Core/MixedRealityToolkitTests.cs
Assets/MRTK/Tests/PlayModeTests/BaseCursorTests.cs
Assets/MRTK/Tests/PlayModeTests/ChangeActiveProfileTests.cs
Assets/MRTK/Tests/PlayModeTests/Core/Providers/Hands/RiggedHandVisualizerTests.cs
Assets/MRTK/Tests/PlayModeTests/Core/Utilities/Async/AsyncCoroutineRunnerTests.cs
Assets/MRTK/Tests/TestUtilities/PlayModeTestUtilities.cs
Assets/MRTK/Tests/TestUtilities/TestUtilities.cs
Assets/MRTK/Tools/OptimizeWindow/MixedRealityOptimizeWindow.cs
Assets/MRTK/Tools/Toolbox/MixedRealityToolboxWindow.cs

Adds precompile statements to avoid calling deprecated FindObject functions.

Add Precompile Statements to Prevent Warnings in Unity 2023
